UPDATE words w SET image_url = v.u
FROM (VALUES
('feel','','https://train.wowteach.ru/media/spotlight4/feel.webp'),
('hope','','https://train.wowteach.ru/media/spotlight4/hope.webp'),
('join','','https://train.wowteach.ru/media/spotlight4/join.webp'),
('worry','','https://train.wowteach.ru/media/spotlight4/worry.webp'),
('hate','','https://train.wowteach.ru/media/spotlight4/hate.webp'),
('wait','','https://train.wowteach.ru/media/spotlight4/wait.webp'),
('check','','https://train.wowteach.ru/media/spotlight4/check.webp'),
('return','','https://train.wowteach.ru/media/spotlight4/return.webp'),
('take care of','','https://train.wowteach.ru/media/spotlight4/take_care_of.webp'),
('back together','','https://train.wowteach.ru/media/spotlight4/back_together.webp'),
('both','','https://train.wowteach.ru/media/spotlight4/both.webp'),
('same','','https://train.wowteach.ru/media/spotlight4/same.webp'),
('stick together','','https://train.wowteach.ru/media/spotlight4/stick_together.webp'),
('What does he look like?','','https://train.wowteach.ru/media/spotlight4/look_like.webp'),
('What''s he like?','','https://train.wowteach.ru/media/spotlight4/what_is_he_like.webp'),
('naughty','','https://train.wowteach.ru/media/spotlight4/naughty.webp'),
('horrid','','https://train.wowteach.ru/media/spotlight4/horrid.webp'),
('fun-loving','','https://train.wowteach.ru/media/spotlight4/fun_loving.webp'),
('always','','https://train.wowteach.ru/media/spotlight4/always.webp'),
('usually','','https://train.wowteach.ru/media/spotlight4/usually.webp'),
('sometimes','','https://train.wowteach.ru/media/spotlight4/sometimes.webp'),
('never','','https://train.wowteach.ru/media/spotlight4/never.webp'),
('week','','https://train.wowteach.ru/media/spotlight4/week.webp'),
('soon','','https://train.wowteach.ru/media/spotlight4/soon.webp'),
('for a while','','https://train.wowteach.ru/media/spotlight4/for_a_while.webp'),
('free time','','https://train.wowteach.ru/media/spotlight4/free_time.webp'),
('rest','','https://train.wowteach.ru/media/spotlight4/rest.webp'),
('make sure','','https://train.wowteach.ru/media/spotlight4/make_sure.webp'),
('pass','u5','https://train.wowteach.ru/media/spotlight4/pass_give.webp'),
('treat','','https://train.wowteach.ru/media/spotlight4/treat.webp'),
('simple','','https://train.wowteach.ru/media/spotlight4/simple.webp'),
('almost','','https://train.wowteach.ru/media/spotlight4/almost.webp'),
('at least','','https://train.wowteach.ru/media/spotlight4/at_least.webp'),
('last a long time','','https://train.wowteach.ru/media/spotlight4/last_a_long_time.webp'),
('surprise','','https://train.wowteach.ru/media/spotlight4/surprise.webp'),
('activity','','https://train.wowteach.ru/media/spotlight4/activity.webp'),
('Happy New Year!','','https://train.wowteach.ru/media/spotlight4/Happy_New_Year.webp'),
('Congratulations!','','https://train.wowteach.ru/media/spotlight4/Congratulations.webp'),
('Bon voyage!','','https://train.wowteach.ru/media/spotlight4/Bon_voyage.webp'),
('Nice to meet you.','','https://train.wowteach.ru/media/spotlight4/Nice_to_meet_you.webp'),
('See you later.','','https://train.wowteach.ru/media/spotlight4/See_you_later.webp'),
('Thank you. — You''re welcome.','','https://train.wowteach.ru/media/spotlight4/Thank_you.webp'),
('It''s your turn','','https://train.wowteach.ru/media/spotlight4/your_turn.webp'),
('Excuse me, where''s ...?','','https://train.wowteach.ru/media/spotlight4/Excuse_me.webp'),
('resolution','','https://train.wowteach.ru/media/spotlight4/resolution.webp'),
('in a hurry','','https://train.wowteach.ru/media/spotlight4/in_a_hurry.webp'),
('on my way','','https://train.wowteach.ru/media/spotlight4/on_my_way.webp'),
('luck','','https://train.wowteach.ru/media/spotlight4/luck.webp'),
('mine','','https://train.wowteach.ru/media/spotlight4/mine.webp'),
('never mind','','https://train.wowteach.ru/media/spotlight4/never_mind.webp'),
('pass','u11','https://train.wowteach.ru/media/spotlight4/pass_go_by.webp'),
('a whale of a time','','https://train.wowteach.ru/media/spotlight4/a_whale_of_a_time.webp'),
('it is worth it','','https://train.wowteach.ru/media/spotlight4/worth_it.webp'),
('pull down','','https://train.wowteach.ru/media/spotlight4/pull_down.webp'),
('adopt','','https://train.wowteach.ru/media/spotlight4/adopt.webp'),
('donate','','https://train.wowteach.ru/media/spotlight4/donate.webp'),
('raise','','https://train.wowteach.ru/media/spotlight4/raise.webp'),
('millionaire','','https://train.wowteach.ru/media/spotlight4/millionaire.webp'),
('sound','','https://train.wowteach.ru/media/spotlight4/sound.webp'),
('is called','','https://train.wowteach.ru/media/spotlight4/is_called.webp'),
('project','','https://train.wowteach.ru/media/spotlight4/project.webp')) AS v(t, k, u), word_decks d, deck_folders f
WHERE w.term = v.t AND w.image_url IS NULL AND d.id = w.deck_id AND f.id = d.folder_id
  AND f.parent_folder_id = (SELECT id FROM deck_folders WHERE title = 'Spotlight 4' AND deleted_at IS NULL)
  AND (v.k = '' OR (v.k = 'meal' AND d.title LIKE 'Unit 6%') OR (v.k = 'rhyme' AND d.title LIKE 'Culture Corner 6%')
       OR (v.k = 'u5' AND d.title LIKE 'Unit 5:%') OR (v.k = 'u11' AND d.title LIKE 'Unit 11:%'))
RETURNING w.id;