UPDATE words w SET image_url = v.u
FROM (VALUES
('CD','','https://train.wowteach.ru/media/spotlight4/CD.webp'),
('glove','','https://train.wowteach.ru/media/spotlight4/glove.webp'),
('hairbrush','','https://train.wowteach.ru/media/spotlight4/hairbrush.webp'),
('key','','https://train.wowteach.ru/media/spotlight4/key.webp'),
('roller blades','','https://train.wowteach.ru/media/spotlight4/roller_blades.webp'),
('play the violin','','https://train.wowteach.ru/media/spotlight4/play_the_violin.webp'),
('ski','','https://train.wowteach.ru/media/spotlight4/ski.webp'),
('surf','','https://train.wowteach.ru/media/spotlight4/surf.webp'),
('crew','','https://train.wowteach.ru/media/spotlight4/crew.webp'),
('plump','','https://train.wowteach.ru/media/spotlight4/plump.webp'),
('baker','','https://train.wowteach.ru/media/spotlight4/baker.webp'),
('greengrocer','','https://train.wowteach.ru/media/spotlight4/greengrocer.webp'),
('postman','','https://train.wowteach.ru/media/spotlight4/postman.webp'),
('taxi driver','','https://train.wowteach.ru/media/spotlight4/taxi_driver.webp'),
('zoo keeper','','https://train.wowteach.ru/media/spotlight4/zoo_keeper.webp'),
('astronaut','','https://train.wowteach.ru/media/spotlight4/astronaut.webp'),
('street performer','','https://train.wowteach.ru/media/spotlight4/street_performer.webp'),
('carry','','https://train.wowteach.ru/media/spotlight4/carry.webp'),
('clean','','https://train.wowteach.ru/media/spotlight4/clean.webp'),
('curtain','','https://train.wowteach.ru/media/spotlight4/curtain.webp'),
('injection','','https://train.wowteach.ru/media/spotlight4/injection.webp'),
('play sports','','https://train.wowteach.ru/media/spotlight4/play_sports.webp'),
('wake (up)','','https://train.wowteach.ru/media/spotlight4/wake_up.webp'),
('meal','','https://train.wowteach.ru/media/spotlight4/meal.webp'),
('dinner','','https://train.wowteach.ru/media/spotlight4/dinner.webp'),
('parcel','','https://train.wowteach.ru/media/spotlight4/parcel.webp'),
('pineapple','','https://train.wowteach.ru/media/spotlight4/pineapple.webp'),
('tomato','','https://train.wowteach.ru/media/spotlight4/tomato.webp'),
('cherry','','https://train.wowteach.ru/media/spotlight4/cherry.webp'),
('onion','','https://train.wowteach.ru/media/spotlight4/onion.webp'),
('olive oil','','https://train.wowteach.ru/media/spotlight4/olive_oil.webp'),
('basket','','https://train.wowteach.ru/media/spotlight4/basket.webp'),
('oats','','https://train.wowteach.ru/media/spotlight4/oats.webp'),
('beef','','https://train.wowteach.ru/media/spotlight4/beef.webp'),
('lamb','meal','https://train.wowteach.ru/media/spotlight4/lamb_meat.webp'),
('bar','','https://train.wowteach.ru/media/spotlight4/bar.webp'),
('carton','','https://train.wowteach.ru/media/spotlight4/carton.webp'),
('jar','','https://train.wowteach.ru/media/spotlight4/jar.webp'),
('kilo','','https://train.wowteach.ru/media/spotlight4/kilo.webp'),
('loaf','','https://train.wowteach.ru/media/spotlight4/loaf.webp'),
('packet','','https://train.wowteach.ru/media/spotlight4/packet.webp'),
('tin','','https://train.wowteach.ru/media/spotlight4/tin.webp'),
('dairy','','https://train.wowteach.ru/media/spotlight4/dairy.webp'),
('yogurt','','https://train.wowteach.ru/media/spotlight4/yogurt.webp'),
('cookie','','https://train.wowteach.ru/media/spotlight4/cookie.webp'),
('French fries','','https://train.wowteach.ru/media/spotlight4/French_fries.webp'),
('paella','','https://train.wowteach.ru/media/spotlight4/paella.webp'),
('sushi','','https://train.wowteach.ru/media/spotlight4/sushi.webp'),
('snack','','https://train.wowteach.ru/media/spotlight4/snack.webp'),
('fast food','','https://train.wowteach.ru/media/spotlight4/fast_food.webp'),
('porridge','','https://train.wowteach.ru/media/spotlight4/porridge.webp'),
('pancake','','https://train.wowteach.ru/media/spotlight4/pancake.webp'),
('cookery book','','https://train.wowteach.ru/media/spotlight4/cookery_book.webp'),
('bread pudding','','https://train.wowteach.ru/media/spotlight4/bread_pudding.webp'),
('dessert','','https://train.wowteach.ru/media/spotlight4/dessert.webp'),
('jam tart','','https://train.wowteach.ru/media/spotlight4/jam_tart.webp'),
('lemon meringue','','https://train.wowteach.ru/media/spotlight4/lemon_meringue.webp'),
('ingredients','','https://train.wowteach.ru/media/spotlight4/ingredients.webp'),
('birthday boy','','https://train.wowteach.ru/media/spotlight4/birthday_boy.webp'),
('birthday girl','','https://train.wowteach.ru/media/spotlight4/birthday_girl.webp'),
('decoration','','https://train.wowteach.ru/media/spotlight4/decoration.webp'),
('zoo','','https://train.wowteach.ru/media/spotlight4/zoo.webp'),
('carnivore','','https://train.wowteach.ru/media/spotlight4/carnivore.webp'),
('herbivore','','https://train.wowteach.ru/media/spotlight4/herbivore.webp'),
('omnivore','','https://train.wowteach.ru/media/spotlight4/omnivore.webp'),
('cuckoo','','https://train.wowteach.ru/media/spotlight4/cuckoo.webp'),
('elephant seal','','https://train.wowteach.ru/media/spotlight4/elephant_seal.webp'),
('bison','','https://train.wowteach.ru/media/spotlight4/bison.webp'),
('hare','','https://train.wowteach.ru/media/spotlight4/hare.webp'),
('bumblebee','','https://train.wowteach.ru/media/spotlight4/bumblebee.webp'),
('camel','','https://train.wowteach.ru/media/spotlight4/camel.webp'),
('geese','','https://train.wowteach.ru/media/spotlight4/geese.webp'),
('lamb','rhyme','https://train.wowteach.ru/media/spotlight4/lamb.webp'),
('fleece','','https://train.wowteach.ru/media/spotlight4/fleece.webp'),
('bark','','https://train.wowteach.ru/media/spotlight4/bark.webp'),
('national park','','https://train.wowteach.ru/media/spotlight4/national_park.webp'),
('reserve','','https://train.wowteach.ru/media/spotlight4/reserve.webp'),
('wood','','https://train.wowteach.ru/media/spotlight4/wood.webp'),
('beanstalk','','https://train.wowteach.ru/media/spotlight4/beanstalk.webp'),
('break a rule','','https://train.wowteach.ru/media/spotlight4/break_a_rule.webp'),
('curl','','https://train.wowteach.ru/media/spotlight4/curl.webp'),
('fair','','https://train.wowteach.ru/media/spotlight4/fair.webp'),
('inside','','https://train.wowteach.ru/media/spotlight4/inside.webp'),
('outside','','https://train.wowteach.ru/media/spotlight4/outside.webp'),
('knock','','https://train.wowteach.ru/media/spotlight4/knock.webp'),
('tune','','https://train.wowteach.ru/media/spotlight4/tune.webp'),
('drum','','https://train.wowteach.ru/media/spotlight4/drum.webp'),
('scary film','','https://train.wowteach.ru/media/spotlight4/scary_film.webp'),
('journey','','https://train.wowteach.ru/media/spotlight4/journey.webp'),
('go to the lake','','https://train.wowteach.ru/media/spotlight4/go_to_the_lake.webp'),
('go to the mountains','','https://train.wowteach.ru/media/spotlight4/go_to_the_mountains.webp'),
('go to the seaside','','https://train.wowteach.ru/media/spotlight4/go_to_the_seaside.webp'),
('flippers','','https://train.wowteach.ru/media/spotlight4/flippers.webp'),
('swimming trunks','','https://train.wowteach.ru/media/spotlight4/swimming_trunks.webp'),
('sandy','','https://train.wowteach.ru/media/spotlight4/sandy.webp'),
('cloudy','','https://train.wowteach.ru/media/spotlight4/cloudy.webp'),
('rainy','','https://train.wowteach.ru/media/spotlight4/rainy.webp'),
('theme park','','https://train.wowteach.ru/media/spotlight4/theme_park.webp'),
('rollercoaster','','https://train.wowteach.ru/media/spotlight4/rollercoaster.webp'),
('ride','','https://train.wowteach.ru/media/spotlight4/ride.webp'),
('carnival','','https://train.wowteach.ru/media/spotlight4/carnival.webp'),
('parade','','https://train.wowteach.ru/media/spotlight4/parade.webp'),
('fireworks','','https://train.wowteach.ru/media/spotlight4/fireworks.webp'),
('April Fool''s Day','','https://train.wowteach.ru/media/spotlight4/April_Fool_s_Day.webp'),
('throw','','https://train.wowteach.ru/media/spotlight4/throw.webp'),
('finish line','','https://train.wowteach.ru/media/spotlight4/finish_line.webp'),
('capital (city)','','https://train.wowteach.ru/media/spotlight4/capital.webp'),
('monument','','https://train.wowteach.ru/media/spotlight4/monument.webp'),
('sight','','https://train.wowteach.ru/media/spotlight4/sight.webp'),
('spaceship','','https://train.wowteach.ru/media/spotlight4/spaceship.webp'),
('oval','','https://train.wowteach.ru/media/spotlight4/oval.webp'),
('world','','https://train.wowteach.ru/media/spotlight4/world.webp'),
('calendar','','https://train.wowteach.ru/media/spotlight4/calendar.webp'),
('yesterday','','https://train.wowteach.ru/media/spotlight4/yesterday.webp'),
('diploma','','https://train.wowteach.ru/media/spotlight4/diploma.webp'),
('Canada','','https://train.wowteach.ru/media/spotlight4/Canada.webp'),
('England','','https://train.wowteach.ru/media/spotlight4/England.webp'),
('Scotland','','https://train.wowteach.ru/media/spotlight4/Scotland.webp'),
('Ireland','','https://train.wowteach.ru/media/spotlight4/Ireland.webp'),
('France','','https://train.wowteach.ru/media/spotlight4/France.webp'),
('Germany','','https://train.wowteach.ru/media/spotlight4/Germany.webp'),
('Greece','','https://train.wowteach.ru/media/spotlight4/Greece.webp'),
('Poland','','https://train.wowteach.ru/media/spotlight4/Poland.webp'),
('Portugal','','https://train.wowteach.ru/media/spotlight4/Portugal.webp'),
('Japan','','https://train.wowteach.ru/media/spotlight4/Japan.webp'),
('New Zealand','','https://train.wowteach.ru/media/spotlight4/New_Zealand.webp'),
('Florida','','https://train.wowteach.ru/media/spotlight4/Florida.webp'),
('Japanese','','https://train.wowteach.ru/media/spotlight4/Japanese.webp'),
('Athens','','https://train.wowteach.ru/media/spotlight4/Athens.webp'),
('Madrid','','https://train.wowteach.ru/media/spotlight4/Madrid.webp'),
('Moscow','','https://train.wowteach.ru/media/spotlight4/Moscow.webp'),
('Paris','','https://train.wowteach.ru/media/spotlight4/Paris.webp'),
('Rome','','https://train.wowteach.ru/media/spotlight4/Rome.webp'),
('Coliseum','','https://train.wowteach.ru/media/spotlight4/Coliseum.webp'),
('feel','','https://train.wowteach.ru/media/spotlight4/feel.webp'),
('hope','','https://train.wowteach.ru/media/spotlight4/hope.webp'),
('join','','https://train.wowteach.ru/media/spotlight4/join.webp'),
('worry','','https://train.wowteach.ru/media/spotlight4/worry.webp'),
('hate','','https://train.wowteach.ru/media/spotlight4/hate.webp'),
('wait','','https://train.wowteach.ru/media/spotlight4/wait.webp'),
('check','','https://train.wowteach.ru/media/spotlight4/check.webp'),
('return','','https://train.wowteach.ru/media/spotlight4/return.webp'),
('take care of','','https://train.wowteach.ru/media/spotlight4/take_care_of.webp'),
('back together','','https://train.wowteach.ru/media/spotlight4/back_together.webp'),
('both','','https://train.wowteach.ru/media/spotlight4/both.webp'),
('same','','https://train.wowteach.ru/media/spotlight4/same.webp'),
('stick together','','https://train.wowteach.ru/media/spotlight4/stick_together.webp'),
('What does he look like?','','https://train.wowteach.ru/media/spotlight4/look_like.webp'),
('What''s he like?','','https://train.wowteach.ru/media/spotlight4/what_is_he_like.webp'),
('naughty','','https://train.wowteach.ru/media/spotlight4/naughty.webp'),
('horrid','','https://train.wowteach.ru/media/spotlight4/horrid.webp'),
('fun-loving','','https://train.wowteach.ru/media/spotlight4/fun_loving.webp'),
('always','','https://train.wowteach.ru/media/spotlight4/always.webp'),
('usually','','https://train.wowteach.ru/media/spotlight4/usually.webp'),
('sometimes','','https://train.wowteach.ru/media/spotlight4/sometimes.webp'),
('never','','https://train.wowteach.ru/media/spotlight4/never.webp'),
('week','','https://train.wowteach.ru/media/spotlight4/week.webp'),
('soon','','https://train.wowteach.ru/media/spotlight4/soon.webp'),
('for a while','','https://train.wowteach.ru/media/spotlight4/for_a_while.webp'),
('free time','','https://train.wowteach.ru/media/spotlight4/free_time.webp'),
('rest','','https://train.wowteach.ru/media/spotlight4/rest.webp'),
('make sure','','https://train.wowteach.ru/media/spotlight4/make_sure.webp'),
('pass','u5','https://train.wowteach.ru/media/spotlight4/pass_give.webp'),
('treat','','https://train.wowteach.ru/media/spotlight4/treat.webp'),
('simple','','https://train.wowteach.ru/media/spotlight4/simple.webp'),
('almost','','https://train.wowteach.ru/media/spotlight4/almost.webp'),
('at least','','https://train.wowteach.ru/media/spotlight4/at_least.webp'),
('last a long time','','https://train.wowteach.ru/media/spotlight4/last_a_long_time.webp'),
('surprise','','https://train.wowteach.ru/media/spotlight4/surprise.webp'),
('activity','','https://train.wowteach.ru/media/spotlight4/activity.webp'),
('Happy New Year!','','https://train.wowteach.ru/media/spotlight4/Happy_New_Year.webp'),
('Congratulations!','','https://train.wowteach.ru/media/spotlight4/Congratulations.webp'),
('Bon voyage!','','https://train.wowteach.ru/media/spotlight4/Bon_voyage.webp'),
('Nice to meet you.','','https://train.wowteach.ru/media/spotlight4/Nice_to_meet_you.webp'),
('See you later.','','https://train.wowteach.ru/media/spotlight4/See_you_later.webp'),
('Thank you. — You''re welcome.','','https://train.wowteach.ru/media/spotlight4/Thank_you.webp'),
('It''s your turn','','https://train.wowteach.ru/media/spotlight4/your_turn.webp'),
('Excuse me, where''s ...?','','https://train.wowteach.ru/media/spotlight4/Excuse_me.webp'),
('resolution','','https://train.wowteach.ru/media/spotlight4/resolution.webp'),
('in a hurry','','https://train.wowteach.ru/media/spotlight4/in_a_hurry.webp'),
('on my way','','https://train.wowteach.ru/media/spotlight4/on_my_way.webp'),
('luck','','https://train.wowteach.ru/media/spotlight4/luck.webp'),
('mine','','https://train.wowteach.ru/media/spotlight4/mine.webp'),
('never mind','','https://train.wowteach.ru/media/spotlight4/never_mind.webp'),
('pass','u11','https://train.wowteach.ru/media/spotlight4/pass_go_by.webp'),
('a whale of a time','','https://train.wowteach.ru/media/spotlight4/a_whale_of_a_time.webp'),
('it is worth it','','https://train.wowteach.ru/media/spotlight4/worth_it.webp'),
('pull down','','https://train.wowteach.ru/media/spotlight4/pull_down.webp'),
('adopt','','https://train.wowteach.ru/media/spotlight4/adopt.webp'),
('donate','','https://train.wowteach.ru/media/spotlight4/donate.webp'),
('raise','','https://train.wowteach.ru/media/spotlight4/raise.webp'),
('millionaire','','https://train.wowteach.ru/media/spotlight4/millionaire.webp'),
('sound','','https://train.wowteach.ru/media/spotlight4/sound.webp'),
('is called','','https://train.wowteach.ru/media/spotlight4/is_called.webp'),
('project','','https://train.wowteach.ru/media/spotlight4/project.webp'),
('seventy','','https://train.wowteach.ru/media/spotlight4/seventy.webp'),
('eighty','','https://train.wowteach.ru/media/spotlight4/eighty.webp'),
('ninety','','https://train.wowteach.ru/media/spotlight4/ninety.webp'),
('hundred','','https://train.wowteach.ru/media/spotlight4/hundred.webp'),
('first','','https://train.wowteach.ru/media/spotlight4/first.webp'),
('second','','https://train.wowteach.ru/media/spotlight4/second.webp'),
('third','','https://train.wowteach.ru/media/spotlight4/third.webp')) AS v(t, k, u), word_decks d, deck_folders f
WHERE w.term = v.t AND w.image_url IS NULL AND d.id = w.deck_id AND f.id = d.folder_id
  AND f.parent_folder_id = (SELECT id FROM deck_folders WHERE title = 'Spotlight 4' AND deleted_at IS NULL)
  AND (v.k = '' OR (v.k = 'meal' AND d.title LIKE 'Unit 6%') OR (v.k = 'rhyme' AND d.title LIKE 'Culture Corner 6%')
       OR (v.k = 'u5' AND d.title LIKE 'Unit 5:%') OR (v.k = 'u11' AND d.title LIKE 'Unit 11:%'))
RETURNING w.id;