-- Go Getter 1 · Unit 7 · Animals · Homework 1
-- собрано tools/gg1_build.py --lesson u7_hw1
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where title = 'Go Getter 1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 7 · Animals', 7
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 7 · Animals');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 7 · Animals';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 1', 'homework',
         60, false, 0
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 1');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 1';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Hello! 👋</h2><p>Добро пожаловать в домашнее задание! В этом уроке тебя ждут упражнения на отработку новых слов про диких животных. Выполни все, если хочешь выучить тему на все 100! А в конце тебя ждут дополнительные задания — выполнишь их, и будешь нереально крут!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"cards": [{"text": "bird", "translation": "птица", "audio_tts": "bird", "image": "@@MEDIA@@gg1/u7/animal_bird.webp"}, {"text": "butterfly", "translation": "бабочка", "audio_tts": "butterfly", "image": "@@MEDIA@@gg1/u7/animal_butterfly.webp"}, {"text": "crocodile", "translation": "крокодил", "audio_tts": "crocodile", "image": "@@MEDIA@@gg1/u7/animal_crocodile.webp"}, {"text": "elephant", "translation": "слон", "audio_tts": "elephant", "image": "@@MEDIA@@gg1/u7/animal_elephant.webp"}, {"text": "fish", "translation": "рыба", "audio_tts": "fish", "image": "@@MEDIA@@gg1/u7/animal_fish.webp"}, {"text": "fly", "translation": "муха", "audio_tts": "fly", "image": "@@MEDIA@@gg1/u7/animal_fly.webp"}, {"text": "frog", "translation": "лягушка", "audio_tts": "frog", "image": "@@MEDIA@@gg1/u7/animal_frog.webp"}, {"text": "giraffe", "translation": "жираф", "audio_tts": "giraffe", "image": "@@MEDIA@@gg1/u7/animal_giraffe.webp"}, {"text": "kangaroo", "translation": "кенгуру", "audio_tts": "kangaroo", "image": "@@MEDIA@@gg1/u7/animal_kangaroo.webp"}, {"text": "lion", "translation": "лев", "audio_tts": "lion", "image": "@@MEDIA@@gg1/u7/animal_lion.webp"}, {"text": "monkey", "translation": "обезьяна", "audio_tts": "monkey", "image": "@@MEDIA@@gg1/u7/animal_monkey.webp"}, {"text": "snake", "translation": "змея", "audio_tts": "snake", "image": "@@MEDIA@@gg1/u7/animal_snake.webp"}, {"text": "spider", "translation": "паук", "audio_tts": "spider", "image": "@@MEDIA@@gg1/u7/animal_spider.webp"}, {"text": "tiger", "translation": "тигр", "audio_tts": "tiger", "image": "@@MEDIA@@gg1/u7/animal_tiger.webp"}, {"text": "whale", "translation": "кит", "audio_tts": "whale", "image": "@@MEDIA@@gg1/u7/animal_whale.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «птица»?", "type": "single", "options": [{"text": "bird"}, {"text": "elephant"}, {"text": "butterfly"}, {"text": "crocodile"}], "correct": [0]}, {"q": "Как по-английски «бабочка»?", "type": "single", "options": [{"text": "fish"}, {"text": "butterfly"}, {"text": "elephant"}, {"text": "crocodile"}], "correct": [1]}, {"q": "Как по-английски «крокодил»?", "type": "single", "options": [{"text": "fish"}, {"text": "elephant"}, {"text": "crocodile"}, {"text": "fly"}], "correct": [2]}, {"q": "Как по-английски «слон»?", "type": "single", "options": [{"text": "frog"}, {"text": "fish"}, {"text": "fly"}, {"text": "elephant"}], "correct": [3]}, {"q": "Как по-английски «рыба»?", "type": "single", "options": [{"text": "frog"}, {"text": "fly"}, {"text": "giraffe"}, {"text": "fish"}], "correct": [3]}, {"q": "Как по-английски «муха»?", "type": "single", "options": [{"text": "frog"}, {"text": "fly"}, {"text": "giraffe"}, {"text": "kangaroo"}], "correct": [1]}, {"q": "Как по-английски «лягушка»?", "type": "single", "options": [{"text": "kangaroo"}, {"text": "giraffe"}, {"text": "frog"}, {"text": "lion"}], "correct": [2]}, {"q": "Как по-английски «жираф»?", "type": "single", "options": [{"text": "giraffe"}, {"text": "kangaroo"}, {"text": "monkey"}, {"text": "lion"}], "correct": [0]}, {"q": "Как по-английски «кенгуру»?", "type": "single", "options": [{"text": "kangaroo"}, {"text": "snake"}, {"text": "monkey"}, {"text": "lion"}], "correct": [0]}, {"q": "Как по-английски «лев»?", "type": "single", "options": [{"text": "snake"}, {"text": "monkey"}, {"text": "spider"}, {"text": "lion"}], "correct": [3]}, {"q": "Как по-английски «обезьяна»?", "type": "single", "options": [{"text": "spider"}, {"text": "tiger"}, {"text": "snake"}, {"text": "monkey"}], "correct": [3]}, {"q": "Как по-английски «змея»?", "type": "single", "options": [{"text": "snake"}, {"text": "whale"}, {"text": "tiger"}, {"text": "spider"}], "correct": [0]}, {"q": "Как по-английски «паук»?", "type": "single", "options": [{"text": "spider"}, {"text": "bird"}, {"text": "tiger"}, {"text": "whale"}], "correct": [0]}, {"q": "Как по-английски «тигр»?", "type": "single", "options": [{"text": "bird"}, {"text": "tiger"}, {"text": "whale"}, {"text": "butterfly"}], "correct": [1]}, {"q": "Как по-английски «кит»?", "type": "single", "options": [{"text": "crocodile"}, {"text": "butterfly"}, {"text": "whale"}, {"text": "bird"}], "correct": [2]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'match', replace($blk${"title": "Найди пару", "pairs": [{"left": "bird", "right": "птица", "left_audio_tts": "bird"}, {"left": "butterfly", "right": "бабочка", "left_audio_tts": "butterfly"}, {"left": "crocodile", "right": "крокодил", "left_audio_tts": "crocodile"}, {"left": "elephant", "right": "слон", "left_audio_tts": "elephant"}, {"left": "fish", "right": "рыба", "left_audio_tts": "fish"}, {"left": "fly", "right": "муха", "left_audio_tts": "fly"}, {"left": "frog", "right": "лягушка", "left_audio_tts": "frog"}, {"left": "giraffe", "right": "жираф", "left_audio_tts": "giraffe"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'match', replace($blk${"title": "И ещё: найди пару", "pairs": [{"left": "kangaroo", "right": "кенгуру", "left_audio_tts": "kangaroo"}, {"left": "lion", "right": "лев", "left_audio_tts": "lion"}, {"left": "monkey", "right": "обезьяна", "left_audio_tts": "monkey"}, {"left": "snake", "right": "змея", "left_audio_tts": "snake"}, {"left": "spider", "right": "паук", "left_audio_tts": "spider"}, {"left": "tiger", "right": "тигр", "left_audio_tts": "tiger"}, {"left": "whale", "right": "кит", "left_audio_tts": "whale"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'exact_input', replace($blk${"title": "Впиши слово целиком: некоторые буквы пропущены", "items": [{"prompt": "b _ r d", "accept": ["bird", "Bird"], "image": "@@MEDIA@@gg1/u7/animal_bird.webp"}, {"prompt": "b _ t _ e _ f _ y", "accept": ["butterfly", "Butterfly"], "image": "@@MEDIA@@gg1/u7/animal_butterfly.webp"}, {"prompt": "c _ o _ o _ i _ e", "accept": ["crocodile", "Crocodile"], "image": "@@MEDIA@@gg1/u7/animal_crocodile.webp"}, {"prompt": "e _ e _ h _ n t", "accept": ["elephant", "Elephant"], "image": "@@MEDIA@@gg1/u7/animal_elephant.webp"}, {"prompt": "f _ s h", "accept": ["fish", "Fish"], "image": "@@MEDIA@@gg1/u7/animal_fish.webp"}, {"prompt": "f _ y", "accept": ["fly", "Fly"], "image": "@@MEDIA@@gg1/u7/animal_fly.webp"}, {"prompt": "f _ o g", "accept": ["frog", "Frog"], "image": "@@MEDIA@@gg1/u7/animal_frog.webp"}, {"prompt": "g _ r _ f _ e", "accept": ["giraffe", "Giraffe"], "image": "@@MEDIA@@gg1/u7/animal_giraffe.webp"}, {"prompt": "k _ n _ a _ o o", "accept": ["kangaroo", "Kangaroo"], "image": "@@MEDIA@@gg1/u7/animal_kangaroo.webp"}, {"prompt": "l _ o n", "accept": ["lion", "Lion"], "image": "@@MEDIA@@gg1/u7/animal_lion.webp"}, {"prompt": "m _ n _ e y", "accept": ["monkey", "Monkey"], "image": "@@MEDIA@@gg1/u7/animal_monkey.webp"}, {"prompt": "s _ a _ e", "accept": ["snake", "Snake"], "image": "@@MEDIA@@gg1/u7/animal_snake.webp"}, {"prompt": "s _ i _ e r", "accept": ["spider", "Spider"], "image": "@@MEDIA@@gg1/u7/animal_spider.webp"}, {"prompt": "t _ g _ r", "accept": ["tiger", "Tiger"], "image": "@@MEDIA@@gg1/u7/animal_tiger.webp"}, {"prompt": "w _ a _ e", "accept": ["whale", "Whale"], "image": "@@MEDIA@@gg1/u7/animal_whale.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'text', replace($blk${"html": "<h3>Добро пожаловать во вторую часть домашнего задания! 👋</h3><p>Выполни все задания, чтобы хорошенько запомнить новые слова! Выполнив их, ты станешь МЕГА крутым учеником!</p><p>Давай повторим всё, что выучили сегодня на уроке.</p><p><img src=\"@@MEDIA@@gg1/u7/card_wild_animals.webp\" alt=\"Wild Animals\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'match', replace($blk${"title": "Итак, первое задание — соедини животных с их умениями. Выполняй задание внимательно, не торопись ;)", "pairs": [{"left": "It can fly.", "right": "bird", "right_audio_tts": "bird"}, {"left": "It can swim, but it can't walk.", "right": "whale", "right_audio_tts": "whale"}, {"left": "It can climb trees.", "right": "monkey", "right_audio_tts": "monkey"}, {"left": "It can jump, but it can't swim.", "right": "kangaroo", "right_audio_tts": "kangaroo"}, {"left": "It can jump and swim.", "right": "frog", "right_audio_tts": "frog"}, {"left": "It can run fast, but it can't fly.", "right": "tiger", "right_audio_tts": "tiger"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'task', replace($blk${"title": "Загадка 🐾", "needs_review": true, "image": "@@MEDIA@@gg1/u7/animals_collage.webp", "html": "<p>Загадай какое-нибудь животное и опиши его, не называя. На уроке загадай его своим одноклассникам и учителю.</p><p><i>Смотри, это моя загадка: It's black and white. It likes bamboo. It's big and cute. It can climb trees. What animal is it?</i></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'match', replace($blk${"title": "Ты выполнил все задания из основной части! А это дополнительное задание — для настоящих чемпионов! Соедини картинку и слово ⭐", "pairs": [{"left_image": "@@MEDIA@@gg1/u7/animal_crocodile.webp", "right": "crocodile", "right_audio_tts": "crocodile"}, {"left_image": "@@MEDIA@@gg1/u7/animal_elephant.webp", "right": "elephant", "right_audio_tts": "elephant"}, {"left_image": "@@MEDIA@@gg1/u7/animal_giraffe.webp", "right": "giraffe", "right_audio_tts": "giraffe"}, {"left_image": "@@MEDIA@@gg1/u7/animal_lion.webp", "right": "lion", "right_audio_tts": "lion"}, {"left_image": "@@MEDIA@@gg1/u7/animal_snake.webp", "right": "snake", "right_audio_tts": "snake"}, {"left_image": "@@MEDIA@@gg1/u7/animal_spider.webp", "right": "spider", "right_audio_tts": "spider"}, {"left_image": "@@MEDIA@@gg1/u7/animal_butterfly.webp", "right": "butterfly", "right_audio_tts": "butterfly"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 9),
    (v_lesson, 'exact_input', replace($blk${"title": "Впиши слова: буквы перепутались ⭐", "items": [{"prompt": "E N O Y K M", "accept": ["monkey", "Monkey"], "image": "@@MEDIA@@gg1/u7/animal_monkey.webp"}, {"prompt": "T R G E I", "accept": ["tiger", "Tiger"], "image": "@@MEDIA@@gg1/u7/animal_tiger.webp"}, {"prompt": "A L H E W", "accept": ["whale", "Whale"], "image": "@@MEDIA@@gg1/u7/animal_whale.webp"}, {"prompt": "O R F G", "accept": ["frog", "Frog"], "image": "@@MEDIA@@gg1/u7/animal_frog.webp"}, {"prompt": "O G A K A O R N", "accept": ["kangaroo", "Kangaroo"], "image": "@@MEDIA@@gg1/u7/animal_kangaroo.webp"}, {"prompt": "Y F L", "accept": ["fly", "Fly"], "image": "@@MEDIA@@gg1/u7/animal_fly.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 10),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/congrats_popper.webp\" alt=\"\" style=\"height:180px\"></p><h3>Поздравляю! Ты завершил домашнее задание. Ты — МЕГА КРУТ! 🎉</h3><p>Жду тебя на уроке!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 11);
end
$mig$;
