-- Go Getter 1 · Unit 8 · Sport and health · Test
-- собрано tools/gg1_build.py --lesson u8_test
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where title = 'Go Getter 1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 8 · Sport and health', 8
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 8 · Sport and health');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 8 · Sport and health';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Test', 'test',
         90, false, 7
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Test');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Test';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'exact_input', replace($blk${"title": "Посмотри на картинку и впиши слово по-английски", "items": [{"prompt": "бадминтон", "accept": ["badminton", "Badminton"], "image": "@@MEDIA@@gg1/u8/sport_badminton.webp"}, {"prompt": "баскетбол", "accept": ["basketball", "Basketball"], "image": "@@MEDIA@@gg1/u8/sport_basketball.webp"}, {"prompt": "велосипедный спорт", "accept": ["cycling", "Cycling"], "image": "@@MEDIA@@gg1/u8/sport_cycling.webp"}, {"prompt": "хоккей", "accept": ["hockey", "Hockey"], "image": "@@MEDIA@@gg1/u8/sport_hockey.webp"}, {"prompt": "катание на коньках", "accept": ["ice-skating", "Ice-skating"], "image": "@@MEDIA@@gg1/u8/sport_ice_skating.webp"}, {"prompt": "парусный спорт", "accept": ["sailing", "Sailing"], "image": "@@MEDIA@@gg1/u8/sport_sailing.webp"}, {"prompt": "скейтбординг", "accept": ["skateboarding", "Skateboarding"], "image": "@@MEDIA@@gg1/u8/sport_skateboarding.webp"}, {"prompt": "тхэквондо", "accept": ["taekwondo", "Taekwondo"], "image": "@@MEDIA@@gg1/u8/sport_taekwondo.webp"}, {"prompt": "волейбол", "accept": ["volleyball", "Volleyball"], "image": "@@MEDIA@@gg1/u8/sport_volleyball.webp"}, {"prompt": "виндсерфинг", "accept": ["windsurfing", "Windsurfing"], "image": "@@MEDIA@@gg1/u8/sport_windsurfing.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'quiz', replace($blk${"title": "Прочитай предложение и выбери пропущенное слово", "questions": [{"q": "He likes ___ football after school.", "type": "single", "options": [{"text": "play"}, {"text": "plays"}, {"text": "playing"}], "correct": [2], "image": "@@MEDIA@@gg1/u8/sport_football.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'quiz', replace($blk${"title": "Прочитай предложение и выбери пропущенные слова", "questions": [{"q": "___ is a good friend. I like her.", "type": "single", "options": [{"text": "Her"}, {"text": "She"}], "correct": [1]}, {"q": "She is a good friend. I like ___.", "type": "single", "options": [{"text": "her"}, {"text": "his"}, {"text": "she"}], "correct": [0]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'quiz', replace($blk${"title": "Прочитай предложение и выбери пропущенные слова", "questions": [{"q": "My sister ___ eating, but she doesn't like cooking.", "type": "single", "options": [{"text": "like"}, {"text": "likes"}], "correct": [1]}, {"q": "My sister likes ___, but she doesn't like cooking.", "type": "single", "options": [{"text": "eating"}, {"text": "eat"}, {"text": "eats"}], "correct": [0]}, {"q": "My sister likes eating, but she ___ like cooking.", "type": "single", "options": [{"text": "don't"}, {"text": "doesn't"}], "correct": [1]}, {"q": "My sister likes eating, but she doesn't like ___.", "type": "single", "options": [{"text": "cooks"}, {"text": "cook"}, {"text": "cooking"}], "correct": [2]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'quiz', replace($blk${"title": "Прочитай диалог и выбери пропущенные слова", "questions": [{"q": "A: ___ she like playing the piano?", "type": "single", "options": [{"text": "Does"}, {"text": "Do"}], "correct": [0]}, {"q": "A: Does she like ___ the piano?", "type": "single", "options": [{"text": "play"}, {"text": "playing"}, {"text": "plays"}], "correct": [1]}, {"q": "B: No, she ___. She likes playing the guitar instead.", "type": "single", "options": [{"text": "doesn't"}, {"text": "do"}, {"text": "don't"}, {"text": "does"}], "correct": [0]}, {"q": "B: No, she doesn't. She likes ___ the guitar instead.", "type": "single", "options": [{"text": "playing"}, {"text": "play"}, {"text": "plays"}], "correct": [0]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'quiz', replace($blk${"title": "Прочитай диалог и выбери пропущенные слова", "questions": [{"q": "A: What ___ your brother like doing?", "type": "single", "options": [{"text": "does"}, {"text": "do"}], "correct": [0]}, {"q": "A: What does your brother ___ doing?", "type": "single", "options": [{"text": "liking"}, {"text": "like"}, {"text": "likes"}], "correct": [1]}, {"q": "A: What does your brother like ___?", "type": "single", "options": [{"text": "do"}, {"text": "does"}, {"text": "doing"}], "correct": [2]}, {"q": "B: He ___ listening to music.", "type": "single", "options": [{"text": "likes"}, {"text": "like"}, {"text": "liking"}], "correct": [0]}, {"q": "B: He likes ___ to music.", "type": "single", "options": [{"text": "listens"}, {"text": "listening"}, {"text": "listen"}], "correct": [1]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'order', replace($blk${"title": "Расставь слова в правильном порядке", "words": ["He", "doesn't", "like", "playing", "computer", "games."], "sentence": "He doesn't like playing computer games.", "audio_tts": "He doesn't like playing computer games."}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'order', replace($blk${"title": "Расставь слова в правильном порядке", "words": ["What", "do", "you", "like", "doing?"], "sentence": "What do you like doing?", "audio_tts": "What do you like doing?"}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'order', replace($blk${"title": "Расставь слова в правильном порядке", "words": ["What", "is", "your", "favourite", "sport?"], "sentence": "What is your favourite sport?", "audio_tts": "What is your favourite sport?", "image": "@@MEDIA@@gg1/u8/sport_tennis.webp"}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'order', replace($blk${"title": "Расставь слова в правильном порядке", "words": ["What", "is", "the weather", "like", "today?"], "sentence": "What is the weather like today?", "audio_tts": "What is the weather like today?", "image": "@@MEDIA@@gg1/u8/weather_sunny.webp"}$blk$, '@@MEDIA@@', v_media)::jsonb, 9),
    (v_lesson, 'order', replace($blk${"title": "Расставь слова в правильном порядке", "words": ["It is", "good", "to brush", "your", "teeth."], "sentence": "It is good to brush your teeth.", "audio_tts": "It is good to brush your teeth.", "image": "@@MEDIA@@gg1/u8/life_brush_teeth.webp"}$blk$, '@@MEDIA@@', v_media)::jsonb, 10),
    (v_lesson, 'text', replace($blk${"html": "<h3>READING</h3><p>Прочитай рассказ Сары о своём образе жизни.</p><p><i>Hi! I'm Sara and I love sports! In summer I go swimming every day, and in winter I go ice-skating with my brother. I go to bed at half past nine and I get up at seven o'clock. I drink two litres of water a day. I eat a lot of fruit — apples and bananas are my favourite. I brush my teeth two times a day, in the morning and in the evening. I've got a lot of friends, and we often play volleyball in the park at the weekend.</i></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 11),
    (v_lesson, 'truefalse', replace($blk${"title": "READING. Правда или неправда?", "statements": [{"text": "Sara doesn't like sports.", "correct": false}, {"text": "She goes swimming in summer.", "correct": true}, {"text": "She loves ice-skating in autumn.", "correct": false}, {"text": "She goes to bed at ten o'clock.", "correct": false}, {"text": "She drinks two litres of water a day.", "correct": true}, {"text": "Sara eats a lot of fruit.", "correct": true}, {"text": "She brushes her teeth one time a day.", "correct": false}, {"text": "Sara has only a few friends.", "correct": false}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 12),
    (v_lesson, 'gaps', replace($blk${"title": "LISTENING. Прослушай прогноз погоды на эту неделю и перетащи нужное слово в каждый пропуск", "mode": "drag", "audio": "", "text": "1. On __Sunday__, it's very hot all day.\n2. In the afternoon, it's __rainy__.\n3. On __Monday__, it's cloudy – there are no blue __skies__.\n4. On Saturday morning, it's __sunny__ and __warm__.\n5. On Tuesday, it's very __windy__."}$blk$, '@@MEDIA@@', v_media)::jsonb, 13),
    (v_lesson, 'speaking', replace($blk${"title": "SPEAKING TASK PART 1 🎤", "html": "<p>Посмотри на таблицу. Расскажи, кто что любит или не любит делать. Затем расскажи, что любишь / не любишь делать ты. Запиши свой ответ, нажав на кнопку микрофона 🙌</p><table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse\"><tr><th></th><th>😊 likes</th><th>😫 doesn't like</th></tr><tr><td><b>Mary</b></td><td>swimming</td><td>climbing</td></tr><tr><td><b>Tom</b></td><td>playing football</td><td>cooking</td></tr><tr><td><b>Lucy</b></td><td>reading</td><td>getting up early</td></tr><tr><td><b>Ben</b></td><td>cycling</td><td>playing tennis</td></tr></table><p><i>Пример: Mary likes swimming, but she doesn't like climbing. As for me, I like…, I don't like…</i></p>", "needs_review": true}$blk$, '@@MEDIA@@', v_media)::jsonb, 14),
    (v_lesson, 'speaking', replace($blk${"title": "SPEAKING TASK PART 2 🎤", "html": "<p>Расскажи, что ты делаешь, чтобы вести здоровый образ жизни. Запиши свой ответ, нажав на кнопку микрофона 🙌</p><p><i>Пример: I do sport. I don't eat sweets.</i></p>", "needs_review": true}$blk$, '@@MEDIA@@', v_media)::jsonb, 15);
end
$mig$;
