-- Go Getter 1 · Unit 2 · My things · Homework 1
-- собрано tools/gg1_build.py --lesson u2_hw1
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where title = 'Go Getter 1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 2 · My things', 2
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 2 · My things');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 2 · My things';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 1', 'homework',
         60, false, 0
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 1');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 1';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Hello! 👋</h2><p>Сегодня мы учим слова про одежду. Выполни все задания, чтобы выучить их на все 100!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"cards": [{"text": "coat", "translation": "пальто", "audio_tts": "coat", "image": "@@MEDIA@@gg1/u2/clothes_coat.webp"}, {"text": "jeans", "translation": "джинсы", "audio_tts": "jeans", "image": "@@MEDIA@@gg1/u2/clothes_jeans.webp"}, {"text": "shoes", "translation": "обувь", "audio_tts": "shoes", "image": "@@MEDIA@@gg1/u2/clothes_shoes.webp"}, {"text": "skirt", "translation": "юбка", "audio_tts": "skirt", "image": "@@MEDIA@@gg1/u2/clothes_skirt.webp"}, {"text": "T-shirt", "translation": "футболка", "audio_tts": "T-shirt", "image": "@@MEDIA@@gg1/u2/clothes_tshirt.webp"}, {"text": "trousers", "translation": "брюки", "audio_tts": "trousers", "image": "@@MEDIA@@gg1/u2/clothes_trousers.webp"}, {"text": "boots", "translation": "сапоги", "audio_tts": "boots", "image": "@@MEDIA@@gg1/u2/clothes_boots.webp"}, {"text": "cap", "translation": "кепка", "audio_tts": "cap", "image": "@@MEDIA@@gg1/u2/clothes_cap.webp"}, {"text": "dress", "translation": "платье", "audio_tts": "dress", "image": "@@MEDIA@@gg1/u2/clothes_dress.webp"}, {"text": "hoodie", "translation": "толстовка с капюшоном", "audio_tts": "hoodie", "image": "@@MEDIA@@gg1/u2/clothes_hoodie.webp"}, {"text": "jacket", "translation": "куртка", "audio_tts": "jacket", "image": "@@MEDIA@@gg1/u2/clothes_jacket.webp"}, {"text": "shirt", "translation": "рубашка", "audio_tts": "shirt", "image": "@@MEDIA@@gg1/u2/clothes_shirt.webp"}, {"text": "jumper", "translation": "свитер", "audio_tts": "jumper", "image": "@@MEDIA@@gg1/u2/clothes_jumper.webp"}, {"text": "tracksuit", "translation": "спортивный костюм", "audio_tts": "tracksuit", "image": "@@MEDIA@@gg1/u2/clothes_tracksuit.webp"}, {"text": "gloves", "translation": "перчатки", "audio_tts": "gloves", "image": "@@MEDIA@@gg1/u2/clothes_gloves.webp"}, {"text": "scarf", "translation": "шарф", "audio_tts": "scarf", "image": "@@MEDIA@@gg1/u2/clothes_scarf.webp"}, {"text": "shorts", "translation": "шорты", "audio_tts": "shorts", "image": "@@MEDIA@@gg1/u2/clothes_shorts.webp"}, {"text": "trainers", "translation": "кроссовки", "audio_tts": "trainers", "image": "@@MEDIA@@gg1/u2/clothes_trainers.webp"}, {"text": "top", "translation": "топ", "audio_tts": "top", "image": "@@MEDIA@@gg1/u2/clothes_top.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'match', replace($blk${"title": "Соедини картинку и слово", "pairs": [{"left_image": "@@MEDIA@@gg1/u2/clothes_coat.webp", "right": "coat", "right_audio_tts": "coat"}, {"left_image": "@@MEDIA@@gg1/u2/clothes_jeans.webp", "right": "jeans", "right_audio_tts": "jeans"}, {"left_image": "@@MEDIA@@gg1/u2/clothes_shoes.webp", "right": "shoes", "right_audio_tts": "shoes"}, {"left_image": "@@MEDIA@@gg1/u2/clothes_skirt.webp", "right": "skirt", "right_audio_tts": "skirt"}, {"left_image": "@@MEDIA@@gg1/u2/clothes_tshirt.webp", "right": "T-shirt", "right_audio_tts": "T-shirt"}, {"left_image": "@@MEDIA@@gg1/u2/clothes_trousers.webp", "right": "trousers", "right_audio_tts": "trousers"}, {"left_image": "@@MEDIA@@gg1/u2/clothes_boots.webp", "right": "boots", "right_audio_tts": "boots"}, {"left_image": "@@MEDIA@@gg1/u2/clothes_cap.webp", "right": "cap", "right_audio_tts": "cap"}, {"left_image": "@@MEDIA@@gg1/u2/clothes_dress.webp", "right": "dress", "right_audio_tts": "dress"}, {"left_image": "@@MEDIA@@gg1/u2/clothes_hoodie.webp", "right": "hoodie", "right_audio_tts": "hoodie"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'match', replace($blk${"title": "И ещё: соедини картинку и слово", "pairs": [{"left_image": "@@MEDIA@@gg1/u2/clothes_jacket.webp", "right": "jacket", "right_audio_tts": "jacket"}, {"left_image": "@@MEDIA@@gg1/u2/clothes_shirt.webp", "right": "shirt", "right_audio_tts": "shirt"}, {"left_image": "@@MEDIA@@gg1/u2/clothes_jumper.webp", "right": "jumper", "right_audio_tts": "jumper"}, {"left_image": "@@MEDIA@@gg1/u2/clothes_tracksuit.webp", "right": "tracksuit", "right_audio_tts": "tracksuit"}, {"left_image": "@@MEDIA@@gg1/u2/clothes_gloves.webp", "right": "gloves", "right_audio_tts": "gloves"}, {"left_image": "@@MEDIA@@gg1/u2/clothes_scarf.webp", "right": "scarf", "right_audio_tts": "scarf"}, {"left_image": "@@MEDIA@@gg1/u2/clothes_shorts.webp", "right": "shorts", "right_audio_tts": "shorts"}, {"left_image": "@@MEDIA@@gg1/u2/clothes_trainers.webp", "right": "trainers", "right_audio_tts": "trainers"}, {"left_image": "@@MEDIA@@gg1/u2/clothes_top.webp", "right": "top", "right_audio_tts": "top"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «пальто»?", "type": "single", "options": [{"text": "coat"}, {"text": "shoes"}, {"text": "jeans"}, {"text": "skirt"}], "correct": [0]}, {"q": "Как по-английски «джинсы»?", "type": "single", "options": [{"text": "jeans"}, {"text": "shoes"}, {"text": "skirt"}, {"text": "T-shirt"}], "correct": [0]}, {"q": "Как по-английски «обувь»?", "type": "single", "options": [{"text": "shoes"}, {"text": "trousers"}, {"text": "skirt"}, {"text": "T-shirt"}], "correct": [0]}, {"q": "Как по-английски «юбка»?", "type": "single", "options": [{"text": "T-shirt"}, {"text": "boots"}, {"text": "skirt"}, {"text": "trousers"}], "correct": [2]}, {"q": "Как по-английски «футболка»?", "type": "single", "options": [{"text": "boots"}, {"text": "T-shirt"}, {"text": "trousers"}, {"text": "cap"}], "correct": [1]}, {"q": "Как по-английски «брюки»?", "type": "single", "options": [{"text": "trousers"}, {"text": "dress"}, {"text": "boots"}, {"text": "cap"}], "correct": [0]}, {"q": "Как по-английски «сапоги»?", "type": "single", "options": [{"text": "cap"}, {"text": "boots"}, {"text": "hoodie"}, {"text": "dress"}], "correct": [1]}, {"q": "Как по-английски «кепка»?", "type": "single", "options": [{"text": "coat"}, {"text": "hoodie"}, {"text": "cap"}, {"text": "dress"}], "correct": [2]}, {"q": "Как по-английски «платье»?", "type": "single", "options": [{"text": "jeans"}, {"text": "coat"}, {"text": "hoodie"}, {"text": "dress"}], "correct": [3]}, {"q": "Как по-английски «толстовка с капюшоном»?", "type": "single", "options": [{"text": "coat"}, {"text": "hoodie"}, {"text": "jeans"}, {"text": "shoes"}], "correct": [1]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'exact_input', replace($blk${"title": "Посмотри на картинку и напиши слово по-английски", "items": [{"prompt": "куртка", "accept": ["jacket", "jacket", "Jacket"], "image": "@@MEDIA@@gg1/u2/clothes_jacket.webp", "audio_tts": "jacket"}, {"prompt": "рубашка", "accept": ["shirt", "shirt", "Shirt"], "image": "@@MEDIA@@gg1/u2/clothes_shirt.webp", "audio_tts": "shirt"}, {"prompt": "свитер", "accept": ["jumper", "jumper", "Jumper"], "image": "@@MEDIA@@gg1/u2/clothes_jumper.webp", "audio_tts": "jumper"}, {"prompt": "спортивный костюм", "accept": ["tracksuit", "tracksuit", "Tracksuit"], "image": "@@MEDIA@@gg1/u2/clothes_tracksuit.webp", "audio_tts": "tracksuit"}, {"prompt": "перчатки", "accept": ["gloves", "gloves", "Gloves"], "image": "@@MEDIA@@gg1/u2/clothes_gloves.webp", "audio_tts": "gloves"}, {"prompt": "шарф", "accept": ["scarf", "scarf", "Scarf"], "image": "@@MEDIA@@gg1/u2/clothes_scarf.webp", "audio_tts": "scarf"}, {"prompt": "шорты", "accept": ["shorts", "shorts", "Shorts"], "image": "@@MEDIA@@gg1/u2/clothes_shorts.webp", "audio_tts": "shorts"}, {"prompt": "кроссовки", "accept": ["trainers", "trainers", "Trainers"], "image": "@@MEDIA@@gg1/u2/clothes_trainers.webp", "audio_tts": "trainers"}, {"prompt": "топ", "accept": ["top", "top", "Top"], "image": "@@MEDIA@@gg1/u2/clothes_top.webp", "audio_tts": "top"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'text', replace($blk${"html": "<h3>Добро пожаловать во вторую часть домашнего задания! 👋</h3><p>Давай повторим всё, что выучили сегодня на уроке.</p><p><img src=\"@@MEDIA@@gg1/u2/card_clothes.webp\" alt=\"Clothes\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'match', replace($blk${"title": "Найди пары", "pairs": [{"left": "coat", "right": "пальто", "left_audio_tts": "coat"}, {"left": "jeans", "right": "джинсы", "left_audio_tts": "jeans"}, {"left": "shoes", "right": "обувь", "left_audio_tts": "shoes"}, {"left": "skirt", "right": "юбка", "left_audio_tts": "skirt"}, {"left": "T-shirt", "right": "футболка", "left_audio_tts": "T-shirt"}, {"left": "trousers", "right": "брюки", "left_audio_tts": "trousers"}, {"left": "boots", "right": "сапоги", "left_audio_tts": "boots"}, {"left": "cap", "right": "кепка", "left_audio_tts": "cap"}, {"left": "dress", "right": "платье", "left_audio_tts": "dress"}, {"left": "hoodie", "right": "толстовка с капюшоном", "left_audio_tts": "hoodie"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'gaps', replace($blk${"title": "Посмотри на картинку и впиши название одежды", "mode": "type", "image": "@@MEDIA@@gg1/u2/kids_outfits.webp", "text": "1. Her __jacket__ is grey.\n2. Her __jumper__ is pink.\n3. Her __jeans__ are blue.\n4. Her __boots__ are brown.\n5. His __cap__ is blue.\n6. His __hoodie__ is green.\n7. His __trousers__ are black.\n8. His __shoes|trainers__ are white."}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'speaking', replace($blk${"title": "Моя одежда 🎤", "html": "<p>А теперь нажми на микрофон и перечисли, какая одежда у тебя есть.</p><p><i>Пример: I've got a blue T-shirt, black jeans and white trainers.</i></p>", "needs_review": true}$blk$, '@@MEDIA@@', v_media)::jsonb, 9),
    (v_lesson, 'quiz', replace($blk${"title": "Ты выполнил все задания из основной части! А это дополнительное задание — для настоящих чемпионов! Что на картинке? ⭐", "questions": [{"q": "What's this?", "type": "single", "options": [{"text": "a dress"}, {"text": "a top"}, {"text": "a skirt"}], "correct": [0], "image": "@@MEDIA@@gg1/u2/clothes_dress.webp"}, {"q": "What's this?", "type": "single", "options": [{"text": "a jacket"}, {"text": "a hoodie"}, {"text": "a jumper"}], "correct": [1], "image": "@@MEDIA@@gg1/u2/clothes_hoodie.webp"}, {"q": "What are these?", "type": "single", "options": [{"text": "trainers"}, {"text": "shoes"}, {"text": "boots"}], "correct": [2], "image": "@@MEDIA@@gg1/u2/clothes_boots.webp"}, {"q": "What are these?", "type": "single", "options": [{"text": "shorts"}, {"text": "trousers"}, {"text": "jeans"}], "correct": [0], "image": "@@MEDIA@@gg1/u2/clothes_shorts.webp"}, {"q": "What's this?", "type": "single", "options": [{"text": "a coat"}, {"text": "a scarf"}, {"text": "a cap"}], "correct": [1], "image": "@@MEDIA@@gg1/u2/clothes_scarf.webp"}, {"q": "What are these?", "type": "single", "options": [{"text": "shoes"}, {"text": "trainers"}, {"text": "gloves"}], "correct": [2], "image": "@@MEDIA@@gg1/u2/clothes_gloves.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 10),
    (v_lesson, 'quiz', replace($blk${"title": "It is или They are? Выбери правильный вариант ⭐", "questions": [{"q": "___ a T-shirt.", "type": "single", "options": [{"text": "They're"}, {"text": "It's"}], "correct": [1], "image": "@@MEDIA@@gg1/u2/clothes_tshirt.webp"}, {"q": "___ trousers.", "type": "single", "options": [{"text": "They're"}, {"text": "It's"}], "correct": [0], "image": "@@MEDIA@@gg1/u2/clothes_trousers.webp"}, {"q": "___ a coat.", "type": "single", "options": [{"text": "They're"}, {"text": "It's"}], "correct": [1], "image": "@@MEDIA@@gg1/u2/clothes_coat.webp"}, {"q": "___ jeans.", "type": "single", "options": [{"text": "They're"}, {"text": "It's"}], "correct": [0], "image": "@@MEDIA@@gg1/u2/clothes_jeans.webp"}, {"q": "The skirt ___ blue.", "type": "single", "options": [{"text": "are"}, {"text": "is"}], "correct": [1], "image": "@@MEDIA@@gg1/u2/clothes_skirt.webp"}, {"q": "The trainers ___ white.", "type": "single", "options": [{"text": "are"}, {"text": "is"}], "correct": [0], "image": "@@MEDIA@@gg1/u2/clothes_trainers.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 11),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_star.webp\" alt=\"\" style=\"height:180px\"></p><h3>Ура, ты выполнил все задания, ты большой молодец! 🎉</h3><p>Увидимся на занятии!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 12);
end
$mig$;
