-- Go Getter 1 · Unit 0 · Get started! · Homework 3
-- собрано tools/gg1_build.py --lesson u0_hw3
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where title = 'Go Getter 1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 0 · Get started!', 0
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 0 · Get started!');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 0 · Get started!';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 3', 'homework',
         60, false, 2
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 3');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 3';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_laptop.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет! 👋</h2><p>Сейчас мы с тобой выучим новые слова — школьные принадлежности. Выполни все задания, чтобы выучить слова на 100%!</p><p><img src=\"@@MEDIA@@gg1/u0/card_in_my_bag.webp\" alt=\"In my bag + Classroom objects\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"cards": [{"text": "bin", "translation": "мусорное ведро", "audio_tts": "bin", "image": "@@MEDIA@@gg1/u0/obj_bin.webp"}, {"text": "board", "translation": "доска", "audio_tts": "board", "image": "@@MEDIA@@gg1/u0/obj_board.webp"}, {"text": "chair", "translation": "стул", "audio_tts": "chair", "image": "@@MEDIA@@gg1/u0/obj_chair.webp"}, {"text": "clock", "translation": "часы", "audio_tts": "clock", "image": "@@MEDIA@@gg1/u0/obj_clock.webp"}, {"text": "desk", "translation": "парта", "audio_tts": "desk", "image": "@@MEDIA@@gg1/u0/obj_desk.webp"}, {"text": "coloured pencil", "translation": "цветной карандаш", "audio_tts": "coloured pencil", "image": "@@MEDIA@@gg1/u0/obj_coloured_pencil.webp"}, {"text": "notebook", "translation": "тетрадь", "audio_tts": "notebook", "image": "@@MEDIA@@gg1/u0/obj_notebook.webp"}, {"text": "pen", "translation": "ручка", "audio_tts": "pen", "image": "@@MEDIA@@gg1/u0/obj_pen.webp"}, {"text": "sharpener", "translation": "точилка", "audio_tts": "sharpener", "image": "@@MEDIA@@gg1/u0/obj_sharpener.webp"}, {"text": "rubber", "translation": "ластик", "audio_tts": "rubber", "image": "@@MEDIA@@gg1/u0/obj_rubber.webp"}, {"text": "ruler", "translation": "линейка", "audio_tts": "ruler", "image": "@@MEDIA@@gg1/u0/obj_ruler.webp"}, {"text": "scissors", "translation": "ножницы", "audio_tts": "scissors", "image": "@@MEDIA@@gg1/u0/obj_scissors.webp"}, {"text": "pencil case", "translation": "пенал", "audio_tts": "pencil case", "image": "@@MEDIA@@gg1/u0/obj_pencil_case.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'match', replace($blk${"title": "Соедини картинку и слово", "pairs": [{"left_image": "@@MEDIA@@gg1/u0/obj_bin.webp", "right": "bin", "right_audio_tts": "bin"}, {"left_image": "@@MEDIA@@gg1/u0/obj_board.webp", "right": "board", "right_audio_tts": "board"}, {"left_image": "@@MEDIA@@gg1/u0/obj_chair.webp", "right": "chair", "right_audio_tts": "chair"}, {"left_image": "@@MEDIA@@gg1/u0/obj_clock.webp", "right": "clock", "right_audio_tts": "clock"}, {"left_image": "@@MEDIA@@gg1/u0/obj_desk.webp", "right": "desk", "right_audio_tts": "desk"}, {"left_image": "@@MEDIA@@gg1/u0/obj_coloured_pencil.webp", "right": "coloured pencil", "right_audio_tts": "coloured pencil"}, {"left_image": "@@MEDIA@@gg1/u0/obj_notebook.webp", "right": "notebook", "right_audio_tts": "notebook"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'match', replace($blk${"title": "И ещё раз — соедини картинку и слово", "pairs": [{"left_image": "@@MEDIA@@gg1/u0/obj_pen.webp", "right": "pen", "right_audio_tts": "pen"}, {"left_image": "@@MEDIA@@gg1/u0/obj_sharpener.webp", "right": "sharpener", "right_audio_tts": "sharpener"}, {"left_image": "@@MEDIA@@gg1/u0/obj_rubber.webp", "right": "rubber", "right_audio_tts": "rubber"}, {"left_image": "@@MEDIA@@gg1/u0/obj_ruler.webp", "right": "ruler", "right_audio_tts": "ruler"}, {"left_image": "@@MEDIA@@gg1/u0/obj_scissors.webp", "right": "scissors", "right_audio_tts": "scissors"}, {"left_image": "@@MEDIA@@gg1/u0/obj_pencil_case.webp", "right": "pencil case", "right_audio_tts": "pencil case"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «мусорное ведро»?", "type": "single", "options": [{"text": "chair"}, {"text": "bin"}, {"text": "board"}, {"text": "clock"}], "correct": [1]}, {"q": "Как по-английски «доска»?", "type": "single", "options": [{"text": "desk"}, {"text": "chair"}, {"text": "clock"}, {"text": "board"}], "correct": [3]}, {"q": "Как по-английски «стул»?", "type": "single", "options": [{"text": "coloured pencil"}, {"text": "clock"}, {"text": "desk"}, {"text": "chair"}], "correct": [3]}, {"q": "Как по-английски «часы»?", "type": "single", "options": [{"text": "coloured pencil"}, {"text": "clock"}, {"text": "desk"}, {"text": "notebook"}], "correct": [1]}, {"q": "Как по-английски «парта»?", "type": "single", "options": [{"text": "coloured pencil"}, {"text": "pen"}, {"text": "desk"}, {"text": "notebook"}], "correct": [2]}, {"q": "Как по-английски «цветной карандаш»?", "type": "single", "options": [{"text": "pen"}, {"text": "sharpener"}, {"text": "notebook"}, {"text": "coloured pencil"}], "correct": [3]}, {"q": "Как по-английски «тетрадь»?", "type": "single", "options": [{"text": "notebook"}, {"text": "rubber"}, {"text": "pen"}, {"text": "sharpener"}], "correct": [0]}, {"q": "Как по-английски «ручка»?", "type": "single", "options": [{"text": "sharpener"}, {"text": "pen"}, {"text": "rubber"}, {"text": "ruler"}], "correct": [1]}, {"q": "Как по-английски «точилка»?", "type": "single", "options": [{"text": "sharpener"}, {"text": "scissors"}, {"text": "ruler"}, {"text": "rubber"}], "correct": [0]}, {"q": "Как по-английски «ластик»?", "type": "single", "options": [{"text": "ruler"}, {"text": "pencil case"}, {"text": "scissors"}, {"text": "rubber"}], "correct": [3]}, {"q": "Как по-английски «линейка»?", "type": "single", "options": [{"text": "pencil case"}, {"text": "bin"}, {"text": "ruler"}, {"text": "scissors"}], "correct": [2]}, {"q": "Как по-английски «ножницы»?", "type": "single", "options": [{"text": "pencil case"}, {"text": "bin"}, {"text": "scissors"}, {"text": "board"}], "correct": [2]}, {"q": "Как по-английски «пенал»?", "type": "single", "options": [{"text": "board"}, {"text": "pencil case"}, {"text": "bin"}, {"text": "chair"}], "correct": [1]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'text', replace($blk${"html": "<h3>Слова выучены! ✏️</h3><p>Добро пожаловать во вторую часть домашнего задания! В конце тебя будет ждать дополнительное задание: сделаешь его — получишь звёздочку! ⭐</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'video', replace($blk${"title": "А теперь посмотри видео! Повторяй слова и внимательно следи за окончаниями — как образуют множественное число разные слова.", "url": "", "provider": "youtube"}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'sort', replace($blk${"title": "Класс! Посмотри видео ещё раз и распредели слова по колонкам: к каким словам нужно добавить s, а к каким es?", "groups": [{"name": "+s", "items": [{"text": "apple"}, {"text": "pencil"}, {"text": "notebook"}, {"text": "egg"}]}, {"name": "+es", "items": [{"text": "box"}, {"text": "sandwich"}, {"text": "bus"}, {"text": "brush"}]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'text', replace($blk${"html": "<p>Супер, двигаемся дальше! Давай вспомним правило про артикли <b>a</b> и <b>an</b>. Внимательно посмотри на зелёную рамочку, а затем выполни упражнение — ты сможешь!</p><p><img src=\"@@MEDIA@@gg1/u0/look_a_an.webp\" alt=\"a book, a pencil, an apple, an umbrella\" style=\"max-width:100%\"></p><p><img src=\"@@MEDIA@@gg1/u0/card_a_an.webp\" alt=\"a / an\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'quiz', replace($blk${"title": "Выбери правильный вариант: a или an?", "questions": [{"q": "1. ___ apple", "type": "single", "options": [{"text": "a"}, {"text": "an"}], "correct": [1]}, {"q": "2. ___ pencil", "type": "single", "options": [{"text": "a"}, {"text": "an"}], "correct": [0]}, {"q": "3. ___ sandwich", "type": "single", "options": [{"text": "a"}, {"text": "an"}], "correct": [0]}, {"q": "4. ___ notebook", "type": "single", "options": [{"text": "a"}, {"text": "an"}], "correct": [0]}, {"q": "5. ___ egg", "type": "single", "options": [{"text": "a"}, {"text": "an"}], "correct": [1]}, {"q": "6. ___ box", "type": "single", "options": [{"text": "a"}, {"text": "an"}], "correct": [0]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 9),
    (v_lesson, 'hotspot', replace($blk${"title": "Эти слова тебе уже знакомы — давай быстренько соединим слова с картинками! Сможешь? ;)", "mode": "label", "image": "@@MEDIA@@gg1/u0/diagram_classroom.webp", "points": [{"x": 25.0, "y": 27.0, "text": "bin", "audio_tts": "bin"}, {"x": 68.0, "y": 25.0, "text": "board", "audio_tts": "board"}, {"x": 13.0, "y": 72.0, "text": "chair", "audio_tts": "chair"}, {"x": 46.0, "y": 76.0, "text": "clock", "audio_tts": "clock"}, {"x": 83.0, "y": 70.0, "text": "desk", "audio_tts": "desk"}], "extras": []}$blk$, '@@MEDIA@@', v_media)::jsonb, 10),
    (v_lesson, 'text', replace($blk${"html": "<p>А теперь соберём всё вместе — внимательно посмотри на зелёную рамочку, а затем выполни упражнение. Ты сможешь!</p><p><img src=\"@@MEDIA@@gg1/u0/look_its_theyre.webp\" alt=\"It's a pencil. They're pencils.\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 11),
    (v_lesson, 'quiz', replace($blk${"title": "Выбери правильный вариант: It's или They're? Пример: It's a bin.", "questions": [{"q": "1. ___ clocks.", "type": "single", "options": [{"text": "It's"}, {"text": "They're"}], "correct": [1]}, {"q": "2. ___ a board.", "type": "single", "options": [{"text": "It's"}, {"text": "They're"}], "correct": [0]}, {"q": "3. ___ a desk.", "type": "single", "options": [{"text": "It's"}, {"text": "They're"}], "correct": [0]}, {"q": "4. ___ chairs.", "type": "single", "options": [{"text": "It's"}, {"text": "They're"}], "correct": [1]}, {"q": "5. ___ bins.", "type": "single", "options": [{"text": "It's"}, {"text": "They're"}], "correct": [1]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 12),
    (v_lesson, 'text', replace($blk${"html": "<p>Давай вспомним, какие фразы нам могут пригодиться на уроке.</p><p><img src=\"@@MEDIA@@gg1/u0/card_classroom_language.webp\" alt=\"Classroom language\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 13),
    (v_lesson, 'match', replace($blk${"title": "Поработаешь немного переводчиком? Соедини фразы на английском с переводом", "pairs": [{"left": "Close your books.", "right": "Закройте книги."}, {"left": "Open your books.", "right": "Откройте книги."}, {"left": "Look (at the photo).", "right": "Посмотрите (на фото)."}, {"left": "Listen (to the story).", "right": "Послушайте (историю)."}, {"left": "Read (the text).", "right": "Прочитайте (текст)."}, {"left": "Write (your name).", "right": "Напишите (своё имя)."}, {"left": "Can you help me?", "right": "Можете мне помочь?"}, {"left": "Can you repeat?", "right": "Можете повторить?"}, {"left": "I'm ready.", "right": "Я готов."}, {"left": "What is … in English?", "right": "Как будет … по-английски?"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 14),
    (v_lesson, 'task', replace($blk${"title": "Что в твоём рюкзаке? 🎒", "needs_review": true, "html": "<p>Прекрасная работа! Напиши список того, что есть в твоём школьном рюкзаке.</p><p><i>Например: a pen, a notebook, two pencils…</i></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 15),
    (v_lesson, 'quiz', replace($blk${"title": "Ты выполнил все задания из основной части! А это дополнительное задание — для настоящих чемпионов! Выбери подходящее слово ⭐", "questions": [{"q": "What's this?", "image": "@@MEDIA@@gg1/u0/obj_book.webp", "type": "single", "options": [{"text": "a book"}, {"text": "a bag"}, {"text": "a board"}], "correct": [0]}, {"q": "What's this?", "image": "@@MEDIA@@gg1/u0/obj_pencil.webp", "type": "single", "options": [{"text": "a pen"}, {"text": "a pencil case"}, {"text": "a pencil"}], "correct": [2]}, {"q": "What's this?", "image": "@@MEDIA@@gg1/u0/obj_sandwich.webp", "type": "single", "options": [{"text": "a ruler"}, {"text": "a sandwich"}, {"text": "a sharpener"}], "correct": [1]}, {"q": "What's this?", "image": "@@MEDIA@@gg1/u0/obj_apple.webp", "type": "single", "options": [{"text": "a apple"}, {"text": "an apple"}], "correct": [1]}, {"q": "What's this?", "image": "@@MEDIA@@gg1/u0/obj_bag.webp", "type": "single", "options": [{"text": "a bag"}, {"text": "a bin"}, {"text": "a book"}], "correct": [0]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 16),
    (v_lesson, 'match', replace($blk${"title": "Соедини слова с картинками ⭐", "pairs": [{"left_image": "@@MEDIA@@gg1/u0/obj_scissors.webp", "right": "scissors", "right_audio_tts": "scissors"}, {"left_image": "@@MEDIA@@gg1/u0/obj_ruler.webp", "right": "ruler", "right_audio_tts": "ruler"}, {"left_image": "@@MEDIA@@gg1/u0/obj_rubber.webp", "right": "rubber", "right_audio_tts": "rubber"}, {"left_image": "@@MEDIA@@gg1/u0/obj_clock.webp", "right": "clock", "right_audio_tts": "clock"}, {"left_image": "@@MEDIA@@gg1/u0/obj_desk.webp", "right": "desk", "right_audio_tts": "desk"}, {"left_image": "@@MEDIA@@gg1/u0/obj_notebook.webp", "right": "notebook", "right_audio_tts": "notebook"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 17),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_trophy.webp\" alt=\"\" style=\"height:180px\"></p><h3>Поздравляю! Ты завершил домашнее задание, ты замечательный ученик! 🎉</h3><p>Увидимся на занятии!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 18);
end
$mig$;
