-- Go Getter 1 · Unit 3 · My home · Homework 1
-- собрано tools/gg1_build.py --lesson u3_hw1
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where title = 'Go Getter 1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 3 · My home', 3
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 3 · My home');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 3 · My home';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 1', 'homework',
         60, false, 0
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 1');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 1';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Hello! 👋</h2><p>Сегодня мы учим слова про дом: комнаты, части дома и мебель. Выполни все задания, чтобы выучить их на все 100!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"cards": [{"text": "bathroom", "translation": "ванная комната", "audio_tts": "bathroom", "image": "@@MEDIA@@gg1/u3/room_bathroom.webp"}, {"text": "bedroom", "translation": "спальня", "audio_tts": "bedroom", "image": "@@MEDIA@@gg1/u3/room_bedroom.webp"}, {"text": "kitchen", "translation": "кухня", "audio_tts": "kitchen", "image": "@@MEDIA@@gg1/u3/room_kitchen.webp"}, {"text": "garage", "translation": "гараж", "audio_tts": "garage", "image": "@@MEDIA@@gg1/u3/room_garage.webp"}, {"text": "garden", "translation": "сад", "audio_tts": "garden", "image": "@@MEDIA@@gg1/u3/room_garden.webp"}, {"text": "living room", "translation": "гостиная", "audio_tts": "living room", "image": "@@MEDIA@@gg1/u3/room_living_room.webp"}, {"text": "floor", "translation": "пол", "audio_tts": "floor", "image": "@@MEDIA@@gg1/u3/part_floor.webp"}, {"text": "door", "translation": "дверь", "audio_tts": "door", "image": "@@MEDIA@@gg1/u3/part_door.webp"}, {"text": "wall", "translation": "стена", "audio_tts": "wall", "image": "@@MEDIA@@gg1/u3/part_wall.webp"}, {"text": "window", "translation": "окно", "audio_tts": "window", "image": "@@MEDIA@@gg1/u3/part_window.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'match', replace($blk${"title": "Соедини картинку и слово", "pairs": [{"left_image": "@@MEDIA@@gg1/u3/room_bathroom.webp", "right": "bathroom", "right_audio_tts": "bathroom"}, {"left_image": "@@MEDIA@@gg1/u3/room_bedroom.webp", "right": "bedroom", "right_audio_tts": "bedroom"}, {"left_image": "@@MEDIA@@gg1/u3/room_kitchen.webp", "right": "kitchen", "right_audio_tts": "kitchen"}, {"left_image": "@@MEDIA@@gg1/u3/room_garage.webp", "right": "garage", "right_audio_tts": "garage"}, {"left_image": "@@MEDIA@@gg1/u3/room_garden.webp", "right": "garden", "right_audio_tts": "garden"}, {"left_image": "@@MEDIA@@gg1/u3/room_living_room.webp", "right": "living room", "right_audio_tts": "living room"}, {"left_image": "@@MEDIA@@gg1/u3/part_floor.webp", "right": "floor", "right_audio_tts": "floor"}, {"left_image": "@@MEDIA@@gg1/u3/part_door.webp", "right": "door", "right_audio_tts": "door"}, {"left_image": "@@MEDIA@@gg1/u3/part_wall.webp", "right": "wall", "right_audio_tts": "wall"}, {"left_image": "@@MEDIA@@gg1/u3/part_window.webp", "right": "window", "right_audio_tts": "window"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «ванная комната»?", "type": "single", "options": [{"text": "kitchen"}, {"text": "garage"}, {"text": "bedroom"}, {"text": "bathroom"}], "correct": [3]}, {"q": "Как по-английски «спальня»?", "type": "single", "options": [{"text": "garage"}, {"text": "bedroom"}, {"text": "garden"}, {"text": "kitchen"}], "correct": [1]}, {"q": "Как по-английски «кухня»?", "type": "single", "options": [{"text": "living room"}, {"text": "kitchen"}, {"text": "garage"}, {"text": "garden"}], "correct": [1]}, {"q": "Как по-английски «гараж»?", "type": "single", "options": [{"text": "floor"}, {"text": "garage"}, {"text": "garden"}, {"text": "living room"}], "correct": [1]}, {"q": "Как по-английски «сад»?", "type": "single", "options": [{"text": "garden"}, {"text": "floor"}, {"text": "living room"}, {"text": "door"}], "correct": [0]}, {"q": "Как по-английски «гостиная»?", "type": "single", "options": [{"text": "wall"}, {"text": "floor"}, {"text": "door"}, {"text": "living room"}], "correct": [3]}, {"q": "Как по-английски «пол»?", "type": "single", "options": [{"text": "wall"}, {"text": "window"}, {"text": "floor"}, {"text": "door"}], "correct": [2]}, {"q": "Как по-английски «дверь»?", "type": "single", "options": [{"text": "bathroom"}, {"text": "wall"}, {"text": "door"}, {"text": "window"}], "correct": [2]}, {"q": "Как по-английски «стена»?", "type": "single", "options": [{"text": "window"}, {"text": "bathroom"}, {"text": "bedroom"}, {"text": "wall"}], "correct": [3]}, {"q": "Как по-английски «окно»?", "type": "single", "options": [{"text": "window"}, {"text": "bathroom"}, {"text": "bedroom"}, {"text": "kitchen"}], "correct": [0]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'exact_input', replace($blk${"title": "Расшифруй слово и впиши его", "items": [{"prompt": "O M O B H R T A", "accept": ["bathroom", "Bathroom"], "image": "@@MEDIA@@gg1/u3/room_bathroom.webp", "audio_tts": "bathroom"}, {"prompt": "B M O D E O R", "accept": ["bedroom", "Bedroom"], "image": "@@MEDIA@@gg1/u3/room_bedroom.webp", "audio_tts": "bedroom"}, {"prompt": "E C T N K I H", "accept": ["kitchen", "Kitchen"], "image": "@@MEDIA@@gg1/u3/room_kitchen.webp", "audio_tts": "kitchen"}, {"prompt": "A R G G A E", "accept": ["garage", "Garage"], "image": "@@MEDIA@@gg1/u3/room_garage.webp", "audio_tts": "garage"}, {"prompt": "N E D R A G", "accept": ["garden", "Garden"], "image": "@@MEDIA@@gg1/u3/room_garden.webp", "audio_tts": "garden"}, {"prompt": "D O W I W N", "accept": ["window", "Window"], "image": "@@MEDIA@@gg1/u3/part_window.webp", "audio_tts": "window"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'flashcards', replace($blk${"cards": [{"text": "armchair", "translation": "кресло", "audio_tts": "armchair", "image": "@@MEDIA@@gg1/u3/furn_armchair.webp"}, {"text": "bath", "translation": "ванна", "audio_tts": "bath", "image": "@@MEDIA@@gg1/u3/furn_bath.webp"}, {"text": "bed", "translation": "кровать", "audio_tts": "bed", "image": "@@MEDIA@@gg1/u3/furn_bed.webp"}, {"text": "chair", "translation": "стул", "audio_tts": "chair", "image": "@@MEDIA@@gg1/u0/obj_chair.webp"}, {"text": "desk", "translation": "письменный стол", "audio_tts": "desk", "image": "@@MEDIA@@gg1/u0/obj_desk.webp"}, {"text": "table", "translation": "стол", "audio_tts": "table", "image": "@@MEDIA@@gg1/u3/furn_table.webp"}, {"text": "fridge", "translation": "холодильник", "audio_tts": "fridge", "image": "@@MEDIA@@gg1/u3/furn_fridge.webp"}, {"text": "sofa", "translation": "диван", "audio_tts": "sofa", "image": "@@MEDIA@@gg1/u3/furn_sofa.webp"}, {"text": "wardrobe", "translation": "шкаф", "audio_tts": "wardrobe", "image": "@@MEDIA@@gg1/u3/furn_wardrobe.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'match', replace($blk${"title": "Соедини картинку и слово", "pairs": [{"left_image": "@@MEDIA@@gg1/u3/furn_armchair.webp", "right": "armchair", "right_audio_tts": "armchair"}, {"left_image": "@@MEDIA@@gg1/u3/furn_bath.webp", "right": "bath", "right_audio_tts": "bath"}, {"left_image": "@@MEDIA@@gg1/u3/furn_bed.webp", "right": "bed", "right_audio_tts": "bed"}, {"left_image": "@@MEDIA@@gg1/u0/obj_chair.webp", "right": "chair", "right_audio_tts": "chair"}, {"left_image": "@@MEDIA@@gg1/u0/obj_desk.webp", "right": "desk", "right_audio_tts": "desk"}, {"left_image": "@@MEDIA@@gg1/u3/furn_table.webp", "right": "table", "right_audio_tts": "table"}, {"left_image": "@@MEDIA@@gg1/u3/furn_fridge.webp", "right": "fridge", "right_audio_tts": "fridge"}, {"left_image": "@@MEDIA@@gg1/u3/furn_sofa.webp", "right": "sofa", "right_audio_tts": "sofa"}, {"left_image": "@@MEDIA@@gg1/u3/furn_wardrobe.webp", "right": "wardrobe", "right_audio_tts": "wardrobe"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «кресло»?", "type": "single", "options": [{"text": "bed"}, {"text": "chair"}, {"text": "bath"}, {"text": "armchair"}], "correct": [3]}, {"q": "Как по-английски «ванна»?", "type": "single", "options": [{"text": "chair"}, {"text": "bed"}, {"text": "bath"}, {"text": "desk"}], "correct": [2]}, {"q": "Как по-английски «кровать»?", "type": "single", "options": [{"text": "table"}, {"text": "chair"}, {"text": "desk"}, {"text": "bed"}], "correct": [3]}, {"q": "Как по-английски «стул»?", "type": "single", "options": [{"text": "fridge"}, {"text": "desk"}, {"text": "table"}, {"text": "chair"}], "correct": [3]}, {"q": "Как по-английски «письменный стол»?", "type": "single", "options": [{"text": "desk"}, {"text": "table"}, {"text": "fridge"}, {"text": "sofa"}], "correct": [0]}, {"q": "Как по-английски «стол»?", "type": "single", "options": [{"text": "fridge"}, {"text": "table"}, {"text": "sofa"}, {"text": "wardrobe"}], "correct": [1]}, {"q": "Как по-английски «холодильник»?", "type": "single", "options": [{"text": "armchair"}, {"text": "sofa"}, {"text": "fridge"}, {"text": "wardrobe"}], "correct": [2]}, {"q": "Как по-английски «диван»?", "type": "single", "options": [{"text": "armchair"}, {"text": "sofa"}, {"text": "bath"}, {"text": "wardrobe"}], "correct": [1]}, {"q": "Как по-английски «шкаф»?", "type": "single", "options": [{"text": "bath"}, {"text": "bed"}, {"text": "armchair"}, {"text": "wardrobe"}], "correct": [3]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'exact_input', replace($blk${"title": "Вставь пропущенные буквы и впиши слово целиком", "items": [{"prompt": "a _ m _ h _ i r", "accept": ["armchair", "Armchair"], "image": "@@MEDIA@@gg1/u3/furn_armchair.webp", "audio_tts": "armchair"}, {"prompt": "b _ t h", "accept": ["bath", "Bath"], "image": "@@MEDIA@@gg1/u3/furn_bath.webp", "audio_tts": "bath"}, {"prompt": "b _ d", "accept": ["bed", "Bed"], "image": "@@MEDIA@@gg1/u3/furn_bed.webp", "audio_tts": "bed"}, {"prompt": "c _ a _ r", "accept": ["chair", "Chair"], "image": "@@MEDIA@@gg1/u0/obj_chair.webp", "audio_tts": "chair"}, {"prompt": "d _ s k", "accept": ["desk", "Desk"], "image": "@@MEDIA@@gg1/u0/obj_desk.webp", "audio_tts": "desk"}, {"prompt": "t _ b _ e", "accept": ["table", "Table"], "image": "@@MEDIA@@gg1/u3/furn_table.webp", "audio_tts": "table"}, {"prompt": "f _ i _ g e", "accept": ["fridge", "Fridge"], "image": "@@MEDIA@@gg1/u3/furn_fridge.webp", "audio_tts": "fridge"}, {"prompt": "s _ f a", "accept": ["sofa", "Sofa"], "image": "@@MEDIA@@gg1/u3/furn_sofa.webp", "audio_tts": "sofa"}, {"prompt": "w _ r _ r _ b e", "accept": ["wardrobe", "Wardrobe"], "image": "@@MEDIA@@gg1/u3/furn_wardrobe.webp", "audio_tts": "wardrobe"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'text', replace($blk${"html": "<h3>Привет! Как поживаешь? (How are you doing?)</h3><p>Сегодня мы с тобой закрепим то, что изучали на уроке!</p><p><img src=\"@@MEDIA@@gg1/u3/card_parts_of_house.webp\" alt=\"Parts of the house\" style=\"max-width:100%\"></p><p><img src=\"@@MEDIA@@gg1/u3/card_inside_house.webp\" alt=\"Inside the house\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 9),
    (v_lesson, 'quiz', replace($blk${"title": "Посмотри на картинку и для каждого утверждения выбери: верно или неверно. Удачи! У тебя всё получится!", "questions": [{"q": "We usually have dinner in the bathroom.", "type": "single", "options": [{"text": "Верно"}, {"text": "Неверно"}], "correct": [1], "image": "@@MEDIA@@gg1/u3/house_cutaway_family.webp"}, {"q": "I do my homework in the kitchen.", "type": "single", "options": [{"text": "Верно"}, {"text": "Неверно"}], "correct": [1]}, {"q": "Sam and Mark play computer games in the garage.", "type": "single", "options": [{"text": "Верно"}, {"text": "Неверно"}], "correct": [1]}, {"q": "I brush my teeth in the bathroom.", "type": "single", "options": [{"text": "Верно"}, {"text": "Неверно"}], "correct": [0]}, {"q": "I go to bed in my bedroom.", "type": "single", "options": [{"text": "Верно"}, {"text": "Неверно"}], "correct": [0]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 10),
    (v_lesson, 'match', replace($blk${"title": "Соедини предметы интерьера с комнатами, где они обычно находятся", "pairs": [{"left": "armchair", "right": "living room"}, {"left": "table", "right": "dining room"}, {"left": "fridge", "right": "kitchen"}, {"left": "bath", "right": "bathroom"}, {"left": "bed", "right": "bedroom"}, {"left": "car", "right": "garage"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 11),
    (v_lesson, 'gaps', replace($blk${"title": "Здесь нас ждёт небольшой рассказ, в котором кто-то украл слова. Поможешь вставить пропущенные слова?", "mode": "drag", "image": "@@MEDIA@@gg1/u3/photo_house.webp", "text": "I live with my parents in a big __house__. The room I like most of all is our __living room__. There are so many things to do in this room. There is a big __bookcase__ and I can take any book I like from it. We often spend time watching films on __TV__. We sit on the comfortable __sofa__ which is opposite the TV. My dad keeps his car in the __garage__ and I like to help him with our __garden__ at the weekend."}$blk$, '@@MEDIA@@', v_media)::jsonb, 12),
    (v_lesson, 'video', replace($blk${"title": "Посмотри видео и попробуй догадаться, о каких комнатах рассказывается. Повторяй слова за рассказчиком!", "url": "", "provider": "youtube"}$blk$, '@@MEDIA@@', v_media)::jsonb, 13),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_jump.webp\" alt=\"\" style=\"height:180px\"></p><h3>Ты уже так много сделал сегодня! Большой отличник!</h3><p>Попробуем выполнить кое-что ещё?</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 14),
    (v_lesson, 'speaking', replace($blk${"title": "Давай проверим наши силы? 🎤", "html": "<p>Расскажи, в каком доме ты хотел бы жить. Что бы ты поставил или купил в каждую комнату?</p><p><i>Пример: I want a big house with a garden. In my bedroom there is a big bed and a wardrobe. In the living room there is a sofa and a TV.</i></p>", "needs_review": true}$blk$, '@@MEDIA@@', v_media)::jsonb, 15),
    (v_lesson, 'match', replace($blk${"title": "Ты выполнил все задания из основной части! А это дополнительное задание — для настоящих чемпионов! Соедини слова с картинкой ⭐", "pairs": [{"left_image": "@@MEDIA@@gg1/u3/part_door.webp", "right": "door", "right_audio_tts": "door"}, {"left_image": "@@MEDIA@@gg1/u3/part_window.webp", "right": "window", "right_audio_tts": "window"}, {"left_image": "@@MEDIA@@gg1/u3/furn_sofa.webp", "right": "sofa", "right_audio_tts": "sofa"}, {"left_image": "@@MEDIA@@gg1/u3/furn_wardrobe.webp", "right": "wardrobe", "right_audio_tts": "wardrobe"}, {"left_image": "@@MEDIA@@gg1/u3/room_garden.webp", "right": "garden", "right_audio_tts": "garden"}, {"left_image": "@@MEDIA@@gg1/u3/furn_fridge.webp", "right": "fridge", "right_audio_tts": "fridge"}, {"left_image": "@@MEDIA@@gg1/u3/room_garage.webp", "right": "garage", "right_audio_tts": "garage"}, {"left_image": "@@MEDIA@@gg1/u3/furn_armchair.webp", "right": "armchair", "right_audio_tts": "armchair"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 16),
    (v_lesson, 'exact_input', replace($blk${"title": "Впиши слова ⭐", "items": [{"prompt": "O L R O F", "accept": ["floor", "Floor"], "image": "@@MEDIA@@gg1/u3/part_floor.webp", "audio_tts": "floor"}, {"prompt": "D O R O", "accept": ["door", "Door"], "image": "@@MEDIA@@gg1/u3/part_door.webp", "audio_tts": "door"}, {"prompt": "L W A L", "accept": ["wall", "Wall"], "image": "@@MEDIA@@gg1/u3/part_wall.webp", "audio_tts": "wall"}, {"prompt": "T A B H", "accept": ["bath", "Bath"], "image": "@@MEDIA@@gg1/u3/furn_bath.webp", "audio_tts": "bath"}, {"prompt": "E B D", "accept": ["bed", "Bed"], "image": "@@MEDIA@@gg1/u3/furn_bed.webp", "audio_tts": "bed"}, {"prompt": "I H A R C", "accept": ["chair", "Chair"], "image": "@@MEDIA@@gg1/u0/obj_chair.webp", "audio_tts": "chair"}, {"prompt": "T A E B L", "accept": ["table", "Table"], "image": "@@MEDIA@@gg1/u3/furn_table.webp", "audio_tts": "table"}, {"prompt": "S F O A", "accept": ["sofa", "Sofa"], "image": "@@MEDIA@@gg1/u3/furn_sofa.webp", "audio_tts": "sofa"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 17),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_trophy.webp\" alt=\"\" style=\"height:180px\"></p><h3>Молодец! До скорых встреч! 🎉</h3><p>Увидимся на занятии!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 18);
end
$mig$;
