-- Go Getter 1 · Unit 8 · Sport and health · Homework 1
-- собрано tools/gg1_build.py --lesson u8_hw1
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where title = 'Go Getter 1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 8 · Sport and health', 8
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 8 · Sport and health');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 8 · Sport and health';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 1', 'homework',
         60, false, 0
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 1');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 1';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Hello! 👋</h2><p>Сегодня тебя ждёт изучение новых слов. Ты повторишь названия разных видов спорта. Давай начинать 😉</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"cards": [{"text": "badminton", "translation": "бадминтон", "audio_tts": "badminton", "image": "@@MEDIA@@gg1/u8/sport_badminton.webp"}, {"text": "basketball", "translation": "баскетбол", "audio_tts": "basketball", "image": "@@MEDIA@@gg1/u8/sport_basketball.webp"}, {"text": "cycling", "translation": "велосипедный спорт", "audio_tts": "cycling", "image": "@@MEDIA@@gg1/u8/sport_cycling.webp"}, {"text": "hockey", "translation": "хоккей", "audio_tts": "hockey", "image": "@@MEDIA@@gg1/u8/sport_hockey.webp"}, {"text": "ice-skating", "translation": "катание на коньках", "audio_tts": "ice-skating", "image": "@@MEDIA@@gg1/u8/sport_ice_skating.webp"}, {"text": "roller skating", "translation": "катание на роликовых коньках", "audio_tts": "roller skating", "image": "@@MEDIA@@gg1/u8/sport_roller_skating.webp"}, {"text": "sailing", "translation": "парусный спорт", "audio_tts": "sailing", "image": "@@MEDIA@@gg1/u8/sport_sailing.webp"}, {"text": "skateboarding", "translation": "скейтбординг", "audio_tts": "skateboarding", "image": "@@MEDIA@@gg1/u8/sport_skateboarding.webp"}, {"text": "skiing", "translation": "катание на лыжах", "audio_tts": "skiing", "image": "@@MEDIA@@gg1/u8/sport_skiing.webp"}, {"text": "swimming", "translation": "плавание", "audio_tts": "swimming", "image": "@@MEDIA@@gg1/u8/sport_swimming.webp"}, {"text": "table tennis", "translation": "настольный теннис", "audio_tts": "table tennis", "image": "@@MEDIA@@gg1/u8/sport_table_tennis.webp"}, {"text": "taekwondo", "translation": "тхэквондо", "audio_tts": "taekwondo", "image": "@@MEDIA@@gg1/u8/sport_taekwondo.webp"}, {"text": "tennis", "translation": "теннис", "audio_tts": "tennis", "image": "@@MEDIA@@gg1/u8/sport_tennis.webp"}, {"text": "volleyball", "translation": "волейбол", "audio_tts": "volleyball", "image": "@@MEDIA@@gg1/u8/sport_volleyball.webp"}, {"text": "windsurfing", "translation": "виндсерфинг", "audio_tts": "windsurfing", "image": "@@MEDIA@@gg1/u8/sport_windsurfing.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'match', replace($blk${"title": "Соедини картинку и слово", "pairs": [{"left_image": "@@MEDIA@@gg1/u8/sport_badminton.webp", "right": "badminton", "right_audio_tts": "badminton"}, {"left_image": "@@MEDIA@@gg1/u8/sport_basketball.webp", "right": "basketball", "right_audio_tts": "basketball"}, {"left_image": "@@MEDIA@@gg1/u8/sport_cycling.webp", "right": "cycling", "right_audio_tts": "cycling"}, {"left_image": "@@MEDIA@@gg1/u8/sport_hockey.webp", "right": "hockey", "right_audio_tts": "hockey"}, {"left_image": "@@MEDIA@@gg1/u8/sport_ice_skating.webp", "right": "ice-skating", "right_audio_tts": "ice-skating"}, {"left_image": "@@MEDIA@@gg1/u8/sport_roller_skating.webp", "right": "roller skating", "right_audio_tts": "roller skating"}, {"left_image": "@@MEDIA@@gg1/u8/sport_sailing.webp", "right": "sailing", "right_audio_tts": "sailing"}, {"left_image": "@@MEDIA@@gg1/u8/sport_skateboarding.webp", "right": "skateboarding", "right_audio_tts": "skateboarding"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'match', replace($blk${"title": "И ещё: соедини картинку и слово", "pairs": [{"left_image": "@@MEDIA@@gg1/u8/sport_skiing.webp", "right": "skiing", "right_audio_tts": "skiing"}, {"left_image": "@@MEDIA@@gg1/u8/sport_swimming.webp", "right": "swimming", "right_audio_tts": "swimming"}, {"left_image": "@@MEDIA@@gg1/u8/sport_table_tennis.webp", "right": "table tennis", "right_audio_tts": "table tennis"}, {"left_image": "@@MEDIA@@gg1/u8/sport_taekwondo.webp", "right": "taekwondo", "right_audio_tts": "taekwondo"}, {"left_image": "@@MEDIA@@gg1/u8/sport_tennis.webp", "right": "tennis", "right_audio_tts": "tennis"}, {"left_image": "@@MEDIA@@gg1/u8/sport_volleyball.webp", "right": "volleyball", "right_audio_tts": "volleyball"}, {"left_image": "@@MEDIA@@gg1/u8/sport_windsurfing.webp", "right": "windsurfing", "right_audio_tts": "windsurfing"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «бадминтон»?", "type": "single", "options": [{"text": "cycling"}, {"text": "badminton"}, {"text": "hockey"}, {"text": "basketball"}], "correct": [1]}, {"q": "Как по-английски «баскетбол»?", "type": "single", "options": [{"text": "hockey"}, {"text": "basketball"}, {"text": "cycling"}, {"text": "ice-skating"}], "correct": [1]}, {"q": "Как по-английски «велосипедный спорт»?", "type": "single", "options": [{"text": "cycling"}, {"text": "hockey"}, {"text": "ice-skating"}, {"text": "roller skating"}], "correct": [0]}, {"q": "Как по-английски «хоккей»?", "type": "single", "options": [{"text": "ice-skating"}, {"text": "roller skating"}, {"text": "sailing"}, {"text": "hockey"}], "correct": [3]}, {"q": "Как по-английски «катание на коньках»?", "type": "single", "options": [{"text": "roller skating"}, {"text": "sailing"}, {"text": "skateboarding"}, {"text": "ice-skating"}], "correct": [3]}, {"q": "Как по-английски «катание на роликовых коньках»?", "type": "single", "options": [{"text": "sailing"}, {"text": "badminton"}, {"text": "skateboarding"}, {"text": "roller skating"}], "correct": [3]}, {"q": "Как по-английски «парусный спорт»?", "type": "single", "options": [{"text": "badminton"}, {"text": "sailing"}, {"text": "skateboarding"}, {"text": "basketball"}], "correct": [1]}, {"q": "Как по-английски «скейтбординг»?", "type": "single", "options": [{"text": "badminton"}, {"text": "cycling"}, {"text": "basketball"}, {"text": "skateboarding"}], "correct": [3]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'exact_input', replace($blk${"title": "Посмотри на картинку и напиши слово по-английски", "items": [{"prompt": "катание на лыжах", "accept": ["skiing", "Skiing"], "image": "@@MEDIA@@gg1/u8/sport_skiing.webp", "audio_tts": "skiing"}, {"prompt": "плавание", "accept": ["swimming", "Swimming"], "image": "@@MEDIA@@gg1/u8/sport_swimming.webp", "audio_tts": "swimming"}, {"prompt": "настольный теннис", "accept": ["table tennis", "Table tennis"], "image": "@@MEDIA@@gg1/u8/sport_table_tennis.webp", "audio_tts": "table tennis"}, {"prompt": "тхэквондо", "accept": ["taekwondo", "Taekwondo"], "image": "@@MEDIA@@gg1/u8/sport_taekwondo.webp", "audio_tts": "taekwondo"}, {"prompt": "теннис", "accept": ["tennis", "Tennis"], "image": "@@MEDIA@@gg1/u8/sport_tennis.webp", "audio_tts": "tennis"}, {"prompt": "волейбол", "accept": ["volleyball", "Volleyball"], "image": "@@MEDIA@@gg1/u8/sport_volleyball.webp", "audio_tts": "volleyball"}, {"prompt": "виндсерфинг", "accept": ["windsurfing", "Windsurfing"], "image": "@@MEDIA@@gg1/u8/sport_windsurfing.webp", "audio_tts": "windsurfing"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'text', replace($blk${"html": "<h3>🌟 Привет, дружок! Рада снова видеть тебя на нашем домашнем задании!</h3><p>Сегодня мы будем говорить о спорте — это очень интересная тема. Настройся и приступай! 💪</p><p>Давай повторим всё, что выучили сегодня на уроке.</p><p><img src=\"@@MEDIA@@gg1/u8/card_sports.webp\" alt=\"Unit 8 Спорт\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'quiz', replace($blk${"title": "Посмотри на картинки. Выбери правильное слово", "questions": [{"q": "What sport is it?", "type": "single", "options": [{"text": "taekwondo"}, {"text": "cycling"}], "correct": [1], "image": "@@MEDIA@@gg1/u8/sport_cycling.webp"}, {"q": "What sport is it?", "type": "single", "options": [{"text": "hockey"}, {"text": "badminton"}], "correct": [0], "image": "@@MEDIA@@gg1/u8/sport_hockey.webp"}, {"q": "What sport is it?", "type": "single", "options": [{"text": "sailing"}, {"text": "windsurfing"}], "correct": [1], "image": "@@MEDIA@@gg1/u8/sport_windsurfing.webp"}, {"q": "What sport is it?", "type": "single", "options": [{"text": "volleyball"}, {"text": "basketball"}], "correct": [0], "image": "@@MEDIA@@gg1/u8/sport_volleyball.webp"}, {"q": "What sport is it?", "type": "single", "options": [{"text": "tennis"}, {"text": "table tennis"}], "correct": [1], "image": "@@MEDIA@@gg1/u8/sport_table_tennis.webp"}, {"q": "What sport is it?", "type": "single", "options": [{"text": "ice-skating"}, {"text": "roller skating"}], "correct": [0], "image": "@@MEDIA@@gg1/u8/sport_ice_skating.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'exact_input', replace($blk${"title": "Посмотри на картинки и подпиши виды спорта. Используй слова из первого задания", "items": [{"prompt": "1.", "accept": ["badminton", "Badminton"], "image": "@@MEDIA@@gg1/u8/sport_badminton.webp", "audio_tts": "badminton"}, {"prompt": "2.", "accept": ["basketball", "Basketball"], "image": "@@MEDIA@@gg1/u8/sport_basketball.webp", "audio_tts": "basketball"}, {"prompt": "3.", "accept": ["taekwondo", "Taekwondo"], "image": "@@MEDIA@@gg1/u8/sport_taekwondo.webp", "audio_tts": "taekwondo"}, {"prompt": "4.", "accept": ["sailing", "Sailing"], "image": "@@MEDIA@@gg1/u8/sport_sailing.webp", "audio_tts": "sailing"}, {"prompt": "5.", "accept": ["roller skating", "Roller skating", "roller-skating", "rollerskating"], "image": "@@MEDIA@@gg1/u8/sport_roller_skating.webp", "audio_tts": "roller skating"}, {"prompt": "6.", "accept": ["tennis", "Tennis"], "image": "@@MEDIA@@gg1/u8/sport_tennis.webp", "audio_tts": "tennis"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'quiz', replace($blk${"title": "Выбери правильное слово: go, do или play", "questions": [{"q": "___ ice-skating", "type": "single", "options": [{"text": "go"}, {"text": "do"}, {"text": "play"}], "correct": [0]}, {"q": "___ cycling", "type": "single", "options": [{"text": "go"}, {"text": "do"}, {"text": "play"}], "correct": [0]}, {"q": "___ taekwondo", "type": "single", "options": [{"text": "go"}, {"text": "do"}, {"text": "play"}], "correct": [1]}, {"q": "___ tennis", "type": "single", "options": [{"text": "go"}, {"text": "do"}, {"text": "play"}], "correct": [2]}, {"q": "___ football", "type": "single", "options": [{"text": "go"}, {"text": "do"}, {"text": "play"}], "correct": [2]}, {"q": "___ swimming", "type": "single", "options": [{"text": "go"}, {"text": "do"}, {"text": "play"}], "correct": [0]}, {"q": "___ sailing", "type": "single", "options": [{"text": "go"}, {"text": "do"}, {"text": "play"}], "correct": [0]}, {"q": "___ volleyball", "type": "single", "options": [{"text": "go"}, {"text": "do"}, {"text": "play"}], "correct": [2]}, {"q": "___ skiing", "type": "single", "options": [{"text": "go"}, {"text": "do"}, {"text": "play"}], "correct": [0]}, {"q": "___ badminton", "type": "single", "options": [{"text": "go"}, {"text": "do"}, {"text": "play"}], "correct": [2]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 9),
    (v_lesson, 'match', replace($blk${"title": "Соедини половинки предложений", "pairs": [{"left": "I sometimes play", "right": "badminton with my dad or my brother."}, {"left": "George does", "right": "taekwondo every Monday after school."}, {"left": "Do you go", "right": "skiing with your family?"}, {"left": "My brother plays", "right": "hockey with his friends."}, {"left": "Sandra never goes", "right": "ice-skating because she can't ice-skate."}, {"left": "Do you often play", "right": "basketball at school?"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 10),
    (v_lesson, 'speaking', replace($blk${"title": "Мой спорт 🎤", "html": "<p>Нажми на микрофон и расскажи, какими видами спорта ты занимаешься, а какими — нет. Используй глаголы do, go, play.</p><p><i>Пример: I play tennis and I go swimming, but I don't do taekwondo.</i></p>", "needs_review": true}$blk$, '@@MEDIA@@', v_media)::jsonb, 11),
    (v_lesson, 'match', replace($blk${"title": "Ты выполнил все задания из основной части! А это дополнительное задание — для настоящих чемпионов! Соедини слова с картинками ⭐", "pairs": [{"left": "go skiing", "left_audio_tts": "go skiing", "right_image": "@@MEDIA@@gg1/u8/sport_skiing.webp"}, {"left": "play hockey", "left_audio_tts": "play hockey", "right_image": "@@MEDIA@@gg1/u8/sport_hockey.webp"}, {"left": "go skateboarding", "left_audio_tts": "go skateboarding", "right_image": "@@MEDIA@@gg1/u8/sport_skateboarding.webp"}, {"left": "do taekwondo", "left_audio_tts": "do taekwondo", "right_image": "@@MEDIA@@gg1/u8/sport_taekwondo.webp"}, {"left": "play basketball", "left_audio_tts": "play basketball", "right_image": "@@MEDIA@@gg1/u8/sport_basketball.webp"}, {"left": "go swimming", "left_audio_tts": "go swimming", "right_image": "@@MEDIA@@gg1/u8/sport_swimming.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 12),
    (v_lesson, 'sort', replace($blk${"title": "Перетащи активности к подходящим глаголам ⭐", "groups": [{"name": "DO", "items": [{"text": "taekwondo"}, {"text": "exercise"}]}, {"name": "GO", "items": [{"text": "swimming"}, {"text": "cycling"}, {"text": "skiing"}, {"text": "sailing"}, {"text": "skateboarding"}, {"text": "ice-skating"}, {"text": "roller skating"}, {"text": "windsurfing"}]}, {"name": "PLAY", "items": [{"text": "basketball"}, {"text": "football"}, {"text": "hockey"}, {"text": "volleyball"}, {"text": "tennis"}, {"text": "badminton"}, {"text": "table tennis"}]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 13),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_trophy.webp\" alt=\"\" style=\"height:180px\"></p><h3>🎊 Ура-ура! Ты выполнил все задания и узнал много новых слов о спорте. Ты просто чемпион! 🏆</h3><p>Жду тебя на нашем следующем уроке!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 14);
end
$mig$;
