-- Go Getter 1 · Unit 6 · My day · Homework 1
-- собрано tools/gg1_build.py --lesson u6_hw1
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where title = 'Go Getter 1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 6 · My day', 6
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 6 · My day');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 6 · My day';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 1', 'homework',
         60, false, 0
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 1');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 1';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Hello! 👋</h2><p>В этом уроке тебя ждут упражнения на отработку новых слов — про то, что мы делаем каждый день. Выполни все, если хочешь выучить тему на все 100!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"cards": [{"text": "get up", "translation": "вставать", "audio_tts": "get up", "image": "@@MEDIA@@gg1/u6/da_get_up.webp"}, {"text": "go to school", "translation": "ходить в школу", "audio_tts": "go to school", "image": "@@MEDIA@@gg1/u6/da_go_to_school.webp"}, {"text": "have lessons", "translation": "учиться на уроках", "audio_tts": "have lessons", "image": "@@MEDIA@@gg1/u6/da_have_lessons.webp"}, {"text": "have breakfast", "translation": "завтракать", "audio_tts": "have breakfast", "image": "@@MEDIA@@gg1/u6/da_have_breakfast.webp"}, {"text": "have lunch", "translation": "обедать", "audio_tts": "have lunch", "image": "@@MEDIA@@gg1/u6/da_have_lunch.webp"}, {"text": "have dinner", "translation": "ужинать", "audio_tts": "have dinner", "image": "@@MEDIA@@gg1/u6/da_have_dinner.webp"}, {"text": "have a shower", "translation": "принимать душ", "audio_tts": "have a shower", "image": "@@MEDIA@@gg1/u6/da_have_a_shower.webp"}, {"text": "do my homework", "translation": "делать домашнее задание", "audio_tts": "do my homework", "image": "@@MEDIA@@gg1/u6/da_do_homework.webp"}, {"text": "tidy my room", "translation": "убираться в комнате", "audio_tts": "tidy my room", "image": "@@MEDIA@@gg1/u6/da_tidy_my_room.webp"}, {"text": "hang out with my friends", "translation": "тусоваться с друзьями", "audio_tts": "hang out with my friends", "image": "@@MEDIA@@gg1/u6/da_hang_out_with_friends.webp"}, {"text": "listen to music", "translation": "слушать музыку", "audio_tts": "listen to music", "image": "@@MEDIA@@gg1/u6/da_listen_to_music.webp"}, {"text": "watch TV", "translation": "смотреть телевизор", "audio_tts": "watch TV", "image": "@@MEDIA@@gg1/u6/da_watch_tv.webp"}, {"text": "go to bed", "translation": "ложиться спать", "audio_tts": "go to bed", "image": "@@MEDIA@@gg1/u6/da_go_to_bed.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'match', replace($blk${"title": "Соедини картинку и фразу", "pairs": [{"left_image": "@@MEDIA@@gg1/u6/da_get_up.webp", "right": "get up", "right_audio_tts": "get up"}, {"left_image": "@@MEDIA@@gg1/u6/da_go_to_school.webp", "right": "go to school", "right_audio_tts": "go to school"}, {"left_image": "@@MEDIA@@gg1/u6/da_have_lessons.webp", "right": "have lessons", "right_audio_tts": "have lessons"}, {"left_image": "@@MEDIA@@gg1/u6/da_have_breakfast.webp", "right": "have breakfast", "right_audio_tts": "have breakfast"}, {"left_image": "@@MEDIA@@gg1/u6/da_have_lunch.webp", "right": "have lunch", "right_audio_tts": "have lunch"}, {"left_image": "@@MEDIA@@gg1/u6/da_have_dinner.webp", "right": "have dinner", "right_audio_tts": "have dinner"}, {"left_image": "@@MEDIA@@gg1/u6/da_have_a_shower.webp", "right": "have a shower", "right_audio_tts": "have a shower"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'match', replace($blk${"title": "И ещё: соедини картинку и фразу", "pairs": [{"left_image": "@@MEDIA@@gg1/u6/da_do_homework.webp", "right": "do my homework", "right_audio_tts": "do my homework"}, {"left_image": "@@MEDIA@@gg1/u6/da_tidy_my_room.webp", "right": "tidy my room", "right_audio_tts": "tidy my room"}, {"left_image": "@@MEDIA@@gg1/u6/da_hang_out_with_friends.webp", "right": "hang out with my friends", "right_audio_tts": "hang out with my friends"}, {"left_image": "@@MEDIA@@gg1/u6/da_listen_to_music.webp", "right": "listen to music", "right_audio_tts": "listen to music"}, {"left_image": "@@MEDIA@@gg1/u6/da_watch_tv.webp", "right": "watch TV", "right_audio_tts": "watch TV"}, {"left_image": "@@MEDIA@@gg1/u6/da_go_to_bed.webp", "right": "go to bed", "right_audio_tts": "go to bed"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «вставать»?", "type": "single", "options": [{"text": "have breakfast"}, {"text": "go to school"}, {"text": "get up"}, {"text": "have lessons"}], "correct": [2]}, {"q": "Как по-английски «ходить в школу»?", "type": "single", "options": [{"text": "have breakfast"}, {"text": "have lunch"}, {"text": "have lessons"}, {"text": "go to school"}], "correct": [3]}, {"q": "Как по-английски «учиться на уроках»?", "type": "single", "options": [{"text": "have lunch"}, {"text": "have lessons"}, {"text": "have breakfast"}, {"text": "have dinner"}], "correct": [1]}, {"q": "Как по-английски «завтракать»?", "type": "single", "options": [{"text": "have lunch"}, {"text": "have a shower"}, {"text": "have breakfast"}, {"text": "have dinner"}], "correct": [2]}, {"q": "Как по-английски «обедать»?", "type": "single", "options": [{"text": "have dinner"}, {"text": "do my homework"}, {"text": "have lunch"}, {"text": "have a shower"}], "correct": [2]}, {"q": "Как по-английски «ужинать»?", "type": "single", "options": [{"text": "do my homework"}, {"text": "tidy my room"}, {"text": "have a shower"}, {"text": "have dinner"}], "correct": [3]}, {"q": "Как по-английски «принимать душ»?", "type": "single", "options": [{"text": "tidy my room"}, {"text": "do my homework"}, {"text": "have a shower"}, {"text": "hang out with my friends"}], "correct": [2]}, {"q": "Как по-английски «делать домашнее задание»?", "type": "single", "options": [{"text": "hang out with my friends"}, {"text": "do my homework"}, {"text": "tidy my room"}, {"text": "listen to music"}], "correct": [1]}, {"q": "Как по-английски «убираться в комнате»?", "type": "single", "options": [{"text": "watch TV"}, {"text": "listen to music"}, {"text": "tidy my room"}, {"text": "hang out with my friends"}], "correct": [2]}, {"q": "Как по-английски «тусоваться с друзьями»?", "type": "single", "options": [{"text": "listen to music"}, {"text": "hang out with my friends"}, {"text": "go to bed"}, {"text": "watch TV"}], "correct": [1]}, {"q": "Как по-английски «слушать музыку»?", "type": "single", "options": [{"text": "go to bed"}, {"text": "listen to music"}, {"text": "watch TV"}, {"text": "get up"}], "correct": [1]}, {"q": "Как по-английски «смотреть телевизор»?", "type": "single", "options": [{"text": "go to school"}, {"text": "watch TV"}, {"text": "get up"}, {"text": "go to bed"}], "correct": [1]}, {"q": "Как по-английски «ложиться спать»?", "type": "single", "options": [{"text": "go to bed"}, {"text": "have lessons"}, {"text": "go to school"}, {"text": "get up"}], "correct": [0]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'exact_input', replace($blk${"title": "Посмотри на картинку и напиши фразу по-английски", "items": [{"prompt": "вставать", "accept": ["get up", "Get up"], "image": "@@MEDIA@@gg1/u6/da_get_up.webp", "audio_tts": "get up"}, {"prompt": "ходить в школу", "accept": ["go to school", "Go to school"], "image": "@@MEDIA@@gg1/u6/da_go_to_school.webp", "audio_tts": "go to school"}, {"prompt": "завтракать", "accept": ["have breakfast", "Have breakfast"], "image": "@@MEDIA@@gg1/u6/da_have_breakfast.webp", "audio_tts": "have breakfast"}, {"prompt": "обедать", "accept": ["have lunch", "Have lunch"], "image": "@@MEDIA@@gg1/u6/da_have_lunch.webp", "audio_tts": "have lunch"}, {"prompt": "слушать музыку", "accept": ["listen to music", "Listen to music"], "image": "@@MEDIA@@gg1/u6/da_listen_to_music.webp", "audio_tts": "listen to music"}, {"prompt": "ложиться спать", "accept": ["go to bed", "Go to bed"], "image": "@@MEDIA@@gg1/u6/da_go_to_bed.webp", "audio_tts": "go to bed"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'text', replace($blk${"html": "<h3>Добро пожаловать во вторую часть домашнего задания! 👋</h3><p>Выполни все задания, чтобы хорошенько запомнить новые слова — и ты станешь МЕГА крутым учеником!</p><p>Давай повторим всё, что выучили сегодня на уроке.</p><p><img src=\"@@MEDIA@@gg1/u6/card_daily_activities.webp\" alt=\"Daily activities\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'gaps', replace($blk${"title": "Вставь глаголы в предложения по смыслу", "mode": "drag", "image": "@@MEDIA@@gg1/u6/girl_routine.webp", "text": "1. I __have__ lessons.\n2. I __get up__ in the morning.\n3. I __do__ my homework.\n4. I __go__ to bed.\n5. I __hang__ out with my friends."}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'match', replace($blk${"title": "Соедини начало и продолжение фраз. Не торопись 😉", "pairs": [{"left": "listen to", "right": "music"}, {"left": "tidy my", "right": "room"}, {"left": "have", "right": "lessons"}, {"left": "have a", "right": "shower"}, {"left": "do my", "right": "homework"}, {"left": "go to", "right": "school"}, {"left": "watch", "right": "TV"}, {"left": "hang out with", "right": "my friends"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'task', replace($blk${"title": "Мой день ✍️", "needs_review": true, "html": "<p><img src=\"@@MEDIA@@gg1/u6/routine_icons.webp\" alt=\"Daily routine\" style=\"height:220px\"></p><p>Напиши список того, что ты делаешь каждый день.</p><p><i>Пример: I get up. I have breakfast. I go to school…</i></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 9),
    (v_lesson, 'match', replace($blk${"title": "Ты выполнил все задания из основной части! А это дополнительное задание — для настоящих чемпионов! Соедини фразу и перевод ⭐", "pairs": [{"left": "get up", "right": "вставать", "left_audio_tts": "get up"}, {"left": "go to school", "right": "ходить в школу", "left_audio_tts": "go to school"}, {"left": "have lessons", "right": "учиться на уроках", "left_audio_tts": "have lessons"}, {"left": "have breakfast", "right": "завтракать", "left_audio_tts": "have breakfast"}, {"left": "have lunch", "right": "обедать", "left_audio_tts": "have lunch"}, {"left": "have dinner", "right": "ужинать", "left_audio_tts": "have dinner"}, {"left": "have a shower", "right": "принимать душ", "left_audio_tts": "have a shower"}, {"left": "do my homework", "right": "делать домашнее задание", "left_audio_tts": "do my homework"}, {"left": "tidy my room", "right": "убираться в комнате", "left_audio_tts": "tidy my room"}, {"left": "hang out with my friends", "right": "тусоваться с друзьями", "left_audio_tts": "hang out with my friends"}, {"left": "listen to music", "right": "слушать музыку", "left_audio_tts": "listen to music"}, {"left": "watch TV", "right": "смотреть телевизор", "left_audio_tts": "watch TV"}, {"left": "go to bed", "right": "ложиться спать", "left_audio_tts": "go to bed"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 10),
    (v_lesson, 'exact_input', replace($blk${"title": "Впиши фразы по-английски ⭐", "items": [{"prompt": "учиться на уроках", "accept": ["have lessons", "Have lessons"], "image": "@@MEDIA@@gg1/u6/da_have_lessons.webp", "audio_tts": "have lessons"}, {"prompt": "ужинать", "accept": ["have dinner", "Have dinner"], "image": "@@MEDIA@@gg1/u6/da_have_dinner.webp", "audio_tts": "have dinner"}, {"prompt": "принимать душ", "accept": ["have a shower", "Have a shower"], "image": "@@MEDIA@@gg1/u6/da_have_a_shower.webp", "audio_tts": "have a shower"}, {"prompt": "делать домашнее задание", "accept": ["do my homework", "Do my homework"], "image": "@@MEDIA@@gg1/u6/da_do_homework.webp", "audio_tts": "do my homework"}, {"prompt": "убираться в комнате", "accept": ["tidy my room", "Tidy my room"], "image": "@@MEDIA@@gg1/u6/da_tidy_my_room.webp", "audio_tts": "tidy my room"}, {"prompt": "смотреть телевизор", "accept": ["watch TV", "Watch TV", "watch tv", "Watch tv"], "image": "@@MEDIA@@gg1/u6/da_watch_tv.webp", "audio_tts": "watch TV"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 11),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/congrats_popper.webp\" alt=\"\" style=\"height:180px\"></p><h3>Поздравляю! Ты завершил домашнее задание. Ты — МЕГА КРУТ! 🎉</h3><p>Жду тебя на уроке!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 12);
end
$mig$;
