-- Go Getter 1 · Unit 0 · Get started! · Homework 2
-- собрано tools/gg1_build.py --lesson u0_hw2
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where title = 'Go Getter 1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 0 · Get started!', 0
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 0 · Get started!');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 0 · Get started!';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 2', 'homework',
         60, false, 1
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 2');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 2';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_book.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет! 👋</h2><p>Сейчас мы с тобой повторим цвета. Выполни все задания, чтобы выучить слова на 100%!</p><p><img src=\"@@MEDIA@@gg1/u0/card_colours.webp\" alt=\"Colours\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"cards": [{"text": "black", "translation": "чёрный", "audio_tts": "black", "image": "@@MEDIA@@gg1/u0/colour_black.svg"}, {"text": "blue", "translation": "синий", "audio_tts": "blue", "image": "@@MEDIA@@gg1/u0/colour_blue.svg"}, {"text": "brown", "translation": "коричневый", "audio_tts": "brown", "image": "@@MEDIA@@gg1/u0/colour_brown.svg"}, {"text": "green", "translation": "зелёный", "audio_tts": "green", "image": "@@MEDIA@@gg1/u0/colour_green.svg"}, {"text": "grey", "translation": "серый", "audio_tts": "grey", "image": "@@MEDIA@@gg1/u0/colour_grey.svg"}, {"text": "orange", "translation": "оранжевый", "audio_tts": "orange", "image": "@@MEDIA@@gg1/u0/colour_orange.svg"}, {"text": "pink", "translation": "розовый", "audio_tts": "pink", "image": "@@MEDIA@@gg1/u0/colour_pink.svg"}, {"text": "purple", "translation": "фиолетовый", "audio_tts": "purple", "image": "@@MEDIA@@gg1/u0/colour_purple.svg"}, {"text": "red", "translation": "красный", "audio_tts": "red", "image": "@@MEDIA@@gg1/u0/colour_red.svg"}, {"text": "white", "translation": "белый", "audio_tts": "white", "image": "@@MEDIA@@gg1/u0/colour_white.svg"}, {"text": "yellow", "translation": "жёлтый", "audio_tts": "yellow", "image": "@@MEDIA@@gg1/u0/colour_yellow.svg"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'match', replace($blk${"title": "Соедини цвет и слово", "pairs": [{"left_image": "@@MEDIA@@gg1/u0/colour_black.svg", "right": "black", "right_audio_tts": "black"}, {"left_image": "@@MEDIA@@gg1/u0/colour_blue.svg", "right": "blue", "right_audio_tts": "blue"}, {"left_image": "@@MEDIA@@gg1/u0/colour_brown.svg", "right": "brown", "right_audio_tts": "brown"}, {"left_image": "@@MEDIA@@gg1/u0/colour_green.svg", "right": "green", "right_audio_tts": "green"}, {"left_image": "@@MEDIA@@gg1/u0/colour_grey.svg", "right": "grey", "right_audio_tts": "grey"}, {"left_image": "@@MEDIA@@gg1/u0/colour_orange.svg", "right": "orange", "right_audio_tts": "orange"}, {"left_image": "@@MEDIA@@gg1/u0/colour_pink.svg", "right": "pink", "right_audio_tts": "pink"}, {"left_image": "@@MEDIA@@gg1/u0/colour_purple.svg", "right": "purple", "right_audio_tts": "purple"}, {"left_image": "@@MEDIA@@gg1/u0/colour_red.svg", "right": "red", "right_audio_tts": "red"}, {"left_image": "@@MEDIA@@gg1/u0/colour_white.svg", "right": "white", "right_audio_tts": "white"}, {"left_image": "@@MEDIA@@gg1/u0/colour_yellow.svg", "right": "yellow", "right_audio_tts": "yellow"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «чёрный»?", "type": "single", "options": [{"text": "blue"}, {"text": "brown"}, {"text": "black"}, {"text": "green"}], "correct": [2]}, {"q": "Как по-английски «синий»?", "type": "single", "options": [{"text": "green"}, {"text": "blue"}, {"text": "grey"}, {"text": "brown"}], "correct": [1]}, {"q": "Как по-английски «коричневый»?", "type": "single", "options": [{"text": "orange"}, {"text": "grey"}, {"text": "green"}, {"text": "brown"}], "correct": [3]}, {"q": "Как по-английски «зелёный»?", "type": "single", "options": [{"text": "pink"}, {"text": "orange"}, {"text": "grey"}, {"text": "green"}], "correct": [3]}, {"q": "Как по-английски «серый»?", "type": "single", "options": [{"text": "grey"}, {"text": "pink"}, {"text": "purple"}, {"text": "orange"}], "correct": [0]}, {"q": "Как по-английски «оранжевый»?", "type": "single", "options": [{"text": "pink"}, {"text": "orange"}, {"text": "purple"}, {"text": "red"}], "correct": [1]}, {"q": "Как по-английски «розовый»?", "type": "single", "options": [{"text": "white"}, {"text": "red"}, {"text": "purple"}, {"text": "pink"}], "correct": [3]}, {"q": "Как по-английски «фиолетовый»?", "type": "single", "options": [{"text": "red"}, {"text": "white"}, {"text": "yellow"}, {"text": "purple"}], "correct": [3]}, {"q": "Как по-английски «красный»?", "type": "single", "options": [{"text": "yellow"}, {"text": "white"}, {"text": "black"}, {"text": "red"}], "correct": [3]}, {"q": "Как по-английски «белый»?", "type": "single", "options": [{"text": "yellow"}, {"text": "blue"}, {"text": "white"}, {"text": "black"}], "correct": [2]}, {"q": "Как по-английски «жёлтый»?", "type": "single", "options": [{"text": "yellow"}, {"text": "blue"}, {"text": "brown"}, {"text": "black"}], "correct": [0]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'exact_input', replace($blk${"items": [{"prompt": "Напиши по-английски: чёрный", "accept": ["black", "Black"], "image": "@@MEDIA@@gg1/u0/colour_black.svg", "audio_tts": "black"}, {"prompt": "Напиши по-английски: синий", "accept": ["blue", "Blue"], "image": "@@MEDIA@@gg1/u0/colour_blue.svg", "audio_tts": "blue"}, {"prompt": "Напиши по-английски: коричневый", "accept": ["brown", "Brown"], "image": "@@MEDIA@@gg1/u0/colour_brown.svg", "audio_tts": "brown"}, {"prompt": "Напиши по-английски: зелёный", "accept": ["green", "Green"], "image": "@@MEDIA@@gg1/u0/colour_green.svg", "audio_tts": "green"}, {"prompt": "Напиши по-английски: серый", "accept": ["grey", "Grey"], "image": "@@MEDIA@@gg1/u0/colour_grey.svg", "audio_tts": "grey"}, {"prompt": "Напиши по-английски: оранжевый", "accept": ["orange", "Orange"], "image": "@@MEDIA@@gg1/u0/colour_orange.svg", "audio_tts": "orange"}, {"prompt": "Напиши по-английски: розовый", "accept": ["pink", "Pink"], "image": "@@MEDIA@@gg1/u0/colour_pink.svg", "audio_tts": "pink"}, {"prompt": "Напиши по-английски: фиолетовый", "accept": ["purple", "Purple"], "image": "@@MEDIA@@gg1/u0/colour_purple.svg", "audio_tts": "purple"}, {"prompt": "Напиши по-английски: красный", "accept": ["red", "Red"], "image": "@@MEDIA@@gg1/u0/colour_red.svg", "audio_tts": "red"}, {"prompt": "Напиши по-английски: белый", "accept": ["white", "White"], "image": "@@MEDIA@@gg1/u0/colour_white.svg", "audio_tts": "white"}, {"prompt": "Напиши по-английски: жёлтый", "accept": ["yellow", "Yellow"], "image": "@@MEDIA@@gg1/u0/colour_yellow.svg", "audio_tts": "yellow"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'text', replace($blk${"html": "<h3>Цвета выучены! 🎨</h3><p>Добро пожаловать во вторую часть домашнего задания! Тебя ждёт много интересных упражнений, а в конце — дополнительное задание: сделаешь его — получишь звёздочку! ⭐</p><p><img src=\"@@MEDIA@@gg1/u0/card_numbers.webp\" alt=\"Numbers 1–100\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'text', replace($blk${"html": "<p>Ты уже справился с несколькими заданиями! Посмотри на картинку — в следующем задании она понадобится.</p><p><img src=\"@@MEDIA@@gg1/u0/scene_zoo_colours.webp\" alt=\"Zoo painting\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'match', replace($blk${"title": "Посмотри на картинку и соедини начало и конец предложений по смыслу. У тебя получится!", "pairs": [{"left": "The elephants are", "right": "grey."}, {"left": "The zebras are", "right": "black and white."}, {"left": "The sky is", "right": "blue."}, {"left": "The oranges are", "right": "orange."}, {"left": "The lemons are", "right": "yellow."}, {"left": "The trees are", "right": "green."}, {"left": "The flamingoes are", "right": "pink."}, {"left": "The flowers are", "right": "red."}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'video', replace($blk${"title": "А теперь посмотри видео! Обязательно повторяй цифры и числа, постарайся запомнить — они тебе очень пригодятся!", "url": "", "provider": "youtube"}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'gaps', replace($blk${"title": "Прекрасная работа! Напиши числа словами в окошки", "mode": "type", "text": "1 = __One|one__\n2 = Two\n3 = Three\n4 = __Four|four__\n5 = Five\n6 = Six\n7 = __Seven|seven__\n8 = Eight\n9 = Nine\n10 = __Ten|ten__\n11 = Eleven\n12 = Twelve\n13 = __Thirteen|thirteen__\n14 = Fourteen\n15 = __Fifteen|fifteen__\n16 = Sixteen\n17 = Seventeen\n18 = __Eighteen|eighteen__\n19 = Nineteen\n20 = __Twenty|twenty__"}$blk$, '@@MEDIA@@', v_media)::jsonb, 9),
    (v_lesson, 'speaking', replace($blk${"title": "Опиши картинку 🎤", "image": "@@MEDIA@@gg1/u0/scene_zoo_colours.webp", "html": "<p>Опиши, что видишь на картинке. Нажми на микрофон и составь 3–4 предложения.</p><p><i>Пример: The lemons are yellow.</i></p>", "needs_review": true}$blk$, '@@MEDIA@@', v_media)::jsonb, 10),
    (v_lesson, 'quiz', replace($blk${"title": "Ты выполнил все задания из основной части! А это дополнительное задание — для настоящих чемпионов! Выбери подходящую цифру ⭐", "questions": [{"q": "thirteen", "type": "single", "options": [{"text": "3"}, {"text": "13"}, {"text": "30"}], "correct": [1]}, {"q": "fifty", "type": "single", "options": [{"text": "15"}, {"text": "5"}, {"text": "50"}], "correct": [2]}, {"q": "twelve", "type": "single", "options": [{"text": "12"}, {"text": "20"}, {"text": "2"}], "correct": [0]}, {"q": "forty", "type": "single", "options": [{"text": "14"}, {"text": "40"}, {"text": "4"}], "correct": [1]}, {"q": "eighteen", "type": "single", "options": [{"text": "80"}, {"text": "8"}, {"text": "18"}], "correct": [2]}, {"q": "a hundred", "type": "single", "options": [{"text": "10"}, {"text": "1000"}, {"text": "100"}], "correct": [2]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 11),
    (v_lesson, 'hotspot', replace($blk${"title": "Соедини: перетащи название цвета на картинку ⭐", "mode": "label", "image": "@@MEDIA@@gg1/u0/scene_zoo_colours.webp", "points": [{"x": 33.0, "y": 55.0, "text": "grey", "audio_tts": "grey"}, {"x": 57.0, "y": 40.0, "text": "pink", "audio_tts": "pink"}, {"x": 72.0, "y": 70.0, "text": "black and white", "audio_tts": "black and white"}, {"x": 47.0, "y": 80.0, "text": "red", "audio_tts": "red"}, {"x": 13.0, "y": 37.0, "text": "orange", "audio_tts": "orange"}, {"x": 88.0, "y": 50.0, "text": "yellow", "audio_tts": "yellow"}, {"x": 62.0, "y": 11.0, "text": "blue", "audio_tts": "blue"}, {"x": 77.0, "y": 22.0, "text": "green", "audio_tts": "green"}], "extras": []}$blk$, '@@MEDIA@@', v_media)::jsonb, 12),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_trophy.webp\" alt=\"\" style=\"height:180px\"></p><h3>Поздравляю! Ты завершил домашнее задание, ты замечательный ученик! 🎉</h3><p>Увидимся на занятии!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 13);
end
$mig$;
