-- Go Getter 1 · Unit 4 · Look at me · Homework 2
-- собрано tools/gg1_build.py --lesson u4_hw2
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where title = 'Go Getter 1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 4 · Look at me', 4
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 4 · Look at me');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 4 · Look at me';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 2', 'homework',
         60, false, 1
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 2');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 2';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_book.webp\" alt=\"\" style=\"height:200px\"></p><h2>Hello! 👋</h2><p>В домашнем задании мы вспомним, что проходили на уроке, и у нас будет путешествие в страну грамматики 😉</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"cards": [{"text": "arm", "translation": "рука (от плеча)", "audio_tts": "arm", "image": "@@MEDIA@@gg1/u4/body_arm.webp"}, {"text": "hand", "translation": "кисть руки", "audio_tts": "hand", "image": "@@MEDIA@@gg1/u4/body_hand.webp"}, {"text": "foot", "translation": "стопа", "audio_tts": "foot", "image": "@@MEDIA@@gg1/u4/body_foot.webp"}, {"text": "leg", "translation": "нога", "audio_tts": "leg", "image": "@@MEDIA@@gg1/u4/body_leg.webp"}, {"text": "head", "translation": "голова", "audio_tts": "head", "image": "@@MEDIA@@gg1/u4/body_head.webp"}, {"text": "fingers", "translation": "пальцы рук", "audio_tts": "fingers", "image": "@@MEDIA@@gg1/u4/body_fingers.webp"}, {"text": "toes", "translation": "пальцы ног", "audio_tts": "toes", "image": "@@MEDIA@@gg1/u4/body_toes.webp"}, {"text": "body", "translation": "тело", "audio_tts": "body", "image": "@@MEDIA@@gg1/u4/body_body.webp"}, {"text": "neck", "translation": "шея", "audio_tts": "neck", "image": "@@MEDIA@@gg1/u4/body_neck.webp"}, {"text": "feet", "translation": "ступни", "audio_tts": "feet", "image": "@@MEDIA@@gg1/u4/body_feet.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'match', replace($blk${"title": "Соедини картинку и слово", "pairs": [{"left_image": "@@MEDIA@@gg1/u4/body_arm.webp", "right": "arm", "right_audio_tts": "arm"}, {"left_image": "@@MEDIA@@gg1/u4/body_hand.webp", "right": "hand", "right_audio_tts": "hand"}, {"left_image": "@@MEDIA@@gg1/u4/body_foot.webp", "right": "foot", "right_audio_tts": "foot"}, {"left_image": "@@MEDIA@@gg1/u4/body_leg.webp", "right": "leg", "right_audio_tts": "leg"}, {"left_image": "@@MEDIA@@gg1/u4/body_head.webp", "right": "head", "right_audio_tts": "head"}, {"left_image": "@@MEDIA@@gg1/u4/body_fingers.webp", "right": "fingers", "right_audio_tts": "fingers"}, {"left_image": "@@MEDIA@@gg1/u4/body_toes.webp", "right": "toes", "right_audio_tts": "toes"}, {"left_image": "@@MEDIA@@gg1/u4/body_body.webp", "right": "body", "right_audio_tts": "body"}, {"left_image": "@@MEDIA@@gg1/u4/body_neck.webp", "right": "neck", "right_audio_tts": "neck"}, {"left_image": "@@MEDIA@@gg1/u4/body_feet.webp", "right": "feet", "right_audio_tts": "feet"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «рука (от плеча)»?", "type": "single", "options": [{"text": "leg"}, {"text": "arm"}, {"text": "foot"}, {"text": "hand"}], "correct": [1]}, {"q": "Как по-английски «кисть руки»?", "type": "single", "options": [{"text": "head"}, {"text": "hand"}, {"text": "leg"}, {"text": "foot"}], "correct": [1]}, {"q": "Как по-английски «стопа»?", "type": "single", "options": [{"text": "leg"}, {"text": "foot"}, {"text": "head"}, {"text": "fingers"}], "correct": [1]}, {"q": "Как по-английски «нога»?", "type": "single", "options": [{"text": "toes"}, {"text": "leg"}, {"text": "fingers"}, {"text": "head"}], "correct": [1]}, {"q": "Как по-английски «голова»?", "type": "single", "options": [{"text": "toes"}, {"text": "fingers"}, {"text": "head"}, {"text": "body"}], "correct": [2]}, {"q": "Как по-английски «пальцы рук»?", "type": "single", "options": [{"text": "toes"}, {"text": "fingers"}, {"text": "neck"}, {"text": "body"}], "correct": [1]}, {"q": "Как по-английски «пальцы ног»?", "type": "single", "options": [{"text": "toes"}, {"text": "neck"}, {"text": "body"}, {"text": "feet"}], "correct": [0]}, {"q": "Как по-английски «тело»?", "type": "single", "options": [{"text": "feet"}, {"text": "arm"}, {"text": "body"}, {"text": "neck"}], "correct": [2]}, {"q": "Как по-английски «шея»?", "type": "single", "options": [{"text": "neck"}, {"text": "arm"}, {"text": "hand"}, {"text": "feet"}], "correct": [0]}, {"q": "Как по-английски «ступни»?", "type": "single", "options": [{"text": "feet"}, {"text": "foot"}, {"text": "hand"}, {"text": "arm"}], "correct": [0]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'exact_input', replace($blk${"title": "Послушай и впиши слово", "items": [{"prompt": "рука (от плеча)", "accept": ["arm", "Arm"], "audio_tts": "arm"}, {"prompt": "кисть руки", "accept": ["hand", "Hand"], "audio_tts": "hand"}, {"prompt": "стопа", "accept": ["foot", "Foot"], "audio_tts": "foot"}, {"prompt": "нога", "accept": ["leg", "Leg"], "audio_tts": "leg"}, {"prompt": "голова", "accept": ["head", "Head"], "audio_tts": "head"}, {"prompt": "пальцы рук", "accept": ["fingers", "Fingers"], "audio_tts": "fingers"}, {"prompt": "пальцы ног", "accept": ["toes", "Toes"], "audio_tts": "toes"}, {"prompt": "тело", "accept": ["body", "Body"], "audio_tts": "body"}, {"prompt": "шея", "accept": ["neck", "Neck"], "audio_tts": "neck"}, {"prompt": "ступни", "accept": ["feet", "Feet"], "audio_tts": "feet"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'text', replace($blk${"html": "<h3>Have got / has got</h3><p>Для начала вспомним правило. <b>Have got / has got</b> нужны, чтобы сказать, что у нас что-то есть или, наоборот, нет.</p><ul><li><b>have got</b> — с местоимениями I, we, you, they и с множественным числом;</li><li><b>has got</b> — с местоимениями he, she, it и в 3-м лице единственного числа.</li></ul><p>Сейчас посмотри видео и вспомни, о чём мы говорили на уроке 😉</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'video', replace($blk${"title": "Have got / has got", "url": "", "provider": "youtube"}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'text', replace($blk${"html": "<p>Давай повторим всё, что выучили сегодня на уроке.</p><p><img src=\"@@MEDIA@@gg1/u4/card_have_got.webp\" alt=\"have got\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'gaps', replace($blk${"title": "Давай теперь потренируемся! Вставь have got / haven't got / has got / hasn't got", "mode": "drag", "text": "1. Mary __has got__ a car, but she __hasn't got__ a motorbike.\n2. John and Mary __have got__ blue eyes and dark hair, they are twins.\n3. Samantha __hasn't got__ a cat, but she __has got__ a dog, she is a dog lover.\n4. My sisters __have got__ dark hair.\n5. My mother __has got__ a small head and big ears.\n6. Alex __hasn't got__ a big face, his face is small.\n7. Trevor __hasn't got__ a mobile phone, he sends emails."}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'order', replace($blk${"title": "Давай расставим слова по порядку, чтобы получились предложения!", "words": ["I", "have got", "a lot of", "money."], "sentence": "I have got a lot of money.", "audio_tts": "I have got a lot of money."}$blk$, '@@MEDIA@@', v_media)::jsonb, 9),
    (v_lesson, 'order', replace($blk${"title": "Расставь слова в правильном порядке", "words": ["She", "has got", "brown hair", "and", "blue eyes."], "sentence": "She has got brown hair and blue eyes.", "audio_tts": "She has got brown hair and blue eyes."}$blk$, '@@MEDIA@@', v_media)::jsonb, 10),
    (v_lesson, 'order', replace($blk${"title": "Расставь слова в правильном порядке", "words": ["My", "sisters", "have got", "computers."], "sentence": "My sisters have got computers.", "audio_tts": "My sisters have got computers."}$blk$, '@@MEDIA@@', v_media)::jsonb, 11),
    (v_lesson, 'order', replace($blk${"title": "Расставь слова в правильном порядке", "words": ["Students", "have got", "books", "and copy-books."], "sentence": "Students have got books and copy-books.", "audio_tts": "Students have got books and copy-books."}$blk$, '@@MEDIA@@', v_media)::jsonb, 12),
    (v_lesson, 'order', replace($blk${"title": "Расставь слова в правильном порядке", "words": ["My dog", "has got", "a bone."], "sentence": "My dog has got a bone.", "audio_tts": "My dog has got a bone."}$blk$, '@@MEDIA@@', v_media)::jsonb, 13),
    (v_lesson, 'order', replace($blk${"title": "Расставь слова в правильном порядке", "words": ["They", "have got", "a large", "family."], "sentence": "They have got a large family.", "audio_tts": "They have got a large family."}$blk$, '@@MEDIA@@', v_media)::jsonb, 14),
    (v_lesson, 'task', replace($blk${"title": "Что есть у Molly и Nick?", "needs_review": true, "html": "<p><img src=\"@@MEDIA@@gg1/u4/venn_have_got.webp\" alt=\"Have got: Nick and Molly\" style=\"max-width:100%\"></p><p>Посмотри на картинку и напиши предложения о том, что есть у Molly и Nick. Подсказка: используй have got / has got.</p><ol><li>What has Molly got?</li><li>What has Nick got?</li><li>What have they got?</li></ol>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 15),
    (v_lesson, 'speaking', replace($blk${"title": "Мой рюкзак 🎤", "html": "<p>Нажми на микрофон и ответь на вопрос: <b>What have you got in your school bag today?</b></p><p><i>Пример: I've got two books, a pencil case and a bottle of water.</i></p>", "needs_review": true}$blk$, '@@MEDIA@@', v_media)::jsonb, 16),
    (v_lesson, 'quiz', replace($blk${"title": "Ты выполнил все задания из основной части! А это дополнительное задание — для настоящих чемпионов! Выбери правильный вариант ⭐", "questions": [{"q": "I ___ two brothers.", "type": "single", "options": [{"text": "have got"}, {"text": "has got"}], "correct": [0]}, {"q": "She ___ long curly hair.", "type": "single", "options": [{"text": "have got"}, {"text": "has got"}], "correct": [1]}, {"q": "My dog ___ big ears.", "type": "single", "options": [{"text": "has got"}, {"text": "have got"}], "correct": [0]}, {"q": "We ___ a cat. We've got a dog.", "type": "single", "options": [{"text": "hasn't got"}, {"text": "haven't got"}], "correct": [1]}, {"q": "Tom ___ a bike. He walks to school.", "type": "single", "options": [{"text": "hasn't got"}, {"text": "haven't got"}], "correct": [0]}, {"q": "They ___ blue eyes.", "type": "single", "options": [{"text": "has got"}, {"text": "have got"}], "correct": [1]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 17),
    (v_lesson, 'order', replace($blk${"title": "Расставь слова в правильном порядке ⭐", "words": ["He", "has", "got", "spiky", "hair."], "sentence": "He has got spiky hair.", "audio_tts": "He has got spiky hair."}$blk$, '@@MEDIA@@', v_media)::jsonb, 18),
    (v_lesson, 'order', replace($blk${"title": "Расставь слова в правильном порядке ⭐", "words": ["We", "haven't", "got", "a", "car."], "sentence": "We haven't got a car.", "audio_tts": "We haven't got a car."}$blk$, '@@MEDIA@@', v_media)::jsonb, 19),
    (v_lesson, 'order', replace($blk${"title": "Расставь слова в правильном порядке ⭐", "words": ["My", "cat", "has", "got", "green", "eyes."], "sentence": "My cat has got green eyes.", "audio_tts": "My cat has got green eyes."}$blk$, '@@MEDIA@@', v_media)::jsonb, 20),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_star.webp\" alt=\"\" style=\"height:180px\"></p><h3>Ты большой молодец сегодня! 🎉</h3><p>Ты получаешь звёздочку за прекрасный результат! До новых встреч!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 21);
end
$mig$;
