-- Go Getter 1 · Unit 4 · Look at me · Homework 1
-- собрано tools/gg1_build.py --lesson u4_hw1
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where title = 'Go Getter 1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 4 · Look at me', 4
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 4 · Look at me');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 4 · Look at me';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 1', 'homework',
         60, false, 0
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 1');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 1';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Hello! 👋</h2><p>Сегодня мы учим слова про лицо, тело и волосы. Выполни все задания, чтобы выучить их на все 100!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"cards": [{"text": "eyes", "translation": "глаза", "audio_tts": "eyes", "image": "@@MEDIA@@gg1/u4/body_eyes.webp"}, {"text": "nose", "translation": "нос", "audio_tts": "nose", "image": "@@MEDIA@@gg1/u4/body_nose.webp"}, {"text": "mouth", "translation": "рот", "audio_tts": "mouth", "image": "@@MEDIA@@gg1/u4/body_mouth.webp"}, {"text": "hair", "translation": "волосы", "audio_tts": "hair", "image": "@@MEDIA@@gg1/u4/body_hair.webp"}, {"text": "foot", "translation": "стопа", "audio_tts": "foot", "image": "@@MEDIA@@gg1/u4/body_foot.webp"}, {"text": "hand", "translation": "кисть руки", "audio_tts": "hand", "image": "@@MEDIA@@gg1/u4/body_hand.webp"}, {"text": "teeth", "translation": "зубы", "audio_tts": "teeth", "image": "@@MEDIA@@gg1/u4/body_teeth.webp"}, {"text": "ears", "translation": "уши", "audio_tts": "ears", "image": "@@MEDIA@@gg1/u4/body_ears.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'match', replace($blk${"title": "Найди пары", "pairs": [{"left": "eyes", "right": "глаза", "left_audio_tts": "eyes"}, {"left": "nose", "right": "нос", "left_audio_tts": "nose"}, {"left": "mouth", "right": "рот", "left_audio_tts": "mouth"}, {"left": "hair", "right": "волосы", "left_audio_tts": "hair"}, {"left": "foot", "right": "стопа", "left_audio_tts": "foot"}, {"left": "hand", "right": "кисть руки", "left_audio_tts": "hand"}, {"left": "teeth", "right": "зубы", "left_audio_tts": "teeth"}, {"left": "ears", "right": "уши", "left_audio_tts": "ears"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «глаза»?", "type": "single", "options": [{"text": "hair"}, {"text": "nose"}, {"text": "eyes"}, {"text": "mouth"}], "correct": [2]}, {"q": "Как по-английски «нос»?", "type": "single", "options": [{"text": "mouth"}, {"text": "hair"}, {"text": "nose"}, {"text": "foot"}], "correct": [2]}, {"q": "Как по-английски «рот»?", "type": "single", "options": [{"text": "mouth"}, {"text": "foot"}, {"text": "hair"}, {"text": "hand"}], "correct": [0]}, {"q": "Как по-английски «волосы»?", "type": "single", "options": [{"text": "teeth"}, {"text": "hair"}, {"text": "foot"}, {"text": "hand"}], "correct": [1]}, {"q": "Как по-английски «стопа»?", "type": "single", "options": [{"text": "teeth"}, {"text": "foot"}, {"text": "hand"}, {"text": "ears"}], "correct": [1]}, {"q": "Как по-английски «кисть руки»?", "type": "single", "options": [{"text": "hand"}, {"text": "eyes"}, {"text": "teeth"}, {"text": "ears"}], "correct": [0]}, {"q": "Как по-английски «зубы»?", "type": "single", "options": [{"text": "nose"}, {"text": "teeth"}, {"text": "ears"}, {"text": "eyes"}], "correct": [1]}, {"q": "Как по-английски «уши»?", "type": "single", "options": [{"text": "nose"}, {"text": "ears"}, {"text": "mouth"}, {"text": "eyes"}], "correct": [1]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'exact_input', replace($blk${"title": "Послушай и впиши слово", "items": [{"prompt": "глаза", "accept": ["eyes", "Eyes"], "audio_tts": "eyes"}, {"prompt": "нос", "accept": ["nose", "Nose"], "audio_tts": "nose"}, {"prompt": "рот", "accept": ["mouth", "Mouth"], "audio_tts": "mouth"}, {"prompt": "волосы", "accept": ["hair", "Hair"], "audio_tts": "hair"}, {"prompt": "стопа", "accept": ["foot", "Foot"], "audio_tts": "foot"}, {"prompt": "кисть руки", "accept": ["hand", "Hand"], "audio_tts": "hand"}, {"prompt": "зубы", "accept": ["teeth", "Teeth"], "audio_tts": "teeth"}, {"prompt": "уши", "accept": ["ears", "Ears"], "audio_tts": "ears"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'flashcards', replace($blk${"cards": [{"text": "red hair", "translation": "рыжие волосы", "audio_tts": "red hair", "image": "@@MEDIA@@gg1/u4/hair_red.webp"}, {"text": "spiky hair", "translation": "торчащие волосы (ёжиком)", "audio_tts": "spiky hair", "image": "@@MEDIA@@gg1/u4/hair_spiky.webp"}, {"text": "wavy hair", "translation": "волнистые волосы", "audio_tts": "wavy hair", "image": "@@MEDIA@@gg1/u4/hair_wavy.webp"}, {"text": "dark hair", "translation": "тёмные волосы", "audio_tts": "dark hair", "image": "@@MEDIA@@gg1/u4/hair_dark.webp"}, {"text": "curly hair", "translation": "кудрявые волосы", "audio_tts": "curly hair", "image": "@@MEDIA@@gg1/u4/hair_curly.webp"}, {"text": "straight hair", "translation": "прямые волосы", "audio_tts": "straight hair", "image": "@@MEDIA@@gg1/u4/hair_straight.webp"}, {"text": "blond hair", "translation": "светлые волосы (блонд)", "audio_tts": "blond hair", "image": "@@MEDIA@@gg1/u4/hair_blond.webp"}, {"text": "fair hair", "translation": "русые волосы", "audio_tts": "fair hair", "image": "@@MEDIA@@gg1/u4/hair_fair.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'match', replace($blk${"title": "Соедини картинку и слово", "pairs": [{"left_image": "@@MEDIA@@gg1/u4/hair_red.webp", "right": "red hair", "right_audio_tts": "red hair"}, {"left_image": "@@MEDIA@@gg1/u4/hair_spiky.webp", "right": "spiky hair", "right_audio_tts": "spiky hair"}, {"left_image": "@@MEDIA@@gg1/u4/hair_wavy.webp", "right": "wavy hair", "right_audio_tts": "wavy hair"}, {"left_image": "@@MEDIA@@gg1/u4/hair_dark.webp", "right": "dark hair", "right_audio_tts": "dark hair"}, {"left_image": "@@MEDIA@@gg1/u4/hair_curly.webp", "right": "curly hair", "right_audio_tts": "curly hair"}, {"left_image": "@@MEDIA@@gg1/u4/hair_straight.webp", "right": "straight hair", "right_audio_tts": "straight hair"}, {"left_image": "@@MEDIA@@gg1/u4/hair_blond.webp", "right": "blond hair", "right_audio_tts": "blond hair"}, {"left_image": "@@MEDIA@@gg1/u4/hair_fair.webp", "right": "fair hair", "right_audio_tts": "fair hair"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «рыжие волосы»?", "type": "single", "options": [{"text": "wavy hair"}, {"text": "dark hair"}, {"text": "red hair"}, {"text": "spiky hair"}], "correct": [2]}, {"q": "Как по-английски «торчащие волосы (ёжиком)»?", "type": "single", "options": [{"text": "spiky hair"}, {"text": "dark hair"}, {"text": "wavy hair"}, {"text": "curly hair"}], "correct": [0]}, {"q": "Как по-английски «волнистые волосы»?", "type": "single", "options": [{"text": "dark hair"}, {"text": "wavy hair"}, {"text": "curly hair"}, {"text": "straight hair"}], "correct": [1]}, {"q": "Как по-английски «тёмные волосы»?", "type": "single", "options": [{"text": "blond hair"}, {"text": "curly hair"}, {"text": "straight hair"}, {"text": "dark hair"}], "correct": [3]}, {"q": "Как по-английски «кудрявые волосы»?", "type": "single", "options": [{"text": "blond hair"}, {"text": "fair hair"}, {"text": "straight hair"}, {"text": "curly hair"}], "correct": [3]}, {"q": "Как по-английски «прямые волосы»?", "type": "single", "options": [{"text": "fair hair"}, {"text": "red hair"}, {"text": "blond hair"}, {"text": "straight hair"}], "correct": [3]}, {"q": "Как по-английски «светлые волосы (блонд)»?", "type": "single", "options": [{"text": "blond hair"}, {"text": "spiky hair"}, {"text": "fair hair"}, {"text": "red hair"}], "correct": [0]}, {"q": "Как по-английски «русые волосы»?", "type": "single", "options": [{"text": "red hair"}, {"text": "wavy hair"}, {"text": "spiky hair"}, {"text": "fair hair"}], "correct": [3]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'exact_input', replace($blk${"title": "Послушай и впиши слово", "items": [{"prompt": "рыжие волосы", "accept": ["red hair", "Red hair"], "audio_tts": "red hair"}, {"prompt": "торчащие волосы (ёжиком)", "accept": ["spiky hair", "Spiky hair"], "audio_tts": "spiky hair"}, {"prompt": "волнистые волосы", "accept": ["wavy hair", "Wavy hair"], "audio_tts": "wavy hair"}, {"prompt": "тёмные волосы", "accept": ["dark hair", "Dark hair"], "audio_tts": "dark hair"}, {"prompt": "кудрявые волосы", "accept": ["curly hair", "Curly hair"], "audio_tts": "curly hair"}, {"prompt": "прямые волосы", "accept": ["straight hair", "Straight hair"], "audio_tts": "straight hair"}, {"prompt": "светлые волосы (блонд)", "accept": ["blond hair", "Blond hair"], "audio_tts": "blond hair"}, {"prompt": "русые волосы", "accept": ["fair hair", "Fair hair"], "audio_tts": "fair hair"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'text', replace($blk${"html": "<h3>Добро пожаловать в третью часть домашнего задания! 👋</h3><p>Давай повторим всё, что выучили сегодня на уроке.</p><p><img src=\"@@MEDIA@@gg1/u4/card_face_body.webp\" alt=\"Face, Body & Hair\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 9),
    (v_lesson, 'gaps', replace($blk${"title": "Посмотри на картинку и напиши названия частей лица. Например, 1 — ear", "mode": "type", "image": "@@MEDIA@@gg1/u4/face_numbers.webp", "text": "1 — __ear|ears__\n2 — __hair__\n3 — __eye|eyes__\n4 — __nose__\n5 — __teeth|tooth__\n6 — __mouth__"}$blk$, '@@MEDIA@@', v_media)::jsonb, 10),
    (v_lesson, 'match', replace($blk${"title": "Соедини слово и картинку", "pairs": [{"left": "eyes", "right_image": "@@MEDIA@@gg1/u4/body_eyes.webp", "left_audio_tts": "eyes"}, {"left": "teeth", "right_image": "@@MEDIA@@gg1/u4/body_teeth.webp", "left_audio_tts": "teeth"}, {"left": "ears", "right_image": "@@MEDIA@@gg1/u4/body_ears.webp", "left_audio_tts": "ears"}, {"left": "nose", "right_image": "@@MEDIA@@gg1/u4/body_nose.webp", "left_audio_tts": "nose"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 11),
    (v_lesson, 'quiz', replace($blk${"title": "Какие у них волосы?", "questions": [{"q": "Посмотри на картинку. Выбери 2 слова, подходящие под описание волос.", "type": "multiple", "image": "@@MEDIA@@gg1/u4/kid_short_blond.webp", "options": [{"text": "long"}, {"text": "short"}, {"text": "red"}, {"text": "blond"}], "correct": [1, 3]}, {"q": "Посмотри на картинку. Выбери 2 слова, подходящие под описание волос.", "type": "multiple", "image": "@@MEDIA@@gg1/u4/kid_spiky_red.webp", "options": [{"text": "red"}, {"text": "straight"}, {"text": "spiky"}, {"text": "black"}], "correct": [2, 0]}, {"q": "Посмотри на картинку. Выбери 2 слова, подходящие под описание волос.", "type": "multiple", "image": "@@MEDIA@@gg1/u4/kid_curly_black.webp", "options": [{"text": "wavy"}, {"text": "black"}, {"text": "blond"}, {"text": "curly"}], "correct": [3, 1]}, {"q": "Посмотри на картинку. Выбери 2 слова, подходящие под описание волос.", "type": "multiple", "image": "@@MEDIA@@gg1/u4/kid_long_black.webp", "options": [{"text": "black"}, {"text": "short"}, {"text": "long"}, {"text": "blond"}], "correct": [2, 0]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 12),
    (v_lesson, 'order', replace($blk${"title": "Расставь слова в правильном порядке", "words": ["short", "straight", "blond", "hair"], "sentence": "short straight blond hair", "audio_tts": "short straight blond hair"}$blk$, '@@MEDIA@@', v_media)::jsonb, 13),
    (v_lesson, 'order', replace($blk${"title": "Расставь слова в правильном порядке", "words": ["big", "blue", "eyes"], "sentence": "big blue eyes", "audio_tts": "big blue eyes"}$blk$, '@@MEDIA@@', v_media)::jsonb, 14),
    (v_lesson, 'order', replace($blk${"title": "Расставь слова в правильном порядке", "words": ["long", "curly", "brown", "hair"], "sentence": "long curly brown hair", "audio_tts": "long curly brown hair"}$blk$, '@@MEDIA@@', v_media)::jsonb, 15),
    (v_lesson, 'order', replace($blk${"title": "Расставь слова в правильном порядке", "words": ["short", "wavy", "red", "hair"], "sentence": "short wavy red hair", "audio_tts": "short wavy red hair"}$blk$, '@@MEDIA@@', v_media)::jsonb, 16),
    (v_lesson, 'speaking', replace($blk${"title": "Глаза и волосы 🎤", "html": "<p>Выбери одного из членов семьи. Нажми на микрофон и расскажи, какие у него глаза и волосы.</p><p><i>Пример: small brown eyes, long straight red hair</i></p>", "needs_review": true}$blk$, '@@MEDIA@@', v_media)::jsonb, 17),
    (v_lesson, 'match', replace($blk${"title": "Ты выполнил все задания из основной части! А это дополнительное задание — для настоящих чемпионов! Соедини слова с картинками ⭐", "pairs": [{"left_image": "@@MEDIA@@gg1/u4/body_eyes.webp", "right": "eyes", "right_audio_tts": "eyes"}, {"left_image": "@@MEDIA@@gg1/u4/body_nose.webp", "right": "nose", "right_audio_tts": "nose"}, {"left_image": "@@MEDIA@@gg1/u4/body_mouth.webp", "right": "mouth", "right_audio_tts": "mouth"}, {"left_image": "@@MEDIA@@gg1/u4/body_hair.webp", "right": "hair", "right_audio_tts": "hair"}, {"left_image": "@@MEDIA@@gg1/u4/body_teeth.webp", "right": "teeth", "right_audio_tts": "teeth"}, {"left_image": "@@MEDIA@@gg1/u4/body_ears.webp", "right": "ears", "right_audio_tts": "ears"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 18),
    (v_lesson, 'exact_input', replace($blk${"title": "Впиши слова: собери слово из букв ⭐", "items": [{"prompt": "Y S E E", "accept": ["eyes", "Eyes"], "image": "@@MEDIA@@gg1/u4/body_eyes.webp", "audio_tts": "eyes"}, {"prompt": "S O E N", "accept": ["nose", "Nose"], "image": "@@MEDIA@@gg1/u4/body_nose.webp", "audio_tts": "nose"}, {"prompt": "O T M H U", "accept": ["mouth", "Mouth"], "image": "@@MEDIA@@gg1/u4/body_mouth.webp", "audio_tts": "mouth"}, {"prompt": "R A H I", "accept": ["hair", "Hair"], "image": "@@MEDIA@@gg1/u4/body_hair.webp", "audio_tts": "hair"}, {"prompt": "T O O F", "accept": ["foot", "Foot"], "image": "@@MEDIA@@gg1/u4/body_foot.webp", "audio_tts": "foot"}, {"prompt": "N A D H", "accept": ["hand", "Hand"], "image": "@@MEDIA@@gg1/u4/body_hand.webp", "audio_tts": "hand"}, {"prompt": "T H E T E", "accept": ["teeth", "Teeth"], "image": "@@MEDIA@@gg1/u4/body_teeth.webp", "audio_tts": "teeth"}, {"prompt": "S E R A", "accept": ["ears", "Ears"], "image": "@@MEDIA@@gg1/u4/body_ears.webp", "audio_tts": "ears"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 19),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_star.webp\" alt=\"\" style=\"height:180px\"></p><h3>Ты справился со всеми заданиями, ты большой молодец! 🎉</h3><p>Увидимся на занятии! Goodbye!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 20);
end
$mig$;
