-- Go Getter 1 · Unit 1 · Family and friends · Homework 1
-- собрано tools/gg1_build.py --lesson u1_hw1
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where title = 'Go Getter 1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 1 · Family and friends', 1
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 1 · Family and friends');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 1 · Family and friends';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 1', 'homework',
         60, false, 0
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 1');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 1';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Добро пожаловать в домашнее задание! 👋</h2><p>В этом уроке тебя ждут упражнения на отработку новых слов! Выполни все, если хочешь выучить тему на все 100!</p><p><img src=\"@@MEDIA@@gg1/u1/fam_family.webp\" alt=\"Family\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"cards": [{"text": "mother", "translation": "мать", "audio_tts": "mother", "image": "@@MEDIA@@gg1/u1/fam_mother.webp"}, {"text": "mum", "translation": "мама", "audio_tts": "mum", "image": "@@MEDIA@@gg1/u1/fam_mother.webp"}, {"text": "father", "translation": "отец", "audio_tts": "father", "image": "@@MEDIA@@gg1/u1/fam_father.webp"}, {"text": "dad", "translation": "папа", "audio_tts": "dad", "image": "@@MEDIA@@gg1/u1/fam_father.webp"}, {"text": "parents", "translation": "родители", "audio_tts": "parents", "image": "@@MEDIA@@gg1/u1/fam_parents.webp"}, {"text": "grandparents", "translation": "бабушка и дедушка", "audio_tts": "grandparents", "image": "@@MEDIA@@gg1/u1/fam_grandparents.webp"}, {"text": "grandfather", "translation": "дедушка", "audio_tts": "grandfather", "image": "@@MEDIA@@gg1/u1/fam_grandfather.webp"}, {"text": "grandad", "translation": "дед", "audio_tts": "grandad", "image": "@@MEDIA@@gg1/u1/fam_grandfather.webp"}, {"text": "grandmother", "translation": "бабушка", "audio_tts": "grandmother", "image": "@@MEDIA@@gg1/u1/fam_grandmother.webp"}, {"text": "granny", "translation": "бабуля", "audio_tts": "granny", "image": "@@MEDIA@@gg1/u1/fam_grandmother.webp"}, {"text": "son", "translation": "сын", "audio_tts": "son", "image": "@@MEDIA@@gg1/u1/fam_son.webp"}, {"text": "daughter", "translation": "дочь", "audio_tts": "daughter", "image": "@@MEDIA@@gg1/u1/fam_daughter.webp"}, {"text": "aunt", "translation": "тётя", "audio_tts": "aunt", "image": "@@MEDIA@@gg1/u1/fam_aunt.webp"}, {"text": "uncle", "translation": "дядя", "audio_tts": "uncle", "image": "@@MEDIA@@gg1/u1/fam_uncle.webp"}, {"text": "cousin", "translation": "двоюродный брат / сестра", "audio_tts": "cousin", "image": "@@MEDIA@@gg1/u1/fam_cousin.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'match', replace($blk${"title": "Соедини картинку и слово", "pairs": [{"left_image": "@@MEDIA@@gg1/u1/fam_mother.webp", "right": "mother", "right_audio_tts": "mother"}, {"left_image": "@@MEDIA@@gg1/u1/fam_father.webp", "right": "father", "right_audio_tts": "father"}, {"left_image": "@@MEDIA@@gg1/u1/fam_parents.webp", "right": "parents", "right_audio_tts": "parents"}, {"left_image": "@@MEDIA@@gg1/u1/fam_grandparents.webp", "right": "grandparents", "right_audio_tts": "grandparents"}, {"left_image": "@@MEDIA@@gg1/u1/fam_grandfather.webp", "right": "grandfather", "right_audio_tts": "grandfather"}, {"left_image": "@@MEDIA@@gg1/u1/fam_grandmother.webp", "right": "grandmother", "right_audio_tts": "grandmother"}, {"left_image": "@@MEDIA@@gg1/u1/fam_son.webp", "right": "son", "right_audio_tts": "son"}, {"left_image": "@@MEDIA@@gg1/u1/fam_daughter.webp", "right": "daughter", "right_audio_tts": "daughter"}, {"left_image": "@@MEDIA@@gg1/u1/fam_aunt.webp", "right": "aunt", "right_audio_tts": "aunt"}, {"left_image": "@@MEDIA@@gg1/u1/fam_uncle.webp", "right": "uncle", "right_audio_tts": "uncle"}, {"left_image": "@@MEDIA@@gg1/u1/fam_cousin.webp", "right": "cousin", "right_audio_tts": "cousin"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «мать»?", "type": "single", "options": [{"text": "grandparents"}, {"text": "father"}, {"text": "mother"}, {"text": "parents"}], "correct": [2]}, {"q": "Как по-английски «отец»?", "type": "single", "options": [{"text": "grandfather"}, {"text": "grandparents"}, {"text": "father"}, {"text": "parents"}], "correct": [2]}, {"q": "Как по-английски «родители»?", "type": "single", "options": [{"text": "grandmother"}, {"text": "grandparents"}, {"text": "grandfather"}, {"text": "parents"}], "correct": [3]}, {"q": "Как по-английски «бабушка и дедушка»?", "type": "single", "options": [{"text": "grandfather"}, {"text": "grandparents"}, {"text": "grandmother"}, {"text": "son"}], "correct": [1]}, {"q": "Как по-английски «дедушка»?", "type": "single", "options": [{"text": "grandfather"}, {"text": "daughter"}, {"text": "grandmother"}, {"text": "son"}], "correct": [0]}, {"q": "Как по-английски «бабушка»?", "type": "single", "options": [{"text": "daughter"}, {"text": "aunt"}, {"text": "son"}, {"text": "grandmother"}], "correct": [3]}, {"q": "Как по-английски «сын»?", "type": "single", "options": [{"text": "son"}, {"text": "daughter"}, {"text": "aunt"}, {"text": "uncle"}], "correct": [0]}, {"q": "Как по-английски «дочь»?", "type": "single", "options": [{"text": "uncle"}, {"text": "daughter"}, {"text": "aunt"}, {"text": "cousin"}], "correct": [1]}, {"q": "Как по-английски «тётя»?", "type": "single", "options": [{"text": "uncle"}, {"text": "mother"}, {"text": "cousin"}, {"text": "aunt"}], "correct": [3]}, {"q": "Как по-английски «дядя»?", "type": "single", "options": [{"text": "uncle"}, {"text": "cousin"}, {"text": "mother"}, {"text": "father"}], "correct": [0]}, {"q": "Как по-английски «двоюродный брат / сестра»?", "type": "single", "options": [{"text": "mother"}, {"text": "father"}, {"text": "parents"}, {"text": "cousin"}], "correct": [3]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'match', replace($blk${"title": "Как сказать то же самое по-домашнему? Соедини пары", "pairs": [{"left": "mother", "right": "mum"}, {"left": "father", "right": "dad"}, {"left": "grandmother", "right": "granny"}, {"left": "grandfather", "right": "grandad"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'text', replace($blk${"html": "<h3>Hello! 👋</h3><p>На занятии мы говорили о членах семьи, повторим? Приступим!</p><p>Давай повторим всё, что выучили сегодня на уроке.</p><p><img src=\"@@MEDIA@@gg1/u1/card_family.webp\" alt=\"Unit 1 Family\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'hotspot', replace($blk${"title": "Посмотри на семью Салли — Салли в середине, в джинсовом комбинезоне. Где кто? Подпиши", "mode": "label", "image": "@@MEDIA@@gg1/u1/scene_sally_family.webp", "points": [{"x": 10.0, "y": 60.0, "text": "Sally's grandfather"}, {"x": 24.0, "y": 57.0, "text": "Sally's grandmother"}, {"x": 38.0, "y": 55.0, "text": "Sally's father"}, {"x": 51.0, "y": 52.0, "text": "Sally's mother"}, {"x": 78.0, "y": 68.0, "text": "Sally's sister"}, {"x": 90.0, "y": 60.0, "text": "Sally's brother"}], "extras": ["Sally's cousin"]}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'gaps', replace($blk${"title": "Посмотри на семейное древо Марка. Заполни предложения одним словом", "mode": "type", "image": "@@MEDIA@@gg1/u1/tree_mark.webp", "text": "Alan: Nick is my father. He's David's __father__ too.\nHolly: Ruth is my __aunt__. Steven and I are Mark's __cousins__. I am Helen and Rob's __daughter__.\nSteven: Holly is my __sister__. I'm Helen's __son__."}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'match', replace($blk${"title": "Найди половинки слов и составь слова, обозначающие членов семьи", "pairs": [{"left": "daught", "right": "er"}, {"left": "cous", "right": "in"}, {"left": "unc", "right": "le"}, {"left": "grand", "right": "ad"}, {"left": "au", "right": "nt"}, {"left": "gran", "right": "ny"}, {"left": "s", "right": "on"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'speaking', replace($blk${"title": "Моя семья 🎤", "html": "<p>Нажми на микрофон и перечисли членов твоей семьи.</p><p><i>Пример: This is my family: my mum, my dad, my granny…</i></p>", "needs_review": true}$blk$, '@@MEDIA@@', v_media)::jsonb, 9),
    (v_lesson, 'exact_input', replace($blk${"title": "Ты выполнил все задания из основной части! А это дополнительное задание — для настоящих чемпионов! Собери слово из букв ⭐", "items": [{"prompt": "E M R T O H", "accept": ["mother", "Mother"], "image": "@@MEDIA@@gg1/u1/fam_mother.webp", "audio_tts": "mother"}, {"prompt": "E R T F A H", "accept": ["father", "Father"], "image": "@@MEDIA@@gg1/u1/fam_father.webp", "audio_tts": "father"}, {"prompt": "T N R P A E S", "accept": ["parents", "Parents"], "image": "@@MEDIA@@gg1/u1/fam_parents.webp", "audio_tts": "parents"}, {"prompt": "N A E G T R N A S P D R", "accept": ["grandparents", "Grandparents"], "image": "@@MEDIA@@gg1/u1/fam_grandparents.webp", "audio_tts": "grandparents"}, {"prompt": "R R G T E F D N H A A", "accept": ["grandfather", "Grandfather"], "image": "@@MEDIA@@gg1/u1/fam_grandfather.webp", "audio_tts": "grandfather"}, {"prompt": "N M A R O G T D H R E", "accept": ["grandmother", "Grandmother"], "image": "@@MEDIA@@gg1/u1/fam_grandmother.webp", "audio_tts": "grandmother"}, {"prompt": "N O S", "accept": ["son", "Son"], "image": "@@MEDIA@@gg1/u1/fam_son.webp", "audio_tts": "son"}, {"prompt": "E H G R A T D U", "accept": ["daughter", "Daughter"], "image": "@@MEDIA@@gg1/u1/fam_daughter.webp", "audio_tts": "daughter"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 10),
    (v_lesson, 'match', replace($blk${"title": "Соедини пары ⭐", "pairs": [{"left": "mum", "right": "мама", "left_audio_tts": "mum"}, {"left": "dad", "right": "папа", "left_audio_tts": "dad"}, {"left": "granny", "right": "бабуля", "left_audio_tts": "granny"}, {"left": "son", "right": "сын", "left_audio_tts": "son"}, {"left": "daughter", "right": "дочь", "left_audio_tts": "daughter"}, {"left": "aunt", "right": "тётя", "left_audio_tts": "aunt"}, {"left": "uncle", "right": "дядя", "left_audio_tts": "uncle"}, {"left": "cousin", "right": "двоюродный брат / сестра", "left_audio_tts": "cousin"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 11),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_trophy.webp\" alt=\"\" style=\"height:180px\"></p><h3>У тебя отлично получилось! 🎉</h3><p>Увидимся на занятии!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 12);
end
$mig$;
