-- Go Getter 1 · Unit 5 · I can do it · Homework 1
-- собрано tools/gg1_build.py --lesson u5_hw1
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where title = 'Go Getter 1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 5 · I can do it', 5
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 5 · I can do it');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 5 · I can do it';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 1', 'homework',
         60, false, 0
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 1');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 1';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Hello! 👋</h2><p>Давай скорее приступим к домашнему заданию! Сегодня мы учим глаголы действия — слова, которые рассказывают, что мы умеем делать.</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"cards": [{"text": "act", "translation": "выступать на сцене", "audio_tts": "act", "image": "@@MEDIA@@gg1/u5/verb_act.webp"}, {"text": "climb", "translation": "лазать, карабкаться", "audio_tts": "climb", "image": "@@MEDIA@@gg1/u5/verb_climb.webp"}, {"text": "cook", "translation": "готовить еду", "audio_tts": "cook", "image": "@@MEDIA@@gg1/u5/verb_cook.webp"}, {"text": "dive", "translation": "нырять", "audio_tts": "dive", "image": "@@MEDIA@@gg1/u5/verb_dive.webp"}, {"text": "fix", "translation": "чинить", "audio_tts": "fix", "image": "@@MEDIA@@gg1/u5/verb_fix.webp"}, {"text": "fly", "translation": "летать", "audio_tts": "fly", "image": "@@MEDIA@@gg1/u5/verb_fly.webp"}, {"text": "jump", "translation": "прыгать", "audio_tts": "jump", "image": "@@MEDIA@@gg1/u5/verb_jump.webp"}, {"text": "read", "translation": "читать", "audio_tts": "read", "image": "@@MEDIA@@gg1/u5/verb_read.webp"}, {"text": "ride", "translation": "ездить верхом, кататься", "audio_tts": "ride", "image": "@@MEDIA@@gg1/u5/verb_ride.webp"}, {"text": "sing", "translation": "петь", "audio_tts": "sing", "image": "@@MEDIA@@gg1/u5/verb_sing.webp"}, {"text": "run", "translation": "бегать", "audio_tts": "run", "image": "@@MEDIA@@gg1/u5/verb_run.webp"}, {"text": "swim", "translation": "плавать", "audio_tts": "swim", "image": "@@MEDIA@@gg1/u5/verb_swim.webp"}, {"text": "write", "translation": "писать", "audio_tts": "write", "image": "@@MEDIA@@gg1/u5/verb_write.webp"}, {"text": "skateboard", "translation": "кататься на скейтборде", "audio_tts": "skateboard", "image": "@@MEDIA@@gg1/u5/verb_skateboard.webp"}, {"text": "draw", "translation": "рисовать", "audio_tts": "draw", "image": "@@MEDIA@@gg1/u5/verb_draw.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'match', replace($blk${"title": "Соедини картинку и слово", "pairs": [{"left_image": "@@MEDIA@@gg1/u5/verb_act.webp", "right": "act", "right_audio_tts": "act"}, {"left_image": "@@MEDIA@@gg1/u5/verb_climb.webp", "right": "climb", "right_audio_tts": "climb"}, {"left_image": "@@MEDIA@@gg1/u5/verb_cook.webp", "right": "cook", "right_audio_tts": "cook"}, {"left_image": "@@MEDIA@@gg1/u5/verb_dive.webp", "right": "dive", "right_audio_tts": "dive"}, {"left_image": "@@MEDIA@@gg1/u5/verb_fix.webp", "right": "fix", "right_audio_tts": "fix"}, {"left_image": "@@MEDIA@@gg1/u5/verb_fly.webp", "right": "fly", "right_audio_tts": "fly"}, {"left_image": "@@MEDIA@@gg1/u5/verb_jump.webp", "right": "jump", "right_audio_tts": "jump"}, {"left_image": "@@MEDIA@@gg1/u5/verb_read.webp", "right": "read", "right_audio_tts": "read"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'match', replace($blk${"title": "И ещё: соедини картинку и слово", "pairs": [{"left_image": "@@MEDIA@@gg1/u5/verb_ride.webp", "right": "ride", "right_audio_tts": "ride"}, {"left_image": "@@MEDIA@@gg1/u5/verb_sing.webp", "right": "sing", "right_audio_tts": "sing"}, {"left_image": "@@MEDIA@@gg1/u5/verb_run.webp", "right": "run", "right_audio_tts": "run"}, {"left_image": "@@MEDIA@@gg1/u5/verb_swim.webp", "right": "swim", "right_audio_tts": "swim"}, {"left_image": "@@MEDIA@@gg1/u5/verb_write.webp", "right": "write", "right_audio_tts": "write"}, {"left_image": "@@MEDIA@@gg1/u5/verb_skateboard.webp", "right": "skateboard", "right_audio_tts": "skateboard"}, {"left_image": "@@MEDIA@@gg1/u5/verb_draw.webp", "right": "draw", "right_audio_tts": "draw"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «выступать на сцене»?", "type": "single", "options": [{"text": "act"}, {"text": "dive"}, {"text": "cook"}, {"text": "climb"}], "correct": [0]}, {"q": "Как по-английски «лазать, карабкаться»?", "type": "single", "options": [{"text": "fix"}, {"text": "climb"}, {"text": "cook"}, {"text": "dive"}], "correct": [1]}, {"q": "Как по-английски «готовить еду»?", "type": "single", "options": [{"text": "dive"}, {"text": "fix"}, {"text": "cook"}, {"text": "fly"}], "correct": [2]}, {"q": "Как по-английски «нырять»?", "type": "single", "options": [{"text": "fly"}, {"text": "fix"}, {"text": "jump"}, {"text": "dive"}], "correct": [3]}, {"q": "Как по-английски «чинить»?", "type": "single", "options": [{"text": "fix"}, {"text": "read"}, {"text": "fly"}, {"text": "jump"}], "correct": [0]}, {"q": "Как по-английски «летать»?", "type": "single", "options": [{"text": "act"}, {"text": "fly"}, {"text": "jump"}, {"text": "read"}], "correct": [1]}, {"q": "Как по-английски «прыгать»?", "type": "single", "options": [{"text": "act"}, {"text": "climb"}, {"text": "jump"}, {"text": "read"}], "correct": [2]}, {"q": "Как по-английски «читать»?", "type": "single", "options": [{"text": "climb"}, {"text": "cook"}, {"text": "act"}, {"text": "read"}], "correct": [3]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'exact_input', replace($blk${"title": "Посмотри на картинку и напиши слово по-английски", "items": [{"prompt": "ездить верхом, кататься", "accept": ["ride", "Ride"], "image": "@@MEDIA@@gg1/u5/verb_ride.webp", "audio_tts": "ride"}, {"prompt": "петь", "accept": ["sing", "Sing"], "image": "@@MEDIA@@gg1/u5/verb_sing.webp", "audio_tts": "sing"}, {"prompt": "бегать", "accept": ["run", "Run"], "image": "@@MEDIA@@gg1/u5/verb_run.webp", "audio_tts": "run"}, {"prompt": "плавать", "accept": ["swim", "Swim"], "image": "@@MEDIA@@gg1/u5/verb_swim.webp", "audio_tts": "swim"}, {"prompt": "писать", "accept": ["write", "Write"], "image": "@@MEDIA@@gg1/u5/verb_write.webp", "audio_tts": "write"}, {"prompt": "кататься на скейтборде", "accept": ["skateboard", "Skateboard"], "image": "@@MEDIA@@gg1/u5/verb_skateboard.webp", "audio_tts": "skateboard"}, {"prompt": "рисовать", "accept": ["draw", "Draw"], "image": "@@MEDIA@@gg1/u5/verb_draw.webp", "audio_tts": "draw"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'text', replace($blk${"html": "<h3>Добро пожаловать во вторую часть домашнего задания! 👋</h3><p>Давай повторим всё, что выучили сегодня на уроке.</p><p><img src=\"@@MEDIA@@gg1/u5/card_action_verbs.webp\" alt=\"Action verbs\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'hotspot', replace($blk${"title": "Посмотри на картинку. Подпиши, кто что делает (буквы a–h)", "mode": "label", "image": "@@MEDIA@@gg1/u5/beach_actions.webp", "points": [{"x": 73.0, "y": 6.0, "text": "fly"}, {"x": 30.0, "y": 32.5, "text": "ride"}, {"x": 58.0, "y": 44.5, "text": "dive"}, {"x": 73.0, "y": 30.0, "text": "swim"}, {"x": 7.0, "y": 67.0, "text": "draw"}, {"x": 41.5, "y": 60.0, "text": "jump"}, {"x": 43.0, "y": 78.0, "text": "run"}, {"x": 72.0, "y": 75.0, "text": "skateboard"}], "extras": []}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'exact_input', replace($blk${"title": "Убери две лишние буквы, чтобы найти глаголы действия. Запиши слова, которые нашёл. Пример: D I R V S E → dive", "items": [{"prompt": "A E C T M", "accept": ["act", "Act"]}, {"prompt": "I S I R N G", "accept": ["sing", "Sing"]}, {"prompt": "C O R O A K", "accept": ["cook", "Cook"]}, {"prompt": "W O R I T D E", "accept": ["write", "Write"]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'gaps', replace($blk${"title": "Посмотри на картинку и заполни пропуски", "mode": "drag", "image": "@@MEDIA@@gg1/u5/verbs_objects.webp", "text": "1. read a newspaper (пример)\n2. __fix__ a wardrobe with a screwdriver\n3. __write__ with a pen\n4. __run__ in new trainers\n5. __swim__ with goggles"}$blk$, '@@MEDIA@@', v_media)::jsonb, 9),
    (v_lesson, 'speaking', replace($blk${"title": "Мои любимые действия 🎤", "html": "<p>Нажми на микрофон и назови несколько действий, которые ты больше всего любишь.</p><p><i>Пример: run, swim, fix.</i></p>", "needs_review": true}$blk$, '@@MEDIA@@', v_media)::jsonb, 10),
    (v_lesson, 'quiz', replace($blk${"title": "Ты выполнил все задания из основной части! А это дополнительное задание — для настоящих чемпионов! Выбери подходящее слово ⭐", "questions": [{"q": "A kangaroo can ___.", "type": "single", "options": [{"text": "write"}, {"text": "jump"}, {"text": "fly"}], "correct": [1], "image": "@@MEDIA@@gg1/u5/verb_jump.webp"}, {"q": "A bird can ___.", "type": "single", "options": [{"text": "cook"}, {"text": "read"}, {"text": "fly"}], "correct": [2], "image": "@@MEDIA@@gg1/u5/verb_fly.webp"}, {"q": "A dolphin can ___.", "type": "single", "options": [{"text": "swim"}, {"text": "sing"}, {"text": "climb"}], "correct": [0], "image": "@@MEDIA@@gg1/u5/verb_swim.webp"}, {"q": "A monkey can ___ a tree.", "type": "single", "options": [{"text": "dive"}, {"text": "climb"}, {"text": "act"}], "correct": [1], "image": "@@MEDIA@@gg1/u5/verb_climb.webp"}, {"q": "A cheetah can ___ fast.", "type": "single", "options": [{"text": "write"}, {"text": "fix"}, {"text": "run"}], "correct": [2], "image": "@@MEDIA@@gg1/u5/verb_run.webp"}, {"q": "I can ___ a book.", "type": "single", "options": [{"text": "read"}, {"text": "ride"}, {"text": "jump"}], "correct": [0], "image": "@@MEDIA@@gg1/u5/verb_read.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 11),
    (v_lesson, 'exact_input', replace($blk${"title": "Впиши слово ⭐", "items": [{"prompt": "c _ o k", "accept": ["cook", "Cook"], "image": "@@MEDIA@@gg1/u5/verb_cook.webp", "audio_tts": "cook"}, {"prompt": "s _ n g", "accept": ["sing", "Sing"], "image": "@@MEDIA@@gg1/u5/verb_sing.webp", "audio_tts": "sing"}, {"prompt": "d _ v e", "accept": ["dive", "Dive"], "image": "@@MEDIA@@gg1/u5/verb_dive.webp", "audio_tts": "dive"}, {"prompt": "f _ x", "accept": ["fix", "Fix"], "image": "@@MEDIA@@gg1/u5/verb_fix.webp", "audio_tts": "fix"}, {"prompt": "w _ i _ e", "accept": ["write", "Write"], "image": "@@MEDIA@@gg1/u5/verb_write.webp", "audio_tts": "write"}, {"prompt": "s _ a _ e _ o _ r d", "accept": ["skateboard", "Skateboard"], "image": "@@MEDIA@@gg1/u5/verb_skateboard.webp", "audio_tts": "skateboard"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 12),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_star.webp\" alt=\"\" style=\"height:180px\"></p><h3>Ты большой молодец! 🎉</h3><p>Увидимся на занятии!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 13);
end
$mig$;
