-- Go Getter 1 · Unit 3 · My home · Homework 5
-- собрано tools/gg1_build.py --lesson u3_hw5
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where title = 'Go Getter 1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 3 · My home', 3
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 3 · My home');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 3 · My home';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 5', 'homework',
         60, false, 4
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 5');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 5';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_headphones.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет! 👋</h2><p>Добро пожаловать в мир домашнего задания! Сегодня мы будем усердно работать, чтобы получить большую звёздочку! Сначала повтори слова, с которыми познакомился на уроке.</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"cards": [{"text": "carpet", "translation": "ковёр", "audio_tts": "carpet", "image": "@@MEDIA@@gg1/u3/furn_carpet.webp"}, {"text": "cushion", "translation": "декоративная подушка", "audio_tts": "cushion", "image": "@@MEDIA@@gg1/u3/furn_cushion.webp"}, {"text": "lamp", "translation": "лампа", "audio_tts": "lamp", "image": "@@MEDIA@@gg1/u3/furn_lamp.webp"}, {"text": "plant", "translation": "растение", "audio_tts": "plant", "image": "@@MEDIA@@gg1/u3/furn_plant.webp"}, {"text": "poster", "translation": "плакат", "audio_tts": "poster", "image": "@@MEDIA@@gg1/u3/furn_poster.webp"}, {"text": "TV", "translation": "телевизор", "audio_tts": "TV", "image": "@@MEDIA@@gg1/u3/furn_tv.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'match', replace($blk${"title": "Соедини картинку и слово", "pairs": [{"left_image": "@@MEDIA@@gg1/u3/furn_carpet.webp", "right": "carpet", "right_audio_tts": "carpet"}, {"left_image": "@@MEDIA@@gg1/u3/furn_cushion.webp", "right": "cushion", "right_audio_tts": "cushion"}, {"left_image": "@@MEDIA@@gg1/u3/furn_lamp.webp", "right": "lamp", "right_audio_tts": "lamp"}, {"left_image": "@@MEDIA@@gg1/u3/furn_plant.webp", "right": "plant", "right_audio_tts": "plant"}, {"left_image": "@@MEDIA@@gg1/u3/furn_poster.webp", "right": "poster", "right_audio_tts": "poster"}, {"left_image": "@@MEDIA@@gg1/u3/furn_tv.webp", "right": "TV", "right_audio_tts": "TV"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «ковёр»?", "type": "single", "options": [{"text": "carpet"}, {"text": "plant"}, {"text": "cushion"}, {"text": "lamp"}], "correct": [0]}, {"q": "Как по-английски «декоративная подушка»?", "type": "single", "options": [{"text": "lamp"}, {"text": "cushion"}, {"text": "plant"}, {"text": "poster"}], "correct": [1]}, {"q": "Как по-английски «лампа»?", "type": "single", "options": [{"text": "poster"}, {"text": "TV"}, {"text": "plant"}, {"text": "lamp"}], "correct": [3]}, {"q": "Как по-английски «растение»?", "type": "single", "options": [{"text": "poster"}, {"text": "carpet"}, {"text": "TV"}, {"text": "plant"}], "correct": [3]}, {"q": "Как по-английски «плакат»?", "type": "single", "options": [{"text": "carpet"}, {"text": "TV"}, {"text": "cushion"}, {"text": "poster"}], "correct": [3]}, {"q": "Как по-английски «телевизор»?", "type": "single", "options": [{"text": "cushion"}, {"text": "carpet"}, {"text": "TV"}, {"text": "lamp"}], "correct": [2]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'exact_input', replace($blk${"title": "Вставь пропущенные буквы и впиши слово целиком", "items": [{"prompt": "c _ r _ e t", "accept": ["carpet", "Carpet"], "image": "@@MEDIA@@gg1/u3/furn_carpet.webp", "audio_tts": "carpet"}, {"prompt": "c _ s _ i _ n", "accept": ["cushion", "Cushion"], "image": "@@MEDIA@@gg1/u3/furn_cushion.webp", "audio_tts": "cushion"}, {"prompt": "l _ m p", "accept": ["lamp", "Lamp"], "image": "@@MEDIA@@gg1/u3/furn_lamp.webp", "audio_tts": "lamp"}, {"prompt": "p _ a _ t", "accept": ["plant", "Plant"], "image": "@@MEDIA@@gg1/u3/furn_plant.webp", "audio_tts": "plant"}, {"prompt": "p _ s _ e r", "accept": ["poster", "Poster"], "image": "@@MEDIA@@gg1/u3/furn_poster.webp", "audio_tts": "poster"}, {"prompt": "T V", "accept": ["TV", "Tv"], "image": "@@MEDIA@@gg1/u3/furn_tv.webp", "audio_tts": "TV"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'text', replace($blk${"html": "<p>Давай повторим всё, что выучили сегодня на уроке.</p><p><img src=\"@@MEDIA@@gg1/u3/card_vocab_carpet.webp\" alt=\"Vocabulary\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'quiz', replace($blk${"title": "Выбери правильный ответ", "questions": [{"q": "We usually put it on the floor to make our feet warm.", "type": "single", "options": [{"text": "cushion"}, {"text": "TV"}, {"text": "carpet"}], "correct": [2]}, {"q": "We watch it with our friends or family.", "type": "single", "options": [{"text": "TV"}, {"text": "carpet"}, {"text": "poster"}], "correct": [0]}, {"q": "We put it on the wall to make it beautiful.", "type": "single", "options": [{"text": "cushion"}, {"text": "poster"}, {"text": "TV"}], "correct": [1]}, {"q": "We use it when we need more light.", "type": "single", "options": [{"text": "cushion"}, {"text": "poster"}, {"text": "lamp"}], "correct": [2]}, {"q": "You need to water it regularly.", "type": "single", "options": [{"text": "plant"}, {"text": "TV"}, {"text": "cushion"}], "correct": [0]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'text', replace($blk${"html": "<p><b>Прочитай текст, а потом выбери «Верно» или «Неверно».</b></p><p><img src=\"@@MEDIA@@gg1/u3/plane_house.webp\" alt=\"Plane house\" style=\"max-width:100%\"></p><p><i>Most people live in a flat or house, some people live in tree houses, old castles, abandoned lighthouses and even caves but my family is different because we live in the airplane! Can you imagine?! It is located near a forest here in the USA and I love it, everything is so green and clean. My father is an engineer and he loves planes. Of course it only looks like a plane because inside we have everything we need to live a normal life. There is electricity, running water and there are a lot of windows! Because we live far from the city, there are some spectacular views from any window of our unusual home. There is a bathroom and two bedrooms, one for my parents and the other for me. Mine is at the back of the plane. It's really very cosy and comfortable. There is also a living room and a kitchen. It's always funny when my friends come and visit. They like the idea of living in a plane and so do I. Anyway, I'm sending you some photos. I hope you like them.</i></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'truefalse', replace($blk${"title": "Верно или неверно?", "statements": [{"text": "The family lives in a tree.", "correct": false}, {"text": "The plane is located in Australia.", "correct": false}, {"text": "The girl's father is a mechanic.", "correct": false}, {"text": "They have everything they need inside the house.", "correct": true}, {"text": "They live far away from the city.", "correct": true}, {"text": "There are five bedrooms in their home.", "correct": false}, {"text": "The girl loves the idea of living in a plane.", "correct": true}, {"text": "Her bedroom is very comfortable.", "correct": true}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'speaking', replace($blk${"title": "Задание со звёздочкой ⭐", "image": "@@MEDIA@@gg1/u3/house_cutaway.webp", "html": "<p>Не обязательно делать, но будет очень здорово, если ты нас порадуешь своими успехами! Расскажи нам о своём доме и вещах, которые у тебя есть.</p><ul><li>How many rooms are there in your house?</li><li>Which one is your favourite?</li><li>What is there in your bedroom?</li></ul>", "needs_review": true}$blk$, '@@MEDIA@@', v_media)::jsonb, 9),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_smiley.webp\" alt=\"\" style=\"height:180px\"></p><h3>Ты справился со всеми заданиями, молодец! 🎉</h3><p>Увидимся на занятии!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 10);
end
$mig$;
