-- Go Getter 2 · Unit 2 · Homework 7
-- собрано tools/gg2_build.py --lesson u2_hw7
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 2', 2 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 2');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 7', 'homework', 60, false, 6
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 2'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 7');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 6
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 2' and l.title = 'Homework 7';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 2' and l.title = 'Homework 7';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет! 👋</h2><p>Рада, что ты заглянул в домашку! Сегодня мы с тобой выполним несколько полезных упражнений, которые помогут тебе закрепить полученные знания. В конце урока тебя также ждёт дополнительное задание — его можно выполнить по желанию. Но ты станешь МЕГА крутым учеником, когда справишься с ним. 😎 Let's go!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'match', replace($blk${"title": "Давай сначала вспомним продукты. Соедини картинку с названием", "pairs": [{"left_image": "@@MEDIA@@gg2/u2/biscuits.webp", "right": "biscuits", "right_audio_tts": "biscuits"}, {"left_image": "@@MEDIA@@gg2/u2/cereal.webp", "right": "cereal", "right_audio_tts": "cereal"}, {"left_image": "@@MEDIA@@gg2/u2/ham.webp", "right": "ham", "right_audio_tts": "ham"}, {"left_image": "@@MEDIA@@gg2/u2/pancakes.webp", "right": "pancakes", "right_audio_tts": "pancakes"}, {"left_image": "@@MEDIA@@gg2/u2/yoghurt.webp", "right": "yoghurt", "right_audio_tts": "yoghurt"}, {"left_image": "@@MEDIA@@gg2/u2/butter.webp", "right": "butter", "right_audio_tts": "butter"}, {"left_image": "@@MEDIA@@gg2/u2/flour.webp", "right": "flour", "right_audio_tts": "flour"}, {"left_image": "@@MEDIA@@gg2/u2/milk.webp", "right": "milk", "right_audio_tts": "milk"}, {"left_image": "@@MEDIA@@gg2/u2/strawberry.webp", "right": "strawberry", "right_audio_tts": "strawberry"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'match', replace($blk${"title": "Как посчитать неисчисляемое? С помощью ёмкостей! Соедини две части, чтобы получилась фраза", "pairs": [{"left": "a bar", "right": "of chocolate", "right_audio_tts": "a bar of chocolate"}, {"left": "a jar", "right": "of jam", "right_audio_tts": "a jar of jam"}, {"left": "a can", "right": "of cola", "right_audio_tts": "a can of cola"}, {"left": "a bottle", "right": "of water", "right_audio_tts": "a bottle of water"}, {"left": "a carton", "right": "of juice", "right_audio_tts": "a carton of juice"}, {"left": "a packet", "right": "of biscuits", "right_audio_tts": "a packet of biscuits"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'gaps', replace($blk${"title": "A / an / some / any: перетащи слова в пропуски", "mode": "drag", "text": "1. There is __an__ orange on the table.\n2. I've got __a__ sandwich for lunch.\n3. There are __some__ eggs in the fridge.\n4. We haven't got __any__ bread.\n5. Mum wants __some__ milk for the pancakes.\n6. There isn't __any__ cheese in the fridge.\n7. Can I have __an__ apple, please?\n8. There's __a__ lemon in the bag."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'gaps', replace($blk${"title": "Прочти диалог между Кейт и продавцом и перетащи подходящие слова в пропуски", "mode": "drag", "image": "@@MEDIA@@gg2/u2/hot_dog_cart.webp", "text": "Waiter: What __would__ you like?\nKate: __I'd like__ a hot dog, please.\nWaiter: Would you __like__ anything to drink?\nKate: Can I have a __lemonade__, please?\nWaiter: __Anything__ else?\nKate: __Yes__. Can I have a small __salad__, please?\nWaiter: Great, __thanks__."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'gaps', replace($blk${"title": "Прочитай диалоги и впиши в пропуски How much или How many", "mode": "type", "text": "1. A: __How much|how much__ milk is there in the fridge? B: There isn't any milk!\n2. A: __How much|how much__ chocolate do you put in the cake? B: Just one bar.\n3. A: I'd like a salad, please. B: __How many|how many__ tomatoes would you like in your salad?\n4. A: Matt usually eats a lot of chips. B: __How many|how many__ potatoes do we need then?\n5. A: Can you buy some cream, please? B: Yes. __How much|how much__ cream do you want?\n6. A: __How much|how much__ water do you drink every day? B: I don't know!"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'gaps', replace($blk${"title": "Я обожаю тосты на завтрак. Прочитай рецепт моих любимых тостов и заполни пропуски", "mode": "drag", "image": "@@MEDIA@@gg2/u2/toast.webp", "text": "What's toast? It's hot __bread__. You need a __toaster__ to cook the bread. I like French toast. What's French toast? Well, you dip your bread in an __egg__. Then you cook it in __butter__ in a frying pan. Then put some __sugar__ on it and it's ready."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'task', replace($blk${"title": "Дополнительное задание: рецепт любимого завтрака", "needs_review": true, "html": "<p>А это последнее задание, оно дополнительное, для самых смелых учеников. Напиши рецепт своего любимого завтрака. Можешь использовать рецепт тостов из предыдущего задания как пример.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_star.webp\" alt=\"\" style=\"height:180px\"></p><h3>Ты справился с домашним заданием!</h3><p>Ты — супер ученик! За это держи звёздочку. До встречи на занятии!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8)
returning sort_order, type;
