-- Go Getter 2 · Unit 3 · Technology · Homework 5
-- собрано tools/gg2_build.py --lesson u3_hw5
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 3 · Technology', 3 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 3 · Technology');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 5', 'homework', 60, false, 4
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 3 · Technology'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 5');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 4
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 3 · Technology' and l.title = 'Homework 5';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 3 · Technology' and l.title = 'Homework 5';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_highfive.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет-привет! 👋</h2><p>Очень здорово, что ты снова решил сделать домашнюю работу. Сегодня мы будем много читать, но тебе понравится 😎 Ну что, начинаем!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'text', replace($blk${"html": "<p>Прочитай интервью. Потом запиши себя на аудио (внизу есть кнопочка). Не забудь менять голоса, чтобы было понятно, кто Дэйв, а кто Тэд.</p><p><img src=\"@@MEDIA@@gg2/u3/inventor.webp\" alt=\"\" style=\"max-width:100%;max-height:260px\"></p><h3>TECH TED</h3><p><i>Tech Ted is interviewing Dave Fernandez. Dave is a young technology blogger and student at North Street Secondary School.</i></p><p><b>Tech Ted:</b> Hi Dave. I can see some photos on the screen. What are you doing in this photo?<br><b>Dave:</b> Hi Ted. In this photo I'm talking to some parents from my school.<br><b>Tech Ted:</b> What are you talking about?<br><b>Dave:</b> I'm asking the parents for help. We need computers for my school.<br><b>Tech Ted:</b> What's wrong with computers at your school?<br><b>Dave:</b> A lot of our computers are old and slow. My friend Hunter knows a lot about computers and sometimes he can fix them. But when they stop working, we can't do Computer Studies lessons.<br><b>Tech Ted:</b> How can the parents help?<br><b>Dave:</b> Well, their families can give their old computers to my school. You know, computers or tablets they don't use. But ones that work of course.<br><b>Tech Ted:</b> Do parents help?<br><b>Dave:</b> Yes! We have four computers and two tablets already. It's amazing.<br><b>Tech Ted:</b> That's brilliant. Good luck with your Computer Studies lessons!<br><b>Dave:</b> Thanks!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'speaking', replace($blk${"title": "Прочитай интервью вслух 🎤", "needs_review": true, "html": "<p>Запиши своё чтение, нажав на кнопку здесь.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'task', replace($blk${"title": "Who is Dave?", "needs_review": true, "html": "<p>А теперь давай ответим на вопрос: <b>Who is Dave?</b> Напиши ответ своими словами.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'truefalse', replace($blk${"title": "Прочитай интервью ещё раз. Затем прочитай предложения и выбери: верно это или неверно", "statements": [{"text": "There are some photos on Dave's screen.", "correct": true}, {"text": "He is talking to friends in the photo.", "correct": false}, {"text": "He is asking people for help in the photo.", "correct": true}, {"text": "Dave can do Computer Studies at school.", "correct": false}, {"text": "He wants new computers for his school.", "correct": false}, {"text": "They have got some computers and tablets.", "correct": true}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'task', replace($blk${"title": "Ответь на вопросы", "needs_review": true, "html": "<p>Великолепно!!! А теперь давай ответим на вопросы письменно.</p><ol><li>Who is Tech Ted interviewing?</li><li>Who is Dave talking to in the photo?</li><li>What does his school need?</li><li>What can families do to help?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'gaps', replace($blk${"title": "Закончи предложения, вставив нужные слова в пропуски", "mode": "drag", "text": "1. He's worried __about__ the Computer Studies lessons.\n2. He's interested __in__ technology.\n3. She's good __at__ playing computer games.\n4. Are you __scared__ of aliens?\n5. I'm really excited __about__ my new tablet!\n6. Grandpa is bad __at__ using my mobile."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'text', replace($blk${"html": "<p>Ты большой-большой молодец!!! Самый старательный ученик на свете 👍</p><h3>Часть 2: дневник Пенни</h3><p>Это дополнительная часть домашнего задания. Сегодня мы будем читать дневник одной девочки — Пенни. Прочитай текст и запомни, в каких местах Пенни успела побывать :) А затем сделай задания по тексту.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Penny's holiday diary</h3><p><b>23rd July</b><br>It's day number one of our holiday. We usually go to Spain in the summer. We love it there but this year we're in Corsica, in France. It's a beautiful island!</p><p><b>27th July</b><br>There are white beaches and you can go swimming, windsurfing and sailing. But today I'm swimming in a lake! There are a lot of lakes and rivers here. The longest river is the Golo – it's 90 kilometres long. I want to swim in the lake again but Mum says the sea is better. She doesn't like cold water and the water in the lake is cold!</p><p><b>1st August</b><br>It's a beautiful day. We're walking in the mountains. You can go mountain biking too. I want to go rock climbing but Dad says it's too dangerous.</p><p><b>3rd August</b><br>Today we're in Ajaccio. Ajaccio is next to the sea and it's the coolest town on the island. I love the shops here. It's lunch time now and we're sitting under an umbrella and eating sausages and cheese. Yum!</p><p><img src=\"@@MEDIA@@gg2/u3/book_penny_diary.webp\" alt=\"Penny's diary\" style=\"max-width:100%;max-height:420px\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'task', replace($blk${"title": "Ответь на вопросы по дневнику", "needs_review": true, "html": "<p>Фух, вот это дневник! Давай проверим, насколько хорошо ты запомнил то, что рассказала Пенни. Ответь на вопросы полными предложениями. Можешь подглядывать в текст 😃</p><ol><li>Where does Penny usually go on holiday?</li><li>What water sports can you do in Corsica?</li><li>How long is the Golo river?</li><li>Why doesn't Penny's mum like swimming in the lake?</li><li>What does Penny's dad think about rock climbing?</li><li>It's 3rd August. What are Penny and her family eating?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'task', replace($blk${"title": "Мой дневник на каникулах", "needs_review": true, "html": "<p>Прекрасная работа 👍 А теперь представь, что ты ведёшь дневник на каникулах. Запиши свои любимые дни и чем ты занимался. Используй дневник Пенни как пример.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_smiley.webp\" alt=\"\" style=\"height:200px\"></p><h2>Ура! 😃</h2><p>Домашняя работа выполнена, ты отлично постарался. Увидимся на занятии!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11)
returning sort_order, type;
