-- Go Getter 2 · Unit 1 · School · Homework 5
-- собрано tools/gg2_build.py --lesson u1_hw5
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 1 · School', 1 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 1 · School');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 5', 'homework', 60, false, 4
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 1 · School'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 5');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 4
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 1 · School' and l.title = 'Homework 5';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 1 · School' and l.title = 'Homework 5';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет! 👋</h2><p>В этом уроке мы выучим названия мест, которые можно встретить в школе. Выполни все задания, чтобы выучить слова! А потом попрактикуемся в чтении. У тебя всё получится. Удачи! ❤️</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'flashcards', replace($blk${"cards": [{"text": "canteen", "translation": "столовая", "image": "@@MEDIA@@gg2/u1/canteen.webp", "audio_tts": "canteen"}, {"text": "classroom", "translation": "класс", "image": "@@MEDIA@@gg2/u1/classroom.webp", "audio_tts": "classroom"}, {"text": "computer room", "translation": "компьютерный зал", "image": "@@MEDIA@@gg2/u1/computer_room.webp", "audio_tts": "computer room"}, {"text": "gym", "translation": "спортивный зал", "image": "@@MEDIA@@gg2/u1/gym.webp", "audio_tts": "gym"}, {"text": "hall", "translation": "коридор", "image": "@@MEDIA@@gg2/u1/hall.webp", "audio_tts": "hall"}, {"text": "library", "translation": "библиотека", "image": "@@MEDIA@@gg2/u1/library.webp", "audio_tts": "library"}, {"text": "playground", "translation": "игровая площадка", "image": "@@MEDIA@@gg2/u1/playground.webp", "audio_tts": "playground"}, {"text": "staff room", "translation": "учительская", "image": "@@MEDIA@@gg2/u1/staff_room.webp", "audio_tts": "staff room"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'match', replace($blk${"title": "Соедини картинку с названием места", "pairs": [{"left_image": "@@MEDIA@@gg2/u1/canteen.webp", "right": "canteen", "right_audio_tts": "canteen"}, {"left_image": "@@MEDIA@@gg2/u1/classroom.webp", "right": "classroom", "right_audio_tts": "classroom"}, {"left_image": "@@MEDIA@@gg2/u1/computer_room.webp", "right": "computer room", "right_audio_tts": "computer room"}, {"left_image": "@@MEDIA@@gg2/u1/gym.webp", "right": "gym", "right_audio_tts": "gym"}, {"left_image": "@@MEDIA@@gg2/u1/hall.webp", "right": "hall", "right_audio_tts": "hall"}, {"left_image": "@@MEDIA@@gg2/u1/library.webp", "right": "library", "right_audio_tts": "library"}, {"left_image": "@@MEDIA@@gg2/u1/playground.webp", "right": "playground", "right_audio_tts": "playground"}, {"left_image": "@@MEDIA@@gg2/u1/staff_room.webp", "right": "staff room", "right_audio_tts": "staff room"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'match', replace($blk${"title": "Соедини слово с его значением", "pairs": [{"left": "canteen", "right": "You have lunch there.", "right_audio_tts": "You have lunch there."}, {"left": "computer room", "right": "This is a special classroom with laptops.", "right_audio_tts": "This is a special classroom with laptops."}, {"left": "gym", "right": "This is a very large room for P.E.", "right_audio_tts": "This is a very large room for P.E."}, {"left": "library", "right": "There are lots of books for extra study there.", "right_audio_tts": "There are lots of books for extra study there."}, {"left": "staff room", "right": "Teachers relax and mark homework there.", "right_audio_tts": "Teachers relax and mark homework there."}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Время почитать 📖</h3><p>Посмотри, это Стив! Он подготовил интересный рассказ о своей школе. Прежде чем читать, подумай: какие места в школе — твои самые любимые? Где ты больше всего любишь проводить время?</p><p><img src=\"@@MEDIA@@gg2/u1/steve.webp\" alt=\"\" style=\"height:240px\"></p><h3>My school</h3><p>How many students have P.E. every day for two hours? Not many? Well, I always have P.E. from 2.30 to 4.30. I'm Steve and I want to tell you about my school.</p><p>My day starts early. I usually get to school at 8.00 but I'm sometimes late. Lessons start at 8.30. My favourite subject is Geography because I like maps. I don't like Art because I don't paint good pictures.</p><p>We have lunch at 12.00 and I often have chicken and chips. I never have fish and chips. In the afternoon we have P.E. I love P.E.! We usually play football or do karate. On Friday we play basketball. My favourite sport is football because I want to play for a big team.</p><p>We finish school at 4.30. That's late for most schools. But I don't mind because I play sport every day! My sport school is great!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'quiz', replace($blk${"title": "Прочитай текст и выбери правильный ответ", "questions": [{"q": "What school does Steve go to?", "type": "single", "options": [{"text": "Art school"}, {"text": "Sports school"}, {"text": "Drama school"}], "correct": [1], "image": "@@MEDIA@@gg2/u1/sports_school.webp"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'quiz', replace($blk${"title": "Прочитай текст о школе ещё раз. Это правда (True) или неправда (False)?", "questions": [{"q": "Steve always gets to school at 8.00.", "type": "single", "options": [{"text": "True"}, {"text": "False"}], "correct": [1], "image": "@@MEDIA@@gg2/u1/steve_late.webp"}, {"q": "Steve's favourite subject is Maths.", "type": "single", "options": [{"text": "True"}, {"text": "False"}], "correct": [1], "image": "@@MEDIA@@gg2/u1/steve_maths.webp"}, {"q": "Steve doesn't like Art.", "type": "single", "options": [{"text": "True"}, {"text": "False"}], "correct": [0], "image": "@@MEDIA@@gg2/u1/steve_art.webp"}, {"q": "Steve has lunch at 12.00.", "type": "single", "options": [{"text": "True"}, {"text": "False"}], "correct": [0], "image": "@@MEDIA@@gg2/u1/steve_lunch.webp"}, {"q": "Steve usually has fish and chips for lunch.", "type": "single", "options": [{"text": "True"}, {"text": "False"}], "correct": [1], "image": "@@MEDIA@@gg2/u1/fish_chips.webp"}, {"q": "Steve loves P.E.", "type": "single", "options": [{"text": "True"}, {"text": "False"}], "correct": [0], "image": "@@MEDIA@@gg2/u1/steve_pe.webp"}, {"q": "Steve plays basketball on Friday.", "type": "single", "options": [{"text": "True"}, {"text": "False"}], "correct": [0], "image": "@@MEDIA@@gg2/u1/steve_basketball.webp"}, {"q": "Steve's favourite sport is tennis.", "type": "single", "options": [{"text": "True"}, {"text": "False"}], "correct": [1], "image": "@@MEDIA@@gg2/u1/tennis_players.webp"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'task', replace($blk${"title": "Последнее задание ✍️", "needs_review": true, "html": "<p>Молодец! Прочитай текст ещё раз и письменно ответь на вопросы:</p><ol><li>Does Steve sometimes get to school late?</li><li>Why does he like Geography?</li><li>Does he paint good pictures?</li><li>What sports does he usually do?</li><li>What does he do on Friday?</li><li>Does he finish school before 4.00?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_jump.webp\" alt=\"\" style=\"height:200px\"></p><h3>Ура! 🎉</h3><p>Ты справился с домашним заданием. Ты — мегакрут! Увидимся на занятии. Goodbye!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8)
returning sort_order, type;
