-- Go Getter 2 · Unit 5 · Homework 6
-- собрано tools/gg2_build.py --lesson u5_hw6
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 5', 5 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 5');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 6', 'homework', 60, false, 5
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 5'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 6');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 5
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 5' and l.title = 'Homework 6';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 5' and l.title = 'Homework 6';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_headphones.webp\" alt=\"\" style=\"height:200px\"></p><h2>Добро пожаловать в домашнее задание!</h2><p>Сегодня мы послушаем, как Джимми разговаривает с мамой, повторим прилагательные и поговорим о городе в прошлом и сейчас.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'task', replace($blk${"title": "Послушай аудио и впиши названия мест в городе, о которых Джимми говорит с мамой", "needs_review": true, "audio": "", "html": "<p>Напиши названия мест, которые ты услышал, по-английски.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'quiz', replace($blk${"title": "Послушай аудио ещё раз и выбери правильный ответ", "questions": [{"q": "Is Jimmy looking at new photos?", "type": "single", "options": [{"text": "Yes"}, {"text": "No"}], "correct": [1]}, {"q": "Was the library in Green Street?", "type": "single", "options": [{"text": "Yes"}, {"text": "No"}], "correct": [0]}, {"q": "Is there a library in Green Street now?", "type": "single", "options": [{"text": "Yes"}, {"text": "No"}], "correct": [1]}, {"q": "Was the bank next to the library?", "type": "single", "options": [{"text": "Yes"}, {"text": "No"}], "correct": [0]}, {"q": "Is there a supermarket next to the bank today?", "type": "single", "options": [{"text": "Yes"}, {"text": "No"}], "correct": [0]}, {"q": "Is Jimmy's mum behind the train station in the next photo?", "type": "single", "options": [{"text": "Yes"}, {"text": "No"}], "correct": [1]}, {"q": "Does Jimmy think his mum's hat was nice?", "type": "single", "options": [{"text": "Yes"}, {"text": "No"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'flashcards', replace($blk${"cards": [{"text": "busy", "translation": "оживлённый, людный", "audio_tts": "busy", "image": "@@MEDIA@@gg2/u5/busy_street.webp"}, {"text": "quiet", "translation": "тихий", "audio_tts": "quiet", "image": "@@MEDIA@@gg2/u5/quiet_street.webp"}, {"text": "small", "translation": "маленький", "audio_tts": "small", "image": "@@MEDIA@@gg2/u5/small_house.webp"}, {"text": "big", "translation": "большой", "audio_tts": "big", "image": "@@MEDIA@@gg2/u5/big_house.webp"}, {"text": "interesting", "translation": "интересный", "audio_tts": "interesting", "image": "@@MEDIA@@gg2/u5/interesting_museum.webp"}, {"text": "boring", "translation": "скучный", "audio_tts": "boring"}, {"text": "old", "translation": "старый", "audio_tts": "old", "image": "@@MEDIA@@gg2/u5/old_stadium.webp"}, {"text": "new", "translation": "новый", "audio_tts": "new", "image": "@@MEDIA@@gg2/u5/new_stadium.webp"}, {"text": "clean", "translation": "чистый", "audio_tts": "clean", "image": "@@MEDIA@@gg2/u5/clean_cinema.webp"}, {"text": "dirty", "translation": "грязный", "audio_tts": "dirty", "image": "@@MEDIA@@gg2/u5/dirty_cinema.webp"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'gaps', replace($blk${"title": "Прочитай предложения и заполни пропуски подходящими прилагательными", "mode": "drag", "text": "1. There are lots of people in the village. It's very __busy__. But it's usually __quiet__ on Sundays.\n2. This __small__ house has one bedroom, but that __big__ house has five.\n3. I usually think museums are __interesting__, but this one is __boring__. There's nothing good to see.\n4. The __old__ stadium wasn't great. But the __new__ stadium is amazing!\n5. The cinema was __clean__ before the film, but after the film it was __dirty__ because there was popcorn on the floor."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'task', replace($blk${"title": "Город в прошлом и сейчас", "needs_review": true, "html": "<p>Посмотри на картинки города и расскажи, что там было и чего не было в прошлом, и что есть сейчас.</p><p><b>In the past</b><br><img src=\"@@MEDIA@@gg2/u5/town_past.webp\" alt=\"Город в прошлом\" style=\"max-width:100%;width:400px\"></p><p><b>Now</b><br><img src=\"@@MEDIA@@gg2/u5/town_now.webp\" alt=\"Город сейчас\" style=\"max-width:100%;width:400px\"></p><p>Используй шаблон:<br><i>There was … . There were … . There wasn't … . There weren't … . There is … . There are … .</i></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'task', replace($blk${"title": "Дополнительное задание — по желанию ⭐", "needs_review": true, "html": "<p>Напиши о своём городе в прошлом и сейчас. Используй шаблон:</p><p><i><b>My town</b><br>Hi, my name is Alice and I live in Overtown. It's a small town.<br>In the past … .<br>Today … .</i></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_medal.webp\" alt=\"\" style=\"height:180px\"></p><h3>Bye! 👋</h3><p>Ты отлично поработал. До встречи на уроке!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7)
returning sort_order, type;
