-- Go Getter 2 · Unit 3 · Technology · Unit 3 Test
-- собрано tools/gg2_build.py --lesson u3_test
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 3 · Technology', 3 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 3 · Technology');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Unit 3 Test', 'test', 90, false, 7
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 3 · Technology'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Unit 3 Test');
update classroom_lessons l set kind = 'test', pass_threshold = 90, sort_order = 7
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 3 · Technology' and l.title = 'Unit 3 Test';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 3 · Technology' and l.title = 'Unit 3 Test';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'exact_input', replace($blk${"items": [{"prompt": "Напиши по-английски: общаться онлайн", "accept": ["chat online"]}, {"prompt": "Напиши по-английски: скачать песню", "accept": ["download a song"]}, {"prompt": "Напиши по-английски: сидеть в интернете", "accept": ["surf the Internet"]}, {"prompt": "Напиши по-английски: планшет", "accept": ["tablet", "a tablet"]}, {"prompt": "Напиши по-английски: наушники", "accept": ["headphones"]}, {"prompt": "Напиши по-английски: клавиатура", "accept": ["keyboard", "a keyboard"]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Выбери правильный вариант. Look! Tom ___ a selfie with his new phone.", "type": "single", "options": [{"text": "takes"}, {"text": "is taking"}, {"text": "is take"}], "correct": [1]}, {"q": "We ___ TV right now — we're surfing the Internet.", "type": "single", "options": [{"text": "aren't watching"}, {"text": "don't watch"}, {"text": "not watching"}], "correct": [0]}, {"q": "— ___ your sister chatting online? — Yes, she is.", "type": "single", "options": [{"text": "Does"}, {"text": "Are"}, {"text": "Is"}], "correct": [2]}, {"q": "I ___ an email to my grandma at the moment.", "type": "single", "options": [{"text": "write"}, {"text": "am writeing"}, {"text": "am writing"}], "correct": [2]}, {"q": "What ___ now?", "type": "single", "options": [{"text": "you do"}, {"text": "are you doing"}, {"text": "you are"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'gaps', replace($blk${"title": "Поставь глагол в скобках в правильную форму Present Continuous", "mode": "type", "text": "1. My brother __is downloading__ (download) a new song right now.\n2. We __are sitting__ (sit) in the kitchen and having lunch.\n3. They __aren't listening|aren’t listening|are not listening__ (not listen) to music — they're studying.\n4. — What __is__ Anna __writing__ (write)? — A text message to her friend.\n5. I __am not using__ (not use) my laptop now, you can take it."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'order', replace($blk${"words": ["What", "are", "your", "friends", "doing", "today?"], "sentence": "What are your friends doing today?", "audio_tts": "What are your friends doing today?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'order', replace($blk${"words": ["I'm", "not", "scared", "of", "spiders,", "I'm", "scared", "of", "snakes."], "sentence": "I'm not scared of spiders, I'm scared of snakes.", "audio_tts": "I'm not scared of spiders, I'm scared of snakes."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'order', replace($blk${"words": ["Is", "Sophie", "sending", "an email", "to", "her", "teacher?"], "sentence": "Is Sophie sending an email to her teacher?", "audio_tts": "Is Sophie sending an email to her teacher?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["They", "aren't", "playing", "computer games", "at the moment."], "sentence": "They aren't playing computer games at the moment.", "audio_tts": "They aren't playing computer games at the moment."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["My", "dad", "is", "talking", "on", "the phone", "now."], "sentence": "My dad is talking on the phone now.", "audio_tts": "My dad is talking on the phone now."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'text', replace($blk${"html": "<h3>READING</h3><p>Прочитай текст и ответь на вопросы ниже.</p><h3>A Family Video Call</h3><p><img src=\"@@MEDIA@@gg2/u3/video_call.webp\" alt=\"\" style=\"max-width:100%;max-height:240px\"></p><p>It's Sunday evening at the Wilson family's house in Manchester. Everyone is at home, but they aren't sitting together — they're all using technology!</p><p>In the living room, Mum is having a video call with Grandma. Grandma lives in Scotland and they talk every Sunday. Mum is showing her some new photos on the screen.</p><p>Dad is in the kitchen. He's wearing his big headphones and listening to a podcast about football. He often does this when he cooks dinner.</p><p>Upstairs, twelve-year-old Lucy is in her bedroom. She's chatting online with her best friend Mia about their school project. They're both worried about their History test on Monday.</p><p>Lucy's brother Jake is fourteen. He's not very interested in school today — he's playing a computer game with his friends and laughing loudly!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Where are the Wilsons today?", "type": "single", "options": [{"text": "At Grandma's house"}, {"text": "In a café"}, {"text": "At home"}, {"text": "At school"}], "correct": [2]}, {"q": "Why is Mum showing Grandma photos?", "type": "single", "options": [{"text": "Grandma is in their house"}, {"text": "They are having a video call"}, {"text": "Grandma is taking selfies"}, {"text": "Mum is sending an email"}], "correct": [1]}, {"q": "What is Dad doing?", "type": "single", "options": [{"text": "Watching football on TV"}, {"text": "Cooking and listening to a podcast"}, {"text": "Talking on the phone"}, {"text": "Eating dinner"}], "correct": [1]}, {"q": "Why is Lucy talking to Mia?", "type": "single", "options": [{"text": "Mia is in their kitchen"}, {"text": "They're worried about a test"}, {"text": "They're playing a game together"}, {"text": "Mia is her sister"}], "correct": [1]}, {"q": "Jake is…", "type": "single", "options": [{"text": "doing his homework"}, {"text": "studying with Lucy"}, {"text": "having fun with his friends online"}, {"text": "helping his dad in the kitchen"}], "correct": [2]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'text', replace($blk${"audio": "", "html": "<h3>LISTENING</h3><p>Послушай разговор по телефону между Эммой и её мамой. Потом выбери для каждого предложения: True (верно), False (неверно) или Not stated (не сказано).</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Emma is calling her mum from home.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [1]}, {"q": "Lily and Emma are doing a school project together.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [0]}, {"q": "Lily's brother is helping them with the computer.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [0]}, {"q": "Lily's brother is fifteen years old.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [2]}, {"q": "Lily's mum is at home.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [1]}, {"q": "Lily's dad is cooking dinner.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [0]}, {"q": "Emma is going home tonight.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING I 🎤", "needs_review": true, "html": "<p>Посмотри на картинку и ответь на вопросы.</p><ol><li>How many people can you see?</li><li>Where are they?</li><li>What is each person doing right now?</li><li>What gadgets can you see in the picture?</li><li>Who is using headphones?</li></ol>", "image": "@@MEDIA@@gg2/u3/scene_gadgets_breakfast.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING II 🎤", "needs_review": true, "html": "<p>Ответь на вопросы полными предложениями.</p><ol><li>What are you doing right now?</li><li>What gadgets have you got?</li><li>What's your favourite gadget?</li><li>Do you usually chat online with your friends or talk on the phone?</li><li>What music are you listening to these days?</li><li>Are you good at computer games?</li><li>What are you scared of?</li><li>Are your parents good at technology?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13)
returning sort_order, type;
