-- Go Getter 2 · Unit 2 · Food · Unit 2 Test
-- собрано tools/gg2_build.py --lesson u2_test
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 2 · Food', 2 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 2 · Food');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Unit 2 Test', 'test', 90, false, 7
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 2 · Food'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Unit 2 Test');
update classroom_lessons l set kind = 'test', pass_threshold = 90, sort_order = 7
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 2 · Food' and l.title = 'Unit 2 Test';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 2 · Food' and l.title = 'Unit 2 Test';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'exact_input', replace($blk${"items": [{"prompt": "Напиши по-английски: печенье", "accept": ["biscuits", "Biscuits"], "audio_tts": "biscuits"}, {"prompt": "Напиши по-английски: хлопья", "accept": ["cereal", "Cereal"], "audio_tts": "cereal"}, {"prompt": "Напиши по-английски: ветчина", "accept": ["ham", "Ham"], "audio_tts": "ham"}, {"prompt": "Напиши по-английски: сосиска", "accept": ["sausage", "Sausage"], "audio_tts": "sausage"}, {"prompt": "Напиши по-английски: вода", "accept": ["water", "Water"], "audio_tts": "water"}, {"prompt": "Напиши по-английски: йогурт", "accept": ["yoghurt", "Yoghurt"], "audio_tts": "yoghurt"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Выбери правильный вариант. There ___ apples on the table.", "type": "single", "options": [{"text": "is some"}, {"text": "are some"}, {"text": "are any"}], "correct": [1]}, {"q": "We haven't got ___ bread for breakfast.", "type": "single", "options": [{"text": "some"}, {"text": "a"}, {"text": "any"}], "correct": [2]}, {"q": "How ___ milk do you drink every day?", "type": "single", "options": [{"text": "much"}, {"text": "many"}, {"text": "a lot"}], "correct": [0]}, {"q": "I'd like ___ egg and a sandwich, please.", "type": "single", "options": [{"text": "a"}, {"text": "an"}, {"text": "some"}], "correct": [1]}, {"q": "How ___ sausages are there in the packet?", "type": "single", "options": [{"text": "much"}, {"text": "many"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'gaps', replace($blk${"title": "Вставь нужное слово", "mode": "drag", "text": "1. There are __some__ tomatoes in the salad.\n2. There isn't __any__ sugar in my tea, thanks.\n3. Can I have __an__ apple, please?\n4. How __much__ chocolate do you eat in a week?\n5. How __many__ eggs do we need for the pancakes?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Расставь части предложения в правильном порядке</h3><p>Ниже пять предложений — собери каждое.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'order', replace($blk${"words": ["There", "are", "some", "sausages", "in", "the fridge."], "sentence": "There are some sausages in the fridge.", "audio_tts": "There are some sausages in the fridge."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'order', replace($blk${"words": ["How", "much", "cheese", "do", "you", "want?"], "sentence": "How much cheese do you want?", "audio_tts": "How much cheese do you want?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["We", "haven't", "got", "any", "orange juice", "today."], "sentence": "We haven't got any orange juice today.", "audio_tts": "We haven't got any orange juice today."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["I'd", "like", "a", "bottle", "of", "water,", "please."], "sentence": "I'd like a bottle of water, please.", "audio_tts": "I'd like a bottle of water, please."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'order', replace($blk${"words": ["How", "many", "strawberries", "are", "there", "in", "the", "jar?"], "sentence": "How many strawberries are there in the jar?", "audio_tts": "How many strawberries are there in the jar?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'text', replace($blk${"html": "<h3>READING</h3><p>Прочитай тексты трёх подростков об их завтраке.</p><p><b>Three Breakfasts Around the World</b></p><p><b>Carlos, 13, from Spain:</b> \"In Spain we don't usually have a big breakfast. I just have toast with butter and a glass of orange juice. On Sundays my dad makes hot chocolate – it's amazing!\"</p><p><b>Yuki, 12, from Japan:</b> \"My breakfast is very different from breakfasts in Europe. I usually have rice, fish and a green vegetable called natto. I drink green tea, not orange juice.\"</p><p><b>Olivia, 13, from the UK:</b> \"On weekdays I have cereal with milk because we don't have much time in the morning. But on Saturdays my mum makes a big English breakfast with eggs, sausages, tomatoes and beans. It's my favourite meal of the week!\"</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'sort', replace($blk${"title": "Соедини каждого человека с фактами о нём. Каждый факт подходит только к одному человеку", "groups": [{"name": "Carlos", "items": [{"text": "drinks hot chocolate on Sundays"}, {"text": "has toast with butter"}]}, {"name": "Yuki", "items": [{"text": "eats fish for breakfast"}, {"text": "doesn't drink orange juice"}, {"text": "drinks green tea"}]}, {"name": "Olivia", "items": [{"text": "has cereal on weekdays"}, {"text": "is often in a hurry in the morning"}]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'text', replace($blk${"html": "<h3>LISTENING 🎧</h3><p>Послушай рассказ Мии о покупках в супермаркете. Затем отметь, какие предложения верные (True), а какие — неверные (False).</p>", "audio": ""}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'truefalse', replace($blk${"title": "True or False?", "statements": [{"text": "Mia is shopping with her dad.", "correct": false}, {"text": "Her brother eats bread every morning.", "correct": true}, {"text": "They need eggs for pancakes.", "correct": true}, {"text": "Mia's dad wants to cook pasta with vegetables.", "correct": false}, {"text": "They need orange juice for Sunday breakfast.", "correct": true}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING I 🎤", "needs_review": true, "image": "@@MEDIA@@gg2/u2/scene_breakfast.webp", "html": "<p>Опиши картинку и ответь на вопросы.</p><ol><li>How many people are there in the picture?</li><li>Where are they?</li><li>What time of day is it — breakfast, lunch or dinner?</li><li>What food can you see on the table?</li><li>What drinks are there?</li><li>Is there any cheese?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING II 🎤", "needs_review": true, "html": "<p>Ответь на вопросы полными предложениями.</p><ol><li>What do you usually have for breakfast?</li><li>What's your favourite food?</li><li>What food don't you like?</li><li>How much water do you drink every day?</li><li>How many eggs do you eat in a week?</li><li>Can you cook? What can you make?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 14)
returning sort_order, type;
