-- Go Getter 2 · Unit 8 · Celebrations · Homework 1
-- собрано tools/gg2_build.py --lesson u8_hw1
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 8 · Celebrations', 8 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 8 · Celebrations');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 1', 'homework', 60, false, 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 8 · Celebrations'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 1');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 8 · Celebrations' and l.title = 'Homework 1';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 8 · Celebrations' and l.title = 'Homework 1';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет! 👋</h2><p>Надеюсь, ты любишь вечеринки! Сегодня мы изучим слова, которые ты сможешь использовать на мероприятиях 😋</p><p>Выполни все задания, чтобы выучить слова на 100%!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'flashcards', replace($blk${"cards": [{"text": "barbecue", "translation": "барбекю", "image": "@@MEDIA@@gg2/u8/barbecue.webp", "audio_tts": "barbecue"}, {"text": "birthday party", "translation": "праздник в честь дня рождения", "image": "@@MEDIA@@gg2/u8/birthday_party.webp", "audio_tts": "birthday party"}, {"text": "concert", "translation": "концерт", "image": "@@MEDIA@@gg2/u8/concert.webp", "audio_tts": "concert"}, {"text": "dance show", "translation": "танцевальное шоу", "image": "@@MEDIA@@gg2/u8/dance_show.webp", "audio_tts": "dance show"}, {"text": "football match", "translation": "футбольный матч", "image": "@@MEDIA@@gg2/u8/football_match.webp", "audio_tts": "football match"}, {"text": "fancy dress party", "translation": "костюмированная вечеринка", "image": "@@MEDIA@@gg2/u8/fancy_dress.webp", "audio_tts": "fancy dress party"}, {"text": "picnic", "translation": "пикник", "image": "@@MEDIA@@gg2/u8/picnic.webp", "audio_tts": "picnic"}, {"text": "play", "translation": "пьеса", "image": "@@MEDIA@@gg2/u8/play.webp", "audio_tts": "play"}, {"text": "sleepover", "translation": "ночёвка", "image": "@@MEDIA@@gg2/u8/sleepover.webp", "audio_tts": "sleepover"}, {"text": "talent competition", "translation": "конкурс талантов", "image": "@@MEDIA@@gg2/u8/talent_competition.webp", "audio_tts": "talent competition"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'match', replace($blk${"title": "Соедини картинки со словами", "pairs": [{"left_image": "@@MEDIA@@gg2/u8/barbecue.webp", "right": "barbecue", "right_audio_tts": "barbecue"}, {"left_image": "@@MEDIA@@gg2/u8/birthday_party.webp", "right": "birthday party", "right_audio_tts": "birthday party"}, {"left_image": "@@MEDIA@@gg2/u8/concert.webp", "right": "concert", "right_audio_tts": "concert"}, {"left_image": "@@MEDIA@@gg2/u8/dance_show.webp", "right": "dance show", "right_audio_tts": "dance show"}, {"left_image": "@@MEDIA@@gg2/u8/football_match.webp", "right": "football match", "right_audio_tts": "football match"}, {"left_image": "@@MEDIA@@gg2/u8/fancy_dress.webp", "right": "fancy dress party", "right_audio_tts": "fancy dress party"}, {"left_image": "@@MEDIA@@gg2/u8/picnic.webp", "right": "picnic", "right_audio_tts": "picnic"}, {"left_image": "@@MEDIA@@gg2/u8/play.webp", "right": "play", "right_audio_tts": "play"}, {"left_image": "@@MEDIA@@gg2/u8/sleepover.webp", "right": "sleepover", "right_audio_tts": "sleepover"}, {"left_image": "@@MEDIA@@gg2/u8/talent_competition.webp", "right": "talent competition", "right_audio_tts": "talent competition"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'exact_input', replace($blk${"items": [{"prompt": "Напиши по-английски: барбекю", "accept": ["barbecue"], "audio_tts": "barbecue"}, {"prompt": "Напиши по-английски: праздник в честь дня рождения", "accept": ["birthday party"], "audio_tts": "birthday party"}, {"prompt": "Напиши по-английски: концерт", "accept": ["concert"], "audio_tts": "concert"}, {"prompt": "Напиши по-английски: танцевальное шоу", "accept": ["dance show"], "audio_tts": "dance show"}, {"prompt": "Напиши по-английски: футбольный матч", "accept": ["football match"], "audio_tts": "football match"}, {"prompt": "Напиши по-английски: костюмированная вечеринка", "accept": ["fancy dress party"], "audio_tts": "fancy dress party"}, {"prompt": "Напиши по-английски: пикник", "accept": ["picnic"], "audio_tts": "picnic"}, {"prompt": "Напиши по-английски: пьеса", "accept": ["play"], "audio_tts": "play"}, {"prompt": "Напиши по-английски: ночёвка", "accept": ["sleepover"], "audio_tts": "sleepover"}, {"prompt": "Напиши по-английски: конкурс талантов", "accept": ["talent competition"], "audio_tts": "talent competition"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Что делают на празднике 🎉</h3><p>Что ты любишь делать на вечеринках? Выучи ещё шесть фраз — и выполни задания, чтобы запомнить их на 100%!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'flashcards', replace($blk${"cards": [{"text": "cook food", "translation": "готовить пищу", "image": "@@MEDIA@@gg2/u8/cook_food.webp", "audio_tts": "cook food"}, {"text": "get presents", "translation": "получать подарки", "image": "@@MEDIA@@gg2/u8/get_presents.webp", "audio_tts": "get presents"}, {"text": "sing \"Happy Birthday\"", "translation": "спеть «С днём рождения»", "image": "@@MEDIA@@gg2/u8/sing_birthday.webp", "audio_tts": "sing Happy Birthday"}, {"text": "sleep on the floor", "translation": "спать на полу", "image": "@@MEDIA@@gg2/u8/sleep_floor.webp", "audio_tts": "sleep on the floor"}, {"text": "take part in a competition", "translation": "принять участие в конкурсе", "image": "@@MEDIA@@gg2/u8/competition.webp", "audio_tts": "take part in a competition"}, {"text": "wear a costume", "translation": "носить костюм", "image": "@@MEDIA@@gg2/u8/wear_costume.webp", "audio_tts": "wear a costume"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'match', replace($blk${"title": "Соедини картинки с фразами", "pairs": [{"left_image": "@@MEDIA@@gg2/u8/cook_food.webp", "right": "cook food", "right_audio_tts": "cook food"}, {"left_image": "@@MEDIA@@gg2/u8/get_presents.webp", "right": "get presents", "right_audio_tts": "get presents"}, {"left_image": "@@MEDIA@@gg2/u8/sing_birthday.webp", "right": "sing \"Happy Birthday\"", "right_audio_tts": "sing Happy Birthday"}, {"left_image": "@@MEDIA@@gg2/u8/sleep_floor.webp", "right": "sleep on the floor", "right_audio_tts": "sleep on the floor"}, {"left_image": "@@MEDIA@@gg2/u8/competition.webp", "right": "take part in a competition", "right_audio_tts": "take part in a competition"}, {"left_image": "@@MEDIA@@gg2/u8/wear_costume.webp", "right": "wear a costume", "right_audio_tts": "wear a costume"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'quiz', replace($blk${"title": "Как это по-английски?", "questions": [{"q": "Как по-английски «готовить пищу»?", "type": "single", "options": [{"text": "get presents"}, {"text": "cook food"}, {"text": "wear a costume"}], "correct": [1]}, {"q": "Как по-английски «получать подарки»?", "type": "single", "options": [{"text": "get presents"}, {"text": "sleep on the floor"}, {"text": "cook food"}], "correct": [0]}, {"q": "Как по-английски «спеть «С днём рождения»»?", "type": "single", "options": [{"text": "take part in a competition"}, {"text": "get presents"}, {"text": "sing \"Happy Birthday\""}], "correct": [2]}, {"q": "Как по-английски «спать на полу»?", "type": "single", "options": [{"text": "wear a costume"}, {"text": "sleep on the floor"}, {"text": "cook food"}], "correct": [1]}, {"q": "Как по-английски «принять участие в конкурсе»?", "type": "single", "options": [{"text": "take part in a competition"}, {"text": "sing \"Happy Birthday\""}, {"text": "sleep on the floor"}], "correct": [0]}, {"q": "Как по-английски «носить костюм»?", "type": "single", "options": [{"text": "cook food"}, {"text": "get presents"}, {"text": "wear a costume"}], "correct": [2]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_highfive.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет ещё раз! 🙌</h2><p>Добро пожаловать в третью ДОПОЛНИТЕЛЬНУЮ часть домашнего задания. Выполни все задания, чтобы хорошенько запомнить новые слова!</p><p>Выполнив эти задания, ты станешь БОЛЬШИМ МОЛОДЦОМ!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'quiz', replace($blk${"title": "Выбери подходящее по смыслу слово", "questions": [{"q": "Dad's cooking meat on the ___.", "type": "single", "options": [{"text": "party"}, {"text": "barbecue"}], "correct": [1], "image": "@@MEDIA@@gg2/u8/barbecue.webp"}, {"q": "We're having a ___ at Tracy's house tonight!", "type": "single", "options": [{"text": "sleepover"}, {"text": "lunch"}], "correct": [0], "image": "@@MEDIA@@gg2/u8/sleepover_girls.webp"}, {"q": "We're enjoying a great ___! I'm 12 today!", "type": "single", "options": [{"text": "birthday party"}, {"text": "concert"}], "correct": [0], "image": "@@MEDIA@@gg2/u8/birthday_party.webp"}, {"q": "Maria is doing ballet in the ___.", "type": "single", "options": [{"text": "football match"}, {"text": "dance show"}], "correct": [1], "image": "@@MEDIA@@gg2/u8/dance_show.webp"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'text', replace($blk${"html": "<p>Молодец! А теперь прочти текст об Анне! Узнай, чем занимается её семья и у кого какие хобби.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'gaps', replace($blk${"title": "Прочитай текст ещё раз и впиши пропущенные слова", "mode": "type", "text": "Hi, I'm Anna. The people in my family do interesting things. My grandad loves sport so he usually sees a football __match__ at the weekend at the stadium. Mum likes the theatre so she often sees a __play__. I like wearing costumes so I always have a fancy __dress__ party on my birthday. My older brother James is a good singer. He loves music and often goes to a __concert__ to hear his favourite band. My uncle, Paul, is also a good singer. He wants to be famous, so he is in a __talent competition__ at the moment. I hope he wins! Dad loves being outdoors. So he often takes us to the park for a __picnic__. He makes all the sandwiches!", "image": "@@MEDIA@@gg2/u8/anna.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'task', replace($blk${"title": "Дополнительное задание — для самых смелых! 💪", "needs_review": true, "html": "<p>Прочти ещё раз текст об Анне в предыдущем упражнении и письменно перечисли: какие увлечения у твоей семьи.</p><p><i>Например: My mum often sees a play. My brother loves football matches.</i></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_star.webp\" alt=\"\" style=\"height:180px\"></p><h3>Поздравляю! 🎉</h3><p>Ты завершил домашнее задание. Ты — БОЛЬШОЙ МОЛОДЕЦ! Жду тебя на уроке!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13)
returning sort_order, type;
