-- Go Getter 2 · Unit 3 · Homework 2
-- собрано tools/gg2_build.py --lesson u3_hw2
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 3', 3 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 3');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 2', 'homework', 60, false, 1
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 3'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 2');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 1
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 3' and l.title = 'Homework 2';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 3' and l.title = 'Homework 2';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_rocket.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет-привет, мастер английского языка 😉</h2><p>Сегодня тебя ждёт новая домашняя работа. Ты точно с ней справишься, можешь быть уверен :) Let's go 😃</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'text', replace($blk${"html": "<p>Внизу тебя ждёт видео 👇</p><ol><li>Посмотри его.</li><li>Включи видео ещё раз и найди не обычного человека, а супергероя. Как только его увидишь, попробуй ответить на вопросы: <i>What is he doing? What is he wearing?</i></li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'video', replace($blk${"title": "Посмотри видео и найди супергероя: What is he doing? What is he wearing?", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'match', replace($blk${"title": "А теперь давай вспомним, кто что делает. Соедини картинку с предложением", "pairs": [{"left_image": "@@MEDIA@@gg2/u3/cat_sitting.webp", "right": "It is sitting.", "right_audio_tts": "It is sitting."}, {"left_image": "@@MEDIA@@gg2/u3/fox_running.webp", "right": "She is running.", "right_audio_tts": "She is running."}, {"left_image": "@@MEDIA@@gg2/u3/animals_eating.webp", "right": "They are eating.", "right_audio_tts": "They are eating."}, {"left_image": "@@MEDIA@@gg2/u3/animals_reading.webp", "right": "We are reading.", "right_audio_tts": "We are reading."}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Mum ___ working today.", "type": "single", "options": [{"text": "am"}, {"text": "is"}, {"text": "are"}], "correct": [1]}, {"q": "They ___ chatting online at the moment.", "type": "single", "options": [{"text": "are"}, {"text": "am"}, {"text": "is"}], "correct": [0]}, {"q": "He ___ taking a photo of a famous person.", "type": "single", "options": [{"text": "am"}, {"text": "are"}, {"text": "is"}], "correct": [2]}, {"q": "We ___ watching a film on TV.", "type": "single", "options": [{"text": "am"}, {"text": "is"}, {"text": "are"}], "correct": [2]}, {"q": "I ___ wearing my tracksuit because we have P.E.", "type": "single", "options": [{"text": "am"}, {"text": "is"}, {"text": "are"}], "correct": [0]}, {"q": "You ___ wearing a nice T-shirt. Is it new?", "type": "single", "options": [{"text": "is"}, {"text": "are"}, {"text": "am"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'gaps', replace($blk${"title": "Знакомься! Это Сара. Прочитай про её обычный день и гаджеты, которыми она пользуется. Вставь пропущенные слова", "mode": "drag", "text": "It's a typical day for Sarah. She wakes up and checks her phone. She sees that her friends are __sending__ emails to each other, so she decides to text them too. She quickly gets dressed and heads out to meet her friend, Emma. Emma is __wearing__ a new smartwatch that can do lots of things. They walk to school together, listening to music on their phones. When they arrive at school, the bell rings and they go to class. In class, the teacher is __talking__ about new technologies. Sarah is __watching__ TV on her tablet under the desk, but she still hears what the teacher is __saying__. After class, Sarah and Emma take selfies together with their phones. Later, Sarah's phone rings — it's her mom. Sarah says goodbye to Emma and goes home. At home, Sarah's little brother is __playing__ video games on his computer. After dinner, Sarah watches a movie on her laptop before going to bed. It was a good day, full of new technologies.", "image": "@@MEDIA@@gg2/u3/sarah.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["We", "are", "dancing", "now."], "sentence": "We are dancing now.", "audio_tts": "We are dancing now.", "image": "@@MEDIA@@gg2/u3/bunny_dancing.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["He", "is", "not", "jumping."], "sentence": "He is not jumping.", "audio_tts": "He is not jumping.", "image": "@@MEDIA@@gg2/u3/dog_not_jumping.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'order', replace($blk${"words": ["They", "are", "crying."], "sentence": "They are crying.", "audio_tts": "They are crying.", "image": "@@MEDIA@@gg2/u3/kittens_crying.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'order', replace($blk${"words": ["His", "mother", "and", "I", "are", "walking", "today."], "sentence": "His mother and I are walking today.", "audio_tts": "His mother and I are walking today.", "image": "@@MEDIA@@gg2/u3/bear_panda_walking.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'order', replace($blk${"words": ["Sarah", "and", "her", "friend", "are", "not", "cleaning", "Sarah's", "room."], "sentence": "Sarah and her friend are not cleaning Sarah's room.", "audio_tts": "Sarah and her friend are not cleaning Sarah's room.", "image": "@@MEDIA@@gg2/u3/pandas_not_cleaning.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'task', replace($blk${"title": "Что вы делаете сейчас?", "needs_review": true, "html": "<p>Молодец! Предыдущее задание выполнено на ура! А теперь напиши, что делаешь сейчас ты, твоя семья и твои друзья (пять предложений). Даже если не знаешь, пофантазируй :)</p><p><i>Например: I am playing computer games. My friend Jess is dancing. My brother and sister are going to school.</i></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Правило: как прибавлять -ing</h3><p>Класс! Самое время немножко отдохнуть и почитать одно интересное правило. Оказывается, когда мы прибавляем ING к слову, иногда происходит что-то необычное:</p><ul><li>look + ing = look<b>ING</b></li><li>tak<s>e</s> + ing = tak<b>ING</b> — буква <b>e</b> на конце исчезает</li><li>sit + <b>t</b> + ing = sit<b>TING</b> — если в слове короткая гласная, а после неё согласная, последнюю букву удваиваем</li></ul>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'sort', replace($blk${"title": "Распредели слова по колонкам (используй правило выше)", "groups": [{"name": "look → looking", "items": [{"text": "ask → asking"}, {"text": "surf → surfing"}, {"text": "wait → waiting"}]}, {"name": "take → taking", "items": [{"text": "dance → dancing"}, {"text": "have → having"}, {"text": "write → writing"}]}, {"name": "sit → sitting", "items": [{"text": "chat → chatting"}, {"text": "run → running"}, {"text": "stop → stopping"}]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13),
('<lesson_id>', 'task', replace($blk${"title": "Опиши картинку", "needs_review": true, "html": "<p>Уррра! Осталось последнее задание 🎉 Посмотри на картинку и составь три положительных и три отрицательных предложения.</p><p><i>Например: The boy and the girl are jumping. The animals are not flying.</i></p><p><img src=\"@@MEDIA@@gg2/u3/scene_pool.webp\" alt=\"У бассейна\" style=\"max-width:100%;max-height:420px\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 14),
('<lesson_id>', 'text', replace($blk${"audio": "", "html": "<p>👏👏👏👏 Это аплодисменты за твои труды! Ты мега крут!</p><p>Для тебя есть ещё дополнительное задание. Оно выполняется по желанию. Если ты устал, можешь отложить его. Но если есть силы, вперёд! Сначала послушай пример.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 15),
('<lesson_id>', 'speaking', replace($blk${"title": "Опиши картинку 🎤", "needs_review": true, "html": "<p>Опиши то, что видишь на картинке. Можешь прослушать пример выше и продолжить своё описание. Не забудь использовать Present Continuous.</p>", "image": "@@MEDIA@@gg2/u3/selfie_teens.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 16),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_trophy.webp\" alt=\"\" style=\"height:200px\"></p><h2>Поздравляю 😉</h2><p>Ты прекрасно выполнил домашнюю работу и можешь гордиться собой. До встречи!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 17)
returning sort_order, type;
