-- Go Getter 2 · Unit 6 · Jobs · Homework 6
-- собрано tools/gg2_build.py --lesson u6_hw6
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 6 · Jobs', 6 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 6 · Jobs');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 6', 'homework', 60, false, 5
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 6 · Jobs'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 6');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 5
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 6 · Jobs' and l.title = 'Homework 6';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 6 · Jobs' and l.title = 'Homework 6';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_headphones.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет! 😃</h2><p>Сегодня мы будем тренироваться в аудировании и даже напишем небольшой рассказ. У тебя всё получится, как и всегда. Давай приступим :)</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'video', replace($blk${"title": "Послушай рассказ Ника о его дне, а потом сделай задания ниже 🎧", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'quiz', replace($blk${"title": "Послушай аудио и выбери правильный вариант ответа", "questions": [{"q": "Nick's ___ visited.", "type": "single", "options": [{"text": "uncle"}, {"text": "grandfather"}], "correct": [0]}, {"q": "They played ___.", "type": "single", "options": [{"text": "basketball"}, {"text": "football"}], "correct": [1]}, {"q": "They had lunch at ___.", "type": "single", "options": [{"text": "a restaurant"}, {"text": "home"}], "correct": [0]}, {"q": "They went to the ___.", "type": "single", "options": [{"text": "theatre"}, {"text": "cinema"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'gaps', replace($blk${"title": "Послушай аудио ещё раз и впиши пропущенные слова", "mode": "type", "text": "1. Nick had a fun day last __Saturday|saturday__.\n2. First, Nick went to the __park__.\n3. He scored __three|3__ goals.\n4. Nick ate __two|2__ cheeseburgers.\n5. Nick and Ted drank __lemonade__.\n6. The __film|movie__ was really exciting.\n7. Gary and Ted went home at __seven|7__ o'clock."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'gaps', replace($blk${"title": "Прочитай рассказ Элены о её выходных и впиши глаголы в прошедшем времени. Смотри пример: go → went", "mode": "type", "text": "Last Sunday I went to the beach with my friends. First, we went (go) to the beach and we went swimming. But the sea __was__ (be) cold, so we __got__ (get) out quickly! Then we played (play) beach volleyball. Amy and I were (be) Team A and the boys were Team B. It was a lot of fun. Amy and I were the winners! After that, we __had__ (have) a picnic on the sand. We __ate__ (eat) sandwiches and __drank__ (drink) coke. Mum came and took us home in her car. We arrived home at 4 o'clock. It was a great day out!"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'task', replace($blk${"title": "Напиши свой рассказ", "needs_review": true, "html": "<p>Супер, ты отлично справляешься! Теперь напиши небольшой рассказ о своих прошлых выходных или о каком-то памятном и интересном для тебя дне ;)</p><p>Воспользуйся примером текста Элены и словами <b>First, Then, After that</b>. Рассказ должен быть в прошедшем времени — проверяй, в какой форме ты пишешь глаголы.</p><p><i><b>First</b>, we visited Madame Tussaud's.<br><b>Then</b>, we went to the London Aquarium.<br><b>After that</b>, we went to a Mexican restaurant.</i></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_jump.webp\" alt=\"\" style=\"height:180px\"></p><h3>Классная работа! 🖐</h3><p>Первая часть готова. Теперь повторим изученный материал, чтобы ты смог хорошо подготовиться к тесту. Для тебя нет ничего невозможного 😎</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'match', replace($blk${"title": "Давай сначала вспомним названия профессий. Соедини название с картинкой", "pairs": [{"left": "nurse", "right_image": "@@MEDIA@@gg2/u6/nurse.webp"}, {"left": "builder", "right_image": "@@MEDIA@@gg2/u6/builder.webp"}, {"left": "police officer", "right_image": "@@MEDIA@@gg2/u6/police_officer.webp"}, {"left": "doctor", "right_image": "@@MEDIA@@gg2/u6/doctor.webp"}, {"left": "farmer", "right_image": "@@MEDIA@@gg2/u6/farmer.webp"}, {"left": "vet", "right_image": "@@MEDIA@@gg2/u6/vet.webp"}, {"left": "teacher", "right_image": "@@MEDIA@@gg2/u6/teacher.webp"}, {"left": "chef", "right_image": "@@MEDIA@@gg2/u6/chef.webp"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'gaps', replace($blk${"title": "Молодец! А сейчас вспомним прошедшее время. Прочитай диалог и вставь подходящие слова", "mode": "drag", "text": "A: Where __did__ you go last weekend?\nB: I __went__ to the zoo.\nA: What did you __see__?\nB: We __saw__ lions and monkeys.\nA: __Did__ you have lunch there?\nB: Yes, we __had__ pizza."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'gaps', replace($blk${"title": "Ты отлично справляешься! Прочитай предложения и заполни пропуски", "mode": "drag", "text": "1. I __had__ lunch at 2 p.m. yesterday.\n2. I __met__ Ted at the cinema an hour ago.\n3. Yesterday Mum __drank__ tea after dinner.\n4. We __bought__ some cakes at the supermarket.\n5. Jim __took__ lots of photos on holiday last year.\n6. Dad __gave__ me a watch for my last birthday."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'gaps', replace($blk${"title": "Следующее задание немного посложнее… Но ты обязательно справишься! Прочитай диалог и заполни пропуски", "mode": "drag", "text": "Pam: Please __can__ I borrow your laptop, dad?\nDad: No, __sorry__, you can't. I'm using it. Why do you need it?\nPam: I'm planning a project for school and I want to look at the Internet.\nDad: Is it OK __if__ I look at your notes?\nPam: Yes, that's __fine__. Here.\nDad: They're good.\nPam: Come on, dad. Can I use your laptop, __please__? Just for an hour.\nDad: Oh, __all right__."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/congrats_popper.webp\" alt=\"\" style=\"height:180px\"></p><h3>Hurray! 🌟</h3><p>Домашняя работа выполнена на отлично — всё благодаря твоим стараниям. Теперь ты готов к тесту на 100%! Увидимся на занятии.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11)
returning sort_order, type;
