-- Go Getter 2 · Unit 4 · Our world · Homework 1
-- собрано tools/gg2_build.py --lesson u4_hw1
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 4 · Our world', 4 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 4 · Our world');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 1', 'homework', 60, false, 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 4 · Our world'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 1');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 4 · Our world' and l.title = 'Homework 1';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 4 · Our world' and l.title = 'Homework 1';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет! 👋</h2><p>Сегодня тебя ждёт изучение новых слов. Ты повторишь названия разных мест, которые есть на нашей планете. Давай начинать 😉</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'flashcards', replace($blk${"cards": [{"text": "beach", "translation": "пляж", "audio_tts": "beach", "image": "@@MEDIA@@gg2/u4/beach.webp"}, {"text": "city", "translation": "крупный город", "audio_tts": "city", "image": "@@MEDIA@@gg2/u4/city.webp"}, {"text": "desert", "translation": "пустыня", "audio_tts": "desert", "image": "@@MEDIA@@gg2/u4/desert.webp"}, {"text": "forest", "translation": "лес", "audio_tts": "forest", "image": "@@MEDIA@@gg2/u4/forest.webp"}, {"text": "island", "translation": "остров", "audio_tts": "island", "image": "@@MEDIA@@gg2/u4/island.webp"}, {"text": "lake", "translation": "озеро", "audio_tts": "lake", "image": "@@MEDIA@@gg2/u4/lake.webp"}, {"text": "mountain", "translation": "гора", "audio_tts": "mountain", "image": "@@MEDIA@@gg2/u4/mountain.webp"}, {"text": "river", "translation": "река", "audio_tts": "river", "image": "@@MEDIA@@gg2/u4/river.webp"}, {"text": "sea", "translation": "море", "audio_tts": "sea", "image": "@@MEDIA@@gg2/u4/sea.webp"}, {"text": "town", "translation": "городок", "audio_tts": "town", "image": "@@MEDIA@@gg2/u4/town.webp"}, {"text": "volcano", "translation": "вулкан", "audio_tts": "volcano", "image": "@@MEDIA@@gg2/u4/volcano.webp"}, {"text": "waterfall", "translation": "водопад", "audio_tts": "waterfall", "image": "@@MEDIA@@gg2/u4/waterfall.webp"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'match', replace($blk${"title": "Соедини картинку с названием места", "pairs": [{"left_image": "@@MEDIA@@gg2/u4/beach.webp", "right": "beach", "right_audio_tts": "beach"}, {"left_image": "@@MEDIA@@gg2/u4/city.webp", "right": "city", "right_audio_tts": "city"}, {"left_image": "@@MEDIA@@gg2/u4/desert.webp", "right": "desert", "right_audio_tts": "desert"}, {"left_image": "@@MEDIA@@gg2/u4/forest.webp", "right": "forest", "right_audio_tts": "forest"}, {"left_image": "@@MEDIA@@gg2/u4/island.webp", "right": "island", "right_audio_tts": "island"}, {"left_image": "@@MEDIA@@gg2/u4/lake.webp", "right": "lake", "right_audio_tts": "lake"}, {"left_image": "@@MEDIA@@gg2/u4/mountain.webp", "right": "mountain", "right_audio_tts": "mountain"}, {"left_image": "@@MEDIA@@gg2/u4/river.webp", "right": "river", "right_audio_tts": "river"}, {"left_image": "@@MEDIA@@gg2/u4/sea.webp", "right": "sea", "right_audio_tts": "sea"}, {"left_image": "@@MEDIA@@gg2/u4/town.webp", "right": "town", "right_audio_tts": "town"}, {"left_image": "@@MEDIA@@gg2/u4/volcano.webp", "right": "volcano", "right_audio_tts": "volcano"}, {"left_image": "@@MEDIA@@gg2/u4/waterfall.webp", "right": "waterfall", "right_audio_tts": "waterfall"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Как по-английски «пляж»?", "type": "single", "options": [{"text": "beach"}, {"text": "forest"}, {"text": "lake"}], "correct": [0]}, {"q": "Как по-английски «крупный город»?", "type": "single", "options": [{"text": "island"}, {"text": "city"}, {"text": "mountain"}], "correct": [1]}, {"q": "Как по-английски «пустыня»?", "type": "single", "options": [{"text": "lake"}, {"text": "river"}, {"text": "desert"}], "correct": [2]}, {"q": "Как по-английски «лес»?", "type": "single", "options": [{"text": "forest"}, {"text": "mountain"}, {"text": "sea"}], "correct": [0]}, {"q": "Как по-английски «остров»?", "type": "single", "options": [{"text": "river"}, {"text": "island"}, {"text": "town"}], "correct": [1]}, {"q": "Как по-английски «озеро»?", "type": "single", "options": [{"text": "sea"}, {"text": "volcano"}, {"text": "lake"}], "correct": [2]}, {"q": "Как по-английски «гора»?", "type": "single", "options": [{"text": "mountain"}, {"text": "town"}, {"text": "waterfall"}], "correct": [0]}, {"q": "Как по-английски «река»?", "type": "single", "options": [{"text": "volcano"}, {"text": "river"}, {"text": "beach"}], "correct": [1]}, {"q": "Как по-английски «море»?", "type": "single", "options": [{"text": "waterfall"}, {"text": "city"}, {"text": "sea"}], "correct": [2]}, {"q": "Как по-английски «городок»?", "type": "single", "options": [{"text": "town"}, {"text": "beach"}, {"text": "desert"}], "correct": [0]}, {"q": "Как по-английски «вулкан»?", "type": "single", "options": [{"text": "city"}, {"text": "volcano"}, {"text": "forest"}], "correct": [1]}, {"q": "Как по-английски «водопад»?", "type": "single", "options": [{"text": "desert"}, {"text": "island"}, {"text": "waterfall"}], "correct": [2]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_highfive.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет-привет, самый старательный ученик!</h2><p>В этой части домашнего задания мы закрепим всё, что выучили. Для этого нужно сделать несколько упражнений. Время пролетит незаметно. Вперёд 😄</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'hotspot', replace($blk${"title": "Помнишь, в прошлом юните ты с учителем изучал различные технологии? Эту картинку нарисовала нейросеть! Поставь название каждого места к нужной точке.", "mode": "label", "image": "@@MEDIA@@gg2/u4/book_places_ai.webp", "points": [{"x": 47, "y": 27, "text": "waterfall", "audio_tts": "waterfall"}, {"x": 60, "y": 8, "text": "forest", "audio_tts": "forest"}, {"x": 30, "y": 44, "text": "lake", "audio_tts": "lake"}, {"x": 73, "y": 54, "text": "mountain", "audio_tts": "mountain"}, {"x": 59, "y": 73, "text": "city", "audio_tts": "city"}, {"x": 66, "y": 90, "text": "beach", "audio_tts": "beach"}, {"x": 18, "y": 82, "text": "sea", "audio_tts": "sea"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'match', replace($blk${"title": "Молодец! А теперь соедини название места с его описанием.", "pairs": [{"left": "desert", "right": "There aren’t any plants because it’s too hot.", "right_audio_tts": "There aren't any plants because it's too hot."}, {"left": "town", "right": "People live in this small place.", "right_audio_tts": "People live in this small place."}, {"left": "beach", "right": "There is sand next to the sea.", "right_audio_tts": "There is sand next to the sea."}, {"left": "forest", "right": "There are a lot of trees.", "right_audio_tts": "There are a lot of trees."}, {"left": "volcano", "right": "This is a mountain but it hasn’t got a top.", "right_audio_tts": "This is a mountain but it hasn't got a top."}, {"left": "city", "right": "People live in this big place.", "right_audio_tts": "People live in this big place."}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'text', replace($blk${"html": "<p>Ты великолепно справился! Посмотри на картинку. Это Платон. Давай узнаем о нём больше. Прочитай текст и выбери правильный вариант для каждого пропуска.</p><p><img src=\"@@MEDIA@@gg2/u4/plato.webp\" alt=\"\" style=\"max-width:100%;max-height:260px;border-radius:12px\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "I live in Greece. There are ___ with lots of trees …", "type": "single", "options": [{"text": "forests"}, {"text": "deserts"}], "correct": [0]}, {"q": "… and there are lots of ___ in the sea.", "type": "single", "options": [{"text": "waterfalls"}, {"text": "islands"}], "correct": [1]}, {"q": "I live in a small ___.", "type": "single", "options": [{"text": "town"}, {"text": "beach"}], "correct": [0]}, {"q": "In the holidays, I sometimes stay with my uncle in the big ___.", "type": "single", "options": [{"text": "river"}, {"text": "city"}], "correct": [1]}, {"q": "In winter, we always go skiing in the ___.", "type": "single", "options": [{"text": "lake"}, {"text": "mountains"}], "correct": [1]}, {"q": "In summer, we go to an island. I like swimming in the ___.", "type": "single", "options": [{"text": "sea"}, {"text": "volcano"}], "correct": [0]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'task', replace($blk${"title": "Необязательное задание: мои места для отдыха", "needs_review": true, "html": "<p>Главная часть домашней работы позади, и ты просто супер постарался! Это задание необязательное. Перерисуй табличку себе на листочек или в тетрадь и заполни её своими идеями. Можешь написать ответы и здесь. Обязательно поделись тем, что написал, с учителем на уроке.</p><table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse\"><tr><th>Holiday places</th><th>Winter or summer?</th><th>Activities you can do there?</th><th>How often do you go there?</th></tr><tr><td>sea or lake</td><td></td><td></td><td></td></tr><tr><td>forest</td><td></td><td></td><td></td></tr><tr><td>mountain</td><td></td><td></td><td></td></tr><tr><td>town or city</td><td></td><td></td><td></td></tr></table>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_star.webp\" alt=\"\" style=\"height:180px\"></p><h3>Классная работа!</h3><p>Поздравляю — домашняя работа выполнена очень здорово. До встречи на занятии 🖐</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10)
returning sort_order, type;
