-- Go Getter 2 · Unit 5 · Homework 5
-- собрано tools/gg2_build.py --lesson u5_hw5
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 5', 5 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 5');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 5', 'homework', 60, false, 4
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 5'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 5');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 4
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 5' and l.title = 'Homework 5';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 5' and l.title = 'Homework 5';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_laptop.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет, самый старательный и классный ученик!</h2><p>Сегодня тебе предстоит много читать :) Но ты точно справишься, ведь для тебя нет ничего невозможного 😎 Давай начнём?</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'text', replace($blk${"html": "<p>Для начала давай прочитаем текст.</p><p><img src=\"@@MEDIA@@gg2/u5/book_london.webp\" alt=\"London Eye\" style=\"max-width:100%\"></p><h3>An amazing city</h3><p>London is a very big city today. It was very big in 1965 too. My grandpa was a boy in London then.</p><p>In 1965 London was an exciting place for fashion and music. The fashion industry was new then and there were a lot of small clothes shops. Pop music was also new, and bands like The Beatles were very popular. There were a lot of small cafés. The theatres were busy, and the museums were full of people.</p><p>Today some things about London are different. Now there are more big shops and shopping centres. There are many large cafés. The theatres have more music shows today like <i>Mamma Mia</i>. The museums are full today too. But there are more things to do today. For example, you can have a ride on the London Eye. It was new in 2000.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'quiz', replace($blk${"title": "Прекрасно! Прочитай предложения и выбери правильный вариант", "questions": [{"q": "London is a very ___ place.", "type": "single", "options": [{"text": "big"}, {"text": "small"}], "correct": [0]}, {"q": "In 1965 there were a lot of ___ shops in London.", "type": "single", "options": [{"text": "big"}, {"text": "small"}], "correct": [1]}, {"q": "Pop music was ___ then.", "type": "single", "options": [{"text": "new"}, {"text": "old"}], "correct": [0]}, {"q": "The museums ___ full in 1965.", "type": "single", "options": [{"text": "weren't"}, {"text": "were"}], "correct": [1]}, {"q": "Today London has got more ___.", "type": "single", "options": [{"text": "theatres"}, {"text": "shopping centres"}], "correct": [1]}, {"q": "The London Eye is a ___.", "type": "single", "options": [{"text": "ride"}, {"text": "museum"}], "correct": [0]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'gaps', replace($blk${"title": "Ещё раз прочитай текст и ответь на вопросы коротким ответом. Первый — пример", "mode": "type", "text": "1. Was the writer's grandpa a boy in 1965? Yes, he was.\n2. Was pop music new in London in 1965? __Yes, it was|Yes, it was.|Yes it was|Yes it was.__\n3. Were the theatres busy in 1965? __Yes, they were|Yes, they were.|Yes they were|Yes they were.__\n4. Were there large cafés like Starbucks in the past? __No, there weren't|No, there weren’t|No, there weren't.|No, there weren’t.|No there weren't|No there weren’t|No there weren't.|No there weren’t.__\n5. Are there more music shows today? __Yes, there are|Yes, there are.|Yes there are|Yes there are.__"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Места в городе</h3><p>Ты просто супер! Повторим места в городе. Посмотри на картинку, прочитай предложение и впиши пропущенное слово целиком — первая буква подскажет. Первое предложение — на два слова.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'exact_input', replace($blk${"items": [{"image": "@@MEDIA@@gg2/u5/sports_centre.webp", "prompt": "1. Let's play basketball at the s______ c______.", "accept": ["sports centre", "sports center"], "audio_tts": "sports centre"}, {"image": "@@MEDIA@@gg2/u5/film_studio.webp", "prompt": "2. They're making a film at the film s______.", "accept": ["studio", "film studio"], "audio_tts": "film studio"}, {"image": "@@MEDIA@@gg2/u5/theme_park.webp", "prompt": "3. The rides at this theme p______ are exciting.", "accept": ["park", "theme park"], "audio_tts": "theme park"}, {"image": "@@MEDIA@@gg2/u5/shopping_centre.webp", "prompt": "4. Do you want to buy some clothes at the s______ centre?", "accept": ["shopping", "shopping centre", "shopping center"], "audio_tts": "shopping centre"}, {"image": "@@MEDIA@@gg2/u5/police_station.webp", "prompt": "5. You can look for your lost bag at the police s______.", "accept": ["station", "police station"], "audio_tts": "police station"}, {"image": "@@MEDIA@@gg2/u5/post_office.webp", "prompt": "6. I'm going to the post o______ to post a letter.", "accept": ["office", "post office"], "audio_tts": "post office"}, {"image": "@@MEDIA@@gg2/u5/train_station.webp", "prompt": "7. Let's buy our tickets to London at the t______ station.", "accept": ["train", "train station"], "audio_tts": "train station"}, {"image": "@@MEDIA@@gg2/u5/swimming_pool.webp", "prompt": "8. I like the s______ pool, but I like the sea more!", "accept": ["swimming", "swimming pool"], "audio_tts": "swimming pool"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'gaps', replace($blk${"title": "Ты уже на финишной прямой! Впиши год цифрами. Подсказка: 1800 — eighteen hundred, 1999 — nineteen ninety-nine, 2008 — two thousand and eight, 2010 — twenty ten", "mode": "type", "text": "1. nineteen hundred — __1900__\n2. nineteen fifteen — __1915__\n3. nineteen fifty — __1950__\n4. nineteen sixty-five — __1965__\n5. two thousand — __2000__\n6. twenty fifteen — __2015__"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/congrats_popper.webp\" alt=\"\" style=\"height:180px\"></p><h3>Ура, всё готово! 🎉</h3><p>Ты много читал и отлично справился. До встречи на уроке!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7)
returning sort_order, type;
