-- Go Getter 2 · Unit 1 · Homework 3
-- собрано tools/gg2_build.py --lesson u1_hw3
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 1', 1 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 1');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 3', 'homework', 60, false, 2
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 1'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 3');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 2
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 1' and l.title = 'Homework 3';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 1' and l.title = 'Homework 3';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Добро пожаловать в домашку! 👋</h2><p>В этом уроке тебя ждёт интересное видео и классные задания! В конце урока есть дополнительное задание — его можно выполнить по желанию, НО если выполнишь, то будешь нереально крут!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'text', replace($blk${"html": "<p>Для начала посмотри видео. Попробуй угадать, кто из ребят любит играть в футбол: Анна, Макс или Хэмми? А ты любишь играть в футбол в свободное время?</p><p><img src=\"@@MEDIA@@gg2/u1/book_football_question.webp\" alt=\"\" style=\"height:260px\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'video', replace($blk${"title": "Видео: Do you play football in your free time?", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'match', replace($blk${"title": "Посмотри видео ещё раз и соедини вопросы и ответы", "pairs": [{"left": "Do you play football in your free time, Max?", "right": "No, I don't.", "right_audio_tts": "No, I don't."}, {"left": "Does Anna play football in her free time?", "right": "No, she doesn't.", "right_audio_tts": "No, she doesn't."}, {"left": "Do you play football in your free time, Hammy?", "right": "Yes, I do.", "right_audio_tts": "Yes, I do."}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'quiz', replace($blk${"title": "Выбери только верные утверждения", "questions": [{"q": "Выбери только верные утверждения. Если нужно — посмотри видео ещё раз.", "type": "multiple", "image": "@@MEDIA@@gg2/u1/book_park.webp", "options": [{"text": "Max doesn't play football."}, {"text": "Anna doesn't like football."}, {"text": "Hammy doesn't play football."}], "correct": [0, 1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Замечательно! 👏</h3><p>Мы с тобой посмотрели видео, а теперь настало время потрудиться! Посмотри на предложения ниже и выбери правильный вариант для каждого пропуска.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'quiz', replace($blk${"title": "Выбери правильный вариант для каждого пропуска", "questions": [{"q": "1. My sister ___ a hobby.", "type": "single", "options": [{"text": "don't have"}, {"text": "doesn't have"}, {"text": "doesn't has"}], "correct": [1]}, {"q": "2. They ___ my pictures.", "type": "single", "options": [{"text": "don't likes"}, {"text": "doesn't like"}, {"text": "don't like"}], "correct": [2]}, {"q": "3. David ___ karate.", "type": "single", "options": [{"text": "doesn't do"}, {"text": "don't does"}, {"text": "doesn't does"}], "correct": [0]}, {"q": "4. My parents ___ tennis.", "type": "single", "options": [{"text": "don't plays"}, {"text": "doesn't play"}, {"text": "don't play"}], "correct": [2]}, {"q": "5. She ___ French at school.", "type": "single", "options": [{"text": "doesn't study"}, {"text": "don't study"}, {"text": "doesn't studies"}], "correct": [0]}, {"q": "6. My grandfather ___ chess.", "type": "single", "options": [{"text": "doesn't plays"}, {"text": "doesn't play"}, {"text": "don't play"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Отличная работа! 💪</h3><p>Давай немного переведём дух и сыграем в игру. Твоя задача — заполнить пропуски!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'gaps', replace($blk${"title": "Do or does? Do or play? Перетащи слова в пропуски", "mode": "drag", "text": "1. __Do__ you play tennis at the weekend?\n2. __Does__ your brother do karate?\n3. My sister __does__ ballet on Mondays.\n4. We __play__ chess after school.\n5. Max doesn't __play__ football in his free time.\n6. I __do__ my homework in the evening."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'gaps', replace($blk${"title": "Отлично! Давай теперь потренируемся составлять вопросы. Впиши Do или Does в пропуски", "mode": "type", "image": "@@MEDIA@@gg2/u1/book_carla_rocco.webp", "text": "1. __Does|does__ Carla paint pictures?\n2. __Does|does__ Rocco paint pictures?\n3. __Do|do__ Rocco and Carla like music?\n4. __Do|do__ Rocco and Carla play football?\n5. __Does|does__ Rocco play chess?\n6. __Does|does__ Carla play chess?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'task', replace($blk${"title": "Дополнительное задание ⭐", "needs_review": true, "html": "<p>Ты справился с основной частью домашнего задания! Это задание — для самых больших умников: оно дополнительное, но ты будешь мегакрутым учеником, если выполнишь его!</p><p>В таблице отмечено, чем любят и не любят заниматься Carla (кошка) и Rocco (енот). Письменно ответь на вопросы из предыдущего упражнения (например: <i>Yes, she does. / No, he doesn't.</i>).</p><p><img src=\"@@MEDIA@@gg2/u1/book_carla_rocco_table.webp\" alt=\"\" style=\"height:220px\"></p><ol><li>Does Carla paint pictures?</li><li>Does Rocco paint pictures?</li><li>Do Rocco and Carla like music?</li><li>Do Rocco and Carla play football?</li><li>Does Rocco play chess?</li><li>Does Carla play chess?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_smiley.webp\" alt=\"\" style=\"height:200px\"></p><h3>Поздравляю! 🎉</h3><p>Ты завершил домашнее задание, ты замечательный ученик! Лови за это сердечко ❤️ Увидимся на занятии!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11)
returning sort_order, type;
