-- Go Getter 2 · Unit 1 · School · Homework 7
-- собрано tools/gg2_build.py --lesson u1_hw7
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 1 · School', 1 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 1 · School');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 7', 'homework', 60, false, 6
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 1 · School'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 7');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 6
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 1 · School' and l.title = 'Homework 7';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 1 · School' and l.title = 'Homework 7';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_highfive.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет! 👋</h2><p>Добро пожаловать в домашнее задание! В этом уроке тебя ждут несколько интересных упражнений, которые помогут закрепить полученные знания. Поехали!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'match', replace($blk${"title": "Давай сначала вспомним школьные предметы. Соедини название предмета с картинкой", "pairs": [{"left_image": "@@MEDIA@@gg2/u1/subj_art.webp", "right": "Art", "right_audio_tts": "Art"}, {"left_image": "@@MEDIA@@gg2/u1/subj_computer.webp", "right": "Computer Studies", "right_audio_tts": "Computer Studies"}, {"left_image": "@@MEDIA@@gg2/u1/subj_english.webp", "right": "English", "right_audio_tts": "English"}, {"left_image": "@@MEDIA@@gg2/u1/subj_geography.webp", "right": "Geography", "right_audio_tts": "Geography"}, {"left_image": "@@MEDIA@@gg2/u1/subj_history.webp", "right": "History", "right_audio_tts": "History"}, {"left_image": "@@MEDIA@@gg2/u1/subj_maths.webp", "right": "Maths", "right_audio_tts": "Maths"}, {"left_image": "@@MEDIA@@gg2/u1/subj_music.webp", "right": "Music", "right_audio_tts": "Music"}, {"left_image": "@@MEDIA@@gg2/u1/subj_pe.webp", "right": "P.E.", "right_audio_tts": "P.E."}, {"left_image": "@@MEDIA@@gg2/u1/subj_science.webp", "right": "Science", "right_audio_tts": "Science"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'sort', replace($blk${"title": "Молодец! Давай вспомним, с какими занятиями мы используем do, а с какими — play", "groups": [{"name": "do", "items": [{"text": "ballet"}, {"text": "karate"}, {"text": "pottery"}]}, {"name": "play", "items": [{"text": "basketball"}, {"text": "chess"}, {"text": "football"}]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'match', replace($blk${"title": "Предложения и вопросы распались на две части и перемешались 😱 Найди вторую половинку для каждого", "pairs": [{"left": "Do you read", "right": "Harry Potter books in English?"}, {"left": "In Maths we can use", "right": "a calculator for problems."}, {"left": "We write games on laptops", "right": "in our Computer Studies lesson."}, {"left": "Do you need a dictionary", "right": "for your French homework?"}, {"left": "I like Geography because", "right": "I think maps are very interesting."}, {"left": "His trainers are in his bag", "right": "because he has P.E. today."}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'quiz', replace($blk${"title": "Выбери правильную форму глагола", "questions": [{"q": "1. I ___ football at break time.", "type": "single", "options": [{"text": "plays"}, {"text": "play"}, {"text": "plaies"}], "correct": [1]}, {"q": "2. She ___ TV before dinner.", "type": "single", "options": [{"text": "watchs"}, {"text": "watch"}, {"text": "watches"}], "correct": [2]}, {"q": "3. John ___ a new pencil.", "type": "single", "options": [{"text": "doesn't have"}, {"text": "doesn't has"}, {"text": "don't have"}], "correct": [0]}, {"q": "4. They ___ to school on Sunday.", "type": "single", "options": [{"text": "doesn't go"}, {"text": "don't go"}], "correct": [1]}, {"q": "5. We ___ pottery at school.", "type": "single", "options": [{"text": "don't do"}, {"text": "doesn't do"}], "correct": [0]}, {"q": "6. You ___ to music on the bus.", "type": "single", "options": [{"text": "listenes"}, {"text": "listens"}, {"text": "listen"}], "correct": [2]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Молодец! 💪</h3><p>Ты выполнил бóльшую часть заданий, осталось совсем немного. Потренируйся составлять предложения.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["I", "always", "do", "ballet", "on", "Monday."], "sentence": "I always do ballet on Monday.", "audio_tts": "I always do ballet on Monday.", "image": "@@MEDIA@@gg2/u1/ballet_girl.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["He", "sometimes", "walks", "to", "school."], "sentence": "He sometimes walks to school.", "audio_tts": "He sometimes walks to school.", "image": "@@MEDIA@@gg2/u1/walk_to_school.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'order', replace($blk${"words": ["I", "never", "play", "football", "before", "school."], "sentence": "I never play football before school.", "audio_tts": "I never play football before school.", "image": "@@MEDIA@@gg2/u1/football_morning.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'order', replace($blk${"words": ["Do", "you", "have", "a", "sandwich", "for", "lunch?"], "sentence": "Do you have a sandwich for lunch?", "audio_tts": "Do you have a sandwich for lunch?", "image": "@@MEDIA@@gg2/u1/lunch_box.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'task', replace($blk${"title": "Задание со звёздочкой ⭐", "needs_review": true, "html": "<p>Это последнее задание, но оно «со звёздочкой». Вспомни вопросы, которые мы учили несколько уроков назад. Обычно я задаю вопрос, а ты отвечаешь. А сейчас наоборот: я напишу ответы, а ты составь и запиши к ним вопросы.</p><p><i>Например: ответ «I'm eleven». Вопрос к нему — «How old are you?»</i></p><ol><li>I'm Paul.</li><li>P-A-U-L.</li><li>22 North Street, Oldtown.</li><li>It's 02465 438967.</li><li>It's paulharris@mymail.com.</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_star.webp\" alt=\"\" style=\"height:200px\"></p><h3>Ты справился! 🌟</h3><p>Ты — большой молодец! За это держи звёздочку.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11)
returning sort_order, type;
