-- Go Getter 2 · Unit 4 · Homework 2
-- собрано tools/gg2_build.py --lesson u4_hw2
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 4', 4 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 4');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 2', 'homework', 60, false, 1
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 4'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 2');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 1
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 4' and l.title = 'Homework 2';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 4' and l.title = 'Homework 2';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_rocket.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет-привет!</h2><p>Давай вспомним слова, которые ты изучал на уроке. Благодаря этому заданию ты точно их запомнишь. Вперёд 🏃‍♂️</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'flashcards', replace($blk${"cards": [{"text": "boring", "translation": "скучный", "audio_tts": "boring", "image": "@@MEDIA@@gg2/u4/boring.webp"}, {"text": "cheap", "translation": "дешёвый", "audio_tts": "cheap", "image": "@@MEDIA@@gg2/u4/cheap.webp"}, {"text": "dangerous", "translation": "опасный", "audio_tts": "dangerous", "image": "@@MEDIA@@gg2/u4/dangerous.webp"}, {"text": "difficult", "translation": "сложный", "audio_tts": "difficult", "image": "@@MEDIA@@gg2/u4/difficult.webp"}, {"text": "easy", "translation": "лёгкий", "audio_tts": "easy", "image": "@@MEDIA@@gg2/u4/easy.webp"}, {"text": "exciting", "translation": "увлекательный", "audio_tts": "exciting", "image": "@@MEDIA@@gg2/u4/exciting.webp"}, {"text": "expensive", "translation": "дорогой", "audio_tts": "expensive", "image": "@@MEDIA@@gg2/u4/expensive.webp"}, {"text": "high", "translation": "высокий", "audio_tts": "high", "image": "@@MEDIA@@gg2/u4/high.webp"}, {"text": "low", "translation": "низкий", "audio_tts": "low", "image": "@@MEDIA@@gg2/u4/low.webp"}, {"text": "safe", "translation": "безопасный", "audio_tts": "safe", "image": "@@MEDIA@@gg2/u4/safe.webp"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'match', replace($blk${"title": "Соедини картинку со словом", "pairs": [{"left_image": "@@MEDIA@@gg2/u4/boring.webp", "right": "boring", "right_audio_tts": "boring"}, {"left_image": "@@MEDIA@@gg2/u4/cheap.webp", "right": "cheap", "right_audio_tts": "cheap"}, {"left_image": "@@MEDIA@@gg2/u4/dangerous.webp", "right": "dangerous", "right_audio_tts": "dangerous"}, {"left_image": "@@MEDIA@@gg2/u4/difficult.webp", "right": "difficult", "right_audio_tts": "difficult"}, {"left_image": "@@MEDIA@@gg2/u4/easy.webp", "right": "easy", "right_audio_tts": "easy"}, {"left_image": "@@MEDIA@@gg2/u4/exciting.webp", "right": "exciting", "right_audio_tts": "exciting"}, {"left_image": "@@MEDIA@@gg2/u4/expensive.webp", "right": "expensive", "right_audio_tts": "expensive"}, {"left_image": "@@MEDIA@@gg2/u4/high.webp", "right": "high", "right_audio_tts": "high"}, {"left_image": "@@MEDIA@@gg2/u4/low.webp", "right": "low", "right_audio_tts": "low"}, {"left_image": "@@MEDIA@@gg2/u4/safe.webp", "right": "safe", "right_audio_tts": "safe"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Как по-английски «скучный»?", "type": "single", "options": [{"text": "boring"}, {"text": "difficult"}, {"text": "exciting"}], "correct": [0]}, {"q": "Как по-английски «дешёвый»?", "type": "single", "options": [{"text": "easy"}, {"text": "cheap"}, {"text": "expensive"}], "correct": [1]}, {"q": "Как по-английски «опасный»?", "type": "single", "options": [{"text": "exciting"}, {"text": "high"}, {"text": "dangerous"}], "correct": [2]}, {"q": "Как по-английски «сложный»?", "type": "single", "options": [{"text": "difficult"}, {"text": "expensive"}, {"text": "low"}], "correct": [0]}, {"q": "Как по-английски «лёгкий»?", "type": "single", "options": [{"text": "high"}, {"text": "easy"}, {"text": "safe"}], "correct": [1]}, {"q": "Как по-английски «увлекательный»?", "type": "single", "options": [{"text": "low"}, {"text": "boring"}, {"text": "exciting"}], "correct": [2]}, {"q": "Как по-английски «дорогой»?", "type": "single", "options": [{"text": "expensive"}, {"text": "safe"}, {"text": "cheap"}], "correct": [0]}, {"q": "Как по-английски «высокий»?", "type": "single", "options": [{"text": "boring"}, {"text": "high"}, {"text": "dangerous"}], "correct": [1]}, {"q": "Как по-английски «низкий»?", "type": "single", "options": [{"text": "cheap"}, {"text": "difficult"}, {"text": "low"}], "correct": [2]}, {"q": "Как по-английски «безопасный»?", "type": "single", "options": [{"text": "safe"}, {"text": "dangerous"}, {"text": "easy"}], "correct": [0]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Сравниваем! 🤹</h3><p>Настало время для новой домашней работы. Сегодня тебя ждёт одно интересное правило, которое ты прошёл на уроке, и несколько заданий, которые помогут его усвоить.</p><p>Начнём с видео: 1. Посмотри его. 2. Выбери персонажа, который понравился тебе больше всех, включи видео ещё раз и повторяй за своим героем :)</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'video', replace($blk${"title": "Посмотри видео и повторяй за своим героем", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'match', replace($blk${"title": "Соедини предложения с героем, который их произносил.", "pairs": [{"left": "Герой 1", "right": "You’re faster than me at juggling.", "right_audio_tts": "You're faster than me at juggling."}, {"left": "Герой 2", "right": "Yes, but I’m more surprising than you!", "right_audio_tts": "Yes, but I'm more surprising than you!"}, {"left": "Герой 3", "right": "I’m better than you at tricks.", "right_audio_tts": "I'm better than you at tricks."}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'text', replace($blk${"html": "<p>Тебя не проведёшь! А теперь посмотри на правило из конца видео:</p><p><img src=\"@@MEDIA@@gg2/u4/book_comparative_rule.webp\" alt=\"\" style=\"max-width:100%;max-height:360px;border-radius:12px\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'match', replace($blk${"title": "Посмотри на правило. Соедини обычное слово с его сравнительной формой.", "pairs": [{"left": "big", "right": "bigger", "right_audio_tts": "bigger"}, {"left": "high", "right": "higher", "right_audio_tts": "higher"}, {"left": "exciting", "right": "more exciting", "right_audio_tts": "more exciting"}, {"left": "dangerous", "right": "more dangerous", "right_audio_tts": "more dangerous"}, {"left": "good", "right": "better", "right_audio_tts": "better"}, {"left": "bad", "right": "worse", "right_audio_tts": "worse"}, {"left": "low", "right": "lower", "right_audio_tts": "lower"}, {"left": "boring", "right": "more boring", "right_audio_tts": "more boring"}, {"left": "expensive", "right": "more expensive", "right_audio_tts": "more expensive"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'text', replace($blk${"html": "<p>Великолепно! Следующее задание кажется простым, но будь внимателен. Расставь слова по порядку, чтобы получились предложения.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'order', replace($blk${"words": ["I’m", "taller", "than", "my", "friend."], "sentence": "I’m taller than my friend.", "audio_tts": "I'm taller than my friend."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'order', replace($blk${"words": ["Kayaking", "is", "more", "exciting", "than", "cycling."], "sentence": "Kayaking is more exciting than cycling.", "audio_tts": "Kayaking is more exciting than cycling.", "image": "@@MEDIA@@gg2/u4/kayaking.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'order', replace($blk${"words": ["Hamburgers", "are", "better", "than", "hot", "dogs."], "sentence": "Hamburgers are better than hot dogs.", "audio_tts": "Hamburgers are better than hot dogs."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'order', replace($blk${"words": ["Walking", "is", "slower", "than", "running."], "sentence": "Walking is slower than running.", "audio_tts": "Walking is slower than running.", "image": "@@MEDIA@@gg2/u4/slow.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13),
('<lesson_id>', 'order', replace($blk${"words": ["Winter", "weather", "is", "worse", "than", "summer", "weather."], "sentence": "Winter weather is worse than summer weather.", "audio_tts": "Winter weather is worse than summer weather."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 14),
('<lesson_id>', 'order', replace($blk${"words": ["Geography", "books", "are", "more", "interesting", "than", "Maths", "books."], "sentence": "Geography books are more interesting than Maths books.", "audio_tts": "Geography books are more interesting than Maths books."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 15),
('<lesson_id>', 'gaps', replace($blk${"title": "Прочитай разговор Джейка и Майкла и впиши правильную форму слова из скобок.", "mode": "type", "image": "@@MEDIA@@gg2/u4/jake_michael.webp", "text": "Jake: Let’s go swimming in the lake. The water today is __hotter__ (hot) than yesterday.\nMichael: No. Let’s go kayaking. It’s __more exciting__ (exciting) than swimming.\nJake: OK. Let’s get a kayak for two. Two people are __faster__ (fast) than one person.\nMichael: OK. And my arms are __longer__ (long) than your arms so I can help you.\nJake: What? That’s not true! My arms aren’t __shorter__ (short) than yours!\nMichael: Yes, they are. And I’m a __better__ (good) swimmer than you.\nJake: No, you aren’t. You are a __worse__ (bad) swimmer."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 16),
('<lesson_id>', 'task', replace($blk${"title": "Сравни мальчиков", "needs_review": true, "html": "<p>Задания становятся всё сложнее! Посмотри на картинку и сравни мальчиков. Составь четыре предложения.</p><p><img src=\"@@MEDIA@@gg2/u4/book_five_boys.webp\" alt=\"\" style=\"max-width:100%;max-height:300px;border-radius:12px\"></p><p><i>Пример: Tom is shorter than John.</i></p><p>Можешь использовать слова: young, old, happy, sad, tall, short, big (не забудь поставить их в правильную форму).</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 17),
('<lesson_id>', 'gaps', replace($blk${"title": "Какое слово пропущено? Подсказка — первая буква уже дана 😄", "mode": "type", "text": "1. The water in this bottle is c__older__ than the Arctic!\n2. Sailing is m__ore__ dangerous than cycling.\n3. I’m shorter t__han__ my brother.\n4. This bad painting is w__orse__ than that good painting.\n5. I can’t do my homework. It’s more d__ifficult__ than the lesson.\n6. He’s a better runner t__han__ you."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 18),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Необязательное задание. Помоги лягушке добраться до берега: выбери слово, которое подходит картинке 🐸", "type": "single", "options": [{"text": "safe"}, {"text": "dangerous"}, {"text": "boring"}], "correct": [1], "image": "@@MEDIA@@gg2/u4/dangerous.webp"}, {"q": "Какое слово подходит картинке?", "type": "single", "options": [{"text": "expensive"}, {"text": "cheap"}], "correct": [0], "image": "@@MEDIA@@gg2/u4/expensive.webp"}, {"q": "Какое слово подходит картинке?", "type": "single", "options": [{"text": "difficult"}, {"text": "easy"}, {"text": "low"}], "correct": [1], "image": "@@MEDIA@@gg2/u4/easy.webp"}, {"q": "Какое слово подходит картинке?", "type": "single", "options": [{"text": "low"}, {"text": "high"}], "correct": [1], "image": "@@MEDIA@@gg2/u4/high.webp"}, {"q": "Какое слово подходит картинке?", "type": "single", "options": [{"text": "boring"}, {"text": "exciting"}, {"text": "safe"}], "correct": [1], "image": "@@MEDIA@@gg2/u4/exciting.webp"}, {"q": "Какое слово подходит картинке?", "type": "single", "options": [{"text": "cheap"}, {"text": "difficult"}], "correct": [1], "image": "@@MEDIA@@gg2/u4/difficult.webp"}, {"q": "Какое слово подходит картинке?", "type": "single", "options": [{"text": "safe"}, {"text": "dangerous"}], "correct": [0], "image": "@@MEDIA@@gg2/u4/safe.webp"}, {"q": "Какое слово подходит картинке?", "type": "single", "options": [{"text": "high"}, {"text": "expensive"}, {"text": "low"}], "correct": [2], "image": "@@MEDIA@@gg2/u4/low.webp"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 19),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_trophy.webp\" alt=\"\" style=\"height:180px\"></p><h3>Ура! Домашняя работа выполнена.</h3><p>Наверное, пора отдохнуть :) Увидимся на занятии 😃</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 20)
returning sort_order, type;
