-- Go Getter 2 · Unit 6 · Unit 6 Test
-- собрано tools/gg2_build.py --lesson u6_test
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 6', 6 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 6');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Unit 6 Test', 'test', 90, false, 6
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 6'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Unit 6 Test');
update classroom_lessons l set kind = 'test', pass_threshold = 90, sort_order = 6
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 6' and l.title = 'Unit 6 Test';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 6' and l.title = 'Unit 6 Test';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'exact_input', replace($blk${"title": "Напиши слово по-английски", "items": [{"prompt": "Напиши по-английски: строитель", "accept": ["builder", "Builder"], "audio_tts": "builder"}, {"prompt": "Напиши по-английски: медсестра", "accept": ["nurse", "Nurse"], "audio_tts": "nurse"}, {"prompt": "Напиши по-английски: пилот", "accept": ["pilot", "Pilot"], "audio_tts": "pilot"}, {"prompt": "Напиши по-английски: полицейский", "accept": ["police officer", "Police officer"], "audio_tts": "police officer"}, {"prompt": "Напиши по-английски: продавец", "accept": ["shop assistant", "Shop assistant"], "audio_tts": "shop assistant"}, {"prompt": "Напиши по-английски: учитель", "accept": ["teacher", "Teacher"], "audio_tts": "teacher"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'quiz', replace($blk${"title": "Выбери правильный вариант, чтобы предложение было грамматически верным", "questions": [{"q": "Yesterday my dad ___ the car after work.", "type": "single", "options": [{"text": "washd"}, {"text": "washed"}, {"text": "washes"}], "correct": [1]}, {"q": "We ___ to a new restaurant last Saturday.", "type": "single", "options": [{"text": "went"}, {"text": "goed"}, {"text": "wented"}], "correct": [0]}, {"q": "My sister ___ her room two hours ago.", "type": "single", "options": [{"text": "tidyed"}, {"text": "tidy"}, {"text": "tidied"}], "correct": [2]}, {"q": "I ___ a new dictionary for school last week.", "type": "single", "options": [{"text": "buyed"}, {"text": "bought"}, {"text": "boughted"}], "correct": [1]}, {"q": "The doctor ___ me some medicine this morning.", "type": "single", "options": [{"text": "gived"}, {"text": "give"}, {"text": "gave"}], "correct": [2]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'gaps', replace($blk${"title": "Поставь глагол в скобках в правильную форму Past Simple", "mode": "type", "text": "1. Last summer my family __stayed__ (stay) in a small hotel in Italy.\n2. The chef __made__ (make) an amazing pizza for dinner.\n3. I __stopped__ (stop) playing computer games at ten o'clock.\n4. We __had__ (have) a Maths test on Monday.\n5. My brother __took__ (take) the dog for a walk an hour ago."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'order', replace($blk${"words": ["My", "mum", "cooked", "dinner", "for", "us", "yesterday."], "sentence": "My mum cooked dinner for us yesterday.", "audio_tts": "My mum cooked dinner for us yesterday."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'order', replace($blk${"words": ["We", "didn't", "go", "to", "school", "last", "Friday."], "sentence": "We didn't go to school last Friday.", "audio_tts": "We didn't go to school last Friday."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'order', replace($blk${"words": ["First,", "I", "made", "my", "bed,", "then", "I", "tidied", "my", "room."], "sentence": "First, I made my bed, then I tidied my room.", "audio_tts": "First, I made my bed, then I tidied my room."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["The", "police officer", "helped", "a", "lost", "tourist", "two", "days", "ago."], "sentence": "The police officer helped a lost tourist two days ago.", "audio_tts": "The police officer helped a lost tourist two days ago."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["My", "dad", "drank", "a", "cup", "of", "coffee", "and", "went", "to", "work."], "sentence": "My dad drank a cup of coffee and went to work.", "audio_tts": "My dad drank a cup of coffee and went to work."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'text', replace($blk${"html": "<h3>READING</h3><p>Прочитай текст и ответь на вопросы ниже.</p><h4>A Day in My Mum's Life</h4><p>My mum is a vet. She loves her job, but it's never easy. Yesterday was a really busy day for her, so I want to tell you about it.</p><p>First, she got up at six o'clock and made breakfast for me and my brother. Then she walked the dog and went to work. She arrived at the animal hospital at half past seven.</p><p>In the morning, a man came in with his old cat. The cat was very ill, and Mum felt sad. But she gave the cat some medicine and the cat got better!</p><p>After lunch, a little girl brought a small bird with a broken wing. Mum helped the bird for two hours.</p><p>She came home at eight o'clock. She was tired, but she said, \"I love my job.\" Then she took the dog for another walk!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'quiz', replace($blk${"title": "READING. Выбери правильный ответ на каждый вопрос", "questions": [{"q": "What's the writer's mum's job?", "type": "single", "options": [{"text": "doctor"}, {"text": "nurse"}, {"text": "vet"}, {"text": "farmer"}], "correct": [2]}, {"q": "What did Mum do first yesterday?", "type": "single", "options": [{"text": "walked the dog"}, {"text": "made breakfast"}, {"text": "went to work"}, {"text": "tidied the kitchen"}], "correct": [1]}, {"q": "Where does the writer's mum work?", "type": "single", "options": [{"text": "in a hospital for people"}, {"text": "in an animal hospital"}, {"text": "at home"}, {"text": "in a school"}], "correct": [1]}, {"q": "Why was Mum sad in the morning?", "type": "single", "options": [{"text": "The man wasn't friendly."}, {"text": "The cat was very ill."}, {"text": "She was tired."}, {"text": "The cat didn't like her."}], "correct": [1]}, {"q": "How long did Mum help the little bird?", "type": "single", "options": [{"text": "half an hour"}, {"text": "one hour"}, {"text": "two hours"}, {"text": "all afternoon"}], "correct": [2]}, {"q": "After work, Mum…", "type": "single", "options": [{"text": "was happy and energetic"}, {"text": "was tired but happy with her job"}, {"text": "didn't want to do anything"}, {"text": "was angry"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'video', replace($blk${"title": "LISTENING. Послушай, как четыре человека рассказывают о том, что они делали вчера 🎧", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'sort', replace($blk${"title": "LISTENING. Соедини каждого человека с двумя фактами о том, что он делал", "groups": [{"name": "Speaker 1", "items": [{"text": "is a builder"}, {"text": "watched TV after work"}]}, {"name": "Speaker 2", "items": [{"text": "bought food at the supermarket"}, {"text": "read a book in the evening"}]}, {"name": "Speaker 3", "items": [{"text": "made food for fifty people"}, {"text": "ordered a sandwich for dinner"}]}, {"name": "Speaker 4", "items": [{"text": "walked the dog in the evening"}, {"text": "is a nurse"}]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING I 🎤", "needs_review": true, "image": "@@MEDIA@@gg2/u6/scene_cleaning.webp", "html": "<p>Опиши картинку и ответь на вопросы. Запиши ответ, нажав на кнопку микрофона.</p><ol><li>How many people are there in the picture?</li><li>Where are they?</li><li>What is each person doing?</li><li>Are the children helping their parents?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING II 🎤", "needs_review": true, "html": "<p>Ответь на вопросы. Запиши ответ, нажав на кнопку микрофона.</p><ol><li>What do you want to be in the future: a doctor, a teacher, an artist or something else?</li><li>What's the most interesting job in your opinion?</li><li>Is being a chef difficult?</li><li>Where does a vet work?</li><li>Where did you go last weekend?</li><li>What time did you get up today?</li><li>Did you tidy your room yesterday?</li><li>Did you walk the dog this week?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13)
returning sort_order, type;
