-- Go Getter 2 · Unit 1 · Homework 1
-- собрано tools/gg2_build.py --lesson u1_hw1
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 1', 1 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 1');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 1', 'homework', 60, false, 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 1'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 1');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 1' and l.title = 'Homework 1';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 1' and l.title = 'Homework 1';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет! 👋</h2><p>Сейчас мы с тобой выучим школьные предметы. Выполни все задания, чтобы выучить слова на 100%!</p><p>Также не забудь выучить школьные принадлежности и потренировать выученные слова на практике. У тебя всё получится! ❤️</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'flashcards', replace($blk${"cards": [{"text": "Art", "translation": "изобразительное искусство", "image": "@@MEDIA@@gg2/u1/subj_art.webp", "audio_tts": "Art"}, {"text": "Computer Studies", "translation": "информатика", "image": "@@MEDIA@@gg2/u1/subj_computer.webp", "audio_tts": "Computer Studies"}, {"text": "English", "translation": "английский", "image": "@@MEDIA@@gg2/u1/subj_english.webp", "audio_tts": "English"}, {"text": "French", "translation": "французский", "image": "@@MEDIA@@gg2/u1/subj_french.webp", "audio_tts": "French"}, {"text": "Geography", "translation": "география", "image": "@@MEDIA@@gg2/u1/subj_geography.webp", "audio_tts": "Geography"}, {"text": "History", "translation": "история", "image": "@@MEDIA@@gg2/u1/subj_history.webp", "audio_tts": "History"}, {"text": "Maths", "translation": "математика", "image": "@@MEDIA@@gg2/u1/subj_maths.webp", "audio_tts": "Maths"}, {"text": "Music", "translation": "музыка", "image": "@@MEDIA@@gg2/u1/subj_music.webp", "audio_tts": "Music"}, {"text": "P.E.", "translation": "физическое воспитание (физкультура)", "image": "@@MEDIA@@gg2/u1/subj_pe.webp", "audio_tts": "P.E."}, {"text": "Science", "translation": "естественные науки", "image": "@@MEDIA@@gg2/u1/subj_science.webp", "audio_tts": "Science"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'match', replace($blk${"title": "Соедини картинку с названием предмета", "pairs": [{"left_image": "@@MEDIA@@gg2/u1/subj_art.webp", "right": "Art", "right_audio_tts": "Art"}, {"left_image": "@@MEDIA@@gg2/u1/subj_computer.webp", "right": "Computer Studies", "right_audio_tts": "Computer Studies"}, {"left_image": "@@MEDIA@@gg2/u1/subj_english.webp", "right": "English", "right_audio_tts": "English"}, {"left_image": "@@MEDIA@@gg2/u1/subj_french.webp", "right": "French", "right_audio_tts": "French"}, {"left_image": "@@MEDIA@@gg2/u1/subj_geography.webp", "right": "Geography", "right_audio_tts": "Geography"}, {"left_image": "@@MEDIA@@gg2/u1/subj_history.webp", "right": "History", "right_audio_tts": "History"}, {"left_image": "@@MEDIA@@gg2/u1/subj_maths.webp", "right": "Maths", "right_audio_tts": "Maths"}, {"left_image": "@@MEDIA@@gg2/u1/subj_music.webp", "right": "Music", "right_audio_tts": "Music"}, {"left_image": "@@MEDIA@@gg2/u1/subj_pe.webp", "right": "P.E.", "right_audio_tts": "P.E."}, {"left_image": "@@MEDIA@@gg2/u1/subj_science.webp", "right": "Science", "right_audio_tts": "Science"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'quiz', replace($blk${"title": "Выбери правильный перевод", "questions": [{"q": "Как по-английски «изобразительное искусство»?", "type": "single", "options": [{"text": "Art"}, {"text": "French"}, {"text": "Maths"}, {"text": "Science"}], "correct": [0]}, {"q": "Как по-английски «информатика»?", "type": "single", "options": [{"text": "Art"}, {"text": "Computer Studies"}, {"text": "Geography"}, {"text": "Music"}], "correct": [1]}, {"q": "Как по-английски «английский»?", "type": "single", "options": [{"text": "Computer Studies"}, {"text": "English"}, {"text": "History"}, {"text": "P.E."}], "correct": [1]}, {"q": "Как по-английски «французский»?", "type": "single", "options": [{"text": "English"}, {"text": "French"}, {"text": "Maths"}, {"text": "Science"}], "correct": [1]}, {"q": "Как по-английски «география»?", "type": "single", "options": [{"text": "Art"}, {"text": "French"}, {"text": "Geography"}, {"text": "Music"}], "correct": [2]}, {"q": "Как по-английски «история»?", "type": "single", "options": [{"text": "Computer Studies"}, {"text": "Geography"}, {"text": "History"}, {"text": "P.E."}], "correct": [2]}, {"q": "Как по-английски «математика»?", "type": "single", "options": [{"text": "English"}, {"text": "History"}, {"text": "Maths"}, {"text": "Science"}], "correct": [2]}, {"q": "Как по-английски «музыка»?", "type": "single", "options": [{"text": "Art"}, {"text": "French"}, {"text": "Maths"}, {"text": "Music"}], "correct": [3]}, {"q": "Как по-английски «физическое воспитание (физкультура)»?", "type": "single", "options": [{"text": "Computer Studies"}, {"text": "Geography"}, {"text": "Music"}, {"text": "P.E."}], "correct": [3]}, {"q": "Как по-английски «естественные науки»?", "type": "single", "options": [{"text": "English"}, {"text": "History"}, {"text": "P.E."}, {"text": "Science"}], "correct": [3]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_book.webp\" alt=\"\" style=\"height:200px\"></p><h3>Школьные принадлежности 🎒</h3><p>А теперь выучим школьные принадлежности. Посмотри карточки, послушай слова и выполни задания. Удачи! ❤️</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'flashcards', replace($blk${"cards": [{"text": "calculator", "translation": "калькулятор", "image": "@@MEDIA@@gg2/u1/calculator.webp", "audio_tts": "calculator"}, {"text": "dictionary", "translation": "словарь", "image": "@@MEDIA@@gg2/u1/dictionary.webp", "audio_tts": "dictionary"}, {"text": "laptop", "translation": "ноутбук", "image": "@@MEDIA@@gg2/u1/laptop.webp", "audio_tts": "laptop"}, {"text": "map", "translation": "карта", "image": "@@MEDIA@@gg2/u1/map.webp", "audio_tts": "map"}, {"text": "paints", "translation": "краски", "image": "@@MEDIA@@gg2/u1/paints.webp", "audio_tts": "paints"}, {"text": "pencil case", "translation": "пенал", "image": "@@MEDIA@@gg2/u1/pencil_case.webp", "audio_tts": "pencil case"}, {"text": "rubber", "translation": "ластик", "image": "@@MEDIA@@gg2/u1/rubber.webp", "audio_tts": "rubber"}, {"text": "ruler", "translation": "линейка", "image": "@@MEDIA@@gg2/u1/ruler.webp", "audio_tts": "ruler"}, {"text": "scissors", "translation": "ножницы", "image": "@@MEDIA@@gg2/u1/scissors.webp", "audio_tts": "scissors"}, {"text": "trainers", "translation": "кроссовки", "image": "@@MEDIA@@gg2/u1/trainers.webp", "audio_tts": "trainers"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'match', replace($blk${"title": "Соедини картинку со словом", "pairs": [{"left_image": "@@MEDIA@@gg2/u1/calculator.webp", "right": "calculator", "right_audio_tts": "calculator"}, {"left_image": "@@MEDIA@@gg2/u1/dictionary.webp", "right": "dictionary", "right_audio_tts": "dictionary"}, {"left_image": "@@MEDIA@@gg2/u1/laptop.webp", "right": "laptop", "right_audio_tts": "laptop"}, {"left_image": "@@MEDIA@@gg2/u1/map.webp", "right": "map", "right_audio_tts": "map"}, {"left_image": "@@MEDIA@@gg2/u1/paints.webp", "right": "paints", "right_audio_tts": "paints"}, {"left_image": "@@MEDIA@@gg2/u1/pencil_case.webp", "right": "pencil case", "right_audio_tts": "pencil case"}, {"left_image": "@@MEDIA@@gg2/u1/rubber.webp", "right": "rubber", "right_audio_tts": "rubber"}, {"left_image": "@@MEDIA@@gg2/u1/ruler.webp", "right": "ruler", "right_audio_tts": "ruler"}, {"left_image": "@@MEDIA@@gg2/u1/scissors.webp", "right": "scissors", "right_audio_tts": "scissors"}, {"left_image": "@@MEDIA@@gg2/u1/trainers.webp", "right": "trainers", "right_audio_tts": "trainers"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'exact_input', replace($blk${"title": "Напиши слово по-английски", "items": [{"prompt": "Напиши по-английски: калькулятор", "image": "@@MEDIA@@gg2/u1/calculator.webp", "accept": ["calculator", "Calculator"], "audio_tts": "calculator"}, {"prompt": "Напиши по-английски: словарь", "image": "@@MEDIA@@gg2/u1/dictionary.webp", "accept": ["dictionary", "Dictionary"], "audio_tts": "dictionary"}, {"prompt": "Напиши по-английски: ноутбук", "image": "@@MEDIA@@gg2/u1/laptop.webp", "accept": ["laptop", "Laptop"], "audio_tts": "laptop"}, {"prompt": "Напиши по-английски: карта", "image": "@@MEDIA@@gg2/u1/map.webp", "accept": ["map", "Map"], "audio_tts": "map"}, {"prompt": "Напиши по-английски: краски", "image": "@@MEDIA@@gg2/u1/paints.webp", "accept": ["paints", "Paints"], "audio_tts": "paints"}, {"prompt": "Напиши по-английски: пенал", "image": "@@MEDIA@@gg2/u1/pencil_case.webp", "accept": ["pencil case", "Pencil case"], "audio_tts": "pencil case"}, {"prompt": "Напиши по-английски: ластик", "image": "@@MEDIA@@gg2/u1/rubber.webp", "accept": ["rubber", "Rubber"], "audio_tts": "rubber"}, {"prompt": "Напиши по-английски: линейка", "image": "@@MEDIA@@gg2/u1/ruler.webp", "accept": ["ruler", "Ruler"], "audio_tts": "ruler"}, {"prompt": "Напиши по-английски: ножницы", "image": "@@MEDIA@@gg2/u1/scissors.webp", "accept": ["scissors", "Scissors"], "audio_tts": "scissors"}, {"prompt": "Напиши по-английски: кроссовки", "image": "@@MEDIA@@gg2/u1/trainers.webp", "accept": ["trainers", "Trainers"], "audio_tts": "trainers"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_rocket.webp\" alt=\"\" style=\"height:200px\"></p><h3>Дополнительная часть 🚀</h3><p>Добро пожаловать в ДОПОЛНИТЕЛЬНУЮ часть домашнего задания! Выполни все задания, чтобы хорошенько запомнить новые слова. Выполнив их, ты станешь МЕГА крутым учеником!</p><p>Твоё первое задание — вставить названия школьных предметов в пропуски. Удачи!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'gaps', replace($blk${"title": "Перетащи названия предметов в пропуски", "mode": "drag", "text": "1. I paint pictures of flowers in __Art__.\n2. We learn to say Bonjour in __French__.\n3. I learn about different countries in __Geography__.\n4. In __Maths__ we can use a calculator for problems.\n5. We do cool experiments in __Science__.\n6. In __Music__ we sing lots of songs.\n7. This book about the past is for __History__.\n8. Today's grammar lesson for __English__ is “I can”."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Молодец! 👍</h3><p>А теперь прочитай, что рассказывает Karen, и отметь её любимые школьные предметы.</p><blockquote><p>My name is Karen. I'm 11 years old. My favourite subjects are P.E. and Computer Studies. I have P.E. on Monday and Wednesday and Computer Studies on Friday.</p></blockquote>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'quiz', replace($blk${"title": "Отметь любимые предметы Karen", "questions": [{"q": "What are Karen's favourite subjects? Выбери ДВА варианта.", "type": "multiple", "options": [{"text": "Art"}, {"text": "Maths"}, {"text": "P.E."}, {"text": "Science"}, {"text": "History"}, {"text": "Computer Studies"}], "correct": [2, 5]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'task', replace($blk${"title": "Дополнительное задание ⭐", "needs_review": true, "html": "<p>А это ДОПОЛНИТЕЛЬНОЕ ЗАДАНИЕ — для самых смелых! Прочитай ещё раз текст о Karen и письменно перечисли свои любимые школьные предметы.</p><p><i>Например: My favourite subjects are English and Art.</i></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/congrats_popper.webp\" alt=\"\" style=\"height:200px\"></p><h3>Поздравляю! 🎉</h3><p>Ты завершил домашнее задание. Ты — МЕГА КРУТ! Жду тебя на уроке!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13)
returning sort_order, type;
