-- Go Getter 2 · Unit 7 · Travel · Unit 7 Test
-- собрано tools/gg2_build.py --lesson u7_test
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 7 · Travel', 7 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 7 · Travel');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Unit 7 Test', 'test', 90, false, 6
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 7 · Travel'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Unit 7 Test');
update classroom_lessons l set kind = 'test', pass_threshold = 90, sort_order = 6
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 7 · Travel' and l.title = 'Unit 7 Test';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 7 · Travel' and l.title = 'Unit 7 Test';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'exact_input', replace($blk${"title": "VOCABULARY. Напиши слова по-английски", "items": [{"prompt": "Напиши по-английски: прибыть", "accept": ["arrive"], "audio_tts": "arrive"}, {"prompt": "Напиши по-английски: лодка", "accept": ["boat", "a boat"], "audio_tts": "boat"}, {"prompt": "Напиши по-английски: мотоцикл", "accept": ["motorbike", "a motorbike"], "audio_tts": "motorbike"}, {"prompt": "Напиши по-английски: самолёт", "accept": ["plane", "a plane"], "audio_tts": "plane"}, {"prompt": "Напиши по-английски: поезд", "accept": ["train", "a train"], "audio_tts": "train"}, {"prompt": "Напиши по-английски: метро", "accept": ["underground", "the underground"], "audio_tts": "underground"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "We ___ the bus yesterday — we walked.", "type": "single", "options": [{"text": "didn't took"}, {"text": "didn't take"}, {"text": "wasn't take"}], "correct": [1]}, {"q": "___ the museum last weekend?", "type": "single", "options": [{"text": "Did you visit"}, {"text": "Did you visited"}, {"text": "Were you visit"}], "correct": [0]}, {"q": "My parents ___ in a hotel — they stayed with friends.", "type": "single", "options": [{"text": "weren't stay"}, {"text": "didn't stayed"}, {"text": "didn't stay"}], "correct": [2]}, {"q": "Where ___ on holiday last summer?", "type": "single", "options": [{"text": "Tom did go"}, {"text": "did Tom go"}, {"text": "did Tom went"}], "correct": [1]}, {"q": "— ___ you buy any souvenirs? — Yes, I did.", "type": "single", "options": [{"text": "Were"}, {"text": "Do"}, {"text": "Did"}], "correct": [2]}, {"q": "— Did you ___ any souvenirs? — Yes, I did.", "type": "single", "options": [{"text": "buy"}, {"text": "buyed"}, {"text": "bought"}], "correct": [0]}], "title": "GRAMMAR. Выбери вариант, чтобы предложение было грамматически верным"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'gaps', replace($blk${"title": "Поставь глагол в скобках в правильную форму", "mode": "type", "text": "1) We __didn't go|did not go__ (not go) sightseeing because the weather was bad.\n2) __Did|did__ you __eat__ (eat) at a Spanish restaurant in Madrid?\n3) My sister __didn't make|did not make__ (not make) any new friends on the trip.\n4) Where __did__ they __stay__ (stay) in Paris?\n5) I __didn't take|did not take__ (not take) my camera, so I haven't got any photos."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'order', replace($blk${"words": ["Why", "did", "you", "take", "a taxi", "to", "the airport?"], "sentence": "Why did you take a taxi to the airport?", "audio_tts": "Why did you take a taxi to the airport?", "title": "Расставь части предложения в правильном порядке"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'order', replace($blk${"words": ["We", "didn't", "get off", "the bus", "at", "the right stop."], "sentence": "We didn't get off the bus at the right stop.", "audio_tts": "We didn't get off the bus at the right stop."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'order', replace($blk${"words": ["Did", "your family", "go", "to", "the beach", "last summer?"], "sentence": "Did your family go to the beach last summer?", "audio_tts": "Did your family go to the beach last summer?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["When", "did", "the train", "arrive", "in", "London?"], "sentence": "When did the train arrive in London?", "audio_tts": "When did the train arrive in London?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["I", "didn't", "pack", "my sleeping bag,", "so", "I", "was cold."], "sentence": "I didn't pack my sleeping bag, so I was cold.", "audio_tts": "I didn't pack my sleeping bag, so I was cold."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'text', replace($blk${"html": "<h3>READING. My Trip to Rome 🇮🇹</h3><p>Прочитай рассказ Эммы о её поездке в Рим.</p><p>Last April, my family and I went to Rome for a week. It was an amazing trip! We flew from London to Rome on Sunday morning. The plane was very fast – only two and a half hours. From the airport, we took a taxi to our hotel because there was a lot of luggage.</p><p>On Monday, we visited the Colosseum. It was incredible, but very busy with tourists. My dad took hundreds of photos. After that, we ate pizza at a small restaurant near the hotel – the best pizza I've ever had!</p><p>On Wednesday, we went sightseeing all day and made friends with an American family. Their daughter Lily was twelve, like me. We chat online now. On our last day, I bought a small souvenir – a tiny model of the Colosseum. I didn't want to leave Rome!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'match', replace($blk${"title": "Соедини вопросы с правильными ответами", "pairs": [{"left": "How long did Emma's family stay in Rome?", "right": "for one week", "right_audio_tts": "for one week"}, {"left": "How did they travel from London to Rome?", "right": "by plane", "right_audio_tts": "by plane"}, {"left": "Why did they take a taxi to the hotel?", "right": "because they had a lot of luggage", "right_audio_tts": "because they had a lot of luggage"}, {"left": "What did they do on Monday?", "right": "They visited the Colosseum.", "right_audio_tts": "They visited the Colosseum."}, {"left": "What did Emma's dad do at the Colosseum?", "right": "He took hundreds of photos.", "right_audio_tts": "He took hundreds of photos."}, {"left": "Where did they have pizza?", "right": "at a small restaurant near the hotel", "right_audio_tts": "at a small restaurant near the hotel"}, {"left": "How did Emma feel at the end of the trip?", "right": "She didn't want to leave.", "right_audio_tts": "She didn't want to leave."}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'video', replace($blk${"title": "LISTENING. Послушай разговор в кассе на железнодорожной станции 🎧", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Where is the customer going?", "type": "single", "options": [{"text": "London"}, {"text": "Edinburgh"}, {"text": "Glasgow"}, {"text": "Manchester"}], "correct": [1]}, {"q": "What kind of ticket does she want?", "type": "single", "options": [{"text": "single"}, {"text": "return"}, {"text": "family"}, {"text": "student"}], "correct": [1]}, {"q": "When is the customer coming back?", "type": "single", "options": [{"text": "Saturday morning"}, {"text": "Saturday evening"}, {"text": "Sunday evening"}, {"text": "Monday morning"}], "correct": [2]}, {"q": "What time does the next train leave?", "type": "single", "options": [{"text": "11:00"}, {"text": "11:15"}, {"text": "11:30"}, {"text": "11:45"}], "correct": [2]}, {"q": "How much is the ticket?", "type": "single", "options": [{"text": "£55"}, {"text": "£75"}, {"text": "£85"}, {"text": "£95"}], "correct": [2]}, {"q": "Which platform does the train leave from?", "type": "single", "options": [{"text": "platform 4"}, {"text": "platform 5"}, {"text": "platform 6"}, {"text": "platform 16"}], "correct": [2]}], "title": "Послушай аудио и выбери правильный ответ на каждый вопрос"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING I 🎤", "html": "<p>Опиши картинку и ответь на вопросы. Запиши ответ, нажав на кнопку микрофона.</p><ol><li>Where are the people?</li><li>How many people are there?</li><li>What are they wearing?</li><li>What can you see?</li><li>Are they going to travel by plane or by train?</li></ol>", "needs_review": true, "image": "@@MEDIA@@gg2/u7/scene_airport.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING II 🎤", "html": "<p>Ответь на вопросы полными предложениями. Запиши ответ, нажав на кнопку микрофона.</p><ol><li>Did you go on holiday last summer? Where did you go?</li><li>How did you travel — by car, by train, by plane or by bus?</li><li>What did you take with you in your suitcase?</li><li>Did you take a lot of photos?</li><li>Did you visit any museums?</li><li>Did you buy any souvenirs? What did you buy?</li><li>What was the best thing about the trip?</li></ol>", "needs_review": true}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13)
returning sort_order, type;
