-- Go Getter 2 · Unit 5 · Unit 5 Test
-- собрано tools/gg2_build.py --lesson u5_test
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 5', 5 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 5');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Unit 5 Test', 'test', 90, false, 6
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 5'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Unit 5 Test');
update classroom_lessons l set kind = 'test', pass_threshold = 90, sort_order = 6
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 5' and l.title = 'Unit 5 Test';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 5' and l.title = 'Unit 5 Test';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'exact_input', replace($blk${"items": [{"image": "@@MEDIA@@gg2/u5/cinema.webp", "prompt": "Напиши по-английски: кинотеатр", "accept": ["cinema"], "audio_tts": "cinema"}, {"image": "@@MEDIA@@gg2/u5/library.webp", "prompt": "Напиши по-английски: библиотека", "accept": ["library"], "audio_tts": "library"}, {"image": "@@MEDIA@@gg2/u5/museum.webp", "prompt": "Напиши по-английски: музей", "accept": ["museum"], "audio_tts": "museum"}, {"image": "@@MEDIA@@gg2/u5/restaurant.webp", "prompt": "Напиши по-английски: ресторан", "accept": ["restaurant"], "audio_tts": "restaurant"}, {"image": "@@MEDIA@@gg2/u5/stadium.webp", "prompt": "Напиши по-английски: стадион", "accept": ["stadium"], "audio_tts": "stadium"}, {"image": "@@MEDIA@@gg2/u5/theatre.webp", "prompt": "Напиши по-английски: театр", "accept": ["theatre", "theater"], "audio_tts": "theatre"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'quiz', replace($blk${"title": "Выбери правильный вариант, чтобы предложение было грамматически верным", "questions": [{"q": "Yesterday I ___ at the swimming pool with my friends.", "type": "single", "options": [{"text": "were"}, {"text": "was"}, {"text": "am"}], "correct": [1]}, {"q": "My parents ___ at home last weekend.", "type": "single", "options": [{"text": "weren't"}, {"text": "wasn't"}, {"text": "didn't"}], "correct": [0]}, {"q": "___ you at the cinema last night?", "type": "single", "options": [{"text": "Was"}, {"text": "Did"}, {"text": "Were"}], "correct": [2]}, {"q": "The shopping centre ___ very busy on Saturday.", "type": "single", "options": [{"text": "is"}, {"text": "were"}, {"text": "was"}], "correct": [2]}, {"q": "___ you two days ago?", "type": "single", "options": [{"text": "Where was"}, {"text": "Where were"}, {"text": "Where you were"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'gaps', replace($blk${"title": "Впиши was, wasn't, were или weren't", "mode": "type", "text": "1. The museum __was__ closed on Monday, so we went to the park.\n2. We __weren't|weren’t__ at school last Tuesday because it was a holiday.\n3. — __Was__ the restaurant good? — Yes, it was amazing!\n4. My grandparents __were__ young in 1970.\n5. There __wasn't|wasn’t__ a sports centre in our town 1000 years ago."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'order', replace($blk${"words": ["There", "was", "a", "small", "café", "opposite", "the", "library."], "sentence": "There was a small café opposite the library.", "audio_tts": "There was a small café opposite the library."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'order', replace($blk${"words": ["My", "brother", "wasn't", "at", "the", "stadium", "yesterday."], "sentence": "My brother wasn't at the stadium yesterday.", "audio_tts": "My brother wasn't at the stadium yesterday."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'order', replace($blk${"words": ["Where", "were", "you", "last", "Saturday", "evening?"], "sentence": "Where were you last Saturday evening?", "audio_tts": "Where were you last Saturday evening?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["The", "hotel", "was", "between", "the", "bank", "and", "the", "post office."], "sentence": "The hotel was between the bank and the post office.", "audio_tts": "The hotel was between the bank and the post office."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["Were", "your", "friends", "at", "the", "shopping centre", "last", "week?"], "sentence": "Were your friends at the shopping centre last week?", "audio_tts": "Were your friends at the shopping centre last week?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'text', replace($blk${"html": "<h3>READING · My Grandfather's Town</h3><p>My name's Olivia and I love my town, Brighton. But my grandfather always says it was very different sixty years ago. Last Sunday we went for a walk and he told me about old Brighton.</p><p>\"In 1965 there wasn't a shopping centre here,\" he said. \"Now there are lots of modern shops, but then there was just a small market on Saturdays. And the cinema was much smaller — there was only one screen!\"</p><p>We walked past the train station. \"When I was a teenager, the station was old and dirty,\" he said. \"Now it's modern and clean — that's much better!\"</p><p>Then we went to the park. \"This park was always my favourite place. My friends and I were here every weekend. There weren't any phones or computers, so we played football and rode our bikes for hours!\"</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'quiz', replace($blk${"title": "Прочитай текст выше. Выбери True (верно), False (неверно) или Not stated (в тексте не сказано)", "questions": [{"q": "Olivia is from Brighton.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [0]}, {"q": "Olivia's grandfather thinks the town is the same as before.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [1]}, {"q": "There was a big shopping centre in Brighton in 1965.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [1]}, {"q": "The old cinema had only one screen.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [0]}, {"q": "Olivia's grandfather worked at the train station.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [2]}, {"q": "He thinks the train station is better now.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [0]}, {"q": "Children played outside more in the past.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [0]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'sequence', replace($blk${"title": "Послушай, как Лиам объясняет туристу дорогу до его отеля. Расставь места в том порядке, в котором турист пройдёт мимо них", "audio": "", "items": [{"text": "the supermarket"}, {"text": "the post office"}, {"text": "the park"}, {"text": "the museum"}, {"text": "the café"}, {"text": "the Royal Hotel"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING I 🎤", "needs_review": true, "image": "@@MEDIA@@gg2/u5/scene_street.webp", "html": "<p>Опиши картинку и ответь на вопросы. Запиши ответ (до 5 минут), нажав на кнопку микрофона.</p><ol><li>What can you see in the picture?</li><li>Is this a big city or a small town?</li><li>Is the street clean or dirty?</li><li>Is the place busy or quiet?</li><li>Is it a modern or an old part of the city?</li><li>What buildings can you see?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING II 🎤", "needs_review": true, "html": "<p>Ответь на вопросы полными предложениями. Запиши ответ (до 5 минут), нажав на кнопку микрофона.</p><ol><li>Where do you live — in a big city, a small town or a village?</li><li>Is your town clean and quiet, or busy and dirty?</li><li>Is there a museum or a theatre in your town?</li><li>What's your favourite place?</li><li>Where's the nearest supermarket (opposite your house, behind the park, etc.)?</li><li>Is there a swimming pool or a sports centre near your home?</li><li>Where were you yesterday evening?</li><li>Where were you last Saturday at three o'clock?</li><li>Was the weather good or bad last weekend?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12)
returning sort_order, type;
