-- Go Getter 2 · Unit 7 · Homework 3
-- собрано tools/gg2_build.py --lesson u7_hw3
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 7', 7 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 7');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 3', 'homework', 60, false, 2
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 7'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 3');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 2
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 7' and l.title = 'Homework 3';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 7' and l.title = 'Homework 3';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Добро пожаловать! 👋</h2><p>В этом уроке тебя ждёт интересное видео и классные упражнения! В конце есть дополнительное задание — его можно выполнить по желанию, НО если выполнишь, будешь нереально крут!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'text', replace($blk${"html": "<p>Готов начать? Посмотри видео! Куда отправились Анна, Макс и Хэмми на этот раз?</p><p><img src=\"@@MEDIA@@gg2/u7/book_hammy_explorer.webp\" alt=\"\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'video', replace($blk${"title": "Посмотри видео: куда отправились Анна, Макс и Хэмми? 🧭", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'match', replace($blk${"title": "Посмотри видео ещё раз и соедини вопросы и ответы", "pairs": [{"left": "Did you have a good holiday?", "right": "Yes, I did.", "right_audio_tts": "Yes, I did."}, {"left": "Did you stay in the hotel?", "right": "No, I didn't.", "right_audio_tts": "No, I didn't."}, {"left": "Did the monkey take any photos?", "right": "Yes, it did.", "right_audio_tts": "Yes, it did."}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'text', replace($blk${"html": "<p>Отлично! А теперь настало время потрудиться: расставь слова в вопросах в правильном порядке.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'order', replace($blk${"words": ["Did", "they", "go", "on", "holiday", "last", "weekend?"], "sentence": "Did they go on holiday last weekend?", "audio_tts": "Did they go on holiday last weekend?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["Did", "the", "boy", "sleep", "in", "a", "tent?"], "sentence": "Did the boy sleep in a tent?", "audio_tts": "Did the boy sleep in a tent?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["Did", "your", "grandparents", "go", "shopping", "yesterday?"], "sentence": "Did your grandparents go shopping yesterday?", "audio_tts": "Did your grandparents go shopping yesterday?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'order', replace($blk${"words": ["Did", "your", "granny", "buy", "a", "new", "camera?"], "sentence": "Did your granny buy a new camera?", "audio_tts": "Did your granny buy a new camera?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Did Big Al go to Italy last week?", "type": "single", "options": [{"text": "Yes, he did."}, {"text": "No, he doesn't."}], "correct": [0]}, {"q": "Did he stay in the hotel?", "type": "single", "options": [{"text": "Yes, I do."}, {"text": "No, he didn't."}], "correct": [1]}, {"q": "Did Al and Sofia eat at a restaurant?", "type": "single", "options": [{"text": "No, she didn't."}, {"text": "Yes, they did."}], "correct": [1]}, {"q": "Did Al buy a T-shirt?", "type": "single", "options": [{"text": "Yes, he did."}, {"text": "No, she didn't."}], "correct": [0]}, {"q": "Did Al like Sofia?", "type": "single", "options": [{"text": "No, they didn't."}, {"text": "Yes, he did."}], "correct": [1]}], "title": "Ты хорошо справляешься! Прочитай вопросы про Big Al и выбери правильный ответ"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'text', replace($blk${"html": "<p>Смотри, сколько ты уже сделал! А теперь давай обсудим, что можно делать на каникулах :)</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Что здесь делают?", "type": "single", "options": [{"text": "take photos"}, {"text": "eat at a restaurant"}, {"text": "play computer games"}], "correct": [1], "image": "@@MEDIA@@gg2/u7/restaurant.webp"}, {"q": "Что здесь делают?", "type": "single", "options": [{"text": "take photos"}, {"text": "visit a museum"}, {"text": "make friends"}], "correct": [0], "image": "@@MEDIA@@gg2/u7/take_photos.webp"}, {"q": "Что здесь делают?", "type": "single", "options": [{"text": "stay in a hotel"}, {"text": "eat pizza"}, {"text": "visit a museum"}], "correct": [2], "image": "@@MEDIA@@gg2/u7/museum.webp"}, {"q": "Что здесь делают?", "type": "single", "options": [{"text": "buy a souvenir"}, {"text": "stay in a hotel"}, {"text": "go sightseeing"}], "correct": [1], "image": "@@MEDIA@@gg2/u7/hotel.webp"}, {"q": "Что здесь делают?", "type": "single", "options": [{"text": "play the piano"}, {"text": "go sightseeing"}, {"text": "buy a souvenir"}], "correct": [2], "image": "@@MEDIA@@gg2/u7/souvenir.webp"}], "title": "Посмотри на картинку и выбери правильный вариант"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'text', replace($blk${"html": "<p>Молодец! Запомнил выражения? А теперь соедини первую часть выражения со второй!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'match', replace($blk${"title": "Соедини части выражений", "pairs": [{"left": "buy", "right": "a souvenir", "right_audio_tts": "a souvenir"}, {"left": "visit", "right": "a museum", "right_audio_tts": "a museum"}, {"left": "make", "right": "friends", "right_audio_tts": "friends"}, {"left": "eat", "right": "at a restaurant", "right_audio_tts": "at a restaurant"}, {"left": "stay", "right": "in a hotel", "right_audio_tts": "in a hotel"}, {"left": "take", "right": "photos", "right_audio_tts": "photos"}, {"left": "go", "right": "sightseeing", "right_audio_tts": "sightseeing"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13),
('<lesson_id>', 'task', replace($blk${"title": "Мои каникулы ✍️", "html": "<p>Дополнительное задание для самых больших умников! Вспомни: куда ты ездил отдыхать в последний раз? Напиши небольшой текст о том, чем ты занимался в путешествии, и прочитай его на занятии.</p><p><i>Например: I went sightseeing with my family. We took a lot of photos …</i></p>", "needs_review": true}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 14),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_trophy.webp\" alt=\"\" style=\"height:200px\"></p><h2>Поздравляю! 🏆</h2><p>Ты завершил домашнее задание, ты замечательный ученик! Не забудь показать свой текст на занятии — и получишь дополнительную звёздочку от учителя! 🌟 Увидимся!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 15)
returning sort_order, type;
