-- Go Getter 2 · Unit 3 · Technology · Homework 1
-- собрано tools/gg2_build.py --lesson u3_hw1
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 3 · Technology', 3 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 3 · Technology');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 1', 'homework', 60, false, 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 3 · Technology'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 1');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 3 · Technology' and l.title = 'Homework 1';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 3 · Technology' and l.title = 'Homework 1';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_laptop.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет! 👋</h2><p>Сегодня мы с тобой выучим названия разных электронных устройств. Наверняка многими из них ты пользуешься каждый день :)</p><p>Сначала карточки, потом упражнения и небольшой тест в конце. Ты справишься 💪 Вперёд!</p><p>Во второй части домашнего задания ты найдёшь ещё много новых полезных слов. Не забудь туда заглянуть.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'flashcards', replace($blk${"title": "Гаджеты: посмотри, послушай и запомни", "cards": [{"text": "mobile phone", "translation": "мобильный телефон", "image": "@@MEDIA@@gg2/u3/mobile_phone.webp", "audio_tts": "mobile phone"}, {"text": "computer", "translation": "компьютер", "image": "@@MEDIA@@gg2/u3/computer.webp", "audio_tts": "computer"}, {"text": "laptop", "translation": "ноутбук", "image": "@@MEDIA@@gg2/u3/laptop.webp", "audio_tts": "laptop"}, {"text": "camera", "translation": "камера", "image": "@@MEDIA@@gg2/u3/camera.webp", "audio_tts": "camera"}, {"text": "tablet", "translation": "планшет", "image": "@@MEDIA@@gg2/u3/tablet.webp", "audio_tts": "tablet"}, {"text": "TV", "translation": "телевизор", "image": "@@MEDIA@@gg2/u3/tv.webp", "audio_tts": "TV"}, {"text": "headphones", "translation": "наушники", "image": "@@MEDIA@@gg2/u3/headphones.webp", "audio_tts": "headphones"}, {"text": "keyboard", "translation": "клавиатура", "image": "@@MEDIA@@gg2/u3/keyboard.webp", "audio_tts": "keyboard"}, {"text": "mouse", "translation": "мышь", "image": "@@MEDIA@@gg2/u3/mouse.webp", "audio_tts": "mouse"}, {"text": "printer", "translation": "принтер", "image": "@@MEDIA@@gg2/u3/printer.webp", "audio_tts": "printer"}, {"text": "screen", "translation": "экран", "image": "@@MEDIA@@gg2/u3/screen.webp", "audio_tts": "screen"}, {"text": "speakers", "translation": "колонки", "image": "@@MEDIA@@gg2/u3/speakers.webp", "audio_tts": "speakers"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'match', replace($blk${"title": "Соедини картинку со словом (1)", "pairs": [{"left_image": "@@MEDIA@@gg2/u3/mobile_phone.webp", "right": "mobile phone", "right_audio_tts": "mobile phone"}, {"left_image": "@@MEDIA@@gg2/u3/computer.webp", "right": "computer", "right_audio_tts": "computer"}, {"left_image": "@@MEDIA@@gg2/u3/laptop.webp", "right": "laptop", "right_audio_tts": "laptop"}, {"left_image": "@@MEDIA@@gg2/u3/camera.webp", "right": "camera", "right_audio_tts": "camera"}, {"left_image": "@@MEDIA@@gg2/u3/tablet.webp", "right": "tablet", "right_audio_tts": "tablet"}, {"left_image": "@@MEDIA@@gg2/u3/tv.webp", "right": "TV", "right_audio_tts": "TV"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'match', replace($blk${"title": "Соедини картинку со словом (2)", "pairs": [{"left_image": "@@MEDIA@@gg2/u3/headphones.webp", "right": "headphones", "right_audio_tts": "headphones"}, {"left_image": "@@MEDIA@@gg2/u3/keyboard.webp", "right": "keyboard", "right_audio_tts": "keyboard"}, {"left_image": "@@MEDIA@@gg2/u3/mouse.webp", "right": "mouse", "right_audio_tts": "mouse"}, {"left_image": "@@MEDIA@@gg2/u3/printer.webp", "right": "printer", "right_audio_tts": "printer"}, {"left_image": "@@MEDIA@@gg2/u3/screen.webp", "right": "screen", "right_audio_tts": "screen"}, {"left_image": "@@MEDIA@@gg2/u3/speakers.webp", "right": "speakers", "right_audio_tts": "speakers"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Как по-английски «мобильный телефон»?", "type": "single", "options": [{"text": "camera"}, {"text": "computer"}, {"text": "laptop"}, {"text": "mobile phone"}], "correct": [3]}, {"q": "Как по-английски «компьютер»?", "type": "single", "options": [{"text": "camera"}, {"text": "computer"}, {"text": "laptop"}, {"text": "tablet"}], "correct": [1]}, {"q": "Как по-английски «ноутбук»?", "type": "single", "options": [{"text": "camera"}, {"text": "laptop"}, {"text": "tablet"}, {"text": "TV"}], "correct": [1]}, {"q": "Как по-английски «камера»?", "type": "single", "options": [{"text": "camera"}, {"text": "headphones"}, {"text": "tablet"}, {"text": "TV"}], "correct": [0]}, {"q": "Как по-английски «планшет»?", "type": "single", "options": [{"text": "headphones"}, {"text": "keyboard"}, {"text": "tablet"}, {"text": "TV"}], "correct": [2]}, {"q": "Как по-английски «телевизор»?", "type": "single", "options": [{"text": "headphones"}, {"text": "keyboard"}, {"text": "mouse"}, {"text": "TV"}], "correct": [3]}, {"q": "Как по-английски «наушники»?", "type": "single", "options": [{"text": "headphones"}, {"text": "keyboard"}, {"text": "mouse"}, {"text": "printer"}], "correct": [0]}, {"q": "Как по-английски «клавиатура»?", "type": "single", "options": [{"text": "keyboard"}, {"text": "mouse"}, {"text": "printer"}, {"text": "screen"}], "correct": [0]}, {"q": "Как по-английски «мышь»?", "type": "single", "options": [{"text": "mouse"}, {"text": "printer"}, {"text": "screen"}, {"text": "speakers"}], "correct": [0]}, {"q": "Как по-английски «принтер»?", "type": "single", "options": [{"text": "mobile phone"}, {"text": "printer"}, {"text": "screen"}, {"text": "speakers"}], "correct": [1]}, {"q": "Как по-английски «экран»?", "type": "single", "options": [{"text": "computer"}, {"text": "mobile phone"}, {"text": "screen"}, {"text": "speakers"}], "correct": [2]}, {"q": "Как по-английски «колонки»?", "type": "single", "options": [{"text": "computer"}, {"text": "laptop"}, {"text": "mobile phone"}, {"text": "speakers"}], "correct": [3]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Часть 2: что мы делаем с гаджетами</h3><p>Привет-привет! В этой части домашнего задания мы постараемся запомнить выражения, которые связаны с интернетом и гаджетами. Они лёгкие и при этом очень полезные!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'flashcards', replace($blk${"title": "Действия с гаджетами: посмотри, послушай и запомни", "cards": [{"text": "chat online", "translation": "общаться онлайн", "image": "@@MEDIA@@gg2/u3/chat_online.webp", "audio_tts": "chat online"}, {"text": "download a song", "translation": "скачать песню", "image": "@@MEDIA@@gg2/u3/download_song.webp", "audio_tts": "download a song"}, {"text": "send an email", "translation": "отправить электронное письмо", "image": "@@MEDIA@@gg2/u3/send_email.webp", "audio_tts": "send an email"}, {"text": "surf the Internet", "translation": "сидеть в интернете", "image": "@@MEDIA@@gg2/u3/surf_internet.webp", "audio_tts": "surf the Internet"}, {"text": "take a selfie/photo", "translation": "сделать селфи/фото", "image": "@@MEDIA@@gg2/u3/take_selfie.webp", "audio_tts": "take a selfie"}, {"text": "talk on the phone", "translation": "говорить по телефону", "image": "@@MEDIA@@gg2/u3/talk_phone.webp", "audio_tts": "talk on the phone"}, {"text": "text a friend", "translation": "написать другу", "image": "@@MEDIA@@gg2/u3/text_friend.webp", "audio_tts": "text a friend"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'match', replace($blk${"title": "Соедини картинку с выражением", "pairs": [{"left_image": "@@MEDIA@@gg2/u3/chat_online.webp", "right": "chat online", "right_audio_tts": "chat online"}, {"left_image": "@@MEDIA@@gg2/u3/download_song.webp", "right": "download a song", "right_audio_tts": "download a song"}, {"left_image": "@@MEDIA@@gg2/u3/send_email.webp", "right": "send an email", "right_audio_tts": "send an email"}, {"left_image": "@@MEDIA@@gg2/u3/surf_internet.webp", "right": "surf the Internet", "right_audio_tts": "surf the Internet"}, {"left_image": "@@MEDIA@@gg2/u3/take_selfie.webp", "right": "take a selfie/photo", "right_audio_tts": "take a selfie"}, {"left_image": "@@MEDIA@@gg2/u3/talk_phone.webp", "right": "talk on the phone", "right_audio_tts": "talk on the phone"}, {"left_image": "@@MEDIA@@gg2/u3/text_friend.webp", "right": "text a friend", "right_audio_tts": "text a friend"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'exact_input', replace($blk${"items": [{"image": "@@MEDIA@@gg2/u3/chat_online.webp", "prompt": "Напиши по-английски: общаться онлайн", "accept": ["chat online"], "audio_tts": "chat online"}, {"image": "@@MEDIA@@gg2/u3/download_song.webp", "prompt": "Напиши по-английски: скачать песню", "accept": ["download a song"], "audio_tts": "download a song"}, {"image": "@@MEDIA@@gg2/u3/send_email.webp", "prompt": "Напиши по-английски: отправить электронное письмо", "accept": ["send an email"], "audio_tts": "send an email"}, {"image": "@@MEDIA@@gg2/u3/surf_internet.webp", "prompt": "Напиши по-английски: сидеть в интернете", "accept": ["surf the Internet", "surf the internet"], "audio_tts": "surf the Internet"}, {"image": "@@MEDIA@@gg2/u3/take_selfie.webp", "prompt": "Напиши по-английски: сделать селфи/фото", "accept": ["take a selfie/photo", "take a selfie", "take a photo"], "audio_tts": "take a selfie"}, {"image": "@@MEDIA@@gg2/u3/talk_phone.webp", "prompt": "Напиши по-английски: говорить по телефону", "accept": ["talk on the phone"], "audio_tts": "talk on the phone"}, {"image": "@@MEDIA@@gg2/u3/text_friend.webp", "prompt": "Напиши по-английски: написать другу", "accept": ["text a friend"], "audio_tts": "text a friend"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_highfive.webp\" alt=\"\" style=\"height:200px\"></p><h3>Часть 3: упражнения</h3><p>Огромный привет прекрасному ученику! Здесь тебя ждёт несколько упражнений. Они нужны, чтобы наверняка запомнить всё-всё, что ты недавно выучил. Давай начинать 😉</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'gaps', replace($blk${"title": "Прочитай историю про Джека и его гаджеты. Вставь пропущенные слова", "mode": "drag", "text": "Jack is a little boy who loves technology. He has a mobile phone, a laptop, and a tablet. He uses them every day to watch videos and play games. He also has __headphones__, so he can listen to music without disturbing anyone. Jack's favourite device is his __laptop__. He loves playing games on it and watching videos on the big __screen__. He has a __camera__, too, so he can take pictures of himself and his friends. When he needs to type something, he uses a __keyboard__. He also has a __mouse__ to help him move things around on the __screen__. Jack's mom has a __printer__, so he can print out pictures and documents when he needs to. Jack likes to connect his devices to __speakers__, so he can listen to music or watch videos with better sound. He even knows how to connect his __laptop__ to the __TV__! Jack is very smart and knows a lot about technology.", "image": "@@MEDIA@@gg2/u3/jack.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'match', replace($blk${"title": "Отлично! Давай теперь соберём фразы — соедини слова так, чтобы получились нужные выражения", "pairs": [{"left": "surf", "right": "the Internet", "right_audio_tts": "surf the Internet"}, {"left": "text", "right": "a friend", "right_audio_tts": "text a friend"}, {"left": "chat", "right": "online", "right_audio_tts": "chat online"}, {"left": "talk on", "right": "the phone", "right_audio_tts": "talk on the phone"}, {"left": "download", "right": "a song", "right_audio_tts": "download a song"}, {"left": "send", "right": "an email", "right_audio_tts": "send an email"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'gaps', replace($blk${"title": "Молодец! Осталось последнее задание 💪 Прочитай диалог и вставь пропущенные слова", "mode": "drag", "text": "A: Let's take a __selfie__. Ready? Smile!\nB: Cool! I really like your new __mobile__ phone. What else do you use it for?\nA: Mostly I __text__ my friends, __download__ songs and __surf the__ Internet.\nB: Can we use it to __chat__ online to Terry?\nA: Let's check!", "image": "@@MEDIA@@gg2/u3/take_selfie.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_star.webp\" alt=\"\" style=\"height:200px\"></p><h2>Супер! ⭐⭐⭐</h2><p>Вся домашняя работа выполнена. Ты просто крут! Увидимся на уроке :)</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13)
returning sort_order, type;
