-- Go Getter 2 · Unit 4 · Our world · Unit 4 Test
-- собрано tools/gg2_build.py --lesson u4_test
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 4 · Our world', 4 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 4 · Our world');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Unit 4 Test', 'test', 90, false, 7
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 4 · Our world'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Unit 4 Test');
update classroom_lessons l set kind = 'test', pass_threshold = 90, sort_order = 7
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 4 · Our world' and l.title = 'Unit 4 Test';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 4 · Our world' and l.title = 'Unit 4 Test';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'exact_input', replace($blk${"items": [{"image": "@@MEDIA@@gg2/u4/beach.webp", "prompt": "Напиши по-английски: пляж", "accept": ["beach", "Beach"], "audio_tts": "beach"}, {"image": "@@MEDIA@@gg2/u4/desert.webp", "prompt": "Напиши по-английски: пустыня", "accept": ["desert", "Desert"], "audio_tts": "desert"}, {"image": "@@MEDIA@@gg2/u4/island.webp", "prompt": "Напиши по-английски: остров", "accept": ["island", "Island"], "audio_tts": "island"}, {"image": "@@MEDIA@@gg2/u4/mountain.webp", "prompt": "Напиши по-английски: гора", "accept": ["mountain", "Mountain"], "audio_tts": "mountain"}, {"image": "@@MEDIA@@gg2/u4/volcano.webp", "prompt": "Напиши по-английски: вулкан", "accept": ["volcano", "Volcano"], "audio_tts": "volcano"}, {"image": "@@MEDIA@@gg2/u4/waterfall.webp", "prompt": "Напиши по-английски: водопад", "accept": ["waterfall", "Waterfall"], "audio_tts": "waterfall"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'text', replace($blk${"html": "<p>Выбери правильный вариант, чтобы предложение было грамматически верным.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "The Nile is ___ the Thames.", "type": "single", "options": [{"text": "longer than"}, {"text": "more long than"}, {"text": "longer that"}], "correct": [0]}, {"q": "Mount Everest is ___ mountain in the world.", "type": "single", "options": [{"text": "highest"}, {"text": "the highest"}, {"text": "the most high"}], "correct": [1]}, {"q": "This film is ___ than the book.", "type": "single", "options": [{"text": "excitinger than"}, {"text": "more exciting that"}, {"text": "more exciting"}], "correct": [2]}, {"q": "My brother is ___ person in our family.", "type": "single", "options": [{"text": "the funnyest"}, {"text": "the funniest"}, {"text": "most funny"}], "correct": [1]}, {"q": "Russian is ___ than English for tourists.", "type": "single", "options": [{"text": "more difficult"}, {"text": "difficulter than"}, {"text": "more difficult that"}], "correct": [0]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'gaps', replace($blk${"title": "Поставь прилагательное в скобках в правильную форму (comparative / superlative).", "mode": "type", "text": "1. The Sahara is __the biggest__ (big) desert in the world.\n2. A train is __cheaper__ (cheap) than a plane.\n3. This is __the most beautiful__ (beautiful) beach I know!\n4. My new bike is __better__ (good) than my old one.\n5. Today the weather is __worse__ (bad) than yesterday."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'text', replace($blk${"html": "<p>Расставь части предложения в правильном порядке.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'order', replace($blk${"words": ["Italy", "is", "smaller", "than", "Spain."], "sentence": "Italy is smaller than Spain.", "audio_tts": "Italy is smaller than Spain."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["The", "Amazon", "is", "the", "longest", "river", "in", "South America."], "sentence": "The Amazon is the longest river in South America.", "audio_tts": "The Amazon is the longest river in South America."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["Climbing", "mountains", "is", "more", "dangerous", "than", "swimming."], "sentence": "Climbing mountains is more dangerous than swimming.", "audio_tts": "Climbing mountains is more dangerous than swimming."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'order', replace($blk${"words": ["What", "is", "the", "most", "interesting", "city", "in", "your", "country?"], "sentence": "What is the most interesting city in your country?", "audio_tts": "What is the most interesting city in your country?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'order', replace($blk${"words": ["My", "sister", "is", "kinder", "than", "my", "brother."], "sentence": "My sister is kinder than my brother.", "audio_tts": "My sister is kinder than my brother."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'text', replace($blk${"html": "<h3>READING</h3><p>Прочитай текст, потом перетащи слова и числа в пропуски в предложениях.</p><h3>Three Amazing Places</h3><p>The world has thousands of beautiful places. Here are three of them.</p><p>The Sahara is the biggest hot desert in the world. It’s in North Africa and it’s bigger than many countries – about 9 million square kilometres! It’s a very dangerous place because it’s so hot and dry. But it’s also beautiful and famous.</p><p>Lake Baikal is in Russia. It isn’t the biggest lake in the world, but it’s the deepest – 1,642 metres deep! It’s also the oldest lake on Earth. In winter the water freezes and people sometimes walk on the ice.</p><p>Angel Falls in Venezuela is the highest waterfall in the world. It’s 979 metres high. The forest around it is dangerous and difficult for tourists, so it’s not as popular as Niagara Falls.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'gaps', replace($blk${"title": "Перетащи слова и числа в пропуски.", "mode": "drag", "text": "1. The Sahara is the __biggest__ hot desert in the world.\n2. The Sahara is in __North Africa__.\n3. Lake Baikal is the __deepest__ lake on Earth.\n4. Lake Baikal is __1,642__ metres deep.\n5. Angel Falls is __979__ metres high.\n6. Angel Falls is in __Venezuela__.\n7. Niagara Falls is __more popular__ than Angel Falls for tourists."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "<b>LISTENING.</b> Послушай интервью с туристом и выбери правильный ответ на каждый вопрос.<br>1. What is Marco’s job?", "type": "single", "options": [{"text": "tour guide"}, {"text": "travel blogger"}, {"text": "photographer"}, {"text": "teacher"}], "correct": [1], "audio": ""}, {"q": "What does Marco think about New Zealand?", "type": "single", "options": [{"text": "It’s the biggest country he knows."}, {"text": "It’s the most beautiful country he knows."}, {"text": "It’s the most expensive country he knows."}, {"text": "It’s the most dangerous country he knows."}], "correct": [1]}, {"q": "According to Marco, people in New Zealand are … than in other countries.", "type": "single", "options": [{"text": "funnier"}, {"text": "cleverer"}, {"text": "friendlier"}, {"text": "richer"}], "correct": [2]}, {"q": "Where did Marco go last year?", "type": "single", "options": [{"text": "New Zealand"}, {"text": "Brazil"}, {"text": "Iceland"}, {"text": "Italy"}], "correct": [2]}, {"q": "What was the weather like in Iceland?", "type": "single", "options": [{"text": "hotter than he expected"}, {"text": "colder than he expected"}, {"text": "the same as he expected"}, {"text": "the worst weather of his life"}], "correct": [1]}, {"q": "Why is the Amazon forest dangerous?", "type": "single", "options": [{"text": "The mountains are very high."}, {"text": "There are dangerous animals."}, {"text": "It’s too cold there."}, {"text": "People aren’t friendly."}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING I 🎤", "needs_review": true, "image": "@@MEDIA@@gg2/u4/book_mountain_lake.webp", "html": "<p>Опиши картинку и ответь на вопросы. Нажми на микрофон и запиши ответ.</p><ol><li>What can you see in the picture?</li><li>Are the mountains high or low?</li><li>Is the lake big or small?</li><li>Is this place beautiful?</li><li>Is it a dangerous place or a safe place?</li><li>What’s the most beautiful thing in the picture?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING II 🎤", "needs_review": true, "html": "<p>Ответь на вопросы полными предложениями. Нажми на микрофон и запиши ответ.</p><ol><li>What’s the biggest city in your country?</li><li>What’s the longest river in your country?</li><li>Are mountains more beautiful than the sea?</li><li>What’s the most interesting place in your town or city?</li><li>Who is the funniest person in your family?</li><li>What’s more exciting: football or computer games?</li><li>What’s more difficult: Maths or English?</li><li>What’s the most dangerous animal you know?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 14)
returning sort_order, type;
