-- Go Getter 2 · Unit 7 · Travel · Homework 1
-- собрано tools/gg2_build.py --lesson u7_hw1
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 7 · Travel', 7 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 7 · Travel');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 1', 'homework', 60, false, 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 7 · Travel'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 1');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 7 · Travel' and l.title = 'Homework 1';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 7 · Travel' and l.title = 'Homework 1';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет! 👋</h2><p>Сейчас мы с тобой выучим разные виды транспорта, а потом — глаголы, которые с ним говорят.</p><p>Выполни все задания, чтобы выучить слова на 100%!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'flashcards', replace($blk${"cards": [{"text": "car", "translation": "автомобиль", "image": "@@MEDIA@@gg2/u7/car.webp", "audio_tts": "car"}, {"text": "boat", "translation": "лодка", "image": "@@MEDIA@@gg2/u7/boat.webp", "audio_tts": "boat"}, {"text": "bike", "translation": "велосипед", "image": "@@MEDIA@@gg2/u7/bike.webp", "audio_tts": "bike"}, {"text": "bus", "translation": "автобус", "image": "@@MEDIA@@gg2/u7/bus.webp", "audio_tts": "bus"}, {"text": "motorbike", "translation": "мотоцикл", "image": "@@MEDIA@@gg2/u7/motorbike.webp", "audio_tts": "motorbike"}, {"text": "plane", "translation": "самолёт", "image": "@@MEDIA@@gg2/u7/plane.webp", "audio_tts": "plane"}, {"text": "taxi", "translation": "такси", "image": "@@MEDIA@@gg2/u7/taxi.webp", "audio_tts": "taxi"}, {"text": "train", "translation": "поезд", "image": "@@MEDIA@@gg2/u7/train.webp", "audio_tts": "train"}, {"text": "tram", "translation": "трамвай", "image": "@@MEDIA@@gg2/u7/tram.webp", "audio_tts": "tram"}, {"text": "underground", "translation": "метро", "image": "@@MEDIA@@gg2/u7/underground.webp", "audio_tts": "underground"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'match', replace($blk${"title": "Соедини картинку со словом", "pairs": [{"left_image": "@@MEDIA@@gg2/u7/car.webp", "right": "car", "right_audio_tts": "car"}, {"left_image": "@@MEDIA@@gg2/u7/boat.webp", "right": "boat", "right_audio_tts": "boat"}, {"left_image": "@@MEDIA@@gg2/u7/bike.webp", "right": "bike", "right_audio_tts": "bike"}, {"left_image": "@@MEDIA@@gg2/u7/bus.webp", "right": "bus", "right_audio_tts": "bus"}, {"left_image": "@@MEDIA@@gg2/u7/motorbike.webp", "right": "motorbike", "right_audio_tts": "motorbike"}, {"left_image": "@@MEDIA@@gg2/u7/plane.webp", "right": "plane", "right_audio_tts": "plane"}, {"left_image": "@@MEDIA@@gg2/u7/taxi.webp", "right": "taxi", "right_audio_tts": "taxi"}, {"left_image": "@@MEDIA@@gg2/u7/train.webp", "right": "train", "right_audio_tts": "train"}, {"left_image": "@@MEDIA@@gg2/u7/tram.webp", "right": "tram", "right_audio_tts": "tram"}, {"left_image": "@@MEDIA@@gg2/u7/underground.webp", "right": "underground", "right_audio_tts": "underground"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'exact_input', replace($blk${"title": "Напиши слово по-английски", "items": [{"prompt": "Напиши по-английски: автомобиль", "accept": ["car", "a car"], "audio_tts": "car"}, {"prompt": "Напиши по-английски: лодка", "accept": ["boat", "a boat"], "audio_tts": "boat"}, {"prompt": "Напиши по-английски: велосипед", "accept": ["bike", "a bike", "bicycle"], "audio_tts": "bike"}, {"prompt": "Напиши по-английски: автобус", "accept": ["bus", "a bus"], "audio_tts": "bus"}, {"prompt": "Напиши по-английски: мотоцикл", "accept": ["motorbike", "a motorbike"], "audio_tts": "motorbike"}, {"prompt": "Напиши по-английски: самолёт", "accept": ["plane", "a plane"], "audio_tts": "plane"}, {"prompt": "Напиши по-английски: такси", "accept": ["taxi", "a taxi"], "audio_tts": "taxi"}, {"prompt": "Напиши по-английски: поезд", "accept": ["train", "a train"], "audio_tts": "train"}, {"prompt": "Напиши по-английски: трамвай", "accept": ["tram", "a tram"], "audio_tts": "tram"}, {"prompt": "Напиши по-английски: метро", "accept": ["underground", "the underground"], "audio_tts": "underground"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Глаголы в дороге 🚉</h3><p>Отлично! А теперь выучим глаголы, которые нужны в дороге. Например: <i>take a bus</i> — поехать на автобусе, <i>get off the train</i> — выйти из поезда.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'flashcards', replace($blk${"cards": [{"text": "arrive", "translation": "прибыть", "image": "@@MEDIA@@gg2/u7/arrive.webp", "audio_tts": "arrive"}, {"text": "get on", "translation": "сесть, войти (в автобус, поезд)", "image": "@@MEDIA@@gg2/u7/get_on.webp", "audio_tts": "get on"}, {"text": "get off", "translation": "выйти (из автобуса, поезда)", "image": "@@MEDIA@@gg2/u7/get_off.webp", "audio_tts": "get off"}, {"text": "leave", "translation": "уезжать, отправляться", "image": "@@MEDIA@@gg2/u7/leave.webp", "audio_tts": "leave"}, {"text": "take", "translation": "сесть на (транспорт), поехать на", "image": "@@MEDIA@@gg2/u7/take_bus.webp", "audio_tts": "take"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'match', replace($blk${"title": "Соедини картинку с глаголом", "pairs": [{"left_image": "@@MEDIA@@gg2/u7/arrive.webp", "right": "arrive", "right_audio_tts": "arrive"}, {"left_image": "@@MEDIA@@gg2/u7/get_on.webp", "right": "get on", "right_audio_tts": "get on"}, {"left_image": "@@MEDIA@@gg2/u7/get_off.webp", "right": "get off", "right_audio_tts": "get off"}, {"left_image": "@@MEDIA@@gg2/u7/leave.webp", "right": "leave", "right_audio_tts": "leave"}, {"left_image": "@@MEDIA@@gg2/u7/take_bus.webp", "right": "take", "right_audio_tts": "take"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'exact_input', replace($blk${"title": "Напиши слово по-английски", "items": [{"prompt": "Напиши по-английски: прибыть", "accept": ["arrive"], "audio_tts": "arrive"}, {"prompt": "Напиши по-английски: сесть, войти (в автобус)", "accept": ["get on"], "audio_tts": "get on"}, {"prompt": "Напиши по-английски: выйти (из поезда)", "accept": ["get off"], "audio_tts": "get off"}, {"prompt": "Напиши по-английски: уезжать, отправляться", "accept": ["leave"], "audio_tts": "leave"}, {"prompt": "Напиши по-английски: сесть на (транспорт), поехать на", "accept": ["take"], "audio_tts": "take"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_rocket.webp\" alt=\"\" style=\"height:200px\"></p><h2>Дополнительная часть 🚀</h2><p>Добро пожаловать в ДОПОЛНИТЕЛЬНУЮ часть домашнего задания! Выполни все задания, чтобы хорошенько запомнить новые слова. Выполнив их, ты станешь МЕГАКЛАССНЫМ учеником!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "It is very long and it has lots of wheels. It runs on streets.", "type": "single", "options": [{"text": "bus"}, {"text": "tram"}, {"text": "car"}], "correct": [1]}, {"q": "You can go to an island on this over water.", "type": "single", "options": [{"text": "boat"}, {"text": "car"}, {"text": "bike"}], "correct": [0]}, {"q": "It flies in the air.", "type": "single", "options": [{"text": "car"}, {"text": "motorbike"}, {"text": "plane"}], "correct": [2]}, {"q": "It has four wheels. Many families have got one.", "type": "single", "options": [{"text": "bus"}, {"text": "car"}, {"text": "motorbike"}], "correct": [1]}, {"q": "Children have got these and they can ride them in the park.", "type": "single", "options": [{"text": "boat"}, {"text": "plane"}, {"text": "bike"}], "correct": [2]}], "title": "Прочитай описание и выбери подходящий транспорт"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'gaps', replace($blk${"title": "Прочитай историю про Энзо. Как он добирается до школы? Перетащи слова в пропуски", "mode": "drag", "image": "@@MEDIA@@gg2/u7/enzo.webp", "text": "14-year-old Enzo Paci lives in Queens in New York City and he travels two hours to a school in the Bronx. It's a very good school. Enzo __takes__ a bus and two trains, and the last ten minutes of his journey is __on__ foot. At 6.30 a.m. he goes to the train station __by__ bus. The train __leaves__ at 7 a.m. and arrives in Manhattan at 8 a.m. Then, at 8.30 a.m. Enzo __gets on__ another train to his school! It's one of the longest school journeys in the world!"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'speaking', replace($blk${"title": "Как ты добираешься до школы? 🎤", "html": "<p>ДОПОЛНИТЕЛЬНОЕ ЗАДАНИЕ — для самых смелых! Прочитай ещё раз историю Энзо и расскажи, как ты добираешься до школы.</p><p><i>Например: I go to school by bus. The bus leaves at 7.30 a.m.</i></p>", "needs_review": true}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_star.webp\" alt=\"\" style=\"height:200px\"></p><h2>Супер! ⭐⭐⭐⭐⭐</h2><p>Вся домашняя работа выполнена. Ты просто крут! Увидимся на уроке :)</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12)
returning sort_order, type;
