-- Go Getter 2 · Unit 2 · Homework 2
-- собрано tools/gg2_build.py --lesson u2_hw2
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 2', 2 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 2');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 2', 'homework', 60, false, 1
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 2'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 2');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 1
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 2' and l.title = 'Homework 2';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 2' and l.title = 'Homework 2';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_book.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет! 👋</h2><p>В этом уроке мы выучим ещё несколько названий продуктов. Выполни все задания, чтобы выучить слова! У тебя всё получится. Удачи! ❤️</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'flashcards', replace($blk${"cards": [{"text": "butter", "translation": "сливочное масло", "audio_tts": "butter", "image": "@@MEDIA@@gg2/u2/butter.webp"}, {"text": "chocolate", "translation": "шоколад", "audio_tts": "chocolate", "image": "@@MEDIA@@gg2/u2/chocolate.webp"}, {"text": "egg", "translation": "яйцо", "audio_tts": "egg", "image": "@@MEDIA@@gg2/u2/egg.webp"}, {"text": "flour", "translation": "мука", "audio_tts": "flour", "image": "@@MEDIA@@gg2/u2/flour.webp"}, {"text": "lemon", "translation": "лимон", "audio_tts": "lemon", "image": "@@MEDIA@@gg2/u2/lemon.webp"}, {"text": "milk", "translation": "молоко", "audio_tts": "milk", "image": "@@MEDIA@@gg2/u2/milk.webp"}, {"text": "strawberry", "translation": "клубника", "audio_tts": "strawberry", "image": "@@MEDIA@@gg2/u2/strawberry.webp"}, {"text": "sugar", "translation": "сахар", "audio_tts": "sugar", "image": "@@MEDIA@@gg2/u2/sugar.webp"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'match', replace($blk${"title": "Соедини картинку со словом", "pairs": [{"left_image": "@@MEDIA@@gg2/u2/butter.webp", "right": "butter", "right_audio_tts": "butter"}, {"left_image": "@@MEDIA@@gg2/u2/chocolate.webp", "right": "chocolate", "right_audio_tts": "chocolate"}, {"left_image": "@@MEDIA@@gg2/u2/egg.webp", "right": "egg", "right_audio_tts": "egg"}, {"left_image": "@@MEDIA@@gg2/u2/flour.webp", "right": "flour", "right_audio_tts": "flour"}, {"left_image": "@@MEDIA@@gg2/u2/lemon.webp", "right": "lemon", "right_audio_tts": "lemon"}, {"left_image": "@@MEDIA@@gg2/u2/milk.webp", "right": "milk", "right_audio_tts": "milk"}, {"left_image": "@@MEDIA@@gg2/u2/strawberry.webp", "right": "strawberry", "right_audio_tts": "strawberry"}, {"left_image": "@@MEDIA@@gg2/u2/sugar.webp", "right": "sugar", "right_audio_tts": "sugar"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'exact_input', replace($blk${"items": [{"image": "@@MEDIA@@gg2/u2/butter.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["butter", "Butter"], "audio_tts": "butter"}, {"image": "@@MEDIA@@gg2/u2/chocolate.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["chocolate", "Chocolate"], "audio_tts": "chocolate"}, {"image": "@@MEDIA@@gg2/u2/egg.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["egg", "Egg"], "audio_tts": "egg"}, {"image": "@@MEDIA@@gg2/u2/flour.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["flour", "Flour"], "audio_tts": "flour"}, {"image": "@@MEDIA@@gg2/u2/lemon.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["lemon", "Lemon"], "audio_tts": "lemon"}, {"image": "@@MEDIA@@gg2/u2/milk.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["milk", "Milk"], "audio_tts": "milk"}, {"image": "@@MEDIA@@gg2/u2/strawberry.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["strawberry", "Strawberry"], "audio_tts": "strawberry"}, {"image": "@@MEDIA@@gg2/u2/sugar.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["sugar", "Sugar"], "audio_tts": "sugar"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Вторая часть 💪</h2><p>Добро пожаловать во вторую часть домашнего задания! Сегодня мы с тобой закрепим знания, полученные на уроке, и ты без проблем сможешь различать исчисляемые и неисчисляемые существительные. В конце тебя будет ждать дополнительное упражнение — для самых смелых и самых сильных учеников 💪</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'text', replace($blk${"html": "<p>И начнём мы с тобой с видео! Анна, Макс и Хэмми решили весело провести время вместе. Посмотри на картинку и попробуй угадать, чем же они будут заниматься. Посмотри видео и проверь, угадал ли ты. Повторяй вопросы и ответы за ребятами, чтобы хорошенько запомнить правила.</p><p><img src=\"@@MEDIA@@gg2/u2/book_bake_perfect.webp\" alt=\"Hammy\" style=\"max-width:100%;max-height:320px\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'video', replace($blk${"title": "Посмотри видео: что готовят Анна, Макс и Хэмми? 🥞", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'match', replace($blk${"title": "Посмотри видео ещё раз и соедини вопросы и ответы", "pairs": [{"left": "Are there any eggs?", "right": "Yes, there are.", "right_audio_tts": "Yes, there are."}, {"left": "Is there any cream?", "right": "There's some milk.", "right_audio_tts": "There's some milk."}, {"left": "Are there any bananas?", "right": "No, there aren't. But there are some strawberries.", "right_audio_tts": "No, there aren't. But there are some strawberries."}, {"left": "Is there any flour?", "right": "Yes, there is.", "right_audio_tts": "Yes, there is."}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'sort', replace($blk${"title": "Рассортируй продукты: исчисляемые (их можно посчитать) — в колонку countable, неисчисляемые (их посчитать нельзя) — в колонку uncountable", "groups": [{"name": "countable", "items": [{"text": "egg"}, {"text": "apple"}, {"text": "banana"}, {"text": "sausage"}, {"text": "lemon"}, {"text": "strawberry"}]}, {"name": "uncountable", "items": [{"text": "butter"}, {"text": "milk"}, {"text": "water"}, {"text": "sugar"}, {"text": "flour"}, {"text": "chocolate"}]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Блинчики Ани 🥞</h3><p>Молодец! Ты справился с заданием. Посмотри — это Аня. Она обожает готовить и есть блинчики. Они у неё оооочень вкусные. Аня поделилась с нами своим рецептом. Как думаешь, в чём же её секрет? Прочти рецепт и выбери правильный вариант для каждого пропуска.</p><p><img src=\"@@MEDIA@@gg2/u2/anya_pancakes.webp\" alt=\"Anya\" style=\"max-width:100%;max-height:320px\"></p><p><i>My pancake recipe has (1) ___, (2) ___, (3) ___ and (4) ___. For the topping I like (5) ___ and (6) ___.</i></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "(1) My pancake recipe has ___, …", "type": "single", "options": [{"text": "a flour"}, {"text": "flour"}, {"text": "an flour"}], "correct": [1]}, {"q": "(2) …, ___, …", "type": "single", "options": [{"text": "an egg"}, {"text": "egg"}, {"text": "a egg"}], "correct": [0]}, {"q": "(3) … ___ and …", "type": "single", "options": [{"text": "a milk"}, {"text": "an milk"}, {"text": "milk"}], "correct": [2]}, {"q": "(4) … and ___.", "type": "single", "options": [{"text": "butter"}, {"text": "a butter"}, {"text": "an butter"}], "correct": [0]}, {"q": "(5) For the topping I like ___ and …", "type": "single", "options": [{"text": "banana"}, {"text": "an banana"}, {"text": "a banana"}], "correct": [2]}, {"q": "(6) … and ___.", "type": "single", "options": [{"text": "a cream"}, {"text": "cream"}, {"text": "an cream"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "А теперь потренируемся составлять вопросы. ___ there ___ sugar?", "type": "single", "options": [{"text": "Are … any"}, {"text": "Is … any"}, {"text": "Is … some"}, {"text": "a … an"}], "correct": [1]}, {"q": "___ there ___ apples?", "type": "single", "options": [{"text": "Are … any"}, {"text": "Is … any"}, {"text": "Are … some"}, {"text": "Are … a"}], "correct": [0]}, {"q": "___ there ___ butter?", "type": "single", "options": [{"text": "Are … any"}, {"text": "Is … some"}, {"text": "Is … a"}, {"text": "Is … any"}], "correct": [3]}, {"q": "___ there ___ bananas?", "type": "single", "options": [{"text": "Is … any"}, {"text": "Are … some"}, {"text": "Are … any"}, {"text": "Are … a"}], "correct": [2]}, {"q": "___ there ___ flour?", "type": "single", "options": [{"text": "Is … some"}, {"text": "Is … any"}, {"text": "Are … any"}, {"text": "Is … a"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Список покупок 📝</h3><p>Ты справился с большей частью заданий! Посмотри! Том и Мэтт собираются в магазин. Но сначала им нужно составить список продуктов. Прочти диалог ниже и заполни пропуски. А ты составляешь список продуктов перед походом в магазин?</p><p><img src=\"@@MEDIA@@gg2/u2/tom_matt_list.webp\" alt=\"Tom and Matt\" style=\"max-width:100%;max-height:320px\"></p><p><b>Shopping list:</b> 1 litre milk · 6 eggs · butter · flour · chocolate · 4 bananas</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'gaps', replace($blk${"title": "Перетащи слова в пропуски", "mode": "drag", "text": "Tom: What's on the shopping list? Does mum want __any__ chocolate?\nMatt: Yes! There are __some__ bananas too.\nTom: And __are__ there any eggs on the list?\nMatt: Yes, __there__ are.\nTom: What about __an__ orange?\nMatt: No. There __aren't__ any oranges. Look! There __is__ some butter on the list. It's a list for pancakes!"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13),
('<lesson_id>', 'task', replace($blk${"title": "Дополнительное задание: диалог о списке продуктов", "needs_review": true, "html": "<p>Ура, ты выполнил все основные задания! А это — последнее, дополнительное, для самых смелых! Составь и запиши диалог о списке продуктов. Можешь взять диалог из предыдущего упражнения в качестве примера. Удачи, ты обязательно справишься!</p><p><i>Shopping list: apples, carrots, chicken, cheese, curry sauce, doughnuts</i></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 14),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_clap.webp\" alt=\"\" style=\"height:180px\"></p><h3>Ура! Ты справился с домашней работой!</h3><p>Ты молодец! Увидимся на занятии!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 15)
returning sort_order, type;
