-- Go Getter 2 · Final Test · Final Test
-- собрано tools/gg2_build.py --lesson final
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Final Test', 9 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Final Test');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Final Test', 'test', 90, false, 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Final Test'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Final Test');
update classroom_lessons l set kind = 'test', pass_threshold = 90, sort_order = 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Final Test' and l.title = 'Final Test';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Final Test' and l.title = 'Final Test';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<h3>DICTATION ✍️</h3><p>Впиши слова по-английски.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'exact_input', replace($blk${"items": [{"prompt": "Напиши по-английски: шкаф для одежды", "accept": ["wardrobe"], "audio_tts": "wardrobe"}, {"prompt": "Напиши по-английски: словарь", "accept": ["dictionary"], "audio_tts": "dictionary"}, {"prompt": "Напиши по-английски: овощи", "accept": ["vegetables"], "audio_tts": "vegetables"}, {"prompt": "Напиши по-английски: наушники", "accept": ["headphones"], "audio_tts": "headphones"}, {"prompt": "Напиши по-английски: водопад", "accept": ["waterfall"], "audio_tts": "waterfall"}, {"prompt": "Напиши по-английски: музей", "accept": ["museum"], "audio_tts": "museum"}, {"prompt": "Напиши по-английски: строитель", "accept": ["builder"], "audio_tts": "builder"}, {"prompt": "Напиши по-английски: чемодан", "accept": ["suitcase"], "audio_tts": "suitcase"}, {"prompt": "Напиши по-английски: ночёвка", "accept": ["sleepover"], "audio_tts": "sleepover"}, {"prompt": "Напиши по-английски: опасный", "accept": ["dangerous"], "audio_tts": "dangerous"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'text', replace($blk${"html": "<h3>VOCABULARY 📚</h3><p>Выбери правильный ответ.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'quiz', replace($blk${"title": "VOCABULARY. Выбери правильный ответ", "questions": [{"q": "We have P.E. lessons in the school ___.", "type": "single", "options": [{"text": "library"}, {"text": "gym"}, {"text": "kitchen"}, {"text": "garden"}], "correct": [1]}, {"q": "In ___ we learn about countries, cities and maps.", "type": "single", "options": [{"text": "Maths"}, {"text": "Music"}, {"text": "Art"}, {"text": "Geography"}], "correct": [3]}, {"q": "Can I have a ___ of chocolate, please?", "type": "single", "options": [{"text": "bar"}, {"text": "bottle"}, {"text": "jar"}, {"text": "cup"}], "correct": [0]}, {"q": "I download songs to my ___.", "type": "single", "options": [{"text": "calculator"}, {"text": "bookcase"}, {"text": "phone"}, {"text": "armchair"}], "correct": [2]}, {"q": "Etna is a famous ___ in Italy. Look at its lava. It's amazing!", "type": "single", "options": [{"text": "waterfall"}, {"text": "volcano"}, {"text": "lake"}, {"text": "island"}], "correct": [1]}, {"q": "We can buy clothes and shoes at the ___.", "type": "single", "options": [{"text": "post office"}, {"text": "police station"}, {"text": "hospital"}, {"text": "shopping centre"}], "correct": [3]}, {"q": "A person who helps sick animals is a ___.", "type": "single", "options": [{"text": "builder"}, {"text": "chef"}, {"text": "vet"}, {"text": "doctor"}], "correct": [2]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'text', replace($blk${"html": "<h3>GRAMMAR ✏️</h3><p>Выбери правильный ответ.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'quiz', replace($blk${"title": "GRAMMAR. Выбери правильный ответ", "questions": [{"q": "My sister ___ thirteen years old.", "type": "single", "options": [{"text": "am"}, {"text": "is"}, {"text": "are"}], "correct": [1]}, {"q": "I ___ two brothers and one sister.", "type": "single", "options": [{"text": "am got"}, {"text": "has got"}, {"text": "have got"}], "correct": [2]}, {"q": "This is my brother. ___ name is Tom.", "type": "single", "options": [{"text": "Her"}, {"text": "His"}, {"text": "Their"}], "correct": [1]}, {"q": "Anna ___ tennis every Sunday morning.", "type": "single", "options": [{"text": "play"}, {"text": "plays"}, {"text": "playing"}], "correct": [1]}, {"q": "We haven't got ___ milk for breakfast.", "type": "single", "options": [{"text": "some"}, {"text": "any"}, {"text": "a"}], "correct": [1]}, {"q": "How ___ eggs are there in the fridge?", "type": "single", "options": [{"text": "much"}, {"text": "many"}, {"text": "a lot"}], "correct": [1]}, {"q": "Look! The boy ___ a selfie with his phone.", "type": "single", "options": [{"text": "take"}, {"text": "takes"}, {"text": "is taking"}], "correct": [2]}, {"q": "Russia is ___ than Italy.", "type": "single", "options": [{"text": "big"}, {"text": "bigger"}, {"text": "the biggest"}], "correct": [1]}, {"q": "Yesterday my parents ___ at work all day.", "type": "single", "options": [{"text": "was"}, {"text": "were"}, {"text": "are"}], "correct": [1]}, {"q": "Last Saturday I ___ a great film at the cinema.", "type": "single", "options": [{"text": "watch"}, {"text": "watches"}, {"text": "watched"}], "correct": [2]}, {"q": "___ you go to school yesterday?", "type": "single", "options": [{"text": "Did"}, {"text": "Do"}, {"text": "Was"}], "correct": [0]}, {"q": "Tomorrow we ___ a film at the cinema with my friends.", "type": "single", "options": [{"text": "watch"}, {"text": "are going to watch"}, {"text": "watched"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'text', replace($blk${"html": "<h3>READING 📖</h3><p>Прочитай текст и выбери правильный ответ на каждый вопрос.</p><h4>My Best Year</h4><p>I'm thirteen years old and last year was the best year of my life. Let me tell you about it.</p><p>In September I started a new school in Manchester. At first, I was scared because I didn't know anyone. But on the first day, I met Lily – she became my best friend! She lives next to my house, so we walk to school together every morning.</p><p>My favourite subject is Geography. Last term, we learned about the longest rivers and the highest mountains in the world. Our teacher, Mrs Green, is very kind and always makes us laugh.</p><p>In July, my family went on holiday to Italy. We visited Rome, ate pizza every day, and I bought lots of souvenirs. Italy was hotter than England and the food was amazing!</p><p>Next year I'm going to study harder because I want to get good marks. I'm also going to do karate!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'quiz', replace($blk${"title": "READING. Выбери правильный ответ", "questions": [{"q": "How old is the writer of the text?", "type": "single", "options": [{"text": "12"}, {"text": "13"}, {"text": "14"}, {"text": "15"}], "correct": [1]}, {"q": "Where is her new school?", "type": "single", "options": [{"text": "London"}, {"text": "Rome"}, {"text": "Manchester"}, {"text": "Italy"}], "correct": [2]}, {"q": "Why was she scared on the first day of school?", "type": "single", "options": [{"text": "The school was very big."}, {"text": "She didn't know anyone."}, {"text": "The teachers were strict."}, {"text": "She got lost."}], "correct": [1]}, {"q": "Where does Lily live?", "type": "single", "options": [{"text": "In Italy."}, {"text": "Far from the writer."}, {"text": "Next to the writer's house."}, {"text": "In the same house as the writer."}], "correct": [2]}, {"q": "What is the writer's favourite subject?", "type": "single", "options": [{"text": "Maths"}, {"text": "English"}, {"text": "History"}, {"text": "Geography"}], "correct": [3]}, {"q": "What did the family do in Italy?", "type": "single", "options": [{"text": "They learned Italian."}, {"text": "They visited Rome and ate pizza."}, {"text": "They went to the mountains."}, {"text": "They stayed in a hotel for a year."}], "correct": [1]}, {"q": "What is the writer's plan for next year?", "type": "single", "options": [{"text": "Change school."}, {"text": "Study less and watch more TV."}, {"text": "Study harder and do karate."}, {"text": "Move to Italy."}], "correct": [2]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'video', replace($blk${"title": "LISTENING 🎧 Послушай разговор Софи с её мамой.", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'truefalse', replace($blk${"title": "Выбери TRUE (верно) или FALSE (неверно)", "statements": [{"text": "Yesterday Sophie was at the library.", "correct": true}, {"text": "Sophie did her homework with Tom.", "correct": false}, {"text": "Sophie's dad likes travelling.", "correct": true}, {"text": "Lily and Sophie are going to have lunch at a restaurant.", "correct": false}, {"text": "Sophie's dad's birthday is on Monday.", "correct": true}, {"text": "Sophie is going to walk to the shopping centre.", "correct": false}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING I 🎤", "needs_review": true, "image": "@@MEDIA@@gg2/final/book_tom_surprise.webp", "html": "<p>Посмотри на 5 картинок и расскажи историю. Используй Past Simple. Помогут вопросы ниже. Запиши ответ, нажав на кнопку микрофона (до 5 минут).</p><ol><li>Where was Tom in the first picture? What did he see on his pillow?</li><li>What did the card say? Who was it from?</li><li>Where did Tom go in the afternoon? Who did he take with him?</li><li>What was waiting for Tom at the park? Who was there?</li><li>What did Tom do in the last picture? How did he feel?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING II 🎤", "needs_review": true, "html": "<p>Ответь на вопросы полными предложениями. Запиши ответ, нажав на кнопку микрофона (до 5 минут).</p><ol><li>Have you got any brothers or sisters?</li><li>What's your favourite school subject? Why do you like it?</li><li>What do you usually have for breakfast? What food don't you like?</li><li>What gadgets have you got? What do you usually use them for?</li><li>What's the most beautiful place in your country? Why?</li><li>Where were you last Saturday afternoon? What did you do there?</li><li>What did you do yesterday after school?</li><li>Where did you go on your last holiday? How did you travel?</li><li>What are you going to do next weekend?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11)
returning sort_order, type;
