-- Go Getter 2 · Unit 0 · Unit 0 Test
-- собрано tools/gg2_build.py --lesson u0_test
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 0', 0 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 0');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Unit 0 Test', 'test', 90, false, 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 0'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Unit 0 Test');
update classroom_lessons l set kind = 'test', pass_threshold = 90, sort_order = 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 0' and l.title = 'Unit 0 Test';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 0' and l.title = 'Unit 0 Test';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/good_luck_clover.webp\" alt=\"\" style=\"height:180px\"></p><h2>Тест: вспоминаем Go Getter 1 📝</h2><p>В этом тесте ты повторишь всё, что учил в прошлом году: семью, комнату и мебель, месяцы, глаголы <i>have got</i> и <i>can</i>, <i>there is / there are</i>.</p><p>Чтобы пройти тест, нужно набрать 90 баллов. Не торопись и внимательно читай задания. Удачи!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'exact_input', replace($blk${"title": "Напиши слова по-английски", "items": [{"prompt": "1. Напиши по-английски: февраль", "image": "@@MEDIA@@gg2/u0/february.webp", "accept": ["February", "february"], "audio_tts": "February"}, {"prompt": "2. Напиши по-английски: кататься на скейтборде", "image": "@@MEDIA@@gg2/u0/skateboard.webp", "accept": ["skateboard", "Skateboard"], "audio_tts": "skateboard"}, {"prompt": "3. Напиши по-английски: рисовать", "image": "@@MEDIA@@gg2/u0/draw.webp", "accept": ["draw", "Draw"], "audio_tts": "draw"}, {"prompt": "4. Напиши по-английски: кресло", "image": "@@MEDIA@@gg2/u0/armchair.webp", "accept": ["armchair", "Armchair", "an armchair"], "audio_tts": "armchair"}, {"prompt": "5. Напиши по-английски: шкаф для одежды", "image": "@@MEDIA@@gg2/u0/wardrobe.webp", "accept": ["wardrobe", "Wardrobe", "a wardrobe"], "audio_tts": "wardrobe"}, {"prompt": "6. Напиши по-английски: полки", "image": "@@MEDIA@@gg2/u0/shelves.webp", "accept": ["shelves", "Shelves"], "audio_tts": "shelves"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'quiz', replace($blk${"title": "Выбери правильный вариант, чтобы предложение было грамматически верным", "questions": [{"q": "My sister ___ thirteen years old.", "type": "single", "options": [{"text": "am"}, {"text": "is"}, {"text": "are"}], "correct": [1]}, {"q": "They ___ got a friendly dog called Max.", "type": "single", "options": [{"text": "are"}, {"text": "has"}, {"text": "have"}], "correct": [2]}, {"q": "___ you ride a bike? — Yes, I can.", "type": "single", "options": [{"text": "Can"}, {"text": "Do"}, {"text": "Are"}], "correct": [0]}, {"q": "___ two armchairs in the living room.", "type": "single", "options": [{"text": "There is"}, {"text": "Are there"}, {"text": "There are"}], "correct": [2]}, {"q": "___ trainers are new. Look!", "type": "single", "options": [{"text": "This"}, {"text": "These"}, {"text": "That"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'gaps', replace($blk${"title": "Поставь слово в скобках в правильную форму. Используй притяжательные прилагательные (my, your, his, her, its, our, their) или 's", "mode": "type", "text": "1. This is __my|My__ new desk. (I)\n2. __Her|her__ name is Maria. (She)\n3. __Their|their__ house is big and modern. (They)\n4. __Anna's|Anna’s__ brother is in my class. (Anna)\n5. The cat is sleeping on the __children's|children’s__ bed. (children)"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Расставь части предложения в правильном порядке</h3><p>В следующих пяти заданиях собери предложения из частей.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'order', replace($blk${"words": ["My friend", "has got", "a new", "black", "skateboard."], "sentence": "My friend has got a new black skateboard.", "audio_tts": "My friend has got a new black skateboard."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["There are", "two armchairs", "next to", "the window."], "sentence": "There are two armchairs next to the window.", "audio_tts": "There are two armchairs next to the window."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["Can", "your sister", "play", "the piano?"], "sentence": "Can your sister play the piano?", "audio_tts": "Can your sister play the piano?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'order', replace($blk${"words": ["My", "cousins", "are", "from", "Argentina."], "sentence": "My cousins are from Argentina.", "audio_tts": "My cousins are from Argentina."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'order', replace($blk${"words": ["These", "shoes", "are", "my", "brother’s."], "sentence": "These shoes are my brother’s.", "audio_tts": "These shoes are my brother's."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'text', replace($blk${"html": "<h3>READING</h3><p>Прочитай текст и выбери правильный ответ на каждый вопрос.</p><h3>Meet Marta</h3><p>Hi! My name's Marta and I'm thirteen years old. I'm from Warsaw, Poland. My mum is Italian, so I can speak Italian. I can also speak Polish and English. My birthday is in September.</p><p>I've got a big family. I've got two brothers, one sister, and a friendly cat called Bruno. We're a happy family!</p><p>My bedroom is my favourite room. There's a desk next to the window and a tall wardrobe in the corner. My bed is under the shelves and my old armchair is next to the bed.</p><p>I love sport. I can swim and ride a bike, but I can't skateboard. My brother Daniel is sporty too. He's twelve and he can play football very well!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'quiz', replace($blk${"title": "READING. Выбери правильный ответ на каждый вопрос", "questions": [{"q": "How old is Marta?", "type": "single", "options": [{"text": "12"}, {"text": "13"}, {"text": "14"}, {"text": "15"}], "correct": [1]}, {"q": "Why can Marta speak Italian?", "type": "single", "options": [{"text": "Her dad is Italian."}, {"text": "She lives in Italy."}, {"text": "She learns it at school."}, {"text": "Her mum is Italian."}], "correct": [3]}, {"q": "Where is the wardrobe?", "type": "single", "options": [{"text": "In the corner"}, {"text": "Next to the window"}, {"text": "Under the shelves"}, {"text": "Next to the bed"}], "correct": [0]}, {"q": "Where is Marta's bed?", "type": "single", "options": [{"text": "Next to the window"}, {"text": "In the corner"}, {"text": "Under the shelves"}, {"text": "Next to the wardrobe"}], "correct": [2]}, {"q": "What CAN'T Marta do?", "type": "single", "options": [{"text": "Swim"}, {"text": "Ride a bike"}, {"text": "Skateboard"}, {"text": "Play football"}], "correct": [2]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'video', replace($blk${"title": "Послушай, как три подростка рассказывают о себе на видеозвонке", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'sort', replace($blk${"title": "Послушай запись ещё раз и соедини каждого подростка с двумя фактами о нём", "groups": [{"name": "Tom", "items": [{"text": "is from Manchester, the UK"}, {"text": "can play tennis"}]}, {"name": "Léa", "items": [{"text": "has no brothers or sisters"}, {"text": "plays the guitar"}]}, {"name": "Aylin", "items": [{"text": "loves cooking"}, {"text": "has a red hoodie"}]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING I 🎤", "needs_review": true, "image": "@@MEDIA@@gg2/u0/scene_bedroom.webp", "html": "<p>Опиши картинку и ответь на вопросы. Нажми на микрофон и запиши ответ.</p><ol><li>What can you see in the room?</li><li>Where is the boy?</li><li>Where is his bag?</li><li>What has he got on his shelves?</li><li>Can the boy play the guitar?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 14),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING II 🎤", "needs_review": true, "html": "<p>Ответь на вопросы полными предложениями. Нажми на микрофон и запиши ответ.</p><ol><li>What's your name? How old are you?</li><li>Where are you from?</li><li>Have you got a pet?</li><li>Can you swim?</li><li>What's your favourite room in your house?</li><li>What is there in your bedroom?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 15),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_trophy.webp\" alt=\"\" style=\"height:180px\"></p><h3>Тест пройден! 🎉</h3><p>Ты отлично вспомнил прошлый год. Теперь — вперёд, к Unit 1!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 16)
returning sort_order, type;
