-- Go Getter 2 · Unit 3 · Technology · Homework 3
-- собрано tools/gg2_build.py --lesson u3_hw3
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 3 · Technology', 3 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 3 · Technology');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 3', 'homework', 60, false, 2
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 3 · Technology'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 3');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 2
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 3 · Technology' and l.title = 'Homework 3';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 3 · Technology' and l.title = 'Homework 3';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_book.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет! 👋</h2><p>Добро пожаловать в новую домашнюю работу :) Здесь тебя как всегда ждут интересные и даже иногда непростые задания. Но у тебя всё-всё получится. Вперёд 🎉</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'text', replace($blk${"html": "<p>Внизу тебя ждёт видео. Посмотри его. Когда увидишь вопросы, отвечай на них вслух: либо <i>Yes</i>, либо <i>No</i>.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'video', replace($blk${"title": "Посмотри видео и отвечай на вопросы вслух: Yes или No", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Вопросы и краткие ответы</h3><p>Посмотри правило и изучи его. Оно пригодится для следующих заданий.</p><p><img src=\"@@MEDIA@@gg2/u3/book_short_answers.webp\" alt=\"Am I coming? Yes, I am.\" style=\"max-width:100%;max-height:360px\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'gaps', replace($blk${"title": "На картинке — кошка Карла и пёс Большой Эл. Прочитай их диалог и впиши пропущенные слова", "mode": "type", "text": "Carla: Hi Rocco. Are you playing with Big Al?\nRocco: No, I'm not. __Are__ you playing with Big Al?\nCarla: No, I'm not! Where __is__ he? What __is__ Big Al doing?\nRocco: I don't know. __Is__ he answering the phone?\nCarla: No, he isn't!\nBig Al: Hi Carla. What __are__ you doing? __Are__ we playing a game?\nCarla: No, Big Al. I'm looking for you. I'm worried.", "image": "@@MEDIA@@gg2/u3/book_carla_big_al.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'order', replace($blk${"words": ["Are", "you", "texting", "a", "friend", "now?"], "sentence": "Are you texting a friend now?", "audio_tts": "Are you texting a friend now?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["Are", "you", "sending", "an", "email", "now?"], "sentence": "Are you sending an email now?", "audio_tts": "Are you sending an email now?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["Is", "your", "friend", "texting", "you", "now?"], "sentence": "Is your friend texting you now?", "audio_tts": "Is your friend texting you now?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'order', replace($blk${"words": ["Is", "Jessica", "doing", "her", "homework", "now?"], "sentence": "Is Jessica doing her homework now?", "audio_tts": "Is Jessica doing her homework now?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'order', replace($blk${"words": ["What", "are", "you", "wearing", "now?"], "sentence": "What are you wearing now?", "audio_tts": "What are you wearing now?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Супер-пупер! Прочитай вопрос и выбери правильный ответ. Are you sending an email? Yes, I ___.", "type": "single", "options": [{"text": "is"}, {"text": "am"}, {"text": "are"}], "correct": [1]}, {"q": "Is he doing his homework? Yes, he ___.", "type": "single", "options": [{"text": "is"}, {"text": "am"}, {"text": "are"}], "correct": [0]}, {"q": "Is she listening to music? No, she ___.", "type": "single", "options": [{"text": "am not"}, {"text": "aren't"}, {"text": "isn't"}], "correct": [2]}, {"q": "Are you having lunch? Yes, we ___.", "type": "single", "options": [{"text": "am"}, {"text": "are"}, {"text": "is"}], "correct": [1]}, {"q": "Are they wearing hats? No, they ___.", "type": "single", "options": [{"text": "aren't"}, {"text": "am not"}, {"text": "isn't"}], "correct": [0]}, {"q": "Am I dreaming? No, you ___.", "type": "single", "options": [{"text": "am not"}, {"text": "isn't"}, {"text": "aren't"}], "correct": [2]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'text', replace($blk${"html": "<p>Смотри, сколько всего ты уже сделал! Первая часть домашней работы позади. А сейчас мы с тобой поговорим об эмоциях 😜</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'match', replace($blk${"title": "Соедини названия эмоций с картинками", "pairs": [{"left_image": "@@MEDIA@@gg2/u3/worried.webp", "right": "worried", "right_audio_tts": "worried"}, {"left_image": "@@MEDIA@@gg2/u3/angry.webp", "right": "angry", "right_audio_tts": "angry"}, {"left_image": "@@MEDIA@@gg2/u3/happy.webp", "right": "happy", "right_audio_tts": "happy"}, {"left_image": "@@MEDIA@@gg2/u3/tired.webp", "right": "tired", "right_audio_tts": "tired"}, {"left_image": "@@MEDIA@@gg2/u3/scared.webp", "right": "scared", "right_audio_tts": "scared"}, {"left_image": "@@MEDIA@@gg2/u3/sad.webp", "right": "sad", "right_audio_tts": "sad"}, {"left_image": "@@MEDIA@@gg2/u3/bored.webp", "right": "bored", "right_audio_tts": "bored"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'task', replace($blk${"title": "Опиши картинку · 1", "needs_review": true, "html": "<p>Молодец! А теперь посмотри на картинки и опиши их. Расскажи про эмоции героев.</p><p><i>Например: They are happy.</i></p><p><img src=\"@@MEDIA@@gg2/u3/cat_tired.webp\" alt=\"\" style=\"max-width:100%;max-height:240px\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13),
('<lesson_id>', 'task', replace($blk${"title": "Опиши картинку · 2", "needs_review": true, "html": "<p>Какие эмоции у героя? Напиши предложение.</p><p><img src=\"@@MEDIA@@gg2/u3/angry_bird.webp\" alt=\"\" style=\"max-width:100%;max-height:240px\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 14),
('<lesson_id>', 'task', replace($blk${"title": "Опиши картинку · 3", "needs_review": true, "html": "<p>Какие эмоции у героя? Напиши предложение.</p><p><img src=\"@@MEDIA@@gg2/u3/scared.webp\" alt=\"\" style=\"max-width:100%;max-height:240px\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 15),
('<lesson_id>', 'task', replace($blk${"title": "Опиши картинку · 4", "needs_review": true, "html": "<p>Какие эмоции у героев? Напиши предложение.</p><p><img src=\"@@MEDIA@@gg2/u3/bored_students.webp\" alt=\"\" style=\"max-width:100%;max-height:240px\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 16),
('<lesson_id>', 'task', replace($blk${"title": "Опиши картинку · 5", "needs_review": true, "html": "<p>Какие эмоции у героини? Напиши предложение.</p><p><img src=\"@@MEDIA@@gg2/u3/worried_woman.webp\" alt=\"\" style=\"max-width:100%;max-height:240px\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 17),
('<lesson_id>', 'text', replace($blk${"html": "<p>Уррра!! Домашняя работа сделана. Для тебя есть ещё дополнительное задание. Ты можешь его не делать, но оно супер интересное. Нужно помочь лягушке 🐸 добраться до берега, отвечая на вопросы.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 18),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "🐸 Попробуй, тебе понравится! ___ you watching TV? — Yes, I am.", "type": "single", "options": [{"text": "Is"}, {"text": "Are"}, {"text": "Am"}], "correct": [1]}, {"q": "🐸 Is your dad cooking dinner? — No, he ___.", "type": "single", "options": [{"text": "isn't"}, {"text": "aren't"}, {"text": "doesn't"}], "correct": [0]}, {"q": "🐸 What ___ they doing? — They're playing football.", "type": "single", "options": [{"text": "is"}, {"text": "do"}, {"text": "are"}], "correct": [2]}, {"q": "🐸 ___ I talking too loudly? — No, you aren't.", "type": "single", "options": [{"text": "Am"}, {"text": "Is"}, {"text": "Are"}], "correct": [0]}, {"q": "🐸 Are your friends chatting online? — Yes, they ___.", "type": "single", "options": [{"text": "is"}, {"text": "are"}, {"text": "do"}], "correct": [1]}, {"q": "🐸 Where ___ Anna going? — To the park.", "type": "single", "options": [{"text": "are"}, {"text": "does"}, {"text": "is"}], "correct": [2]}, {"q": "🐸 Is the cat sleeping? — Yes, it ___.", "type": "single", "options": [{"text": "is"}, {"text": "does"}, {"text": "are"}], "correct": [0]}, {"q": "🐸 Why ___ you running? — Because I'm late!", "type": "single", "options": [{"text": "is"}, {"text": "are"}, {"text": "do"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 19),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_clap.webp\" alt=\"\" style=\"height:200px\"></p><h2>Ты заслуживаешь большой-большой похвалы!</h2><p>Вся твоя домашняя работа сделана. Самое время немножко отдохнуть. Увидимся на занятии 😉</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 20)
returning sort_order, type;
