-- Go Getter 2 · Unit 4 · Our world · Homework 3
-- собрано tools/gg2_build.py --lesson u4_hw3
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 4 · Our world', 4 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 4 · Our world');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 3', 'homework', 60, false, 2
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 4 · Our world'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 3');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 2
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 4 · Our world' and l.title = 'Homework 3';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 4 · Our world' and l.title = 'Homework 3';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_book.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет-привет!</h2><p>В первой части домашнего задания мы выучим слова, которые пригодятся для описания людей или даже животных :) Let’s go 🎉</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'flashcards', replace($blk${"cards": [{"text": "beautiful", "translation": "красивый", "audio_tts": "beautiful", "image": "@@MEDIA@@gg2/u4/beautiful.webp"}, {"text": "fast", "translation": "быстрый", "audio_tts": "fast", "image": "@@MEDIA@@gg2/u4/fast.webp"}, {"text": "friendly", "translation": "дружелюбный", "audio_tts": "friendly", "image": "@@MEDIA@@gg2/u4/friendly.webp"}, {"text": "funny", "translation": "смешной", "audio_tts": "funny", "image": "@@MEDIA@@gg2/u4/funny.webp"}, {"text": "intelligent", "translation": "умный", "audio_tts": "intelligent", "image": "@@MEDIA@@gg2/u4/intelligent.webp"}, {"text": "kind", "translation": "добрый", "audio_tts": "kind", "image": "@@MEDIA@@gg2/u4/kind.webp"}, {"text": "strong", "translation": "сильный", "audio_tts": "strong", "image": "@@MEDIA@@gg2/u4/strong.webp"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'match', replace($blk${"title": "Соедини картинку со словом", "pairs": [{"left_image": "@@MEDIA@@gg2/u4/beautiful.webp", "right": "beautiful", "right_audio_tts": "beautiful"}, {"left_image": "@@MEDIA@@gg2/u4/fast.webp", "right": "fast", "right_audio_tts": "fast"}, {"left_image": "@@MEDIA@@gg2/u4/friendly.webp", "right": "friendly", "right_audio_tts": "friendly"}, {"left_image": "@@MEDIA@@gg2/u4/funny.webp", "right": "funny", "right_audio_tts": "funny"}, {"left_image": "@@MEDIA@@gg2/u4/intelligent.webp", "right": "intelligent", "right_audio_tts": "intelligent"}, {"left_image": "@@MEDIA@@gg2/u4/kind.webp", "right": "kind", "right_audio_tts": "kind"}, {"left_image": "@@MEDIA@@gg2/u4/strong.webp", "right": "strong", "right_audio_tts": "strong"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Как по-английски «красивый»?", "type": "single", "options": [{"text": "beautiful"}, {"text": "funny"}, {"text": "kind"}], "correct": [0]}, {"q": "Как по-английски «быстрый»?", "type": "single", "options": [{"text": "intelligent"}, {"text": "fast"}, {"text": "strong"}], "correct": [1]}, {"q": "Как по-английски «дружелюбный»?", "type": "single", "options": [{"text": "kind"}, {"text": "beautiful"}, {"text": "friendly"}], "correct": [2]}, {"q": "Как по-английски «смешной»?", "type": "single", "options": [{"text": "funny"}, {"text": "strong"}, {"text": "fast"}], "correct": [0]}, {"q": "Как по-английски «умный»?", "type": "single", "options": [{"text": "beautiful"}, {"text": "intelligent"}, {"text": "friendly"}], "correct": [1]}, {"q": "Как по-английски «добрый»?", "type": "single", "options": [{"text": "fast"}, {"text": "funny"}, {"text": "kind"}], "correct": [2]}, {"q": "Как по-английски «сильный»?", "type": "single", "options": [{"text": "strong"}, {"text": "friendly"}, {"text": "intelligent"}], "correct": [0]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Огромный привет!</h3><p>В этой части мы повторим всё, что ты прошёл на уроке с учителем. Это поможет тебе не только всё запомнить, но и использовать :)</p><p>Давай начнём с видео. Посмотри его, а потом сделай задание ниже.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'video', replace($blk${"title": "Посмотри видео", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'text', replace($blk${"html": "<p>Правило-подсказка:</p><p><img src=\"@@MEDIA@@gg2/u4/book_superlative_rule.webp\" alt=\"\" style=\"max-width:100%;max-height:380px;border-radius:12px\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'sort', replace($blk${"title": "Распредели предложения из видео по колонкам. Можешь подсматривать в правило.", "groups": [{"name": "Adjective", "items": [{"text": "This cat is small."}, {"text": "This elephant is big."}, {"text": "This tree is beautiful."}]}, {"name": "Comparative (-er / more)", "items": [{"text": "This cat is smaller."}, {"text": "This elephant is bigger."}, {"text": "This tree is more beautiful."}]}, {"name": "Superlative (-est / most)", "items": [{"text": "This cat is the smallest."}, {"text": "This elephant is the biggest."}, {"text": "This tree is the most beautiful."}]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'gaps', replace($blk${"title": "Посмотри на картинку с животными и подбери правильное слово к каждому.", "mode": "drag", "image": "@@MEDIA@@gg2/u4/book_giraffe_hippo_elephant.webp", "text": "1. The giraffe is __the tallest__.\n2. The hippo is __the smallest__.\n3. The elephant is __the funniest__."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'gaps', replace($blk${"title": "Впиши правильную форму слова из скобок.", "mode": "type", "image": "@@MEDIA@@gg2/u4/book_lion_dog_monkey.webp", "text": "1. The lion is __the most dangerous__ (dangerous).\n2. The dog is __the friendliest|the most friendly__ (friendly).\n3. The monkey is __the most intelligent__ (intelligent)."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'text', replace($blk${"html": "<p>Наши знакомые — Карла, Рокко и Большой Эл — нарисовали картины! Слева картина Рокко, посередине — Большого Эла, справа — Карлы. Посмотри на них, а потом прочитай предложения и выбери правильный вариант.</p><p><img src=\"@@MEDIA@@gg2/u4/three_paintings.webp\" alt=\"\" style=\"max-width:100%;max-height:300px;border-radius:12px\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Rocco’s painting is ___ Big Al’s painting …", "type": "single", "options": [{"text": "the biggest"}, {"text": "bigger than"}], "correct": [1]}, {"q": "… but Carla’s painting is ___ of all.", "type": "single", "options": [{"text": "the biggest"}, {"text": "bigger"}], "correct": [0]}, {"q": "Big Al’s picture and Carla’s picture are ___ Rocco’s picture.", "type": "single", "options": [{"text": "better than"}, {"text": "the best"}], "correct": [0]}, {"q": "His painting isn’t good! I think it is ___.", "type": "single", "options": [{"text": "worse than"}, {"text": "the worst"}], "correct": [1]}, {"q": "I think Big Al is ___ artist of all.", "type": "single", "options": [{"text": "funnier than"}, {"text": "the funniest"}], "correct": [1]}, {"q": "His picture is ___ than Carla’s picture.", "type": "single", "options": [{"text": "more interesting"}, {"text": "the most interesting"}], "correct": [0]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'gaps', replace($blk${"title": "Так держать! Посмотри на этого тигра. Ого! Пока он на нас не смотрит, впиши нужные слова в пропуски.", "mode": "type", "image": "@@MEDIA@@gg2/u4/tiger.webp", "text": "Tigers are bigger __than__ pet cats. They are also __more__ dangerous than pet cats. They eat meat. They are faster __than__ many animals so they can catch them. I think tigers are __the__ __most__ beautiful cats in the world. They’ve got __the__ nicest colours __of__ all the cats. They’ve also got the best faces."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'task', replace($blk${"title": "Напиши свои предложения о животных", "needs_review": true, "html": "<p>Фух, успели — тигр так и не оглянулся :) А теперь непростое задание. Напиши свои предложения о животных. Используй слова ниже и свои идеи.</p><p><i>Пример: nicer than — Giraffes are nicer than monkeys.</i></p><ol><li>smaller than</li><li>more intelligent than</li><li>the funniest</li><li>the most beautiful</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13),
('<lesson_id>', 'text', replace($blk${"html": "<p>Великолепно! Какие классные предложения у тебя получились 👍</p><p><b>Это задание необязательное</b>, но если ты его выполнишь, будешь по-настоящему крут. Помнишь картины Карлы, Рокко и Большого Эла? Нарисуй три картины, будто их нарисовали три разных персонажа.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 14),
('<lesson_id>', 'speaking', replace($blk${"title": "Сравни картины 🎤", "needs_review": true, "html": "<p>А теперь сравни свои картины между собой. Можешь взять за образец предложения про картины Карлы, Рокко и Большого Эла. Нажми на микрофон и расскажи.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 15),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_clap.webp\" alt=\"\" style=\"height:180px\"></p><h3>Спасибо тебе огромное!</h3><p>Ты сегодня здорово потрудился. Твой учитель тобой гордится, и ты тоже можешь собой гордиться. До встречи на занятии ⭐</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 16)
returning sort_order, type;
