-- Go Getter 2 · Unit 7 · Travel · Homework 6
-- собрано tools/gg2_build.py --lesson u7_hw6
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 7 · Travel', 7 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 7 · Travel');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 6', 'homework', 60, false, 5
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 7 · Travel'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 6');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 5
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 7 · Travel' and l.title = 'Homework 6';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 7 · Travel' and l.title = 'Homework 6';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Добро пожаловать! 👋</h2><p>Сегодня мы послушаем интересную аудиозапись, напишем открытку и вспомним транспорт и прошедшее время. Поехали!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'text', replace($blk${"html": "<p>А начнём мы с аудио. Это — Пенни. Послушай её разговор с Дэвидом и выполни задания.</p><p><img src=\"@@MEDIA@@gg2/u7/penny_skateboard.webp\" alt=\"\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'video', replace($blk${"title": "Послушай разговор Пенни и Дэвида 🎧", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Did Penny have a nice holiday?", "type": "single", "options": [{"text": "No, I didn't. It was horrible!"}, {"text": "Yes, I did. It was amazing!"}, {"text": "Yes, I do. It was fun!"}], "correct": [1]}], "title": "Послушай аудио и выбери правильный ответ"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'match', replace($blk${"title": "Послушай аудио ещё раз и соедини вопросы с ответами", "pairs": [{"left": "Where did Penny stay?", "right": "She stayed at a hotel.", "right_audio_tts": "She stayed at a hotel."}, {"left": "What did she do every day?", "right": "She went swimming every day.", "right_audio_tts": "She went swimming every day."}, {"left": "What did she take the photos with?", "right": "She took a lot of photos with her mobile phone.", "right_audio_tts": "She took a lot of photos with her mobile phone."}, {"left": "What did she download her photos to?", "right": "She downloaded photos to her tablet.", "right_audio_tts": "She downloaded photos to her tablet."}, {"left": "What was the weather like?", "right": "It was sunny!", "right_audio_tts": "It was sunny!"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'match', replace($blk${"title": "Вспомни слова из аудио! Соедини картинки с названиями", "pairs": [{"left_image": "@@MEDIA@@gg2/u3/tablet.webp", "right": "tablet", "right_audio_tts": "tablet"}, {"left_image": "@@MEDIA@@gg2/u3/camera.webp", "right": "camera", "right_audio_tts": "camera"}, {"left_image": "@@MEDIA@@gg2/u7/hotel.webp", "right": "hotel", "right_audio_tts": "hotel"}, {"left_image": "@@MEDIA@@gg2/u3/mobile_phone.webp", "right": "mobile phone", "right_audio_tts": "mobile phone"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'text', replace($blk${"html": "<p>Отлично! Теперь напишем открытку. Для начала прочитай открытку Терри для Джоша и заполни пропуски.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'gaps', replace($blk${"title": "Перетащи фразы в пропуски", "mode": "drag", "text": "__Hi__ Josh!\n__We're having a lovely time in__ London. It's cloudy here, but it isn't cold. We're staying in a nice hotel. __There are lots of__ museums and cafés, but the hotel isn't near the big shops. __Yesterday we went to__ the Science Museum and I bought some souvenirs. For dinner we had cheeseburgers and chips and it was great! Today we are at the river. There's a boat here that goes to Tower Bridge. It leaves in 20 minutes! I hope it's fun!\n__Lots of love__,\nTerry"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'task', replace($blk${"title": "Открытка другу ✍️", "html": "<p>Напиши открытку своему другу! О чём ты хотел бы ему рассказать? Постарайся ответить в тексте на вопросы:</p><ol><li>Where are you?</li><li>Where are you staying?</li><li>What's the weather like?</li><li>What did you do/eat/drink yesterday?</li><li>What are you doing today?</li></ol>", "needs_review": true}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Вторая часть</h3><p>Молодец! Первая часть позади. Во второй части закрепим транспорт и прошедшее время. Let's go! 😎</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'match', replace($blk${"title": "Давай вспомним виды транспорта. Соедини картинку со словом", "pairs": [{"left_image": "@@MEDIA@@gg2/u7/car.webp", "right": "car", "right_audio_tts": "car"}, {"left_image": "@@MEDIA@@gg2/u7/bike.webp", "right": "bike", "right_audio_tts": "bike"}, {"left_image": "@@MEDIA@@gg2/u7/lorry.webp", "right": "lorry", "right_audio_tts": "lorry"}, {"left_image": "@@MEDIA@@gg2/u7/train.webp", "right": "train", "right_audio_tts": "train"}, {"left_image": "@@MEDIA@@gg2/u7/bus.webp", "right": "bus", "right_audio_tts": "bus"}, {"left_image": "@@MEDIA@@gg2/u7/plane.webp", "right": "plane", "right_audio_tts": "plane"}, {"left_image": "@@MEDIA@@gg2/u7/boat.webp", "right": "boat", "right_audio_tts": "boat"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'match', replace($blk${"title": "Какие слова мы говорим с транспортом? Соедини глагол с маленьким словом", "pairs": [{"left": "arrive ___ the station", "right": "at", "right_audio_tts": "at"}, {"left": "get ___ the bus (выйти)", "right": "off", "right_audio_tts": "off"}, {"left": "get ___ the train (сесть)", "right": "on", "right_audio_tts": "on"}, {"left": "go to school ___ bus", "right": "by", "right_audio_tts": "by"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'text', replace($blk${"html": "<p>Молодец! Следующее задание — выбери, какие слова пропущены.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Be careful when you get ___.", "type": "single", "options": [{"text": "on foot"}, {"text": "on the boat"}], "correct": [1], "image": "@@MEDIA@@gg2/u7/boat.webp"}, {"q": "I go to school ___.", "type": "single", "options": [{"text": "by car"}, {"text": "by bus"}], "correct": [0], "image": "@@MEDIA@@gg2/u7/car.webp"}, {"q": "Dad always ___ of us on holiday.", "type": "single", "options": [{"text": "takes a taxi"}, {"text": "takes pictures"}], "correct": [1], "image": "@@MEDIA@@gg2/u7/dad_photos.webp"}, {"q": "Terry always goes to work ___.", "type": "single", "options": [{"text": "by bike"}, {"text": "by car"}], "correct": [0], "image": "@@MEDIA@@gg2/u7/bike.webp"}, {"q": "The boy ___ at this stop.", "type": "single", "options": [{"text": "get on the boat"}, {"text": "gets off the bus"}], "correct": [1], "image": "@@MEDIA@@gg2/u7/kids_off_bus.webp"}], "title": "Посмотри на картинку и выбери правильный вариант"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13),
('<lesson_id>', 'gaps', replace($blk${"title": "Вспомним прошедшее время! Напиши подходящие вопросы и ответы. Образец: A: Did you stay in a hotel in London? B: Yes, I did.", "mode": "type", "text": "1) A: __Did he leave|did he leave__ (he / leave) at 9 a.m.? B: Yes, he did.\n2) A: __Did your dad cook|did your dad cook__ (your dad / cook) dinner last night? B: No, he didn't.\n3) A: Did your mum have coffee for breakfast? B: __Yes, she did.|Yes, she did|yes, she did__\n4) A: Did he go to school yesterday? B: __Yes, he did.|Yes, he did|yes, he did__\n5) A: Did they arrive at 3 p.m.? B: __No, they didn't.|No, they didn't|no, they didn't|No, they did not.__"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 14),
('<lesson_id>', 'text', replace($blk${"html": "<p>Молодец! Следующее задание — расставь слова в правильном порядке.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 15),
('<lesson_id>', 'order', replace($blk${"words": ["Did", "you", "go", "to", "school", "by", "bus?"], "sentence": "Did you go to school by bus?", "audio_tts": "Did you go to school by bus?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 16),
('<lesson_id>', 'order', replace($blk${"words": ["I", "didn't", "take", "a", "taxi."], "sentence": "I didn't take a taxi.", "audio_tts": "I didn't take a taxi."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 17),
('<lesson_id>', 'order', replace($blk${"words": ["Did", "they", "arrive", "at", "the", "station", "on", "time?"], "sentence": "Did they arrive at the station on time?", "audio_tts": "Did they arrive at the station on time?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 18),
('<lesson_id>', 'order', replace($blk${"words": ["We", "didn't", "get", "off", "the", "train."], "sentence": "We didn't get off the train.", "audio_tts": "We didn't get off the train."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 19),
('<lesson_id>', 'order', replace($blk${"words": ["Where", "did", "she", "buy", "the", "ticket?"], "sentence": "Where did she buy the ticket?", "audio_tts": "Where did she buy the ticket?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 20),
('<lesson_id>', 'task', replace($blk${"title": "Моя дорога в школу ✍️", "html": "<p>Дополнительное задание для самых смелых! Расскажи, как ты добираешься до школы. Постарайся ответить на вопросы:</p><ul><li>What time do you leave home?</li><li>What transport do you use?</li><li>How long does it take?</li><li>Do you like your journey to school? Why/Why not?</li></ul><p>Не забудь прочитать свой рассказ учителю!</p>", "needs_review": true}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 21),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_star.webp\" alt=\"\" style=\"height:200px\"></p><h2>Ты супер ученик! ⭐</h2><p>Ты справился с домашним заданием — держи звёздочку! До встречи на занятии!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 22)
returning sort_order, type;
