-- Go Getter 2 · Unit 8 · Homework 3
-- собрано tools/gg2_build.py --lesson u8_hw3
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 8', 8 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 8');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 3', 'homework', 60, false, 2
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 8'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 3');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 2
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 8' and l.title = 'Homework 3';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 8' and l.title = 'Homework 3';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_rocket.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет! 👋</h2><p>В этом уроке тебя ждёт интересное видео и классные задания!</p><p>В конце урока есть дополнительное задание — его можно выполнить по желанию, НО если выполнишь, то будешь нереально крут!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'text', replace($blk${"html": "<p>Для начала посмотри видео! Как думаешь, почему Hammy так недоволен?</p><p><img src=\"@@MEDIA@@gg2/u8/book_hammy_angry.webp\" alt=\"\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'video', replace($blk${"title": "Посмотри видео: почему Hammy так недоволен?", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'match', replace($blk${"title": "Посмотри видео ещё раз и соедини вопросы и ответы.", "pairs": [{"left": "Is he asleep?", "right": "Yes, he is.", "right_audio_tts": "Yes, he is."}, {"left": "Can Hammy swim?", "right": "Yes, he can.", "right_audio_tts": "Yes, he can."}, {"left": "Does he like biscuits?", "right": "No, he doesn't.", "right_audio_tts": "No, he doesn't."}, {"left": "Did he exercise this morning?", "right": "No, he didn't.", "right_audio_tts": "No, he didn't."}, {"left": "Do you love your pet?", "right": "Yes, we do!", "right_audio_tts": "Yes, we do!"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'text', replace($blk${"html": "<p>Замечательно! Мы с тобой посмотрели видео, а теперь перейдём к практике!</p><p>Посмотри на предложения ниже. Расставь слова в правильном порядке.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'order', replace($blk${"words": ["Are", "you", "wearing", "my", "clothes?"], "sentence": "Are you wearing my clothes?", "audio_tts": "Are you wearing my clothes?", "image": "@@MEDIA@@gg2/u8/armful_clothes.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["What", "did", "you", "have", "for", "breakfast?"], "sentence": "What did you have for breakfast?", "audio_tts": "What did you have for breakfast?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["Do", "you", "want", "tickets", "for", "a", "concert?"], "sentence": "Do you want tickets for a concert?", "audio_tts": "Do you want tickets for a concert?", "image": "@@MEDIA@@gg2/u8/concert_tickets.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'order', replace($blk${"words": ["Have", "you", "got", "a boyfriend?"], "sentence": "Have you got a boyfriend?", "audio_tts": "Have you got a boyfriend?", "image": "@@MEDIA@@gg2/u8/flowers.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'order', replace($blk${"words": ["Where", "does", "she", "buy", "her", "clothes?"], "sentence": "Where does she buy her clothes?", "audio_tts": "Where does she buy her clothes?", "image": "@@MEDIA@@gg2/u8/shop_window.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'match', replace($blk${"title": "Отлично! Ты хорошо справляешься! Сопоставь вопросы и ответы.", "pairs": [{"left": "What did you have for breakfast?", "right": "I had sausages and eggs.", "right_audio_tts": "I had sausages and eggs."}, {"left": "Where were you last week?", "right": "I was in New York. I played two concerts there.", "right_audio_tts": "I was in New York. I played two concerts there."}, {"left": "Do you live in a big house?", "right": "Yes, I do. It's got seven bedrooms.", "right_audio_tts": "Yes, I do. It's got seven bedrooms."}, {"left": "Can you play the guitar?", "right": "No, I can't. But I can sing and rap.", "right_audio_tts": "No, I can't. But I can sing and rap."}, {"left": "Does your mom like rap music?", "right": "No, she doesn't. She hates it!", "right_audio_tts": "No, she doesn't. She hates it!"}, {"left": "Are you in an ice hotel?", "right": "Yes, I am. It's very nice.", "right_audio_tts": "Yes, I am. It's very nice."}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Types of music 🎵</h3><p>Отлично! А теперь давай поговорим немного о музыке! Какая музыка тебе нравится? Какие виды музыки ты знаешь?</p><p>Посмотри на картинки в упражнении и выбери правильный вариант!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'quiz', replace($blk${"title": "Какая это музыка?", "questions": [{"q": "What type of music is it?", "type": "single", "options": [{"text": "pop"}, {"text": "rock"}, {"text": "jazz"}], "correct": [1], "image": "@@MEDIA@@gg2/u8/rock.webp"}, {"q": "What type of music is it?", "type": "single", "options": [{"text": "pop"}, {"text": "country"}, {"text": "classical"}], "correct": [0], "image": "@@MEDIA@@gg2/u8/pop.webp"}, {"q": "What type of music is it?", "type": "single", "options": [{"text": "rap"}, {"text": "rock"}, {"text": "classical"}], "correct": [2], "image": "@@MEDIA@@gg2/u8/classical.webp"}, {"q": "What type of music is it?", "type": "single", "options": [{"text": "rap"}, {"text": "jazz"}, {"text": "country"}], "correct": [0], "image": "@@MEDIA@@gg2/u8/rap.webp"}, {"q": "What type of music is it?", "type": "single", "options": [{"text": "classical"}, {"text": "jazz"}, {"text": "pop"}], "correct": [1], "image": "@@MEDIA@@gg2/u8/jazz.webp"}, {"q": "What type of music is it?", "type": "single", "options": [{"text": "rock"}, {"text": "rap"}, {"text": "country"}], "correct": [2], "image": "@@MEDIA@@gg2/u8/country.webp"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'task', replace($blk${"title": "Дополнительное задание — для самых больших умников! 🧠", "needs_review": true, "html": "<p>Отлично, ты справился с основной частью домашнего задания! Это задание дополнительное, но ты будешь мегакрутым учеником, если выполнишь его!</p><p>Придумай 3 вопроса для своих одноклассников! Не забудь задать их на уроке!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/congrats_popper.webp\" alt=\"\" style=\"height:180px\"></p><h3>Поздравляю! 🎉</h3><p>Ты завершил домашнее задание, ты замечательный ученик! Увидимся на занятии!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 14)
returning sort_order, type;
