-- Go Getter 2 · Unit 6 · Jobs · Homework 1
-- собрано tools/gg2_build.py --lesson u6_hw1
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 6 · Jobs', 6 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 6 · Jobs');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 1', 'homework', 60, false, 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 6 · Jobs'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 1');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 6 · Jobs' and l.title = 'Homework 1';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 6 · Jobs' and l.title = 'Homework 1';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет! 👋</h2><p>Сейчас мы с тобой выучим различные профессии. Выполни все задания, чтобы выучить слова на 100%!</p><p>Сначала посмотри карточки и послушай, как звучит каждое слово.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'flashcards', replace($blk${"cards": [{"text": "artist", "translation": "художник", "audio_tts": "artist", "image": "@@MEDIA@@gg2/u6/artist.webp"}, {"text": "builder", "translation": "строитель", "audio_tts": "builder", "image": "@@MEDIA@@gg2/u6/builder.webp"}, {"text": "bus driver", "translation": "водитель автобуса", "audio_tts": "bus driver", "image": "@@MEDIA@@gg2/u6/bus_driver.webp"}, {"text": "chef", "translation": "повар", "audio_tts": "chef", "image": "@@MEDIA@@gg2/u6/chef.webp"}, {"text": "doctor", "translation": "врач", "audio_tts": "doctor", "image": "@@MEDIA@@gg2/u6/doctor.webp"}, {"text": "farmer", "translation": "фермер", "audio_tts": "farmer", "image": "@@MEDIA@@gg2/u6/farmer.webp"}, {"text": "footballer", "translation": "футболист", "audio_tts": "footballer", "image": "@@MEDIA@@gg2/u6/footballer.webp"}, {"text": "nurse", "translation": "медсестра", "audio_tts": "nurse", "image": "@@MEDIA@@gg2/u6/nurse.webp"}, {"text": "office worker", "translation": "офисный работник", "audio_tts": "office worker", "image": "@@MEDIA@@gg2/u6/office_worker.webp"}, {"text": "pilot", "translation": "пилот", "audio_tts": "pilot", "image": "@@MEDIA@@gg2/u6/pilot.webp"}, {"text": "police officer", "translation": "полицейский", "audio_tts": "police officer", "image": "@@MEDIA@@gg2/u6/police_officer.webp"}, {"text": "shop assistant", "translation": "продавец", "audio_tts": "shop assistant", "image": "@@MEDIA@@gg2/u6/shop_assistant.webp"}, {"text": "singer", "translation": "певица", "audio_tts": "singer", "image": "@@MEDIA@@gg2/u6/singer.webp"}, {"text": "teacher", "translation": "учитель", "audio_tts": "teacher", "image": "@@MEDIA@@gg2/u6/teacher.webp"}, {"text": "vet", "translation": "ветеринар", "audio_tts": "vet", "image": "@@MEDIA@@gg2/u6/vet.webp"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'quiz', replace($blk${"title": "Выбери правильный перевод", "questions": [{"q": "Как по-английски «художник»?", "type": "single", "options": [{"text": "office worker"}, {"text": "artist"}, {"text": "chef"}, {"text": "pilot"}], "correct": [1]}, {"q": "Как по-английски «строитель»?", "type": "single", "options": [{"text": "teacher"}, {"text": "footballer"}, {"text": "builder"}, {"text": "farmer"}], "correct": [2]}, {"q": "Как по-английски «водитель автобуса»?", "type": "single", "options": [{"text": "teacher"}, {"text": "singer"}, {"text": "artist"}, {"text": "bus driver"}], "correct": [3]}, {"q": "Как по-английски «повар»?", "type": "single", "options": [{"text": "footballer"}, {"text": "vet"}, {"text": "builder"}, {"text": "chef"}], "correct": [3]}, {"q": "Как по-английски «врач»?", "type": "single", "options": [{"text": "office worker"}, {"text": "footballer"}, {"text": "doctor"}, {"text": "bus driver"}], "correct": [2]}, {"q": "Как по-английски «фермер»?", "type": "single", "options": [{"text": "farmer"}, {"text": "shop assistant"}, {"text": "artist"}, {"text": "pilot"}], "correct": [0]}, {"q": "Как по-английски «футболист»?", "type": "single", "options": [{"text": "footballer"}, {"text": "shop assistant"}, {"text": "bus driver"}, {"text": "farmer"}], "correct": [0]}, {"q": "Как по-английски «медсестра»?", "type": "single", "options": [{"text": "footballer"}, {"text": "nurse"}, {"text": "teacher"}, {"text": "bus driver"}], "correct": [1]}, {"q": "Как по-английски «офисный работник»?", "type": "single", "options": [{"text": "singer"}, {"text": "footballer"}, {"text": "office worker"}, {"text": "doctor"}], "correct": [2]}, {"q": "Как по-английски «пилот»?", "type": "single", "options": [{"text": "singer"}, {"text": "farmer"}, {"text": "pilot"}, {"text": "nurse"}], "correct": [2]}, {"q": "Как по-английски «полицейский»?", "type": "single", "options": [{"text": "pilot"}, {"text": "police officer"}, {"text": "farmer"}, {"text": "shop assistant"}], "correct": [1]}, {"q": "Как по-английски «продавец»?", "type": "single", "options": [{"text": "teacher"}, {"text": "singer"}, {"text": "shop assistant"}, {"text": "pilot"}], "correct": [2]}, {"q": "Как по-английски «певица»?", "type": "single", "options": [{"text": "footballer"}, {"text": "singer"}, {"text": "vet"}, {"text": "chef"}], "correct": [1]}, {"q": "Как по-английски «учитель»?", "type": "single", "options": [{"text": "bus driver"}, {"text": "artist"}, {"text": "teacher"}, {"text": "office worker"}], "correct": [2]}, {"q": "Как по-английски «ветеринар»?", "type": "single", "options": [{"text": "nurse"}, {"text": "artist"}, {"text": "office worker"}, {"text": "vet"}], "correct": [3]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'exact_input', replace($blk${"title": "Напиши слово по-английски", "items": [{"prompt": "Напиши по-английски: врач", "accept": ["doctor", "Doctor"], "audio_tts": "doctor", "image": "@@MEDIA@@gg2/u6/doctor.webp"}, {"prompt": "Напиши по-английски: повар", "accept": ["chef", "Chef"], "audio_tts": "chef", "image": "@@MEDIA@@gg2/u6/chef.webp"}, {"prompt": "Напиши по-английски: водитель автобуса", "accept": ["bus driver", "Bus driver"], "audio_tts": "bus driver", "image": "@@MEDIA@@gg2/u6/bus_driver.webp"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_rocket.webp\" alt=\"\" style=\"height:180px\"></p><h3>А теперь — задания! 💪</h3><p>Сейчас мы закрепим знания, полученные на уроке. У тебя всё обязательно получится!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'match', replace($blk${"title": "Итак, первое задание! Посмотри внимательно на картинки и соедини названия профессий с подходящими картинками. Удачи!", "pairs": [{"left_image": "@@MEDIA@@gg2/u6/shop_assistant.webp", "right": "shop assistant", "right_audio_tts": "shop assistant"}, {"left_image": "@@MEDIA@@gg2/u6/builder.webp", "right": "builder", "right_audio_tts": "builder"}, {"left_image": "@@MEDIA@@gg2/u6/bus_driver.webp", "right": "bus driver", "right_audio_tts": "bus driver"}, {"left_image": "@@MEDIA@@gg2/u6/office_worker.webp", "right": "office worker", "right_audio_tts": "office worker"}, {"left_image": "@@MEDIA@@gg2/u6/chef.webp", "right": "chef", "right_audio_tts": "chef"}, {"left_image": "@@MEDIA@@gg2/u6/police_officer.webp", "right": "police officer", "right_audio_tts": "police officer"}, {"left_image": "@@MEDIA@@gg2/u6/vet.webp", "right": "vet", "right_audio_tts": "vet"}, {"left_image": "@@MEDIA@@gg2/u6/artist.webp", "right": "artist", "right_audio_tts": "artist"}, {"left_image": "@@MEDIA@@gg2/u6/singer.webp", "right": "singer", "right_audio_tts": "singer"}, {"left_image": "@@MEDIA@@gg2/u6/farmer.webp", "right": "farmer", "right_audio_tts": "farmer"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'quiz', replace($blk${"title": "Прочитай предложения и выбери правильный вариант ответа по смыслу", "questions": [{"q": "I sing in a band. I'm a…", "type": "single", "options": [{"text": "singer"}, {"text": "office worker"}], "correct": [0]}, {"q": "I sit at a desk and work on a computer. I'm an…", "type": "single", "options": [{"text": "bus driver"}, {"text": "office worker"}], "correct": [1]}, {"q": "I build houses and flats. I'm a…", "type": "single", "options": [{"text": "pilot"}, {"text": "builder"}], "correct": [1]}, {"q": "I drive around town and take people to different places. I'm a…", "type": "single", "options": [{"text": "bus driver"}, {"text": "footballer"}], "correct": [0]}, {"q": "I fly planes and take people to other countries. I'm a…", "type": "single", "options": [{"text": "artist"}, {"text": "pilot"}], "correct": [1]}, {"q": "I play a popular sport and I score goals. I'm a…", "type": "single", "options": [{"text": "footballer"}, {"text": "farmer"}], "correct": [0]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'gaps', replace($blk${"title": "Внимательно прочитай текст и заполни пропуски подходящими словами. Слово chef уже вписано — это пример.", "mode": "drag", "text": "Hi, I'm Mark and this is my family. You can see me with my dad on the left. Dad loves cooking but he isn't a chef. He works at the hospital, but he isn't a doctor. He's a __nurse__. Mum works at my sister's school. She's a French __teacher__. My grandpa and grandma work too. Grandma is a great __artist__ and she paints beautiful pictures. She sells them in a shop. Grandpa works in her shop – he's her __shop assistant__. I like animals and when I grow up I want to be a __vet__ so I can look after people's pets."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'task', replace($blk${"title": "Дополнительное задание — для самых крутых учеников! ⭐", "needs_review": true, "html": "<p>Заполни табличку про себя и расскажи, кем ты хочешь стать и почему.</p><p><b>What do you want to be? Why?</b></p><ul><li>jobs I like: ___, ___</li><li>jobs I don't like: ___, ___</li><li>jobs I like a lot: ___, ___</li><li>I want to be ___ because ___.</li></ul><p><i>For example: I want to be a vet because I like animals.</i></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_clap.webp\" alt=\"\" style=\"height:180px\"></p><h3>Классная работа! 🖐</h3><p>Я тебя поздравляю — домашняя работа выполнена очень здорово. До встречи на занятии!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9)
returning sort_order, type;
