-- Go Getter 2 · Unit 4 · Our world · Homework 7
-- собрано tools/gg2_build.py --lesson u4_hw7
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 4 · Our world', 4 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 4 · Our world');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 7', 'homework', 60, false, 6
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 4 · Our world'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 7');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 6
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 4 · Our world' and l.title = 'Homework 7';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 4 · Our world' and l.title = 'Homework 7';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_rocket.webp\" alt=\"\" style=\"height:200px\"></p><h2>Hello, dear student!</h2><p>Представляешь, ты уже заканчиваешь четвёртый юнит! В этой домашней работе тебя ждёт повторение того, что ты прошёл. Ты наверняка всё отлично помнишь. Let’s go 🚀</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'text', replace($blk${"html": "<p>Посмотри на картинку и выбери, что на ней изображено.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "What is it?", "type": "single", "options": [{"text": "sea"}, {"text": "river"}, {"text": "beach"}], "correct": [0], "image": "@@MEDIA@@gg2/u4/sea.webp"}, {"q": "What is it?", "type": "single", "options": [{"text": "city"}, {"text": "forest"}, {"text": "grass"}], "correct": [1], "image": "@@MEDIA@@gg2/u4/forest.webp"}, {"q": "What is it?", "type": "single", "options": [{"text": "island"}, {"text": "volcano"}, {"text": "mountain"}], "correct": [1], "image": "@@MEDIA@@gg2/u4/volcano.webp"}, {"q": "What is it?", "type": "single", "options": [{"text": "waterfall"}, {"text": "river"}, {"text": "desert"}], "correct": [2], "image": "@@MEDIA@@gg2/u4/desert.webp"}, {"q": "What is it?", "type": "single", "options": [{"text": "town"}, {"text": "mountain"}, {"text": "forest"}], "correct": [1], "image": "@@MEDIA@@gg2/u4/mountain.webp"}, {"q": "What is it?", "type": "single", "options": [{"text": "lake"}, {"text": "beach"}, {"text": "volcano"}], "correct": [0], "image": "@@MEDIA@@gg2/u4/lake.webp"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'gaps', replace($blk${"title": "Отлично! Теперь поработаем со словами. Прочитай предложения и вставь нужные слова.", "mode": "drag", "text": "1. Geography trips aren’t boring. They’re __exciting__.\n2. Be careful. That dog isn’t __friendly__.\n3. I can’t do my homework. It’s __difficult__.\n4. He is a __fast__ runner.\n5. I can’t buy this watch because it’s very __expensive__.\n6. My bike isn’t dangerous. It’s __safe__."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'gaps', replace($blk${"title": "Прочитай предложения и впиши нужную форму слова из скобок.", "mode": "type", "text": "1. My feet are __bigger than__ (big) your feet!\n2. This test is __easier than__ (easy) the last test.\n3. I think it’s __more difficult than__ (difficult) the last test!\n4. My brother is __better than__ (good) me at Maths!\n5. This car is __more expensive than__ (expensive) that one.\n6. Today is __hotter than__ (hot) yesterday."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'text', replace($blk${"html": "<p>В этом задании ты точно мастер! Составь из слов предложения.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["This", "is", "the", "highest", "mountain", "in", "my", "country."], "sentence": "This is the highest mountain in my country.", "audio_tts": "This is the highest mountain in my country.", "image": "@@MEDIA@@gg2/u4/book_mountain_cartoon.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["This", "pizza", "is", "the", "cheapest", "meal."], "sentence": "This pizza is the cheapest meal.", "audio_tts": "This pizza is the cheapest meal.", "image": "@@MEDIA@@gg2/u4/book_pizza.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'order', replace($blk${"words": ["This", "is", "the", "best", "holiday", "of", "all."], "sentence": "This is the best holiday of all.", "audio_tts": "This is the best holiday of all.", "image": "@@MEDIA@@gg2/u4/beach.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'order', replace($blk${"words": ["This", "is", "the", "worst", "ice", "cream."], "sentence": "This is the worst ice cream.", "audio_tts": "This is the worst ice cream.", "image": "@@MEDIA@@gg2/u4/book_icecream.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'order', replace($blk${"words": ["My", "sister", "is", "the", "most", "beautiful", "person", "in", "my", "family."], "sentence": "My sister is the most beautiful person in my family.", "audio_tts": "My sister is the most beautiful person in my family."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'order', replace($blk${"words": ["You", "are", "the", "most", "intelligent", "student", "in", "my", "class."], "sentence": "You are the most intelligent student in my class.", "audio_tts": "You are the most intelligent student in my class.", "image": "@@MEDIA@@gg2/u4/intelligent.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'text', replace($blk${"html": "<p>Супер! Давай прочитаем разговор Лукаса и Эми (это герои видео, которое ты смотришь с учителем на уроке). Выбери правильный вариант для каждого пропуска :)</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Lucas: ___ your favourite film?", "type": "single", "options": [{"text": "What"}, {"text": "What’s"}], "correct": [1]}, {"q": "Amy: My ___ Frozen.", "type": "single", "options": [{"text": "favourite film is"}, {"text": "favourite is"}], "correct": [0]}, {"q": "Amy: What ___ you?", "type": "single", "options": [{"text": "do"}, {"text": "about"}], "correct": [1]}, {"q": "Lucas: I like Shrek. What do you ___ of going to the cinema?", "type": "single", "options": [{"text": "think"}, {"text": "thinking"}], "correct": [0]}, {"q": "Amy: ___ my opinion, it’s great.", "type": "single", "options": [{"text": "On"}, {"text": "In"}], "correct": [1]}, {"q": "Lucas: You’re ___. Going to the cinema is great.", "type": "single", "options": [{"text": "right"}, {"text": "true"}], "correct": [0]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13),
('<lesson_id>', 'text', replace($blk${"html": "<p>Первая часть домашнего задания позади! Дальше тебя ждут интересные задания о спорте и отдыхе на природе. А ты любишь спорт? ⚽ 🚴 ⚾</p><p>Посмотри на картинки и выбери правильный вариант.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 14),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "I like big ___.", "type": "single", "options": [{"text": "islands"}, {"text": "cities"}, {"text": "mountains"}], "correct": [1], "image": "@@MEDIA@@gg2/u4/city.webp"}, {"q": "I like activities on the ___.", "type": "single", "options": [{"text": "river"}, {"text": "sea"}, {"text": "beach"}], "correct": [0], "image": "@@MEDIA@@gg2/u4/kayak_river.webp"}, {"q": "We always ride bikes in the ___.", "type": "single", "options": [{"text": "city"}, {"text": "volcano"}, {"text": "forest"}], "correct": [2], "image": "@@MEDIA@@gg2/u4/bike_forest.webp"}, {"q": "I love activities on the ___.", "type": "single", "options": [{"text": "town"}, {"text": "lake"}, {"text": "desert"}], "correct": [1], "image": "@@MEDIA@@gg2/u4/boat_lake.webp"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 15),
('<lesson_id>', 'gaps', replace($blk${"title": "Прочитай текст про каникулы в городе и вставь пропущенные буквы — по одной в каждый пропуск.", "mode": "type", "image": "@@MEDIA@@gg2/u4/book_city_park.webp", "text": "I like city holidays. Cities are not b__o__r__i__ng at all. They are exc__i__t__i__ng places. They are sometimes exp__e__ns__i__v__e__, so you need money. But you can find ch__e____a__p places to eat burgers and pizzas. In many cities there are b__e____a____u__t__i__f__u__l parks. Some cities are d__a__ng__e__r__o____u__s because there are lots of f__a__st cars. But most cities have got buses, so it is __e____a__sy to get to places. People are usually fr__i____e__ndly and k__i__nd to tourists."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 16),
('<lesson_id>', 'match', replace($blk${"title": "Соедини название вида спорта с картинкой.", "pairs": [{"left_image": "@@MEDIA@@gg2/u4/kayaking.webp", "right": "kayaking", "right_audio_tts": "kayaking"}, {"left_image": "@@MEDIA@@gg2/u4/climbing.webp", "right": "climbing", "right_audio_tts": "climbing"}, {"left_image": "@@MEDIA@@gg2/u4/parachute.webp", "right": "jumping with a parachute", "right_audio_tts": "jumping with a parachute"}, {"left_image": "@@MEDIA@@gg2/u4/sailing.webp", "right": "sailing", "right_audio_tts": "sailing"}, {"left_image": "@@MEDIA@@gg2/u4/fishing.webp", "right": "fishing", "right_audio_tts": "fishing"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 17),
('<lesson_id>', 'task', replace($blk${"title": "Необязательное задание: мой любимый спорт", "needs_review": true, "html": "<p>Оно необязательное, но будет очень здорово, если ты его сделаешь. Нарисуй картинку со своим любимым видом спорта. Покажи её учителю на уроке и расскажи о ней. Можешь написать здесь, что ты нарисовал.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 18),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_laptop.webp\" alt=\"\" style=\"height:180px\"></p><h3>Привет! Это вторая часть домашней работы :)</h3><p>И она последняя в этом юните. Здесь ты узнаешь кое-что об интересных технологиях и прочитаешь объявления. Прочитай три очень познавательные истории о технологиях, а потом сделаем по ним задания 😊</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 19),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@gg2/u4/book_kitchen_robot.webp\" alt=\"\" style=\"max-width:100%;max-height:240px;border-radius:12px\"></p><p>Micky Bailey’s parents have got a … robot! They’re very excited about it. It’s a kitchen robot and it makes dinner for Micky’s family every day. It’s very good at cooking! Micky’s mum and dad are really happy. Now they don’t need to cook dinner so now they’ve got more time. All they need to do is go shopping!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 20),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@gg2/u4/book_dog_attila.webp\" alt=\"\" style=\"max-width:100%;max-height:240px;border-radius:12px\"></p><p>David Smith’s new puppy, Attila, is friendly and intelligent. David is worried about Attila because he sometimes gets lost. Like all dogs in the UK, Attila has got a microchip so the police know his name and address. The microchip isn’t new technology but it’s David’s favourite!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 21),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@gg2/u4/dan_laptop.webp\" alt=\"\" style=\"max-width:100%;max-height:240px;border-radius:12px\"></p><p>Suzie Highton’s brother Dan can’t see very well. He can’t see text in books. The most important technology in Suzie’s house is a computer program. Dan can download books onto his computer. The text is big so he can see it and the computer reads it aloud too.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 22),
('<lesson_id>', 'gaps', replace($blk${"title": "Ты огромный молодец! Впиши одно или два слова в каждый пропуск. Пример: Micky’s parents are very excited about their new robot.", "mode": "type", "text": "1. The robot is __good at__ cooking.\n2. Attila is David’s __dog|puppy__.\n3. David is __worried about__ Attila because he sometimes gets lost.\n4. David’s favourite technology is Attila’s __microchip__.\n5. Suzie Highton’s brother can’t __see__ very well.\n6. Dan can see text on his computer because it’s __big__."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 23),
('<lesson_id>', 'gaps', replace($blk${"title": "Посмотри на картинку и допиши предложения.", "mode": "type", "image": "@@MEDIA@@gg2/u4/book_river_scene.webp", "text": "1. The boy with the tablet feels __scared__.\n2. The dog is playing __in the river|in the water__.\n3. The blue boat is bigger __than the red boat|than the red one__.\n4. The yellow boat is __the biggest|the biggest boat|the biggest one__."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 24),
('<lesson_id>', 'task', replace($blk${"title": "Ответь на вопросы по картинке", "needs_review": true, "html": "<p>Задание усложняется! Теперь нужно не просто дописать слова, а ответить на вопросы по той же картинке. Ты точно-точно справишься 💪</p><p><img src=\"@@MEDIA@@gg2/u4/book_river_scene.webp\" alt=\"\" style=\"max-width:100%;max-height:300px;border-radius:12px\"></p><ol><li>What is the girl doing?</li><li>What’s the girl wearing?</li><li>What’s the woman wearing?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 25),
('<lesson_id>', 'text', replace($blk${"html": "<p>Первая часть этой домашней работы позади. Теперь осталось совсем немножко!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 26),
('<lesson_id>', 'task', replace($blk${"title": "Прочитай объявления и ответь на вопросы", "needs_review": true, "html": "<p><img src=\"@@MEDIA@@gg2/u4/book_game_ads.webp\" alt=\"\" style=\"max-width:100%;max-height:300px;border-radius:12px\"></p><p><i>Даты выхода игр (на картинке мелко): Shark City — August 2017, Volcano Disaster! — March 2015, Desert Adventure — September 2017.</i></p><ol><li>What’s the shark doing?</li><li>What’s the girl doing?</li><li>Which game is the most expensive?</li><li>Is Desert Adventure more difficult than Volcano Disaster?</li><li>Which is the newest game?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 27),
('<lesson_id>', 'gaps', replace($blk${"title": "Послушай разговор Софи и папы и вставь пропущенные слова. Пример: Sophie is doing her Geography homework.", "mode": "drag", "audio": "", "text": "1. Studying: mountains, lakes and __waterfalls__\n2. Ben Nevis, Scotland: the __highest__ __mountain__ in the UK\n3. Windermere: __17__ kilometres long\n4. Volcanoes: sometimes __very__ __dangerous__"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 28),
('<lesson_id>', 'text', replace($blk${"html": "<p>И-и-и — последнее задание на сегодня! Прочитай диалоги и выбери самый подходящий ответ.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 29),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Ben: Are you busy? May: …", "type": "single", "options": [{"text": "No, I’m doing my homework."}, {"text": "Yes, it’s busy."}, {"text": "Yes, I’m downloading music."}], "correct": [2]}, {"q": "Ben: Let’s go to the cinema! May: …", "type": "single", "options": [{"text": "OK. Tickets are cheap today."}, {"text": "You’re right, it’s boring."}, {"text": "OK. It’s on TV."}], "correct": [0]}, {"q": "Ben: What do you think of Star Trek? May: …", "type": "single", "options": [{"text": "I’m worried about it."}, {"text": "I think it’s amazing!"}, {"text": "Well done!"}], "correct": [1]}, {"q": "Ben: What time is the film? May: …", "type": "single", "options": [{"text": "We can walk."}, {"text": "It’s at 5 p.m."}, {"text": "Yes, it is."}], "correct": [1]}, {"q": "Ben: Let’s meet at my house. May: …", "type": "single", "options": [{"text": "I like your house."}, {"text": "What’s my address?"}, {"text": "OK, see you later."}], "correct": [2]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 30),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_trophy.webp\" alt=\"\" style=\"height:180px\"></p><h3>Великолепная работа!</h3><p>Поздравляю тебя с окончанием большой-пребольшой темы! Ты отлично потрудился и узнал много нового о технологиях, научился сравнивать предметы и интересоваться мнением других. Твой учитель очень-очень гордится тобой! Увидимся на занятии 😎</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 31)
returning sort_order, type;
