-- Go Getter 2 · Unit 1 · School · Unit 1 Test
-- собрано tools/gg2_build.py --lesson u1_test
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 1 · School', 1 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 1 · School');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Unit 1 Test', 'test', 90, false, 7
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 1 · School'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Unit 1 Test');
update classroom_lessons l set kind = 'test', pass_threshold = 90, sort_order = 7
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 1 · School' and l.title = 'Unit 1 Test';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 1 · School' and l.title = 'Unit 1 Test';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/good_luck_clover.webp\" alt=\"\" style=\"height:180px\"></p><h2>Тест Unit 1 📝</h2><p>Пора проверить, как ты запомнил школьные предметы, принадлежности и Present Simple. Чтобы пройти тест, нужно набрать 90 баллов. Читай задания внимательно. Удачи!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'exact_input', replace($blk${"title": "Напиши слова по-английски", "items": [{"prompt": "1. Напиши по-английски: калькулятор", "image": "@@MEDIA@@gg2/u1/calculator.webp", "accept": ["calculator", "calculator"], "audio_tts": "calculator"}, {"prompt": "2. Напиши по-английски: словарь", "image": "@@MEDIA@@gg2/u1/dictionary.webp", "accept": ["dictionary", "dictionary"], "audio_tts": "dictionary"}, {"prompt": "3. Напиши по-английски: ножницы", "image": "@@MEDIA@@gg2/u1/scissors.webp", "accept": ["scissors", "scissors"], "audio_tts": "scissors"}, {"prompt": "4. Напиши по-английски: география", "image": "@@MEDIA@@gg2/u1/subj_geography.webp", "accept": ["Geography", "geography"], "audio_tts": "Geography"}, {"prompt": "5. Напиши по-английски: история", "image": "@@MEDIA@@gg2/u1/subj_history.webp", "accept": ["History", "history"], "audio_tts": "History"}, {"prompt": "6. Напиши по-английски: естественные науки", "image": "@@MEDIA@@gg2/u1/subj_science.webp", "accept": ["Science", "science"], "audio_tts": "Science"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'quiz', replace($blk${"title": "Выбери правильный вариант, чтобы предложение было грамматически верным", "questions": [{"q": "1. Sarah ___ tennis on Saturdays.", "type": "single", "options": [{"text": "always plays"}, {"text": "plays always"}, {"text": "always play"}], "correct": [0]}, {"q": "2. Tom ___ Polish, but he speaks Russian.", "type": "single", "options": [{"text": "don't speak"}, {"text": "doesn't speak"}, {"text": "doesn't speaks"}], "correct": [1]}, {"q": "3. My sister ___ English and French at school.", "type": "single", "options": [{"text": "studys"}, {"text": "study"}, {"text": "studies"}], "correct": [2]}, {"q": "4. — ___ judo or karate? — I do judo.", "type": "single", "options": [{"text": "Are you do"}, {"text": "Do you do"}, {"text": "Does you do"}], "correct": [1]}, {"q": "5. We ___ in the canteen at half past twelve.", "type": "single", "options": [{"text": "have usually lunch"}, {"text": "has usually lunch"}, {"text": "usually have lunch"}], "correct": [2]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'gaps', replace($blk${"title": "Поставь глагол в скобках в правильную форму Present Simple", "mode": "type", "text": "1. Mark __plays__ (play) basketball on Wednesdays.\n2. My mum __teaches__ (teach) Geography at our school.\n3. Anna __studies__ (study) Maths every evening.\n4. We __don't go|don’t go|do not go__ (not go) to school on Sunday.\n5. — Does Liam __do__ (do) karate? — Yes, he does."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Расставь части предложения в правильном порядке</h3><p>В следующих пяти заданиях собери предложения из частей.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'order', replace($blk${"words": ["We", "always", "play", "chess", "at the weekend."], "sentence": "We always play chess at the weekend.", "audio_tts": "We always play chess at the weekend."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["My", "brother", "doesn't", "like", "Music", "at school."], "sentence": "My brother doesn't like Music at school.", "audio_tts": "My brother doesn't like Music at school."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["Does", "Sarah", "ride", "her bike", "to school?"], "sentence": "Does Sarah ride her bike to school?", "audio_tts": "Does Sarah ride her bike to school?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'order', replace($blk${"words": ["Tom", "sometimes", "forgets", "his", "pencil case."], "sentence": "Tom sometimes forgets his pencil case.", "audio_tts": "Tom sometimes forgets his pencil case."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'order', replace($blk${"words": ["They", "never", "have", "P.E.", "on Friday morning."], "sentence": "They never have P.E. on Friday morning.", "audio_tts": "They never have P.E. on Friday morning."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'text', replace($blk${"html": "<h3>READING</h3><p>Прочитай текст и реши, верны ли утверждения (True), неверны (False) или об этом в тексте не сказано (Not stated).</p><h3>Daniel's School Week</h3><p>Hi! I'm Daniel and I'm twelve. I go to school in Bristol, in the UK. I've got six lessons every day, but my favourite day is Wednesday because I have Art and P.E.!</p><p>I always take my pencil case, ruler and calculator to school. I sometimes forget my dictionary, but my friend Liam usually helps me – he's a really helpful boy.</p><p>We have lunch in the canteen at half past twelve. The food is normally quite good. After school, on Mondays and Thursdays, I do judo at the sports centre. I never play computer games on weekdays because my mum doesn't let me. At the weekend I often play chess with my dad. He usually wins!</p><p>My sister Emma loves Music. She plays the guitar and the piano.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'quiz', replace($blk${"title": "True, False или Not stated?", "questions": [{"q": "1. Daniel has six lessons every day.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [0]}, {"q": "2. Wednesday is his favourite day because of Art and P.E.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [0]}, {"q": "3. Daniel always remembers all his school things.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [1]}, {"q": "4. Daniel and Liam are in the same class.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [2]}, {"q": "5. Daniel has lunch at half past twelve.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [0]}, {"q": "6. Daniel does judo three times a week.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [1]}, {"q": "7. Daniel can play computer games on Saturday.", "type": "single", "options": [{"text": "True"}, {"text": "False"}, {"text": "Not stated"}], "correct": [0]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'sequence', replace($blk${"title": "Послушай рассказ Софии о её вторнике. Расставь события в том порядке, в котором она о них говорит", "audio": "", "items": [{"text": "Sophia gets up at seven o’clock."}, {"text": "Sophia's mum drives her to school."}, {"text": "Sophia has Computer Studies."}, {"text": "Sophia goes to the canteen with Emma."}, {"text": "Sophia plays tennis with the school team."}, {"text": "Sophia goes to the library to do her homework."}, {"text": "Sophia has dinner with her family."}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING I 🎤", "needs_review": true, "image": "@@MEDIA@@gg2/u1/scene_canteen.webp", "html": "<p>Опиши картинку и ответь на вопросы-помощники. Нажми на микрофон и запиши ответ.</p><ol><li>Where are the students?</li><li>How many students can you see?</li><li>What food and drink can you see on the table?</li><li>Are the students friendly?</li><li>Where do you have lunch: at home, in the canteen or in the classroom?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING II 🎤", "needs_review": true, "html": "<p>Ответь на вопросы полными предложениями. Нажми на микрофон и запиши ответ.</p><ol><li>What's your favourite subject at school?</li><li>Which subject don't you like? Why?</li><li>How many lessons do you have on Mondays?</li><li>What do you always have in your pencil case?</li><li>Do you have a laptop or a tablet for school?</li><li>How often do you do your homework – always, usually, sometimes or never?</li><li>What do you usually do on Friday evenings?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 14),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_trophy.webp\" alt=\"\" style=\"height:180px\"></p><h3>Тест завершён! 🎉</h3><p>Ты молодец! Unit 1 пройден — увидимся на занятии.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 15)
returning sort_order, type;
