-- Go Getter 2 · Unit 2 · Homework 6
-- собрано tools/gg2_build.py --lesson u2_hw6
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 2', 2 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 2');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 6', 'homework', 60, false, 5
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 2'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 6');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 5
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 2' and l.title = 'Homework 6';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 2' and l.title = 'Homework 6';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_headphones.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет! 👋</h2><p>Добро пожаловать в домашнее задание! Сегодня мы прослушаем интересную аудиозапись и напишем электронное письмо (e-mail). Поехали!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'text', replace($blk${"html": "<h3>А начнём мы с аудио 🎧</h3><p>Это Пенни. Прослушай её диалог с папой и выполни задания под аудио.</p><p><img src=\"@@MEDIA@@gg2/u2/penny_breakfast.webp\" alt=\"Penny and her dad\" style=\"max-width:100%;max-height:320px\"></p>", "audio": ""}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Прослушай аудио и выбери, что Пенни будет на завтрак. Верных ответов несколько.", "type": "multiple", "options": [{"text": "an egg"}, {"text": "some bread and ham"}, {"text": "some orange juice"}, {"text": "a glass of milk"}, {"text": "some sugar"}, {"text": "some cereal"}], "correct": [0, 1, 3]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "Прослушай аудио ещё раз. Penny has P.E. ___.", "type": "single", "options": [{"text": "after lunch"}, {"text": "in the morning"}], "correct": [1]}, {"q": "She ___ for breakfast.", "type": "single", "options": [{"text": "doesn't want any cereal"}, {"text": "wants some cereal"}], "correct": [0]}, {"q": "She wants a ___ sandwich.", "type": "single", "options": [{"text": "cheese"}, {"text": "ham"}], "correct": [1]}, {"q": "She can have a glass of ___.", "type": "single", "options": [{"text": "juice"}, {"text": "water"}, {"text": "milk"}], "correct": [2]}, {"q": "She would like to have ___.", "type": "single", "options": [{"text": "an egg"}, {"text": "two eggs"}], "correct": [0]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'sequence', replace($blk${"title": "Вспомни диалог и расставь реплики в правильном порядке (не подглядывая)", "items": [{"text": "Good morning, Penny."}, {"text": "What would you like for breakfast?"}, {"text": "How about some cereal?"}, {"text": "I don't want any cereal."}, {"text": "How about a sandwich?"}, {"text": "Yes, please."}, {"text": "Would you like anything to drink?"}, {"text": "Is there any orange juice in the fridge?"}, {"text": "Ok. Milk is fine."}, {"text": "Can I have an egg too, please, dad?"}, {"text": "Yes, I can make one for you."}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Письмо Стива ✉️</h3><p>Отлично! Ты справился с первой частью заданий. Я обещала тебе, что мы напишем электронное письмо сегодня. Для начала прочти письмо Стива и выбери слово для каждого пропуска: <b>because</b> или <b>so</b>.</p><p><b>From:</b> Steve<br><b>Subject:</b> What would you like to eat?</p><p>Hi! I'm very happy (1) ___ you are coming to stay at my house this weekend. Mum wants to do the shopping (2) ___ she wants to know what food you like. For breakfast I usually have milk and cereal (3) ___ it is quick and easy. I also drink apple juice (4) ___ it is my favourite. What would you like? We can go to the beach on Saturday (5) ___ let's take a picnic lunch. What would you like for lunch? I love chicken and chips. Can we have that for dinner? Do you like chicken and chips too?</p><p>Bye for now!<br>Steve</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'quiz', replace($blk${"questions": [{"q": "(1) I'm very happy ___ you are coming to stay at my house this weekend.", "type": "single", "options": [{"text": "so"}, {"text": "because"}], "correct": [1]}, {"q": "(2) Mum wants to do the shopping ___ she wants to know what food you like.", "type": "single", "options": [{"text": "so"}, {"text": "because"}], "correct": [0]}, {"q": "(3) For breakfast I usually have milk and cereal ___ it is quick and easy.", "type": "single", "options": [{"text": "because"}, {"text": "so"}], "correct": [0]}, {"q": "(4) I also drink apple juice ___ it is my favourite.", "type": "single", "options": [{"text": "so"}, {"text": "because"}], "correct": [1]}, {"q": "(5) We can go to the beach on Saturday ___ let's take a picnic lunch.", "type": "single", "options": [{"text": "because"}, {"text": "so"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'task', replace($blk${"title": "Ответь на письмо Стива", "needs_review": true, "html": "<p>Ура! Ты справился почти со всеми заданиями. Это — последнее! Письменно ответь на письмо Стива: расскажи ему, что ты любишь на завтрак, обед и ужин. С началом письма я тебе помогу:</p><p><i>From: Your name<br>Subject: My favourite food.<br>Hi, Steve!<br>I'm very happy, too.<br>For breakfast …</i></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_star.webp\" alt=\"\" style=\"height:180px\"></p><h3>Молодец!</h3><p>Ты сделал всё-всё домашнее задание. Увидимся на занятии ⭐</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8)
returning sort_order, type;
