-- Go Getter 2 · Unit 8 · Celebrations · Homework 2
-- собрано tools/gg2_build.py --lesson u8_hw2
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 8 · Celebrations', 8 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 8 · Celebrations');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 2', 'homework', 60, false, 1
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 8 · Celebrations'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 2');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 1
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 8 · Celebrations' and l.title = 'Homework 2';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 8 · Celebrations' and l.title = 'Homework 2';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Добро пожаловать! 👋</h2><p>Сегодня мы с тобой научимся рассказывать о своих планах на будущее.</p><p>В конце тебя будет ждать дополнительное задание. Если ты его сделаешь, получишь звание чемпиона английского 💪</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'text', replace($blk${"html": "<p>Для начала посмотри видео. Что собирается делать Hammy на каникулах?</p><p><img src=\"@@MEDIA@@gg2/u8/book_hammy_holiday.webp\" alt=\"\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'video', replace($blk${"title": "Посмотри видео: что собирается делать Hammy на каникулах?", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'quiz', replace($blk${"title": "Посмотри видео ещё раз и выбери правильный вариант для каждого пропуска", "questions": [{"q": "What ___ you going to do on holidays?", "type": "single", "options": [{"text": "is"}, {"text": "are"}], "correct": [1]}, {"q": "I ___ swim in the sea.", "type": "single", "options": [{"text": "am going to"}, {"text": "is going to"}], "correct": [0]}, {"q": "I ___ to eat lots of food.", "type": "single", "options": [{"text": "likes"}, {"text": "am going"}], "correct": [1]}, {"q": "My dad ___ drive to France.", "type": "single", "options": [{"text": "is going to"}, {"text": "am going to"}], "correct": [0]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'text', replace($blk${"html": "<p>Отлично, ты посмотрел видео и выполнил задание, а теперь переходим к практике!</p><p>Расставь слова в правильном порядке, чтобы получилось предложение.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'order', replace($blk${"words": ["We", "are", "not", "going", "to", "see", "our", "grandmother", "this", "summer."], "sentence": "We are not going to see our grandmother this summer.", "audio_tts": "We are not going to see our grandmother this summer.", "image": "@@MEDIA@@gg2/u8/grandma_cottage.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["Are", "you", "going", "to", "come", "to", "my", "party", "tomorrow?"], "sentence": "Are you going to come to my party tomorrow?", "audio_tts": "Are you going to come to my party tomorrow?", "image": "@@MEDIA@@gg2/u8/birthday_party.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["I", "am", "going", "to", "go", "to", "Japan", "to", "see", "sakura."], "sentence": "I am going to go to Japan to see sakura.", "audio_tts": "I am going to go to Japan to see sakura.", "image": "@@MEDIA@@gg2/u8/sakura.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'order', replace($blk${"words": ["She", "is", "going", "to", "do", "her", "homework", "in the evening."], "sentence": "She is going to do her homework in the evening.", "audio_tts": "She is going to do her homework in the evening.", "image": "@@MEDIA@@gg2/u8/homework_girl.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'text', replace($blk${"html": "<p>Молодец! Ты справился с большей частью заданий. Давай ещё немного потренируемся!</p><p>Посмотри на картинки и выбери правильный вариант ответа!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'quiz', replace($blk${"title": "Выбери правильный вариант ответа", "questions": [{"q": "We ___ going to paint our bedroom tomorrow.", "type": "single", "options": [{"text": "aren't"}, {"text": "isn't"}, {"text": "am not"}], "correct": [0], "image": "@@MEDIA@@gg2/u8/paint_bedroom.webp"}, {"q": "I ___ going to go on holiday next week.", "type": "single", "options": [{"text": "is"}, {"text": "are"}, {"text": "am"}], "correct": [2], "image": "@@MEDIA@@gg2/u8/beach_holiday.webp"}, {"q": "She is ___ to the cinema tonight.", "type": "single", "options": [{"text": "going to"}, {"text": "going"}, {"text": "go to"}], "correct": [1], "image": "@@MEDIA@@gg2/u8/cinema_tonight.webp"}, {"q": "He's going to ___ the book.", "type": "single", "options": [{"text": "reading"}, {"text": "read"}], "correct": [1], "image": "@@MEDIA@@gg2/u8/boy_reading.webp"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'match', replace($blk${"title": "Ты большой молодец! Осталось ещё пару заданий! Внимательно прочитай слова и найди продолжения предложений.", "pairs": [{"left": "I'm going to buy tickets to the", "right": "cinema tomorrow.", "right_audio_tts": "cinema tomorrow."}, {"left": "Are you going to come to my birthday", "right": "party next week?", "right_audio_tts": "party next week?"}, {"left": "My favourite singer is going to", "right": "sing at the concert this Friday.", "right_audio_tts": "sing at the concert this Friday."}, {"left": "I am going to wear a vampire costume", "right": "for a fancy dress party this Saturday.", "right_audio_tts": "for a fancy dress party this Saturday."}, {"left": "My best friend Kate is going to come to my house", "right": "for a sleepover this weekend.", "right_audio_tts": "for a sleepover this weekend."}, {"left": "They are going to take part in a", "right": "dance show at school next month.", "right_audio_tts": "dance show at school next month."}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'task', replace($blk${"title": "Дополнительное задание — для самых смелых! 💪", "needs_review": true, "html": "<p>Мне очень интересно, что ты и твоя семья планируете делать на каникулах. Письменно напиши 3 предложения о себе и 3 предложения о членах семьи.</p><p><i>Например: I am going to swim in the sea. My grandma is going to play golf.</i></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_trophy.webp\" alt=\"\" style=\"height:180px\"></p><h3>Ура! 🎉</h3><p>Ты справился с домашней работой. Ты — большой молодец! Увидимся на занятии!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13),
('<lesson_id>', 'text', replace($blk${"html": "<h3>Бонус: числа и даты 📅</h3><p>Выучи порядковые числительные и даты — они пригодятся, чтобы рассказать, когда у тебя праздник. Послушай каждую карточку и повтори вслух.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 14),
('<lesson_id>', 'flashcards', replace($blk${"cards": [{"text": "the first", "translation": "первый", "audio_tts": "the first"}, {"text": "the second", "translation": "второй", "audio_tts": "the second"}, {"text": "the third", "translation": "третий", "audio_tts": "the third"}, {"text": "the fourth", "translation": "четвёртый", "audio_tts": "the fourth"}, {"text": "the fifth", "translation": "пятый", "audio_tts": "the fifth"}, {"text": "the sixth", "translation": "шестой", "audio_tts": "the sixth"}, {"text": "the seventh", "translation": "седьмой", "audio_tts": "the seventh"}, {"text": "the eighth", "translation": "восьмой", "audio_tts": "the eighth"}, {"text": "the ninth", "translation": "девятый", "audio_tts": "the ninth"}, {"text": "the tenth", "translation": "десятый", "audio_tts": "the tenth"}, {"text": "the eleventh", "translation": "одиннадцатый", "audio_tts": "the eleventh"}, {"text": "the twelfth", "translation": "двенадцатый", "audio_tts": "the twelfth"}, {"text": "the thirteenth", "translation": "тринадцатый", "audio_tts": "the thirteenth"}, {"text": "the twentieth", "translation": "двадцатый", "audio_tts": "the twentieth"}, {"text": "the thirtieth", "translation": "тридцатый", "audio_tts": "the thirtieth"}, {"text": "the twenty-first", "translation": "двадцать первый", "audio_tts": "the twenty-first"}, {"text": "the forty-second", "translation": "сорок второй", "audio_tts": "the forty-second"}, {"text": "the first of September", "translation": "первое сентября", "audio_tts": "the first of September"}, {"text": "the second of April", "translation": "второе апреля", "audio_tts": "the second of April"}, {"text": "the thirty-first of December", "translation": "тридцать первое декабря", "audio_tts": "the thirty-first of December"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 15),
('<lesson_id>', 'match', replace($blk${"title": "Соедини числа с их названиями", "pairs": [{"left": "1st", "right": "the first", "right_audio_tts": "the first"}, {"left": "2nd", "right": "the second", "right_audio_tts": "the second"}, {"left": "3rd", "right": "the third", "right_audio_tts": "the third"}, {"left": "5th", "right": "the fifth", "right_audio_tts": "the fifth"}, {"left": "8th", "right": "the eighth", "right_audio_tts": "the eighth"}, {"left": "12th", "right": "the twelfth", "right_audio_tts": "the twelfth"}, {"left": "20th", "right": "the twentieth", "right_audio_tts": "the twentieth"}, {"left": "21st", "right": "the twenty-first", "right_audio_tts": "the twenty-first"}, {"left": "30th", "right": "the thirtieth", "right_audio_tts": "the thirtieth"}, {"left": "42nd", "right": "the forty-second", "right_audio_tts": "the forty-second"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 16),
('<lesson_id>', 'quiz', replace($blk${"title": "Выбери, как сказать дату по-английски", "questions": [{"q": "1 сентября", "type": "single", "options": [{"text": "the first of September"}, {"text": "the one of September"}, {"text": "the first September of"}], "correct": [0]}, {"q": "2 апреля", "type": "single", "options": [{"text": "the two of April"}, {"text": "the second April"}, {"text": "the second of April"}], "correct": [2]}, {"q": "31 декабря", "type": "single", "options": [{"text": "the thirty-one of December"}, {"text": "the thirty-first of December"}, {"text": "the thirtieth of December"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 17)
returning sort_order, type;
