-- Go Getter 2 · Unit 5 · My town · Homework 1
-- собрано tools/gg2_build.py --lesson u5_hw1
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 5 · My town', 5 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 5 · My town');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 1', 'homework', 60, false, 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 5 · My town'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 1');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 5 · My town' and l.title = 'Homework 1';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 5 · My town' and l.title = 'Homework 1';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет! 👋</h2><p>Сегодня тебя ждёт изучение новых слов. Ты повторишь названия разных мест, куда можно пойти в городе. Давай начинать 😉</p><p>Не забудь: после слов тебя ждёт ещё одна часть домашнего задания — с упражнениями!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'flashcards', replace($blk${"cards": [{"text": "bank", "translation": "банк", "audio_tts": "bank", "image": "@@MEDIA@@gg2/u5/bank.webp"}, {"text": "café", "translation": "кафе", "audio_tts": "cafe", "image": "@@MEDIA@@gg2/u5/cafe.webp"}, {"text": "cinema", "translation": "кинотеатр", "audio_tts": "cinema", "image": "@@MEDIA@@gg2/u5/cinema.webp"}, {"text": "hotel", "translation": "отель", "audio_tts": "hotel", "image": "@@MEDIA@@gg2/u5/hotel.webp"}, {"text": "hospital", "translation": "больница", "audio_tts": "hospital", "image": "@@MEDIA@@gg2/u5/hospital.webp"}, {"text": "library", "translation": "библиотека", "audio_tts": "library", "image": "@@MEDIA@@gg2/u5/library.webp"}, {"text": "park", "translation": "парк", "audio_tts": "park", "image": "@@MEDIA@@gg2/u5/park.webp"}, {"text": "museum", "translation": "музей", "audio_tts": "museum", "image": "@@MEDIA@@gg2/u5/museum.webp"}, {"text": "restaurant", "translation": "ресторан", "audio_tts": "restaurant", "image": "@@MEDIA@@gg2/u5/restaurant.webp"}, {"text": "supermarket", "translation": "супермаркет", "audio_tts": "supermarket", "image": "@@MEDIA@@gg2/u5/supermarket.webp"}, {"text": "shop", "translation": "магазин", "audio_tts": "shop", "image": "@@MEDIA@@gg2/u5/clothes_shop.webp"}, {"text": "stadium", "translation": "стадион", "audio_tts": "stadium", "image": "@@MEDIA@@gg2/u5/stadium.webp"}, {"text": "theatre", "translation": "театр", "audio_tts": "theatre", "image": "@@MEDIA@@gg2/u5/theatre.webp"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'match', replace($blk${"title": "Соедини картинку со словом", "pairs": [{"left_image": "@@MEDIA@@gg2/u5/bank.webp", "right": "bank", "right_audio_tts": "bank"}, {"left_image": "@@MEDIA@@gg2/u5/cafe.webp", "right": "café", "right_audio_tts": "cafe"}, {"left_image": "@@MEDIA@@gg2/u5/cinema.webp", "right": "cinema", "right_audio_tts": "cinema"}, {"left_image": "@@MEDIA@@gg2/u5/hotel.webp", "right": "hotel", "right_audio_tts": "hotel"}, {"left_image": "@@MEDIA@@gg2/u5/hospital.webp", "right": "hospital", "right_audio_tts": "hospital"}, {"left_image": "@@MEDIA@@gg2/u5/library.webp", "right": "library", "right_audio_tts": "library"}, {"left_image": "@@MEDIA@@gg2/u5/park.webp", "right": "park", "right_audio_tts": "park"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'match', replace($blk${"title": "И ещё шесть мест — соедини картинку со словом", "pairs": [{"left_image": "@@MEDIA@@gg2/u5/museum.webp", "right": "museum", "right_audio_tts": "museum"}, {"left_image": "@@MEDIA@@gg2/u5/restaurant.webp", "right": "restaurant", "right_audio_tts": "restaurant"}, {"left_image": "@@MEDIA@@gg2/u5/supermarket.webp", "right": "supermarket", "right_audio_tts": "supermarket"}, {"left_image": "@@MEDIA@@gg2/u5/clothes_shop.webp", "right": "shop", "right_audio_tts": "shop"}, {"left_image": "@@MEDIA@@gg2/u5/stadium.webp", "right": "stadium", "right_audio_tts": "stadium"}, {"left_image": "@@MEDIA@@gg2/u5/theatre.webp", "right": "theatre", "right_audio_tts": "theatre"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'quiz', replace($blk${"title": "Выбери правильное слово", "questions": [{"q": "Как по-английски «банк»?", "type": "single", "options": [{"text": "bank"}, {"text": "hotel"}, {"text": "museum"}], "correct": [0]}, {"q": "Как по-английски «кафе»?", "type": "single", "options": [{"text": "hospital"}, {"text": "café"}, {"text": "restaurant"}], "correct": [1]}, {"q": "Как по-английски «кинотеатр»?", "type": "single", "options": [{"text": "library"}, {"text": "supermarket"}, {"text": "cinema"}], "correct": [2]}, {"q": "Как по-английски «отель»?", "type": "single", "options": [{"text": "hotel"}, {"text": "park"}, {"text": "shop"}], "correct": [0]}, {"q": "Как по-английски «больница»?", "type": "single", "options": [{"text": "museum"}, {"text": "hospital"}, {"text": "stadium"}], "correct": [1]}, {"q": "Как по-английски «библиотека»?", "type": "single", "options": [{"text": "restaurant"}, {"text": "theatre"}, {"text": "library"}], "correct": [2]}, {"q": "Как по-английски «парк»?", "type": "single", "options": [{"text": "park"}, {"text": "supermarket"}, {"text": "bank"}], "correct": [0]}, {"q": "Как по-английски «музей»?", "type": "single", "options": [{"text": "shop"}, {"text": "museum"}, {"text": "café"}], "correct": [1]}, {"q": "Как по-английски «ресторан»?", "type": "single", "options": [{"text": "stadium"}, {"text": "cinema"}, {"text": "restaurant"}], "correct": [2]}, {"q": "Как по-английски «супермаркет»?", "type": "single", "options": [{"text": "supermarket"}, {"text": "theatre"}, {"text": "hotel"}], "correct": [0]}, {"q": "Как по-английски «магазин»?", "type": "single", "options": [{"text": "bank"}, {"text": "shop"}, {"text": "hospital"}], "correct": [1]}, {"q": "Как по-английски «стадион»?", "type": "single", "options": [{"text": "café"}, {"text": "library"}, {"text": "stadium"}], "correct": [2]}, {"q": "Как по-английски «театр»?", "type": "single", "options": [{"text": "theatre"}, {"text": "cinema"}, {"text": "park"}], "correct": [0]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_highfive.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет-привет, самый старательный ученик!</h2><p>В этой части домашнего задания мы закрепим всё, что выучили. Для этого нужно сделать несколько упражнений. Время пролетит незаметно. Вперёд 😄</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'hotspot', replace($blk${"title": "Внимательно посмотри на картинку и соедини названия мест с правильными домиками. Удачи!", "mode": "label", "image": "@@MEDIA@@gg2/u5/book_street.webp", "points": [{"x": 4.7, "y": 18.7, "text": "restaurant", "audio_tts": "restaurant"}, {"x": 26.1, "y": 18.7, "text": "cinema", "audio_tts": "cinema"}, {"x": 42.0, "y": 18.7, "text": "supermarket", "audio_tts": "supermarket"}, {"x": 57.8, "y": 18.7, "text": "hotel", "audio_tts": "hotel"}, {"x": 73.3, "y": 18.7, "text": "café", "audio_tts": "cafe"}, {"x": 87.8, "y": 18.7, "text": "hospital", "audio_tts": "hospital"}], "extras": []}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'quiz', replace($blk${"title": "Ты великолепно справился! Прочитай предложения и выбери правильный вариант по смыслу", "questions": [{"q": "I want to get some eggs and flour from the ___.", "type": "single", "options": [{"text": "café"}, {"text": "supermarket"}], "correct": [1]}, {"q": "Let's go to the ___ to get some money.", "type": "single", "options": [{"text": "bank"}, {"text": "cinema"}], "correct": [0]}, {"q": "This is a nice ___. I love the clothes they sell.", "type": "single", "options": [{"text": "library"}, {"text": "shop"}], "correct": [1]}, {"q": "Who wants to see an Egyptian mummy at the ___?", "type": "single", "options": [{"text": "museum"}, {"text": "hotel"}], "correct": [0]}, {"q": "There's a football match on Saturday at the ___.", "type": "single", "options": [{"text": "theatre"}, {"text": "stadium"}], "correct": [1]}, {"q": "Can we have a picnic in the ___, please, Mum?", "type": "single", "options": [{"text": "park"}, {"text": "hospital"}], "correct": [0]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'match', replace($blk${"title": "Супер! А теперь вспомним предлоги места. Где собачка? Соедини картинку с предлогом", "pairs": [{"left_image": "@@MEDIA@@gg2/u5/book_dog_1.webp", "right": "between", "right_audio_tts": "between"}, {"left_image": "@@MEDIA@@gg2/u5/book_dog_2.webp", "right": "next to", "right_audio_tts": "next to"}, {"left_image": "@@MEDIA@@gg2/u5/book_dog_3.webp", "right": "opposite", "right_audio_tts": "opposite"}, {"left_image": "@@MEDIA@@gg2/u5/book_dog_4.webp", "right": "in front of", "right_audio_tts": "in front of"}, {"left_image": "@@MEDIA@@gg2/u5/book_dog_5.webp", "right": "behind", "right_audio_tts": "behind"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'gaps', replace($blk${"title": "Ты просто супер! Внимательно посмотри на карту и заполни пропуски подходящими словами", "mode": "drag", "image": "@@MEDIA@@gg2/u5/book_map_north_south.webp", "text": "A: Where's the café? I'd like a cup of coffee.\nB: It's __next to__ my favourite clothes shop in North Street. But I haven't got any money, so let's go to the bank first. It's __between__ the library and the Italian restaurant.\nA: I know, it's near the hotel in South Street. There is a lovely garden __in front of__ the hotel and there is a park __behind__ it.\nB: Yes. The supermarket is __opposite__ the café, so we can get some food for a picnic ...\nA: ... and have lunch in the park. Good idea!"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'task', replace($blk${"title": "Дополнительное задание — для самых крутых учеников! ⭐", "needs_review": true, "html": "<p>Посмотри внимательно на карту и опиши её. Напиши 2–3 предложения.</p><p><i>Например: The swimming pool is behind the restaurant.</i></p><p><img src=\"@@MEDIA@@gg2/u5/book_town_map.webp\" alt=\"Карта города\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_star.webp\" alt=\"\" style=\"height:180px\"></p><h3>Bye-bye! 👋</h3><p>Ты отлично поработал. До встречи на уроке!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11)
returning sort_order, type;
