-- Go Getter 2 · Unit 8 · Homework 6
-- собрано tools/gg2_build.py --lesson u8_hw6
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 8', 8 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 8');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Homework 6', 'homework', 60, false, 5
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 8'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Homework 6');
update classroom_lessons l set kind = 'homework', pass_threshold = 60, sort_order = 5
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 8' and l.title = 'Homework 6';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 8' and l.title = 'Homework 6';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_headphones.webp\" alt=\"\" style=\"height:200px\"></p><h2>Hello! 👋</h2><p>Сегодня мы с тобой попрактикуемся в чтении и аудировании! Тебя ждёт много интересных заданий! Готов начать?</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'video', replace($blk${"title": "Послушай аудиозапись: как ребята собираются провести дни рождения? Чей праздник тебе понравился больше всего?", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'match', replace($blk${"title": "Послушай аудиозапись ещё раз и соедини имена ребят с событиями!", "pairs": [{"left": "Tina", "right": "see a dance show", "right_audio_tts": "see a dance show"}, {"left": "Harry", "right": "go to the cinema", "right_audio_tts": "go to the cinema"}, {"left": "Robert", "right": "birthday party at home", "right_audio_tts": "birthday party at home"}, {"left": "Kelly", "right": "go bowling", "right_audio_tts": "go bowling"}, {"left": "David", "right": "eat at a restaurant", "right_audio_tts": "eat at a restaurant"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'gaps', replace($blk${"title": "Послушай аудиозапись ещё раз и расставь слова по смыслу", "mode": "drag", "text": "1. Tina has a ticket for her __sister__.\n2. Harry is going to go out with his __brother__.\n3. Robert's __mum__ is making a cake.\n4. Kelly and her __uncle__ love the same activity.\n5. David is going to go out with his __dad__."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'text', replace($blk${"html": "<p>SUPER! Ты справился с аудированием! У меня для тебя есть приглашение на вечеринку, но оно незаполненное! Прочитай его в следующем задании и вставь пропущенные слова.</p><p><img src=\"@@MEDIA@@gg2/u8/invitation.webp\" alt=\"\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'gaps', replace($blk${"title": "Прочитай приглашение и вставь пропущенные слова по смыслу", "mode": "drag", "text": "PARTY INVITATION\nOn: Tuesday, 3rd __August__, at 4:30 __p.m.__\n__At__: Fun Times Sport Centre\nWe're going to go swimming and then eat pancakes.\n__Please__ bring towels for the swimming.\nYour parents can __collect__ you from Patty's Pancakes at 9 o'clock.\nPlease __reply__ to 678954321."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'quiz', replace($blk${"title": "Прочитай приглашение ещё раз и ответь на вопросы", "questions": [{"q": "What day is the party going to happen?", "type": "single", "options": [{"text": "Wednesday"}, {"text": "Tuesday"}, {"text": "Friday"}], "correct": [1]}, {"q": "Where is the party going to happen?", "type": "single", "options": [{"text": "At Fun Times Sport Centre"}, {"text": "At Swimming pool"}, {"text": "At School"}], "correct": [0]}, {"q": "What are they going to do first?", "type": "single", "options": [{"text": "play football"}, {"text": "play basketball"}, {"text": "go swimming"}], "correct": [2]}, {"q": "What do they need to bring?", "type": "single", "options": [{"text": "boots"}, {"text": "towels"}, {"text": "hats"}], "correct": [1]}, {"q": "What are they going to eat?", "type": "single", "options": [{"text": "salads"}, {"text": "fruits"}, {"text": "pancakes"}], "correct": [2]}, {"q": "What time is the party going to finish?", "type": "single", "options": [{"text": "at 9 o'clock"}, {"text": "at 6 o'clock"}, {"text": "at 10 o'clock"}], "correct": [0]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'text', replace($blk${"html": "<p>Ты большой молодец! У меня для тебя есть дополнительное задание! Оно необязательное, но если ты его выполнишь, ты будешь МЕГА КРУТ!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'task', replace($blk${"title": "Дополнительное задание: твоё приглашение 💌", "needs_review": true, "html": "<p>Подумай, куда бы ты хотел пригласить друзей! Напиши своё приглашение! Используй вопросы из предыдущего задания — они помогут тебе составить приглашение.</p><p>Не забудь показать своё приглашение учителю на уроке!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_clap.webp\" alt=\"\" style=\"height:180px\"></p><h3>Ура! 🎉</h3><p>Ты справился с первой частью домашнего задания! Ты — мегакрут! А теперь — повторение перед тестом.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_laptop.webp\" alt=\"\" style=\"height:200px\"></p><h2>Hello! 👋</h2><p>Сегодня мы будем повторять изученный материал, чтобы ты смог хорошо подготовиться к тесту :) Давай начнём!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'match', replace($blk${"title": "Посмотри на картинки и соедини их с названиями!", "pairs": [{"left_image": "@@MEDIA@@gg2/u8/barbecue.webp", "right": "barbecue", "right_audio_tts": "barbecue"}, {"left_image": "@@MEDIA@@gg2/u8/birthday_party.webp", "right": "birthday party", "right_audio_tts": "birthday party"}, {"left_image": "@@MEDIA@@gg2/u8/concert.webp", "right": "concert", "right_audio_tts": "concert"}, {"left_image": "@@MEDIA@@gg2/u8/dance_show.webp", "right": "dance show", "right_audio_tts": "dance show"}, {"left_image": "@@MEDIA@@gg2/u8/football_match.webp", "right": "football match", "right_audio_tts": "football match"}, {"left_image": "@@MEDIA@@gg2/u8/fancy_dress.webp", "right": "fancy dress party", "right_audio_tts": "fancy dress party"}, {"left_image": "@@MEDIA@@gg2/u8/picnic.webp", "right": "picnic", "right_audio_tts": "picnic"}, {"left_image": "@@MEDIA@@gg2/u8/play.webp", "right": "play", "right_audio_tts": "play"}, {"left_image": "@@MEDIA@@gg2/u8/sleepover.webp", "right": "sleepover", "right_audio_tts": "sleepover"}, {"left_image": "@@MEDIA@@gg2/u8/talent_competition.webp", "right": "talent competition", "right_audio_tts": "talent competition"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'text', replace($blk${"html": "<p>Отлично! Давай ещё потренируемся! Соедини цифры и их названия ниже!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'match', replace($blk${"title": "Соедини цифры и их названия", "pairs": [{"left": "24th", "right": "twenty-fourth", "right_audio_tts": "twenty-fourth"}, {"left": "1st", "right": "first", "right_audio_tts": "first"}, {"left": "2nd", "right": "second", "right_audio_tts": "second"}, {"left": "3rd", "right": "third", "right_audio_tts": "third"}, {"left": "7th", "right": "seventh", "right_audio_tts": "seventh"}, {"left": "6th", "right": "sixth", "right_audio_tts": "sixth"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13),
('<lesson_id>', 'text', replace($blk${"html": "<p>Ты отлично справляешься! А теперь давай повторим грамматику! Внимательно посмотри на слова и расставь их в правильном порядке!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 14),
('<lesson_id>', 'order', replace($blk${"words": ["I", "am", "going", "to", "visit", "my", "grandpa", "on", "Monday."], "sentence": "I am going to visit my grandpa on Monday.", "audio_tts": "I am going to visit my grandpa on Monday."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 15),
('<lesson_id>', 'order', replace($blk${"words": ["We", "are", "going", "to", "have", "a", "party", "on", "Saturday."], "sentence": "We are going to have a party on Saturday.", "audio_tts": "We are going to have a party on Saturday."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 16),
('<lesson_id>', 'order', replace($blk${"words": ["He", "is", "going", "to", "travel", "by", "plane."], "sentence": "He is going to travel by plane.", "audio_tts": "He is going to travel by plane."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 17),
('<lesson_id>', 'order', replace($blk${"words": ["They", "are", "not", "going", "to", "play", "football", "next", "week."], "sentence": "They are not going to play football next week.", "audio_tts": "They are not going to play football next week."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 18),
('<lesson_id>', 'text', replace($blk${"html": "<p>МОЛОДЕЦ! А сейчас мы с тобой вспомним вопросы! Внимательно прочитай слова и расставь их по порядку!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 19),
('<lesson_id>', 'order', replace($blk${"words": ["Is", "he", "asleep?"], "sentence": "Is he asleep?", "audio_tts": "Is he asleep?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 20),
('<lesson_id>', 'order', replace($blk${"words": ["Can", "Hammy", "swim?"], "sentence": "Can Hammy swim?", "audio_tts": "Can Hammy swim?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 21),
('<lesson_id>', 'order', replace($blk${"words": ["Does", "he", "like", "biscuits?"], "sentence": "Does he like biscuits?", "audio_tts": "Does he like biscuits?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 22),
('<lesson_id>', 'order', replace($blk${"words": ["Did", "he", "exercise", "this", "morning?"], "sentence": "Did he exercise this morning?", "audio_tts": "Did he exercise this morning?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 23),
('<lesson_id>', 'order', replace($blk${"words": ["Do", "you", "love", "your", "pet?"], "sentence": "Do you love your pet?", "audio_tts": "Do you love your pet?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 24),
('<lesson_id>', 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_star.webp\" alt=\"\" style=\"height:180px\"></p><h3>Hooray! 🌟</h3><p>Домашняя работа выполнена на отлично, всё благодаря твоим стараниям. Теперь ты готов к тесту на 100%! Увидимся на занятии!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 25)
returning sort_order, type;
