-- Go Getter 2 · Unit 8 · Celebrations · Unit 8 Test
-- собрано tools/gg2_build.py --lesson u8_test
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 8 · Celebrations', 8 from classroom_courses c
where c.slug = 'gg2'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 8 · Celebrations');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Unit 8 Test', 'test', 90, false, 6
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 8 · Celebrations'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Unit 8 Test');
update classroom_lessons l set kind = 'test', pass_threshold = 90, sort_order = 6
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg2' and u.title = 'Unit 8 · Celebrations' and l.title = 'Unit 8 Test';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg2' and u.title = 'Unit 8 · Celebrations' and l.title = 'Unit 8 Test';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'exact_input', replace($blk${"items": [{"prompt": "Напиши по-английски: барбекю", "accept": ["barbecue"], "audio_tts": "barbecue"}, {"prompt": "Напиши по-английски: танцевальное шоу", "accept": ["dance show"], "audio_tts": "dance show"}, {"prompt": "Напиши по-английски: костюмированная вечеринка", "accept": ["fancy dress party"], "audio_tts": "fancy dress party"}, {"prompt": "Напиши по-английски: пикник", "accept": ["picnic"], "audio_tts": "picnic"}, {"prompt": "Напиши по-английски: ночёвка", "accept": ["sleepover"], "audio_tts": "sleepover"}, {"prompt": "Напиши по-английски: конкурс талантов", "accept": ["talent competition"], "audio_tts": "talent competition"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'quiz', replace($blk${"title": "Выбери правильный вариант, чтобы предложение было грамматически верным", "questions": [{"q": "We ___ to have a barbecue on Saturday.", "type": "single", "options": [{"text": "going to have"}, {"text": "are going"}, {"text": "going"}], "correct": [1]}, {"q": "My sister ___ to the concert with us.", "type": "single", "options": [{"text": "not going to come"}, {"text": "doesn't going to come"}, {"text": "isn't going to come"}], "correct": [2]}, {"q": "___ invite Tom to your party?", "type": "single", "options": [{"text": "Do you going to"}, {"text": "You are going to"}, {"text": "Are you going to"}], "correct": [2]}, {"q": "___ going to wear to the fancy dress party?", "type": "single", "options": [{"text": "What is Anna"}, {"text": "What does Anna"}, {"text": "What Anna is"}], "correct": [0]}, {"q": "___ last weekend?", "type": "single", "options": [{"text": "Where you went"}, {"text": "Where did you go"}, {"text": "Where did you went"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'gaps', replace($blk${"title": "Поставь глагол в скобках в правильную форму с be going to", "mode": "type", "text": "1. On the twenty-first of June, we __are going to celebrate|'re going to celebrate|’re going to celebrate__ (celebrate) my dad's birthday.\n2. They __aren't going to watch|are not going to watch|aren’t going to watch|'re not going to watch__ (not watch) the football match — they hate football.\n3. __Is__ Liam __going to play__ (play) at the talent competition?\n4. I __am going to have|'m going to have|’m going to have__ (have) a sleepover with my best friend on Friday.\n5. What __are you going to do__ (do) on the thirty-first of December?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'text', replace($blk${"html": "<p>Расставь части предложения в правильном порядке.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'order', replace($blk${"words": ["We", "are", "going", "to have", "a picnic", "in the park."], "sentence": "We are going to have a picnic in the park.", "audio_tts": "We are going to have a picnic in the park."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'order', replace($blk${"words": ["Are", "you", "going", "to wear", "a costume", "to the fancy", "dress party?"], "sentence": "Are you going to wear a costume to the fancy dress party?", "audio_tts": "Are you going to wear a costume to the fancy dress party?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["My", "birthday", "is", "on", "the twelfth", "of May."], "sentence": "My birthday is on the twelfth of May.", "audio_tts": "My birthday is on the twelfth of May."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["They", "aren't", "going", "to listen", "to classical", "music", "tonight."], "sentence": "They aren't going to listen to classical music tonight.", "audio_tts": "They aren't going to listen to classical music tonight."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'order', replace($blk${"words": ["What", "time", "are", "we", "going", "to meet", "on Sunday?"], "sentence": "What time are we going to meet on Sunday?", "audio_tts": "What time are we going to meet on Sunday?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'text', replace($blk${"html": "<h3>READING 📖</h3><p>Прочитай приглашение Маркуса и сообщения. Потом перетащи слова в пропуски в предложениях.</p><h4>Markus's Invitation</h4><p><b>Please come to my 13th birthday party!</b><br><b>When:</b> Saturday, the seventh of June, at 4 p.m.<br><b>Where:</b> 25 Park Road<br><b>Theme:</b> Fancy dress – favourite singer or band!<br><b>RSVP</b> by Wednesday.</p><h4>Messages between Markus and his friends</h4><p><b>Anna:</b> Hi Markus! Thanks for the invitation! I'm going to come, of course! I'm going to wear a Taylor Swift costume – I'm her biggest fan!<br><b>Markus:</b> Cool! Can't wait!<br><b>Tom:</b> Sorry mate, I can't come. My family is going to Spain on the seventh of June. We're going to be there for two weeks. I'll bring you a present when I'm back!<br><b>Markus:</b> No problem! Have a great holiday!<br><b>Lily:</b> Hi! I'd love to come, but I don't have a costume! Can I just wear normal clothes?<br><b>Markus:</b> Of course! It's not a problem. Are you going to bring your sister?<br><b>Lily:</b> Yes! She loves rap music, so she's going to come as a famous rapper!</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'gaps', replace($blk${"title": "Перетащи слова в пропуски", "mode": "drag", "text": "1. The party is on the __seventh__ of June.\n2. Anna is going to come as __Taylor Swift__.\n3. Tom __isn't going to__ come to the party.\n4. Tom and his family are going on holiday for __two weeks__.\n5. Lily isn't going to wear a __costume__.\n6. Lily's sister loves __rap__ music."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'video', replace($blk${"title": "LISTENING 🎧 Послушай разговор Софи и Бена о субботе.", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'sequence', replace($blk${"title": "Расставь реплики Бена в том порядке, в котором он их говорит", "items": [{"text": "Hi Sophie! Yes, I am. Why?"}, {"text": "A talent competition? Sounds fun! What time does it start?"}, {"text": "OK, great. Where shall we meet?"}, {"text": "Good idea! I love that café. What are you going to wear?"}, {"text": "Cool. Is anyone else coming?"}, {"text": "Amazing! See you on Saturday at half past five at the café!"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING I 🎤", "needs_review": true, "image": "@@MEDIA@@gg2/u8/scene_birthday.webp", "html": "<p>Опиши картинку и ответь на вопросы. Запиши ответ, нажав на кнопку микрофона (до 5 минут).</p><ol><li>What event is this?</li><li>How many people are there?</li><li>What are they wearing?</li><li>What food and drinks can you see?</li><li>What are they going to do next — open the presents, eat the cake or dance?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING II 🎤", "needs_review": true, "html": "<p>Ответь на вопросы полными предложениями. Запиши ответ, нажав на кнопку микрофона (до 5 минут).</p><ol><li>When is your birthday?</li><li>How are you going to celebrate your next birthday?</li><li>What's your favourite type of music?</li><li>What are you going to do next weekend?</li><li>Are you going to study English this evening?</li><li>What did you do last weekend?</li><li>Do you like sleepovers? Who do you usually have sleepovers with?</li><li>What's the best birthday present you ever got?</li></ol>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 14)
returning sort_order, type;
