-- Go Getter 3 · Unit 4 · Gadgets · Unit 4 Test
-- собрано tools/gg3_build.py --lesson u4_test
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 4 · Gadgets', 4 from classroom_courses c
where c.slug = 'gg3'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 4 · Gadgets');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Unit 4 Test', 'test', 90, false, 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg3' and u.title = 'Unit 4 · Gadgets'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Unit 4 Test');
update classroom_lessons l set kind = 'test', pass_threshold = 90, sort_order = 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg3' and u.title = 'Unit 4 · Gadgets' and l.title = 'Unit 4 Test';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg3' and u.title = 'Unit 4 · Gadgets' and l.title = 'Unit 4 Test';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'match', replace($blk${"title": "Соедини фразу с картинкой", "pairs": [{"left_image": "@@MEDIA@@gg3/u4/blender.webp", "right": "blender", "right_audio_tts": "blender"}, {"left_image": "@@MEDIA@@gg3/u4/microwave.webp", "right": "microwave oven", "right_audio_tts": "microwave oven"}, {"left_image": "@@MEDIA@@gg3/u4/smart_tv.webp", "right": "smart TV", "right_audio_tts": "smart TV"}, {"left_image": "@@MEDIA@@gg3/u4/usb_stick.webp", "right": "USB stick", "right_audio_tts": "USB stick"}, {"left_image": "@@MEDIA@@gg3/u4/unplug.webp", "right": "unplug", "right_audio_tts": "unplug"}, {"left_image": "@@MEDIA@@gg3/u4/plug_in.webp", "right": "plug in", "right_audio_tts": "plug in"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'exact_input', replace($blk${"title": "Посмотри на картинку и впиши пропущенные буквы", "items": [{"image": "@@MEDIA@@gg3/u4/turn_on.webp", "prompt": "1. Напиши фразу целиком: t_rn on", "accept": ["turn on", "Turn on"]}, {"image": "@@MEDIA@@gg3/u4/remote.webp", "prompt": "2. Напиши фразу целиком: r_m_t_ c_ntr_l", "accept": ["remote control", "Remote control"]}, {"image": "@@MEDIA@@gg3/u4/hairdryer.webp", "prompt": "3. Напиши слово целиком: h__rdry_r", "accept": ["hairdryer", "Hairdryer"]}, {"image": "@@MEDIA@@gg3/u4/games_console.webp", "prompt": "4. Напиши фразу целиком: g_m_s c_ns_l_", "accept": ["games console", "Games console"]}, {"image": "@@MEDIA@@gg3/u4/toaster.webp", "prompt": "5. Напиши слово целиком: t__st_r", "accept": ["toaster", "Toaster"]}, {"image": "@@MEDIA@@gg3/u4/turn_off.webp", "prompt": "6. Напиши фразу целиком: t_rn off", "accept": ["turn off", "Turn off"]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'quiz', replace($blk${"title": "Прочитай предложение и выбери пропущенное слово", "questions": [{"q": "He ___ a film on his smart TV when the power went off.", "type": "single", "options": [{"text": "watched"}, {"text": "was watching"}, {"text": "were watching"}], "correct": [1]}, {"q": "He was watching a film on his smart TV when the power ___.", "type": "single", "options": [{"text": "went off"}, {"text": "go off"}, {"text": "wented off"}], "correct": [0]}, {"q": "They ___ dinner in the kitchen at eight o'clock.", "type": "single", "options": [{"text": "was cooking"}, {"text": "cook"}, {"text": "were cooking"}], "correct": [2]}, {"q": "When I ___, she was drying her hair with the hairdryer.", "type": "single", "options": [{"text": "arrives"}, {"text": "arrived"}], "correct": [1]}, {"q": "When I arrived, she ___ her hair with the hairdryer.", "type": "single", "options": [{"text": "was drying"}, {"text": "dried"}], "correct": [0]}, {"q": "The dog ran ___ to the door when it heard the noise.", "type": "single", "options": [{"text": "fastly"}, {"text": "fast"}], "correct": [1]}, {"q": "He ___ on his games console when his mum turned off the Wi-Fi.", "type": "single", "options": [{"text": "played"}, {"text": "plays"}, {"text": "was playing"}], "correct": [2]}, {"q": "He was playing on his games console when his mum ___ the Wi-Fi.", "type": "single", "options": [{"text": "turned off"}, {"text": "was turning"}, {"text": "turning off"}], "correct": [0]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'order', replace($blk${"words": ["He", "was", "using", "the blender", "when", "I", "came in."], "sentence": "He was using the blender when I came in.", "audio_tts": "He was using the blender when I came in."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'order', replace($blk${"words": ["They", "turned on", "the smart TV", "carefully."], "sentence": "They turned on the smart TV carefully.", "audio_tts": "They turned on the smart TV carefully."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'order', replace($blk${"words": ["She", "plugged in", "the hairdryer", "and", "started", "drying her hair."], "sentence": "She plugged in the hairdryer and started drying her hair.", "audio_tts": "She plugged in the hairdryer and started drying her hair."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["We", "were watching", "a DVD", "at eight o'clock."], "sentence": "We were watching a DVD at eight o'clock.", "audio_tts": "We were watching a DVD at eight o'clock."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["He", "unplugged", "the toaster", "quickly."], "sentence": "He unplugged the toaster quickly.", "audio_tts": "He unplugged the toaster quickly."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING TASK 1 🎤", "needs_review": true, "html": "<p>Опиши картинку, ответь на вопросы.</p><ul><li>What is the girl doing?</li><li>What appliance is she using?</li><li>How often do you use a hairdryer at home?</li><li>Is it safe or dangerous?</li></ul><p>Нажми на микрофон и запиши ответ.</p>", "image": "@@MEDIA@@gg3/u4/scene_hairdryer.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING TASK 2 🎤", "needs_review": true, "html": "<p>Ответь на вопросы (не забудь отвечать полными предложениями).</p><ol><li>Do you have a smart TV at home?</li><li>How often do you use a microwave oven?</li><li>What do you usually plug in every day?</li><li>What appliance do you use most often?</li><li>What do you turn on in the morning?</li><li>What do you turn off before leaving home?</li><li>What were you doing at eight o'clock yesterday?</li><li>What were your parents doing ten minutes ago?</li></ol><p>Нажми на микрофон и запиши ответ.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9)
returning sort_order, type;
