-- Go Getter 3 · Unit 2 · Unit 2 Test
-- собрано tools/gg3_build.py --lesson u2_test
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 2', 2 from classroom_courses c
where c.slug = 'gg3'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 2');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Unit 2 Test', 'test', 90, false, 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg3' and u.title = 'Unit 2'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Unit 2 Test');
update classroom_lessons l set kind = 'test', pass_threshold = 90, sort_order = 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg3' and u.title = 'Unit 2' and l.title = 'Unit 2 Test';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg3' and u.title = 'Unit 2' and l.title = 'Unit 2 Test';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'match', replace($blk${"title": "Соедини фразу с картинкой", "pairs": [{"left_image": "@@MEDIA@@gg3/u2/basket.webp", "right": "shopping basket", "right_audio_tts": "shopping basket"}, {"left_image": "@@MEDIA@@gg3/u2/pay_card.webp", "right": "pay by card", "right_audio_tts": "pay by card"}, {"left_image": "@@MEDIA@@gg3/u2/list.webp", "right": "shopping list", "right_audio_tts": "shopping list"}, {"left_image": "@@MEDIA@@gg3/u2/greengrocers.webp", "right": "greengrocer's", "right_audio_tts": "greengrocer's"}, {"left_image": "@@MEDIA@@gg3/u2/cashier.webp", "right": "cashier", "right_audio_tts": "cashier"}, {"left_image": "@@MEDIA@@gg3/u2/department_store.webp", "right": "department store", "right_audio_tts": "department store"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'exact_input', replace($blk${"title": "Посмотри на картинку и впиши пропущенные буквы", "items": [{"image": "@@MEDIA@@gg3/u2/pay_cash.webp", "prompt": "1. Напиши фразу целиком: p_y in c_sh", "accept": ["pay in cash", "Pay in cash"]}, {"image": "@@MEDIA@@gg3/u2/carry_shopping.webp", "prompt": "2. Напиши фразу целиком: c_rry th_ sh_pp_ng", "accept": ["carry the shopping", "Carry the shopping"]}, {"image": "@@MEDIA@@gg3/u2/get_change.webp", "prompt": "3. Напиши фразу целиком: g_t y__r ch_ng_", "accept": ["get your change", "Get your change"]}, {"image": "@@MEDIA@@gg3/u2/chemists.webp", "prompt": "4. Напиши слово целиком: ch_m_st's", "accept": ["chemist's", "chemist’s", "Chemist's", "Chemist’s"]}, {"image": "@@MEDIA@@gg3/u2/queue.webp", "prompt": "5. Напиши фразу целиком: st_nd in a q____", "accept": ["stand in a queue", "Stand in a queue"]}, {"image": "@@MEDIA@@gg3/u2/trolley.webp", "prompt": "6. Напиши фразу целиком: sh_pp_ng tr_ll_y", "accept": ["shopping trolley", "Shopping trolley"]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'quiz', replace($blk${"title": "Прочитай предложение и выбери пропущенное слово", "questions": [{"q": "This T-shirt is ___ than that at the department store.", "type": "single", "options": [{"text": "more cheap"}, {"text": "cheaper"}, {"text": "the cheapest"}], "correct": [1]}, {"q": "The shopping bag isn't ___ for all these things.", "type": "single", "options": [{"text": "big enough"}, {"text": "too big"}, {"text": "big too"}], "correct": [0]}, {"q": "The cashier is ___ the one at the baker's.", "type": "single", "options": [{"text": "as friendlier as"}, {"text": "not as friendliest as"}, {"text": "as friendly as"}], "correct": [2]}, {"q": "This sports shop is ___ in our town.", "type": "single", "options": [{"text": "more expensive"}, {"text": "the most expensive"}, {"text": "the expensivest"}], "correct": [1]}, {"q": "The queue is ___, let's come back later.", "type": "single", "options": [{"text": "long enough"}, {"text": "the longest"}, {"text": "too long"}], "correct": [2]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'order', replace($blk${"words": ["She", "is", "checking", "the price", "now."], "sentence": "She is checking the price now.", "audio_tts": "She is checking the price now."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'order', replace($blk${"words": ["They", "pay", "in cash", "at the greengrocer's."], "sentence": "They pay in cash at the greengrocer's.", "audio_tts": "They pay in cash at the greengrocer's."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'order', replace($blk${"words": ["This", "is", "the biggest", "department store", "in our city."], "sentence": "This is the biggest department store in our city.", "audio_tts": "This is the biggest department store in our city."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["He", "isn't", "old enough", "to pay", "by card."], "sentence": "He isn't old enough to pay by card.", "audio_tts": "He isn't old enough to pay by card."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["Carrying", "the shopping", "is", "too heavy", "for me."], "sentence": "Carrying the shopping is too heavy for me.", "audio_tts": "Carrying the shopping is too heavy for me."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING TASK 1 🎤", "needs_review": true, "html": "<p>Опиши картинку, ответь на вопросы.</p><ol><li>What can you see in the shop?</li><li>What are the people buying?</li><li>What is the cashier doing?</li><li>Are people standing in a queue?</li><li>What items can you name?</li><li>Is the shop big or small?</li><li>Is the shopping trolley full or empty?</li></ol><p>Нажми на микрофон и запиши ответ.</p>", "image": "@@MEDIA@@gg3/u2/scene_shop.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING TASK 2 🎤", "needs_review": true, "html": "<p>Ответь на вопросы (не забудь отвечать полными предложениями).</p><ol><li>Do you like shopping?</li><li>What do you usually buy?</li><li>Do you use a shopping basket or a shopping trolley?</li><li>Do you pay in cash or by card?</li><li>What shops do you have near your home?</li><li>Which shop is the cheapest in your town?</li><li>Which shop is the most expensive?</li><li>Which shop is better – the baker's or the greengrocer's?</li></ol><p>Нажми на микрофон и запиши ответ.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9)
returning sort_order, type;
