-- Go Getter 3 · Unit 1 · Unit 1 Test
-- собрано tools/gg3_build.py --lesson u1_test
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 1', 1 from classroom_courses c
where c.slug = 'gg3'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 1');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Unit 1 Test', 'test', 90, false, 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg3' and u.title = 'Unit 1'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Unit 1 Test');
update classroom_lessons l set kind = 'test', pass_threshold = 90, sort_order = 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg3' and u.title = 'Unit 1' and l.title = 'Unit 1 Test';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg3' and u.title = 'Unit 1' and l.title = 'Unit 1 Test';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'match', replace($blk${"title": "Соедини фразу с картинкой", "pairs": [{"left_image": "@@MEDIA@@gg3/u1/clear_table.webp", "right": "clear the table", "right_audio_tts": "clear the table"}, {"left_image": "@@MEDIA@@gg3/u1/feed_dog.webp", "right": "feed the dog", "right_audio_tts": "feed the dog"}, {"left_image": "@@MEDIA@@gg3/u1/hang_washing.webp", "right": "hang out the washing", "right_audio_tts": "hang out the washing"}, {"left_image": "@@MEDIA@@gg3/u1/iron_tshirt.webp", "right": "iron your T-shirt", "right_audio_tts": "iron your T-shirt"}, {"left_image": "@@MEDIA@@gg3/u1/take_rubbish.webp", "right": "take out the rubbish", "right_audio_tts": "take out the rubbish"}, {"left_image": "@@MEDIA@@gg3/u1/water_plants.webp", "right": "water the plants", "right_audio_tts": "water the plants"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'exact_input', replace($blk${"title": "Посмотри на картинку и впиши пропущенные буквы", "items": [{"image": "@@MEDIA@@gg3/u1/load_dishwasher.webp", "prompt": "1. Напиши фразу целиком: l__d th_ d_shw_sh_r", "accept": ["load the dishwasher", "Load the dishwasher"]}, {"image": "@@MEDIA@@gg3/u1/make_bed.webp", "prompt": "2. Напиши фразу целиком: m_k_ y__r b_d", "accept": ["make your bed", "Make your bed"]}, {"image": "@@MEDIA@@gg3/u1/vacuum_room.webp", "prompt": "3. Напиши фразу целиком: v_c__m y__r r__m", "accept": ["vacuum your room", "Vacuum your room"]}, {"image": "@@MEDIA@@gg3/u1/empty_dishwasher.webp", "prompt": "4. Напиши фразу целиком: empty th_ d_shw_sh_r", "accept": ["empty the dishwasher", "Empty the dishwasher"]}, {"image": "@@MEDIA@@gg3/u1/set_table.webp", "prompt": "5. Напиши фразу целиком: s_t th_ t_bl_", "accept": ["set the table", "Set the table"]}, {"image": "@@MEDIA@@gg3/u1/put_away_clothes.webp", "prompt": "6. Напиши фразу целиком: p_t aw_y y__r cl_th_s", "accept": ["put away your clothes", "Put away your clothes"]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'quiz', replace($blk${"title": "Прочитай предложение и выбери пропущенное слово", "questions": [{"q": "She ___ the dog now.", "type": "single", "options": [{"text": "feeds"}, {"text": "is feeding"}, {"text": "is feed"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'quiz', replace($blk${"title": "Прочитай предложение и выбери пропущенное слово", "questions": [{"q": "He usually ___ out the washing on Fridays.", "type": "single", "options": [{"text": "is hanging"}, {"text": "hang"}, {"text": "hangs"}], "correct": [2]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'quiz', replace($blk${"title": "Прочитай предложение и выбери пропущенное слово", "questions": [{"q": "___ you ___ your room now? — первый пропуск", "type": "single", "options": [{"text": "Are"}, {"text": "Do"}, {"text": "Does"}, {"text": "Is"}], "correct": [0]}, {"q": "___ you ___ your room now? — второй пропуск", "type": "single", "options": [{"text": "vacuums"}, {"text": "vacuuming"}, {"text": "vacuum"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'quiz', replace($blk${"title": "Прочитай предложение и выбери пропущенное слово", "questions": [{"q": "They ___ their beds at the moment.", "type": "single", "options": [{"text": "isn't making"}, {"text": "don't make"}, {"text": "aren't making"}], "correct": [2]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'quiz', replace($blk${"title": "Прочитай предложение и выбери пропущенное слово", "questions": [{"q": "I ___ this homework.", "type": "single", "options": [{"text": "am not understanding"}, {"text": "don't understand"}, {"text": "doesn't understand"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["She", "is", "watering", "the plants", "now."], "sentence": "She is watering the plants now.", "audio_tts": "She is watering the plants now."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'order', replace($blk${"words": ["They", "usually", "set", "the table", "at the weekend."], "sentence": "They usually set the table at the weekend.", "audio_tts": "They usually set the table at the weekend."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'order', replace($blk${"words": ["I", "never", "load", "the dishwasher."], "sentence": "I never load the dishwasher.", "audio_tts": "I never load the dishwasher."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'order', replace($blk${"words": ["He", "is", "ironing", "his T-shirt", "at the moment."], "sentence": "He is ironing his T-shirt at the moment.", "audio_tts": "He is ironing his T-shirt at the moment."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10),
('<lesson_id>', 'order', replace($blk${"words": ["Do", "you", "like", "easy-going", "people?"], "sentence": "Do you like easy-going people?", "audio_tts": "Do you like easy-going people?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 11),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING TASK 1 🎤", "needs_review": true, "html": "<p>Опиши картинку. Расскажи, кто чем занят. Используй Present Continuous и лексику по теме «домашние обязанности».<br><i>Example: The woman is sweeping the floor.</i></p><p>Нажми на микрофон и запиши ответ.</p>", "image": "@@MEDIA@@gg3/u1/scene_chores.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 12),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING TASK 2 🎤", "needs_review": true, "html": "<p>Ответь на вопросы. Используй Present Simple и Present Continuous.</p><ol><li>What chores do you usually do at home?</li><li>What chore do you never do?</li><li>What are you doing right now?</li><li>How often do you make your bed?</li><li>Who usually vacuums your home?</li></ol><p>Нажми на микрофон и запиши ответ.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 13)
returning sort_order, type;
