-- Go Getter 3 · Final Test · Final Test
-- собрано tools/gg3_build.py --lesson final
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Final Test', 9 from classroom_courses c
where c.slug = 'gg3'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Final Test');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Final Test', 'test', 90, false, 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg3' and u.title = 'Final Test'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Final Test');
update classroom_lessons l set kind = 'test', pass_threshold = 90, sort_order = 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg3' and u.title = 'Final Test' and l.title = 'Final Test';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg3' and u.title = 'Final Test' and l.title = 'Final Test';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'text', replace($blk${"html": "<h2>Listening 🎧</h2>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'video', replace($blk${"title": "Listen to five people talking about health problems.", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'truefalse', replace($blk${"title": "Listen to five people talking about health problems. Choose T (true) or F (false).", "statements": [{"text": "Ben doesn't want to stop snorkelling.", "correct": true}, {"text": "Molly got headaches, because her eyes got tired.", "correct": true}, {"text": "Molly wears glasses now.", "correct": true}, {"text": "Duncan got the flu eight months ago.", "correct": false}, {"text": "Olivia's dad put cold tea on her mosquito bites.", "correct": false}, {"text": "Spicy food is bad for Stuart's stomach.", "correct": true}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'text', replace($blk${"html": "<h2>Reading and Writing 📖</h2><p>Look at the picture. Then choose True (Верно) or False (Неверно).</p><p><img src=\"@@MEDIA@@gg3/final/scene_camping.webp\" alt=\"Camping\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'truefalse', replace($blk${"title": "Look at the picture. Choose True or False.", "statements": [{"text": "Two people are walking together, and they are carrying their backpacks.", "correct": true}, {"text": "The man near the fire is singing, and the woman next to him is playing the guitar.", "correct": false}, {"text": "The tents in the picture are bigger than the backpacks.", "correct": true}, {"text": "The boy near the lake is going to swim.", "correct": false}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'exact_input', replace($blk${"title": "Unjumble the letters. Картинка — подсказка.", "items": [{"image": "@@MEDIA@@gg3/u1/water_plants.webp", "prompt": "1. terwa teh atplsn", "accept": ["water the plants", "Water the plants"]}, {"image": "@@MEDIA@@gg3/u4/hairdryer.webp", "prompt": "2. rydreirah", "accept": ["hairdryer", "Hairdryer"]}, {"image": "@@MEDIA@@gg3/u2/cashier.webp", "prompt": "3. cshreia", "accept": ["cashier", "Cashier"]}, {"image": "@@MEDIA@@gg3/u5/bruise.webp", "prompt": "4. iesbur", "accept": ["bruise", "Bruise"]}, {"image": "@@MEDIA@@gg3/u6/bake.webp", "prompt": "5. baek", "accept": ["bake", "Bake"]}, {"image": "@@MEDIA@@gg3/u7/cottage.webp", "prompt": "6. tgotcae", "accept": ["cottage", "Cottage"]}, {"image": "@@MEDIA@@gg3/u8/shake_hands.webp", "prompt": "7. eskha ndash", "accept": ["shake hands", "Shake hands"]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'gaps', replace($blk${"title": "Complete the text with the words in the box. Первое слово (cottage) — пример, оно уже вставлено.", "mode": "drag", "text": "HOME SWEET HOME by Helen Todd\n\nMy family and I live in a cottage in a small __village__ in Yorkshire. My parents have their own __business__ here and my brother and I go to the local school.\nPeople here are very friendly. They smile, say good morning and __shake__ hands when they meet in the street. They chat to their neighbours when they __water__ the plants in the garden or take __out__ the rubbish. It's a great place to live."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'quiz', replace($blk${"title": "Choose the correct answer.", "questions": [{"q": "Dad ___ the office a few minutes ago.", "type": "single", "options": [{"text": "leaves"}, {"text": "left"}], "correct": [1]}, {"q": "___ to do this exercise, but I don't understand it.", "type": "single", "options": [{"text": "I'm trying"}, {"text": "I try"}], "correct": [0]}, {"q": "I can't come with you tomorrow. ___ tennis with Paula.", "type": "single", "options": [{"text": "I play"}, {"text": "I'm playing"}], "correct": [1]}, {"q": "She ___ the plants yesterday, so please water them now.", "type": "single", "options": [{"text": "didn't water"}, {"text": "doesn't water"}], "correct": [0]}, {"q": "We ___ the old town when we got lost.", "type": "single", "options": [{"text": "explored"}, {"text": "were exploring"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'quiz', replace($blk${"title": "Choose the correct answer.", "questions": [{"q": "I can't play basketball. I'm not ___.", "type": "single", "options": [{"text": "tall enough"}, {"text": "too tall"}], "correct": [0]}, {"q": "He always listens ___ to his teachers.", "type": "single", "options": [{"text": "careful"}, {"text": "carefully"}], "correct": [1]}, {"q": "Do we ___ ask for permission?", "type": "single", "options": [{"text": "should"}, {"text": "have to"}], "correct": [1]}, {"q": "I ___ be late! Mum will be angry.", "type": "single", "options": [{"text": "mustn't"}, {"text": "can"}], "correct": [0]}, {"q": "That's the ___ programme on TV.", "type": "single", "options": [{"text": "worse"}, {"text": "worst"}], "correct": [1]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'text', replace($blk${"html": "<h2>Speaking 🎤</h2>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9),
('<lesson_id>', 'speaking', replace($blk${"title": "Answer the questions 🎤", "needs_review": true, "html": "<p>Answer the questions:</p><ol><li>What chores do you usually do at home?</li><li>Do you prefer paying in cash or by card when you go shopping? Why?</li><li>Where did you go on your last day trip or holiday? What did you do there?</li><li>What were you doing yesterday at eight o'clock?</li><li>What should you do if you have a cold or a headache?</li><li>Have you ever tried cooking something difficult? What did you make?</li><li>Where do you live: in a city, in a town, or in a village? Do you like it? Why?</li><li>Are you doing anything special tomorrow or next week?</li><li>Do you think you will live in a house or in a flat? Why?</li></ol><p>Нажми на микрофон и запиши ответ.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 10)
returning sort_order, type;
