-- Go Getter 3 · Unit 7 · Unit 7 Test
-- собрано tools/gg3_build.py --lesson u7_test
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 7', 7 from classroom_courses c
where c.slug = 'gg3'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 7');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Unit 7 Test', 'test', 90, false, 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg3' and u.title = 'Unit 7'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Unit 7 Test');
update classroom_lessons l set kind = 'test', pass_threshold = 90, sort_order = 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg3' and u.title = 'Unit 7' and l.title = 'Unit 7 Test';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg3' and u.title = 'Unit 7' and l.title = 'Unit 7 Test';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'match', replace($blk${"title": "Соедини фразу с картинкой", "pairs": [{"left_image": "@@MEDIA@@gg3/u7/detached.webp", "right": "detached house", "right_audio_tts": "detached house"}, {"left_image": "@@MEDIA@@gg3/u7/terraced.webp", "right": "terraced house", "right_audio_tts": "terraced house"}, {"left_image": "@@MEDIA@@gg3/u7/attic.webp", "right": "attic", "right_audio_tts": "attic"}, {"left_image": "@@MEDIA@@gg3/u7/balcony.webp", "right": "balcony", "right_audio_tts": "balcony"}, {"left_image": "@@MEDIA@@gg3/u7/lift.webp", "right": "lift", "right_audio_tts": "lift"}, {"left_image": "@@MEDIA@@gg3/u7/stairs.webp", "right": "stairs", "right_audio_tts": "stairs"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'exact_input', replace($blk${"title": "Посмотри на картинку и впиши пропущенные буквы", "items": [{"image": "@@MEDIA@@gg3/u7/block_of_flats.webp", "prompt": "1. Напиши фразу целиком: bl_ck of fl_ts", "accept": ["block of flats", "Block of flats"]}, {"image": "@@MEDIA@@gg3/u7/basement.webp", "prompt": "2. Напиши слово целиком: b_s_m_nt", "accept": ["basement", "Basement"]}, {"image": "@@MEDIA@@gg3/u7/mirror.webp", "prompt": "3. Напиши слово целиком: m_rr_r", "accept": ["mirror", "Mirror"]}, {"image": "@@MEDIA@@gg3/u7/drawer.webp", "prompt": "4. Напиши слово целиком: dr_w_r", "accept": ["drawer", "Drawer"]}, {"image": "@@MEDIA@@gg3/u7/tap.webp", "prompt": "5. Напиши слово целиком: t_p", "accept": ["tap", "Tap"]}, {"image": "@@MEDIA@@gg3/u7/semi_detached.webp", "prompt": "6. Напиши фразу целиком: s_m_-d_t_ch_d h__s_", "accept": ["semi-detached house", "Semi-detached house"]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'quiz', replace($blk${"title": "Прочитай предложение и выбери пропущенное слово", "questions": [{"q": "We ___ our grandparents tomorrow morning.", "type": "single", "options": [{"text": "are visiting"}, {"text": "visit"}], "correct": [0]}, {"q": "She ___ to a new flat next week.", "type": "single", "options": [{"text": "moves"}, {"text": "is moving"}], "correct": [1]}, {"q": "You ___ run on the stairs – it's dangerous.", "type": "single", "options": [{"text": "must"}, {"text": "mustn't"}], "correct": [1]}, {"q": "He ___ use the lift because his leg is broken.", "type": "single", "options": [{"text": "can't"}, {"text": "can to"}, {"text": "can"}], "correct": [2]}, {"q": "Students ___ clean up the classroom after school.", "type": "single", "options": [{"text": "must"}, {"text": "mustn't"}, {"text": "can't"}], "correct": [0]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'order', replace($blk${"words": ["We", "are", "checking out", "a new house", "this evening."], "sentence": "We are checking out a new house this evening.", "audio_tts": "We are checking out a new house this evening."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'order', replace($blk${"words": ["She", "must", "clean up", "her room", "today."], "sentence": "She must clean up her room today.", "audio_tts": "She must clean up her room today."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'order', replace($blk${"words": ["They", "are", "meeting", "friends", "tomorrow", "at six o'clock."], "sentence": "They are meeting friends tomorrow at six o'clock.", "audio_tts": "They are meeting friends tomorrow at six o'clock."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["He", "is", "looking for", "the book", "in the attic."], "sentence": "He is looking for the book in the attic.", "audio_tts": "He is looking for the book in the attic."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["You", "mustn't", "wake up", "the baby", "in the next room."], "sentence": "You mustn't wake up the baby in the next room.", "audio_tts": "You mustn't wake up the baby in the next room."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING TASK 1 🎤", "needs_review": true, "html": "<p>Опиши картинку, ответь на вопросы.</p><ul><li>What kind of house is it?</li><li>What are the people doing now?</li><li>Are they moving in or moving out?</li><li>What can you see around the house?</li><li>What must they do before they finish moving?</li></ul><p>Нажми на микрофон и запиши ответ.</p>", "image": "@@MEDIA@@gg3/u7/scene_moving.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING TASK 2 🎤", "needs_review": true, "html": "<p>Ответь на вопросы (не забудь отвечать полными предложениями).</p><ol><li>Where do you live: in a city, in a town or in a village?</li><li>What kind of home would you like to live in?</li><li>What floor do you live on?</li><li>Do you have an attic or a basement?</li><li>What can you see from your balcony?</li><li>What must you do at home every day?</li><li>Can you use the lift in your building?</li><li>What room do you clean up most often?</li><li>What are you doing tomorrow evening?</li><li>What are you doing after school today?</li></ol><p>Нажми на микрофон и запиши ответ.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9)
returning sort_order, type;
