-- Go Getter 3 · Unit 8 · The future · Unit 8 Test
-- собрано tools/gg3_build.py --lesson u8_test
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 8 · The future', 8 from classroom_courses c
where c.slug = 'gg3'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 8 · The future');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Unit 8 Test', 'test', 90, false, 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg3' and u.title = 'Unit 8 · The future'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Unit 8 Test');
update classroom_lessons l set kind = 'test', pass_threshold = 90, sort_order = 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg3' and u.title = 'Unit 8 · The future' and l.title = 'Unit 8 Test';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg3' and u.title = 'Unit 8 · The future' and l.title = 'Unit 8 Test';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'match', replace($blk${"title": "Соедини фразу с картинкой", "pairs": [{"left_image": "@@MEDIA@@gg3/u8/be_rich.webp", "right": "be rich", "right_audio_tts": "be rich"}, {"left_image": "@@MEDIA@@gg3/u8/have_family.webp", "right": "have a family", "right_audio_tts": "have a family"}, {"left_image": "@@MEDIA@@gg3/u8/foreign_language.webp", "right": "learn a foreign language", "right_audio_tts": "learn a foreign language"}, {"left_image": "@@MEDIA@@gg3/u8/wait_turn.webp", "right": "wait your turn", "right_audio_tts": "wait your turn"}, {"left_image": "@@MEDIA@@gg3/u8/hug.webp", "right": "give someone a hug", "right_audio_tts": "give someone a hug"}, {"left_image": "@@MEDIA@@gg3/u8/shake_hands.webp", "right": "shake hands", "right_audio_tts": "shake hands"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'exact_input', replace($blk${"title": "Посмотри на картинку и впиши пропущенные буквы", "items": [{"image": "@@MEDIA@@gg3/u8/be_doctor.webp", "prompt": "1. Напиши фразу целиком: b_ a d_ct_r", "accept": ["be a doctor", "Be a doctor"]}, {"image": "@@MEDIA@@gg3/u8/invite.webp", "prompt": "2. Напиши слово целиком: inv_t_", "accept": ["invite", "Invite"]}, {"image": "@@MEDIA@@gg3/u8/learn_drive.webp", "prompt": "3. Напиши фразу целиком: l__rn t_ dr_v_", "accept": ["learn to drive", "Learn to drive"]}, {"image": "@@MEDIA@@gg3/u8/call.webp", "prompt": "4. Напиши слово целиком: c_ll", "accept": ["call", "Call"]}, {"image": "@@MEDIA@@gg3/u8/arrive_on_time.webp", "prompt": "5. Напиши фразу целиком: arr_v_ on t_m_", "accept": ["arrive on time", "Arrive on time"]}, {"image": "@@MEDIA@@gg3/u8/be_famous.webp", "prompt": "6. Напиши фразу целиком: b_ f_m__s", "accept": ["be famous", "Be famous"]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'quiz', replace($blk${"title": "Прочитай предложение и выбери пропущенное слово", "questions": [{"q": "I think she ___ abroad one day.", "type": "single", "options": [{"text": "is going to live"}, {"text": "will live"}, {"text": "lives"}], "correct": [1]}, {"q": "He ___ a famous singer in the future.", "type": "single", "options": [{"text": "will be"}, {"text": "is"}, {"text": "will being"}], "correct": [0]}, {"q": "___ when I called you last night?", "type": "single", "options": [{"text": "What did you do"}, {"text": "What are you doing"}, {"text": "What were you doing"}], "correct": [2]}, {"q": "___ tonight?", "type": "single", "options": [{"text": "Where do you go"}, {"text": "Where are you going"}, {"text": "Where were you going"}], "correct": [1]}, {"q": "___ at the party yesterday?", "type": "single", "options": [{"text": "When did he arrive"}, {"text": "When does he arrive"}, {"text": "When is he arriving"}], "correct": [0]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'order', replace($blk${"words": ["She", "will", "learn", "a foreign language", "in the future."], "sentence": "She will learn a foreign language in the future.", "audio_tts": "She will learn a foreign language in the future."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'order', replace($blk${"words": ["They", "are", "visiting", "their grandparents", "tomorrow."], "sentence": "They are visiting their grandparents tomorrow.", "audio_tts": "They are visiting their grandparents tomorrow."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'order', replace($blk${"words": ["When", "will", "you", "arrive", "at the cinema?"], "sentence": "When will you arrive at the cinema?", "audio_tts": "When will you arrive at the cinema?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["He", "is", "going", "to", "have", "his own business", "one day."], "sentence": "He is going to have his own business one day.", "audio_tts": "He is going to have his own business one day."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["Why", "are", "you", "asking", "for permission?"], "sentence": "Why are you asking for permission?", "audio_tts": "Why are you asking for permission?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING TASK 1 🎤", "needs_review": true, "html": "<p>Опиши картинку, ответь на вопросы.</p><ul><li>How are the boys greeting each other?</li><li>Are they polite?</li><li>What will they do next?</li><li>Do they look happy?</li><li>When do you usually hug your friends?</li></ul><p>Нажми на микрофон и запиши ответ.</p>", "image": "@@MEDIA@@gg3/u8/scene_greeting.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING TASK 2 🎤", "needs_review": true, "html": "<p>Ответь на вопросы (не забудь отвечать полными предложениями).</p><ol><li>Will you live abroad one day?</li><li>What foreign language do you want to learn?</li><li>Do you want to have your own business?</li><li>Are you going to call anyone today?</li><li>Who do you usually hug?</li><li>Do you always arrive on time?</li><li>What should people do to be polite?</li><li>What did you do yesterday evening?</li><li>What were you doing at six o'clock yesterday?</li><li>Where are you going this weekend?</li></ol><p>Нажми на микрофон и запиши ответ.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9)
returning sort_order, type;
