-- Go Getter 3 · Unit 3 · Unit 3 Test
-- собрано tools/gg3_build.py --lesson u3_test
-- заливалось через execute_sql кусками (--setup, --clear, --chunks); этот файл — исходник
insert into classroom_units (course_id, title, sort_order)
select c.id, 'Unit 3', 3 from classroom_courses c
where c.slug = 'gg3'
  and not exists (select 1 from classroom_units u where u.course_id = c.id and u.title = 'Unit 3');
insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
select u.id, 'Unit 3 Test', 'test', 90, false, 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where c.slug = 'gg3' and u.title = 'Unit 3'
  and not exists (select 1 from classroom_lessons l where l.unit_id = u.id and l.title = 'Unit 3 Test');
update classroom_lessons l set kind = 'test', pass_threshold = 90, sort_order = 0
from classroom_units u join classroom_courses c on c.id = u.course_id
where l.unit_id = u.id and c.slug = 'gg3' and u.title = 'Unit 3' and l.title = 'Unit 3 Test';
select l.id, l.kind, l.pass_threshold, l.is_published from classroom_lessons l
join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
where c.slug = 'gg3' and u.title = 'Unit 3' and l.title = 'Unit 3 Test';

-- затем: delete блоков урока (CTE) и вставка:
-- кусок 1
insert into classroom_blocks (lesson_id, type, payload, sort_order) values
('<lesson_id>', 'match', replace($blk${"title": "Соедини фразу с картинкой", "pairs": [{"left_image": "@@MEDIA@@gg3/u3/hiking.webp", "right": "go hiking", "right_audio_tts": "go hiking"}, {"left_image": "@@MEDIA@@gg3/u3/camping.webp", "right": "go camping", "right_audio_tts": "go camping"}, {"left_image": "@@MEDIA@@gg3/u3/boat_trip.webp", "right": "go on a boat trip", "right_audio_tts": "go on a boat trip"}, {"left_image": "@@MEDIA@@gg3/u3/local_food.webp", "right": "try the local food", "right_audio_tts": "try the local food"}, {"left_image": "@@MEDIA@@gg3/u3/cycling.webp", "right": "go cycling", "right_audio_tts": "go cycling"}, {"left_image": "@@MEDIA@@gg3/u3/explore_city.webp", "right": "explore a city", "right_audio_tts": "explore a city"}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 0),
('<lesson_id>', 'exact_input', replace($blk${"title": "Посмотри на картинку и впиши пропущенные буквы", "items": [{"image": "@@MEDIA@@gg3/u3/snorkelling.webp", "prompt": "1. Напиши фразу целиком: g_ sn_rk_ll_ng", "accept": ["go snorkelling", "Go snorkelling"]}, {"image": "@@MEDIA@@gg3/u3/guided_tour.webp", "prompt": "2. Напиши фразу целиком: g_ on a g__d_d t__r", "accept": ["go on a guided tour", "Go on a guided tour"]}, {"image": "@@MEDIA@@gg3/u3/beach.webp", "prompt": "3. Напиши фразу целиком: g_ t_ th_ b__ch", "accept": ["go to the beach", "Go to the beach"]}, {"image": "@@MEDIA@@gg3/u3/get_tired.webp", "prompt": "4. Напиши фразу целиком: g_t t_r_d", "accept": ["get tired", "Get tired"]}, {"image": "@@MEDIA@@gg3/u3/get_lost.webp", "prompt": "5. Напиши фразу целиком: g_t l_st", "accept": ["get lost", "Get lost"]}, {"image": "@@MEDIA@@gg3/u3/get_bored.webp", "prompt": "6. Напиши фразу целиком: g_t b_r_d", "accept": ["get bored", "Get bored"]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 1),
('<lesson_id>', 'quiz', replace($blk${"title": "Прочитай предложение и выбери пропущенное слово", "questions": [{"q": "We ___ to the beach yesterday.", "type": "single", "options": [{"text": "goed"}, {"text": "went"}], "correct": [1]}, {"q": "He ___ tired on the day trip.", "type": "single", "options": [{"text": "didn't get"}, {"text": "wasn't get"}], "correct": [0]}, {"q": "___ the local food?", "type": "single", "options": [{"text": "Do you try"}, {"text": "Did you try"}], "correct": [1]}, {"q": "They ___ lost in the city centre.", "type": "single", "options": [{"text": "were"}, {"text": "was"}, {"text": "weren't"}], "correct": [0]}, {"q": "She ___ on a guided tour last weekend.", "type": "single", "options": [{"text": "didn't went"}, {"text": "wasn't go"}, {"text": "didn't go"}], "correct": [2]}]}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 2),
('<lesson_id>', 'order', replace($blk${"words": ["We", "went", "on a day trip", "last Saturday."], "sentence": "We went on a day trip last Saturday.", "audio_tts": "We went on a day trip last Saturday."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 3),
('<lesson_id>', 'order', replace($blk${"words": ["Did", "you", "go snorkelling", "on holiday?"], "sentence": "Did you go snorkelling on holiday?", "audio_tts": "Did you go snorkelling on holiday?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 4),
('<lesson_id>', 'order', replace($blk${"words": ["They", "didn't", "explore", "the town", "yesterday."], "sentence": "They didn't explore the town yesterday.", "audio_tts": "They didn't explore the town yesterday."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 5),
('<lesson_id>', 'order', replace($blk${"words": ["Was", "the weather", "cold", "at the beach?"], "sentence": "Was the weather cold at the beach?", "audio_tts": "Was the weather cold at the beach?"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 6),
('<lesson_id>', 'order', replace($blk${"words": ["He", "got", "bored", "on the guided tour."], "sentence": "He got bored on the guided tour.", "audio_tts": "He got bored on the guided tour."}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 7),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING TASK 1 🎤", "needs_review": true, "html": "<p>Опиши картинку, ответь на вопросы.</p><ol><li>Where were the people?</li><li>What did they do on their trip?</li><li>Did they go hiking or cycling?</li><li>What did they carry with them?</li><li>Did they get tired?</li><li>What was the weather like?</li><li>Were they happy on the trip?</li><li>What else can you see?</li></ol><p>Нажми на микрофон и запиши ответ.</p>", "image": "@@MEDIA@@gg3/u3/scene_trip.webp"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 8),
('<lesson_id>', 'speaking', replace($blk${"title": "SPEAKING TASK 2 🎤", "needs_review": true, "html": "<p>Ответь на вопросы (не забудь отвечать полными предложениями).</p><ol><li>Where did you go last weekend?</li><li>Did you go to the beach last summer?</li><li>Did you try any local food on holiday?</li><li>What city or area did you explore last year?</li><li>Did you get bored on your trip?</li><li>Did you get lost in a new place?</li><li>What was the weather like on your last holiday?</li><li>What did you enjoy most on your trip?</li><li>Were you with friends or family?</li><li>Did you buy any souvenirs?</li></ol><p>Нажми на микрофон и запиши ответ.</p>"}$blk$, '@@MEDIA@@', 'https://classroom.wowteach.ru/media/')::jsonb, 9)
returning sort_order, type;
