-- Super Minds 1 · Unit 8 · My body · Homework 1
-- собрано tools/sm1_build.py --lesson u8_hw1
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where slug = 'sm1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 8 · My body', 8
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 8 · My body');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 8 · My body';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 1', 'homework',
         60, false, 0
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 1');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 1';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Добро пожаловать в домашнее задание! 👋</h2><p>В этом уроке тебя ждёт много классных упражнений — мы выучим, как по-английски называются части тела.</p><p><img src=\"@@MEDIA@@sm1/u8/body_teddy.webp\" alt=\"\" style=\"max-width:260px\"></p><p>Выполни все задания, если хочешь выучить тему на все 100!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"title": "Запомни слова", "cards": [{"text": "head", "translation": "голова", "audio_tts": "head", "image": "@@MEDIA@@sm1/u8/body_head.webp"}, {"text": "fingers", "translation": "пальцы рук", "audio_tts": "fingers", "image": "@@MEDIA@@sm1/u8/body_fingers.webp"}, {"text": "hand", "translation": "кисть руки", "audio_tts": "hand", "image": "@@MEDIA@@sm1/u8/body_hand.webp"}, {"text": "knee", "translation": "колено", "audio_tts": "knee", "image": "@@MEDIA@@sm1/u8/body_knee.webp"}, {"text": "leg", "translation": "нога", "audio_tts": "leg", "image": "@@MEDIA@@sm1/u8/body_leg.webp"}, {"text": "toes", "translation": "пальцы ног", "audio_tts": "toes", "image": "@@MEDIA@@sm1/u8/body_toes.webp"}, {"text": "foot", "translation": "ступня", "audio_tts": "foot", "image": "@@MEDIA@@sm1/u8/body_foot.webp"}, {"text": "arms", "translation": "руки (от плеча)", "audio_tts": "arms", "image": "@@MEDIA@@sm1/u8/body_arms.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «голова»?", "type": "single", "options": [{"text": "fingers"}, {"text": "hand"}, {"text": "head"}, {"text": "knee"}], "correct": [2]}, {"q": "Как по-английски «пальцы рук»?", "type": "single", "options": [{"text": "fingers"}, {"text": "hand"}, {"text": "knee"}, {"text": "leg"}], "correct": [0]}, {"q": "Как по-английски «кисть руки»?", "type": "single", "options": [{"text": "hand"}, {"text": "knee"}, {"text": "leg"}, {"text": "toes"}], "correct": [0]}, {"q": "Как по-английски «колено»?", "type": "single", "options": [{"text": "foot"}, {"text": "knee"}, {"text": "leg"}, {"text": "toes"}], "correct": [1]}, {"q": "Как по-английски «нога»?", "type": "single", "options": [{"text": "arms"}, {"text": "foot"}, {"text": "leg"}, {"text": "toes"}], "correct": [2]}, {"q": "Как по-английски «пальцы ног»?", "type": "single", "options": [{"text": "arms"}, {"text": "foot"}, {"text": "head"}, {"text": "toes"}], "correct": [3]}, {"q": "Как по-английски «ступня»?", "type": "single", "options": [{"text": "arms"}, {"text": "fingers"}, {"text": "foot"}, {"text": "head"}], "correct": [2]}, {"q": "Как по-английски «руки (от плеча)»?", "type": "single", "options": [{"text": "arms"}, {"text": "fingers"}, {"text": "hand"}, {"text": "head"}], "correct": [0]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Послушай слово и выбери его", "type": "single", "audio_tts": "head", "options": [{"text": "head"}, {"text": "fingers"}, {"text": "hand"}, {"text": "knee"}], "correct": [0]}, {"q": "Послушай слово и выбери его", "type": "single", "audio_tts": "fingers", "options": [{"text": "hand"}, {"text": "fingers"}, {"text": "knee"}, {"text": "leg"}], "correct": [1]}, {"q": "Послушай слово и выбери его", "type": "single", "audio_tts": "hand", "options": [{"text": "knee"}, {"text": "leg"}, {"text": "hand"}, {"text": "toes"}], "correct": [2]}, {"q": "Послушай слово и выбери его", "type": "single", "audio_tts": "knee", "options": [{"text": "leg"}, {"text": "toes"}, {"text": "foot"}, {"text": "knee"}], "correct": [3]}, {"q": "Послушай слово и выбери его", "type": "single", "audio_tts": "leg", "options": [{"text": "leg"}, {"text": "toes"}, {"text": "foot"}, {"text": "arms"}], "correct": [0]}, {"q": "Послушай слово и выбери его", "type": "single", "audio_tts": "toes", "options": [{"text": "foot"}, {"text": "toes"}, {"text": "arms"}, {"text": "head"}], "correct": [1]}, {"q": "Послушай слово и выбери его", "type": "single", "audio_tts": "foot", "options": [{"text": "arms"}, {"text": "head"}, {"text": "foot"}, {"text": "fingers"}], "correct": [2]}, {"q": "Послушай слово и выбери его", "type": "single", "audio_tts": "arms", "options": [{"text": "head"}, {"text": "fingers"}, {"text": "hand"}, {"text": "arms"}], "correct": [3]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'match', replace($blk${"title": "Найди пару: соедини картинку и слово", "pairs": [{"left_image": "@@MEDIA@@sm1/u8/body_head.webp", "right": "head", "right_audio_tts": "head"}, {"left_image": "@@MEDIA@@sm1/u8/body_fingers.webp", "right": "fingers", "right_audio_tts": "fingers"}, {"left_image": "@@MEDIA@@sm1/u8/body_hand.webp", "right": "hand", "right_audio_tts": "hand"}, {"left_image": "@@MEDIA@@sm1/u8/body_knee.webp", "right": "knee", "right_audio_tts": "knee"}, {"left_image": "@@MEDIA@@sm1/u8/body_leg.webp", "right": "leg", "right_audio_tts": "leg"}, {"left_image": "@@MEDIA@@sm1/u8/body_toes.webp", "right": "toes", "right_audio_tts": "toes"}, {"left_image": "@@MEDIA@@sm1/u8/body_foot.webp", "right": "foot", "right_audio_tts": "foot"}, {"left_image": "@@MEDIA@@sm1/u8/body_arms.webp", "right": "arms", "right_audio_tts": "arms"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:180px\"></p><h3>Основная часть позади — ты большой молодец! 🎉</h3><p>Добро пожаловать в дополнительную часть домашнего задания! Эти задания можно выполнить по желанию, НО если ты выполнишь их, то будешь нереально крут!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'text', replace($blk${"html": "<p>Давай повторим всё, что выучили с тобой на уроке:</p><p><img src=\"@@MEDIA@@sm1/u8/vocab_body.webp\" alt=\"Vocabulary — The Body\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'speaking', replace($blk${"title": "Мой монстр 🎤", "html": "<p>Нарисуй своего монстра и расскажи, какие у него части тела! Я уверена, у тебя получится очень красиво!</p><p><b>Пример:</b> <i>2 legs, 4 arms, 10 teeth.</i></p>", "image": "@@MEDIA@@sm1/u8/monster_draw.webp", "sample": "", "sample_tts": "2 legs, 4 arms, 10 teeth.", "needs_review": true}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'exact_input', replace($blk${"items": [{"prompt": "Задание для настоящих чемпионов! 🏆 Впиши слова! Напиши по-английски: голова", "accept": ["head", "Head"], "audio_tts": "head"}, {"prompt": "Напиши по-английски: пальцы рук", "accept": ["fingers", "Fingers"], "audio_tts": "fingers"}, {"prompt": "Напиши по-английски: кисть руки", "accept": ["hand", "Hand"], "audio_tts": "hand"}, {"prompt": "Напиши по-английски: колено", "accept": ["knee", "Knee"], "audio_tts": "knee"}, {"prompt": "Напиши по-английски: нога", "accept": ["leg", "Leg"], "audio_tts": "leg"}, {"prompt": "Напиши по-английски: пальцы ног", "accept": ["toes", "Toes"], "audio_tts": "toes"}, {"prompt": "Напиши по-английски: ступня", "accept": ["foot", "Foot"], "audio_tts": "foot"}, {"prompt": "Напиши по-английски: руки (от плеча)", "accept": ["arms", "Arms"], "audio_tts": "arms"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_star.webp\" alt=\"\" style=\"height:180px\"></p><h3>Поздравляю! Ты завершил домашнее задание, ты замечательный ученик! 🌟</h3><p>За это лови звёздочку :)</p><p>Увидимся на занятии!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 9);
end
$mig$;
