-- SM1: починка 36 старых уроков (Unit 0–5), 07.10.2026.
-- Собрано скриптом из проверки docs/SM1_проверка_старых_уроков.md.
-- Картинки base64 не переписываются: правки идут через jsonb_set / replace по тексту
-- без base64 / перестановку элементов массива на сервере.
--
-- ОТКАТ: исходные payload всех 513 блоков курса лежат в classroom_blocks_backup_sm1_20261007
-- (id, payload_text — полностью, с base64), уроков — в classroom_lessons_backup_sm1_20261007.
--   update classroom_blocks b set payload = k.payload_text::jsonb, updated_at = now()
--     from classroom_blocks_backup_sm1_20261007 k where k.id = b.id;          -- все блоки
--   (или с условием and b.id = '<id>' — один блок)
--   update classroom_lessons set sort_order = 100 + sort_order where unit_id = '<unit0>';  -- затем
--   update classroom_lessons l set sort_order = k.sort_order, title = k.title
--     from classroom_lessons_backup_sm1_20261007 k where k.id = l.id;

-- 0. Бэкап (сделан до первой правки)
create table if not exists classroom_blocks_backup_sm1_20261007 as
select b.id, b.lesson_id, b.type, b.sort_order, b.payload::text as payload_text, b.updated_at, now() as saved_at
  from classroom_blocks b join classroom_lessons l on l.id = b.lesson_id
  join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
 where c.slug = 'sm1';
create table if not exists classroom_lessons_backup_sm1_20261007 as
select l.id, l.title, l.sort_order, l.updated_at, now() as saved_at
  from classroom_lessons l join classroom_units u on u.id = l.unit_id join classroom_courses c on c.id = u.course_id
 where c.slug = 'sm1';
alter table classroom_blocks_backup_sm1_20261007 enable row level security;
alter table classroom_lessons_backup_sm1_20261007 enable row level security;

-- 7. Тест Unit 0 — последним уроком юнита, название «Unit 0 Test»
update classroom_lessons set sort_order = 100 where id = '436d7600-4022-4e42-967c-f30e9e8f16b4';
update classroom_lessons set sort_order = 1 where id = '9ad9086c-a2c7-4af7-8a01-92119918e456';  -- HW2
update classroom_lessons set sort_order = 2 where id = 'a56bc2b0-cd78-466e-9dcb-da787da7d949';  -- HW3
update classroom_lessons set sort_order = 3 where id = '71133446-3777-4dbd-a5a2-1ba78fe82fe9';  -- HW4
update classroom_lessons set sort_order = 4, title = 'Unit 0 Test', updated_at = now() where id = '436d7600-4022-4e42-967c-f30e9e8f16b4';

-- Блоки. Функция-помощник применяет к payload список операций; все значения — текст,
-- base64 не переписывается. Операции переприменяемые: повторный прогон ничего не ломает
-- (заглушка звука чистится, только если это ещё ВАШ-ПРОЕКТ; перестановка вариантов
-- узнаёт уже переставленный вопрос). Через MCP update идёт только в форме CTE (with … update).
-- Операции: s — поставить значение, c — убрать заглушку ВАШ-ПРОЕКТ, r — замена текста,
-- g — groups[].title → name, p — [вопрос, перестановка, новый correct, тексты до, correct до].
create or replace function sm1fix_apply(p jsonb, ops jsonb) returns jsonb
language plpgsql as $f$
declare o jsonb; qi int; arr jsonb; perm jsonb; i int; t text; cur jsonb;
begin
  for o in select * from jsonb_array_elements(ops) loop
    if o ? 's' then          -- ["s": [path[], value]]  — поставить значение (без base64)
      p := jsonb_set(p, array(select jsonb_array_elements_text(o->'s'->0)), o->'s'->1, true);
    elsif o ? 'c' then       -- ["c": path[]] — убрать заглушку ВАШ-ПРОЕКТ (настоящий звук не трогаем)
      if p #>> array(select jsonb_array_elements_text(o->'c')) like '%ВАШ-ПРОЕКТ%' then
        p := jsonb_set(p, array(select jsonb_array_elements_text(o->'c')), '""'::jsonb, false);
      end if;
    elsif o ? 'r' then       -- ["r": [old, new]]  — замена текста (в base64 таких строк нет)
      t := p::text;
      if position(o->'r'->>0 in t) > 0 then
        p := replace(t, o->'r'->>0, o->'r'->>1)::jsonb;
      elsif position(o->'r'->>1 in t) = 0 then
        raise exception 'нет текста: %', left(o->'r'->>0, 60);
      end if;
    elsif o ? 'g' then       -- groups[].title -> name
      p := jsonb_set(p, '{groups}', (select jsonb_agg(case when g ? 'title' and not g ? 'name'
             then (g - 'title') || jsonb_build_object('name', g->'title') else g end order by n)
             from jsonb_array_elements(p->'groups') with ordinality e(g, n)));
    elsif o ? 'p' then       -- ["p": [qi, perm[], correct[]]] — переставить варианты целиком
      qi := (o->'p'->>0)::int; perm := o->'p'->1; arr := '[]'::jsonb;
      -- o->'p'->3 — тексты вариантов до перестановки, o->'p'->4 — correct до неё:
      -- повторный прогон узнаёт уже переставленный вопрос и пропускает его
      cur := (select coalesce(jsonb_agg(x->'text' order by n), '[]') from jsonb_array_elements(p->'questions'->qi->'options') with ordinality e(x, n));
      if cur = o->'p'->3 and p->'questions'->qi->'correct' = o->'p'->4 then
        for i in 0 .. jsonb_array_length(perm) - 1 loop
          arr := arr || jsonb_build_array(p->'questions'->qi->'options'->((perm->>i)::int));
        end loop;
        p := jsonb_set(p, array['questions', qi::text, 'options'], arr);
        p := jsonb_set(p, array['questions', qi::text, 'correct'], o->'p'->2);
      elsif p->'questions'->qi->'correct' = o->'p'->2 and cur = (select jsonb_agg(o->'p'->3->((j)::int) order by n) from jsonb_array_elements_text(perm) with ordinality e(j, n)) then
        null;  -- уже переставлено
      else
        raise exception 'вопрос % не в ожидаемом состоянии', qi;
      end if;
    end if;
  end loop;
  return p;
end $f$;

with v(id, ops) as (values
('20b7e084-a229-4a8b-afbc-a978289a9f8c', $o$[{"c": ["cards", "0", "audio"]}, {"s": [["cards", "0", "audio_tts"], "friends"]}, {"c": ["cards", "1", "audio"]}, {"s": [["cards", "1", "audio_tts"], "Thunder"]}, {"c": ["cards", "2", "audio"]}, {"s": [["cards", "2", "audio_tts"], "Misty"]}, {"c": ["cards", "3", "audio"]}, {"s": [["cards", "3", "audio_tts"], "Whisper"]}, {"c": ["cards", "4", "audio"]}, {"s": [["cards", "4", "audio_tts"], "Flash"]}]$o$)  -- U0 Homework 1 b2 (flashcards): c/s,
('0c5031ef-6098-4fa9-8424-6d4684e6e6b9', $o$[{"c": ["cards", "0", "audio"]}, {"s": [["cards", "0", "audio_tts"], "friends"]}, {"c": ["cards", "1", "audio"]}, {"s": [["cards", "1", "audio_tts"], "Thunder"]}, {"c": ["cards", "2", "audio"]}, {"s": [["cards", "2", "audio_tts"], "Misty"]}, {"c": ["cards", "3", "audio"]}, {"s": [["cards", "3", "audio_tts"], "Whisper"]}, {"c": ["cards", "4", "audio"]}, {"s": [["cards", "4", "audio_tts"], "Flash"]}]$o$)  -- U0 Homework 1 b3 (flashcards): c/s,
('6d322769-b435-4220-9704-1d3a308e16f6', $o$[{"s": [["pairs", "1", "right"], "Тандер"]}, {"s": [["pairs", "2", "right"], "Мисти"]}, {"s": [["pairs", "3", "right"], "Виспер"]}, {"s": [["pairs", "4", "right"], "Флэш"]}, {"s": [["needs_review"], false]}]$o$)  -- U0 Homework 1 b4 (match): s,
('847fcb5b-2167-4143-a821-02528c4b6b32', $o$[{"s": [["questions", "1", "q"], "Как по-английски пишется имя «Тандер»?"]}, {"s": [["questions", "2", "q"], "Как по-английски пишется имя «Мисти»?"]}, {"s": [["questions", "3", "q"], "Как по-английски пишется имя «Виспер»?"]}, {"s": [["questions", "4", "q"], "Как по-английски пишется имя «Флэш»?"]}, {"p": [0, [1, 4, 3, 2, 0], [4], ["friends", "Thunder", "Misty", "Whisper", "Flash"], [0]]}, {"p": [1, [2, 0, 3, 1, 4], [3], ["friends", "Thunder", "Misty", "Whisper", "Flash"], [1]]}, {"p": [2, [0, 4, 2, 3, 1], [2], ["friends", "Thunder", "Misty", "Whisper", "Flash"], [2]]}, {"p": [3, [1, 2, 4, 0, 3], [4], ["friends", "Thunder", "Misty", "Whisper", "Flash"], [3]]}, {"p": [4, [3, 4, 2, 0, 1], [1], ["friends", "Thunder", "Misty", "Whisper", "Flash"], [4]]}, {"s": [["needs_review"], false]}]$o$)  -- U0 Homework 1 b5 (quiz): p/s,
('5a18a661-3695-4216-b879-00fd0bf43c35', $o$[{"c": ["pairs", "0", "left_audio"]}, {"s": [["pairs", "0", "left_audio_tts"], "friends"]}, {"c": ["pairs", "1", "left_audio"]}, {"s": [["pairs", "1", "left_audio_tts"], "Thunder"]}, {"c": ["pairs", "2", "left_audio"]}, {"s": [["pairs", "2", "left_audio_tts"], "Misty"]}, {"c": ["pairs", "3", "left_audio"]}, {"s": [["pairs", "3", "left_audio_tts"], "Whisper"]}, {"c": ["pairs", "4", "left_audio"]}, {"s": [["pairs", "4", "left_audio_tts"], "Flash"]}, {"s": [["pairs", "1", "right"], "Тандер"]}, {"s": [["pairs", "2", "right"], "Мисти"]}, {"s": [["pairs", "3", "right"], "Виспер"]}, {"s": [["pairs", "4", "right"], "Флэш"]}, {"s": [["needs_review"], false]}]$o$)  -- U0 Homework 1 b6 (match): c/s,
('c4ae197c-aa5c-4fe8-ac67-e3a6d04fbcc9', $o$[{"c": ["questions", "0", "audio"]}, {"c": ["questions", "1", "audio"]}, {"c": ["questions", "2", "audio"]}, {"s": [["questions", "0", "options"], [{"text": "S"}, {"text": "I"}, {"text": "T"}]]}, {"s": [["questions", "0", "correct"], [2]]}, {"s": [["questions", "0", "audio_tts"], "tiger"]}, {"s": [["questions", "1", "options"], [{"text": "S"}, {"text": "I"}, {"text": "T"}]]}, {"s": [["questions", "1", "correct"], [0]]}, {"s": [["questions", "1", "audio_tts"], "sun"]}, {"s": [["questions", "2", "options"], [{"text": "S"}, {"text": "I"}, {"text": "T"}]]}, {"s": [["questions", "2", "correct"], [1]]}, {"s": [["questions", "2", "audio_tts"], "iguana"]}, {"p": [0, [1, 2, 0], [1], ["S", "I", "T"], [2]]}, {"p": [1, [1, 0, 2], [1], ["S", "I", "T"], [0]]}, {"p": [2, [1, 0, 2], [0], ["S", "I", "T"], [1]]}, {"s": [["needs_review"], false]}]$o$)  -- U0 Homework 1 b8 (quiz): c/p/s,
('3b0fad22-5d08-49c9-a98f-86e36ec5d94e', $o$[{"p": [0, [2, 1, 0], [2], ["Thunder", "Misty", "Whisper"], [0]]}, {"p": [1, [1, 2, 0], [1], ["Whisper", "Misty", "Flash"], [2]]}, {"p": [2, [2, 0, 1], [1], ["Misty", "Whisper", "Mindy"], [0]]}, {"p": [3, [2, 1, 0], [1], ["Willy", "Whisper", "Thunder"], [1]]}]$o$)  -- U0 Homework 1 b9 (quiz): p,
('5c8f7fb3-4d25-44a5-a9c5-7de80396884a', $o$[{"c": ["audio"]}, {"s": [["audio_tts"], "Hi, I'm Whisper. What's your name? Hi, I'm Thunder. What a nice name! Hi, I'm Flash. What's your name? Hi, I'm Misty. What a nice name!"]}]$o$)  -- U0 Homework 1 b10 (order): c/s,
('f9cde5a6-7879-479d-952e-3b05ec4c2b57', $o$[{"c": ["audio"]}, {"s": [["audio_tts"], "What's your name?"]}]$o$)  -- U0 Homework 1 b12 (task): c/s,
('c85f5331-62ee-42e9-b833-46a549aa81da', $o$[{"s": [["pairs", "0", "right"], "Misty"]}, {"s": [["pairs", "1", "right"], "Flash"]}, {"s": [["pairs", "2", "right"], "Thunder"]}, {"s": [["pairs", "3", "right"], "Whisper"]}, {"s": [["needs_review"], false]}]$o$)  -- U0 Homework 1 b13 (match): s,
('52c9c700-8fc1-4ff2-a867-9e899c926c54', $o$[{"c": ["cards", "0", "audio"]}, {"s": [["cards", "0", "audio_tts"], "one"]}, {"c": ["cards", "1", "audio"]}, {"s": [["cards", "1", "audio_tts"], "two"]}, {"c": ["cards", "2", "audio"]}, {"s": [["cards", "2", "audio_tts"], "three"]}, {"c": ["cards", "3", "audio"]}, {"s": [["cards", "3", "audio_tts"], "four"]}, {"c": ["cards", "4", "audio"]}, {"s": [["cards", "4", "audio_tts"], "five"]}, {"c": ["cards", "5", "audio"]}, {"s": [["cards", "5", "audio_tts"], "six"]}, {"c": ["cards", "6", "audio"]}, {"s": [["cards", "6", "audio_tts"], "seven"]}, {"c": ["cards", "7", "audio"]}, {"s": [["cards", "7", "audio_tts"], "eight"]}, {"c": ["cards", "8", "audio"]}, {"s": [["cards", "8", "audio_tts"], "nine"]}, {"c": ["cards", "9", "audio"]}, {"s": [["cards", "9", "audio_tts"], "ten"]}]$o$)  -- U0 Homework 2 b2 (flashcards): c/s,
('6436d0c3-1888-4def-8450-6c7bed525418', $o$[{"c": ["cards", "0", "audio"]}, {"s": [["cards", "0", "audio_tts"], "one"]}, {"c": ["cards", "1", "audio"]}, {"s": [["cards", "1", "audio_tts"], "two"]}, {"c": ["cards", "2", "audio"]}, {"s": [["cards", "2", "audio_tts"], "three"]}, {"c": ["cards", "3", "audio"]}, {"s": [["cards", "3", "audio_tts"], "four"]}, {"c": ["cards", "4", "audio"]}, {"s": [["cards", "4", "audio_tts"], "five"]}, {"c": ["cards", "5", "audio"]}, {"s": [["cards", "5", "audio_tts"], "six"]}, {"c": ["cards", "6", "audio"]}, {"s": [["cards", "6", "audio_tts"], "seven"]}, {"c": ["cards", "7", "audio"]}, {"s": [["cards", "7", "audio_tts"], "eight"]}, {"c": ["cards", "8", "audio"]}, {"s": [["cards", "8", "audio_tts"], "nine"]}, {"c": ["cards", "9", "audio"]}, {"s": [["cards", "9", "audio_tts"], "ten"]}]$o$)  -- U0 Homework 2 b3 (flashcards): c/s,
('ad0b82eb-2471-460c-85db-6bb7cb83938d', $o$[{"p": [0, [2, 0, 3, 1], [1], ["one", "two", "three", "four"], [0]]}, {"p": [1, [1, 0, 2, 3], [1], ["two", "three", "four", "five"], [0]]}, {"p": [2, [3, 1, 0, 2], [2], ["three", "four", "five", "six"], [0]]}, {"p": [3, [2, 3, 1, 0], [3], ["four", "five", "six", "seven"], [0]]}, {"p": [4, [1, 3, 0, 2], [2], ["five", "six", "seven", "eight"], [0]]}, {"p": [5, [1, 2, 3, 0], [3], ["six", "seven", "eight", "nine"], [0]]}, {"p": [6, [3, 1, 2, 0], [3], ["seven", "eight", "nine", "ten"], [0]]}, {"p": [7, [0, 3, 1, 2], [2], ["one", "eight", "nine", "ten"], [1]]}, {"p": [8, [1, 3, 2, 0], [2], ["one", "two", "nine", "ten"], [2]]}, {"p": [9, [1, 2, 0, 3], [3], ["one", "two", "three", "ten"], [3]]}]$o$)  -- U0 Homework 2 b4 (quiz): p,
('6ef4eb32-5bd9-4450-a7a7-c8128f07bb64', $o$[{"p": [0, [1, 0, 2, 3], [1], ["один", "два", "три", "четыре"], [0]]}, {"p": [1, [3, 1, 0, 2], [2], ["два", "три", "четыре", "пять"], [0]]}, {"p": [2, [1, 2, 0, 3], [2], ["три", "четыре", "пять", "шесть"], [0]]}, {"p": [3, [3, 2, 1, 0], [3], ["четыре", "пять", "шесть", "семь"], [0]]}, {"p": [4, [2, 1, 3, 0], [3], ["пять", "шесть", "семь", "восемь"], [0]]}, {"p": [5, [2, 3, 0, 1], [2], ["шесть", "семь", "восемь", "девять"], [0]]}, {"p": [6, [3, 0, 1, 2], [1], ["семь", "восемь", "девять", "десять"], [0]]}, {"p": [7, [2, 0, 3, 1], [3], ["один", "восемь", "девять", "десять"], [1]]}, {"p": [8, [0, 2, 3, 1], [1], ["один", "два", "девять", "десять"], [2]]}, {"p": [9, [0, 2, 3, 1], [2], ["один", "два", "три", "десять"], [3]]}]$o$)  -- U0 Homework 2 b6 (quiz): p,
('cccfc96c-90c1-4cc9-86ad-5259d46b87c1', $o$[{"c": ["questions", "0", "audio"]}, {"s": [["questions", "0", "audio_tts"], "one"]}, {"c": ["questions", "1", "audio"]}, {"s": [["questions", "1", "audio_tts"], "two"]}, {"c": ["questions", "2", "audio"]}, {"s": [["questions", "2", "audio_tts"], "three"]}, {"c": ["questions", "3", "audio"]}, {"s": [["questions", "3", "audio_tts"], "four"]}, {"c": ["questions", "4", "audio"]}, {"s": [["questions", "4", "audio_tts"], "five"]}, {"c": ["questions", "5", "audio"]}, {"s": [["questions", "5", "audio_tts"], "six"]}, {"c": ["questions", "6", "audio"]}, {"s": [["questions", "6", "audio_tts"], "seven"]}, {"c": ["questions", "7", "audio"]}, {"s": [["questions", "7", "audio_tts"], "eight"]}, {"c": ["questions", "8", "audio"]}, {"s": [["questions", "8", "audio_tts"], "nine"]}, {"c": ["questions", "9", "audio"]}, {"s": [["questions", "9", "audio_tts"], "ten"]}, {"p": [0, [3, 1, 0, 2], [2], ["one", "two", "three", "four"], [0]]}, {"p": [1, [3, 0, 1, 2], [1], ["two", "three", "four", "five"], [0]]}, {"p": [2, [2, 3, 0, 1], [2], ["three", "four", "five", "six"], [0]]}, {"p": [3, [3, 1, 2, 0], [3], ["four", "five", "six", "seven"], [0]]}, {"p": [4, [1, 2, 3, 0], [3], ["five", "six", "seven", "eight"], [0]]}, {"p": [5, [0, 3, 2, 1], [0], ["six", "seven", "eight", "nine"], [0]]}, {"p": [6, [1, 3, 0, 2], [2], ["seven", "eight", "nine", "ten"], [0]]}, {"p": [7, [3, 2, 0, 1], [3], ["one", "eight", "nine", "ten"], [1]]}, {"p": [8, [0, 1, 3, 2], [3], ["one", "two", "nine", "ten"], [2]]}, {"p": [9, [2, 3, 1, 0], [1], ["one", "two", "three", "ten"], [3]]}]$o$)  -- U0 Homework 2 b7 (quiz): c/p/s,
('6cd669eb-5d0c-43cd-8705-89c2553250bd', $o$[{"c": ["questions", "0", "audio"]}, {"c": ["questions", "1", "audio"]}, {"c": ["questions", "2", "audio"]}, {"s": [["questions", "0", "options"], [{"text": "P"}, {"text": "A"}, {"text": "N"}]]}, {"s": [["questions", "0", "correct"], [2]]}, {"s": [["questions", "0", "audio_tts"], "nest"]}, {"s": [["questions", "1", "options"], [{"text": "P"}, {"text": "A"}, {"text": "N"}]]}, {"s": [["questions", "1", "correct"], [1]]}, {"s": [["questions", "1", "audio_tts"], "apple"]}, {"s": [["questions", "2", "options"], [{"text": "P"}, {"text": "A"}, {"text": "N"}]]}, {"s": [["questions", "2", "correct"], [0]]}, {"s": [["questions", "2", "audio_tts"], "panda"]}, {"p": [0, [1, 2, 0], [1], ["P", "A", "N"], [2]]}, {"p": [1, [2, 1, 0], [1], ["P", "A", "N"], [1]]}, {"p": [2, [1, 0, 2], [1], ["P", "A", "N"], [0]]}, {"s": [["needs_review"], false]}]$o$)  -- U0 Homework 2 b9 (quiz): c/p/s,
('6c418bc1-f567-4991-b0f8-1f3f7febbfe0', $o$[{"s": [["needs_review"], false]}]$o$)  -- U0 Homework 2 b10 (match): s,
('3499f4be-fd10-4714-be0d-3021eaa3f409', $o$[{"c": ["questions", "0", "audio"]}, {"s": [["questions", "0", "audio_tts"], "Hi, I'm Misty. I'm six."]}, {"c": ["questions", "1", "audio"]}, {"s": [["questions", "1", "audio_tts"], "Hi, I'm Whisper. I'm eight."]}, {"c": ["questions", "2", "audio"]}, {"s": [["questions", "2", "audio_tts"], "Hi, I'm Flash. I'm eight."]}, {"c": ["questions", "3", "audio"]}, {"s": [["questions", "3", "audio_tts"], "Hi, I'm Thunder. I'm seven."]}, {"p": [0, [2, 0, 1, 3], [1], ["six", "five", "seven", "four"], [0]]}, {"p": [1, [1, 2, 3, 0], [3], ["eight", "seven", "nine", "six"], [0]]}, {"p": [2, [1, 0, 2, 3], [1], ["eight", "seven", "ten", "eleven"], [0]]}, {"p": [3, [0, 1, 3, 2], [0], ["seven", "six", "nine", "eight"], [0]]}, {"s": [["needs_review"], false]}]$o$)  -- U0 Homework 2 b12 (quiz): c/p/s,
('a33b1788-d992-44fb-a28a-8454daba0cd3', $o$[{"c": ["audio"]}, {"s": [["audio_tts"], "How old are you?"]}]$o$)  -- U0 Homework 2 b13 (task): c/s,
('f08288ca-e59c-4029-87fe-ede038465c82', $o$[{"c": ["cards", "0", "audio"]}, {"s": [["cards", "0", "audio_tts"], "yellow"]}, {"c": ["cards", "1", "audio"]}, {"s": [["cards", "1", "audio_tts"], "red"]}, {"c": ["cards", "2", "audio"]}, {"s": [["cards", "2", "audio_tts"], "orange"]}, {"c": ["cards", "3", "audio"]}, {"s": [["cards", "3", "audio_tts"], "purple"]}, {"c": ["cards", "4", "audio"]}, {"s": [["cards", "4", "audio_tts"], "blue"]}, {"c": ["cards", "5", "audio"]}, {"s": [["cards", "5", "audio_tts"], "green"]}]$o$)  -- U0 Homework 3 b2 (flashcards): c/s,
('36aa365e-b364-4699-83ee-2da3e86474a2', $o$[{"c": ["cards", "0", "audio"]}, {"s": [["cards", "0", "audio_tts"], "yellow"]}, {"c": ["cards", "1", "audio"]}, {"s": [["cards", "1", "audio_tts"], "red"]}, {"c": ["cards", "2", "audio"]}, {"s": [["cards", "2", "audio_tts"], "orange"]}, {"c": ["cards", "3", "audio"]}, {"s": [["cards", "3", "audio_tts"], "purple"]}, {"c": ["cards", "4", "audio"]}, {"s": [["cards", "4", "audio_tts"], "blue"]}, {"c": ["cards", "5", "audio"]}, {"s": [["cards", "5", "audio_tts"], "green"]}]$o$)  -- U0 Homework 3 b3 (flashcards): c/s,
('42c156df-4dff-4d7b-b3ef-643e88f05335', $o$[{"p": [0, [1, 2, 3, 0], [3], ["yellow", "red", "orange", "purple"], [0]]}, {"p": [1, [2, 0, 3, 1], [1], ["red", "orange", "purple", "blue"], [0]]}, {"p": [2, [1, 3, 2, 0], [3], ["orange", "purple", "blue", "green"], [0]]}, {"p": [3, [1, 2, 3, 0], [0], ["yellow", "purple", "blue", "green"], [1]]}, {"p": [4, [1, 3, 2, 0], [2], ["yellow", "red", "blue", "green"], [2]]}, {"p": [5, [1, 2, 3, 0], [2], ["yellow", "red", "orange", "green"], [3]]}]$o$)  -- U0 Homework 3 b4 (quiz): p,
('d029f089-ce05-457a-ab7b-320af1acea79', $o$[{"p": [0, [3, 0, 1, 2], [1], ["жёлтый", "красный", "оранжевый", "фиолетовый"], [0]]}, {"p": [1, [2, 3, 0, 1], [2], ["красный", "оранжевый", "фиолетовый", "синий"], [0]]}, {"p": [2, [1, 0, 3, 2], [1], ["оранжевый", "фиолетовый", "синий", "зелёный"], [0]]}, {"p": [3, [0, 3, 2, 1], [3], ["жёлтый", "фиолетовый", "синий", "зелёный"], [1]]}, {"p": [4, [0, 1, 3, 2], [3], ["жёлтый", "красный", "синий", "зелёный"], [2]]}, {"p": [5, [0, 2, 3, 1], [2], ["жёлтый", "красный", "оранжевый", "зелёный"], [3]]}]$o$)  -- U0 Homework 3 b6 (quiz): p,
('3308f0d6-69d7-47ef-89b2-507426b76032', $o$[{"c": ["questions", "0", "audio"]}, {"s": [["questions", "0", "audio_tts"], "yellow"]}, {"c": ["questions", "1", "audio"]}, {"s": [["questions", "1", "audio_tts"], "red"]}, {"c": ["questions", "2", "audio"]}, {"s": [["questions", "2", "audio_tts"], "orange"]}, {"c": ["questions", "3", "audio"]}, {"s": [["questions", "3", "audio_tts"], "purple"]}, {"c": ["questions", "4", "audio"]}, {"s": [["questions", "4", "audio_tts"], "blue"]}, {"c": ["questions", "5", "audio"]}, {"s": [["questions", "5", "audio_tts"], "green"]}, {"p": [0, [3, 1, 0, 2], [2], ["yellow", "red", "orange", "purple"], [0]]}, {"p": [1, [2, 0, 3, 1], [1], ["red", "orange", "purple", "blue"], [0]]}, {"p": [2, [2, 1, 0, 3], [2], ["orange", "purple", "blue", "green"], [0]]}, {"p": [3, [0, 3, 2, 1], [3], ["yellow", "purple", "blue", "green"], [1]]}, {"p": [4, [0, 2, 1, 3], [1], ["yellow", "red", "blue", "green"], [2]]}, {"p": [5, [3, 1, 0, 2], [0], ["yellow", "red", "orange", "green"], [3]]}]$o$)  -- U0 Homework 3 b7 (quiz): c/p/s,
('294c3f5b-5833-4302-a166-2f460eeda1c5', $o$[{"c": ["pairs", "0", "left_audio"]}, {"s": [["pairs", "0", "left_audio_tts"], "yellow"]}, {"c": ["pairs", "1", "left_audio"]}, {"s": [["pairs", "1", "left_audio_tts"], "red"]}, {"c": ["pairs", "2", "left_audio"]}, {"s": [["pairs", "2", "left_audio_tts"], "orange"]}, {"c": ["pairs", "3", "left_audio"]}, {"s": [["pairs", "3", "left_audio_tts"], "purple"]}, {"c": ["pairs", "4", "left_audio"]}, {"s": [["pairs", "4", "left_audio_tts"], "blue"]}, {"c": ["pairs", "5", "left_audio"]}, {"s": [["pairs", "5", "left_audio_tts"], "green"]}]$o$)  -- U0 Homework 3 b8 (match): c/s,
('09283dfc-b38a-4d23-9961-4e159d1b2dff', $o$[{"c": ["questions", "0", "audio"]}, {"c": ["questions", "1", "audio"]}, {"c": ["questions", "2", "audio"]}, {"s": [["questions", "0", "options"], [{"text": "M"}, {"text": "D"}, {"text": "G"}]]}, {"s": [["questions", "0", "correct"], [1]]}, {"s": [["questions", "0", "audio_tts"], "dog"]}, {"s": [["questions", "1", "options"], [{"text": "M"}, {"text": "D"}, {"text": "G"}]]}, {"s": [["questions", "1", "correct"], [0]]}, {"s": [["questions", "1", "audio_tts"], "mouse"]}, {"s": [["questions", "2", "options"], [{"text": "M"}, {"text": "D"}, {"text": "G"}]]}, {"s": [["questions", "2", "correct"], [2]]}, {"s": [["questions", "2", "audio_tts"], "gorilla"]}, {"p": [0, [2, 1, 0], [1], ["M", "D", "G"], [1]]}, {"p": [1, [1, 2, 0], [2], ["M", "D", "G"], [0]]}, {"p": [2, [1, 0, 2], [2], ["M", "D", "G"], [2]]}, {"s": [["needs_review"], false]}]$o$)  -- U0 Homework 3 b10 (quiz): c/p/s,
('518395e4-6269-402c-bf7b-8b8f9cb1dece', $o$[{"s": [["pairs", "0", "right"], "yellow"]}, {"s": [["pairs", "1", "right"], "red"]}, {"s": [["pairs", "2", "right"], "orange"]}, {"s": [["pairs", "3", "right"], "green"]}, {"s": [["pairs", "4", "right"], "purple"]}, {"s": [["pairs", "5", "right"], "blue"]}]$o$)  -- U0 Homework 3 b11 (match): s,
('6a30a214-43cf-4246-b9a9-3c286bd4f25b', $o$[{"s": [["pairs", "0", "right"], "yellow"]}, {"s": [["pairs", "1", "right"], "red"]}, {"s": [["pairs", "2", "right"], "orange"]}, {"s": [["pairs", "3", "right"], "purple"]}, {"s": [["pairs", "4", "right"], "blue"]}, {"s": [["pairs", "5", "right"], "green"]}]$o$)  -- U0 Homework 3 b12 (match): s,
('272888e7-c55a-4256-a681-6e861769112f', $o$[{"c": ["questions", "0", "audio"]}, {"c": ["questions", "1", "audio"]}, {"s": [["questions", "0", "options"], [{"text": "O"}, {"text": "C"}, {"text": "K"}]]}, {"s": [["questions", "0", "correct"], [0]]}, {"s": [["questions", "0", "audio_tts"], "octopus"]}, {"s": [["questions", "1", "options"], [{"text": "O"}, {"text": "C"}, {"text": "K"}]]}, {"s": [["questions", "1", "correct"], [1, 2]]}, {"s": [["questions", "1", "audio_tts"], "car, kiwi"]}, {"p": [0, [2, 0, 1], [1], ["O", "C", "K"], [0]]}, {"p": [1, [1, 2, 0], [0, 1], ["O", "C", "K"], [1, 2]]}, {"s": [["needs_review"], false]}]$o$)  -- U0 Homework 4 b3 (quiz): c/p/s,
('9d02d3d0-64fe-4742-bab0-e3a31acd29b9', $o$[{"c": ["questions", "0", "audio"]}, {"s": [["questions", "0", "audio_tts"], "Look! A cat! Hello, cat! What's your name? — I'm Tabby. — What a nice name, Tabby!"]}, {"p": [0, [2, 3, 0, 1], [2], ["Tabby", "Tommy", "Mabby", "Kitty"], [0]]}, {"s": [["needs_review"], false]}]$o$)  -- U0 Homework 4 b5 (quiz): c/p/s,
('c6897eee-6edb-46bb-91ea-7aa76961824b', $o$[{"c": ["questions", "0", "audio"]}, {"c": ["questions", "1", "audio"]}, {"c": ["questions", "2", "audio"]}]$o$)  -- U0 Homework 4 b6 (quiz): c,
('6145687f-28c8-4a14-b577-b8b4126f1df9', $o$[{"s": [["pairs", "0", "right"], "Flash"]}, {"s": [["pairs", "1", "right"], "Misty"]}, {"s": [["pairs", "2", "right"], "Thunder"]}, {"s": [["pairs", "3", "right"], "Whisper"]}, {"s": [["title"], "Соедини героя и его имя"]}, {"s": [["needs_review"], false]}]$o$)  -- U0 Homework 4 b7 (match): s,
('315ec0b4-71b6-485c-90da-5a5bc243e557', $o$[{"c": ["questions", "0", "audio"]}]$o$)  -- U0 Test b3 (quiz): c,
('4a1f56f2-015e-45d0-bc61-51666911ddea', $o$[{"p": [0, [3, 4, 0, 1, 5, 2], [2], ["I'm", "your", "Flash", "name", "Hi", "nice"], [0]]}, {"p": [1, [2, 1, 4, 0, 5, 3], [1], ["I'm", "your", "Flash", "name", "Hi", "nice"], [1]]}, {"p": [2, [1, 4, 5, 0, 2, 3], [4], ["I'm", "your", "Flash", "name", "Hi", "nice"], [2]]}, {"p": [3, [4, 3, 0, 2, 1, 5], [1], ["I'm", "your", "Flash", "name", "Hi", "nice"], [3]]}, {"s": [["needs_review"], false]}]$o$)  -- U0 Test b4 (quiz): p/s,
('d4ac2555-3afb-4ba7-9fe1-4370f68909da', $o$[{"r": ["Чтобы найти дополнительное упражнение, вернись в личный кабинет и выбери урок SM1 Unit 1 Homework 1 (extra)!", "Дополнительные задания ждут тебя в конце этого урока!"]}]$o$)  -- U1 Homework 1 b1 (text): r,
('b3a078f3-7f61-433d-9d62-df463491e7ee', $o$[{"p": [0, [2, 3, 1, 0], [3], ["pen", "rubber", "pencil", "ruler"], [0]]}, {"p": [1, [3, 0, 2, 1], [1], ["rubber", "pencil", "ruler", "book"], [0]]}, {"p": [2, [3, 0, 2, 1], [1], ["pencil", "ruler", "book", "notebook"], [0]]}, {"p": [3, [3, 2, 1, 0], [3], ["ruler", "book", "notebook", "desk"], [0]]}, {"p": [4, [1, 0, 2, 3], [1], ["book", "notebook", "desk", "pencil case"], [0]]}, {"p": [5, [1, 2, 0, 3], [2], ["notebook", "desk", "pencil case", "bag"], [0]]}, {"p": [6, [1, 0, 2, 3], [1], ["desk", "pencil case", "bag", "paper"], [0]]}, {"p": [7, [2, 0, 3, 1], [3], ["pen", "pencil case", "bag", "paper"], [1]]}, {"p": [8, [0, 2, 1, 3], [1], ["pen", "rubber", "bag", "paper"], [2]]}, {"p": [9, [3, 2, 0, 1], [0], ["pen", "rubber", "pencil", "paper"], [3]]}]$o$)  -- U1 Homework 1 b3 (quiz): p,
('e9f77655-d06a-43b2-b062-3c5dd187b2d9', $o$[{"s": [["questions", "0", "options"], [{"text": "E"}, {"text": "U"}, {"text": "R"}]]}, {"s": [["questions", "0", "correct"], [0]]}, {"s": [["questions", "0", "audio_tts"], "egg"]}, {"s": [["questions", "1", "options"], [{"text": "E"}, {"text": "U"}, {"text": "R"}]]}, {"s": [["questions", "1", "correct"], [1]]}, {"s": [["questions", "1", "audio_tts"], "umbrella"]}, {"s": [["questions", "2", "options"], [{"text": "E"}, {"text": "U"}, {"text": "R"}]]}, {"s": [["questions", "2", "correct"], [2]]}, {"s": [["questions", "2", "audio_tts"], "red"]}, {"p": [0, [2, 0, 1], [1], ["E", "U", "R"], [0]]}, {"p": [1, [1, 0, 2], [0], ["E", "U", "R"], [1]]}, {"p": [2, [2, 1, 0], [0], ["E", "U", "R"], [2]]}, {"s": [["needs_review"], false]}]$o$)  -- U1 Homework 1 b18 (quiz): p/s,
('727b1f7a-cc74-4c1d-9794-690061d80bb8', $o$[{"p": [0, [5, 3, 2, 0, 1, 4], [3], ["pet", "net", "mum", "cup", "red", "rat"], [0]]}, {"p": [1, [5, 3, 2, 4, 1, 0], [4], ["pet", "net", "mum", "cup", "red", "rat"], [1]]}, {"p": [2, [1, 5, 0, 4, 3, 2], [5], ["pet", "net", "mum", "cup", "red", "rat"], [2]]}, {"p": [3, [2, 5, 3, 4, 0, 1], [2], ["pet", "net", "mum", "cup", "red", "rat"], [3]]}, {"p": [4, [3, 0, 1, 5, 2, 4], [5], ["pet", "net", "mum", "cup", "red", "rat"], [4]]}, {"p": [5, [0, 2, 1, 3, 4, 5], [5], ["pet", "net", "mum", "cup", "red", "rat"], [5]]}]$o$)  -- U1 Homework 1 b19 (quiz): p,
('8ea3f29b-2440-492f-99b8-c57abbb9e8f9', $o$[{"p": [0, [1, 0], [1], ["purple", "white"], [0]]}, {"p": [1, [1, 0], [1], ["pink", "red"], [0]]}, {"p": [2, [1, 0], [1], ["blue", "orange"], [0]]}, {"p": [3, [1, 0], [0], ["black", "yellow"], [1]]}, {"p": [4, [1, 0], [0], ["blue", "orange"], [1]]}, {"p": [5, [1, 0], [0], ["purple", "red"], [1]]}, {"p": [6, [1, 0], [1], ["blue", "green"], [0]]}, {"p": [7, [1, 0], [0], ["black", "white"], [1]]}]$o$)  -- U1 Homework 1 b21 (quiz): p,
('796690cb-43de-430f-b063-7e792181408a', $o$[{"s": [["questions", "0", "options"], [{"text": "H"}, {"text": "B"}, {"text": "F"}]]}, {"s": [["questions", "0", "correct"], [1]]}, {"s": [["questions", "0", "audio_tts"], "bed"]}, {"s": [["questions", "1", "options"], [{"text": "H"}, {"text": "B"}, {"text": "F"}]]}, {"s": [["questions", "1", "correct"], [2]]}, {"s": [["questions", "1", "audio_tts"], "fig"]}, {"s": [["questions", "2", "options"], [{"text": "H"}, {"text": "B"}, {"text": "F"}]]}, {"s": [["questions", "2", "correct"], [0]]}, {"s": [["questions", "2", "audio_tts"], "hat"]}, {"p": [0, [0, 2, 1], [2], ["H", "B", "F"], [1]]}, {"p": [1, [2, 0, 1], [0], ["H", "B", "F"], [2]]}, {"p": [2, [1, 2, 0], [2], ["H", "B", "F"], [0]]}, {"s": [["needs_review"], false]}]$o$)  -- U1 Homework 2 b3 (quiz): p/s,
('983d7c89-02fe-4ebd-86cd-a872501a7144', $o$[{"p": [0, [5, 0, 2, 3, 1, 4], [1], ["hat", "hippo", "bed", "rabbit", "fig", "frog"], [0]]}, {"p": [1, [0, 5, 1, 2, 3, 4], [2], ["hat", "hippo", "bed", "rabbit", "fig", "frog"], [1]]}, {"p": [2, [3, 0, 1, 4, 2, 5], [4], ["hat", "hippo", "bed", "rabbit", "fig", "frog"], [2]]}, {"p": [3, [2, 4, 5, 3, 0, 1], [3], ["hat", "hippo", "bed", "rabbit", "fig", "frog"], [3]]}, {"p": [4, [3, 2, 1, 0, 4, 5], [4], ["hat", "hippo", "bed", "rabbit", "fig", "frog"], [4]]}, {"p": [5, [4, 3, 0, 1, 2, 5], [5], ["hat", "hippo", "bed", "rabbit", "fig", "frog"], [5]]}]$o$)  -- U1 Homework 2 b4 (quiz): p,
('48bc4a51-9b19-441d-9c73-ede874f32c6d', $o$[{"p": [0, [1, 0], [0], ["Yes, it is.", "No, it isn't."], [1]]}, {"p": [1, [1, 0], [1], ["Yes, it is.", "No, it isn't."], [0]]}, {"p": [2, [1, 0], [1], ["Yes, it is.", "No, it isn't."], [0]]}, {"s": [["needs_review"], false]}]$o$)  -- U1 Homework 2 b12 (quiz): p/s,
('55489d60-e930-49c2-9e03-3adf657b79b0', $o$[{"p": [0, [0, 3, 1, 2], [0], ["Сядьте за свой стол, пожалуйста", "Откройте сумку, пожалуйста", "Закройте книгу, пожалуйста.", "Передайте мне ручку, пожалуйста"], [0]]}, {"p": [1, [2, 3, 0, 1], [2], ["Откройте сумку, пожалуйста", "Закройте книгу, пожалуйста.", "Передайте мне ручку, пожалуйста", "Напишите от одного до десяти."], [0]]}, {"p": [2, [3, 2, 1, 0], [3], ["Закройте книгу, пожалуйста.", "Передайте мне ручку, пожалуйста", "Напишите от одного до десяти.", "Встаньте, пожалуйста"], [0]]}, {"p": [3, [2, 1, 0, 3], [2], ["Передайте мне ручку, пожалуйста", "Напишите от одного до десяти.", "Встаньте, пожалуйста", "Садитесь, пожалуйста"], [0]]}, {"p": [4, [2, 0, 3, 1], [1], ["Напишите от одного до десяти.", "Встаньте, пожалуйста", "Садитесь, пожалуйста", "Выньте линейку, пожалуйста"], [0]]}, {"p": [5, [3, 0, 2, 1], [1], ["Встаньте, пожалуйста", "Садитесь, пожалуйста", "Выньте линейку, пожалуйста", "Уберите свою книгу, пожалуйста"], [0]]}, {"p": [6, [2, 3, 0, 1], [3], ["Сядьте за свой стол, пожалуйста", "Садитесь, пожалуйста", "Выньте линейку, пожалуйста", "Уберите свою книгу, пожалуйста"], [1]]}, {"p": [7, [0, 3, 2, 1], [2], ["Сядьте за свой стол, пожалуйста", "Откройте сумку, пожалуйста", "Выньте линейку, пожалуйста", "Уберите свою книгу, пожалуйста"], [2]]}, {"p": [8, [1, 0, 3, 2], [2], ["Сядьте за свой стол, пожалуйста", "Откройте сумку, пожалуйста", "Закройте книгу, пожалуйста.", "Уберите свою книгу, пожалуйста"], [3]]}]$o$)  -- U1 Homework 3 b2 (quiz): p,
('30b53761-1a7c-40e2-8482-5c66c9ee155a', $o$[{"p": [0, [1, 0, 3, 2], [1], ["Sit at your desk, please", "Open your bag, please", "Close your book, please", "Pass me a pen, please"], [0]]}, {"p": [1, [1, 2, 0, 3], [2], ["Open your bag, please", "Close your book, please", "Pass me a pen, please", "Write one to ten"], [0]]}, {"p": [2, [2, 0, 1, 3], [1], ["Close your book, please", "Pass me a pen, please", "Write one to ten", "Stand up, please"], [0]]}, {"p": [3, [3, 2, 1, 0], [3], ["Pass me a pen, please", "Write one to ten", "Stand up, please", "Sit down, please"], [0]]}, {"p": [4, [1, 3, 0, 2], [2], ["Write one to ten", "Stand up, please", "Sit down, please", "Take out your ruler, please"], [0]]}, {"p": [5, [2, 1, 0, 3], [2], ["Stand up, please", "Sit down, please", "Take out your ruler, please", "Put away your book, please"], [0]]}, {"p": [6, [2, 3, 0, 1], [3], ["Sit at your desk, please", "Sit down, please", "Take out your ruler, please", "Put away your book, please"], [1]]}, {"p": [7, [0, 3, 2, 1], [2], ["Sit at your desk, please", "Open your bag, please", "Take out your ruler, please", "Put away your book, please"], [2]]}, {"p": [8, [0, 2, 1, 3], [3], ["Sit at your desk, please", "Open your bag, please", "Close your book, please", "Put away your book, please"], [3]]}]$o$)  -- U1 Homework 3 b3 (quiz): p,
('edd344ab-6673-45d5-8031-b9379605550f', $o$[{"p": [0, [3, 2, 1, 0], [3], ["Sit at your desk, please", "Open your bag, please", "Close your book, please", "Pass me a pen, please"], [0]]}, {"p": [1, [1, 2, 3, 0], [3], ["Open your bag, please", "Close your book, please", "Pass me a pen, please", "Write one to ten"], [0]]}, {"p": [2, [3, 2, 1, 0], [3], ["Close your book, please", "Pass me a pen, please", "Write one to ten", "Stand up, please"], [0]]}, {"p": [3, [2, 0, 1, 3], [1], ["Pass me a pen, please", "Write one to ten", "Stand up, please", "Sit down, please"], [0]]}, {"p": [4, [2, 1, 3, 0], [3], ["Write one to ten", "Stand up, please", "Sit down, please", "Take out your ruler, please"], [0]]}, {"p": [5, [1, 3, 2, 0], [3], ["Stand up, please", "Sit down, please", "Take out your ruler, please", "Put away your book, please"], [0]]}, {"p": [6, [2, 3, 1, 0], [2], ["Sit at your desk, please", "Sit down, please", "Take out your ruler, please", "Put away your book, please"], [1]]}, {"p": [7, [3, 1, 2, 0], [2], ["Sit at your desk, please", "Open your bag, please", "Take out your ruler, please", "Put away your book, please"], [2]]}, {"p": [8, [0, 3, 1, 2], [1], ["Sit at your desk, please", "Open your bag, please", "Close your book, please", "Put away your book, please"], [3]]}]$o$)  -- U1 Homework 3 b4 (quiz): p,
('cc36be7a-55ac-497f-a9dc-87303b007667', $o$[{"s": [["questions", "0", "options"], [{"text": "L"}, {"text": "J"}, {"text": "V"}]]}, {"s": [["questions", "0", "correct"], [0]]}, {"s": [["questions", "0", "audio_tts"], "lion"]}, {"s": [["questions", "1", "options"], [{"text": "L"}, {"text": "J"}, {"text": "V"}]]}, {"s": [["questions", "1", "correct"], [2]]}, {"s": [["questions", "1", "audio_tts"], "van"]}, {"s": [["questions", "2", "options"], [{"text": "L"}, {"text": "J"}, {"text": "V"}]]}, {"s": [["questions", "2", "correct"], [1]]}, {"s": [["questions", "2", "audio_tts"], "jump"]}, {"p": [0, [1, 2, 0], [2], ["L", "J", "V"], [0]]}, {"p": [1, [0, 2, 1], [1], ["L", "J", "V"], [2]]}, {"p": [2, [2, 1, 0], [1], ["L", "J", "V"], [1]]}, {"s": [["needs_review"], false]}]$o$)  -- U1 Homework 3 b7 (quiz): p/s,
('ff83901c-ca47-4c2a-a6ba-01135d5ec5dc', $o$[{"p": [0, [4, 2, 1, 3, 0, 5], [4], ["doll", "bell", "jump", "jog", "van", "vet"], [0]]}, {"p": [1, [4, 2, 0, 5, 3, 1], [5], ["doll", "bell", "jump", "jog", "van", "vet"], [1]]}, {"p": [2, [5, 1, 4, 3, 0, 2], [5], ["doll", "bell", "jump", "jog", "van", "vet"], [2]]}, {"p": [3, [4, 2, 1, 0, 5, 3], [5], ["doll", "bell", "jump", "jog", "van", "vet"], [3]]}, {"p": [4, [3, 0, 1, 2, 4, 5], [4], ["doll", "bell", "jump", "jog", "van", "vet"], [4]]}, {"p": [5, [2, 0, 3, 4, 5, 1], [4], ["doll", "bell", "jump", "jog", "van", "vet"], [5]]}]$o$)  -- U1 Homework 3 b8 (quiz): p,
('ed70c80c-bbf4-4960-9592-22ffc31eadb5', $o$[{"p": [0, [1, 0, 3, 2], [3], ["red", "yellow", "purple", "black"], [2]]}]$o$)  -- U1 Homework 3 b11 (quiz): p,
('b1eee66f-e5d7-4a86-b652-0829e1c275f4', $o$[{"r": ["идет интерактивное видео с заданием, которое учитель также прикрепил к выполнению в твоем личном кабинете.", "идет интерактивное видео с заданием — оно в конце этого урока."]}]$o$)  -- U1 Homework 4 b1 (text): r,
('bcf52590-9c67-4560-9ce8-635de3447737', $o$[{"s": [["questions", "0", "options"], [{"text": "W"}, {"text": "X"}, {"text": "Y"}]]}, {"s": [["questions", "0", "correct"], [0]]}, {"s": [["questions", "0", "audio_tts"], "west"]}, {"s": [["questions", "1", "options"], [{"text": "W"}, {"text": "X"}, {"text": "Y"}]]}, {"s": [["questions", "1", "correct"], [1]]}, {"s": [["questions", "1", "audio_tts"], "box"]}, {"s": [["questions", "2", "options"], [{"text": "W"}, {"text": "X"}, {"text": "Y"}]]}, {"s": [["questions", "2", "correct"], [2]]}, {"s": [["questions", "2", "audio_tts"], "yes"]}, {"p": [0, [1, 2, 0], [2], ["W", "X", "Y"], [0]]}, {"p": [1, [2, 0, 1], [2], ["W", "X", "Y"], [1]]}, {"p": [2, [1, 0, 2], [2], ["W", "X", "Y"], [2]]}, {"s": [["needs_review"], false]}]$o$)  -- U1 Homework 4 b4 (quiz): p/s,
('9f8b95c0-f4fb-4e11-830f-8743c2c6ed3e', $o$[{"p": [0, [3, 0, 2, 1, 5, 4], [1], ["well", "west", "box", "taxi", "yell", "yes"], [0]]}, {"p": [1, [4, 0, 1, 2, 5, 3], [2], ["well", "west", "box", "taxi", "yell", "yes"], [1]]}, {"p": [2, [5, 3, 4, 1, 0, 2], [5], ["well", "west", "box", "taxi", "yell", "yes"], [2]]}, {"p": [3, [0, 2, 5, 3, 1, 4], [3], ["well", "west", "box", "taxi", "yell", "yes"], [3]]}, {"p": [4, [1, 5, 0, 2, 3, 4], [5], ["well", "west", "box", "taxi", "yell", "yes"], [4]]}, {"p": [5, [2, 3, 4, 0, 5, 1], [4], ["well", "west", "box", "taxi", "yell", "yes"], [5]]}]$o$)  -- U1 Homework 4 b5 (quiz): p,
('e4e737ab-691d-458a-88d6-dfeef1087f02', $o$[{"p": [0, [5, 7, 4, 2, 6, 0, 3, 1], [2, 3, 4, 6, 7], ["a pencil", "a ruler", "a bag", "a notebook", "a pencil case", "a rubber", "a book", "a pen"], [1, 2, 3, 4, 6]]}]$o$)  -- U1 Homework 4 b8 (quiz): p,
('1c01fe67-a7e2-4769-945d-f772904eee90', $o$[{"r": ["идет интерактивное видео, которое учитель также прикрепил к выполнению в твоем личном кабинете.", "идет интерактивное видео — оно ниже."]}]$o$)  -- U1 Homework 4 b11 (text): r,
('5243fb10-b129-4cfc-9c6b-2a05f174295a', $o$[{"s": [["questions", "0", "options"], [{"text": "Z"}, {"text": "Q"}]]}, {"s": [["questions", "0", "correct"], [0]]}, {"s": [["questions", "0", "audio_tts"], "zigzag"]}, {"s": [["questions", "1", "options"], [{"text": "Z"}, {"text": "Q"}]]}, {"s": [["questions", "1", "correct"], [1]]}, {"s": [["questions", "1", "audio_tts"], "queen"]}, {"p": [0, [1, 0], [1], ["Z", "Q"], [0]]}, {"p": [1, [1, 0], [0], ["Z", "Q"], [1]]}, {"s": [["needs_review"], false]}]$o$)  -- U1 Homework 5 b4 (quiz): p/s,
('eb5e4288-24eb-46b7-b86c-55aec9e34273', $o$[{"p": [0, [1, 0, 2, 3], [1], ["buzz", "zigzag", "queen", "quest"], [0]]}, {"p": [1, [1, 3, 2, 0], [0], ["buzz", "zigzag", "queen", "quest"], [1]]}, {"p": [2, [3, 2, 1, 0], [1], ["buzz", "zigzag", "queen", "quest"], [2]]}, {"p": [3, [0, 3, 1, 2], [1], ["buzz", "zigzag", "queen", "quest"], [3]]}]$o$)  -- U1 Homework 5 b5 (quiz): p,
('f31a5b19-9085-4b0c-b090-3405c0f3b125', $o$[{"p": [0, [1, 0], [1], ["Верно", "Неверно"], [0]]}, {"p": [1, [1, 0], [0], ["Верно", "Неверно"], [1]]}, {"p": [2, [1, 0], [0], ["Верно", "Неверно"], [1]]}, {"p": [3, [1, 0], [0], ["Верно", "Неверно"], [1]]}, {"p": [4, [1, 0], [1], ["Верно", "Неверно"], [0]]}, {"p": [5, [1, 0], [1], ["Верно", "Неверно"], [0]]}]$o$)  -- U1 Homework 5 b7 (quiz): p,
('7cdd8acf-36ee-4c3b-8de4-9bf94cca2a6b', $o$[{"s": [["audio_tts"], "Number one is a pencil. Number two is a ruler. Number three is a pencil case. Number four is a notebook. Number five is a rubber. Number six is a book. Number seven is a bag. Number eight is a pen."]}]$o$)  -- U1 Homework 5 b8 (text): s,
('f3983f5e-f14d-4315-b05c-4c86e61d848e', $o$[{"s": [["points", "0", "text"], "pencil"]}, {"s": [["points", "0", "audio_tts"], "pencil"]}, {"s": [["points", "1", "text"], "ruler"]}, {"s": [["points", "1", "audio_tts"], "ruler"]}, {"s": [["points", "2", "text"], "pencil case"]}, {"s": [["points", "2", "audio_tts"], "pencil case"]}, {"s": [["points", "3", "text"], "notebook"]}, {"s": [["points", "3", "audio_tts"], "notebook"]}, {"s": [["points", "4", "text"], "rubber"]}, {"s": [["points", "4", "audio_tts"], "rubber"]}, {"s": [["points", "5", "text"], "book"]}, {"s": [["points", "5", "audio_tts"], "book"]}, {"s": [["points", "6", "text"], "bag"]}, {"s": [["points", "6", "audio_tts"], "bag"]}, {"s": [["points", "7", "text"], "pen"]}, {"s": [["points", "7", "audio_tts"], "pen"]}, {"s": [["title"], "Соедини цифры с предметами: нажми на номер на картинке, потом на слово."]}, {"s": [["needs_review"], false]}]$o$)  -- U1 Homework 5 b9 (hotspot): s,
('77ce720d-25a4-4512-bd01-5765c0aa9529', $o$[{"p": [0, [3, 1, 0, 2, 4], [2], ["слушать", "смотреть", "трогать", "нюхать", "пробовать на вкус"], [0]]}, {"p": [1, [0, 1, 3, 2, 4], [1], ["слушать", "смотреть", "трогать", "нюхать", "пробовать на вкус"], [1]]}, {"p": [2, [4, 3, 0, 1, 2], [4], ["слушать", "смотреть", "трогать", "нюхать", "пробовать на вкус"], [2]]}, {"p": [3, [2, 0, 3, 4, 1], [2], ["слушать", "смотреть", "трогать", "нюхать", "пробовать на вкус"], [3]]}, {"p": [4, [0, 2, 1, 4, 3], [3], ["слушать", "смотреть", "трогать", "нюхать", "пробовать на вкус"], [4]]}]$o$)  -- U1 Homework 6 b2 (quiz): p,
('1a560824-6615-434a-80bd-d2f282ee35fa', $o$[{"p": [0, [3, 4, 1, 2, 0], [4], ["Listen", "Look", "Touch", "Smell", "Taste"], [0]]}, {"p": [1, [2, 4, 0, 3, 1], [4], ["Listen", "Look", "Touch", "Smell", "Taste"], [1]]}, {"p": [2, [0, 4, 2, 3, 1], [2], ["Listen", "Look", "Touch", "Smell", "Taste"], [2]]}, {"p": [3, [2, 0, 3, 1, 4], [2], ["Listen", "Look", "Touch", "Smell", "Taste"], [3]]}, {"p": [4, [1, 0, 4, 3, 2], [2], ["Listen", "Look", "Touch", "Smell", "Taste"], [4]]}]$o$)  -- U1 Homework 6 b3 (quiz): p,
('813dc792-abc6-4380-b7ca-c58500d0e05c', $o$[{"p": [0, [2, 1, 4, 3, 0], [4], ["Listen", "Look", "Touch", "Smell", "Taste"], [0]]}, {"p": [1, [0, 1, 3, 2, 4], [1], ["Listen", "Look", "Touch", "Smell", "Taste"], [1]]}, {"p": [2, [1, 2, 3, 0, 4], [1], ["Listen", "Look", "Touch", "Smell", "Taste"], [2]]}, {"p": [3, [0, 3, 4, 2, 1], [1], ["Listen", "Look", "Touch", "Smell", "Taste"], [3]]}, {"p": [4, [1, 2, 3, 4, 0], [3], ["Listen", "Look", "Touch", "Smell", "Taste"], [4]]}]$o$)  -- U1 Homework 6 b4 (quiz): p,
('0c35af7d-1586-47f6-a00d-302cf3819f0b', $o$[{"p": [0, [1, 0], [0], ["True ✅", "False ❌"], [1]]}, {"p": [1, [1, 0], [1], ["True ✅", "False ❌"], [0]]}, {"p": [2, [1, 0], [1], ["True ✅", "False ❌"], [0]]}, {"p": [3, [1, 0], [0], ["True ✅", "False ❌"], [1]]}, {"p": [4, [1, 0], [1], ["True ✅", "False ❌"], [0]]}]$o$)  -- U1 Homework 6 b14 (quiz): p,
('e201869e-1ff4-4324-a8d5-d7258112d7a7', $o$[{"p": [0, [2, 1, 0], [1], ["listen", "look", "smell"], [1]]}, {"p": [1, [2, 1, 0], [2], ["listen", "look", "taste"], [0]]}, {"p": [2, [2, 0, 1], [2], ["listen", "smell", "taste"], [1]]}, {"p": [3, [1, 0, 2], [2], ["listen", "look", "taste"], [2]]}, {"p": [4, [1, 0, 2], [2], ["smell", "taste", "touch"], [2]]}]$o$)  -- U1 Homework 6 b16 (quiz): p,
('0cd19ae1-b872-4270-80a0-33277714fb73', $o$[{"s": [["sample_tts"], "This is my sense story. I can see a book. I can hear a bird. I can smell a flower."]}]$o$)  -- U1 Homework 6 b17 (speaking): s,
('59d7c3b9-c5d6-4485-bc0b-7b09cbd8d924', $o$[{"p": [0, [2, 1, 0], [2], ["Yes, it is", "What's this?", "It's a rubber"], [0]]}, {"p": [1, [2, 1, 0], [0], ["Is it a ruler?", "No, it isn't", "It's a rubber"], [2]]}, {"p": [2, [2, 1, 0], [1], ["What's this?", "No, it isn't", "It's a bag"], [1]]}]$o$)  -- U1 Homework 7 b12 (quiz): p,
('20de2dcf-f504-4a72-999a-120df3ca5eda', $o$[{"s": [["sample_tts"], "I can see a bag, a book, a pencil and a desk."]}]$o$)  -- U1 Homework 7 b20 (speaking): s,
('8d350e1a-cadb-4210-9cc0-615f9b96673e', $o$[{"r": ["Тебя ждет дополнительное задание, которое учитель прикрепил в твоем личном кабинете.", "В конце урока тебя ждет дополнительное задание."]}]$o$)  -- U2 Homework 1 b1 (text): r,
('10886573-0fff-485c-86f0-16987629c0c4', $o$[{"p": [0, [2, 0, 3, 1], [1], ["doll", "ball", "kite", "car"], [0]]}, {"p": [1, [2, 1, 3, 0], [3], ["ball", "kite", "car", "bike"], [0]]}, {"p": [2, [2, 3, 1, 0], [3], ["kite", "car", "bike", "computer game"], [0]]}, {"p": [3, [2, 0, 1, 3], [1], ["car", "bike", "computer game", "go-kart"], [0]]}, {"p": [4, [3, 1, 0, 2], [2], ["bike", "computer game", "go-kart", "train"], [0]]}, {"p": [5, [1, 3, 0, 2], [2], ["computer game", "go-kart", "train", "monster"], [0]]}, {"p": [6, [0, 1, 3, 2], [0], ["go-kart", "train", "monster", "plane"], [0]]}, {"p": [7, [3, 2, 1, 0], [2], ["doll", "train", "monster", "plane"], [1]]}, {"p": [8, [3, 1, 0, 2], [3], ["doll", "ball", "monster", "plane"], [2]]}, {"p": [9, [1, 0, 3, 2], [2], ["doll", "ball", "kite", "plane"], [3]]}]$o$)  -- U2 Homework 1 b3 (quiz): p,
('6edcd55e-0ff0-460d-ace5-71c030eef1ba', $o$[{"p": [0, [1, 0], [0], ["OA", "OO"], [1]]}, {"p": [1, [1, 0], [1], ["OA", "OO"], [0]]}, {"s": [["needs_review"], false]}]$o$)  -- U2 Homework 1 b10 (quiz): p/s,
('aab9a6b6-43b7-48ec-aadf-6640d76f5a80', $o$[{"p": [0, [3, 2, 1, 0], [3], ["doll", "ball", "kite", "car"], [0]]}, {"p": [1, [3, 0, 2, 1], [1], ["ball", "kite", "car", "bike"], [0]]}, {"p": [2, [2, 0, 1, 3], [1], ["kite", "car", "bike", "computer game"], [0]]}, {"p": [3, [3, 2, 0, 1], [2], ["car", "bike", "computer game", "go-kart"], [0]]}, {"p": [4, [1, 0, 3, 2], [1], ["bike", "computer game", "go-kart", "train"], [0]]}, {"p": [5, [2, 0, 1, 3], [1], ["computer game", "go-kart", "train", "monster"], [0]]}, {"p": [6, [1, 2, 3, 0], [3], ["go-kart", "train", "monster", "plane"], [0]]}, {"p": [7, [3, 2, 0, 1], [3], ["doll", "train", "monster", "plane"], [1]]}, {"p": [8, [0, 2, 3, 1], [1], ["doll", "ball", "monster", "plane"], [2]]}, {"p": [9, [1, 2, 3, 0], [2], ["doll", "ball", "kite", "plane"], [3]]}]$o$)  -- U2 Homework 1 b11 (quiz): p,
('4ef8ca73-715c-449d-9c5b-f7fdabd5511e', $o$[{"p": [0, [1, 0], [0], ["AR", "OR"], [1]]}, {"p": [1, [1, 0], [1], ["AR", "OR"], [0]]}, {"s": [["needs_review"], false]}]$o$)  -- U2 Homework 2 b3 (quiz): p/s,
('6af05c4f-43d8-4375-934d-8332a415b93b', $o$[{"p": [0, [1, 0], [0], ["Her", "His"], [1]]}, {"p": [1, [1, 0], [1], ["Her", "His"], [0]]}, {"p": [2, [1, 0], [1], ["Her", "His"], [0]]}]$o$)  -- U2 Homework 2 b12 (quiz): p,
('7c99ae5c-dda6-47cb-9a20-473cc40f1eaa', $o$[{"p": [0, [1, 0], [1], ["Her", "His"], [0]]}, {"p": [1, [1, 0], [0], ["Her", "His"], [1]]}, {"p": [2, [1, 0], [1], ["Her", "His"], [0]]}]$o$)  -- U2 Homework 2 b13 (quiz): p,
('7ca508e9-d77d-4e70-b95d-2109ab72cdc5', $o$[{"s": [["sample_tts"], "This is my best friend. Her name is Kate. She's eight. She's happy and funny."]}]$o$)  -- U2 Homework 2 b14 (speaking): s,
('ba5470bb-6905-4aa1-973f-d49c313b0424', $o$[{"p": [0, [1, 2, 0], [2], ["Her name's Kim.", "Her favourite toy is her bike.", "She's six."], [0]]}, {"p": [1, [0, 2, 1], [0], ["Her favourite toy is her bike.", "She's six.", "His favourite toy is his plane."], [0]]}, {"p": [2, [0, 2, 1], [0], ["She's six.", "His favourite toy is his plane.", "His name's Tim."], [0]]}, {"p": [3, [2, 1, 0], [2], ["His favourite toy is his plane.", "His name's Tim.", "He's ten."], [0]]}, {"p": [4, [2, 0, 1], [2], ["Her name's Kim.", "His name's Tim.", "He's ten."], [1]]}, {"p": [5, [1, 0, 2], [2], ["Her name's Kim.", "Her favourite toy is her bike.", "He's ten."], [2]]}, {"s": [["needs_review"], false]}]$o$)  -- U2 Homework 2 b15 (quiz): p/s,
('a0188c0a-dbd8-462d-9ae0-8c37a8cfb27e', $o$[{"p": [0, [1, 0], [1], ["UR", "OW"], [0]]}, {"p": [1, [1, 0], [0], ["UR", "OW"], [1]]}, {"s": [["needs_review"], false]}]$o$)  -- U2 Homework 3 b3 (quiz): p/s,
('eb6dd7a7-c0ab-4e18-b607-42f5237f4ea3', $o$[{"s": [["needs_review"], false]}]$o$)  -- U2 Homework 3 b6 (match): s,
('c075be6e-0cc5-4640-9aa9-46add1afeeac', $o$[{"r": ["go-cart", "go-kart"]}]$o$)  -- U2 Homework 3 b8 (hotspot): r,
('0ae721fe-c368-4813-812c-3053dfa1b50f', $o$[{"p": [0, [1, 0], [1], ["a", "an"], [0]]}, {"p": [1, [1, 0], [0], ["a", "an"], [1]]}, {"p": [2, [1, 0], [1], ["a", "an"], [0]]}, {"p": [3, [1, 0], [1], ["a", "an"], [0]]}, {"p": [4, [1, 0], [0], ["a", "an"], [1]]}]$o$)  -- U2 Homework 3 b13 (quiz): p,
('0bfe716b-9b82-4a0e-9a36-eef559b0937e', $o$[{"s": [["sample_tts"], "This is my train. It's green, red and yellow. It's big and beautiful. It's new."]}]$o$)  -- U2 Homework 3 b14 (speaking): s,
('fe2db57e-0c47-4d34-9425-0bfefe5a7e6d', $o$[{"r": ["go-cart", "go-kart"]}, {"s": [["needs_review"], false]}]$o$)  -- U2 Homework 3 b15 (match): r/s,
('cac30fcc-6f54-47e2-86f7-87513ed5974f', $o$[{"s": [["needs_review"], false]}]$o$)  -- U2 Homework 3 b16 (truefalse): s,
('74ab84e7-e04a-4f89-af0a-7edd033e3fa4', $o$[{"r": ["тебя ждет интерактивное видео, которое учитель прикрепил в твоем личном кабинете.", "тебя ждет интерактивное видео — оно в конце урока."]}]$o$)  -- U2 Homework 4 b1 (text): r,
('df9ed9a1-f92f-4c20-9038-e4d086d28952', $o$[{"p": [0, [1, 0], [0], ["TH (глухой)", "TH (звонкий)"], [1]]}, {"p": [1, [1, 0], [1], ["TH (глухой)", "TH (звонкий)"], [0]]}, {"s": [["needs_review"], false]}]$o$)  -- U2 Homework 4 b4 (quiz): p/s,
('9987d17b-f0c3-457a-9d24-c2574b84ad22', $o$[{"s": [["audio_tts"], "Man: This is Ben from the Red team and this is Misty from the Green team! Red team driver: Ha ha ha! What an ugly old go-kart! Man: One, two, three, go! Thunder and Whisper: Go! Flash: Great, Misty! Red team girl: She's first! Stop her! Misty: Help! Thunder: Oh, no! Red team driver: Ha ha ha! Now I'm first! Misty: That isn't fair! Thunder: Just a minute. Thunder: Hold on, Misty!"]}]$o$)  -- U2 Homework 4 b5 (text): s,
('8479ea38-cc68-4db1-9e49-9b4abf93a759', $o$[{"r": ["Не забудь про дополнительное задание, которое ждет тебя в личном кабинете! За него ты получишь дополнительную звездочку!", "Не забудь про дополнительное задание — интерактивное видео выше! За него ты получишь дополнительную звездочку!"]}]$o$)  -- U2 Homework 4 b15 (text): r,
('7f7862f8-499a-47c2-ae40-229b121de045', $o$[{"p": [0, [1, 0], [1], ["AI", "NG"], [0]]}, {"p": [1, [1, 0], [0], ["AI", "NG"], [1]]}, {"s": [["needs_review"], false]}]$o$)  -- U2 Homework 5 b4 (quiz): p/s,
('ee3a2a57-fc4a-494d-ace1-19c36c4d2132', $o$[{"r": ["go-cart", "go-kart"]}]$o$)  -- U2 Homework 5 b9 (order): r,
('0729ae5c-5bf1-40ae-a37e-76c599e47c47', $o$[{"p": [0, [1, 0], [0], ["EE", "IGH"], [1]]}, {"p": [1, [1, 0], [1], ["EE", "IGH"], [0]]}, {"s": [["needs_review"], false]}]$o$)  -- U2 Homework 6 b3 (quiz): p/s,
('b0c5bd05-9776-4fb1-9f53-6882ca414d8a', $o$[{"p": [0, [1, 0], [1], ["circle", "triangle"], [0]]}, {"p": [1, [1, 0], [1], ["rectangle", "triangle"], [0]]}, {"p": [2, [1, 0], [0], ["circle", "kite"], [1]]}, {"p": [3, [1, 0], [0], ["square", "triangle"], [1]]}, {"p": [4, [2, 1, 0], [1], ["circle", "square", "triangle"], [1]]}]$o$)  -- U2 Homework 6 b6 (quiz): p,
('187dfc15-3972-46c6-b593-64c647e32588', $o$[{"p": [0, [2, 4, 5, 3, 0, 1], [5], ["a car", "a kite", "a doll", "a bike", "a monster", "a plane"], [1]]}, {"p": [1, [5, 1, 2, 0, 4, 3], [5], ["a car", "a kite", "a doll", "a bike", "a monster", "a plane"], [3]]}, {"p": [2, [4, 0, 2, 5, 1, 3], [3], ["a car", "a kite", "a doll", "a bike", "a monster", "a plane"], [5]]}]$o$)  -- U2 Homework 7 b2 (quiz): p,
('55e97931-6b23-430d-8b31-8f9b34b926f9', $o$[{"p": [0, [1, 0], [0], ["Верно", "Неверно"], [1]]}, {"p": [1, [1, 0], [1], ["Верно", "Неверно"], [0]]}, {"p": [2, [1, 0], [0], ["Верно", "Неверно"], [1]]}, {"p": [3, [1, 0], [0], ["Верно", "Неверно"], [1]]}, {"p": [4, [1, 0], [0], ["Верно", "Неверно"], [1]]}, {"p": [5, [1, 0], [1], ["Верно", "Неверно"], [0]]}]$o$)  -- U2 Homework 7 b3 (quiz): p,
('3bb14972-42ee-423b-a398-713a9a52af89', $o$[{"s": [["needs_review"], false]}]$o$)  -- U2 Homework 7 b8 (match): s,
('2f92d738-f8a7-446a-975c-8c225c0ae6de', $o$[{"s": [["sample_tts"], "This is my friend Tom. We are in the toy shop. Look! A big red car and a small blue ball. I like the car!"]}]$o$)  -- U2 Homework 7 b9 (speaking): s,
('ce41e2a9-0922-46a8-8ac0-6e3743a86635', $o$[{"r": ["Чтобы найти дополнительное упражнение, вернись в личный кабинет и выбери урок SM1 Unit 3 Homework 1 (extra)!", "Дополнительные задания ждут тебя в конце этого урока!"]}]$o$)  -- U3 Homework 1 b1 (text): r,
('ac69ab17-47a0-4774-8d9a-eb3be63e37bf', $o$[{"p": [0, [2, 3, 1, 0], [3], ["elephant", "rat", "lizard", "frog"], [0]]}, {"p": [1, [2, 3, 1, 0], [3], ["rat", "lizard", "frog", "spider"], [0]]}, {"p": [2, [1, 2, 3, 0], [3], ["lizard", "frog", "spider", "dog"], [0]]}, {"p": [3, [2, 0, 1, 3], [1], ["frog", "spider", "dog", "cat"], [0]]}, {"p": [4, [3, 1, 2, 0], [3], ["spider", "dog", "cat", "duck"], [0]]}, {"p": [5, [2, 1, 3, 0], [3], ["dog", "cat", "duck", "donkey"], [0]]}, {"p": [6, [3, 2, 0, 1], [3], ["elephant", "cat", "duck", "donkey"], [1]]}, {"p": [7, [2, 3, 1, 0], [0], ["elephant", "rat", "duck", "donkey"], [2]]}, {"p": [8, [1, 3, 2, 0], [1], ["elephant", "rat", "lizard", "donkey"], [3]]}]$o$)  -- U3 Homework 1 b3 (quiz): p,
('3a9f75eb-dd98-44c3-a522-9325931fe839', $o$[{"s": [["needs_review"], false]}]$o$)  -- U3 Homework 1 b18 (match): s,
('eeb1276d-89ff-4a05-912f-b334ac45f825', $o$[{"p": [0, [3, 2, 1, 0], [3], ["elephant", "rat", "lizard", "frog"], [0]]}, {"p": [1, [1, 3, 2, 0], [3], ["rat", "lizard", "frog", "spider"], [0]]}, {"p": [2, [3, 0, 2, 1], [1], ["lizard", "frog", "spider", "dog"], [0]]}, {"p": [3, [0, 1, 3, 2], [0], ["frog", "spider", "dog", "cat"], [0]]}, {"p": [4, [2, 1, 0, 3], [2], ["spider", "dog", "cat", "duck"], [0]]}, {"p": [5, [3, 2, 1, 0], [3], ["dog", "cat", "duck", "donkey"], [0]]}, {"p": [6, [3, 2, 0, 1], [3], ["elephant", "cat", "duck", "donkey"], [1]]}, {"p": [7, [1, 0, 2, 3], [2], ["elephant", "rat", "duck", "donkey"], [2]]}, {"p": [8, [2, 3, 0, 1], [1], ["elephant", "rat", "lizard", "donkey"], [3]]}, {"s": [["needs_review"], false]}]$o$)  -- U3 Homework 1 b20 (quiz): p/s,
('539a3bd2-94a7-49e7-a03a-11957d015acc', $o$[{"s": [["needs_review"], false]}]$o$)  -- U3 Homework 1 b21 (exact_input): s,
('7c963150-c910-4bca-9140-f6b4f6912678', $o$[{"s": [["sample_tts"], "The cat is on the bed. The mouse is on the table. The dog is under the table. The spider is on the chair. The duck is under the chair. The frog is in the box."]}]$o$)  -- U3 Homework 2 b10 (speaking): s,
('deec4756-add8-459c-b965-70fdb7324c4c', $o$[{"p": [0, [0, 2, 3, 1], [0], [null, null, null, null], [0]]}, {"p": [1, [3, 2, 1, 0], [3], [null, null, null, null], [0]]}, {"p": [2, [3, 0, 1, 2], [1], [null, null, null, null], [0]]}, {"p": [3, [2, 1, 3, 0], [1], [null, null, null, null], [1]]}, {"p": [4, [3, 1, 0, 2], [3], [null, null, null, null], [2]]}, {"p": [5, [0, 1, 3, 2], [2], [null, null, null, null], [3]]}, {"s": [["needs_review"], false]}]$o$)  -- U3 Homework 2 b11 (quiz): p/s,
('84551c3f-cb06-4725-a433-28071d2729c0', $o$[{"p": [0, [2, 3, 1, 0], [0, 3], ["dogs", "cats", "frogs", "lizards"], [0, 2]]}]$o$)  -- U3 Homework 3 b5 (quiz): p,
('7093fd8f-4750-45f0-82b5-f3de2890d153', $o$[{"p": [0, [2, 0, 1, 3], [2], ["blue and red", "blue and yellow", "black and white", "orange and yellow"], [1]]}]$o$)  -- U3 Homework 3 b7 (quiz): p,
('ce38bdb7-f2c3-409f-8c14-9872d3b14be5', $o$[{"r": ["идет интерактивное видео с заданием, которое учитель также прикрепил к выполнению в твоем личном кабинете.", "идет интерактивное видео с заданием — оно в конце этого урока."]}]$o$)  -- U3 Homework 4 b1 (text): r,
('742b5644-7f96-4432-9c89-0db3f8673a32', $o$[{"g": 1}, {"s": [["needs_review"], false]}]$o$)  -- U3 Homework 4 b4 (sort): g/s,
('765ebe19-0bd6-421d-a0ad-ac6eed1a2d47', $o$[{"p": [0, [2, 0, 1], [2], ["in the bag", "under the table", "on the table"], [1]]}]$o$)  -- U3 Homework 4 b7 (quiz): p,
('86359964-eac5-4fd2-b279-e2a4bb4bfb3c', $o$[{"p": [0, [1, 0], [1], ["OI", "EAR"], [0]]}, {"p": [1, [1, 0], [0], ["OI", "EAR"], [1]]}, {"p": [2, [1, 0], [1], ["OI", "EAR"], [0]]}, {"p": [3, [1, 0], [0], ["OI", "EAR"], [1]]}]$o$)  -- U3 Homework 5 b4 (quiz): p,
('e811a444-e108-46ac-a373-765fed7a41f7', $o$[{"s": [["needs_review"], false]}]$o$)  -- U3 Homework 5 b7 (hotspot): s,
('8c52bc7f-ce30-4db8-af4f-3c14af567bd5', $o$[{"g": 1}, {"s": [["needs_review"], false]}]$o$)  -- U3 Homework 6 b4 (sort): g/s,
('8fdafe50-b0f4-493a-b11e-8f617405e2af', $o$[{"p": [0, [3, 0, 1, 4, 2], [0, 1, 2], ["rabbit", "horse", "lizard", "elephant", "snake"], [0, 1, 3]]}]$o$)  -- U3 Homework 6 b7 (quiz): p,
('48b1d147-4ae7-49a7-955b-1b45aa4dffb1', $o$[{"g": 1}, {"s": [["title"], "Ты отлично справляешься! А теперь давай попробуем распределить картинки по категориям: water, food and shelter! Смотри внимательно!"]}, {"s": [["needs_review"], false]}]$o$)  -- U3 Homework 6 b8 (sort): g/s,
('5330081e-c309-49bc-8d2e-c554a257e50c', $o$[{"p": [0, [1, 2, 0], [0], ["air.", "food.", "shelter."], [1]]}, {"p": [1, [0, 2, 1], [2], ["water.", "shelter.", "air."], [1]]}, {"p": [2, [2, 1, 0], [2], ["water.", "food.", "shelter."], [0]]}]$o$)  -- U3 Homework 6 b10 (quiz): p,
('3709492c-d0fd-4298-ba13-4eb688f7ad30', $o$[{"p": [0, [1, 0], [0], ["snak", "snake"], [1]]}, {"p": [1, [1, 0], [0], ["vale", "whale"], [1]]}, {"p": [2, [1, 0], [0], ["coen", "coin"], [1]]}, {"p": [3, [1, 0], [1], ["sister", "sistar"], [0]]}, {"p": [4, [1, 0], [0], ["chiar", "chair"], [1]]}]$o$)  -- U3 Homework 7 b2 (quiz): p,
('b5594baa-34db-4c96-953b-62b0f5611f06', $o$[{"p": [0, [4, 6, 2, 1, 3, 5, 0, 7], [1, 3, 4, 5], ["I like frogs.", "I like cats.", "I like donkeys.", "I don't like frogs.", "I don't like cats.", "I don't like donkeys.", "I like spiders.", "I don't like spiders."], [1, 3, 5, 6]]}]$o$)  -- U3 Homework 7 b5 (quiz): p,
('865d927a-89d6-412e-8cbc-2a1d47a682dc', $o$[{"p": [0, [3, 2, 0, 1], [2], ["банан", "торт", "бутерброд", "яблоко"], [0]]}, {"p": [1, [3, 0, 2, 1], [1], ["торт", "бутерброд", "яблоко", "пицца"], [0]]}, {"p": [2, [2, 3, 0, 1], [2], ["бутерброд", "яблоко", "пицца", "сосиска"], [0]]}, {"p": [3, [1, 0, 2, 3], [1], ["яблоко", "пицца", "сосиска", "курица"], [0]]}, {"p": [4, [3, 1, 0, 2], [2], ["пицца", "сосиска", "курица", "стейк"], [0]]}, {"p": [5, [2, 0, 3, 1], [1], ["сосиска", "курица", "стейк", "горох"], [0]]}, {"p": [6, [3, 1, 2, 0], [3], ["курица", "стейк", "горох", "морковь"], [0]]}, {"p": [7, [1, 2, 0, 3], [2], ["стейк", "горох", "морковь", "рыба"], [0]]}, {"p": [8, [3, 1, 0, 2], [1], ["банан", "горох", "морковь", "рыба"], [1]]}, {"p": [9, [3, 2, 1, 0], [1], ["банан", "торт", "морковь", "рыба"], [2]]}, {"p": [10, [2, 0, 1, 3], [3], ["банан", "торт", "бутерброд", "рыба"], [3]]}]$o$)  -- U4 Homework 1 b3 (quiz): p,
('37021cc2-0b85-4dab-ae50-b804ab559bba', $o$[{"p": [0, [1, 2, 0, 3], [2], ["banana", "cake", "sandwich", "apple"], [0]]}, {"p": [1, [3, 2, 0, 1], [2], ["cake", "sandwich", "apple", "pizza"], [0]]}, {"p": [2, [3, 0, 2, 1], [1], ["sandwich", "apple", "pizza", "sausage"], [0]]}, {"p": [3, [2, 1, 0, 3], [2], ["apple", "pizza", "sausage", "chicken"], [0]]}, {"p": [4, [3, 0, 2, 1], [1], ["pizza", "sausage", "chicken", "steak"], [0]]}, {"p": [5, [2, 0, 3, 1], [1], ["sausage", "chicken", "steak", "peas"], [0]]}, {"p": [6, [3, 2, 1, 0], [3], ["chicken", "steak", "peas", "carrots"], [0]]}, {"p": [7, [2, 3, 0, 1], [2], ["steak", "peas", "carrots", "fish"], [0]]}, {"p": [8, [3, 2, 1, 0], [2], ["banana", "peas", "carrots", "fish"], [1]]}, {"p": [9, [3, 2, 1, 0], [1], ["banana", "cake", "carrots", "fish"], [2]]}, {"p": [10, [0, 2, 1, 3], [3], ["banana", "cake", "sandwich", "fish"], [3]]}]$o$)  -- U4 Homework 1 b4 (quiz): p,
('83d7f396-d411-4abf-b0f8-c00541bc3766', $o$[{"p": [0, [3, 0, 1, 2], [1], [null, null, null, null], [0]]}, {"p": [1, [1, 0, 3, 2], [1], [null, null, null, null], [0]]}, {"p": [2, [0, 2, 3, 1], [0], [null, null, null, null], [0]]}, {"p": [3, [1, 3, 0, 2], [2], [null, null, null, null], [0]]}, {"p": [4, [3, 1, 2, 0], [3], [null, null, null, null], [0]]}, {"p": [5, [2, 3, 1, 0], [3], [null, null, null, null], [0]]}, {"p": [6, [1, 2, 0, 3], [2], [null, null, null, null], [0]]}, {"p": [7, [2, 0, 1, 3], [1], [null, null, null, null], [0]]}, {"p": [8, [2, 1, 3, 0], [1], [null, null, null, null], [1]]}, {"p": [9, [1, 0, 2, 3], [2], [null, null, null, null], [2]]}, {"p": [10, [0, 2, 3, 1], [2], [null, null, null, null], [3]]}, {"s": [["needs_review"], false]}]$o$)  -- U4 Homework 1 b9 (quiz): p/s,
('76232d8f-fff5-4801-995b-de8245f48700', $o$[{"s": [["needs_review"], false]}]$o$)  -- U4 Homework 1 b10 (exact_input): s,
('cbe0c2f8-9a49-4aa1-a1f3-8279f46bdd7e', $o$[{"p": [0, [1, 0], [0], ["S", "LE"], [1]]}, {"p": [1, [1, 0], [1], ["S", "LE"], [0]]}, {"p": [2, [1, 0], [1], ["S", "LE"], [0]]}, {"p": [3, [1, 0], [0], ["S", "LE"], [1]]}]$o$)  -- U4 Homework 2 b4 (quiz): p,
('0f85cbb1-061f-4d3f-8688-4c74f2059acd', $o$[{"s": [["sample_tts"], "I'm Bear. This is my fridge. I've got eggs, bread and chicken. I've got sausages and cheese. I like eggs!"]}]$o$)  -- U4 Homework 2 b11 (speaking): s,
('9d123601-dd0a-42cd-84aa-ddbe21768708', $o$[{"p": [0, [3, 1, 2, 0], [3], [null, null, null, null], [0]]}, {"p": [1, [2, 3, 1, 0], [3], [null, null, null, null], [0]]}, {"p": [2, [2, 1, 0, 3], [2], [null, null, null, null], [0]]}, {"p": [3, [2, 0, 1, 3], [1], [null, null, null, null], [0]]}, {"p": [4, [3, 0, 2, 1], [1], [null, null, null, null], [0]]}, {"p": [5, [0, 2, 1, 3], [0], [null, null, null, null], [0]]}, {"p": [6, [2, 0, 3, 1], [1], [null, null, null, null], [0]]}, {"p": [7, [3, 0, 2, 1], [1], [null, null, null, null], [0]]}, {"p": [8, [0, 3, 2, 1], [3], [null, null, null, null], [1]]}, {"p": [9, [1, 3, 2, 0], [2], [null, null, null, null], [2]]}, {"p": [10, [0, 3, 2, 1], [1], [null, null, null, null], [3]]}, {"s": [["needs_review"], false]}]$o$)  -- U4 Homework 2 b12 (quiz): p/s,
('91a23092-0727-438f-ad80-1f4f6183875d', $o$[{"g": 1}, {"s": [["needs_review"], false]}]$o$)  -- U4 Homework 3 b4 (sort): g/s,
('33019a89-806e-4fa8-b142-362ad4924a96', $o$[{"s": [["sample_tts"], "Hello, Farmer! How are you? ... Have we got any apples? ... Have we got any bananas? ... Have we got any orange juice? ... Have we got any sausages? ... Have we got any cheese? ... Have we got any chicken?"]}]$o$)  -- U4 Homework 3 b6 (speaking): s,
('a13ae889-e24f-434e-8964-efa1ae3290ab', $o$[{"s": [["sample_tts"], "I am fine, thank you. ... Yes, we have. ... No, we haven't. ... Yes, we have. ... Yes, we have. ... No, we haven't. ... No, we haven't."]}]$o$)  -- U4 Homework 3 b7 (speaking): s,
('290c4e9e-8890-4bc6-8652-9db3e7f7fc07', $o$[{"p": [0, [1, 0], [1], ["Yes, we have.", "No, we haven't."], [0]]}, {"p": [1, [1, 0], [0], ["Yes, we have.", "No, we haven't."], [1]]}, {"p": [2, [1, 0], [1], ["Yes, we have.", "No, we haven't."], [0]]}, {"p": [3, [1, 0], [1], ["Yes, we have.", "No, we haven't."], [0]]}, {"p": [4, [1, 0], [0], ["Yes, we have.", "No, we haven't."], [1]]}, {"p": [5, [1, 0], [0], ["Yes, we have.", "No, we haven't."], [1]]}]$o$)  -- U4 Homework 3 b8 (quiz): p,
('ed891c4b-694d-4340-a122-f63eaaf66b3f', $o$[{"p": [0, [2, 1, 0], [1], ["cake", "sausage", "apple"], [1]]}]$o$)  -- U4 Homework 4 b5 (quiz): p,
('7d466c9f-4068-40cb-b298-435e63a58611', $o$[{"s": [["audio_tts"], "Thunder: Where's Misty? Misty: Mmm... pizza. My favourite! Whisper: Look at Misty! Flash: Hey! That isn't fair. Misty: Pizza, please. Woman: Sorry. We haven't got pizza. Misty: OK. Sausages and peas, please. Woman: Here you are. Misty: Thank you. Thunder: Look! Woman: A new pizza. Nice and hot. Flash: Fantastic! Misty: What have you got? Whisper, Thunder and Flash: We've got pizza. Nice and hot!"]}]$o$)  -- U4 Homework 4 b6 (text): s,
('2c20bd83-3b0d-4c37-b815-9f3662a88dc3', $o$[{"p": [0, [4, 1, 3, 2, 0], [0, 1, 4], ["peas", "sausage", "steak", "chicken", "pizza"], [0, 1, 4]]}]$o$)  -- U4 Homework 4 b7 (quiz): p,
('6df6d031-eb4f-4b6e-a527-a5ec7e7c3b22', $o$[{"p": [0, [3, 1, 0, 2], [2], ["11", "12", "13", "14"], [0]]}, {"p": [1, [3, 0, 2, 1], [1], ["12", "13", "14", "15"], [0]]}, {"p": [2, [1, 2, 0, 3], [2], ["13", "14", "15", "16"], [0]]}, {"p": [3, [2, 3, 1, 0], [3], ["14", "15", "16", "17"], [0]]}, {"p": [4, [1, 3, 0, 2], [2], ["15", "16", "17", "18"], [0]]}, {"p": [5, [3, 0, 2, 1], [1], ["16", "17", "18", "19"], [0]]}, {"p": [6, [1, 3, 0, 2], [2], ["17", "18", "19", "20"], [0]]}, {"p": [7, [0, 1, 3, 2], [1], ["11", "18", "19", "20"], [1]]}, {"p": [8, [3, 1, 2, 0], [2], ["11", "12", "19", "20"], [2]]}, {"p": [9, [2, 0, 1, 3], [3], ["11", "12", "13", "20"], [3]]}]$o$)  -- U4 Homework 5 b3 (quiz): p,
('8e2dbe5a-f9ff-47b0-9548-1892ebf97374', $o$[{"p": [0, [2, 0, 3, 1], [1], ["eleven", "twelve", "thirteen", "fourteen"], [0]]}, {"p": [1, [3, 0, 1, 2], [1], ["twelve", "thirteen", "fourteen", "fifteen"], [0]]}, {"p": [2, [2, 1, 0, 3], [2], ["thirteen", "fourteen", "fifteen", "sixteen"], [0]]}, {"p": [3, [3, 1, 2, 0], [3], ["fourteen", "fifteen", "sixteen", "seventeen"], [0]]}, {"p": [4, [3, 0, 2, 1], [1], ["fifteen", "sixteen", "seventeen", "eighteen"], [0]]}, {"p": [5, [3, 1, 2, 0], [3], ["sixteen", "seventeen", "eighteen", "nineteen"], [0]]}, {"p": [6, [3, 1, 0, 2], [2], ["seventeen", "eighteen", "nineteen", "twenty"], [0]]}, {"p": [7, [2, 0, 3, 1], [3], ["eleven", "eighteen", "nineteen", "twenty"], [1]]}, {"p": [8, [3, 1, 2, 0], [2], ["eleven", "twelve", "nineteen", "twenty"], [2]]}, {"p": [9, [0, 1, 3, 2], [2], ["eleven", "twelve", "thirteen", "twenty"], [3]]}]$o$)  -- U4 Homework 5 b4 (quiz): p,
('8cdc3b34-654f-4a07-b7d7-d5bf0dda281f', $o$[{"p": [0, [0, 2, 1], [1], ["eleven", "thirteen", "twenty"], [2]]}, {"p": [1, [2, 0, 1], [1], ["fourteen", "sixteen", "eighteen"], [0]]}, {"p": [2, [1, 0, 2], [1], ["eleven", "nineteen", "twelve"], [0]]}]$o$)  -- U4 Homework 5 b14 (quiz): p,
('fda2c542-7772-438b-ba88-3a3afc901129', $o$[{"s": [["needs_review"], false]}]$o$)  -- U4 Homework 5 b17 (exact_input): s,
('d65feea7-0b66-4209-a578-19cf4485f2a4', $o$[{"g": 1}]$o$)  -- U4 Homework 6 b4 (sort): g,
('50c71d51-d23c-4d46-ba75-00cd300d59b0', $o$[{"g": 1}]$o$)  -- U4 Homework 6 b6 (sort): g,
('d5d1a7de-a821-47dc-a23f-7ad40ccbd224', $o$[{"s": [["needs_review"], false]}]$o$)  -- U4 Homework 6 b7 (sequence): s,
('226abd44-a4cb-44c1-bad8-72145b22bfa6', $o$[{"p": [0, [3, 0, 2, 1], [1], ["in the soil", "big", "in a shop", "dinner"], [0]]}, {"p": [1, [2, 3, 1, 0], [2], ["in the soil", "big", "in a shop", "dinner"], [1]]}, {"p": [2, [3, 2, 1, 0], [1], ["in the soil", "big", "in a shop", "dinner"], [2]]}, {"p": [3, [2, 0, 3, 1], [2], ["in the soil", "big", "in a shop", "dinner"], [3]]}]$o$)  -- U4 Homework 6 b8 (quiz): p,
('a07e782a-9200-462f-bd5d-247d67d31bab', $o$[{"r": ["Не забудь про дополнительное домашнее задание. Оно необязательное, но если ты его сделаешь, будет очень здорово! Перед его выполнением можно немножко отдохнуть, а потом уже приступить :)", "Увидимся на уроке!"]}]$o$)  -- U4 Homework 6 b10 (text): r,
('aafbde85-95e4-427d-8e23-50ca5bbca12c', $o$[{"p": [0, [0, 2, 1], [1], ["fish", "pizza", "steak"], [2]]}, {"p": [1, [1, 0, 2], [2], ["banana", "carrot", "peas"], [2]]}, {"p": [2, [2, 1, 0], [2], ["cheese sandwich", "carrots", "banana"], [0]]}, {"p": [3, [1, 0, 2], [2], ["apple", "steak", "sausage"], [2]]}]$o$)  -- U4 Homework 7 b2 (quiz): p,
('8c0708ef-f936-4d4c-9cc0-a9562d34a81b', $o$[{"s": [["questions", "0", "audio_tts"], "saw"]}, {"s": [["questions", "1", "audio_tts"], "home"]}, {"s": [["questions", "2", "audio_tts"], "jam"]}, {"p": [0, [1, 2, 0], [2], ["straw", "cloud", "bone"], [0]]}, {"p": [1, [1, 0, 2], [2], ["straw", "cloud", "bone"], [2]]}, {"p": [2, [1, 2, 0], [0], ["glow", "giraffe", "new"], [1]]}, {"s": [["needs_review"], false]}]$o$)  -- U4 Homework 7 b3 (quiz): p/s,
('32b36fa2-a692-45fc-93a5-30c1e016bb2e', $o$[{"p": [0, [1, 2, 0], [2], ["Yes, we have.", "Yes, I got.", "No, I haven't."], [0]]}, {"p": [1, [2, 0, 1], [2], ["No, we have.", "No, we haven't.", "Yes, we got."], [1]]}, {"p": [2, [1, 0, 2], [2], ["No, we hasn't.", "Yes, we have.", "No, we haven't."], [2]]}]$o$)  -- U4 Homework 7 b5 (quiz): p,
('9e3952e0-59df-4f32-8e40-71af6e1c1106', $o$[{"p": [0, [2, 1, 3, 0], [3], ["понедельник", "вторник", "среда", "четверг"], [0]]}, {"p": [1, [1, 3, 2, 0], [3], ["вторник", "среда", "четверг", "пятница"], [0]]}, {"p": [2, [3, 0, 2, 1], [1], ["среда", "четверг", "пятница", "суббота"], [0]]}, {"p": [3, [3, 2, 0, 1], [2], ["четверг", "пятница", "суббота", "воскресенье"], [0]]}, {"p": [4, [3, 1, 2, 0], [1], ["понедельник", "пятница", "суббота", "воскресенье"], [1]]}, {"p": [5, [2, 3, 1, 0], [0], ["понедельник", "вторник", "суббота", "воскресенье"], [2]]}, {"p": [6, [1, 3, 2, 0], [1], ["понедельник", "вторник", "среда", "воскресенье"], [3]]}]$o$)  -- U5 Homework 1 b3 (quiz): p,
('329d6515-4489-4a2c-9348-97e806f345b5', $o$[{"p": [0, [1, 0, 2, 3], [1], ["Monday", "Tuesday", "Wednesday", "Thursday"], [0]]}, {"p": [1, [2, 1, 0, 3], [2], ["Tuesday", "Wednesday", "Thursday", "Friday"], [0]]}, {"p": [2, [3, 0, 2, 1], [1], ["Wednesday", "Thursday", "Friday", "Saturday"], [0]]}, {"p": [3, [2, 3, 1, 0], [3], ["Thursday", "Friday", "Saturday", "Sunday"], [0]]}, {"p": [4, [0, 2, 3, 1], [3], ["Monday", "Friday", "Saturday", "Sunday"], [1]]}, {"p": [5, [3, 1, 2, 0], [2], ["Monday", "Tuesday", "Saturday", "Sunday"], [2]]}, {"p": [6, [0, 1, 3, 2], [2], ["Monday", "Tuesday", "Wednesday", "Sunday"], [3]]}]$o$)  -- U5 Homework 1 b4 (quiz): p,
('93a57365-e65d-47e2-8c10-3ad870db0674', $o$[{"p": [0, [2, 3, 0, 1], [2], ["Monday", "Tuesday", "Wednesday", "Thursday"], [0]]}, {"p": [1, [2, 1, 3, 0], [3], ["Tuesday", "Wednesday", "Thursday", "Friday"], [0]]}, {"p": [2, [1, 0, 2, 3], [1], ["Wednesday", "Thursday", "Friday", "Saturday"], [0]]}, {"p": [3, [3, 1, 2, 0], [3], ["Thursday", "Friday", "Saturday", "Sunday"], [0]]}, {"p": [4, [0, 2, 3, 1], [3], ["Monday", "Friday", "Saturday", "Sunday"], [1]]}, {"p": [5, [3, 0, 2, 1], [2], ["Monday", "Tuesday", "Saturday", "Sunday"], [2]]}, {"p": [6, [0, 1, 3, 2], [2], ["Monday", "Tuesday", "Wednesday", "Sunday"], [3]]}]$o$)  -- U5 Homework 1 b5 (quiz): p,
('a4200df6-7edf-44c3-87b2-20ac5fca5621', $o$[{"p": [0, [2, 1, 0, 3], [2], ["плавать", "кататься на пони", "кататься на велосипеде", "играть в футбол"], [0]]}, {"p": [1, [1, 0, 2, 3], [1], ["кататься на пони", "кататься на велосипеде", "играть в футбол", "играть на пианино"], [0]]}, {"p": [2, [2, 0, 3, 1], [1], ["кататься на велосипеде", "играть в футбол", "играть на пианино", "играть в прятки"], [0]]}, {"p": [3, [3, 1, 2, 0], [3], ["играть в футбол", "играть на пианино", "играть в прятки", "смотреть телевизор"], [0]]}, {"p": [4, [3, 2, 1, 0], [3], ["играть на пианино", "играть в прятки", "смотреть телевизор", "играть в компьютерные игры"], [0]]}, {"p": [5, [1, 0, 2, 3], [1], ["играть в прятки", "смотреть телевизор", "играть в компьютерные игры", "играть с игрушками"], [0]]}, {"p": [6, [0, 3, 2, 1], [0], ["смотреть телевизор", "играть в компьютерные игры", "играть с игрушками", "играть в мяч"], [0]]}, {"p": [7, [3, 1, 2, 0], [3], ["играть в компьютерные игры", "играть с игрушками", "играть в мяч", "петь"], [0]]}, {"p": [8, [2, 3, 1, 0], [3], ["играть с игрушками", "играть в мяч", "петь", "играть в настольные игры"], [0]]}, {"p": [9, [2, 0, 1, 3], [2], ["плавать", "играть в мяч", "петь", "играть в настольные игры"], [1]]}, {"p": [10, [1, 2, 3, 0], [1], ["плавать", "кататься на пони", "петь", "играть в настольные игры"], [2]]}, {"p": [11, [1, 2, 0, 3], [3], ["плавать", "кататься на пони", "кататься на велосипеде", "играть в настольные игры"], [3]]}]$o$)  -- U5 Homework 2 b2 (quiz): p,
('7455e4c1-2978-4b0c-a0b3-353764a47cbc', $o$[{"p": [0, [2, 1, 0, 3], [2], ["go swimming", "ride a pony", "ride a bike", "play football"], [0]]}, {"p": [1, [2, 3, 0, 1], [2], ["ride a pony", "ride a bike", "play football", "play the piano"], [0]]}, {"p": [2, [3, 2, 1, 0], [3], ["ride a bike", "play football", "play the piano", "play hide-and-seek"], [0]]}, {"p": [3, [3, 1, 2, 0], [3], ["play football", "play the piano", "play hide-and-seek", "watch TV"], [0]]}, {"p": [4, [1, 2, 3, 0], [3], ["play the piano", "play hide-and-seek", "watch TV", "play computer games"], [0]]}, {"p": [5, [3, 2, 1, 0], [3], ["play hide-and-seek", "watch TV", "play computer games", "play with toys"], [0]]}, {"p": [6, [3, 0, 2, 1], [1], ["watch TV", "play computer games", "play with toys", "play ball"], [0]]}, {"p": [7, [3, 0, 2, 1], [1], ["play computer games", "play with toys", "play ball", "sing"], [0]]}, {"p": [8, [2, 0, 1, 3], [1], ["play with toys", "play ball", "sing", "play board games"], [0]]}, {"p": [9, [3, 1, 2, 0], [1], ["go swimming", "play ball", "sing", "play board games"], [1]]}, {"p": [10, [0, 3, 2, 1], [2], ["go swimming", "ride a pony", "sing", "play board games"], [2]]}, {"p": [11, [3, 2, 0, 1], [0], ["go swimming", "ride a pony", "ride a bike", "play board games"], [3]]}]$o$)  -- U5 Homework 2 b3 (quiz): p,
('cd3201ec-6731-472e-a5e5-190b6b1d03be', $o$[{"p": [0, [3, 2, 0, 1], [2], ["go swimming", "ride a pony", "ride a bike", "play football"], [0]]}, {"p": [1, [1, 3, 0, 2], [2], ["ride a pony", "ride a bike", "play football", "play the piano"], [0]]}, {"p": [2, [2, 0, 1, 3], [1], ["ride a bike", "play football", "play the piano", "play hide-and-seek"], [0]]}, {"p": [3, [3, 1, 0, 2], [2], ["play football", "play the piano", "play hide-and-seek", "watch TV"], [0]]}, {"p": [4, [1, 2, 3, 0], [3], ["play the piano", "play hide-and-seek", "watch TV", "play computer games"], [0]]}, {"p": [5, [3, 1, 2, 0], [3], ["play hide-and-seek", "watch TV", "play computer games", "play with toys"], [0]]}, {"p": [6, [2, 3, 1, 0], [3], ["watch TV", "play computer games", "play with toys", "play ball"], [0]]}, {"p": [7, [3, 0, 2, 1], [1], ["play computer games", "play with toys", "play ball", "sing"], [0]]}, {"p": [8, [2, 3, 1, 0], [3], ["play with toys", "play ball", "sing", "play board games"], [0]]}, {"p": [9, [3, 2, 0, 1], [3], ["go swimming", "play ball", "sing", "play board games"], [1]]}, {"p": [10, [3, 2, 0, 1], [1], ["go swimming", "ride a pony", "sing", "play board games"], [2]]}, {"p": [11, [1, 2, 3, 0], [2], ["go swimming", "ride a pony", "ride a bike", "play board games"], [3]]}]$o$)  -- U5 Homework 2 b4 (quiz): p,
('08d7a1f3-d919-4918-a6e2-1e935c50f99b', $o$[{"s": [["audio_tts"], "Hi! I'm Susie. On Mondays I go swimming. On Tuesdays I play ball with my friends. On Fridays I play football. On Sundays I ride my bike."]}]$o$)  -- U5 Homework 2 b17 (text): s
),
u as (update classroom_blocks b set payload = sm1fix_apply(b.payload, v.ops::jsonb), updated_at = now()
  from v where b.id = v.id::uuid returning b.id)
select count(*) from u;

drop function sm1fix_apply(jsonb, jsonb);
