-- Super Minds 1 · Unit 6 · My house · Homework 1
-- собрано tools/sm1_build.py --lesson u6_hw1
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where slug = 'sm1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 6 · My house', 6
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 6 · My house');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 6 · My house';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 1', 'homework',
         60, false, 0
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 1');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 1';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет! 👋</h2><p>Сейчас мы с тобой выучим все слова, которые разобрали на уроке: комнаты в доме. Выполни все задания, чтобы выучить слова на 100%!</p><p>В конце первой части тебя ждёт тест. А потом — вторая часть и ДОПОЛНИТЕЛЬНОЕ задание. Его можно выполнить по желанию, но если ты его сделаешь — ты будешь МЕГА КРУТЫМ! У тебя всё получится. Удачи! ❤</p><p><img src=\"@@MEDIA@@sm1/u6/house_outside.webp\" alt=\"\" style=\"max-width:100%;max-height:260px\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"title": "Запомни слова. Нажми на карточку, чтобы увидеть перевод", "cards": [{"text": "bathroom", "translation": "ванная", "audio_tts": "bathroom", "image": "@@MEDIA@@sm1/u6/room_bathroom.webp"}, {"text": "bedroom", "translation": "спальня", "audio_tts": "bedroom", "image": "@@MEDIA@@sm1/u6/room_bedroom.webp"}, {"text": "living room", "translation": "гостиная", "audio_tts": "living room", "image": "@@MEDIA@@sm1/u6/room_living_room.webp"}, {"text": "hall", "translation": "коридор", "audio_tts": "hall", "image": "@@MEDIA@@sm1/u6/room_hall.webp"}, {"text": "dining room", "translation": "столовая", "audio_tts": "dining room", "image": "@@MEDIA@@sm1/u6/room_dining_room.webp"}, {"text": "kitchen", "translation": "кухня", "audio_tts": "kitchen", "image": "@@MEDIA@@sm1/u6/room_kitchen.webp"}, {"text": "stairs", "translation": "лестница", "audio_tts": "stairs", "image": "@@MEDIA@@sm1/u6/room_stairs.webp"}, {"text": "cellar", "translation": "подвал", "audio_tts": "cellar", "image": "@@MEDIA@@sm1/u6/room_cellar.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Послушай слово и выбери его.", "type": "single", "correct": [0], "options": [{"text": "bathroom"}, {"text": "bedroom"}, {"text": "living room"}, {"text": "hall"}], "audio_tts": "bathroom"}, {"q": "Послушай слово и выбери его.", "type": "single", "correct": [1], "options": [{"text": "living room"}, {"text": "bedroom"}, {"text": "hall"}, {"text": "dining room"}], "audio_tts": "bedroom"}, {"q": "Послушай слово и выбери его.", "type": "single", "correct": [2], "options": [{"text": "hall"}, {"text": "dining room"}, {"text": "living room"}, {"text": "kitchen"}], "audio_tts": "living room"}, {"q": "Послушай слово и выбери его.", "type": "single", "correct": [3], "options": [{"text": "dining room"}, {"text": "kitchen"}, {"text": "stairs"}, {"text": "hall"}], "audio_tts": "hall"}, {"q": "Послушай слово и выбери его.", "type": "single", "correct": [0], "options": [{"text": "dining room"}, {"text": "kitchen"}, {"text": "stairs"}, {"text": "cellar"}], "audio_tts": "dining room"}, {"q": "Послушай слово и выбери его.", "type": "single", "correct": [1], "options": [{"text": "stairs"}, {"text": "kitchen"}, {"text": "cellar"}, {"text": "bathroom"}], "audio_tts": "kitchen"}, {"q": "Послушай слово и выбери его.", "type": "single", "correct": [2], "options": [{"text": "cellar"}, {"text": "bathroom"}, {"text": "stairs"}, {"text": "bedroom"}], "audio_tts": "stairs"}, {"q": "Послушай слово и выбери его.", "type": "single", "correct": [3], "options": [{"text": "bathroom"}, {"text": "bedroom"}, {"text": "living room"}, {"text": "cellar"}], "audio_tts": "cellar"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'match', replace($blk${"title": "Найди пару: слово и перевод", "pairs": [{"left": "bathroom", "right": "ванная", "left_audio_tts": "bathroom"}, {"left": "bedroom", "right": "спальня", "left_audio_tts": "bedroom"}, {"left": "living room", "right": "гостиная", "left_audio_tts": "living room"}, {"left": "hall", "right": "коридор", "left_audio_tts": "hall"}, {"left": "dining room", "right": "столовая", "left_audio_tts": "dining room"}, {"left": "kitchen", "right": "кухня", "left_audio_tts": "kitchen"}, {"left": "stairs", "right": "лестница", "left_audio_tts": "stairs"}, {"left": "cellar", "right": "подвал", "left_audio_tts": "cellar"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'order', replace($blk${"title": "Собери слово: ванная", "image": "@@MEDIA@@sm1/u6/room_bathroom.webp", "words": ["b", "a", "t", "h", "r", "o", "o", "m"], "sentence": "b a t h r o o m", "audio_tts": "bathroom"}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'order', replace($blk${"title": "Собери слово: спальня", "image": "@@MEDIA@@sm1/u6/room_bedroom.webp", "words": ["b", "e", "d", "r", "o", "o", "m"], "sentence": "b e d r o o m", "audio_tts": "bedroom"}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'order', replace($blk${"title": "Собери слово: гостиная (два слова)", "image": "@@MEDIA@@sm1/u6/room_living_room.webp", "words": ["l", "i", "v", "i", "n", "g", "r", "o", "o", "m"], "sentence": "l i v i n g r o o m", "audio_tts": "living room"}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'order', replace($blk${"title": "Собери слово: коридор", "image": "@@MEDIA@@sm1/u6/room_hall.webp", "words": ["h", "a", "l", "l"], "sentence": "h a l l", "audio_tts": "hall"}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'order', replace($blk${"title": "Собери слово: столовая (два слова)", "image": "@@MEDIA@@sm1/u6/room_dining_room.webp", "words": ["d", "i", "n", "i", "n", "g", "r", "o", "o", "m"], "sentence": "d i n i n g r o o m", "audio_tts": "dining room"}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'order', replace($blk${"title": "Собери слово: кухня", "image": "@@MEDIA@@sm1/u6/room_kitchen.webp", "words": ["k", "i", "t", "c", "h", "e", "n"], "sentence": "k i t c h e n", "audio_tts": "kitchen"}$blk$, '@@MEDIA@@', v_media)::jsonb, 9),
    (v_lesson, 'order', replace($blk${"title": "Собери слово: лестница", "image": "@@MEDIA@@sm1/u6/room_stairs.webp", "words": ["s", "t", "a", "i", "r", "s"], "sentence": "s t a i r s", "audio_tts": "stairs"}$blk$, '@@MEDIA@@', v_media)::jsonb, 10),
    (v_lesson, 'order', replace($blk${"title": "Собери слово: подвал", "image": "@@MEDIA@@sm1/u6/room_cellar.webp", "words": ["c", "e", "l", "l", "a", "r"], "sentence": "c e l l a r", "audio_tts": "cellar"}$blk$, '@@MEDIA@@', v_media)::jsonb, 11),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Посмотри на картинку и выбери слово.", "type": "single", "correct": [0], "options": [{"text": "bathroom", "audio_tts": "bathroom"}, {"text": "bedroom", "audio_tts": "bedroom"}, {"text": "living room", "audio_tts": "living room"}, {"text": "hall", "audio_tts": "hall"}], "image": "@@MEDIA@@sm1/u6/room_bathroom.webp"}, {"q": "Посмотри на картинку и выбери слово.", "type": "single", "correct": [1], "options": [{"text": "living room", "audio_tts": "living room"}, {"text": "bedroom", "audio_tts": "bedroom"}, {"text": "hall", "audio_tts": "hall"}, {"text": "dining room", "audio_tts": "dining room"}], "image": "@@MEDIA@@sm1/u6/room_bedroom.webp"}, {"q": "Посмотри на картинку и выбери слово.", "type": "single", "correct": [2], "options": [{"text": "hall", "audio_tts": "hall"}, {"text": "dining room", "audio_tts": "dining room"}, {"text": "living room", "audio_tts": "living room"}, {"text": "kitchen", "audio_tts": "kitchen"}], "image": "@@MEDIA@@sm1/u6/room_living_room.webp"}, {"q": "Посмотри на картинку и выбери слово.", "type": "single", "correct": [3], "options": [{"text": "dining room", "audio_tts": "dining room"}, {"text": "kitchen", "audio_tts": "kitchen"}, {"text": "stairs", "audio_tts": "stairs"}, {"text": "hall", "audio_tts": "hall"}], "image": "@@MEDIA@@sm1/u6/room_hall.webp"}, {"q": "Посмотри на картинку и выбери слово.", "type": "single", "correct": [0], "options": [{"text": "dining room", "audio_tts": "dining room"}, {"text": "kitchen", "audio_tts": "kitchen"}, {"text": "stairs", "audio_tts": "stairs"}, {"text": "cellar", "audio_tts": "cellar"}], "image": "@@MEDIA@@sm1/u6/room_dining_room.webp"}, {"q": "Посмотри на картинку и выбери слово.", "type": "single", "correct": [1], "options": [{"text": "stairs", "audio_tts": "stairs"}, {"text": "kitchen", "audio_tts": "kitchen"}, {"text": "cellar", "audio_tts": "cellar"}, {"text": "bathroom", "audio_tts": "bathroom"}], "image": "@@MEDIA@@sm1/u6/room_kitchen.webp"}, {"q": "Посмотри на картинку и выбери слово.", "type": "single", "correct": [2], "options": [{"text": "cellar", "audio_tts": "cellar"}, {"text": "bathroom", "audio_tts": "bathroom"}, {"text": "stairs", "audio_tts": "stairs"}, {"text": "bedroom", "audio_tts": "bedroom"}], "image": "@@MEDIA@@sm1/u6/room_stairs.webp"}, {"q": "Посмотри на картинку и выбери слово.", "type": "single", "correct": [3], "options": [{"text": "bathroom", "audio_tts": "bathroom"}, {"text": "bedroom", "audio_tts": "bedroom"}, {"text": "living room", "audio_tts": "living room"}, {"text": "cellar", "audio_tts": "cellar"}], "image": "@@MEDIA@@sm1/u6/room_cellar.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 12),
    (v_lesson, 'exact_input', replace($blk${"items": [{"image": "@@MEDIA@@sm1/u6/room_bathroom.webp", "prompt": "Напиши по-английски: ванная", "accept": ["bathroom", "Bathroom"], "audio_tts": "bathroom"}, {"image": "@@MEDIA@@sm1/u6/room_bedroom.webp", "prompt": "Напиши по-английски: спальня", "accept": ["bedroom", "Bedroom"], "audio_tts": "bedroom"}, {"image": "@@MEDIA@@sm1/u6/room_living_room.webp", "prompt": "Напиши по-английски: гостиная", "accept": ["living room", "Living room"], "audio_tts": "living room"}, {"image": "@@MEDIA@@sm1/u6/room_hall.webp", "prompt": "Напиши по-английски: коридор", "accept": ["hall", "Hall"], "audio_tts": "hall"}, {"image": "@@MEDIA@@sm1/u6/room_dining_room.webp", "prompt": "Напиши по-английски: столовая", "accept": ["dining room", "Dining room"], "audio_tts": "dining room"}, {"image": "@@MEDIA@@sm1/u6/room_kitchen.webp", "prompt": "Напиши по-английски: кухня", "accept": ["kitchen", "Kitchen"], "audio_tts": "kitchen"}, {"image": "@@MEDIA@@sm1/u6/room_stairs.webp", "prompt": "Напиши по-английски: лестница", "accept": ["stairs", "Stairs"], "audio_tts": "stairs"}, {"image": "@@MEDIA@@sm1/u6/room_cellar.webp", "prompt": "Напиши по-английски: подвал", "accept": ["cellar", "Cellar"], "audio_tts": "cellar"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 13),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_rocket.webp\" alt=\"\" style=\"height:180px\"></p><h3>Ты выучил все комнаты! 🎉</h3><p>Добро пожаловать во вторую часть домашнего задания. Выполни все задания, чтобы хорошенько запомнить новые слова!</p><p>Выполнив это задание, ты станешь МЕГА крутым учеником!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 14),
    (v_lesson, 'text', replace($blk${"html": "<h3>Давай повторим всё, что выучили с тобой на уроке:</h3><p><img src=\"@@MEDIA@@sm1/u6/card_rooms_vocab.webp\" alt=\"Vocabulary — Rooms in the House\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 15),
    (v_lesson, 'speaking', replace($blk${"title": "Какие комнаты есть в твоём доме? 🎤", "html": "<p>Запиши аудио, где ты называешь все комнаты, которые есть в твоём доме.</p><p>Послушай пример ответа, а потом нажми на микрофон.</p><p><i>Например: a kitchen, a bathroom, a living room, two bedrooms, a hall.</i></p>", "sample": "", "sample_tts": "In my house there is a kitchen, a bathroom, a living room, two bedrooms and a hall.", "needs_review": true}$blk$, '@@MEDIA@@', v_media)::jsonb, 16),
    (v_lesson, 'match', replace($blk${"title": "⭐ Ты выполнил все задания из основной части! А это дополнительное задание — для настоящих чемпионов! Соедини картинки со словами:", "pairs": [{"left_image": "@@MEDIA@@sm1/u6/room_bathroom.webp", "right": "bathroom", "right_audio_tts": "bathroom"}, {"left_image": "@@MEDIA@@sm1/u6/room_bedroom.webp", "right": "bedroom", "right_audio_tts": "bedroom"}, {"left_image": "@@MEDIA@@sm1/u6/room_living_room.webp", "right": "living room", "right_audio_tts": "living room"}, {"left_image": "@@MEDIA@@sm1/u6/room_hall.webp", "right": "hall", "right_audio_tts": "hall"}, {"left_image": "@@MEDIA@@sm1/u6/room_dining_room.webp", "right": "dining room", "right_audio_tts": "dining room"}, {"left_image": "@@MEDIA@@sm1/u6/room_kitchen.webp", "right": "kitchen", "right_audio_tts": "kitchen"}, {"left_image": "@@MEDIA@@sm1/u6/room_stairs.webp", "right": "stairs", "right_audio_tts": "stairs"}, {"left_image": "@@MEDIA@@sm1/u6/room_cellar.webp", "right": "cellar", "right_audio_tts": "cellar"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 17),
    (v_lesson, 'exact_input', replace($blk${"items": [{"image": "@@MEDIA@@sm1/u6/room_bathroom.webp", "prompt": "⭐ Впиши слово: что это за комната?", "accept": ["bathroom", "Bathroom", "a bathroom", "the bathroom"]}, {"image": "@@MEDIA@@sm1/u6/room_bedroom.webp", "prompt": "⭐ Впиши слово: что это за комната?", "accept": ["bedroom", "Bedroom", "a bedroom", "the bedroom"]}, {"image": "@@MEDIA@@sm1/u6/room_living_room.webp", "prompt": "⭐ Впиши слово: что это за комната?", "accept": ["living room", "Living room", "a living room", "the living room"]}, {"image": "@@MEDIA@@sm1/u6/room_hall.webp", "prompt": "⭐ Впиши слово: что это за комната?", "accept": ["hall", "Hall", "a hall", "the hall"]}, {"image": "@@MEDIA@@sm1/u6/room_dining_room.webp", "prompt": "⭐ Впиши слово: что это за комната?", "accept": ["dining room", "Dining room", "a dining room", "the dining room"]}, {"image": "@@MEDIA@@sm1/u6/room_kitchen.webp", "prompt": "⭐ Впиши слово: что это за комната?", "accept": ["kitchen", "Kitchen", "a kitchen", "the kitchen"]}, {"image": "@@MEDIA@@sm1/u6/room_stairs.webp", "prompt": "⭐ Впиши слово: что это за комната?", "accept": ["stairs", "Stairs", "a stairs", "the stairs"]}, {"image": "@@MEDIA@@sm1/u6/room_cellar.webp", "prompt": "⭐ Впиши слово: что это за комната?", "accept": ["cellar", "Cellar", "a cellar", "the cellar"]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 18),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_trophy.webp\" alt=\"\" style=\"height:180px\"></p><h3>Поздравляю! Ты завершил домашнее задание. Ты — МЕГА КРУТ! 🎉</h3><p>Жду тебя на уроке!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 19);
end
$mig$;
