-- Super Minds 1 · Unit 7 · Get dressed · Unit 7 Test
-- собрано tools/sm1_build.py --lesson u7_test
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where slug = 'sm1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 7 · Get dressed', 7
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 7 · Get dressed');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 7 · Get dressed';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Unit 7 Test', 'test',
         90, false, 7
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Unit 7 Test');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Unit 7 Test';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'exact_input', replace($blk${"items": [{"prompt": "Напиши по-английски: джинсы", "accept": ["jeans", "Jeans"], "audio_tts": "jeans"}, {"prompt": "Напиши по-английски: свитер", "accept": ["sweater", "Sweater"], "audio_tts": "sweater"}, {"prompt": "Напиши по-английски: пиджак, куртка", "accept": ["jacket", "Jacket"], "audio_tts": "jacket"}, {"prompt": "Напиши по-английски: юбка", "accept": ["skirt", "Skirt"], "audio_tts": "skirt"}, {"prompt": "Напиши по-английски: шорты", "accept": ["shorts", "Shorts"], "audio_tts": "shorts"}, {"prompt": "Напиши по-английски: бейсболка, кепка", "accept": ["baseball cap", "Baseball cap", "cap"], "audio_tts": "baseball cap"}, {"prompt": "Напиши по-английски: обувь", "accept": ["shoes", "Shoes"], "audio_tts": "shoes"}, {"prompt": "Напиши по-английски: носки", "accept": ["socks", "Socks"], "audio_tts": "socks"}, {"prompt": "Напиши по-английски: футболка", "accept": ["T-shirt", "t-shirt", "T shirt", "tshirt"], "audio_tts": "T-shirt"}, {"prompt": "Напиши по-английски: брюки", "accept": ["trousers", "Trousers"], "audio_tts": "trousers"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'match', replace($blk${"title": "Соедини слова с картинками:", "pairs": [{"left": "sweater", "left_audio_tts": "sweater", "right": "картинка sweater", "right_image": "@@MEDIA@@sm1/u7/clothes_sweater.webp"}, {"left": "T-shirt", "left_audio_tts": "T-shirt", "right": "картинка T-shirt", "right_image": "@@MEDIA@@sm1/u7/clothes_tshirt.webp"}, {"left": "baseball cap", "left_audio_tts": "baseball cap", "right": "картинка baseball cap", "right_image": "@@MEDIA@@sm1/u7/clothes_cap.webp"}, {"left": "jacket", "left_audio_tts": "jacket", "right": "картинка jacket", "right_image": "@@MEDIA@@sm1/u7/clothes_jacket.webp"}, {"left": "jeans", "left_audio_tts": "jeans", "right": "картинка jeans", "right_image": "@@MEDIA@@sm1/u7/clothes_jeans.webp"}, {"left": "skirt", "left_audio_tts": "skirt", "right": "картинка skirt", "right_image": "@@MEDIA@@sm1/u7/clothes_skirt.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'quiz', replace($blk${"title": "Заполни пропуски — выбери подходящий вариант", "questions": [{"q": "Заполни пропуски — выбери подходящий вариант.<br>A: Do you like ___ hat?<br>B: Yes, I do.", "type": "single", "image": "@@MEDIA@@sm1/u7/clothes_hat_elephant.webp", "options": [{"text": "these"}, {"text": "this"}], "correct": [1]}, {"q": "A: Do you like this hat?<br>B: Yes, I ___.", "type": "single", "image": "@@MEDIA@@sm1/u7/clothes_hat_elephant.webp", "options": [{"text": "do"}, {"text": "like"}, {"text": "don't"}], "correct": [0]}, {"q": "A: Do you like ___ socks?<br>B: No, I don't.", "type": "single", "image": "@@MEDIA@@sm1/u7/clothes_socks_faces.webp", "options": [{"text": "this"}, {"text": "these"}], "correct": [1]}, {"q": "A: Do you like these socks?<br>B: No, I ___.", "type": "single", "image": "@@MEDIA@@sm1/u7/clothes_socks_faces.webp", "options": [{"text": "do"}, {"text": "don't"}], "correct": [1]}, {"q": "Olivia is ___ a red sweater.", "type": "single", "image": "@@MEDIA@@sm1/u7/clothes_sweater_red.webp", "options": [{"text": "wear"}, {"text": "wears"}, {"text": "wearing"}], "correct": [2]}, {"q": "A: ___ he watching TV?<br>B: No, he isn't.", "type": "single", "image": "@@MEDIA@@sm1/u7/obj_tv.webp", "options": [{"text": "Is"}, {"text": "Are"}, {"text": "Do"}], "correct": [0]}, {"q": "A: Is he watching TV?<br>B: No, he ___.", "type": "single", "image": "@@MEDIA@@sm1/u7/obj_tv.webp", "options": [{"text": "is"}, {"text": "does"}, {"text": "isn't"}], "correct": [2]}, {"q": "A: ___ Kate singing?<br>B: Yes, she is.", "type": "single", "image": "@@MEDIA@@sm1/u7/obj_microphone.webp", "options": [{"text": "Are"}, {"text": "Is"}, {"text": "Does"}], "correct": [1]}, {"q": "A: Is Kate singing?<br>B: Yes, she ___.", "type": "single", "image": "@@MEDIA@@sm1/u7/obj_microphone.webp", "options": [{"text": "sing"}, {"text": "isn't"}, {"text": "is"}], "correct": [2]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'order', replace($blk${"image": "@@MEDIA@@sm1/u7/obj_bikes.webp", "words": ["Are", "Amy", "and Hannah", "riding", "bikes?"], "sentence": "Are Amy and Hannah riding bikes?", "audio_tts": "Are Amy and Hannah riding bikes?"}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'order', replace($blk${"image": "@@MEDIA@@sm1/u7/clothes_shoes.webp", "words": ["Do", "you", "like", "these", "shoes?"], "sentence": "Do you like these shoes?", "audio_tts": "Do you like these shoes?"}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'order', replace($blk${"image": "@@MEDIA@@sm1/u7/obj_game_controllers.webp", "words": ["They", "are", "playing", "computer", "games."], "sentence": "They are playing computer games.", "audio_tts": "They are playing computer games."}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'order', replace($blk${"image": "@@MEDIA@@sm1/u7/clothes_shorts.webp", "words": ["Do", "you", "like", "these", "shorts?"], "sentence": "Do you like these shorts?", "audio_tts": "Do you like these shorts?"}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'order', replace($blk${"image": "@@MEDIA@@sm1/u7/obj_sandwich.webp", "words": ["Is", "Bobby", "eating", "a", "sandwich?"], "sentence": "Is Bobby eating a sandwich?", "audio_tts": "Is Bobby eating a sandwich?"}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'text', replace($blk${"html": "<p><b>Прочитай текст и выбери правильный вариант ответа к вопросам 1–5.</b></p><p>Today is a fun day! The children are at a fashion show at school.</p><p>Look at Tom! He is wearing a brown jacket and blue trousers. His T-shirt is black. “Do you like my jacket?” Tom asks. “Yes, I do! It's cool!” says Emma.</p><p>Emma is wearing a blue sweater and brown shorts. She is wearing blue shoes too. Her sweater is plain — no spots, no stripes!</p><p>Lily is wearing a yellow dress. The dress has got flowers. “I love my dress!” says Lily. “Do you like these shoes?” She is wearing brown sandals.</p><p>Ben is wearing a blue T-shirt and brown trousers. “Is Ben wearing a cap?” asks Emma. “No, he isn't,” says Tom. “But look at his bag! It's blue!”</p><p>Sofia is wearing a blue jacket and a white shirt. Her trousers are blue and her shoes are pink. “I love pink!” says Sofia. “Pink is my favourite colour!”</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'quiz', replace($blk${"title": "Прочитай текст и выбери правильный вариант ответа", "questions": [{"q": "1. What colour is Tom's jacket?", "type": "single", "options": [{"text": "A) black"}, {"text": "B) blue"}, {"text": "C) brown"}], "correct": [2]}, {"q": "2. What pattern has Emma's sweater got?", "type": "single", "options": [{"text": "A) spots"}, {"text": "B) no pattern — it's plain"}, {"text": "C) stripes"}], "correct": [1]}, {"q": "3. What has Lily's dress got?", "type": "single", "options": [{"text": "A) stripes"}, {"text": "B) flowers"}, {"text": "C) zigzags"}], "correct": [1]}, {"q": "4. Is Ben wearing a cap?", "type": "single", "options": [{"text": "A) No, he isn't."}, {"text": "B) Yes, he is."}, {"text": "C) We don't know."}], "correct": [0]}, {"q": "5. What colour are Sofia's shoes?", "type": "single", "options": [{"text": "A) blue"}, {"text": "B) white"}, {"text": "C) pink"}], "correct": [2]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 9),
    (v_lesson, 'speaking', replace($blk${"title": "SPEAKING TASK · Part 1 🎤", "needs_review": true, "image": "@@MEDIA@@sm1/u7/scene_clothes_shop.webp", "html": "<p>Посмотри на картинку, расскажи, какая одежда тебе нравится (используй this / these).</p><p><i>For example: I like this yellow dress.</i></p><p>Запиши свой ответ, нажав на кнопку микрофона 🙌</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 10),
    (v_lesson, 'speaking', replace($blk${"title": "SPEAKING TASK · Part 2 🎤", "needs_review": true, "image": "@@MEDIA@@sm1/u7/chars_three.webp", "html": "<p>Посмотри на картинку. Выбери двоих ребят и расскажи, кто во что одет.</p><p><i>For example: He is wearing a red jacket, a white T-shirt, brown trousers and orange shoes.</i></p><p>Запиши свой ответ, нажав на кнопку микрофона 🙌</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 11);
end
$mig$;
