-- Super Minds 1 · Unit 6 · My house · Homework 3
-- собрано tools/sm1_build.py --lesson u6_hw3
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where slug = 'sm1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 6 · My house', 6
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 6 · My house');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 6 · My house';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 3', 'homework',
         60, false, 2
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 3');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 3';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_laptop.webp\" alt=\"\" style=\"height:200px\"></p><h2>Добро пожаловать в домашнее задание!</h2><p>Впереди тебя ждут несколько интересных видео и увлекательных упражнений.</p><p>За каждое задание ты будешь получать ⭐ Собери максимальное количество звёздочек и стань ЧЕМПИОНОМ!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'text', replace($blk${"html": "<h3>Давай повторим всё, что выучили с тобой на уроке:</h3><p><img src=\"@@MEDIA@@sm1/u6/card_grammar_is_there.webp\" alt=\"Is there…? / Are there…?\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'video', replace($blk${"title": "Ура! Мы с тобой посмотрим интересное видео. В этом видео ты увидишь много животных. Попробуй угадать, какие животные встретятся тебе в видео? Для начала посмотри видео один раз, внимательно слушай, что говорят персонажи. Потом посмотри видео ещё раз и повторяй за персонажами.", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Посмотри видео ещё раз и на картинку. Выбери ответ на вопрос. Are there five lions?", "type": "single", "audio_tts": "Are there five lions?", "options": [{"text": "Yes, there is."}, {"text": "No, there aren't."}, {"text": "No, there isn't."}, {"text": "Yes, there are."}], "correct": [1], "image": "@@MEDIA@@sm1/u6/hw3_lions.webp"}, {"q": "Is there a small ball?", "type": "single", "audio_tts": "Is there a small ball?", "options": [{"text": "No, there isn't."}, {"text": "Yes, there is."}, {"text": "Yes, there are."}, {"text": "No, there aren't."}], "correct": [0], "image": "@@MEDIA@@sm1/u6/hw3_ball.webp"}, {"q": "Is there a dragon?", "type": "single", "audio_tts": "Is there a dragon?", "options": [{"text": "No, there isn't."}, {"text": "No, there aren't."}, {"text": "Yes, there is."}, {"text": "Yes, there are."}], "correct": [2], "image": "@@MEDIA@@sm1/u6/hw3_dragon.webp"}, {"q": "Are there four dogs?", "type": "single", "audio_tts": "Are there four dogs?", "options": [{"text": "No, there aren't."}, {"text": "No, there isn't."}, {"text": "Yes, there is."}, {"text": "Yes, there are."}], "correct": [3], "image": "@@MEDIA@@sm1/u6/hw3_dogs.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Ты посмотрел видео, и сейчас нужно выполнить ещё одно задание. Выбери правильный вариант: ___ there any pears?", "type": "single", "options": [{"text": "Are"}, {"text": "Is"}], "correct": [0], "image": "@@MEDIA@@sm1/u6/test_pears.webp"}, {"q": "___ there any rats?", "type": "single", "options": [{"text": "Is"}, {"text": "Are"}], "correct": [1], "image": "@@MEDIA@@sm1/u6/hw3_rats.webp"}, {"q": "How many cars ___ there?", "type": "single", "options": [{"text": "is"}, {"text": "are"}], "correct": [1], "image": "@@MEDIA@@sm1/u6/hw3_cars.webp"}, {"q": "___ there a plane?", "type": "single", "options": [{"text": "Is"}, {"text": "Are"}], "correct": [0], "image": "@@MEDIA@@sm1/u6/test_plane.webp"}, {"q": "___ there a go-kart?", "type": "single", "options": [{"text": "Are"}, {"text": "Is"}], "correct": [1], "image": "@@MEDIA@@sm1/u6/hw3_go_kart.webp"}, {"q": "How many cakes ___ there?", "type": "single", "options": [{"text": "is"}, {"text": "are"}], "correct": [1], "image": "@@MEDIA@@sm1/u6/hw3_cake.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'task', replace($blk${"title": "Посмотри на картинку и впиши ответы на вопросы ✏️", "image": "@@MEDIA@@sm1/u6/hw3_house_rooms.webp", "needs_review": true, "html": "<p>Внимательно посмотри на картинку. Впиши ответы на вопросы 1–8. Первые три вопроса — примеры, на них уже есть ответы.</p><p><i>How many bedrooms are there? — There are two bedrooms.<br>Are there two living rooms? — No, there aren't.<br>Is there a bathroom? — Yes, there is.</i></p><ol><li>How many rooms are there?</li><li>Are there two bedrooms?</li><li>Is there a hall?</li><li>Is there a living room?</li><li>Are there 3 rooms?</li><li>Are there 4 bedrooms?</li><li>Is there a dining room?</li><li>Is there a kitchen?</li></ol>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "⭐ Ты выполнил все задания из основной части! А это дополнительное задание — для настоящих чемпионов! Выбери правильный вариант: ___ there a kitchen in the house?", "type": "single", "options": [{"text": "Is"}, {"text": "Are"}], "correct": [0]}, {"q": "___ there any chairs in the dining room?", "type": "single", "options": [{"text": "Is"}, {"text": "Are"}], "correct": [1]}, {"q": "___ there a sofa in the living room?", "type": "single", "options": [{"text": "Are"}, {"text": "Is"}], "correct": [1]}, {"q": "How many bedrooms ___ there?", "type": "single", "options": [{"text": "are"}, {"text": "is"}], "correct": [0]}, {"q": "___ there any lizards in the bathroom?", "type": "single", "options": [{"text": "Is"}, {"text": "Are"}], "correct": [1]}, {"q": "___ there a cellar in the house?", "type": "single", "options": [{"text": "Are"}, {"text": "Is"}], "correct": [1]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "⭐ Посмотри на картинку дома и выбери правильный ответ. Is there a sofa in the living room?", "type": "single", "audio_tts": "Is there a sofa in the living room?", "options": [{"text": "Yes, there is."}, {"text": "No, there isn't."}, {"text": "Yes, there are."}, {"text": "No, there aren't."}], "correct": [0], "image": "@@MEDIA@@sm1/u6/hw3_house_rooms.webp"}, {"q": "Is there a fridge in the kitchen?", "type": "single", "audio_tts": "Is there a fridge in the kitchen?", "options": [{"text": "No, there isn't."}, {"text": "Yes, there is."}, {"text": "No, there aren't."}, {"text": "Yes, there are."}], "correct": [1], "image": "@@MEDIA@@sm1/u6/hw3_house_rooms.webp"}, {"q": "Are there any cats in the house?", "type": "single", "audio_tts": "Are there any cats in the house?", "options": [{"text": "Yes, there are."}, {"text": "No, there aren't."}, {"text": "Yes, there is."}, {"text": "No, there isn't."}], "correct": [1], "image": "@@MEDIA@@sm1/u6/hw3_house_rooms.webp"}, {"q": "Is there a car in the kitchen?", "type": "single", "audio_tts": "Is there a car in the kitchen?", "options": [{"text": "No, there aren't."}, {"text": "Yes, there are."}, {"text": "No, there isn't."}, {"text": "Yes, there is."}], "correct": [2], "image": "@@MEDIA@@sm1/u6/hw3_house_rooms.webp"}, {"q": "Are there any lamps in the living room?", "type": "single", "audio_tts": "Are there any lamps in the living room?", "options": [{"text": "No, there isn't."}, {"text": "Yes, there is."}, {"text": "No, there aren't."}, {"text": "Yes, there are."}], "correct": [3], "image": "@@MEDIA@@sm1/u6/hw3_house_rooms.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_jump.webp\" alt=\"\" style=\"height:180px\"></p><h3>Ура, ты справился со всеми заданиями, ты — супер ученик! 💜</h3><p>Увидимся на занятии!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 8);
end
$mig$;
