-- Super Minds 1 · Unit 7 · Get dressed · Homework 1
-- собрано tools/sm1_build.py --lesson u7_hw1
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where slug = 'sm1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 7 · Get dressed', 7
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 7 · Get dressed');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 7 · Get dressed';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 1', 'homework',
         60, false, 0
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 1');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 1';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Добро пожаловать в домашнее задание! 👋</h2><p>В этом уроке тебя ждут задания на отработку новых слов — мы выучим, как по-английски называется одежда. Выполни все задания, если хочешь выучить тему на все 100!</p><p>После того как завершишь все задания, тебя ждёт дополнительная часть — её можно выполнить по желанию, НО если ты выполнишь её, то будешь нереально крут!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"title": "Запомни слова. Нажми на карточку, чтобы увидеть перевод", "cards": [{"text": "jeans", "translation": "джинсы", "audio_tts": "jeans", "image": "@@MEDIA@@sm1/u7/clothes_jeans.webp"}, {"text": "sweater", "translation": "свитер", "audio_tts": "sweater", "image": "@@MEDIA@@sm1/u7/clothes_sweater.webp"}, {"text": "jacket", "translation": "пиджак, куртка", "audio_tts": "jacket", "image": "@@MEDIA@@sm1/u7/clothes_jacket.webp"}, {"text": "skirt", "translation": "юбка", "audio_tts": "skirt", "image": "@@MEDIA@@sm1/u7/clothes_skirt.webp"}, {"text": "shorts", "translation": "шорты", "audio_tts": "shorts", "image": "@@MEDIA@@sm1/u7/clothes_shorts.webp"}, {"text": "baseball cap", "translation": "бейсболка, кепка", "audio_tts": "baseball cap", "image": "@@MEDIA@@sm1/u7/clothes_cap.webp"}, {"text": "shoes", "translation": "обувь", "audio_tts": "shoes", "image": "@@MEDIA@@sm1/u7/clothes_shoes.webp"}, {"text": "socks", "translation": "носки", "audio_tts": "socks", "image": "@@MEDIA@@sm1/u7/clothes_socks.webp"}, {"text": "T-shirt", "translation": "футболка", "audio_tts": "T-shirt", "image": "@@MEDIA@@sm1/u7/clothes_tshirt.webp"}, {"text": "trousers", "translation": "брюки", "audio_tts": "trousers", "image": "@@MEDIA@@sm1/u7/clothes_trousers.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «джинсы»?", "type": "single", "options": [{"text": "jacket"}, {"text": "jeans"}, {"text": "skirt"}, {"text": "sweater"}], "correct": [1]}, {"q": "Как по-английски «свитер»?", "type": "single", "options": [{"text": "jacket"}, {"text": "shorts"}, {"text": "skirt"}, {"text": "sweater"}], "correct": [3]}, {"q": "Как по-английски «пиджак, куртка»?", "type": "single", "options": [{"text": "baseball cap"}, {"text": "jacket"}, {"text": "shorts"}, {"text": "skirt"}], "correct": [1]}, {"q": "Как по-английски «юбка»?", "type": "single", "options": [{"text": "baseball cap"}, {"text": "shoes"}, {"text": "shorts"}, {"text": "skirt"}], "correct": [3]}, {"q": "Как по-английски «шорты»?", "type": "single", "options": [{"text": "baseball cap"}, {"text": "shoes"}, {"text": "shorts"}, {"text": "socks"}], "correct": [2]}, {"q": "Как по-английски «бейсболка, кепка»?", "type": "single", "options": [{"text": "baseball cap"}, {"text": "shoes"}, {"text": "socks"}, {"text": "T-shirt"}], "correct": [0]}, {"q": "Как по-английски «обувь»?", "type": "single", "options": [{"text": "shoes"}, {"text": "socks"}, {"text": "T-shirt"}, {"text": "trousers"}], "correct": [0]}, {"q": "Как по-английски «носки»?", "type": "single", "options": [{"text": "jeans"}, {"text": "socks"}, {"text": "T-shirt"}, {"text": "trousers"}], "correct": [1]}, {"q": "Как по-английски «футболка»?", "type": "single", "options": [{"text": "jeans"}, {"text": "sweater"}, {"text": "T-shirt"}, {"text": "trousers"}], "correct": [2]}, {"q": "Как по-английски «брюки»?", "type": "single", "options": [{"text": "jacket"}, {"text": "jeans"}, {"text": "sweater"}, {"text": "trousers"}], "correct": [3]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Послушай слово и выбери его", "type": "single", "audio_tts": "jeans", "options": [{"text": "jeans"}, {"text": "sweater"}, {"text": "jacket"}, {"text": "skirt"}], "correct": [0]}, {"q": "Послушай слово и выбери его", "type": "single", "audio_tts": "sweater", "options": [{"text": "jacket"}, {"text": "sweater"}, {"text": "skirt"}, {"text": "shorts"}], "correct": [1]}, {"q": "Послушай слово и выбери его", "type": "single", "audio_tts": "jacket", "options": [{"text": "skirt"}, {"text": "shorts"}, {"text": "jacket"}, {"text": "baseball cap"}], "correct": [2]}, {"q": "Послушай слово и выбери его", "type": "single", "audio_tts": "skirt", "options": [{"text": "shorts"}, {"text": "baseball cap"}, {"text": "shoes"}, {"text": "skirt"}], "correct": [3]}, {"q": "Послушай слово и выбери его", "type": "single", "audio_tts": "shorts", "options": [{"text": "shorts"}, {"text": "baseball cap"}, {"text": "shoes"}, {"text": "socks"}], "correct": [0]}, {"q": "Послушай слово и выбери его", "type": "single", "audio_tts": "baseball cap", "options": [{"text": "shoes"}, {"text": "baseball cap"}, {"text": "socks"}, {"text": "T-shirt"}], "correct": [1]}, {"q": "Послушай слово и выбери его", "type": "single", "audio_tts": "shoes", "options": [{"text": "socks"}, {"text": "T-shirt"}, {"text": "shoes"}, {"text": "trousers"}], "correct": [2]}, {"q": "Послушай слово и выбери его", "type": "single", "audio_tts": "socks", "options": [{"text": "T-shirt"}, {"text": "trousers"}, {"text": "jeans"}, {"text": "socks"}], "correct": [3]}, {"q": "Послушай слово и выбери его", "type": "single", "audio_tts": "T-shirt", "options": [{"text": "T-shirt"}, {"text": "trousers"}, {"text": "jeans"}, {"text": "sweater"}], "correct": [0]}, {"q": "Послушай слово и выбери его", "type": "single", "audio_tts": "trousers", "options": [{"text": "jeans"}, {"text": "trousers"}, {"text": "sweater"}, {"text": "jacket"}], "correct": [1]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'match', replace($blk${"title": "Найди пару: соедини слово и перевод", "pairs": [{"left": "jeans", "left_audio_tts": "jeans", "right": "джинсы"}, {"left": "sweater", "left_audio_tts": "sweater", "right": "свитер"}, {"left": "jacket", "left_audio_tts": "jacket", "right": "пиджак, куртка"}, {"left": "skirt", "left_audio_tts": "skirt", "right": "юбка"}, {"left": "shorts", "left_audio_tts": "shorts", "right": "шорты"}, {"left": "baseball cap", "left_audio_tts": "baseball cap", "right": "бейсболка, кепка"}, {"left": "shoes", "left_audio_tts": "shoes", "right": "обувь"}, {"left": "socks", "left_audio_tts": "socks", "right": "носки"}, {"left": "T-shirt", "left_audio_tts": "T-shirt", "right": "футболка"}, {"left": "trousers", "left_audio_tts": "trousers", "right": "брюки"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_clap.webp\" alt=\"\" style=\"height:160px\"></p><h3>Отлично! Слова выучены 💪</h3><p>Добро пожаловать в дополнительную часть домашнего задания! Здесь тебя ждут интересные упражнения. Их можно выполнить по желанию.</p><p>НО если ты выполнишь их, то будешь большим молодцом!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'text', replace($blk${"html": "<p>Давай повторим всё, что выучили с тобой на уроке:</p><p><img src=\"@@MEDIA@@sm1/u7/vocab_clothes.webp\" alt=\"Vocabulary — Clothes\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'speaking', replace($blk${"title": "Нарисуй себя в любимой одежде 🎨🎤", "needs_review": true, "image": "@@MEDIA@@sm1/u7/kids_drawing_sample.webp", "html": "<p>Нарисуй себя в любимой одежде (не забудь раскрасить!) и покажи рисунок своему учителю на уроке.</p><p>Нажми на микрофон и перечисли, какую одежду ты нарисовал.</p><p><i>Пример: a blue T-shirt, blue shorts, green shoes.</i></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'match', replace($blk${"title": "Ты выполнил все задания из основной части! А это дополнительное задание — для настоящих чемпионов! Соедини слова с картинками:", "pairs": [{"left_image": "@@MEDIA@@sm1/u7/clothes_jeans.webp", "right": "jeans", "right_audio_tts": "jeans"}, {"left_image": "@@MEDIA@@sm1/u7/clothes_sweater.webp", "right": "sweater", "right_audio_tts": "sweater"}, {"left_image": "@@MEDIA@@sm1/u7/clothes_jacket.webp", "right": "jacket", "right_audio_tts": "jacket"}, {"left_image": "@@MEDIA@@sm1/u7/clothes_skirt.webp", "right": "skirt", "right_audio_tts": "skirt"}, {"left_image": "@@MEDIA@@sm1/u7/clothes_shorts.webp", "right": "shorts", "right_audio_tts": "shorts"}, {"left_image": "@@MEDIA@@sm1/u7/clothes_cap.webp", "right": "baseball cap", "right_audio_tts": "baseball cap"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'exact_input', replace($blk${"items": [{"image": "@@MEDIA@@sm1/u7/clothes_shoes.webp", "prompt": "Впиши слова: что на картинке?", "accept": ["shoes", "Shoes"], "audio_tts": "shoes"}, {"image": "@@MEDIA@@sm1/u7/clothes_socks.webp", "prompt": "Что на картинке?", "accept": ["socks", "Socks"], "audio_tts": "socks"}, {"image": "@@MEDIA@@sm1/u7/clothes_tshirt.webp", "prompt": "Что на картинке?", "accept": ["T-shirt", "t-shirt", "T shirt", "tshirt", "a T-shirt"], "audio_tts": "T-shirt"}, {"image": "@@MEDIA@@sm1/u7/clothes_trousers.webp", "prompt": "Что на картинке?", "accept": ["trousers", "Trousers"], "audio_tts": "trousers"}, {"image": "@@MEDIA@@sm1/u7/clothes_sweater.webp", "prompt": "Что на картинке?", "accept": ["sweater", "Sweater", "a sweater"], "audio_tts": "sweater"}, {"image": "@@MEDIA@@sm1/u7/clothes_jeans.webp", "prompt": "Что на картинке?", "accept": ["jeans", "Jeans"], "audio_tts": "jeans"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 9),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_star.webp\" alt=\"\" style=\"height:180px\"></p><h3>Поздравляю! Ты завершил домашнее задание, ты молодец!</h3><p>За это лови сердечко 💗</p><p>Увидимся на занятии!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 10);
end
$mig$;
