-- Super Minds 1 · Unit 7 · Get dressed · Homework 2
-- собрано tools/sm1_build.py --lesson u7_hw2
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where slug = 'sm1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 7 · Get dressed', 7
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 7 · Get dressed');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 7 · Get dressed';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 2', 'homework',
         60, false, 1
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 2');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 2';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет!</h2><p>В этом уроке тебя ждут несколько интересных заданий!</p><p>Выполни все упражнения, если хочешь выучить тему на все 100!</p><p>В конце тебя будет ждать дополнительное задание. Если ты его сделаешь, получишь звание ГРОССМЕЙСТЕРА английского 💪 (это очень крутое звание в шахматах ♟)</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'text', replace($blk${"html": "<p>Давай повторим всё, что выучили с тобой на уроке:</p><p><img src=\"@@MEDIA@@sm1/u7/grammar_this_these.webp\" alt=\"Do you like this / these?\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'text', replace($blk${"html": "<p>Мы начнём с видео, но прежде чем смотреть, как думаешь, какие предметы есть у главного героя?</p><p>Посмотри видео один раз, внимательно слушай, что говорит персонаж, и проверь себя — угадал ли ты?</p><p>Затем посмотри видео снова и повторяй за персонажами.</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'video', replace($blk${"title": "Видео 1: что есть у героя?", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'match', replace($blk${"title": "Сейчас посмотри видео ещё раз и соедини предложения и подходящие картинки!", "pairs": [{"left": "This is a flower.", "left_audio_tts": "This is a flower.", "right": "one flower", "right_image": "@@MEDIA@@sm1/u7/pic_flower.webp"}, {"left": "This is a rabbit.", "left_audio_tts": "This is a rabbit.", "right": "one rabbit", "right_image": "@@MEDIA@@sm1/u7/pic_rabbit.webp"}, {"left": "These are flowers.", "left_audio_tts": "These are flowers.", "right": "many flowers", "right_image": "@@MEDIA@@sm1/u7/pic_flowers.webp"}, {"left": "These are rabbits.", "left_audio_tts": "These are rabbits.", "right": "many rabbits", "right_image": "@@MEDIA@@sm1/u7/pic_rabbits.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'text', replace($blk${"html": "<p>Посмотри ещё одно видео. Но прежде чем смотреть, попробуй угадать, какую одежду ты в нём увидишь? A T-shirt? A cap? Shoes?</p><p>Теперь посмотри видео один раз, внимательно слушай, что говорят персонажи, и проверь себя — угадал ли ты?</p><p>Затем посмотри видео снова и повторяй за персонажами.</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'video', replace($blk${"title": "Видео 2: Do you like this cap?", "url": "", "provider": "file"}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'match', replace($blk${"title": "Сейчас посмотри видео ещё раз. Обрати внимание, какая одежда нравится герою видео, и соедини вопрос с правильным ответом.", "pairs": [{"left": "Do you like this cap?", "right": "Yes, I do.", "right_audio_tts": "Yes, I do."}, {"left": "Do you like these socks?", "right": "No, I don't.", "right_audio_tts": "No, I don't."}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'quiz', replace($blk${"title": "Теперь пришло время практики. Выбери правильный вариант ответа.", "questions": [{"q": "Теперь пришло время практики! Выбери правильное слово.<br>Do you like ___ T-shirt?", "type": "single", "image": "@@MEDIA@@sm1/u7/clothes_tshirt.webp", "options": [{"text": "this"}, {"text": "these"}], "correct": [0]}, {"q": "Do you like ___ jeans?", "type": "single", "image": "@@MEDIA@@sm1/u7/clothes_jeans.webp", "options": [{"text": "this"}, {"text": "these"}], "correct": [1]}, {"q": "Do you like ___ jacket?", "type": "single", "image": "@@MEDIA@@sm1/u7/clothes_jacket.webp", "options": [{"text": "this"}, {"text": "these"}], "correct": [0]}, {"q": "Do you like ___ shoes?", "type": "single", "image": "@@MEDIA@@sm1/u7/clothes_shoes.webp", "options": [{"text": "this"}, {"text": "these"}], "correct": [1]}, {"q": "Do you like ___ socks?", "type": "single", "image": "@@MEDIA@@sm1/u7/clothes_socks.webp", "options": [{"text": "this"}, {"text": "these"}], "correct": [1]}, {"q": "Do you like ___ skirt?", "type": "single", "image": "@@MEDIA@@sm1/u7/clothes_skirt.webp", "options": [{"text": "this"}, {"text": "these"}], "correct": [0]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_smiley.webp\" alt=\"\" style=\"height:160px\"></p><p>Отлично! Ты справился с половиной заданий. Ты — молодец.</p><p>Внизу тебя ждут несколько вопросов, на которые нужно выбрать правильный ответ. Возле каждого вопроса тебя ждёт смайлик-подсказка.</p><p>Ты справишься, я в тебя верю!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 9),
    (v_lesson, 'quiz', replace($blk${"title": "Выбери правильный вариант ответа.", "questions": [{"q": "Выбери правильный вариант ответа.<br>Do you like this skirt? 👍", "type": "single", "image": "@@MEDIA@@sm1/u7/clothes_skirt.webp", "options": [{"text": "Yes, I do."}, {"text": "Yes, I don't."}, {"text": "No, I do."}], "correct": [0]}, {"q": "Do you like these trousers? 👎", "type": "single", "image": "@@MEDIA@@sm1/u7/clothes_trousers.webp", "options": [{"text": "Yes, I don't."}, {"text": "No, I do."}, {"text": "No, I don't."}], "correct": [2]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 10),
    (v_lesson, 'text', replace($blk${"html": "<p>А теперь давай расставим слова в правильном порядке, чтобы получились предложения.</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 11),
    (v_lesson, 'order', replace($blk${"image": "@@MEDIA@@sm1/u7/clothes_jacket.webp", "words": ["Do", "you", "like", "this", "jacket?"], "sentence": "Do you like this jacket?", "audio_tts": "Do you like this jacket?"}$blk$, '@@MEDIA@@', v_media)::jsonb, 12),
    (v_lesson, 'order', replace($blk${"image": "@@MEDIA@@sm1/u7/clothes_jeans.webp", "words": ["Do", "you", "like", "these", "jeans?"], "sentence": "Do you like these jeans?", "audio_tts": "Do you like these jeans?"}$blk$, '@@MEDIA@@', v_media)::jsonb, 13),
    (v_lesson, 'order', replace($blk${"image": "@@MEDIA@@sm1/u7/clothes_shoes.webp", "words": ["Do", "you", "like", "these", "shoes?"], "sentence": "Do you like these shoes?", "audio_tts": "Do you like these shoes?"}$blk$, '@@MEDIA@@', v_media)::jsonb, 14),
    (v_lesson, 'order', replace($blk${"image": "@@MEDIA@@sm1/u7/clothes_cap.webp", "words": ["Do", "you", "like", "this", "cap?"], "sentence": "Do you like this cap?", "audio_tts": "Do you like this cap?"}$blk$, '@@MEDIA@@', v_media)::jsonb, 15),
    (v_lesson, 'speaking', replace($blk${"title": "Расскажи, какая одежда тебе нравится 🎤", "needs_review": true, "image": "@@MEDIA@@sm1/u7/clothes_set_speaking.webp", "sample": "", "sample_tts": "I like this T-shirt. I like these jeans. I don't like this skirt.", "html": "<p>Посмотри на картинку: на ней разные предметы одежды. Расскажи, какая одежда тебе нравится, — запиши голосом.</p><p>Сначала послушай образец ответа.</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 16),
    (v_lesson, 'quiz', replace($blk${"title": "Дополнительное задание — выбери правильный вариант", "questions": [{"q": "Ты выполнил все задания из основной части! А это дополнительное задание — для настоящих чемпионов! Посмотри на смайлик и выбери ответ.<br>Do you like this sweater? 👍", "type": "single", "image": "@@MEDIA@@sm1/u7/clothes_sweater.webp", "options": [{"text": "No, I don't."}, {"text": "Yes, I do."}], "correct": [1]}, {"q": "Do you like these shorts? 👎", "type": "single", "image": "@@MEDIA@@sm1/u7/clothes_shorts.webp", "options": [{"text": "No, I don't."}, {"text": "Yes, I do."}], "correct": [0]}, {"q": "Do you like this T-shirt? 👍", "type": "single", "image": "@@MEDIA@@sm1/u7/clothes_tshirt.webp", "options": [{"text": "No, I don't."}, {"text": "Yes, I do."}], "correct": [1]}, {"q": "Do you like these socks? 👎", "type": "single", "image": "@@MEDIA@@sm1/u7/clothes_socks.webp", "options": [{"text": "Yes, I do."}, {"text": "No, I don't."}], "correct": [1]}, {"q": "Do you like this cap? 👍", "type": "single", "image": "@@MEDIA@@sm1/u7/clothes_cap.webp", "options": [{"text": "Yes, I do."}, {"text": "No, I don't."}], "correct": [0]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 17),
    (v_lesson, 'sort', replace($blk${"title": "Перенеси вещи в подходящие столбики: одна вещь — this, пара или много — these", "groups": [{"name": "this", "items": [{"text": "cap", "image": "@@MEDIA@@sm1/u7/clothes_cap.webp"}, {"text": "skirt", "image": "@@MEDIA@@sm1/u7/clothes_skirt.webp"}, {"text": "jacket", "image": "@@MEDIA@@sm1/u7/clothes_jacket.webp"}, {"text": "T-shirt", "image": "@@MEDIA@@sm1/u7/clothes_tshirt.webp"}, {"text": "sweater", "image": "@@MEDIA@@sm1/u7/clothes_sweater.webp"}]}, {"name": "these", "items": [{"text": "jeans", "image": "@@MEDIA@@sm1/u7/clothes_jeans.webp"}, {"text": "trousers", "image": "@@MEDIA@@sm1/u7/clothes_trousers.webp"}, {"text": "shoes", "image": "@@MEDIA@@sm1/u7/clothes_shoes.webp"}, {"text": "socks", "image": "@@MEDIA@@sm1/u7/clothes_socks.webp"}, {"text": "shorts", "image": "@@MEDIA@@sm1/u7/clothes_shorts.webp"}]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 18),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_trophy.webp\" alt=\"\" style=\"height:180px\"></p><h3>Поздравляю! Ты завершил домашнее задание, ты молодец!</h3><p>Увидимся на занятии!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 19);
end
$mig$;
