-- Super Minds 1 · Unit 4 · Food · Unit 4 Test
-- собрано tools/sm1_build.py --lesson u4_test
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where slug = 'sm1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 4 · Food', 4
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 4 · Food');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 4 · Food';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Unit 4 Test', 'test',
         90, false, 7
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Unit 4 Test');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Unit 4 Test';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'exact_input', replace($blk${"items": [{"prompt": "Напиши по-английски: банан", "accept": ["banana", "Banana"], "audio_tts": "banana"}, {"prompt": "Напиши по-английски: торт", "accept": ["cake", "Cake"], "audio_tts": "cake"}, {"prompt": "Напиши по-английски: бутерброд", "accept": ["sandwich", "Sandwich"], "audio_tts": "sandwich"}, {"prompt": "Напиши по-английски: яблоко", "accept": ["apple", "Apple"], "audio_tts": "apple"}, {"prompt": "Напиши по-английски: пицца", "accept": ["pizza", "Pizza"], "audio_tts": "pizza"}, {"prompt": "Напиши по-английски: сосиска", "accept": ["sausage", "Sausage"], "audio_tts": "sausage"}, {"prompt": "Напиши по-английски: курица", "accept": ["chicken", "Chicken"], "audio_tts": "chicken"}, {"prompt": "Напиши по-английски: стейк", "accept": ["steak", "Steak"], "audio_tts": "steak"}, {"prompt": "Напиши по-английски: горох", "accept": ["peas", "Peas"], "audio_tts": "peas"}, {"prompt": "Напиши по-английски: морковь", "accept": ["carrots", "Carrots"], "audio_tts": "carrots"}, {"prompt": "Напиши по-английски: рыба", "accept": ["fish", "Fish"], "audio_tts": "fish"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'match', replace($blk${"title": "Соедини слова с картинками:", "pairs": [{"left": "chicken", "left_audio_tts": "chicken", "right": "картинка chicken", "right_image": "@@MEDIA@@sm1/u4/food_chicken.webp"}, {"left": "cheese sandwich", "left_audio_tts": "cheese sandwich", "right": "картинка cheese sandwich", "right_image": "@@MEDIA@@sm1/u4/food_cheese_sandwich.webp"}, {"left": "cake", "left_audio_tts": "cake", "right": "картинка cake", "right_image": "@@MEDIA@@sm1/u4/food_cake.webp"}, {"left": "sausage", "left_audio_tts": "sausage", "right": "картинка sausage", "right_image": "@@MEDIA@@sm1/u4/food_sausage.webp"}, {"left": "banana", "left_audio_tts": "banana", "right": "картинка banana", "right_image": "@@MEDIA@@sm1/u4/food_banana.webp"}, {"left": "steak", "left_audio_tts": "steak", "right": "картинка steak", "right_image": "@@MEDIA@@sm1/u4/food_steak.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'speaking', replace($blk${"title": "Прочитай вслух 🎤", "needs_review": true, "html": "<p>Внимательно прочитай предложения глазками 👀</p><p>Нажми на микрофон 🎤 и проговори их вслух.</p><ol><li>Look at the photo of the turtle.</li><li>The crow sits on a rope.</li><li>Chew the cute little cube.</li><li>I draw a big cloud.</li><li>The giraffe is very tall.</li></ol><p>У тебя получится! 🌟</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'quiz', replace($blk${"title": "Заполни пропуски — выбери подходящий вариант", "questions": [{"q": "Заполни пропуски — выбери подходящий вариант.<br>A: Have we ___ any pizza?<br>B: Yes, we have.", "type": "single", "options": [{"text": "have"}, {"text": "got"}, {"text": "have got"}], "correct": [1], "image": "@@MEDIA@@sm1/u4/food_pizza.webp"}, {"q": "A: Have we got any pizza?<br>B: Yes, we ___.", "type": "single", "options": [{"text": "got"}, {"text": "haven't got"}, {"text": "have"}], "correct": [2], "image": "@@MEDIA@@sm1/u4/food_pizza.webp"}, {"q": "We ___ any steak.", "type": "single", "options": [{"text": "haven't got"}, {"text": "don't got"}, {"text": "haven't"}], "correct": [0], "image": "@@MEDIA@@sm1/u4/food_steak.webp"}, {"q": "A: What ___ you got?<br>B: I've got an apple and a banana.", "type": "single", "options": [{"text": "has"}, {"text": "have"}, {"text": "got"}], "correct": [1], "image": "@@MEDIA@@sm1/u4/food_apple_banana.webp"}, {"q": "A: What have you got?<br>B: I've ___ an apple and a banana.", "type": "single", "options": [{"text": "have"}, {"text": "have got"}, {"text": "got"}], "correct": [2], "image": "@@MEDIA@@sm1/u4/food_apple_banana.webp"}, {"q": "A: ___ we got any milk?<br>B: No, we haven't.", "type": "single", "options": [{"text": "Has"}, {"text": "Got"}, {"text": "Have"}], "correct": [2], "image": "@@MEDIA@@sm1/u4/food_milk.webp"}, {"q": "A: Have we got any milk?<br>B: No, we ___.", "type": "single", "options": [{"text": "haven't"}, {"text": "have"}, {"text": "don't"}], "correct": [0], "image": "@@MEDIA@@sm1/u4/food_milk.webp"}, {"q": "A: What ___ you got in your lunch box?<br>B: I have got peas and carrots.", "type": "single", "options": [{"text": "got"}, {"text": "have"}, {"text": "do"}], "correct": [1], "image": "@@MEDIA@@sm1/u4/food_peas_carrots.webp"}, {"q": "A: What have you got in your lunch box?<br>B: I ___ peas and carrots.", "type": "single", "options": [{"text": "'ve"}, {"text": "got"}, {"text": "have got"}], "correct": [2], "image": "@@MEDIA@@sm1/u4/food_peas_carrots.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'order', replace($blk${"image": "@@MEDIA@@sm1/u4/food_cake.webp", "words": ["Have", "we", "got", "any", "cake?"], "sentence": "Have we got any cake?", "audio_tts": "Have we got any cake?"}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'order', replace($blk${"image": "@@MEDIA@@sm1/u4/food_chicken_carrots.webp", "words": ["I've", "got", "chicken", "and", "carrots."], "sentence": "I've got chicken and carrots.", "audio_tts": "I've got chicken and carrots."}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'order', replace($blk${"image": "@@MEDIA@@sm1/u4/food_pizza.webp", "words": ["Have", "we", "got", "any", "pizza?"], "sentence": "Have we got any pizza?", "audio_tts": "Have we got any pizza?"}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'order', replace($blk${"image": "@@MEDIA@@sm1/u4/food_orange_juice.webp", "words": ["I", "haven't", "got", "orange", "juice."], "sentence": "I haven't got orange juice.", "audio_tts": "I haven't got orange juice."}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'order', replace($blk${"image": "@@MEDIA@@sm1/u4/food_ice_cream.webp", "words": ["Have", "you", "got", "any", "ice", "cream?"], "sentence": "Have you got any ice cream?", "audio_tts": "Have you got any ice cream?"}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'truefalse', replace($blk${"title": "READING. Прочитай текст. Прочитай предложения и выбери Верно или Неверно. — Hi! My name is Ben. Look at my lunch box! I've got a cheese sandwich and an apple. I've got some carrots too. Yummy! But I haven't got a banana. And I haven't got any cake. Oh no!", "statements": [{"text": "Ben has got a cheese sandwich.", "correct": true}, {"text": "Ben has got a banana.", "correct": false}, {"text": "Ben has got an apple.", "correct": true}, {"text": "Ben has got a cake.", "correct": false}, {"text": "Ben has got some carrots.", "correct": true}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 9),
    (v_lesson, 'quiz', replace($blk${"title": "LISTENING. Послушай запись. Выбери правильный ответ.", "questions": [{"q": "LISTENING. Послушай запись. Выбери правильный ответ.<br>1. Have they got any bananas?", "type": "single", "options": [{"text": "Yes, they have."}, {"text": "No, they haven't."}], "correct": [1], "audio": ""}, {"q": "2. What has Sam got?", "type": "single", "options": [{"text": "a steak"}, {"text": "a cake"}, {"text": "pizza"}], "correct": [1]}, {"q": "3. Have they got any peas?", "type": "single", "options": [{"text": "Yes, they have."}, {"text": "No, they haven't."}], "correct": [0]}, {"q": "4. What hasn't Lisa got?", "type": "single", "options": [{"text": "carrots"}, {"text": "an apple"}, {"text": "a chicken"}], "correct": [2]}, {"q": "5. Have they got any cheese?", "type": "single", "options": [{"text": "No, they haven't."}, {"text": "Yes, they have."}], "correct": [1]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 10),
    (v_lesson, 'speaking', replace($blk${"title": "SPEAKING TASK 🎤", "needs_review": true, "image": "@@MEDIA@@sm1/u4/fridge.webp", "html": "<p>Посмотри на картинку. Представь, что это твой холодильник. Расскажи, что у тебя есть и чего нет.</p><p><i>For example:<br>I’ve got cheese.<br>I’ve got steak.<br>I haven’t got pizza.</i></p><p>Запиши свой ответ, нажав на кнопку микрофона 🙌</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 11);
end
$mig$;
