-- Super Minds 1 · Unit 9 · Holidays · Homework 1
-- собрано tools/sm1_build.py --lesson u9_hw1
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where slug = 'sm1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 9 · Holidays', 9
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 9 · Holidays');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 9 · Holidays';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 1', 'homework',
         60, false, 0
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 1');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 1';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Добро пожаловать в домашнее задание!</h2><p>Я не знаю человека, который бы не любил море! 🌊</p><p>Сегодня мы с тобой выучим различные занятия, которыми можно заниматься на море. В этом уроке тебя ждут задания на отработку новых слов! Выполни все, если хочешь выучить тему на все 100!</p><p>После того как завершишь все задания, тебя ждёт дополнительное задание — его можно выполнить по желанию, НО если ты выполнишь его, то будешь нереально крут!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"title": "Запомни слова. Нажми на карточку, чтобы увидеть перевод", "cards": [{"text": "catch a fish", "translation": "поймать рыбу", "audio_tts": "catch a fish", "image": "@@MEDIA@@sm1/u9/act_catch_fish.webp"}, {"text": "paint a picture", "translation": "рисовать картину", "audio_tts": "paint a picture", "image": "@@MEDIA@@sm1/u9/act_paint_picture.webp"}, {"text": "eat ice cream", "translation": "есть мороженое", "audio_tts": "eat ice cream", "image": "@@MEDIA@@sm1/u9/act_eat_ice_cream.webp"}, {"text": "take a photo", "translation": "фотографировать", "audio_tts": "take a photo", "image": "@@MEDIA@@sm1/u9/act_take_photo.webp"}, {"text": "listen to music", "translation": "слушать музыку", "audio_tts": "listen to music", "image": "@@MEDIA@@sm1/u9/act_listen_music.webp"}, {"text": "look for shells", "translation": "искать ракушки", "audio_tts": "look for shells", "image": "@@MEDIA@@sm1/u9/act_look_shells.webp"}, {"text": "read a book", "translation": "читать книгу", "audio_tts": "read a book", "image": "@@MEDIA@@sm1/u9/act_read_book.webp"}, {"text": "make a sandcastle", "translation": "строить замок из песка", "audio_tts": "make a sandcastle", "image": "@@MEDIA@@sm1/u9/act_make_sandcastle.webp"}, {"text": "play the guitar", "translation": "играть на гитаре", "audio_tts": "play the guitar", "image": "@@MEDIA@@sm1/u9/act_play_guitar.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «поймать рыбу»?", "type": "single", "options": [{"text": "catch a fish"}, {"text": "eat ice cream"}, {"text": "paint a picture"}, {"text": "take a photo"}], "correct": [0]}, {"q": "Как по-английски «рисовать картину»?", "type": "single", "options": [{"text": "eat ice cream"}, {"text": "listen to music"}, {"text": "paint a picture"}, {"text": "take a photo"}], "correct": [2]}, {"q": "Как по-английски «есть мороженое»?", "type": "single", "options": [{"text": "eat ice cream"}, {"text": "listen to music"}, {"text": "look for shells"}, {"text": "take a photo"}], "correct": [0]}, {"q": "Как по-английски «фотографировать»?", "type": "single", "options": [{"text": "listen to music"}, {"text": "look for shells"}, {"text": "read a book"}, {"text": "take a photo"}], "correct": [3]}, {"q": "Как по-английски «слушать музыку»?", "type": "single", "options": [{"text": "listen to music"}, {"text": "look for shells"}, {"text": "make a sandcastle"}, {"text": "read a book"}], "correct": [0]}, {"q": "Как по-английски «искать ракушки»?", "type": "single", "options": [{"text": "look for shells"}, {"text": "make a sandcastle"}, {"text": "play the guitar"}, {"text": "read a book"}], "correct": [0]}, {"q": "Как по-английски «читать книгу»?", "type": "single", "options": [{"text": "catch a fish"}, {"text": "make a sandcastle"}, {"text": "play the guitar"}, {"text": "read a book"}], "correct": [3]}, {"q": "Как по-английски «строить замок из песка»?", "type": "single", "options": [{"text": "catch a fish"}, {"text": "make a sandcastle"}, {"text": "paint a picture"}, {"text": "play the guitar"}], "correct": [1]}, {"q": "Как по-английски «играть на гитаре»?", "type": "single", "options": [{"text": "catch a fish"}, {"text": "eat ice cream"}, {"text": "paint a picture"}, {"text": "play the guitar"}], "correct": [3]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Послушай и выбери, что прозвучало", "type": "single", "audio_tts": "catch a fish", "options": [{"text": "catch a fish"}, {"text": "paint a picture"}, {"text": "eat ice cream"}, {"text": "take a photo"}], "correct": [0]}, {"q": "Послушай и выбери, что прозвучало", "type": "single", "audio_tts": "paint a picture", "options": [{"text": "eat ice cream"}, {"text": "paint a picture"}, {"text": "take a photo"}, {"text": "listen to music"}], "correct": [1]}, {"q": "Послушай и выбери, что прозвучало", "type": "single", "audio_tts": "eat ice cream", "options": [{"text": "take a photo"}, {"text": "listen to music"}, {"text": "eat ice cream"}, {"text": "look for shells"}], "correct": [2]}, {"q": "Послушай и выбери, что прозвучало", "type": "single", "audio_tts": "take a photo", "options": [{"text": "listen to music"}, {"text": "look for shells"}, {"text": "read a book"}, {"text": "take a photo"}], "correct": [3]}, {"q": "Послушай и выбери, что прозвучало", "type": "single", "audio_tts": "listen to music", "options": [{"text": "listen to music"}, {"text": "look for shells"}, {"text": "read a book"}, {"text": "make a sandcastle"}], "correct": [0]}, {"q": "Послушай и выбери, что прозвучало", "type": "single", "audio_tts": "look for shells", "options": [{"text": "read a book"}, {"text": "look for shells"}, {"text": "make a sandcastle"}, {"text": "play the guitar"}], "correct": [1]}, {"q": "Послушай и выбери, что прозвучало", "type": "single", "audio_tts": "read a book", "options": [{"text": "make a sandcastle"}, {"text": "play the guitar"}, {"text": "read a book"}, {"text": "catch a fish"}], "correct": [2]}, {"q": "Послушай и выбери, что прозвучало", "type": "single", "audio_tts": "make a sandcastle", "options": [{"text": "play the guitar"}, {"text": "catch a fish"}, {"text": "paint a picture"}, {"text": "make a sandcastle"}], "correct": [3]}, {"q": "Послушай и выбери, что прозвучало", "type": "single", "audio_tts": "play the guitar", "options": [{"text": "play the guitar"}, {"text": "catch a fish"}, {"text": "paint a picture"}, {"text": "eat ice cream"}], "correct": [0]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'match', replace($blk${"title": "Найди пару: соедини картинку и слова", "pairs": [{"left_image": "@@MEDIA@@sm1/u9/act_catch_fish.webp", "right": "catch a fish", "right_audio_tts": "catch a fish"}, {"left_image": "@@MEDIA@@sm1/u9/act_paint_picture.webp", "right": "paint a picture", "right_audio_tts": "paint a picture"}, {"left_image": "@@MEDIA@@sm1/u9/act_eat_ice_cream.webp", "right": "eat ice cream", "right_audio_tts": "eat ice cream"}, {"left_image": "@@MEDIA@@sm1/u9/act_take_photo.webp", "right": "take a photo", "right_audio_tts": "take a photo"}, {"left_image": "@@MEDIA@@sm1/u9/act_listen_music.webp", "right": "listen to music", "right_audio_tts": "listen to music"}, {"left_image": "@@MEDIA@@sm1/u9/act_look_shells.webp", "right": "look for shells", "right_audio_tts": "look for shells"}, {"left_image": "@@MEDIA@@sm1/u9/act_read_book.webp", "right": "read a book", "right_audio_tts": "read a book"}, {"left_image": "@@MEDIA@@sm1/u9/act_make_sandcastle.webp", "right": "make a sandcastle", "right_audio_tts": "make a sandcastle"}, {"left_image": "@@MEDIA@@sm1/u9/act_play_guitar.webp", "right": "play the guitar", "right_audio_tts": "play the guitar"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'exact_input', replace($blk${"items": [{"prompt": "Собери слова из букв: cacth a hifs (поймать рыбу)", "accept": ["catch a fish"], "audio_tts": "catch a fish"}, {"prompt": "Собери слова из букв: napit a rtipcue (рисовать картину)", "accept": ["paint a picture"], "audio_tts": "paint a picture"}, {"prompt": "Собери слова из букв: aet cie arcem (есть мороженое)", "accept": ["eat ice cream"], "audio_tts": "eat ice cream"}, {"prompt": "Собери слова из букв: eatk a thpoo (фотографировать)", "accept": ["take a photo"], "audio_tts": "take a photo"}, {"prompt": "Собери слова из букв: ntilse ot iumsc (слушать музыку)", "accept": ["listen to music"], "audio_tts": "listen to music"}, {"prompt": "Собери слова из букв: kolo ofr slhsel (искать ракушки)", "accept": ["look for shells"], "audio_tts": "look for shells"}, {"prompt": "Собери слова из букв: dera a kobo (читать книгу)", "accept": ["read a book"], "audio_tts": "read a book"}, {"prompt": "Собери слова из букв: eamk a etadasncsl (строить замок из песка)", "accept": ["make a sandcastle"], "audio_tts": "make a sandcastle"}, {"prompt": "Собери слова из букв: ylpa hte rtugia (играть на гитаре)", "accept": ["play the guitar"], "audio_tts": "play the guitar"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'exact_input', replace($blk${"items": [{"prompt": "Впиши пропущенные буквы: c_t_h a f_s_ (поймать рыбу)", "accept": ["catch a fish"], "image": "@@MEDIA@@sm1/u9/act_catch_fish.webp", "audio_tts": "catch a fish"}, {"prompt": "Впиши пропущенные буквы: p_i_t a p_c_u_e (рисовать картину)", "accept": ["paint a picture"], "image": "@@MEDIA@@sm1/u9/act_paint_picture.webp", "audio_tts": "paint a picture"}, {"prompt": "Впиши пропущенные буквы: e_t i_e c_e_m (есть мороженое)", "accept": ["eat ice cream"], "image": "@@MEDIA@@sm1/u9/act_eat_ice_cream.webp", "audio_tts": "eat ice cream"}, {"prompt": "Впиши пропущенные буквы: t_k_ a p_o_o (фотографировать)", "accept": ["take a photo"], "image": "@@MEDIA@@sm1/u9/act_take_photo.webp", "audio_tts": "take a photo"}, {"prompt": "Впиши пропущенные буквы: l_s_e_ t_ m_s_c (слушать музыку)", "accept": ["listen to music"], "image": "@@MEDIA@@sm1/u9/act_listen_music.webp", "audio_tts": "listen to music"}, {"prompt": "Впиши пропущенные буквы: l_o_ f_r s_e_l_ (искать ракушки)", "accept": ["look for shells"], "image": "@@MEDIA@@sm1/u9/act_look_shells.webp", "audio_tts": "look for shells"}, {"prompt": "Впиши пропущенные буквы: r_a_ a b_o_ (читать книгу)", "accept": ["read a book"], "image": "@@MEDIA@@sm1/u9/act_read_book.webp", "audio_tts": "read a book"}, {"prompt": "Впиши пропущенные буквы: m_k_ a s_n_c_s_l_ (строить замок из песка)", "accept": ["make a sandcastle"], "image": "@@MEDIA@@sm1/u9/act_make_sandcastle.webp", "audio_tts": "make a sandcastle"}, {"prompt": "Впиши пропущенные буквы: p_a_ t_e g_i_a_ (играть на гитаре)", "accept": ["play the guitar"], "image": "@@MEDIA@@sm1/u9/act_play_guitar.webp", "audio_tts": "play the guitar"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'text', replace($blk${"html": "<h3>Привет! 👋</h3><p>Добро пожаловать во вторую, ДОПОЛНИТЕЛЬНУЮ часть домашнего задания.</p><p>Выполни задание, чтобы хорошенько запомнить новые слова! Выполнив его, ты станешь МЕГА крутым учеником!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'task', replace($blk${"title": "Дополнительное задание ⭐ Мой отдых на море", "needs_review": true, "image": "@@MEDIA@@sm1/u9/hw1_drawing_example.webp", "html": "<p>Это ДОПОЛНИТЕЛЬНОЕ ЗАДАНИЕ — для самых смелых!</p><p><b>Нарисуй свой отдых на море</b> и пришли рисунок сюда. А на уроке устно расскажи учителю, чем ты больше всего любишь заниматься на каникулах.</p><p>Уверена, что твой рисунок будет очень красивым. Удачи 💗</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_star.webp\" alt=\"\" style=\"height:180px\"></p><h3>Поздравляю! Ты завершил домашнее задание. Ты — МЕГА КРУТ! 🌟</h3><p>Жду тебя на уроке!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 9);
end
$mig$;
