-- Super Minds 1 · Unit 9 · Holidays · Homework 6
-- собрано tools/sm1_build.py --lesson u9_hw6
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where slug = 'sm1';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 9 · Holidays', 9
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 9 · Holidays');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 9 · Holidays';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 6', 'homework',
         60, false, 5
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 6');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 6';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_highfive.webp\" alt=\"\" style=\"height:200px\"></p><h2>Добро пожаловать в домашнее задание!</h2><p>Сегодня мы выучим, как по-английски называются места, куда можно поехать на каникулы: горы, пляж, озеро, город…</p><p>Выполни все задания, если хочешь выучить тему на все 100!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"title": "Запомни слова. Нажми на карточку, чтобы увидеть перевод", "cards": [{"text": "mountains", "translation": "горы", "audio_tts": "mountains", "image": "@@MEDIA@@sm1/u9/place_mountains.webp"}, {"text": "countryside", "translation": "сельская местность", "audio_tts": "countryside", "image": "@@MEDIA@@sm1/u9/place_countryside.webp"}, {"text": "beach", "translation": "пляж", "audio_tts": "beach", "image": "@@MEDIA@@sm1/u9/place_beach.webp"}, {"text": "city", "translation": "город", "audio_tts": "city", "image": "@@MEDIA@@sm1/u9/place_city.webp"}, {"text": "theme park", "translation": "парк развлечений", "audio_tts": "theme park", "image": "@@MEDIA@@sm1/u9/place_theme_park.webp"}, {"text": "campsite", "translation": "кемпинг", "audio_tts": "campsite", "image": "@@MEDIA@@sm1/u9/place_campsite.webp"}, {"text": "lake", "translation": "озеро", "audio_tts": "lake", "image": "@@MEDIA@@sm1/u9/place_lake.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «горы»?", "type": "single", "options": [{"text": "beach"}, {"text": "city"}, {"text": "countryside"}, {"text": "mountains"}], "correct": [3]}, {"q": "Как по-английски «сельская местность»?", "type": "single", "options": [{"text": "beach"}, {"text": "city"}, {"text": "countryside"}, {"text": "theme park"}], "correct": [2]}, {"q": "Как по-английски «пляж»?", "type": "single", "options": [{"text": "beach"}, {"text": "campsite"}, {"text": "city"}, {"text": "theme park"}], "correct": [0]}, {"q": "Как по-английски «город»?", "type": "single", "options": [{"text": "campsite"}, {"text": "city"}, {"text": "lake"}, {"text": "theme park"}], "correct": [1]}, {"q": "Как по-английски «парк развлечений»?", "type": "single", "options": [{"text": "campsite"}, {"text": "lake"}, {"text": "mountains"}, {"text": "theme park"}], "correct": [3]}, {"q": "Как по-английски «кемпинг»?", "type": "single", "options": [{"text": "campsite"}, {"text": "countryside"}, {"text": "lake"}, {"text": "mountains"}], "correct": [0]}, {"q": "Как по-английски «озеро»?", "type": "single", "options": [{"text": "beach"}, {"text": "countryside"}, {"text": "lake"}, {"text": "mountains"}], "correct": [2]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Что значит <b>mountains</b>?", "type": "single", "audio_tts": "mountains", "image": "@@MEDIA@@sm1/u9/place_mountains.webp", "options": [{"text": "сельская местность"}, {"text": "пляж"}, {"text": "горы"}, {"text": "город"}], "correct": [2]}, {"q": "Что значит <b>countryside</b>?", "type": "single", "audio_tts": "countryside", "image": "@@MEDIA@@sm1/u9/place_countryside.webp", "options": [{"text": "пляж"}, {"text": "город"}, {"text": "парк развлечений"}, {"text": "сельская местность"}], "correct": [3]}, {"q": "Что значит <b>beach</b>?", "type": "single", "audio_tts": "beach", "image": "@@MEDIA@@sm1/u9/place_beach.webp", "options": [{"text": "пляж"}, {"text": "город"}, {"text": "парк развлечений"}, {"text": "кемпинг"}], "correct": [0]}, {"q": "Что значит <b>city</b>?", "type": "single", "audio_tts": "city", "image": "@@MEDIA@@sm1/u9/place_city.webp", "options": [{"text": "парк развлечений"}, {"text": "город"}, {"text": "кемпинг"}, {"text": "озеро"}], "correct": [1]}, {"q": "Что значит <b>theme park</b>?", "type": "single", "audio_tts": "theme park", "image": "@@MEDIA@@sm1/u9/place_theme_park.webp", "options": [{"text": "кемпинг"}, {"text": "озеро"}, {"text": "парк развлечений"}, {"text": "горы"}], "correct": [2]}, {"q": "Что значит <b>campsite</b>?", "type": "single", "audio_tts": "campsite", "image": "@@MEDIA@@sm1/u9/place_campsite.webp", "options": [{"text": "озеро"}, {"text": "горы"}, {"text": "сельская местность"}, {"text": "кемпинг"}], "correct": [3]}, {"q": "Что значит <b>lake</b>?", "type": "single", "audio_tts": "lake", "image": "@@MEDIA@@sm1/u9/place_lake.webp", "options": [{"text": "озеро"}, {"text": "горы"}, {"text": "сельская местность"}, {"text": "пляж"}], "correct": [0]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Послушай и выбери, что прозвучало", "type": "single", "audio_tts": "mountains", "options": [{"text": "mountains"}, {"text": "countryside"}, {"text": "beach"}, {"text": "city"}], "correct": [0]}, {"q": "Послушай и выбери, что прозвучало", "type": "single", "audio_tts": "countryside", "options": [{"text": "beach"}, {"text": "countryside"}, {"text": "city"}, {"text": "theme park"}], "correct": [1]}, {"q": "Послушай и выбери, что прозвучало", "type": "single", "audio_tts": "beach", "options": [{"text": "city"}, {"text": "theme park"}, {"text": "beach"}, {"text": "campsite"}], "correct": [2]}, {"q": "Послушай и выбери, что прозвучало", "type": "single", "audio_tts": "city", "options": [{"text": "theme park"}, {"text": "campsite"}, {"text": "lake"}, {"text": "city"}], "correct": [3]}, {"q": "Послушай и выбери, что прозвучало", "type": "single", "audio_tts": "theme park", "options": [{"text": "theme park"}, {"text": "campsite"}, {"text": "lake"}, {"text": "mountains"}], "correct": [0]}, {"q": "Послушай и выбери, что прозвучало", "type": "single", "audio_tts": "campsite", "options": [{"text": "lake"}, {"text": "campsite"}, {"text": "mountains"}, {"text": "countryside"}], "correct": [1]}, {"q": "Послушай и выбери, что прозвучало", "type": "single", "audio_tts": "lake", "options": [{"text": "mountains"}, {"text": "countryside"}, {"text": "lake"}, {"text": "beach"}], "correct": [2]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'text', replace($blk${"html": "<h3>Отлично! Переходим ко второй части 🙌</h3><p>Уверена, что ты хорошо выучил новые слова и готов к следующему этапу!</p><p>Тебя ждут увлекательные упражнения. А ещё тебя ждёт ДОПОЛНИТЕЛЬНОЕ задание, которое ты можешь выполнить по желанию, НО если ты его сделаешь, то будешь нереально крут!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'match', replace($blk${"title": "Посмотри на картинки и слова. Соедини пейзажи с их названиями:", "pairs": [{"left_image": "@@MEDIA@@sm1/u9/place_mountains.webp", "right": "mountains", "right_audio_tts": "mountains"}, {"left_image": "@@MEDIA@@sm1/u9/place_countryside.webp", "right": "countryside", "right_audio_tts": "countryside"}, {"left_image": "@@MEDIA@@sm1/u9/place_beach.webp", "right": "beach", "right_audio_tts": "beach"}, {"left_image": "@@MEDIA@@sm1/u9/place_city.webp", "right": "city", "right_audio_tts": "city"}, {"left_image": "@@MEDIA@@sm1/u9/place_theme_park.webp", "right": "theme park", "right_audio_tts": "theme park"}, {"left_image": "@@MEDIA@@sm1/u9/place_campsite.webp", "right": "campsite", "right_audio_tts": "campsite"}, {"left_image": "@@MEDIA@@sm1/u9/place_lake.webp", "right": "lake", "right_audio_tts": "lake"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'match', replace($blk${"title": "А теперь давай вспомним, чем мы можем заняться в каждом из этих мест. Соедини предложения с картинками.", "pairs": [{"left_image": "@@MEDIA@@sm1/u9/place_city.webp", "right": "We can go to shops here.", "right_audio_tts": "We can go to shops here."}, {"left_image": "@@MEDIA@@sm1/u9/place_mountains.webp", "right": "We can climb up here.", "right_audio_tts": "We can climb up here."}, {"left_image": "@@MEDIA@@sm1/u9/place_beach.webp", "right": "We can make a sandcastle here.", "right_audio_tts": "We can make a sandcastle here."}, {"left_image": "@@MEDIA@@sm1/u9/place_lake.webp", "right": "We can go on a boat here.", "right_audio_tts": "We can go on a boat here."}, {"left_image": "@@MEDIA@@sm1/u9/place_campsite.webp", "right": "We can sleep in a tent here.", "right_audio_tts": "We can sleep in a tent here."}, {"left_image": "@@MEDIA@@sm1/u9/place_theme_park.webp", "right": "We can ride on fun things here.", "right_audio_tts": "We can ride on fun things here."}, {"left_image": "@@MEDIA@@sm1/u9/place_countryside.webp", "right": "We can see lots of trees here.", "right_audio_tts": "We can see lots of trees here."}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'gaps', replace($blk${"title": "Прочитай рассказы ребят и перетащи в пропуск, где каждый из них сейчас.", "mode": "drag", "text": "My name is Lucy. I’m at a __campsite__. I can sleep here.\nMy name is Mark. I’m in a __city__. I can take photos here.\nMy name is Jen. I’m in the __mountains__. I can go skiing here.\nMy name is Ben. I’m at the __beach__. I can go surfing here.\nMy name is Tim. I’m in the __countryside__. I can see birds here."}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'gaps', replace($blk${"title": "Ты справился с большей частью задания, ты — большой МОЛОДЕЦ! Прочитай о местах, которые я очень люблю, и заполни пропуски.", "mode": "drag", "text": "I like the __mountains__. I can climb up and __go skiing__ here.\nI like the __beach__. I can look for shells and __make a sandcastle__ here.\nI like the __campsite__. I can sleep in a tent here."}$blk$, '@@MEDIA@@', v_media)::jsonb, 9),
    (v_lesson, 'task', replace($blk${"title": "Дополнительное задание для ЧЕМПИОНОВ ⭐", "needs_review": true, "html": "<p>Его можно выполнить по желанию. <b>Письменно расскажи мне о своих любимых местах.</b> Используй мой рассказ из предыдущего упражнения как пример.</p><p><i>I like the … . I can … here.</i></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 10),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_trophy.webp\" alt=\"\" style=\"height:180px\"></p><h3>Поздравляю! Ты завершил домашнее задание 🏆</h3><p>Ты замечательный ученик! Лови сердечко ❤ Увидимся на занятии!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 11);
end
$mig$;
