-- Super Minds 3 · Unit 8 · Countries · Homework 7
-- собрано tools/sm3_build.py --lesson u8_hw7
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where title = 'Super Minds 3';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 8 · Countries', 8
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 8 · Countries');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 8 · Countries';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 7', 'homework',
         60, false, 6
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 7');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 7';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_rocket.webp\" alt=\"\" style=\"height:200px\"></p><h2>Hello! Welcome to your homework!</h2><p>Сегодня нас ждут задания о чудесах света. В конце есть дополнительное задание — для чемпионов: кто сделает его добросовестно, получит дополнительный балл.</p><p>Для начала ответь на вопрос: <b>How many new wonders are there in the world?</b> Прочитай текст и проверь себя!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@sm3/u8/reading_wonders_1.webp\" alt=\"\" style=\"max-width:100%\"></p><p><img src=\"@@MEDIA@@sm3/u8/reading_wonders_2.webp\" alt=\"\" style=\"max-width:100%\"></p><p><img src=\"@@MEDIA@@sm3/u8/reading_wonders_3.webp\" alt=\"\" style=\"max-width:100%\"></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'truefalse', replace($blk${"title": "Прочитай текст ещё раз и скажи, верные это предложения (correct) или нет (incorrect)", "statements": [{"text": "There are pink snakes in the Grand Canyon.", "correct": true}, {"text": "The beaches next to the Harbour of Rio de Janeiro are small.", "correct": false}, {"text": "The Northern Lights can be more than one colour.", "correct": true}, {"text": "Mount Everest isn’t very old.", "correct": false}, {"text": "Many fish live in the Great Barrier Reef.", "correct": true}, {"text": "The Zambezi river forms a big waterfall.", "correct": true}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'match', replace($blk${"title": "Соедини описания чудес света с их названиями", "pairs": [{"left": "Apart from different species of fish, you can also see whales and dolphins here. There are also 900 different islands around it and more than 2500 reefs. It is in danger because of sea pollution and climate change.", "right": "Great Barrier Reef", "right_image": "@@MEDIA@@sm3/u8/wonder_reef.webp", "right_audio_tts": "Great Barrier Reef"}, {"left": "It is named after a famous English queen. The area has a dry season and a rainy season. When it rains, more than 300,000 gallons of water fall there every second. When it doesn’t rain, you can walk across the top.", "right": "Victoria Falls", "right_image": "@@MEDIA@@sm3/u8/wonder_victoria_falls.webp", "right_audio_tts": "Victoria Falls"}, {"left": "There are more than 100 islands here with 15 different cities. There are 30 different beaches here, too, and in summer a million people can be on the beaches at the same time.", "right": "The Harbour of Rio de Janeiro", "right_image": "@@MEDIA@@sm3/u8/wonder_rio.webp", "right_audio_tts": "The Harbour of Rio de Janeiro"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'quiz', replace($blk${"title": "Задание на аудирование: ты услышишь радиопередачу о чудесах света. Прочитай факты, послушай запись и выбери правильный вариант", "audio": "", "questions": [{"q": "1. The Great Pyramid is in ___.", "type": "single", "options": [{"text": "Giza"}, {"text": "Cairo"}, {"text": "Khufu"}], "correct": [0]}, {"q": "2. The pyramid was the tallest building until ___. After that, Lincoln Cathedral in England was the tallest in 1311.", "type": "single", "options": [{"text": "1310"}, {"text": "1312"}, {"text": "755"}], "correct": [0]}, {"q": "3. The longest wall in the world is called the ___.", "type": "single", "options": [{"text": "Great Wall"}, {"text": "Grand Canyon"}, {"text": "Grand Wall"}], "correct": [0]}, {"q": "4. The wall has more than ___ stones.", "type": "single", "options": [{"text": "2.3 million"}, {"text": "2.3 billion"}, {"text": "2,300"}], "correct": [0]}, {"q": "5. The Taj Mahal was built to remember ___.", "type": "single", "options": [{"text": "a wife"}, {"text": "a daughter"}, {"text": "Shah Jahan"}], "correct": [0]}, {"q": "6. The palace is in ___.", "type": "single", "options": [{"text": "India"}, {"text": "Australia"}, {"text": "Argentina"}], "correct": [0]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'task', replace($blk${"title": "Дополнительное задание — для чемпионов", "needs_review": true, "html": "<p>Напиши небольшой рассказ (5–6 предложений) об одном из чудес света. Будет круто, если ты придумаешь своё собственное чудо света — включи воображение!</p><p>Не забудь рассказать: 1) что это; 2) где оно находится; 3) как оно выглядит.</p><p>А чтобы рассказ стал ещё красочнее — нарисуй своё чудо света!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/good_luck_clover.webp\" alt=\"\" style=\"height:180px\"></p><h3>Отличная работа! Осталась вторая часть</h3><p>В ней мы повторим всё, что прошли за месяц. Посмотри видео и ответь: <b>Was it hot or cold at the beach?</b></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'video', replace($blk${"title": "Видео: каникулы Грега", "url": "", "provider": ""}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'match', replace($blk${"title": "Помоги Грегу соединить начало и конец фраз — они перепутались!", "pairs": [{"left": "I went to the sea but", "right": "I didn’t have fun!", "right_audio_tts": "I didn't have fun!"}, {"left": "I didn’t want to swim because", "right": "there wasn’t sun!", "right_audio_tts": "there wasn't sun!"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'quiz', replace($blk${"title": "Внимательно читай предложения и выбирай правильный ответ", "questions": [{"q": "1. I went to China but I ___ the wall.", "type": "single", "options": [{"text": "didn’t see"}, {"text": "didn’t saw"}], "correct": [0]}, {"q": "2. In India, I ___ the Taj Mahal.", "type": "single", "options": [{"text": "didn’t visit"}, {"text": "didn’t visited"}], "correct": [0]}, {"q": "3. I went to Egypt but I didn’t ___ a picture of the Sphinx.", "type": "single", "options": [{"text": "take"}, {"text": "took"}], "correct": [0]}, {"q": "4. I went to Australia but I didn’t ___ in the sun.", "type": "single", "options": [{"text": "relax"}, {"text": "relaxed"}], "correct": [0]}, {"q": "5. In Brazil, I ___ in the Amazon.", "type": "single", "options": [{"text": "didn’t swim"}, {"text": "didn’t swam"}], "correct": [0]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 9),
    (v_lesson, 'video', replace($blk${"title": "Видео: на чём Грег поехал на каникулы", "url": "", "provider": ""}$blk$, '@@MEDIA@@', v_media)::jsonb, 10),
    (v_lesson, 'match', replace($blk${"title": "Лукас побывал в Древнем Египте. Вопросы и ответы интервью перепутались — помоги им найти друг друга!", "pairs": [{"left": "Lucas, where did you go in your time machine?", "right": "I went to ancient Egypt.", "right_audio_tts": "I went to ancient Egypt."}, {"left": "What did you see?", "right": "I saw the pyramids. There were thousands of people working there.", "right_audio_tts": "I saw the pyramids. There were thousands of people working there."}, {"left": "Did you have fun?", "right": "Yes, I did. It was great.", "right_audio_tts": "Yes, I did. It was great."}, {"left": "Was it hot?", "right": "Yes, it was. But I was OK. I had a big hat.", "right_audio_tts": "Yes, it was. But I was OK. I had a big hat."}, {"left": "How long did you stay there?", "right": "About five hours.", "right_audio_tts": "About five hours."}, {"left": "Did you buy anything?", "right": "No, I didn’t, but I took some photos.", "right_audio_tts": "No, I didn't, but I took some photos."}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 11),
    (v_lesson, 'task', replace($blk${"title": "Дополнительное задание — напиши о своём путешествии в машине времени", "needs_review": true, "html": "<p>Ты можешь отправиться в любое время и любую страну — прояви воображение! Воспользуйся рассказом Лукаса как образцом.</p><p><i>Lucas went to ancient Egypt in his time machine. He saw the pyramids and he saw thousands of people. He had fun in Egypt. He had a big hat with him. He stayed in Egypt for about five hours. He didn’t buy any food and took some photos.</i></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 12),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/congrats_popper.webp\" alt=\"\" style=\"height:180px\"></p><h3>Поздравляю! Ты завершил домашнее задание и готов к уроку.</h3><p>Ты — СУПЕР КРУТ! Жду тебя на уроке!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 13);
end
$mig$;
