-- Super Minds 3 · Unit 8 · Countries · Homework 1
-- собрано tools/sm3_build.py --lesson u8_hw1
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where title = 'Super Minds 3';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 8 · Countries', 8
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 8 · Countries');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 8 · Countries';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 1', 'homework',
         60, false, 0
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 1');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 1';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_rocket.webp\" alt=\"\" style=\"height:200px\"></p><h2>Добро пожаловать в домашнее задание!</h2><p>Ты начал новую тему — пора учить слова :) Сегодня мы запомним страны, о которых говорили на уроке.</p><p>А после основной части тебя ждут дополнительные задания — необязательные, но очень интересные!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"cards": [{"text": "Egypt", "translation": "Египет", "audio_tts": "Egypt", "image": "@@MEDIA@@sm3/u8/country_egypt.webp"}, {"text": "Chile", "translation": "Чили", "audio_tts": "Chile", "image": "@@MEDIA@@sm3/u8/country_chile.webp"}, {"text": "Mexico", "translation": "Мексика", "audio_tts": "Mexico", "image": "@@MEDIA@@sm3/u8/country_mexico.webp"}, {"text": "China", "translation": "Китай", "audio_tts": "China", "image": "@@MEDIA@@sm3/u8/country_china.webp"}, {"text": "Spain", "translation": "Испания", "audio_tts": "Spain", "image": "@@MEDIA@@sm3/u8/country_spain.webp"}, {"text": "India", "translation": "Индия", "audio_tts": "India", "image": "@@MEDIA@@sm3/u8/country_india.webp"}, {"text": "Argentina", "translation": "Аргентина", "audio_tts": "Argentina", "image": "@@MEDIA@@sm3/u8/country_argentina.webp"}, {"text": "Australia", "translation": "Австралия", "audio_tts": "Australia", "image": "@@MEDIA@@sm3/u8/country_australia.webp"}, {"text": "Brazil", "translation": "Бразилия", "audio_tts": "Brazil", "image": "@@MEDIA@@sm3/u8/country_brazil.webp"}, {"text": "Turkey", "translation": "Турция", "audio_tts": "Turkey", "image": "@@MEDIA@@sm3/u8/country_turkey.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «Египет»?", "type": "single", "options": [{"text": "Chile"}, {"text": "China"}, {"text": "Egypt"}, {"text": "Mexico"}], "correct": [2]}, {"q": "Как по-английски «Чили»?", "type": "single", "options": [{"text": "Chile"}, {"text": "China"}, {"text": "Mexico"}, {"text": "Spain"}], "correct": [0]}, {"q": "Как по-английски «Мексика»?", "type": "single", "options": [{"text": "China"}, {"text": "India"}, {"text": "Mexico"}, {"text": "Spain"}], "correct": [2]}, {"q": "Как по-английски «Китай»?", "type": "single", "options": [{"text": "Argentina"}, {"text": "China"}, {"text": "India"}, {"text": "Spain"}], "correct": [1]}, {"q": "Как по-английски «Испания»?", "type": "single", "options": [{"text": "Argentina"}, {"text": "Australia"}, {"text": "India"}, {"text": "Spain"}], "correct": [3]}, {"q": "Как по-английски «Индия»?", "type": "single", "options": [{"text": "Argentina"}, {"text": "Australia"}, {"text": "Brazil"}, {"text": "India"}], "correct": [3]}, {"q": "Как по-английски «Аргентина»?", "type": "single", "options": [{"text": "Argentina"}, {"text": "Australia"}, {"text": "Brazil"}, {"text": "Turkey"}], "correct": [0]}, {"q": "Как по-английски «Австралия»?", "type": "single", "options": [{"text": "Australia"}, {"text": "Brazil"}, {"text": "Egypt"}, {"text": "Turkey"}], "correct": [0]}, {"q": "Как по-английски «Бразилия»?", "type": "single", "options": [{"text": "Brazil"}, {"text": "Chile"}, {"text": "Egypt"}, {"text": "Turkey"}], "correct": [0]}, {"q": "Как по-английски «Турция»?", "type": "single", "options": [{"text": "Chile"}, {"text": "Egypt"}, {"text": "Mexico"}, {"text": "Turkey"}], "correct": [3]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'exact_input', replace($blk${"items": [{"image": "@@MEDIA@@sm3/u8/country_egypt.webp", "prompt": "Посмотри на картинку и напиши страну", "accept": ["Egypt", "egypt"], "audio_tts": "Egypt"}, {"image": "@@MEDIA@@sm3/u8/country_chile.webp", "prompt": "Посмотри на картинку и напиши страну", "accept": ["Chile", "chile"], "audio_tts": "Chile"}, {"image": "@@MEDIA@@sm3/u8/country_mexico.webp", "prompt": "Посмотри на картинку и напиши страну", "accept": ["Mexico", "mexico"], "audio_tts": "Mexico"}, {"image": "@@MEDIA@@sm3/u8/country_china.webp", "prompt": "Посмотри на картинку и напиши страну", "accept": ["China", "china"], "audio_tts": "China"}, {"image": "@@MEDIA@@sm3/u8/country_spain.webp", "prompt": "Посмотри на картинку и напиши страну", "accept": ["Spain", "spain"], "audio_tts": "Spain"}, {"image": "@@MEDIA@@sm3/u8/country_india.webp", "prompt": "Посмотри на картинку и напиши страну", "accept": ["India", "india"], "audio_tts": "India"}, {"image": "@@MEDIA@@sm3/u8/country_argentina.webp", "prompt": "Посмотри на картинку и напиши страну", "accept": ["Argentina", "argentina"], "audio_tts": "Argentina"}, {"image": "@@MEDIA@@sm3/u8/country_australia.webp", "prompt": "Посмотри на картинку и напиши страну", "accept": ["Australia", "australia"], "audio_tts": "Australia"}, {"image": "@@MEDIA@@sm3/u8/country_brazil.webp", "prompt": "Посмотри на картинку и напиши страну", "accept": ["Brazil", "brazil"], "audio_tts": "Brazil"}, {"image": "@@MEDIA@@sm3/u8/country_turkey.webp", "prompt": "Посмотри на картинку и напиши страну", "accept": ["Turkey", "turkey"], "audio_tts": "Turkey"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/good_luck_clover.webp\" alt=\"\" style=\"height:180px\"></p><h3>Добро пожаловать в дополнительную часть!</h3><p>Те, кто выполнит задания отсюда, будут самыми крутыми и подготовленными на следующем уроке.</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'match', replace($blk${"title": "Соедини название страны и флаг", "pairs": [{"left": "Egypt", "right_image": "@@MEDIA@@sm3/u8/flag_egypt.webp", "right": "Egypt flag"}, {"left": "Argentina", "right_image": "@@MEDIA@@sm3/u8/flag_argentina.webp", "right": "Argentina flag"}, {"left": "Chile", "right_image": "@@MEDIA@@sm3/u8/flag_chile.webp", "right": "Chile flag"}, {"left": "Mexico", "right_image": "@@MEDIA@@sm3/u8/flag_mexico.webp", "right": "Mexico flag"}, {"left": "Spain", "right_image": "@@MEDIA@@sm3/u8/flag_spain.webp", "right": "Spain flag"}, {"left": "China", "right_image": "@@MEDIA@@sm3/u8/flag_china.webp", "right": "China flag"}, {"left": "India", "right_image": "@@MEDIA@@sm3/u8/flag_india.webp", "right": "India flag"}, {"left": "Turkey", "right_image": "@@MEDIA@@sm3/u8/flag_turkey.webp", "right": "Turkey flag"}, {"left": "Brazil", "right_image": "@@MEDIA@@sm3/u8/flag_brazil.webp", "right": "Brazil flag"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'task', replace($blk${"title": "Нарисуй два флага", "needs_review": true, "html": "<p>Дома на листочке или в тетради нарисуй флаг своей страны и флаг страны, в которой ты мечтаешь жить. Если это одна и та же страна — супер, нарисуй один флаг!</p><p><i>For example: I live in Russia, but I’d like to live in Turkey!</i></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_star.webp\" alt=\"\" style=\"height:180px\"></p><h3>Поздравляю! Ты завершил домашнее задание — ты МЕГА КРУТ!</h3><p>Жду тебя на уроке!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 7);
end
$mig$;
