-- Super Minds 3 · Unit 4 · In the town · Homework 1
-- собрано tools/sm3_build.py --lesson u4_hw1
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where title = 'Super Minds 3';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 4 · In the town', 4
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 4 · In the town');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 4 · In the town';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 1', 'homework',
         60, false, 0
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 1');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 1';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет! How are you?</h2><p>Сегодня мы выучим слова, которые ты изучил на занятии. Поехали!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"cards": [{"text": "bank", "translation": "банк", "audio_tts": "bank", "image": "@@MEDIA@@sm3/u4/town_bank.webp"}, {"text": "tower", "translation": "башня", "audio_tts": "tower", "image": "@@MEDIA@@sm3/u4/town_tower.webp"}, {"text": "map", "translation": "карта", "audio_tts": "map", "image": "@@MEDIA@@sm3/u4/town_map.webp"}, {"text": "library", "translation": "библиотека", "audio_tts": "library", "image": "@@MEDIA@@sm3/u4/town_library.webp"}, {"text": "market square", "translation": "торговая площадь", "audio_tts": "market square", "image": "@@MEDIA@@sm3/u4/town_market.webp"}, {"text": "supermarket", "translation": "супермаркет", "audio_tts": "supermarket", "image": "@@MEDIA@@sm3/u4/town_supermarket.webp"}, {"text": "bus station", "translation": "автобусная остановка", "audio_tts": "bus station", "image": "@@MEDIA@@sm3/u4/town_bus_station.webp"}, {"text": "sports centre", "translation": "спортивный центр", "audio_tts": "sports centre", "image": "@@MEDIA@@sm3/u4/town_sports_centre.webp"}, {"text": "car park", "translation": "парковка", "audio_tts": "car park", "image": "@@MEDIA@@sm3/u4/town_car_park.webp"}, {"text": "funfair", "translation": "парк с аттракционами", "audio_tts": "funfair", "image": "@@MEDIA@@sm3/u4/town_funfair.webp"}, {"text": "go straight", "translation": "идти прямо", "audio_tts": "go straight", "image": "@@MEDIA@@sm3/u4/arrow_straight.webp"}, {"text": "turn left", "translation": "повернуть налево", "audio_tts": "turn left", "image": "@@MEDIA@@sm3/u4/arrow_left.webp"}, {"text": "turn right", "translation": "повернуть направо", "audio_tts": "turn right", "image": "@@MEDIA@@sm3/u4/arrow_right.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «банк»?", "type": "single", "options": [{"text": "bank"}, {"text": "library"}, {"text": "map"}, {"text": "tower"}], "correct": [0]}, {"q": "Как по-английски «башня»?", "type": "single", "options": [{"text": "library"}, {"text": "map"}, {"text": "market square"}, {"text": "tower"}], "correct": [3]}, {"q": "Как по-английски «карта»?", "type": "single", "options": [{"text": "library"}, {"text": "map"}, {"text": "market square"}, {"text": "supermarket"}], "correct": [1]}, {"q": "Как по-английски «библиотека»?", "type": "single", "options": [{"text": "bus station"}, {"text": "library"}, {"text": "market square"}, {"text": "supermarket"}], "correct": [1]}, {"q": "Как по-английски «торговая площадь»?", "type": "single", "options": [{"text": "bus station"}, {"text": "market square"}, {"text": "sports centre"}, {"text": "supermarket"}], "correct": [1]}, {"q": "Как по-английски «супермаркет»?", "type": "single", "options": [{"text": "bus station"}, {"text": "car park"}, {"text": "sports centre"}, {"text": "supermarket"}], "correct": [3]}, {"q": "Как по-английски «автобусная остановка»?", "type": "single", "options": [{"text": "bus station"}, {"text": "car park"}, {"text": "funfair"}, {"text": "sports centre"}], "correct": [0]}, {"q": "Как по-английски «спортивный центр»?", "type": "single", "options": [{"text": "car park"}, {"text": "funfair"}, {"text": "go straight"}, {"text": "sports centre"}], "correct": [3]}, {"q": "Как по-английски «парковка»?", "type": "single", "options": [{"text": "car park"}, {"text": "funfair"}, {"text": "go straight"}, {"text": "turn left"}], "correct": [0]}, {"q": "Как по-английски «парк с аттракционами»?", "type": "single", "options": [{"text": "funfair"}, {"text": "go straight"}, {"text": "turn left"}, {"text": "turn right"}], "correct": [0]}, {"q": "Как по-английски «идти прямо»?", "type": "single", "options": [{"text": "bank"}, {"text": "go straight"}, {"text": "turn left"}, {"text": "turn right"}], "correct": [1]}, {"q": "Как по-английски «повернуть налево»?", "type": "single", "options": [{"text": "bank"}, {"text": "tower"}, {"text": "turn left"}, {"text": "turn right"}], "correct": [2]}, {"q": "Как по-английски «повернуть направо»?", "type": "single", "options": [{"text": "bank"}, {"text": "map"}, {"text": "tower"}, {"text": "turn right"}], "correct": [3]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'exact_input', replace($blk${"items": [{"image": "@@MEDIA@@sm3/u4/town_bank.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["bank", "Bank"], "audio_tts": "bank"}, {"image": "@@MEDIA@@sm3/u4/town_tower.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["tower", "Tower"], "audio_tts": "tower"}, {"image": "@@MEDIA@@sm3/u4/town_map.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["map", "Map"], "audio_tts": "map"}, {"image": "@@MEDIA@@sm3/u4/town_library.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["library", "Library"], "audio_tts": "library"}, {"image": "@@MEDIA@@sm3/u4/town_market.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["market square", "Market square"], "audio_tts": "market square"}, {"image": "@@MEDIA@@sm3/u4/town_supermarket.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["supermarket", "Supermarket"], "audio_tts": "supermarket"}, {"image": "@@MEDIA@@sm3/u4/town_bus_station.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["bus station", "Bus station"], "audio_tts": "bus station"}, {"image": "@@MEDIA@@sm3/u4/town_sports_centre.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["sports centre", "Sports centre"], "audio_tts": "sports centre"}, {"image": "@@MEDIA@@sm3/u4/town_car_park.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["car park", "Car park"], "audio_tts": "car park"}, {"image": "@@MEDIA@@sm3/u4/town_funfair.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["funfair", "Funfair"], "audio_tts": "funfair"}, {"image": "@@MEDIA@@sm3/u4/arrow_straight.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["go straight", "Go straight"], "audio_tts": "go straight"}, {"image": "@@MEDIA@@sm3/u4/arrow_left.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["turn left", "Turn left"], "audio_tts": "turn left"}, {"image": "@@MEDIA@@sm3/u4/arrow_right.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["turn right", "Turn right"], "audio_tts": "turn right"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_star.webp\" alt=\"\" style=\"height:180px\"></p><h3>Отлично! Слова выучены.</h3><p>Увидимся на уроке!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 4);
end
$mig$;
