-- Super Minds 3 · Unit 9 · Weather · Homework 1
-- собрано tools/sm3_build.py --lesson u9_hw1
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where title = 'Super Minds 3';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 9 · Weather', 9
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 9 · Weather');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 9 · Weather';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 1', 'homework',
         60, false, 0
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 1');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 1';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Добро пожаловать в домашнее задание!</h2><p>Сегодня мы выучим разные виды погоды. Выполни все задания, если хочешь выучить тему на все 100!</p><p>А в конце тебя ждёт дополнительная часть — по желанию, НО если сделаешь, будешь нереально крут!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"cards": [{"text": "thunderstorm", "translation": "шторм", "audio_tts": "thunderstorm", "image": "@@MEDIA@@sm3/u9/weather_thunderstorm.webp"}, {"text": "rainy", "translation": "дождливо", "audio_tts": "rainy", "image": "@@MEDIA@@sm3/u9/weather_rainy.webp"}, {"text": "cloudy", "translation": "облачно", "audio_tts": "cloudy", "image": "@@MEDIA@@sm3/u9/weather_cloudy.webp"}, {"text": "windy", "translation": "ветрено", "audio_tts": "windy", "image": "@@MEDIA@@sm3/u9/weather_windy.webp"}, {"text": "boots", "translation": "сапоги", "audio_tts": "boots", "image": "@@MEDIA@@sm3/u9/clothes_boots.webp"}, {"text": "raincoat", "translation": "дождевик", "audio_tts": "raincoat", "image": "@@MEDIA@@sm3/u9/clothes_raincoat.webp"}, {"text": "umbrella", "translation": "зонт", "audio_tts": "umbrella", "image": "@@MEDIA@@sm3/u9/clothes_umbrella.webp"}, {"text": "lightning", "translation": "молния", "audio_tts": "lightning", "image": "@@MEDIA@@sm3/u9/weather_lightning.webp"}, {"text": "foggy", "translation": "туманно", "audio_tts": "foggy", "image": "@@MEDIA@@sm3/u9/weather_foggy.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «шторм»?", "type": "single", "options": [{"text": "cloudy"}, {"text": "rainy"}, {"text": "thunderstorm"}, {"text": "windy"}], "correct": [2]}, {"q": "Как по-английски «дождливо»?", "type": "single", "options": [{"text": "boots"}, {"text": "cloudy"}, {"text": "rainy"}, {"text": "windy"}], "correct": [2]}, {"q": "Как по-английски «облачно»?", "type": "single", "options": [{"text": "boots"}, {"text": "cloudy"}, {"text": "raincoat"}, {"text": "windy"}], "correct": [1]}, {"q": "Как по-английски «ветрено»?", "type": "single", "options": [{"text": "boots"}, {"text": "raincoat"}, {"text": "umbrella"}, {"text": "windy"}], "correct": [3]}, {"q": "Как по-английски «сапоги»?", "type": "single", "options": [{"text": "boots"}, {"text": "lightning"}, {"text": "raincoat"}, {"text": "umbrella"}], "correct": [0]}, {"q": "Как по-английски «дождевик»?", "type": "single", "options": [{"text": "foggy"}, {"text": "lightning"}, {"text": "raincoat"}, {"text": "umbrella"}], "correct": [2]}, {"q": "Как по-английски «зонт»?", "type": "single", "options": [{"text": "foggy"}, {"text": "lightning"}, {"text": "thunderstorm"}, {"text": "umbrella"}], "correct": [3]}, {"q": "Как по-английски «молния»?", "type": "single", "options": [{"text": "foggy"}, {"text": "lightning"}, {"text": "rainy"}, {"text": "thunderstorm"}], "correct": [1]}, {"q": "Как по-английски «туманно»?", "type": "single", "options": [{"text": "cloudy"}, {"text": "foggy"}, {"text": "rainy"}, {"text": "thunderstorm"}], "correct": [1]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'exact_input', replace($blk${"items": [{"image": "@@MEDIA@@sm3/u9/weather_thunderstorm.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["thunderstorm", "Thunderstorm"], "audio_tts": "thunderstorm"}, {"image": "@@MEDIA@@sm3/u9/weather_rainy.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["rainy", "Rainy"], "audio_tts": "rainy"}, {"image": "@@MEDIA@@sm3/u9/weather_cloudy.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["cloudy", "Cloudy"], "audio_tts": "cloudy"}, {"image": "@@MEDIA@@sm3/u9/weather_windy.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["windy", "Windy"], "audio_tts": "windy"}, {"image": "@@MEDIA@@sm3/u9/clothes_boots.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["boots", "Boots"], "audio_tts": "boots"}, {"image": "@@MEDIA@@sm3/u9/clothes_raincoat.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["raincoat", "Raincoat"], "audio_tts": "raincoat"}, {"image": "@@MEDIA@@sm3/u9/clothes_umbrella.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["umbrella", "Umbrella"], "audio_tts": "umbrella"}, {"image": "@@MEDIA@@sm3/u9/weather_lightning.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["lightning", "Lightning"], "audio_tts": "lightning"}, {"image": "@@MEDIA@@sm3/u9/weather_foggy.webp", "prompt": "Посмотри на картинку и напиши слово", "accept": ["foggy", "Foggy"], "audio_tts": "foggy"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/good_luck_clover.webp\" alt=\"\" style=\"height:180px\"></p><h3>А теперь — вторая, дополнительная часть</h3><p>Выполнив эти задания, ты станешь МЕГА крутым учеником!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'match', replace($blk${"title": "Сопоставь слова и их описания", "pairs": [{"left": "When there’s lots of rain and lightning. You can hear big ‘bangs’.", "right": "Thunderstorm", "right_audio_tts": "thunderstorm"}, {"left": "You use this in the rain.", "right": "Umbrella", "right_audio_tts": "umbrella"}, {"left": "A good day to fly your kite.", "right": "Windy", "right_audio_tts": "windy"}, {"left": "A flash from the sky.", "right": "Lightning", "right_audio_tts": "lightning"}, {"left": "When you can’t see the sun.", "right": "Cloudy", "right_audio_tts": "cloudy"}, {"left": "When you can’t see where you are going.", "right": "Foggy", "right_audio_tts": "foggy"}, {"left": "You can get very wet in weather like this.", "right": "Rainy", "right_audio_tts": "rainy"}, {"left": "You put these on your feet when it’s raining.", "right": "Boots", "right_audio_tts": "boots"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'gaps', replace($blk${"title": "Слова растерялись! Помоги им найти свои места в тексте", "mode": "drag", "text": "The weather was terrible yesterday. It was cold and __foggy__ in the morning. Then there was no sun because it was __cloudy__. At lunchtime it was very __rainy__, so all my things got wet. And then at about 5 o’clock the __thunderstorm__ started. There was lots of __lightning__ in the sky. I was quite scared because I was in a tent, camping! And I didn’t have an __umbrella__ or a __raincoat__ to wear. And I didn’t have any __boots__ for my feet. It was awful!"}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_star.webp\" alt=\"\" style=\"height:180px\"></p><h3>Поздравляю! Ты завершил домашнее задание — ты МЕГА КРУТ!</h3><p>Жду тебя на уроке!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 7);
end
$mig$;
