-- Super Minds 3 · Unit 3 · At home · Homework 1
-- собрано tools/sm3_build.py --lesson u3_hw1
do $mig$
declare
  v_course uuid;
  v_unit   uuid;
  v_lesson uuid;
  v_media  text := 'https://classroom.wowteach.ru/media/';
begin
  select id into v_course from classroom_courses where title = 'Super Minds 3';

  insert into classroom_units (course_id, title, sort_order)
  select v_course, 'Unit 3 · At home', 3
  where not exists (select 1 from classroom_units
                    where course_id = v_course and title = 'Unit 3 · At home');
  select id into v_unit from classroom_units
   where course_id = v_course and title = 'Unit 3 · At home';

  insert into classroom_lessons (unit_id, title, kind, pass_threshold, is_published, sort_order)
  select v_unit, 'Homework 1', 'homework',
         60, false, 0
  where not exists (select 1 from classroom_lessons
                    where unit_id = v_unit and title = 'Homework 1');
  select id into v_lesson from classroom_lessons
   where unit_id = v_unit and title = 'Homework 1';

  delete from classroom_blocks where lesson_id = v_lesson;

  insert into classroom_blocks (lesson_id, type, payload, sort_order) values
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/hello_wave.webp\" alt=\"\" style=\"height:200px\"></p><h2>Привет-привет!</h2><p>Сегодня мы будем изучать слова, которые ты проходил на уроке. Чем ты любишь заниматься дома? Выполни задания, повтори слова и ответь на вопрос :) Готов начать?</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 0),
    (v_lesson, 'flashcards', replace($blk${"cards": [{"text": "tidy up", "translation": "убираться", "audio_tts": "tidy up", "image": "@@MEDIA@@sm3/u3/chore_tidy_up.webp"}, {"text": "do the shopping", "translation": "ходить за покупками", "audio_tts": "do the shopping", "image": "@@MEDIA@@sm3/u3/chore_do_shopping.webp"}, {"text": "take the dog for a walk", "translation": "выгуливать собаку", "audio_tts": "take the dog for a walk", "image": "@@MEDIA@@sm3/u3/chore_walk_dog.webp"}, {"text": "wash up", "translation": "мыть посуду", "audio_tts": "wash up", "image": "@@MEDIA@@sm3/u3/chore_wash_up.webp"}, {"text": "sweep", "translation": "подметать", "audio_tts": "sweep", "image": "@@MEDIA@@sm3/u3/chore_sweep.webp"}, {"text": "cook", "translation": "готовить", "audio_tts": "cook", "image": "@@MEDIA@@sm3/u3/chore_cook.webp"}, {"text": "dry the dishes", "translation": "вытирать посуду", "audio_tts": "dry the dishes", "image": "@@MEDIA@@sm3/u3/chore_dry_dishes.webp"}, {"text": "feed the dog", "translation": "кормить собаку", "audio_tts": "feed the dog", "image": "@@MEDIA@@sm3/u3/chore_feed_dog.webp"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 1),
    (v_lesson, 'quiz', replace($blk${"questions": [{"q": "Как по-английски «убираться»?", "type": "single", "options": [{"text": "do the shopping"}, {"text": "take the dog for a walk"}, {"text": "tidy up"}, {"text": "wash up"}], "correct": [2]}, {"q": "Как по-английски «ходить за покупками»?", "type": "single", "options": [{"text": "do the shopping"}, {"text": "sweep"}, {"text": "take the dog for a walk"}, {"text": "wash up"}], "correct": [0]}, {"q": "Как по-английски «выгуливать собаку»?", "type": "single", "options": [{"text": "cook"}, {"text": "sweep"}, {"text": "take the dog for a walk"}, {"text": "wash up"}], "correct": [2]}, {"q": "Как по-английски «мыть посуду»?", "type": "single", "options": [{"text": "cook"}, {"text": "dry the dishes"}, {"text": "sweep"}, {"text": "wash up"}], "correct": [3]}, {"q": "Как по-английски «подметать»?", "type": "single", "options": [{"text": "cook"}, {"text": "dry the dishes"}, {"text": "feed the dog"}, {"text": "sweep"}], "correct": [3]}, {"q": "Как по-английски «готовить»?", "type": "single", "options": [{"text": "cook"}, {"text": "dry the dishes"}, {"text": "feed the dog"}, {"text": "tidy up"}], "correct": [0]}, {"q": "Как по-английски «вытирать посуду»?", "type": "single", "options": [{"text": "do the shopping"}, {"text": "dry the dishes"}, {"text": "feed the dog"}, {"text": "tidy up"}], "correct": [1]}, {"q": "Как по-английски «кормить собаку»?", "type": "single", "options": [{"text": "do the shopping"}, {"text": "feed the dog"}, {"text": "take the dog for a walk"}, {"text": "tidy up"}], "correct": [1]}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 2),
    (v_lesson, 'exact_input', replace($blk${"items": [{"image": "@@MEDIA@@sm3/u3/chore_tidy_up.webp", "prompt": "Посмотри на картинку и напиши, что здесь делают", "accept": ["tidy up", "Tidy up"], "audio_tts": "tidy up"}, {"image": "@@MEDIA@@sm3/u3/chore_do_shopping.webp", "prompt": "Посмотри на картинку и напиши, что здесь делают", "accept": ["do the shopping", "Do the shopping"], "audio_tts": "do the shopping"}, {"image": "@@MEDIA@@sm3/u3/chore_walk_dog.webp", "prompt": "Посмотри на картинку и напиши, что здесь делают", "accept": ["take the dog for a walk", "Take the dog for a walk"], "audio_tts": "take the dog for a walk"}, {"image": "@@MEDIA@@sm3/u3/chore_wash_up.webp", "prompt": "Посмотри на картинку и напиши, что здесь делают", "accept": ["wash up", "Wash up"], "audio_tts": "wash up"}, {"image": "@@MEDIA@@sm3/u3/chore_sweep.webp", "prompt": "Посмотри на картинку и напиши, что здесь делают", "accept": ["sweep", "Sweep"], "audio_tts": "sweep"}, {"image": "@@MEDIA@@sm3/u3/chore_cook.webp", "prompt": "Посмотри на картинку и напиши, что здесь делают", "accept": ["cook", "Cook"], "audio_tts": "cook"}, {"image": "@@MEDIA@@sm3/u3/chore_dry_dishes.webp", "prompt": "Посмотри на картинку и напиши, что здесь делают", "accept": ["dry the dishes", "Dry the dishes"], "audio_tts": "dry the dishes"}, {"image": "@@MEDIA@@sm3/u3/chore_feed_dog.webp", "prompt": "Посмотри на картинку и напиши, что здесь делают", "accept": ["feed the dog", "Feed the dog"], "audio_tts": "feed the dog"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 3),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/good_luck_clover.webp\" alt=\"\" style=\"height:180px\"></p><h3>Это дополнительная часть домашней работы</h3><p>Здесь тебя ждут очень интересные задания. Её можно выполнить по желанию — но если ты всё-таки её сделаешь, будет просто отлично 😊</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 4),
    (v_lesson, 'match', replace($blk${"title": "Посмотри внимательно на слова и соедини первую часть фразы со второй", "pairs": [{"left": "sweep", "right": "the floor", "right_audio_tts": "sweep the floor"}, {"left": "wash", "right": "up", "right_audio_tts": "wash up"}, {"left": "do", "right": "the shopping", "right_audio_tts": "do the shopping"}, {"left": "tidy", "right": "up your room", "right_audio_tts": "tidy up your room"}, {"left": "cook", "right": "the dinner", "right_audio_tts": "cook the dinner"}, {"left": "dry", "right": "the dishes", "right_audio_tts": "dry the dishes"}, {"left": "take", "right": "the dog for a walk", "right_audio_tts": "take the dog for a walk"}, {"left": "feed", "right": "the dog", "right_audio_tts": "feed the dog"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 5),
    (v_lesson, 'match', replace($blk${"title": "Молодец! Давай ещё потренируемся — соедини картинки с названиями", "pairs": [{"left_image": "@@MEDIA@@sm3/u3/chore_tidy_up.webp", "right": "tidy up", "right_audio_tts": "tidy up"}, {"left_image": "@@MEDIA@@sm3/u3/chore_sweep.webp", "right": "sweep", "right_audio_tts": "sweep"}, {"left_image": "@@MEDIA@@sm3/u3/chore_feed_dog.webp", "right": "feed the dog", "right_audio_tts": "feed the dog"}, {"left_image": "@@MEDIA@@sm3/u3/chore_dry_dishes.webp", "right": "dry the dishes", "right_audio_tts": "dry the dishes"}, {"left_image": "@@MEDIA@@sm3/u3/chore_do_shopping.webp", "right": "do the shopping", "right_audio_tts": "do the shopping"}, {"left_image": "@@MEDIA@@sm3/u3/chore_wash_up.webp", "right": "wash up", "right_audio_tts": "wash up"}]}$blk$, '@@MEDIA@@', v_media)::jsonb, 6),
    (v_lesson, 'text', replace($blk${"html": "<h3>WOW! Ты справился с основными заданиями. Осталось ещё одно — прочитай образец</h3><p><b>Write about you.</b></p><p><i>I like taking the dog for a walk. I don’t like tidying up.</i></p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 7),
    (v_lesson, 'task', replace($blk${"title": "Теперь расскажи про себя!", "needs_review": true, "html": "<p>Что ты любишь и не любишь делать по дому? Ориентируйся на образец выше.</p><p>Не забудь рассказать свой текст на уроке :)</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 8),
    (v_lesson, 'text', replace($blk${"html": "<p><img src=\"@@MEDIA@@shared/well_done_clap.webp\" alt=\"\" style=\"height:180px\"></p><h3>Вот и всё, домашняя работа выполнена!</h3><p>Огромное спасибо за твой труд. Увидимся на занятии!</p>"}$blk$, '@@MEDIA@@', v_media)::jsonb, 9);
end
$mig$;
