UPDATE words w SET image_url = v.u
FROM (VALUES
(271,'break up','https://train.wowteach.ru/media/prepare5/254/break_up.webp'),
(271,'figure (sth) out','https://train.wowteach.ru/media/prepare6/271/figure_sth_out.webp'),
(271,'get in','https://train.wowteach.ru/media/prepare6/271/get_in.webp'),
(271,'get on','https://train.wowteach.ru/media/prepare6/271/get_on.webp'),
(271,'give (sth) out','https://train.wowteach.ru/media/prepare6/271/give_sth_out.webp'),
(271,'go for (sth)','https://train.wowteach.ru/media/prepare6/271/go_for_sth.webp'),
(271,'hand (sth) in','https://train.wowteach.ru/media/prepare6/271/hand_sth_in.webp'),
(271,'join in (sth)','https://train.wowteach.ru/media/prepare5/270/join_in.webp'),
(271,'note (sth) down','https://train.wowteach.ru/media/prepare6/271/note_sth_down.webp'),
(271,'put (sth) off','https://train.wowteach.ru/media/prepare6/271/put_sth_off.webp'),
(271,'read (sth) out','https://train.wowteach.ru/media/prepare6/271/read_sth_out.webp'),
(271,'stay behind','https://train.wowteach.ru/media/prepare6/271/stay_behind.webp'),
(271,'try (sth) out','https://train.wowteach.ru/media/prepare6/271/try_sth_out.webp'),
(272,'action','https://train.wowteach.ru/media/prepare6/272/action.webp'),
(272,'concentration','https://train.wowteach.ru/media/prepare6/272/concentration.webp'),
(272,'connection','https://train.wowteach.ru/media/prepare5/251/connection.webp'),
(272,'decision','https://train.wowteach.ru/media/prepare6/272/decision.webp'),
(272,'definition','https://train.wowteach.ru/media/prepare6/272/definition.webp'),
(272,'discussion','https://train.wowteach.ru/media/prepare6/272/discussion.webp'),
(272,'education','https://train.wowteach.ru/media/prepare5/254/education.webp'),
(272,'explanation','https://train.wowteach.ru/media/prepare6/272/explanation.webp'),
(272,'expression','https://train.wowteach.ru/media/prepare6/272/expression.webp'),
(272,'introduction','https://train.wowteach.ru/media/prepare6/272/introduction.webp'),
(272,'invention','https://train.wowteach.ru/media/prepare5/251/invention.webp'),
(272,'motivation','https://train.wowteach.ru/media/prepare6/272/motivation.webp'),
(272,'permission','https://train.wowteach.ru/media/prepare6/272/permission.webp'),
(272,'preparation','https://train.wowteach.ru/media/prepare6/272/preparation.webp'),
(272,'recommendation','https://train.wowteach.ru/media/prepare6/272/recommendation.webp'),
(272,'registration','https://train.wowteach.ru/media/prepare6/272/registration.webp'),
(272,'selection','https://train.wowteach.ru/media/prepare6/272/selection.webp'),
(273,'background music','https://train.wowteach.ru/media/prepare6/273/background_music.webp'),
(273,'the charts','https://train.wowteach.ru/media/prepare6/273/the_charts.webp'),
(273,'concert venue','https://train.wowteach.ru/media/prepare6/273/concert_venue.webp'),
(273,'debut album','https://train.wowteach.ru/media/prepare6/273/debut_album.webp'),
(273,'devoted fans','https://train.wowteach.ru/media/prepare6/273/devoted_fans.webp'),
(273,'give a performance','https://train.wowteach.ru/media/prepare6/273/give_a_performance.webp'),
(273,'go solo','https://train.wowteach.ru/media/prepare6/273/go_solo.webp'),
(273,'lead singer','https://train.wowteach.ru/media/prepare6/273/lead_singer.webp'),
(273,'massive hit','https://train.wowteach.ru/media/prepare6/273/massive_hit.webp'),
(273,'musical talent','https://train.wowteach.ru/media/prepare6/273/musical_talent.webp'),
(273,'release a track','https://train.wowteach.ru/media/prepare6/273/release_a_track.webp'),
(273,'tour the world','https://train.wowteach.ru/media/prepare6/273/tour_the_world.webp'),
(275,'accuse','https://train.wowteach.ru/media/prepare6/275/accuse.webp'),
(275,'claim','https://train.wowteach.ru/media/prepare6/275/claim.webp'),
(275,'confess','https://train.wowteach.ru/media/prepare6/275/confess.webp'),
(275,'deny','https://train.wowteach.ru/media/prepare6/275/deny.webp'),
(275,'order','https://train.wowteach.ru/media/prepare6/275/order.webp'),
(275,'suggest','https://train.wowteach.ru/media/prepare5/264/suggest.webp'),
(275,'threaten','https://train.wowteach.ru/media/prepare6/275/threaten.webp'),
(275,'warn','https://train.wowteach.ru/media/prepare5/265/warn.webp'),
(276,'depend on (sb)','https://train.wowteach.ru/media/prepare5/270/depend_on.webp'),
(276,'fall out with (sb)','https://train.wowteach.ru/media/prepare6/276/fall_out_with_sb.webp'),
(276,'identify with (sb)','https://train.wowteach.ru/media/prepare6/276/identify_with_sb.webp'),
(276,'pick on (sb)','https://train.wowteach.ru/media/prepare6/276/pick_on_sb.webp'),
(276,'take after (sb)','https://train.wowteach.ru/media/prepare6/276/take_after_sb.webp'),
(276,'talk (sb) into','https://train.wowteach.ru/media/prepare6/276/talk_sb_into.webp'),
(277,'collapse','https://train.wowteach.ru/media/prepare6/277/collapse.webp'),
(277,'crack','https://train.wowteach.ru/media/prepare6/277/crack.webp'),
(277,'drag','https://train.wowteach.ru/media/prepare6/277/drag.webp'),
(277,'erupt','https://train.wowteach.ru/media/prepare6/277/erupt.webp'),
(277,'float','https://train.wowteach.ru/media/prepare6/277/float.webp'),
(277,'knock over','https://train.wowteach.ru/media/prepare6/277/knock_over.webp'),
(277,'run','https://train.wowteach.ru/media/prepare6/277/run.webp'),
(277,'shake','https://train.wowteach.ru/media/prepare5/243/shake.webp'),
(277,'smash','https://train.wowteach.ru/media/prepare6/277/smash.webp'),
(278,'argument','https://train.wowteach.ru/media/prepare6/278/argument.webp'),
(278,'arrangement','https://train.wowteach.ru/media/prepare6/278/arrangement.webp'),
(278,'darkness','https://train.wowteach.ru/media/prepare6/278/darkness.webp'),
(278,'embarrassment','https://train.wowteach.ru/media/prepare6/278/embarrassment.webp'),
(278,'encouragement','https://train.wowteach.ru/media/prepare6/278/encouragement.webp'),
(278,'fitness','https://train.wowteach.ru/media/prepare6/278/fitness.webp'),
(278,'friendliness','https://train.wowteach.ru/media/prepare6/278/friendliness.webp'),
(278,'tiredness','https://train.wowteach.ru/media/prepare6/278/tiredness.webp'),
(278,'treatment','https://train.wowteach.ru/media/prepare6/278/treatment.webp'),
(278,'weakness','https://train.wowteach.ru/media/prepare6/278/weakness.webp'),
(279,'balance','https://train.wowteach.ru/media/prepare6/279/balance.webp'),
(279,'brake','https://train.wowteach.ru/media/prepare6/279/brake.webp'),
(279,'chase','https://train.wowteach.ru/media/prepare6/279/chase.webp'),
(279,'construct','https://train.wowteach.ru/media/prepare6/279/construct.webp'),
(279,'dive','https://train.wowteach.ru/media/prepare6/279/dive.webp'),
(279,'exchange','https://train.wowteach.ru/media/prepare6/279/exchange.webp'),
(279,'gather','https://train.wowteach.ru/media/prepare6/279/gather.webp'),
(279,'interact','https://train.wowteach.ru/media/prepare6/279/interact.webp'),
(279,'overtake','https://train.wowteach.ru/media/prepare6/279/overtake.webp'),
(279,'reverse','https://train.wowteach.ru/media/prepare6/279/reverse.webp'),
(279,'roll','https://train.wowteach.ru/media/prepare6/279/roll.webp'),
(279,'slide','https://train.wowteach.ru/media/prepare6/279/slide.webp'),
(279,'steer','https://train.wowteach.ru/media/prepare6/279/steer.webp'),
(280,'cool down','https://train.wowteach.ru/media/prepare6/280/cool_down.webp'),
(280,'cut (sth) out','https://train.wowteach.ru/media/prepare6/280/cut_sth_out.webp'),
(280,'eat out','https://train.wowteach.ru/media/prepare6/280/eat_out.webp'),
(280,'eat (sth) up','https://train.wowteach.ru/media/prepare6/280/eat_sth_up.webp'),
(280,'fill up on (sth)','https://train.wowteach.ru/media/prepare6/280/fill_up_on_sth.webp'),
(280,'go off','https://train.wowteach.ru/media/prepare6/280/go_off.webp'),
(280,'heat (sth) up','https://train.wowteach.ru/media/prepare6/280/heat_sth_up.webp'),
(280,'live on (sth)','https://train.wowteach.ru/media/prepare6/280/live_on_sth.webp'),
(281,'accidentally','https://train.wowteach.ru/media/prepare6/281/accidentally.webp'),
(281,'completely','https://train.wowteach.ru/media/prepare6/281/completely.webp'),
(281,'deeply','https://train.wowteach.ru/media/prepare6/281/deeply.webp'),
(281,'happily','https://train.wowteach.ru/media/prepare6/281/happily.webp'),
(281,'sensibly','https://train.wowteach.ru/media/prepare6/281/sensibly.webp'),
(281,'terribly','https://train.wowteach.ru/media/prepare6/281/terribly.webp'),
(282,'complex issue','https://train.wowteach.ru/media/prepare6/282/complex_issue.webp'),
(282,'major role','https://train.wowteach.ru/media/prepare6/282/major_role.webp'),
(282,'minor character','https://train.wowteach.ru/media/prepare6/282/minor_character.webp'),
(282,'moving novel','https://train.wowteach.ru/media/prepare6/282/moving_novel.webp'),
(282,'opening chapter','https://train.wowteach.ru/media/prepare6/282/opening_chapter.webp'),
(282,'predictable plot','https://train.wowteach.ru/media/prepare6/282/predictable_plot.webp'),
(282,'stunning illustration','https://train.wowteach.ru/media/prepare6/282/stunning_illustration.webp'),
(283,'addicted (to)','https://train.wowteach.ru/media/prepare6/283/addicted_to.webp'),
(283,'annoyed (by)','https://train.wowteach.ru/media/prepare6/283/annoyed_by.webp'),
(283,'disappointed (with)','https://train.wowteach.ru/media/prepare6/283/disappointed_with.webp'),
(283,'furious (with)','https://train.wowteach.ru/media/prepare6/283/furious_with.webp'),
(283,'keen (on)','https://train.wowteach.ru/media/prepare6/283/keen_on.webp'),
(283,'nervous (about)','https://train.wowteach.ru/media/prepare6/283/nervous_about.webp'),
(283,'suitable (for)','https://train.wowteach.ru/media/prepare6/283/suitable_for.webp'),
(283,'surprised (at)','https://train.wowteach.ru/media/prepare6/283/surprised_at.webp'),
(284,'chill out','https://train.wowteach.ru/media/prepare6/284/chill_out.webp'),
(284,'cool down','https://train.wowteach.ru/media/prepare6/284/cool_down.webp'),
(284,'cruise','https://train.wowteach.ru/media/prepare6/284/cruise.webp'),
(284,'get a tan','https://train.wowteach.ru/media/prepare6/284/get_a_tan.webp'),
(284,'go trekking','https://train.wowteach.ru/media/prepare6/284/go_trekking.webp'),
(284,'hire','https://train.wowteach.ru/media/prepare6/284/hire.webp'),
(284,'photograph','https://train.wowteach.ru/media/prepare6/284/photograph.webp'),
(284,'sign up (for sth)','https://train.wowteach.ru/media/prepare6/284/sign_up_for_sth.webp'),
(284,'socialise','https://train.wowteach.ru/media/prepare6/284/socialise.webp'),
(284,'stay up','https://train.wowteach.ru/media/prepare6/284/stay_up.webp'),
(284,'take a selfie','https://train.wowteach.ru/media/prepare6/284/take_a_selfie.webp'),
(284,'wander around','https://train.wowteach.ru/media/prepare6/284/wander_around.webp'),
(285,'check in','https://train.wowteach.ru/media/prepare6/285/check_in.webp'),
(285,'check out','https://train.wowteach.ru/media/prepare6/285/check_out.webp'),
(285,'get around','https://train.wowteach.ru/media/prepare6/285/get_around.webp'),
(285,'get away','https://train.wowteach.ru/media/prepare6/285/get_away.webp'),
(285,'look around','https://train.wowteach.ru/media/prepare4/212/look_around.webp'),
(285,'see (sb) off','https://train.wowteach.ru/media/prepare6/285/see_sb_off.webp'),
(285,'stay over','https://train.wowteach.ru/media/prepare6/285/stay_over.webp'),
(285,'stop over','https://train.wowteach.ru/media/prepare6/285/stop_over.webp'),
(285,'take (sb) around','https://train.wowteach.ru/media/prepare6/285/take_sb_around.webp'),
(287,'allowance','https://train.wowteach.ru/media/prepare6/287/allowance.webp'),
(287,'balance','https://train.wowteach.ru/media/prepare6/287/balance.webp'),
(287,'bargain','https://train.wowteach.ru/media/prepare6/287/bargain.webp'),
(287,'budget','https://train.wowteach.ru/media/prepare6/287/budget.webp'),
(287,'cashpoint','https://train.wowteach.ru/media/prepare6/287/cashpoint.webp'),
(287,'debit card','https://train.wowteach.ru/media/prepare6/287/debit_card.webp'),
(287,'financially independent','https://train.wowteach.ru/media/prepare6/287/financially_independent.webp'),
(287,'live on','https://train.wowteach.ru/media/prepare6/287/live_on.webp'),
(287,'pay off','https://train.wowteach.ru/media/prepare6/287/pay_off.webp'),
(287,'PIN','https://train.wowteach.ru/media/prepare6/287/PIN.webp'),
(287,'savings','https://train.wowteach.ru/media/prepare6/287/savings.webp'),
(287,'short of cash','https://train.wowteach.ru/media/prepare6/287/short_of_cash.webp'),
(287,'take out','https://train.wowteach.ru/media/prepare6/287/take_out.webp'),
(287,'wealthy','https://train.wowteach.ru/media/prepare6/287/wealthy.webp'),
(288,'clear up','https://train.wowteach.ru/media/prepare6/288/clear_up.webp'),
(288,'fix','https://train.wowteach.ru/media/prepare5/245/fix.webp'),
(288,'fold','https://train.wowteach.ru/media/prepare6/288/fold.webp'),
(288,'load','https://train.wowteach.ru/media/prepare6/288/load.webp'),
(288,'put (sth) away','https://train.wowteach.ru/media/prepare6/288/put_sth_away.webp'),
(288,'sort','https://train.wowteach.ru/media/prepare6/288/sort.webp'),
(288,'sweep','https://train.wowteach.ru/media/prepare6/288/sweep.webp'),
(288,'wash (sth) up','https://train.wowteach.ru/media/prepare6/288/wash_sth_up.webp'),
(288,'water','https://train.wowteach.ru/media/prepare6/288/water.webp'),
(288,'wipe','https://train.wowteach.ru/media/prepare6/288/wipe.webp'),
(290,'driverless car','https://train.wowteach.ru/media/prepare6/290/driverless_car.webp'),
(290,'drone','https://train.wowteach.ru/media/prepare6/290/drone.webp'),
(290,'fitness tracker','https://train.wowteach.ru/media/prepare6/290/fitness_tracker.webp'),
(290,'interactive whiteboard','https://train.wowteach.ru/media/prepare6/290/interactive_whiteboard.webp'),
(290,'portable charger','https://train.wowteach.ru/media/prepare6/290/portable_charger.webp'),
(290,'smart speaker','https://train.wowteach.ru/media/prepare6/290/smart_speaker.webp'),
(290,'smartwatch','https://train.wowteach.ru/media/prepare6/290/smartwatch.webp'),
(290,'video game console','https://train.wowteach.ru/media/prepare6/290/video_game_console.webp'),
(290,'virtual-reality headset','https://train.wowteach.ru/media/prepare6/290/virtual_reality_headset.webp'),
(290,'wireless headphones','https://train.wowteach.ru/media/prepare6/290/wireless_headphones.webp'),
(291,'affordable','https://train.wowteach.ru/media/prepare6/291/affordable.webp'),
(291,'careful','https://train.wowteach.ru/media/prepare4/197/careful.webp'),
(291,'careless','https://train.wowteach.ru/media/prepare4/197/careless.webp'),
(291,'creative','https://train.wowteach.ru/media/prepare6/291/creative.webp'),
(291,'dangerous','https://train.wowteach.ru/media/prepare6/291/dangerous.webp'),
(291,'endless','https://train.wowteach.ru/media/prepare6/291/endless.webp'),
(291,'enjoyable','https://train.wowteach.ru/media/prepare6/291/enjoyable.webp'),
(291,'environmental','https://train.wowteach.ru/media/prepare6/291/environmental.webp'),
(291,'famous','https://train.wowteach.ru/media/prepare6/291/famous.webp'),
(291,'faulty','https://train.wowteach.ru/media/prepare6/291/faulty.webp'),
(291,'impressive','https://train.wowteach.ru/media/prepare6/291/impressive.webp'),
(291,'innovative','https://train.wowteach.ru/media/prepare6/291/innovative.webp'),
(291,'interactive','https://train.wowteach.ru/media/prepare6/291/interactive.webp'),
(291,'mysterious','https://train.wowteach.ru/media/prepare6/291/mysterious.webp'),
(291,'original','https://train.wowteach.ru/media/prepare4/231/original.webp'),
(291,'profitable','https://train.wowteach.ru/media/prepare6/291/profitable.webp'),
(291,'reliable','https://train.wowteach.ru/media/prepare5/240/reliable.webp'),
(291,'seasonal','https://train.wowteach.ru/media/prepare6/291/seasonal.webp'),
(291,'spicy','https://train.wowteach.ru/media/prepare4/215/spicy.webp'),
(291,'thoughtful','https://train.wowteach.ru/media/prepare5/240/thoughtful.webp'),
(291,'thoughtless','https://train.wowteach.ru/media/prepare6/291/thoughtless.webp'),
(291,'traditional','https://train.wowteach.ru/media/prepare5/249/traditional.webp'),
(291,'useful','https://train.wowteach.ru/media/prepare6/291/useful.webp'),
(291,'useless','https://train.wowteach.ru/media/prepare6/291/useless.webp'),
(292,'bad-tempered','https://train.wowteach.ru/media/prepare6/292/bad_tempered.webp'),
(292,'easy-going','https://train.wowteach.ru/media/prepare5/240/easygoing.webp'),
(292,'generous','https://train.wowteach.ru/media/prepare6/292/generous.webp'),
(292,'impatient','https://train.wowteach.ru/media/prepare4/198/impatient.webp'),
(292,'insensitive','https://train.wowteach.ru/media/prepare6/292/insensitive.webp'),
(292,'mean','https://train.wowteach.ru/media/prepare6/292/mean.webp'),
(292,'optimistic','https://train.wowteach.ru/media/prepare6/292/optimistic.webp'),
(292,'patient','https://train.wowteach.ru/media/prepare6/292/patient.webp'),
(292,'pessimistic','https://train.wowteach.ru/media/prepare6/292/pessimistic.webp'),
(292,'reliable','https://train.wowteach.ru/media/prepare5/240/reliable.webp'),
(292,'thoughtful','https://train.wowteach.ru/media/prepare5/240/thoughtful.webp'),
(292,'thoughtless','https://train.wowteach.ru/media/prepare6/291/thoughtless.webp'),
(292,'unreliable','https://train.wowteach.ru/media/prepare5/239/unreliable.webp'),
(294,'confession','https://train.wowteach.ru/media/prepare6/294/confession.webp'),
(294,'confirmation','https://train.wowteach.ru/media/prepare6/294/confirmation.webp'),
(294,'criticism','https://train.wowteach.ru/media/prepare6/294/criticism.webp'),
(294,'hint','https://train.wowteach.ru/media/prepare6/294/hint.webp'),
(294,'prediction','https://train.wowteach.ru/media/prepare6/294/prediction.webp'),
(294,'proposal','https://train.wowteach.ru/media/prepare6/294/proposal.webp'),
(294,'response','https://train.wowteach.ru/media/prepare6/294/response.webp'),
(294,'rumour','https://train.wowteach.ru/media/prepare6/294/rumour.webp'),
(294,'statement','https://train.wowteach.ru/media/prepare6/294/statement.webp'),
(294,'threat','https://train.wowteach.ru/media/prepare6/294/threat.webp'),
(294,'update','https://train.wowteach.ru/media/prepare5/268/update.webp'),
(295,'admit','https://train.wowteach.ru/media/prepare6/295/admit.webp'),
(295,'argue','https://train.wowteach.ru/media/prepare6/295/argue.webp'),
(295,'beg','https://train.wowteach.ru/media/prepare6/295/beg.webp'),
(295,'claim','https://train.wowteach.ru/media/prepare6/275/claim.webp'),
(295,'confirm','https://train.wowteach.ru/media/prepare6/295/confirm.webp'),
(295,'declare','https://train.wowteach.ru/media/prepare6/295/declare.webp'),
(295,'emphasise','https://train.wowteach.ru/media/prepare6/295/emphasise.webp'),
(295,'encourage','https://train.wowteach.ru/media/prepare5/269/encourage.webp'),
(295,'propose','https://train.wowteach.ru/media/prepare6/295/propose.webp'),
(295,'remind','https://train.wowteach.ru/media/prepare5/265/remind.webp'),
(295,'reveal','https://train.wowteach.ru/media/prepare6/295/reveal.webp'),
(295,'tell','https://train.wowteach.ru/media/prepare6/295/tell.webp'),
(296,'be bitten','https://train.wowteach.ru/media/prepare6/296/be_bitten.webp'),
(296,'bump','https://train.wowteach.ru/media/prepare6/296/bump.webp'),
(296,'cut yourself','https://train.wowteach.ru/media/prepare5/246/cut.webp'),
(296,'have an allergic reaction','https://train.wowteach.ru/media/prepare6/296/have_an_allergic_reaction.webp'),
(296,'pass out','https://train.wowteach.ru/media/prepare6/296/pass_out.webp'),
(296,'slip','https://train.wowteach.ru/media/prepare6/296/slip.webp'),
(296,'swallow','https://train.wowteach.ru/media/prepare6/296/swallow.webp'),
(296,'trip over','https://train.wowteach.ru/media/prepare6/296/trip_over.webp'),
(296,'twist','https://train.wowteach.ru/media/prepare6/296/twist.webp'),
(297,'have a quarrel','https://train.wowteach.ru/media/prepare6/297/have_a_quarrel.webp'),
(297,'have the strength','https://train.wowteach.ru/media/prepare6/297/have_the_strength.webp'),
(297,'have a word','https://train.wowteach.ru/media/prepare6/297/have_a_word.webp'),
(297,'make an attempt','https://train.wowteach.ru/media/prepare6/297/make_an_attempt.webp'),
(297,'make fun of someone/sth','https://train.wowteach.ru/media/prepare6/297/make_fun_of_someone_sth.webp'),
(297,'make a promise','https://train.wowteach.ru/media/prepare6/297/make_a_promise.webp'),
(297,'give someone a hand','https://train.wowteach.ru/media/prepare6/297/give_someone_a_hand.webp'),
(297,'give someone a hug','https://train.wowteach.ru/media/prepare6/297/give_someone_a_hug.webp'),
(297,'give a talk','https://train.wowteach.ru/media/prepare6/297/give_a_talk.webp'),
(298,'avoid eye contact','https://train.wowteach.ru/media/prepare6/298/avoid_eye_contact.webp'),
(298,'bite your lip','https://train.wowteach.ru/media/prepare6/298/bite_your_lip.webp'),
(298,'blink','https://train.wowteach.ru/media/prepare5/246/blink.webp'),
(298,'blush','https://train.wowteach.ru/media/prepare6/298/blush.webp'),
(298,'lick your lips','https://train.wowteach.ru/media/prepare6/298/lick_your_lips.webp'),
(298,'nod your head','https://train.wowteach.ru/media/prepare6/298/nod_your_head.webp'),
(298,'rub your eyes','https://train.wowteach.ru/media/prepare6/298/rub_your_eyes.webp'),
(298,'shake your head','https://train.wowteach.ru/media/prepare6/298/shake_your_head.webp'),
(298,'stare','https://train.wowteach.ru/media/prepare6/298/stare.webp'),
(298,'yawn','https://train.wowteach.ru/media/prepare5/246/yawn.webp'),
(299,'carbon dioxide emissions','https://train.wowteach.ru/media/prepare6/299/carbon_dioxide_emissions.webp'),
(299,'carbon footprint','https://train.wowteach.ru/media/prepare6/299/carbon_footprint.webp'),
(299,'energy efficient','https://train.wowteach.ru/media/prepare6/299/energy_efficient.webp'),
(299,'environmentally friendly','https://train.wowteach.ru/media/prepare6/299/environmentally_friendly.webp'),
(299,'exhaust fumes','https://train.wowteach.ru/media/prepare6/299/exhaust_fumes.webp'),
(299,'fossil fuel','https://train.wowteach.ru/media/prepare6/299/fossil_fuel.webp'),
(299,'global warming','https://train.wowteach.ru/media/prepare6/299/global_warming.webp'),
(299,'greenhouse gas','https://train.wowteach.ru/media/prepare6/299/greenhouse_gas.webp'),
(299,'renewable','https://train.wowteach.ru/media/prepare6/299/renewable.webp'),
(299,'solar power','https://train.wowteach.ru/media/prepare6/299/solar_power.webp'),
(299,'wind power','https://train.wowteach.ru/media/prepare6/299/wind_power.webp'),
(301,'abstract','https://train.wowteach.ru/media/prepare6/301/abstract.webp'),
(301,'bizarre','https://train.wowteach.ru/media/prepare6/301/bizarre.webp'),
(301,'classic','https://train.wowteach.ru/media/prepare6/301/classic.webp'),
(301,'contemporary','https://train.wowteach.ru/media/prepare6/301/contemporary.webp'),
(301,'controversial','https://train.wowteach.ru/media/prepare6/301/controversial.webp'),
(301,'conventional','https://train.wowteach.ru/media/prepare6/301/conventional.webp'),
(301,'dramatic','https://train.wowteach.ru/media/prepare6/301/dramatic.webp'),
(301,'humorous','https://train.wowteach.ru/media/prepare6/301/humorous.webp'),
(301,'powerful','https://train.wowteach.ru/media/prepare6/301/powerful.webp'),
(301,'remarkable','https://train.wowteach.ru/media/prepare6/301/remarkable.webp'),
(301,'unique','https://train.wowteach.ru/media/prepare6/301/unique.webp'),
(302,'award','https://train.wowteach.ru/media/prepare6/302/award.webp'),
(302,'devote','https://train.wowteach.ru/media/prepare6/302/devote.webp'),
(302,'elect','https://train.wowteach.ru/media/prepare6/302/elect.webp'),
(302,'establish','https://train.wowteach.ru/media/prepare6/302/establish.webp'),
(302,'prohibit','https://train.wowteach.ru/media/prepare6/302/prohibit.webp'),
(302,'set','https://train.wowteach.ru/media/prepare6/302/set.webp'),
(303,'ambition','https://train.wowteach.ru/media/prepare6/303/ambition.webp'),
(303,'bravery','https://train.wowteach.ru/media/prepare6/303/bravery.webp'),
(303,'commitment','https://train.wowteach.ru/media/prepare6/303/commitment.webp'),
(303,'courage','https://train.wowteach.ru/media/prepare6/303/courage.webp'),
(303,'determination','https://train.wowteach.ru/media/prepare6/303/determination.webp'),
(303,'drive','https://train.wowteach.ru/media/prepare6/303/drive.webp'),
(303,'inspiration','https://train.wowteach.ru/media/prepare6/303/inspiration.webp'),
(303,'kindness','https://train.wowteach.ru/media/prepare6/303/kindness.webp'),
(303,'passion','https://train.wowteach.ru/media/prepare6/303/passion.webp'),
(303,'strength','https://train.wowteach.ru/media/prepare6/303/strength.webp'),
(304,'get away with','https://train.wowteach.ru/media/prepare6/304/get_away_with.webp'),
(304,'get back','https://train.wowteach.ru/media/prepare4/212/get_back.webp'),
(304,'get into','https://train.wowteach.ru/media/prepare5/270/get_into.webp'),
(304,'get on with','https://train.wowteach.ru/media/prepare6/304/get_on_with.webp'),
(304,'get out of','https://train.wowteach.ru/media/prepare6/304/get_out_of.webp'),
(304,'get round to','https://train.wowteach.ru/media/prepare6/304/get_round_to.webp'),
(304,'get through','https://train.wowteach.ru/media/prepare6/304/get_through.webp'),
(305,'burglar','https://train.wowteach.ru/media/prepare4/205/burglar.webp'),
(305,'burglary','https://train.wowteach.ru/media/prepare4/205/burglary.webp'),
(305,'burgle','https://train.wowteach.ru/media/prepare6/305/burgle.webp'),
(305,'charge (verb)','https://train.wowteach.ru/media/prepare6/305/charge_verb.webp'),
(305,'charge (noun)','https://train.wowteach.ru/media/prepare6/305/charge_noun.webp'),
(305,'commit','https://train.wowteach.ru/media/prepare6/305/commit.webp'),
(305,'court','https://train.wowteach.ru/media/prepare6/305/court.webp'),
(305,'deny','https://train.wowteach.ru/media/prepare6/275/deny.webp'),
(305,'hacker','https://train.wowteach.ru/media/prepare4/205/hacker.webp'),
(305,'investigate','https://train.wowteach.ru/media/prepare6/305/investigate.webp'),
(305,'judge','https://train.wowteach.ru/media/prepare6/305/judge.webp'),
(305,'jury','https://train.wowteach.ru/media/prepare6/305/jury.webp'),
(305,'make an arrest','https://train.wowteach.ru/media/prepare6/305/make_an_arrest.webp'),
(305,'prisoner','https://train.wowteach.ru/media/prepare6/305/prisoner.webp'),
(305,'release','https://train.wowteach.ru/media/prepare6/305/release.webp'),
(305,'sentence','https://train.wowteach.ru/media/prepare6/305/sentence.webp'),
(305,'statement','https://train.wowteach.ru/media/prepare6/294/statement.webp'),
(305,'suspect (noun)','https://train.wowteach.ru/media/prepare6/305/suspect_noun.webp'),
(305,'suspect (verb)','https://train.wowteach.ru/media/prepare6/305/suspect_verb.webp'),
(305,'theft','https://train.wowteach.ru/media/prepare4/205/theft.webp'),
(305,'victim','https://train.wowteach.ru/media/prepare6/305/victim.webp'),
(305,'witness','https://train.wowteach.ru/media/prepare6/305/witness.webp'),
(306,'disorganised','https://train.wowteach.ru/media/prepare6/306/disorganised.webp'),
(306,'impatient','https://train.wowteach.ru/media/prepare4/198/impatient.webp'),
(306,'impolite','https://train.wowteach.ru/media/prepare4/198/impolite.webp'),
(306,'inaccurate','https://train.wowteach.ru/media/prepare6/306/inaccurate.webp'),
(306,'invisible','https://train.wowteach.ru/media/prepare4/198/invisible.webp'),
(306,'unclear','https://train.wowteach.ru/media/prepare6/306/unclear.webp'),
(306,'unfair','https://train.wowteach.ru/media/prepare4/198/unfair.webp'),
(306,'unsafe','https://train.wowteach.ru/media/prepare6/306/unsafe.webp'),
(307,'barrier','https://train.wowteach.ru/media/prepare6/307/barrier.webp'),
(307,'basement','https://train.wowteach.ru/media/prepare6/307/basement.webp'),
(307,'bench','https://train.wowteach.ru/media/prepare6/307/bench.webp'),
(307,'chimney','https://train.wowteach.ru/media/prepare6/307/chimney.webp'),
(307,'community centre','https://train.wowteach.ru/media/prepare6/307/community_centre.webp'),
(307,'complex','https://train.wowteach.ru/media/prepare6/307/complex.webp'),
(307,'concrete','https://train.wowteach.ru/media/prepare6/307/concrete.webp'),
(307,'frame','https://train.wowteach.ru/media/prepare6/307/frame.webp'),
(307,'hut','https://train.wowteach.ru/media/prepare6/307/hut.webp'),
(307,'ladder','https://train.wowteach.ru/media/prepare6/307/ladder.webp'),
(307,'rug','https://train.wowteach.ru/media/prepare6/307/rug.webp'),
(307,'shed','https://train.wowteach.ru/media/prepare6/307/shed.webp'),
(307,'shelter','https://train.wowteach.ru/media/prepare6/307/shelter.webp'),
(307,'step','https://train.wowteach.ru/media/prepare6/307/step.webp'),
(307,'surface','https://train.wowteach.ru/media/prepare6/307/surface.webp')
) AS v(d,t,u)
WHERE w.deck_id=v.d AND w.term=v.t AND w.image_url IS NULL;
